### DISCUSSION TITLE
ip proxi cambia e non mi connetto più in remoto

### DISCUSSION THREAD

**Discussion by calz64** [indomus/forum#1008] [HUB: Home Assistant]
Sapete dirmi come mai ogni tanto trovo che non mi connetto più in remoto, e scopro che è cambiato l'ip proxi e devo mettere mano alla file configuration.yaml? Succede anche a voi, sono gli aggiornamenti?

**Comment by snakuzzo** [comment]
Prima però devi dire che hai fatto...che tipo di installazione hai...etc

Ragionaci un attimo...come può un aggiornamento di Core avere impatti sul cambio ip del tuo reverse proxy?!

Se hai installato Core su Docker l'ip del container del reverse proxy non dovrebbe cambiare.

Non so se su HassOS c'è qualcosa di particolare, ma puoi tranquillamente impostare la subnet al posto del singolo IP

**Comment by calz64** [comment]
Scusa, in effetto ho HassOS, però non ho capito i tuoi ragionamenti, ma per miei limiti. Impostare la subnet come può indirizzare correttamente la richiesta se cambia l'ip?

**Reply by snakuzzo** [reply]
Su core tu devi impostare i trusted proxy...che sono gli unici a cui HA risponderà correttamente.  Se tu imposti un solo ip (quello del reverse proxy) e poi ti cambia ogni volta, dovresti anche adeguare la configurazione di HA. Mettendo tutta la subnet invece gli fai "trustare" tutto quel range di io...e pure se ti cambia sempre ip, continuerà a funzionare.

**Reply by calz64** [reply]
OK. Grazie della spiegazione, leggo da guida //HTTP che questa è la config.
```
Proxy inversi
Quando si utilizza un proxy inverso, sarà necessario abilitare le opzioni use_x_forwarded_fore trusted_proxies. Le richieste da proxy inversi verranno bloccate se queste opzioni non sono impostate.

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.200      # Add the IP address of the proxy server
    - 172.30.33.0/24  # You may also provide the subnet mask**
```
la mia configurazione è questa
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.5
```
Quello che cambia è l'ultimo numero che diventa 3 poi 4 poi 5.
   - 172.30.33.5 è la subnet o è l'IP ??
