### DISCUSSION TITLE
Error while setting up rpi_gpio platform for switch

### DISCUSSION THREAD

**Discussion by ghost** [indomus/forum#1010] [HUB: Home Assistant]
Ho istallato Home Assistant Core 2021.11.0 su Docker su Raspberry 3 e come prima prova ho seguito la guida:
https://indomus.it/progetti/gestire-dinamicamente-una-ventola-tradizionale-su-raspberry-pi-via-home-assistant/
non si crea l'entità: switch.fan_shim

Credo si tratti di permessi all'accesso dei GPIO del raspberry.

Questo il log:
Logger: homeassistant.components.switch
Source: components/rpi_gpio/__init__.py:28
Integration: Interruttore (documentation, issues)
First occurred: 18:05:05 (1 occurrences)
Last logged: 18:05:05

Error while setting up rpi_gpio platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/rpi_gpio/switch.py", line 38, in setup_platform
    switches.append(RPiGPIOSwitch(name, port, invert_logic))
  File "/usr/src/homeassistant/homeassistant/components/rpi_gpio/switch.py", line 51, in __init__
    rpi_gpio.setup_output(self._port)
  File "/usr/src/homeassistant/homeassistant/components/rpi_gpio/__init__.py", line 28, in setup_output
    GPIO.setup(port, GPIO.OUT)
RuntimeError: No access to /dev/mem.  Try running as root!

Dopo vari giorni di ricerche non sono riuscito a risolvere da solo
Ho bisogno di aiuto

Grazie

**Comment by ghost** [comment]
Saluti
Nessuno utilizza i gpio del raspy ?

**Reply by snakuzzo** [reply]
https://github.com/home-assistant/core/issues/48068

**Comment by Juri78** [comment]
Ciao @mspeek!
Come hai risolto con questo problema?
Grazie

**Reply by snakuzzo** [reply]
Ho fatto ora una prova su un RPI3B.

Questo è il file docker-compose...

```yaml
version: '3.9'

services:
 
  homeassistant:
    hostname: homeassistant
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    privileged: true
    volumes:
    - ${PWD}/homeassistant:/config
    environment:
    - "TZ=Europe/Rome"
    network_mode: host
    restart: 'no'
```

Ho creato uno switch così nel `configuration.yaml`...

```yaml
switch:
  - platform: rpi_gpio
    ports:
      29: Fan Office
      31: Light Desk
```

e questo è il log del container (come vedi...nessun errore)...

```
pi@raspberrypi:~/prove $ docker logs -f homeassistant 
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```

E queste le entità in dashboard...

![log](https://user-images.githubusercontent.com/7205371/149822728-923152ff-1948-476d-9dad-22179ef8fa59.png)

Forse non avete impostato `privileged: true` nel compose

EDIT: Infatti ho fatto un'altra prova togliendo `privileged: true` e dà quell'errore. Quindi è lì che dovete correggere. Aggiungetelo e vedrete che andrà tutto bene
