### DISCUSSION TITLE
incremento velocita fan

### DISCUSSION THREAD

**Discussion by RtoRoc** [indomus/forum#1025] [HUB: Home Assistant]
Salve ragazzi....vorrei chiedervi una cosa: ho creato un automazzione utilizzando come trigger il singolo click di un pulsante tradfri, e come azione l'incremento del 50 % ad ogni clik della cappa, cliccando la prima volta va al 50% e se riclicco va al 100%.... solo che ora pensavo se fosse possibile fare in modo che con un altro clic torni a 0...insomma una cosa ciclica.... secondo voi e fattibile? in che modo?

ovviamente l'automazione che posto e fatta da GUI.... perdonatemi :) :) :)

```
alias: AAA CAPPA INCREMENTO VELOCITA'
description: ''
trigger:
  - platform: device
    domain: mqtt
    device_id: 128e8ced5b683ce93ef7710a6a1a5d26
    type: action
    subtype: 'on'
    discovery_id: 0x84fd27fffe19e5bf action_on
condition: []
action:
  - service: fan.increase_speed
    data:
      percentage_step: 50
    target:
      entity_id: fan.cappa
mode: single
```

**Comment by snakuzzo** [comment]
Ti posto di seguito solo la action (testata sulla mia istanza di test in una sequence di uno script)...

```yaml
  action:
    - choose:
      # Se è alla velocità massima -> spegne la ventola
      - conditions:
        - condition: state
          entity_id: fan.cappa
          attribute: percentage
          state: 100
        sequence:
        - service: fan.set_percentage
          data:
            entity_id: fan.cappa
            percentage: 0
      # Se è spenta -> la accende
      - conditions:
        - condition: state
          entity_id: fan.cappa
          state: "off"
        sequence:
        - service: fan.turn_on
          data:
            entity_id: fan.cappa
            percentage: 50
      default:
        - service: fan.increase_speed
          data:
            percentage_step: 50
            entity_id: fan.cappa
```

![doc_2021-11-11_22-51-22](https://user-images.githubusercontent.com/7205371/141374569-ce2a46e9-fb45-4032-9916-566d0e2ebe31.gif)
