### DISCUSSION TITLE
Valvole Termostatiche - Lovelace

### DISCUSSION THREAD

**Discussion by 2Max2Pax** [indomus/forum#1033] [HUB: Home Assistant]
Ciao a tutti,
tramite Pyscript sto realizzato script/automazione per la gestione delle valvole termostatiche (ne devo installare altre 10).
Vorrei realizzare una card in Lovelace che rappresenti le impostazioni delle valvole termostatiche. Al momento l'unico sistema "piacevole" che ho trovato e' quello di scrivere un file html che posso aprire con un button:
![valvoletermostatiche](https://user-images.githubusercontent.com/86773160/141449451-ee7216ff-77f3-4521-afc4-4982a999fcd0.jpg)

[valvoletermostatiche.html.txt](https://github.com/indomus/forum/files/7526637/valvoletermostatiche.html.txt)

i colori vanno dal giallo superchiaro per la temperatura minima al rosso intenso per la temperatura massima.
Andrebbe bene anche se la visualizzazione non fosse a colori.

Voglio creare al massimo un'entita' (che sia una variabile o sensore) per ogni valvola termostatica, "attaccandoci" tutti gli attributi necessari, per esempio:

```yaml
friendly_name: Termosifone sala
last_change: '2021-11-12 07:15:39.294106'
program:
  - days: Monday Tuesday Wednesday Thursday Friday
    - time: '00:00'
      temperature:'16'
    - time: '05:30'
      temperature:'21'
.
.
.
.
.
    - time: '15:00'
      temperature:'22.5'
    - time: '19:00'
      temperature:'16'

#   .... e cosi via
#  oppure piu semplicemente:

friendly_name: Termosifone sala
last_change: '2021-11-12 07:15:39.294106'
program:
  - days: Monday Tuesday Wednesday Thursday Friday
    time: '00:00 => 16'
    time: '05:30 => 21'

#   e cosi via	  
```
L'idea e' quella di non dovere rifare la card nel caso le impostazioni vengano cambiate/aggiunte/eliminate.
Andrebbe bene anche realizzare una card per ogni entita'(valvola).
Il problema e' che **non sono in grado di iterare gli attributi da visualizzare nella card come se fossero dei template o simili** e vorrei evitare di passare Lovelace a yaml.

Ho fatto dei test con:
[config-template-card](https://github.com/iantrich/config-template-card) anche in combinazione con [flex-table-card](https://github.com/custom-cards/flex-table-card) senza successo.
Esiste un modo?
