### DISCUSSION TITLE
Condition: OR

### DISCUSSION THREAD

**Discussion by calz64** [indomus/forum#1036] [HUB: Home Assistant]
Sapete dirmi perchè impostando una "condition: or" di questo tipo (come da guida):
```
condition:
  alias: ""
  condition: or
  conditions:
     - condition: state
       entity_id: "binary_sensor.shelly_finestra_sala_door"
       state: "on"
     - condition: state
       entity_id: "binary_sensor.shelly_finestra_lavanderia_door"
       state: "on"
```

mi messaggia questo errore:
Message malformed: Unexpected value for condition: '{'alias': '', 'condition': 'or', 'conditions': [{'condition': 'state', 'entity_id': 'binary_sensor.shelly_finestra_sala_door', 'state': 'on'}, {'condition': 'state', 'entity_id': 'binary_sensor.shelly_finestra_lavanderia_door', 'state': 'on'}]}'. Expected and, device, not, numeric_state, or, state, sun, template, time, trigger, zone @ data['condition'][0]
