### DISCUSSION TITLE
Come ottenere la somma di due valori

### DISCUSSION THREAD

**Discussion by elpiube** [indomus/forum#1044] [HUB: Home Assistant]
Ciao a tutti,
sono nuovo del forum e di Home Assistant.
Sono riuscito a configurare correttamente due shelly EM per la misura della produzione dei pannelli e del consumo dell'abitazione, ora vorrei calcolare il consumo reale al netto della produzione.
Cercando su google e su altri forum ho trovato che dovrei fare qualcosa come questo:
```
- platform: template
    sensors:
       strom_total:
        friendly_name: 'CalcoloConsumo'
        value_template: "{{ (states('sensor.shellyem_98cdac1f235d_channel_1_power')|float + states('sensor.shellyem_98cdac1f235d_channel_2_power')|float )}}"
        unit_of_measurement: W
		value_template: {{ (states('sensor.shellyem_98cdac1f235d_channel_1_power')|float + states('sensor.shellyem_98cdac1f235d_channel_2_power')|float)}}
```
Tuttavia non mi è chiaro dove si debba apportare tale modifica, ho provato a metterla nel configuration.yaml ma mi dice che è mal formattata.
Grazie a tutti per l'aiuto e mi scuso se la domanda è banale ma sono alle prime armi.
Ciao,
Massimo

**Comment by snakuzzo** [comment]
Ti pregherei di correggere il post utilizzando il markdown per il codice.
Grazie

**Reply by elpiube** [reply]
> Ti pregherei di correggere il post utilizzando il markdown per il codice. Grazie

Aggiornato! Sorry

**Reply by snakuzzo** [reply]
```yaml
sensor:

- platform: template
  sensors:
    strom_total:
      friendly_name: 'CalcoloConsumo'
      value_template: "{{ (states('sensor.shellyem_98cdac1f235d_channel_1_power') | float + states('sensor.shellyem_98cdac1f235d_channel_2_power') | float ) }}"
      unit_of_measurement: W
```

**Reply by elpiube** [reply]
Grazie per la risposta, ora il file configuration.yaml salva correttamente.
Tuttavia non riesco ad utilizzare il sensore appena creato, vorrei metterlo qui:
![image](https://user-images.githubusercontent.com/77537980/141856504-0430d44c-240c-4ce5-baa5-fbb4074c3583.png)
Ho provato aggiungendo il sensore dopo gli altri shelly, in questo modo (ho cambiato nome, ho provato il friendly_name) 
Grazie in anticipo per l'aiuto

```
title: Casa
views:
  - path: default_view
    title: Home
    cards:
      - title: Energy distribution today
        type: energy-distribution
        link_dashboard: true
      - type: entities
        entities:
          - entity: sensor.shellyem_98cdac1f235d_channel_1_power
          - entity: sensor.shellyem_98cdac1f235d_channel_1_energy_returned
          - entity: sensor.shellyem_98cdac1f235d_channel_2_power
          - entity: sensor.shellyem_98cdac1f235d_channel_2_energy
          - entity: sensor.strom_total
        title: Contatore
      - type: media-control
```

**Reply by snakuzzo** [reply]
Cercala sotto Configuration  > Entities
Se non c'è vuol dire che non l'hai creata

**Reply by elpiube** [reply]
Ciao purtroppo nelle entities non c'è ma questo è quanto ho nel file configuration.yaml, ho messo esattamente il codice che hai mi hai indicato. Ho riavviato sia i singoli componenti (core e supervisor) che anche completamente l'host.
Niente sulle entities non mi trovo CalcoloConsumo
```
title: Casa
views:
  - path: default_view
    title: Home
    cards:
      - title: Energy distribution today
        type: energy-distribution
        link_dashboard: true
      - type: entities
        entities:
          - entity: sensor.shellyem_98cdac1f235d_channel_1_power
          - entity: sensor.shellyem_98cdac1f235d_channel_1_energy_returned
          - entity: sensor.shellyem_98cdac1f235d_channel_2_power
          - entity: sensor.shellyem_98cdac1f235d_channel_2_energy
        title: Contatore
      - type: media-control
        entity: media_player.cucina
      - type: media-control
        entity: media_player.moretti_s_family_sala
      - type: entities
        entities:
          - person.massimo
        title: Test
      - type: weather-forecast
        entity: weather.casa
        show_forecast: false
      - type: entities
        entities:
          - sun.sun
        title: Sun
  - title: aaa
    path: aaa
    badges: []
    cards: []
sensor:
  - platform: template
    sensors:
      strom_total:
        friendly_name: CalcoloConsumo
        value_template: >-
          {{ (states('sensor.shellyem_98cdac1f235d_channel_1_power') | float +
          states('sensor.shellyem_98cdac1f235d_channel_2_power') | float ) }}
        unit_of_measurement: W
```

Mi pare che sia tutto corretto, fammi sapere che cosa potrei modificare e grazie mille per l'aiuto.

Ciao,
Massimo
