### DISCUSSION TITLE
info routine

### DISCUSSION THREAD

**Discussion by federico89mi** [indomus/forum#1046] [HUB: Home Assistant]
Buongiorno a tutti,
volevo chiedervi una dritta su un'idea che ho e che vorrei implementare nel mio home assistant, ma non so bene come farlo.
Vorrei che il mio google home mini, il lunedì e martedì ad una certa ora mi avvisasse (parlando) di ricordarmi di spostare la macchina.
Avete qualche idea su come impostare questa automazione? Mi sembra di capire che potrei farlo dalle automazioni da file editor. Forse potrei farlo tramite l'app di google home? Help me please

**Comment by snakuzzo** [comment]
Su Google Home puoi fare qualcosa con le routine di sicuro.
Se vuoi farlo con Home Assistant in un'automazione potresti usare

- trigger un [time trigger](https://www.home-assistant.io/docs/automation/trigger/#time-trigger)
- condition -> [time condition](https://www.home-assistant.io/docs/scripts/conditions/#time-condition) con solo **weekday**
- action -> service media 

Ti consiglio di lasciar perdere la GUI e fare le automazione scrivendole direttamente in YAML

Prova così...

```yaml
automation:

- id: avviso_spostamento_macchina
  alias: "Avviso Spostamento Macchina"
  trigger:
  - platform: time
    at: "21:00:00"
  condition:
  - condition: time
    weekday:
    - mon
    - tue
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.google_home_mini
      message: "Ricordati di spostare la macchina"
 ```
