### DISCUSSION TITLE
Zigbee e entità non create.

### DISCUSSION THREAD

**Discussion by pirata880** [indomus/forum#1055] [ZigBee, Z-Wave, Thread, Matter]
Ho  nel mio RPY3 Home Assistant hassio e CC2531 come gateway zigbee.
Ho eseguito correttamente il Pairing verso Xiaomi MiJia door & window contact sensor.
Stessa cosa con un sensor motion stessa famiglia. Dalla Gui di Zigbee2MQTT, i sensori rispondono perfettamente alle azioni, ma non mi si creano le entità in HA. D Ho flaggato “Update Home Assistant entity ID”.  Ma niente . Avete esperienze simili?  Grazie

**Comment by Scialla** [comment]
Hai installato un Broker MQTT? (mosquitto)
Hai abilitato l'auto discovery in HA?

**Reply by snakuzzo** [reply]
Se non avesse installato il broker, Zigbee2mqtt nemmeno partirebbe.
Da verificare la questione autodiscovery

**Reply by pirata880** [reply]
Si Broker e discovery sono Ok. Oggi ho accoppiato anche un sonoff BASICZBR3. E stesso comportamento, nessuna entità in HA. Ma perfettamente comandabile dall' interfaccia di Zigbee2mqtt. Mi sta venendo in mente che, nella Gui di Zigbee2mqtt, nel pannello "Setting", debba andare ad impostare qualcosa. Ma non trovo indicazioni in tal senso neanche nelle pagine della configurazione di Zigbee2mqtt.io. Ho capito solo che devo leggere il log sul broker MQTT quando i device pubblicano qualcosa, ma lo vedo dal "Registro" dell'addon Mqtt o sul file config di HA? Scusate la mia ignoranza.

**Reply by snakuzzo** [reply]
L'autodiscovery deve essere attivo sia sulla configurazione mqtt su ha che su zigbee2mqtt.

Esempio di configurazione mqtt nel `configuration.yaml` di Home Assistant dove è fondamentale avere `discovery: true`

```yaml
mqtt:
  broker: mosquitto #192.168.1.10
  port: 1883
  client_id: home-assistant
  username: !secret mosquitto_user
  password: !secret mosquitto_passwd
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true
```

Esempio di `configuration.yaml` di zigbee2mqtt dive è fondamentale avere `homeassistant: true` e dove volendo puoi forzare Il discovery_topic di default è `homeassistant`, quindi come puoi vedere farebbe scopa con quanto indicato nella configurazione MQTT su HA. Volendo puoi anche cambiarlo qui impostando `homeassistant_discovery_topic`, ma l'importante è che poi sia impostato allo stesso modo anche nel blocco di configurazione di MQTT su HA

```yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.10
  user: tuauser
  password: tuapassword
serial:
  port: tcp://192.168.1.37:23
```
