### DISCUSSION TITLE
automazioni in base ad un valore numerico

### DISCUSSION THREAD

**Discussion by GrupponeMissionario** [indomus/forum#1062] [GENERALE - Discussioni generiche]
Ciao a tutti, se gentilmente mi aiutate, non ne vengo fuori.
Devo monitorare un consumo, se la potenza è sopra i 60w tutto ok, se scende sotto i 60w dopo 1 minuto devo spegnere lo switch.
Se invece rimane sempre sotto i 60w non deve spegnersi.
Ho pensato quindi di fare un'automazione:
```
 - alias: automation_auto_off
   trigger:
     - platform: numeric_state
       entity_id: sensor.shellyswitch25_e8db84ac7e70_channel_2_power
       above: '60'
   action:
     - service: script.turn_on
       data:
        entity_id: script_auto_off
```

e uno script:
```
script_auto_off:
  sequence:
  - wait_for_trigger:
      - patform: numeric_state
        entity_id: sensor.shellyswitch25_e8db84ac7e70_channel_2_power
        below: '60'
  - delay: 00:01:00
  - type: turn.off
    device_id: ec0ae4043ed9aeebfdeb36c76f2c0988
    entity_id: switch.xyz
    domain: switch
```
In teoria appena la potenza sale sopra i 60w l'automazione fa partire uno script, che rimane in attesa che la potenza scenda sotto i 60w e spegne lo switch.
Ho cambiato 350 mila volte sintassi e comandi senza successo.

Grazie!

**Comment by snakuzzo** [comment]
Non so se ho capito male io, ma non ti conviene fare una sola automazione che scatti quando il valore scende sotto i 60 e rimane sotto i 60 per almeno un minuto dopodiché spegne lo switch

???

```yaml
automation:

- id: switch_auto_turn_off
  alias: "Switch auto turn off"
  trigger:
  - platform: numeric_state
    entity_id: sensor.shellyswitch25_e8db84ac7e70_channel_2_power
    below: 60
    for:
      minutes: 1
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.xyz
```
