### DISCUSSION TITLE
Semplice aiuto per una correzione offset su entità

### DISCUSSION THREAD

**Discussion by emiliopalmucci** [indomus/forum#1064] [HUB: Home Assistant]
Ciao a tutti,. Qui di seguito riporto le stringhe di programmazione del file di configurazione, prese da un esempio in  un articolo di indomus: " 

sensor:
  - platform: template
    sensors:
      sala_temperatura_offset:
        friendly_name: "Temperatura SALA offset"
        value_template: '{{ states("sensor.sala_temperatura")|float + 0.2 }}'
        unit_of_measurement: "°C"
        icon_template: mdi:thermometer

Il sensore dell'esempio si chiama:
sensor.temperatura_sala

Quello di cui vorrei fare la correzione io invece:
sensor.sonoff_a48001ae7e_temperature

Potete gentilmente spiegarmi come inserire il nome del mio sonoff nell'esempio?

Scusate la banalità, ma non vorrei far danni.

Grazie in anticipo

**Comment by snakuzzo** [comment]
Innanzi tutto devi usare il markdown quando pubblichi il codice...è scritto nel regolamento.
Poi non sono "stringhe di programmazione"...è semplicemente l'impostazione di un'entità di tipo template sensor.

```yaml
sensor:

- platform: template
  sensors:
    sensore_esempio:
      friendly_name: "Temperatura SALA offset"
      value_template: "{{ states('sensor.sonoff_a48001ae7e_temperature') | float + 0.2 }}"
      unit_of_measurement: "°C"
      icon_template: mdi:thermometer
```

P.S. Con queste cose non fai danni

**Comment by emiliopalmucci** [comment]
Grazie della risposta!

**Comment by emiliopalmucci** [comment]
La tua modifica ha funzionato perfettamente.  Vorrei chiederti un altro consiglio.  Perché nelle automazioni di H.A. se imposto il tipo di automazione, come valore numerico di un entità, e la imposto esempio, maggiore di 20, di un sensore di temperatura.  Il Trigger viene attivato solo se il valore si trova nel passaggio da minore a maggiore di 20.  Ma se volessi far attivare il Trigger, a ripetizione, continuamente come dovrei impostarlo?  All'inizio, c'è la possibilità di scegliere "singolo"; riavviare; parallelo.   Li ho provati tutti, ma senza risultato.  Puoi aiutarmi?   Grazie in anticipo

**Reply by emiliopalmucci** [reply]
```
id: '1637425174473'
alias: Spegnimento Pompa
description: ''
trigger:
  - platform: numeric_state
    entity_id: sensor.shelly1_40f520381c17_temperature_2
    above: '20'
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
condition: []
action:
  - type: turn_off
    device_id: 6402588f01d9f6289881d6dbe03ae80d
    entity_id: switch.shelly1pm_e8db84a11dad
    domain: switch
mode: restart
```

**Reply by snakuzzo** [reply]
Ma perché vorresti fare una cosa del genere? Non avrebbe proprio senso

**Reply by snakuzzo** [reply]
E comunque stai sbagliando proprio approccio.
Ti chiedo...spiega nel dettaglio l'esigenza specifica. Solo così forse ti si può dare un'indicazione adeguata

**Reply by emiliopalmucci** [reply]
La mia esigenza è aprire un contatto di un rele' shelly al raggiungimento di una temperatura (esempio 20°C)  questa automazione funziona, ma solo nel passaggio da 19 a 20.  Se ad esempio si trova a 21, e accendo il relè shelly, questo rimane acceso indisturbato.  A me, interesserebbe che sopra i 20°C , cmq mi andasse a spegnere il relè.  non so se mi sono spiegato

**Reply by snakuzzo** [reply]
No...non ti sei spiegato.
Se vuoi che una volta superati i 20°C si accenda, non vedo perché arrivato a 21*C debba spegnersi.
Sii più preciso...vuoi tenere la temperatura di un qualcosa che riscalda costante ?
Perché se è questo il caso hai proprio toppato. In tal caso devi creare un'entità di tipo [generic thermostat](https://www.home-assistant.io/integrations/generic_thermostat/) utilizzando le due entità che stai utilizzando nell'automazione (automazione che ovviamente dopo non ti servirà più)

**Reply by emiliopalmucci** [reply]
È per questo che pensavo che impostando il modo in restart, questa mi si resettasse ogni volta che la temperatura si trova a un valore superiore a 20°C.  Che sia, 21, o 25, cmq se il sensore sta sopra a 20, allora cmq deve avvenire l' automazione.   Solo che non è cosi

**Reply by snakuzzo** [reply]
Il restart serve a tutt'altra cosa, non c'entra niente con quello che serve a te.
Rispondi alla mia domanda nel precedente post per favore

**Reply by emiliopalmucci** [reply]
Si, scusa, nel mio caso, una volta superati i 20 °C deve aprirsi il relè.

**Reply by emiliopalmucci** [reply]
E si, dovrei tenere una temperatura costante.  Quindi sopra a 20 dovrebbe disattivarsi lo shelly

**Reply by emiliopalmucci** [reply]
Quindi dovrei creare una nuova entità, come  generic thermostat?  È difficile?

**Reply by emiliopalmucci** [reply]
`climate:
  - platform: generic_thermostat
    name:Riscaldamento
    heater: switch.riscaldamento_sala
    target_sensor: sensor.temperatura_sala
    min_temp: 15
    max_temp: 21
    ac_mode: False
    target_temp: 17
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 16`

**Reply by snakuzzo** [reply]
Tipo così...

```yaml
climate:

- platform: generic_thermostat
  name: "Generic Thermostat"
  heater: switch.shelly1pm_e8db84a11dad
  target_sensor: sensor.shelly1_40f520381c17_temperature_2
  min_temp: 10
  max_temp: 25
  ac_mode: false
  target_temp: 17
  min_cycle_duration:
    seconds: 30
  away_temp: 10
  precision: 1.0
```

Ma resta il fatto che devi ANDARE A LEGGERE la documentazione DALL'INIZIO ALLA FINE per capire anche come personalizzarla in base alle tue esigenze

**Reply by snakuzzo** [reply]
P.S. Ma riesci a postare il codice correttamente con il markdown ?

**Reply by emiliopalmucci** [reply]
Quindi, se scrivo questo codice in configuration.yiam e sostituisco il sensore generico, con il mio, e il relè con quello che ho io, avrò una nuova entità, che sarà il termostato?

**Reply by emiliopalmucci** [reply]
Perdonami! Ma non ho capito questo markdown!😅😅😅....ma non sono le virgolette?

**Reply by emiliopalmucci** [reply]
Posso darti gli ID del sensore di temperatura e quello del relè?  Cosi sono sicuro che funziona?

**Reply by emiliopalmucci** [reply]
Volevo ringraziarti ancora.  Ho copiato il tuo esempio, impostando i miei Id...e funziona!   Grazie ancora!   P.s...scusa per questo markdown, prossimamente mi aggiornero'.  grazie ancora

**Comment by emiliopalmucci** [comment]
Ciao, posso chiederti un altro consiglio?  Il tuo termostato che ho copiato va alla grande.  Se ne volessi uno simile, ma anziché per riscaldamento, mi servisse per aria condizionata sarebbe sufficiente nella riga A/C mode sostituire il false con true?   Grazie ancora!

**Reply by snakuzzo** [reply]
prova

**Comment by emiliopalmucci** [comment]
Ciao Diego, ho provato semplicemente a copiare il termostato con le istruzioni da te suggerite, cambiando il nome, il sensore, e lo switch ( in parole povere vorrei fare un altro termistato con altro sensore e altro switch). Alla verifica della configurazione l'unica cosa che non gli va bene è la prima riga, ovvero (climate.). Mi dice che è un doppione del termostato che ho sopra.   Quale altra funzione o servizio posso mettere al suo posto?    Grazie ancora in anticipo

**Reply by snakuzzo** [reply]
però ragazzi...un minimo di cultura vi serve...non potete andare avanti a caso sperando di non avere errori.
Devi capire un minimo la sintassi YAML...aiutati con un editor evoluto o un IDE o magari online con un linter per capire se stai sbagliando qualcosa a livello di sintassi.
E ci tengo a precisare che non siamo noi a dover insegnare queste cose!!!

Comunque...

```yaml
climate:

- platform: generic_thermostat
  name: "Generic Thermostat"
  ...
  ...

- platform: generic_thermostat
  name: "Generic Thermostat 2"
  ...
  ...
```

**Reply by emiliopalmucci** [reply]
Grazie!  Lo so, sono proprio ai primi passi....  Ho capito, (climate) è una specie di cartella,  dopo la quale si possono inserire più termostati.    Mi consiglieresti qualcosa?, tipo rivista, ebook che sia abbastanza comprensibile, e magari con esempi pratici? Grazie  ancora e buon week!!!!

**Reply by emiliopalmucci** [reply]
Ciao, posso chiederti come fare per far si che si riavvii il server ad esempio una volta al giorno a una determinata ora?

**Reply by snakuzzo** [reply]
Il server o solo la parte core di Home Assistant?

**Reply by snakuzzo** [reply]
Ma poi che tipo di installazione hai?

**Reply by emiliopalmucci** [reply]
Vorrei provare a far riavviare solo il server. Ho un Raspberry con H.A. come sistema.
Grazie in anticipo

**Reply by snakuzzo** [reply]
Premesso che questo che stai facendo non ha alcun senso e che se hai problemi particolari che richiedono il restart andrebbe indagato a fondo.
Se vuoi restartare tutto hassos (l'host per intenderci)...

```yaml
automation:

- id: daily_reboot_hassos
  alias: 'Daily Reboot HassOS'
  trigger:
  - platform: time
    at: '04:00:00'
  action:
  - service: hassio.host_reboot
```

Se vuoi restartare solo home assistant (core per intenderci)...

```yaml
automation:

- id: daily_reboot_core
  alias: 'Daily Reboot Core'
  trigger:
  - platform: time
    at: '04:00:00'
  action:
  - service: homeassistant.restart
```

**Reply by emiliopalmucci** [reply]
Grazie infinite, come al solito le mie lacune vengono subito colmate. Cmq, ho pensato di fare questo" restart" perché ho 2 sensori con l'applicazione tuya, i quali vanno per un paio di giorni, poi si piantano, restando "congelati".  Successivamente, riavvio il server e ripartono per altri 2 gg.  Ho pensato di farlo fare in automatico.  Secondo te, quale delle due forme è meno "invasiva" per il sistema?  Grazie infinite

**Reply by snakuzzo** [reply]
Allora al tuo posto penserei di ricaricare solo l'integrazione tuya e non hassos o core

**Reply by emiliopalmucci** [reply]
Magari.... però avrei sempre bisogno dei comandi giusti?  Puoi darmi anche quelli?

**Reply by emiliopalmucci** [reply]
Pensavo non si potesse riavviare solo il servizio tuya

**Reply by emiliopalmucci** [reply]
Scusami Diego, ho creato un'automazione, facendo riavviare solo HA a una determinata ora.  L'alternativa di far riavviare solo l'integrazione Tuya è complessa?  Secondo te, a lungo andare si creeranno problemi al sistema con dei riavvii giornalieri?    Grazie in anticipo

**Reply by snakuzzo** [reply]
Non c'è nessun problema con il riavvio di HA, ma di fatto puoi semplicemente riavviare solo l'integrazione. Devo spiegarti come fare, perché tocca recuperare l'ID dell'integrazione sotto storage e lanciare un determinato servizio con quell'id specifico.
Appena ho un attimo ti spiego

**Reply by emiliopalmucci** [reply]
Grazie,  permettimi però, dopo tutti questi problemi che mi hai risolto di offrirti un aperitivo.  Magari con PayPal....mi sembra il minimo! Grazie ancora

**Reply by snakuzzo** [reply]
Ma figurati...per così poco?! :D

**Reply by snakuzzo** [reply]
Allora...innanzi tutto devi recuperare l' `entry_id` relativo all'integrazione che vuoi ricaricare.
Per farlo ti basta aprire il file `/config/.storage/core.config_entries` e cercare quello che ti interessa...nel tuo caso dovrebbe essere "Tuya" e quindi avrai qualcosa del genere:

```
...
...
{
  "entry_id": "9dc7caae2e640a7dd8ea9ac831bffae0",
  "version": 1,
  "domain": "tuya",
...
...
```

A questo punto puoi creare la seguente automazione...

```yaml
- id: daily_reboot_tuya
  alias: 'Daily Reboot Tuya'
  trigger:
  - platform: time
    at: '04:00:00'
  action:
  - service: homeassistant.reload_config_entry
    data:
      entry_id: '9dc7caae2e640a7dd8ea9ac831bffae0'
```

Per provarla ovviamente puoi andare da GUI su Automazioni e "triggerarla" a mano.
