### DISCUSSION TITLE
Led "fioco" Smart Life

### DISCUSSION THREAD

**Discussion by nromagna** [indomus/forum#1072] [HUB: Home Assistant]
Ciao, vediamo un po' da dove partire... ho due strisce che creano un gruppo in HA, una Philips Hue ed una Shopped (comandata con Smart Life), avevo creato automazione che si accendessero assieme colore blu quando si accende TV. Ha sempre funzionato tutto ma dopo l'ultimo aggiornamento alla 21.11 la stricia Shopped NON si accende sul blu ma ahimè bianca.
Effettivamente la configurazione in HA mi permette di sceglere solo colore e luminosita e non l'intensita (?) di colore a differenza dell'app che ha sia luminosità che intensità.

![HA](https://user-images.githubusercontent.com/79841098/142841973-e02c7d77-5ebd-4c35-a502-54cc4680b639.jpg)

![Screenshot_20211122-101555](https://user-images.githubusercontent.com/79841098/142841979-618ceebb-675e-4b23-a319-8aa91c49d801.jpg)

Praticamente se nell'app porto al massimo la seconda barra la stricia torna blu!

Qualche idea su come risolvere problema?

```
alias: Divano ON
description: ''
trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: media_player.avr
condition:
  - condition: time
    after: '18:00'
    before: '06:00'
action:
  - service: light.turn_on
    data:
      color_name: blue
      brightness_pct: 100
    target:
      entity_id:
        - light.divano_dietro
        - light.divano_sotto
mode: single

```

Grazie.
