### DISCUSSION TITLE
Conta-ore

### DISCUSSION THREAD

**Discussion by vespadj** [indomus/forum#1078] [HUB: Home Assistant]
Come creare un "conta ore" su HA su una variabile 'on' / 'off' ?
Non c'è un aiutante specifico.
Si potrebbe fare in diversi modi, quindi chiedo a chi ci è già passato quale può essere il più efficace.

Un conta-ore potrebbe essere perpetuo, a reset manuale, o periodico (giornaliero, settimanale, ecc... ).

Ho provato con `hystory_stat `, un contaore giornaliero (da mezzanotte), ma mi da valori di cui capisco il nesso logico.
```yaml
sensor:
  - platform: history_stats
    name: "Contaore giornaliero"
    entity_id: binary_sensor.esempio_on_off
    state: "on"
    type: count
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
```
Forse va implementata la parte statitica:
[https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)
