### DISCUSSION TITLE
Controllo codice automazione

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#1105] [HUB: Home Assistant]
Qualcuno per favore mi controlla il codice dell'automazione che segue? 
L'intenzione è che _se **uno o più **  dei device descritti fosse acceso alle ore 2  venisse spento_ indipendentemente dallo stato di ciascun degli altri device. Lo so che si potrebbero semplicemente spegnere tutti gli switch alle ore due, ma ad esempio di gardelight non conosco lo stato se non attreverso uno switch virtuale perchè il segnale di accensione è pilotato da uno shelly 1 attraverso un telecomando che comanda un relè.
```yaml
- id: '1619974364714'
  alias: Verifica ore 2  #luci giardino, computer e altre luci
  description: Se alle 2 le luci in giardino sono ancora accese, le spegne
  trigger:
  - platform: time
    at: 02:00:00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.gardenlight
        state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: switch.shellyplug_s_9d8caf
            state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: switch.corsair
            state: 'on'
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.luci_giardino
      - switch.gardenlight
      - switch.shellyplug_s_9d8caf
      - switch.corsair
  mode: single
```

**Comment by snakuzzo** [comment]
IL MARKDOWN !!!!
Correggi altrimenti cancello il topic

**Reply by Dregi56** [reply]
Ciao, ho usato <> dalla barra menù, perchè non ricordavo i tasti per ''' ... come li riproduco? Grazie

**Reply by Dregi56** [reply]
spero vada bene ora.

**Reply by Dregi56** [reply]
Snakuzzo, ti ringrazio per la gentilezza.

**Reply by snakuzzo** [reply]
non va bene
Devi usare i tre backtick prima e tre dopo... non uno.
Ti ho corretto io il post...vai in edit e guarda come si fa. La prossima volta cancello direttamente il topic

**Comment by snakuzzo** [comment]
Le condition sono tutte sbagliate...ma comunque non ti servono a niente.
Ti basta semplicemente far spegnere tutto ad una determinata ora...tanto se è già spento rimane spento

```yaml
- id: spegni_luci_giardino
  alias: "Spegni luci giardino"
  description: Spegne le luci alle 2 di notte
  trigger:
  - platform: time
    at: '02:00:00'
  action:
  - service: switch.turn_off
    data:
      entity_id:
      - switch.luci_giardino
      - switch.gardenlight
      - switch.shellyplug_s_9d8caf
      - switch.corsair
```

**Reply by Dregi56** [reply]
Ringrazio sempre quando qualcuno risponde ed apprezzo i suggerimenti ed i gesti di cortesia. :) 
Per cui grazie per tutto.
Ma hai letto bene l'introduzione al mio topic? 
L'ho ritrovato: ALT + 96 è l ASCII per quel benedetto backtick. Lo scrivo a beneficio di tutti.

**Reply by snakuzzo** [reply]
Ok...ma non ho capito perché ti interesserebbe sapere prima lo stato se poi comunque devi mettere lo switch virtuale a `'off'`

**Reply by Dregi56** [reply]
Lo switch virtuale mi serve per conoscere lo stato (acceso-spento) in quanto con un sistema che considero provvisorio, ho collegato uno shelly 1 ad un telecomando che guida un relè (acceso spento). una volta cliccato, se ri-clicco lo spengo, per questo dando il primo impulso (accensione) accendo anche uno switch virtuale per _ritrovare lo status_  successivamente, altrimenti alle ore due, se fosse spento, un clic da parte del telecomando lo accenderebbe facendo esattamente il contrario di ciò che mi serve.

**Reply by snakuzzo** [reply]
Ah ok...
tornando quindi a quello che hai scritto nel primo post, mi pare di capire che questa cosa riguardi solo `gardenlight`. Giusto?
Se così fosse, potresti provare così...

```yaml
- id: spegni_luci_giardino
  alias: "Spegni luci giardino"
  description: Spegne le luci alle 2 di notte
  # L'automazione scatta alle ore 02:00
  trigger:
  - platform: time
    at: '02:00:00'
  action:
  # spegne le luci di cui conosco lo stato...
  - service: switch.turn_off
    data:
      entity_id:
      - switch.luci_giardino
      - switch.shellyplug_s_9d8caf
      - switch.corsair
  # ...infine, se lo gardenlight è accesa...
  - condition: state
    entity_id: switch.gardenlight
    state: 'on'
  # ...spegne gardenlight
  - service: switch.turn_off
    data:
      entity_id:
      - switch.gardenlight
```
