### DISCUSSION TITLE
NUT - monitorare UPS remoto (non locale)

### DISCUSSION THREAD

**Discussion by cicciociccio333** [indomus/forum#1107] [HUB: Home Assistant]
Buonasera, ho una domanda su NUT, il gestore degli UPS. 
La mia configurazione attuale è:
- Home Assistant OS 6.6 installato in vm su Proxmox
- Versione Core 2021.11.5
- Versione supervisor supervisor-2021.10.8
- Addon NUT (a0d7b954_nut) configurato così:
 
```
devices:
  - name: UPS_APC
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: 'false'
users:
  - username: user1
    password: pass1
    instcmds:
      - all
    actions: []
  - username: user2 #utente definito sul raspberry
    password: pass2
    instcmds:
      - all
    actions: []
```

Ho un ups (APC) collegato via cavo all'host che l'addon vede correttamente.
Ho aggiunto poi l'integrazione NUT per visualizzare i dati dell'ups in ha. 
Fin qui tutto ok. 

La mia esigenza è riuscire in qualche modo a integrare in HA anche un secondo UPS (un tecnoware) collegato in garage ad un raspberry pi con Raspbian. Sono tutti nella stessa LAN.
In locale sul Raspi ho installato NUT e rileva i dati del secondo ups. 
Al momento è configurato come mode: netserver lasciando le altre impostazioni di default. Lo user2 è stato definito come "upsmon" sul nut del raspberry.
Non ci sono firewall tra il raspberry e l'host dove gira HA.

Quando in HA provo ad aggiungere una seconda integrazione Nut inserendo IP, porta, user2 e pass2 del raspberry ma dà un errore generico che non mi fa accedere 

![img1](https://user-images.githubusercontent.com/1780407/143483250-b953a904-8788-44b6-8793-2a7a371e3ad0.JPG).

L'unico msg nei log che vedo è:
`2021-11-25 18:26:45 ERROR (SyncWorker_3) [homeassistant.components.nut] Failure getting NUT ups alias, Socket error.`

Qualche idea?
