### DISCUSSION TITLE
Script con più blocchi

### DISCUSSION THREAD

**Discussion by ocimin** [indomus/forum#1116] [HUB: Home Assistant]
Salve a tutti!
Leggendo la documentazione sulla sintassi degli script, non riesco a capire se è possibile chiudere le diverse strutture di controllo, come ad esempio le "condition" o il ciclo while. E' possibile, ad esempio, far continuare uno script a seguito del controllo di una condizione a prescindere da quale sia il risultato del controllo?
Grazie a chi mi saprà dare una delucidazione a riguardo.
Saluti.

Ocimin

**Comment by xyzmauro** [comment]
Ciao, non ho ben capito cosa intendi,però uno script non è altro che la parte action di un’automazione per cui potresti usare una [choose](https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions) come fosse un if/then/else oppure come nell’ultimo esempio una if/if
Spero di aver compreso la tua richiesta 😅

**Reply by ocimin** [reply]
Mi spiego meglio. Normalmente le strutture di controllo hanno dei marcatori che le chiudono, nel caso di if/then/else hai per dire un "end if" che fa terminare il blocco di istruzioni e che permette di proseguire lo script. Facciamo ad esempio che voglio abbassare la luce del tavolo a 10 nel caso sia accesa, poi aspettare comunque 10 secondi e infine accendere la luce del divano. Se scrivo questo:

```
  - condition: template
     value_template: '{{ is_state(''light.tavolo'', ''on'') }}'
  - service: light.turn_on
    data:
      entity_id: light.tavolo
      brightness_pct: 10
  - delay: 00:00:10  
  - service: light.turn_on
     entity_id: light.divano
```

e la luce del tavolo non è accesa, si blocca tutto perchè non so come dirgli che la condition interessa solo la prima istruzione e non anche le seguenti. E con la choose mi pare di avere lo stesso problema.
