### DISCUSSION TITLE
configuration.yaml

### DISCUSSION THREAD

**Discussion by genioperso** [indomus/forum#1121] [HUB: Home Assistant]
Stò provando a inserire il componente Climate con un termostato generico, seguendo l'articolo provo a inserire l seguente codice in configaration.yaml:

```
climate:
  - platform: generic_thermostat
    name:Cameretta
    heater: switch.cameretta_3
    target_sensor: sensor.cameretta_temperature
    min_temp: 15
    max_temp: 23
    ac_mode: False
    target_temp: 20.5
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:      
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 10
```

ma mi ritorna un errore, precisamente:

can not read a block mapping entry; a multiline key may not be an implicit key at line 161, column 11:
        heater: switch.cameretta_3
              ^
la riga interessata è:     heater: switch.cameretta_3

Potete aiutarmi a capire dove sbaglio?

Grazie in anticipo.
