### DISCUSSION TITLE
far leggere json attributes su un rest sensor

### DISCUSSION THREAD

**Discussion by kimuss** [indomus/forum#1126] [GENERALE - Discussioni generiche]
salve a tutti, 
sto creando un sensore rest ma non riesco a far creare i json attributes che mi interessano..
il codice json che mi rilascia la resource è questo:
```
{"result":[{"reg":1,"val":10,"mod":5},{"reg":2,"val":190,"mod":5},{"reg":4,"val":192,"mod":5},{"reg":6,"val":0,"mod":5},{"reg":8,"val":0,"mod":5}]}
```

a me interessa estrapolare solo i "val"..
quindi... se io metto nel sensor:
```
json_attributes:
  - result
```

ovviamente mi fa un lista anche di reg e mod... quindi in realtà ci posso arrivare creando dei sensor template che puntano solo al val che mi interessa... ma volevo tenere pulito gli attributi del rest.

ho provato anche:
`json_attributes_path: "$.result"` o `$.result[0,1,2].val` che nel json path online evaluator funziona... 
però boh non ho capito cosa sbaglio
spero sia riuscito a spiegarmi
grazie

**Comment by snakuzzo** [comment]
Per com'è fatto mi sa che avrai comunque 1 sensore per ogni elemento di quella lista...

```yaml
sensor:

- platform: rest
  name: Example1
  resource: http://192.168.1.10:8124/local/json/prova.json
  value_template: "{{ value_json.result[0].reg }}"
  json_attributes_path: "$.[0]"
  json_attributes:
  - val
  
- platform: rest
  name: Example2
  resource: http://192.168.1.10:8124/local/json/prova.json
  value_template: "{{ value_json.result[1].reg }}"
  json_attributes_path: "$.[1]"
  json_attributes:
  - val

- platform: rest
  name: Example3
  resource: http://192.168.1.10:8124/local/json/prova.json
  value_template: "{{ value_json.result[2].reg }}"
  json_attributes_path: "$.[2]"
  json_attributes:
  - val

- platform: rest
  name: Example4
  resource: http://192.168.1.10:8124/local/json/prova.json
  value_template: "{{ value_json.result[3].reg }}"
  json_attributes_path: "$.[3]"
  json_attributes:
  - val

- platform: rest
  name: Example5
  resource: http://192.168.1.10:8124/local/json/prova.json
  value_template: "{{ value_json.result[4].reg }}"
  json_attributes_path: "$.[4]"
  json_attributes:
  - val
```

**Reply by kimuss** [reply]
ciao die grazie della risposta,
però così farei 5 GET (moltiplicato per altri 4 sensor rest)  che quel device non mi regge.. preferisco un unico GET e poi creare vari sensor template se non posso accorpare gli attributi..

quindi il problema è che json_attributes_path non prende.. dei multi path...

perché se io metto:
```
    json_attributes_path: $.result[0]
    json_attributes:
      - val
```
questo mi restituisce sugli attr solo quel val (giusto)

però perché questo altro non dovrebbe funzionare:
```
    json_attributes_path: $.result[*]
    json_attributes:
      - val
```
??
o anche:
```
    json_attributes_path: $.result[0,1,2]
    json_attributes:
      - val
```
sull'evaluator funziona

**Reply by snakuzzo** [reply]
Di quale evaluator parli ?
Comunque sì, è più performante utilizzare un sensor rest (quindi con una sola chiamata) e poi n sensor template.

**Reply by kimuss** [reply]
jsonpath online evaluator
a codice dato, in base a cosa scrivi ti restituisce il risultato, lo uso per vedere se faccio errori
ma comunque anche nel link ufficiale descritto nella spiegazione del json_attributes_path, c'è il link che riporta questi JSONPath... non so se posso mettere il link

**Reply by snakuzzo** [reply]
Non c'è bisogno di link. La documentazione l'abbiamo letta entrambi, ma devi comunque capire che quell'evaluator non è Home Assistant.
Nel tuo caso usando `$.result[0,1,2]` puoi facilmente vedere che ottieni n JSON diversi.
Su HA questo non puoi farlo, o almeno non puoi farlo con `json_attributes_path`

**Reply by snakuzzo** [reply]
Ma in alternativa...fatti uno script shell o uno script python ad esempio...e su HA ti crei un command line sensor. Così ti generi il JSON come ti pare

**Reply by kimuss** [reply]
> Non c'è bisogno di link. La documentazione l'abbiamo letta entrambi, ma devi comunque capire che quell'evaluator non è Home Assistant. Nel tuo caso usando `$.result[0,1,2]` puoi facilmente vedere che ottieni n JSON diversi. Su HA questo non puoi farlo, o almeno non puoi farlo con `json_attributes_path`

^^ ci mancherebbe, non mettevo in dubbio, avevo solo paura di non essermi spiegato bene, anyway.. capito, immaginavo che andavo a finire sugli script.. grazie mille, almeno so che con il rest non posso avanzare

**Reply by snakuzzo** [reply]
Poi magari ci sono modi diversi. Potresti usare un for nel template per farti restituire un `value` come ti pare.
Ma comunque la strada degli n sensor template secondo me non è male...e non "sporchi" nulla secondo me.

**Comment by kimuss** [comment]
ma invece una cosa del genere??

```
rest:
  - authentication: basic
    resource: http://192.168.1.63/api/xxxxxxx
    sensor:
      - name: "val 1"
        value_template: "{{ value_json.result[0].val }}"
      - name: "val 2"
        value_template: "{{ value_json.result[1].val }}"
      - name: "val 3"
        value_template: "{{ value_json.result[2].val }}"
```

mi sembra che funzioni ma fa una **sola** chiamata? (misa manco mi serve `authentication: basic`)
adesso l'ho buttato al volo dentro configuration, penso posso mettere un `rest: !include restsens.yaml` e fare uno yaml a parte vero?
