### DISCUSSION TITLE
restful e template

### DISCUSSION THREAD

**Discussion by kimuss** [indomus/forum#1141] [HUB: Home Assistant]
salve a tutti,
stavo provando a compilare un URL su un rest_command ma non riesco .. penso sia in realtà un problema banale.. scusate... non ho proprio capito la guida ufficiale.. quindi chiedo qui

allora questo è l'url del rest_command: 

`  url: 'http://192.168.1.63/api/command.php?xxxxxxxxxxxxxxx_cmd=[{"mod":5,"reg":1,"val":10}]'`

io vorrei sostituire il 10 di val con un valore dinamico ricavato da questo input_number:

`
{{ states('input_number.fan_studio') | int }}
`
cercando in giro avevo capito che basta sostituirlo... ma ovviamente non riesco
grazie del supporto

**Comment by snakuzzo** [comment]
Io ho fatto così per un `rest_command` per le Tado°...

`url: https://my.tado.com/api/v2/devices/{{ states('input_text.tado_cameretta_id') }}/temperatureOffset`

**Comment by kimuss** [comment]
sbagliavo la forma, così la prende:
```
{{ states.input_number.fan_studio.state }}
```
penso che comunque dovrei usare i payload per "comporre" l'url... ma dalla guida ufficiale proprio non la capisco come si compone

**Reply by snakuzzo** [reply]
Non ho capito che intendi

**Reply by kimuss** [reply]
da quello che ho capito, posso "scrivere " l' url dandogli una serie di variabili che cambiano, e a seconda delle variabili HA lo compila.

esempio su questo url:
`url: 'http://192.168.1.23/api/command.php?key=1234567_cmd=[{"mod":5,"reg":1,"val":10}]'`

invece di scrivere tutto a mano, non ho capito come (grosse lacune sulle basi di scripting :( ) attraverso `payload:` posso dargli che ne so IP variabile, i valori del `cmd=`  in base a un sensore, la parte di ` key=` magari attraverso un altro valore registrato.. cose così..

sbaglio?

**Reply by snakuzzo** [reply]
La documentazione è tutta [QUI](https://www.home-assistant.io/integrations/rest_command/)
Solitamente il payload viene passato in base al tipo di request che fai.
Se fai una chiamata in GET, i parametri li passi in querystring
Se fai una chiamata in POST,PUT, o altro... i parametri li passi nel payload.

Per farti un esempio...io ho fatto dei rest command per forzare l'offset che prevedono il metodo PUT. In tal caso gli passo un payload...

```yaml
rest_command:

  tado_camara_offset_on:
    url: https://my.tado.com/api/v2/devices/{{ states('input_text.tado_camera_id') }}/temperatureOffset
    method: PUT
    headers:
      authorization: "Bearer {{ state_attr('sensor.tado_auth','access_token') }}"
      content-type: "application/json"
    payload: '{"celsius":"-9.9"}'
    verify_ssl: true
```

P.S. Poi non so sinceramente se, facendo una chiamata in GET (come quella che hai postato tu), passando i parametri nel payload al posto di passarli in querystring nella url funzioni lo stesso...ma non mi pare
