### DISCUSSION TITLE
configurazione tasmota switch e automazioni

### DISCUSSION THREAD

**Discussion by Virgilio123** [indomus/forum#1143] [GENERALE - Discussioni generiche]
Buongiorno a Tutti e grazie per la disponibilità a fornire supporto.

ho una schedina esp12 con installato Tasmota ultima versione per display
ho collegato un display, una sensore di temperatura, un relè e un interruttore sopra un piedino.
funziona tutto bene.
ho integrato il sensore di temperatura e il display con un ambiente "Climate" e funziona.

Non riesco a far funzionare l'interruttore sul piedino!!!
infatti ho creato una entità binary_sensor:
```
- platform: mqtt
  name: Chiudi_Luci
  state_topic: "stat/display/RESULT"
  availability_topic: "tele/display/LWT"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: light
  value_template: "{{ value_json.Switch1.Action }}"

```

Sembra funzionare, appare nel sistema e l'icona segue le variazioni ON e OFF , **ma non riesco a creare una automazione che al variare dello stato del interruttore faccia qualcosa tipo accendere una luce**

**Comment by snakuzzo** [comment]
Per favore, indenta bene usando il markdown correttamente...così non si capisce niente

**Reply by Virgilio123** [reply]
scusa non avevo fatto caso alla formattazione del codice

**Reply by snakuzzo** [reply]
Di seguito un esempio sfruttando il trigger objdect da cui evinci il nuovo stato del binary ed in base a quello fai accendere o spegnere un altro switch

```yaml
automation:

- id: prova
  alias: prova
  trigger:
    platform: state
    entity_id: binary_sensor.chiudi_luci
  action:
  - service: >
      {% if trigger.to_state.state == 'on' %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    data:
      entity_id: switch.pippo
```
