### DISCUSSION TITLE
Verifica su configurazione recorder

### DISCUSSION THREAD

**Discussion by directy01** [indomus/forum#1161] [HUB: Home Assistant]
Ciao, il mio database è diventato troppo grande quindi, per porre rimedio,  ho letto i vari documenti online ed ho provato ad inserire quanto segue nel file di configurazione per tenere solo di dati degli ultimi 60 giorni. Dopo più di 24 ore però non vedo ancora cambiamenti e mi viene il dubbio di aver sbagliato qualcosa oppure di aver dimenticato di aggiungere qualche stringa nel file... 
manca qualcosa?

```
recorder:
  purge_interval: 1          # Esegue l'operazione ogni giorno
  purge_keep_days: 60  # Conserva i dati per 60 giorni
  commit_interval: 60    # invia i dati al DB ogni 60 secondi

  include:
    domains:
    - sensor
    - binary_sensor
    - light
    - switch

  exclude:
    entities:
    - sensor.shelly
    - sensor.shellyem # escludi es.  sensor.shellyem_98cdac1e46a9_channel_1_energy
    - sensor.date
    - sensor.time
    - sensor.workday
    - sun.sun
 ```
