### DISCUSSION TITLE
Automazione notifica telegram template stato

### DISCUSSION THREAD

**Discussion by DigoGibin** [indomus/forum#1188] [HUB: Home Assistant]
Buonasera a tutti, sto riscontrando un problema con le notifiche via telegram in automazione
Ho creato una semplice automazione per inviare una notifica a Diego sullo stato dell'allarme e un messaggio telegram verso il gruppo famiglia 

```
 - alias: comunicazione stato antifurto
    trigger:
      platform: state
      entity_id: alarm_control_panel.home
      to: ~
    condition: []
    action:
      - service: notify.mobile_app_smartphone_diego
        data:
          message: "Stato attuale allarme: {{ states.alarm_control_panel.home.state }}."
      - service: notify.famiglia
        data:
          message: "Stato attuale allarme: {{ states.alarm_control_panel.home.state }}."

``` 

il problema che dei 3 possibili stati : armed_home , armed_away , disarmed
l'automazione invia correttamente come notifica a Diego ogni cambio stato con il relativo valore
invece come messaggio telegram con lo stato disarmed invia il messaggio corretto con gli altri 2 stati non lo invia nemmeno 

qualcuno sa il perchè o ha voglia di aiutarmi a trovare una soluzione?

Grazie

**Comment by snakuzzo** [comment]
Per il codice devi usare il markdown...per favore correggi il post

**Reply by DigoGibin** [reply]
corretto scusa pensavo di averlo fatto correttamente

**Comment by xyzmauro** [comment]
Ma su telegram non ti manda proprio il messaggio o ti scrive solo **Stato attuale allarme:** senza lo stato? perchè se così fosse potrebbero essere le impostazioni dei tempi del alarm_control_panel
Fai una prova, tra i 2 notify, metti un delay di tipo 10" e vedi che fa

**Reply by DigoGibin** [reply]
Ciao, grazie per l'interesse. Ho scoperto che però il problema non era dovuto all'automazione ma ad una errata configurazione dei parametri alarm in configurazione ora le notifiche arrivano entrambi sempre e puntuali.

**Reply by Miorivarone** [reply]
Ciao, mi puoi dire come hai risolto? Vorrei ricevere un messaggio su telegram quando armo o disarmo.
Grazie

**Reply by DigoGibin** [reply]
Ciao Miorivarone, il mio problema era dovuto a un errata gestione dei tempi di sulla configurazione del alarm panel.

Se ti può essere di aiuto ti allego la configurazione del mio pannello

```
# PANNELLO ANTIFURTO
alarm_control_panel:
  - platform: manual
    name: INIM
    code: " **** "
    code_arm_required: false
    arming_time: 1
    delay_time: 1
    trigger_time: 1
    disarmed:
      trigger_time: 1
    armed_home:
      arming_time: 1
      delay_time: 1

```
Naturalmente alla voce code: sostituisci **** con il tuo pin , il nome metti pure quello che vuoi.
Inoltre io non uso inserimenti ritardati, diciamo tutto immediato infatti ho tenuto un tempo minimo di 1 secondo poichè con zero avevo problemi.
Con questa configurazione l'inserimento del pin è solo per il disarmo se lo vuoi inserire sempre metti a true la voce code_arm_required

Ti allego anche l'automazione delle notifiche telegram

```
# CENSIMENTO STATO ANTIFURTO

# notifica bot telegram
- alias: comunicazione stato antifurto
  trigger:
    platform: state
    entity_id: alarm_control_panel.inim
    to: ~
  condition: []
  action:
    - service: notify.famiglia
      data:
        message: "Stato attuale allarme: {{ states.alarm_control_panel.inim.state }}."
```

Se hai dubbi scrivi pure spero di esserti stato di aiuto come altri lo sono stati con me 
Ciao
