### DISCUSSION TITLE
Doppio notify (Telegram e Pushbullet)

### DISCUSSION THREAD

**Discussion by nromagna** [indomus/forum#1190] [HUB: Home Assistant]
Ciao a tutti ho integrato in configuration.yaml il servizio Pushbullet (e devo dire che funziona)

```
# Pushbullet
notify:
  - platform: pushbullet
    name: pushbullet
    api_key: xxxxxxxxxxxxxxxxxxxxx
```

Ora vorrei integrare anche Telegram

```
# Telegram
telegram_bot:
 - platform: polling
   api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
   allowed_chat_ids:
    - 82584xxxx # (chat ID1)

notify: 
  - name: Nicola
    chat_id: 82584xxxx 
    platform: telegram
```

Solamente che se lascio così mi da errore al momento del salvataggio del File Editor perchè trova due "notify" uno alla riga 8 (Telegram) ed uno alla 250 (Pushbullet).
Se cambio uno dei due con notifi_tg mi da errore in fase di controllo dutante la verifica del configuratore:
Integration error: notify_tg - Integration 'notify_tg' not found.

É possibile avere i due servizi di notifica oppure solo uno?

Grazie a tutti.

**Comment by Larry-78** [comment]
Ciao, mi sa che il problema è nei due notify, dovresti mettere soltanto uno . Prova in questo modo.
```yaml
notify: 
  - platform: telegram
    name: Nicola
    chat_id: 82584xxxx
  - platform: pushbullet
    name: pushbullet
    api_key: xxxxxxxxxxxxxxxxxxxxx
```
