### DISCUSSION TITLE
servizio tts.google_say

### DISCUSSION THREAD

**Discussion by calz64** [indomus/forum#1198] [HUB: Home Assistant]
Salve qulcuno sa spiegrami perchè il servzio tts non funziona e invia il messaggio che in rete trovo in varie discussioni 
` [custom_components.alexa_media.media_player]  Sorry, text to speech can only be called with the notify.alexa_media service. Please see the alexa_media wiki for details.https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component#use-the-notifyalexa_media-service`

la mia configurazione è quella spiegata in tutte le guide 
```
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    language: 'it'
    base_url: https://*****.duckdns.org:8123
    service_name: google_say
```
il riferimento ll pagina https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component#use-the-notifyalexa_media-service pe me è incomprensibile.
grazie in anticipo
