### DISCUSSION TITLE
Automazione Home Assistant sfruttando l' ID del trigger

### DISCUSSION THREAD

**Discussion by diaz66** [indomus/forum#1238] [HUB: Home Assistant]
Un saluto a tutti.
Argomento: automazioni HA.
Non credo sia una funzionalità presente da molto tempo. Ai vari trigger che possono innescare una automazione, è possibile assegnare un id.
Questi id, dovrebbero essere molto utili nel proseguimento dello sviluppo dell' automazione, per esempio da utilizzare nelle condition. Li vedo utili perchè, per esempio, con un' unica automazione posso gestire più trigger, evito il proliferare di automazioni, evito "stratagemmi" con variabili di appoggio tipo input text, boolean, codice interno {% ... %}, etc. etc., che rendo meno "leggibile" l' automazione. Solo che a me non funziona. Oppure non ho capito a cosa servono o, forse, non servono proprio.
Esempio con due trigger:
```
- id: '1640715517314'
  alias: CCC
  description: ''
  trigger:
  - platform: state
    entity_id: switch.terrazzo_grande_sala
    for:
      hours: 0
      minutes: 0
      seconds: 4
    id: terrazzosala         #<----------------------------------------------id del primo trigger = terrazzosala
    to: 'on'
  - platform: state
    entity_id: switch.ingresso
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 3
    id: ingresso            #<----------------------------------------------id del secondo trigger = ingresso
  condition: []
  action:
  - condition: trigger  #<----------------------------------------------condizione sull' id del trigger
    id: terrazzosala      #<----------------------------------------------id del trigger
  - service: switch.turn_off
    target:
      entity_id: switch.terrazzo_grande_sala
  - condition: trigger   #<----------------------------------------------condizione sull' id del trigger
    id: ingresso             #<----------------------------------------------id del trigger
  - service: switch.turn_off
    target:
      entity_id: switch.ingresso
  mode: single
```
L' automazione è molto semplice. Spegne una luce dopo 3 secondi che è stata accesa, e l' altra dopo 4. Per discriminare quale delle due ha attivato l' automazione, prendo l' id del trigger. Solo che, con uno switch è ok (switch.terrazzo_grande_sala) ma con l' altro non fa nulla (switch.ingresso). L' automazione , però , viene attivata. In quanto si aggiorna la "data ultima attivazione" nella lista delle automazioni.

Boh, dopo varie prove , tentativi e ricerche, non ho trovato nulla. 
A voi è mai capitato di utilizzare lì id del trigger nelle automazioni ?

Ringrazio chiunque voglia fare alcune prove sull 'argomento.

**Comment by diaz66** [comment]
> Un saluto a tutti. Argomento: automazioni HA. Non credo sia una funzionalità presente da molto tempo. Ai vari trigger che possono innescare una automazione, è possibile assegnare un id. Questi id, dovrebbero essere molto utili nel proseguimento dello sviluppo dell' automazione, per esempio da utilizzare nelle condition. Li vedo utili perchè, per esempio, con un' unica automazione posso gestire più trigger, evito il proliferare di automazioni, evito "stratagemmi" con variabili di appoggio tipo input text, boolean, codice interno {% ... %}, etc. etc., che rendo meno "leggibile" l' automazione. Solo che a me non funziona. Oppure non ho capito a cosa servono o, forse, non servono proprio. Esempio con due trigger:
> 
> ```
> - id: '1640715517314'
>   alias: CCC
>   description: ''
>   trigger:
>   - platform: state
>     entity_id: switch.terrazzo_grande_sala
>     for:
>       hours: 0
>       minutes: 0
>       seconds: 4
>     id: terrazzosala         #<----------------------------------------------id del primo trigger = terrazzosala
>     to: 'on'
>   - platform: state
>     entity_id: switch.ingresso
>     to: 'on'
>     for:
>       hours: 0
>       minutes: 0
>       seconds: 3
>     id: ingresso            #<----------------------------------------------id del secondo trigger = ingresso
>   condition: []
>   action:
>   - condition: trigger  #<----------------------------------------------condizione sull' id del trigger
>     id: terrazzosala      #<----------------------------------------------id del trigger
>   - service: switch.turn_off
>     target:
>       entity_id: switch.terrazzo_grande_sala
>   - condition: trigger   #<----------------------------------------------condizione sull' id del trigger
>     id: ingresso             #<----------------------------------------------id del trigger
>   - service: switch.turn_off
>     target:
>       entity_id: switch.ingresso
>   mode: single
> ```
> 
> L' automazione è molto semplice. Spegne una luce dopo 3 secondi che è stata accesa, e l' altra dopo 4. Per discriminare quale delle due ha attivato l' automazione, prendo l' id del trigger. Solo che, con uno switch è ok (switch.terrazzo_grande_sala) ma con l' altro non fa nulla (switch.ingresso). L' automazione , però , viene attivata. In quanto si aggiorna la "data ultima attivazione" nella lista delle automazioni.
> 
> Boh, dopo varie prove , tentativi e ricerche, non ho trovato nulla. A voi è mai capitato di utilizzare lì id del trigger nelle automazioni ?
> 
> Ringrazio chiunque voglia fare alcune prove sull 'argomento.

Mi rispondo da solo. Ecco il codice corretto e funzionante:
```
- id: '1640715517314'
  alias: CCC
  description: ''
  trigger:
  - platform: state
    entity_id: switch.terrazzo_grande_sala
    for:
      hours: 0
      minutes: 0
      seconds: 4
    id: terrazzosala
    to: 'on'
  - platform: state
    entity_id: switch.ingresso
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 3
    id: ingresso
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: terrazzosala
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.terrazzo_grande_sala
    - conditions:
      - condition: trigger
        id: ingresso
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.ingresso
    default: []
  mode: single


```
