### DISCUSSION TITLE
Zigbee2mqtt + CC2531 - antenna non riconosciuta

### DISCUSSION THREAD

**Discussion by braudoo** [indomus/forum#1252] [ZigBee, Z-Wave, Thread, Matter]
Salve e Buon Anno a tutti, sto riscontrando problemi nel riconoscimento dell'antenna CC2531 dopo installazione di Z2M.
Di seguito i log :

stato attivazione Z2M:

```
● zigbee2mqtt.service - zigbee2mqtt
     Loaded: loaded (/etc/systemd/system/zigbee2mqtt.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-01-02 15:17:40 CET; 2s ago
   Main PID: 7393 (npm start)
      Tasks: 19 (limit: 1438)
        CPU: 2.739s
     CGroup: /system.slice/zigbee2mqtt.service
             ├─7393 npm start
             ├─7407 sh -c node index.js
             └─7408 node index.js

gen 02 15:17:40 raspberrypi systemd[1]: Started zigbee2mqtt.
gen 02 15:17:42 raspberrypi bash[7393]: > zigbee2mqtt@1.22.2 start
gen 02 15:17:42 raspberrypi bash[7393]: > node index.js
```

Allocazione della CC2531:

```
/dev/bus/usb/001/002 - 2109_USB2.0_Hub
/dev/ttyACM0 - Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CD475F2
/dev/bus/usb/001/003 - Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CD475F2

```

_journal_ del servizio:

```
gen 02 15:25:00 raspberrypi bash[10308]:     at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
gen 02 15:25:00 raspberrypi systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
gen 02 15:25:00 raspberrypi systemd[1]: zigbee2mqtt.service: Failed with result 'exit-code'.
gen 02 15:25:00 raspberrypi systemd[1]: zigbee2mqtt.service: Consumed 6.221s CPU time.
gen 02 15:25:00 raspberrypi systemd[1]: zigbee2mqtt.service: Scheduled restart job, restart counter is at 240.
gen 02 15:25:00 raspberrypi systemd[1]: Stopped zigbee2mqtt.
gen 02 15:25:00 raspberrypi systemd[1]: zigbee2mqtt.service: Consumed 6.221s CPU time.
gen 02 15:25:00 raspberrypi systemd[1]: Started zigbee2mqtt.
gen 02 15:25:01 raspberrypi bash[10329]: > zigbee2mqtt@1.22.2 start
gen 02 15:25:01 raspberrypi bash[10329]: > node index.js
gen 02 15:25:05 raspberrypi bash[10344]: Zigbee2MQTT:info  2022-01-02 15:25:05: Logging to console and directory: '/var/log' filename: log.txt
gen 02 15:25:05 raspberrypi bash[10344]: Zigbee2MQTT:info  2022-01-02 15:25:05: Starting Zigbee2MQTT version 1.22.2 (commit #414c51f5)
gen 02 15:25:05 raspberrypi bash[10344]: Zigbee2MQTT:info  2022-01-02 15:25:05: Starting zigbee-herdsman (0.13.188)
gen 02 15:25:05 raspberrypi bash[10344]: Zigbee2MQTT:error 2022-01-02 15:25:05: Error while starting zigbee-herdsman
gen 02 15:25:05 raspberrypi bash[10344]: Zigbee2MQTT:error 2022-01-02 15:25:05: Failed to start zigbee
gen 02 15:25:05 raspberrypi bash[10344]: Zigbee2MQTT:error 2022-01-02 15:25:05: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
gen 02 15:25:05 raspberrypi bash[10344]: Zigbee2MQTT:error 2022-01-02 15:25:05: Exiting...
gen 02 15:25:06 raspberrypi bash[10344]: Zigbee2MQTT:error 2022-01-02 15:25:06: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0 - Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CD475F2'
gen 02 15:25:06 raspberrypi bash[10344]:     at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
gen 02 15:25:06 raspberrypi bash[10344]:     at SerialPort._error (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
```
Ho seguito le istruzioni al sito

https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html

ma è tutto regolare.

Ho anche staccato la prolunga ma niente.

Qualcuno riuscirebbe ad aiutarmi.

Aggiungo che l'antenna su l'ultima installazione di HA andava correttamente quindi dovrebbe essere tutto regolare nel funzionamento dell'antenna stessa.

Grazie per il supporto.

**Comment by snakuzzo** [comment]
HA non c'entra assolutamente nulla con Z2M.
Ti sei assicurato di aver flashato la CC2531 con l'ultimo firmware rilasciato a metà novembre ?
Col passaggio alle versioni di Z2M > 1.20.x è necessario.

Se non l'hai fatto, ogni volta che devi riavviare Z2M devi scollegare e ricollegare la chiavetta prima di avviarlo

**Comment by braudoo** [comment]
Ho citato HA perchè su una SD avevo installato HASSIO e poi avevo provato la CC2531 e mi riconosceva i dispositivi zigbee.
Provo a fare aggiornamento della chiavetta e vediamo se funziona.

**Comment by braudoo** [comment]
Ciao Diego,
 aggiornato chiavetta CC2531 all'ultima versione con successo ma ancora non riesco far partire niente.

 journal attuale:

```
pi@raspberrypi:~ $ sudo journalctl -u zigbee2mqtt.service -f
-- Journal begins at Sat 2021-10-30 13:36:50 CEST. --
gen 04 00:03:26 raspberrypi bash[13060]:     at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
gen 04 00:03:26 raspberrypi bash[13060]:     at SerialPort._error (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
gen 04 00:03:26 raspberrypi bash[13060]:     at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
gen 04 00:03:26 raspberrypi systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
gen 04 00:03:26 raspberrypi systemd[1]: zigbee2mqtt.service: Failed with result 'exit-code'.
gen 04 00:03:26 raspberrypi systemd[1]: zigbee2mqtt.service: Consumed 6.302s CPU time.
gen 04 00:03:26 raspberrypi systemd[1]: zigbee2mqtt.service: Scheduled restart job, restart counter is at 315.
gen 04 00:03:26 raspberrypi systemd[1]: Stopped zigbee2mqtt.
gen 04 00:03:26 raspberrypi systemd[1]: zigbee2mqtt.service: Consumed 6.302s CPU time.
gen 04 00:03:26 raspberrypi systemd[1]: Started zigbee2mqtt.
gen 04 00:03:27 raspberrypi bash[13083]: > zigbee2mqtt@1.22.2 start
gen 04 00:03:27 raspberrypi bash[13083]: > node index.js
gen 04 00:03:31 raspberrypi bash[13100]: Zigbee2MQTT:info  2022-01-04 00:03:31: Logging to console and directory: '/var/log' filename: log.txt
gen 04 00:03:31 raspberrypi bash[13100]: Zigbee2MQTT:info  2022-01-04 00:03:31: Starting Zigbee2MQTT version 1.22.2 (commit #414c51f5)
gen 04 00:03:31 raspberrypi bash[13100]: Zigbee2MQTT:info  2022-01-04 00:03:31: Starting zigbee-herdsman (0.13.188)
gen 04 00:03:32 raspberrypi bash[13100]: Zigbee2MQTT:error 2022-01-04 00:03:32: Error while starting zigbee-herdsman
gen 04 00:03:32 raspberrypi bash[13100]: Zigbee2MQTT:error 2022-01-04 00:03:32: Failed to start zigbee
gen 04 00:03:32 raspberrypi bash[13100]: Zigbee2MQTT:error 2022-01-04 00:03:32: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
gen 04 00:03:32 raspberrypi bash[13100]: Zigbee2MQTT:error 2022-01-04 00:03:32: Exiting...
gen 04 00:03:32 raspberrypi bash[13100]: Zigbee2MQTT:error 2022-01-04 00:03:32: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0 - Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CD475F2'
```
Questo è il mio file di configuration.yaml nel caso vedessi qualche incongruenza:

```
# Autodiscovery su Home Assistant abilitato
homeassistant: true
# Join alla rete MQTT disabilitato di default
permit_join: false
# MQTT settings
mqtt:
  # MQTT base topic per i messaggi di zigbee2mqtt
  base_topic: zigbee2mqtt
  # MQTT server - URL (indirizzo LAN)
  server: 'mqtt://localhost'
  # MQTT server - Parametri di autenticazione (decommentare e popolare correttamente se si utilizzano credenziali per la connessione al broker MQTT
  user: mqtt_user
  password: Alfio-1982
serial:
  # Porta su cui è mappata l'antennza zigbee
  port: /dev/ttyACM0 - Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CD475F2
advanced:
  # Directory in cui verrà salvato il file di log
  log_directory: /var/log
experimental:
  # abilita le nuove API e l'esposizione della webGUI
  new_api: true
frontend:
  # porta su cui verrà esposta la webGUI
  port: 8080
```

mi sembra un problema di porta dove connesso il dongle ma ho fatto diversi test suggeriti dal sito di Z2M ma tutto corretto.

Come potrei risolvere secondo te?

Grazie.
