### DISCUSSION TITLE
Zigbee2MQTT vs Zigbee Home Automation

### DISCUSSION THREAD

**Discussion by labattazza** [indomus/forum#1262] [ZigBee, Z-Wave, Thread, Matter]
Ciao, dal momento che sono un po' nuovo nel settore, e sono riuscito a fare le varie installazioni/configurazioni nei ritagli di tempo,  potrei aver tralasciato qualcosa nella mia "autoformazione", e quindi il dubbio che mi resta potrebbe esser molto "banale".

Sono riuscito a integrare vari pulsanti e luci Ikea Tradfri, e sensori vari Xiaomi Aqara.
Come Hardware ho una Conbee II.

Ho usato l'integrazione Zigbee Home Automation, per cui ho la mia bella lista di dispositivi ed entità (purtroppo per alcuni non avevo probabilmente settato correttamente il "name" in fase di riconoscimento, così ora invece di avere una entità del tipo  _sensor.temperature.balcone_ ho _sensor.lumi_lumi_weather_968dbd05_temperature_ e mi toccherà correggere tutto).
Il tutto funziona anche in assenza di connessione internet, proprio come desideravo (cosa che al momento non riesco a fare con alcuni altri dispositivi che ho inserito tramite cloud del produttore).

Ci sarebbe qualche vantaggio a "trasferire" il tutto su Zigbee2MQTT?
In caso affermativo: devo disinstallare l'integrazione Zigbee Home Automation e procedere a creare a mano ogni dispositivo? (o anche le entità?)

Grazie mille e chiedo venia in anticipo se ho detto qualche boiata!

**Comment by snakuzzo** [comment]
zigbee2mqtt è sicuramente una soluzione più duttile.
Se vuoi passare a zigbee2mqtt devi innanzi tutto rimuovere l'integrazione ZHA e poi installare un broker MQTT (mosquitto) e Zigbee2mqtt. Ho visto un tuo topic dove dici che ora hai HA Supervised su Docker...quindi se è così andrai ad installare l'addon Mosquitto e l'addon Zigbee2mqtt.

Per le entità a quel punto puoi scegliere. Di base solitamente si usa l'autodiscovery MQTT...quindi ti ritroverai (come già successo con ZHA) le entità create manualmente. Se disabiliti l'autodiscovery per HA dovrai creare a mano le entità con platform MQTT. Io le creo tutte a mano, ma il 99% delle persone le lasciano creare con autodiscovery e, se sei alle prime armi, ti sconsiglio di procedere manualmente

**Reply by labattazza** [reply]
Mosquitto è già installato, infatti sto provando a far funzionare una Shelly plug S tramite MQTT.
Pensavo che, una volta che riesca a capire il funzionamento, potrei allora migrare tutto togliendo ZHA, mettendo Zigbee2mqtt e lasciando l'autodiscovery.
Spero di farcela senza impantanarmi, intanto grazie!

**Comment by federoco** [comment]
Io utilizzo con successo Zigbee2MQTT per le luci ma non è buono per il sensore di movimento Ikea Tradfri perchè non fornisce la rilevazione del movimento come valore da usare per le automazioni.
E' possibile, allora, usare in contemporanea anche Zigbee Home Automation per configurare solo il sensore di movimento Ikea Tradfri?
(ovviamente dopo averlo prima rimosso da Zigbee2MQTT)

**Reply by Scialla** [reply]
![Schermata 2025-02-21 alle 20 18 46](https://github.com/user-attachments/assets/36aa1ee5-e2c6-4be6-b7e4-66bd1bf2d9f4)

A me il sensore di movimento Ikea con z2m funziona perfettamente...

**Comment by KC-inDomus** [comment]
https://indomus.it/focus/scegliere-tra-zigbee2mqtt-zha-e-deconz-cose-meglio/

**Comment by federoco** [comment]
Grazie ad entrambi. Avevo già letto l'articolo proposto e riesco a vedere il sensore di movimento Ikea Tradfri come Scialla. Solo che il mio è sempre in stato "occupato". L'ho puntato contro un muro in modo da evitare che intercetti eventuali movimenti involontari ma non si muove dallo stato di "occupato"
Inoltre non capisco come poter creare uno script che, una volta rilevato il movimento, mi accenda una luce o faccia altro.
Potreste condividere il codice che usate voi? O i passaggi da fare tramite GUI

**Reply by Scialla** [reply]
Rimuovilo da z2m (senza impedire la riconnessione) e rifai il pairing

L'automazione con cui lo uso è questa:
```
  - alias: PIR Letto
    id: pir_letto
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.ikeapir1_occupancy
        to: "on"
    conditions:
      - condition: state
        entity_id: light.striscia_letto
        state: "off"
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
    actions:
      - action: light.turn_on
        entity_id: light.striscia_letto
        data:
          brightness: 255
          color_temp: 150
    # Aspetta che il PIR passi a off (quindi prima deve attivarsi)
      - wait_for_trigger:
          - trigger: state
            entity_id: binary_sensor.ikeapir1_occupancy
            to: "off"
        timeout:
          minutes: 10
    # spegne la luce
      - action: light.turn_off
        entity_id: light.striscia_letto
```
