### DISCUSSION TITLE
Errore aggiornando Home assistant con docker-compose

### DISCUSSION THREAD

**Discussion by manny199** [indomus/forum#1263] [GENERALE - Discussioni generiche]
Ciao,
oggi ho tentanto di aggiornare home assistant su Raspberry PI OS e docker mediante docker-compose.
Dall'interno della directory contenente docker-compose.yaml ho eseguito i seguenti comandi:

```
docker-compose pull home-assistant
docker-compose up --build -d home-assistant 
docker image prune -f
```

Ma viene restituito il seguente errore:

Creating home-assistant ... error
ERROR: for home-assistant  Cannot create container for service home-assistant: Conflict. 
The container name "/home-assistant" is already in use by container 
"10ad4cbnhhuynnne78mkkoo900suuudnndhscjfjurhhctgsyyyejwsjs4273929". 
You have to remove (or rename) that container to be able to reuse that name

Se effettuo l'operazione di rimozione del container con "sudo docker rm home-assistant" e poi "docker image prune -f" mi ritrovo un nuovo home assistant inizializzato da zero.

Il file docker-compose.yaml è così composto:

```
services:

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
    - "/home/pi/zigbee2mqtt:/app/data"
    devices:
    - "/dev/ttyACM0"
    environment:
    - "TZ=Europe/Rome"
    network_mode: host
    restart: always

  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
    - /home/pi/homeassistant:/config
    environment:
    - TZ=Europe/Rome
    network_mode: host
    restart: always
```
Dove sbaglio?

**Comment by snakuzzo** [comment]
Togli il `build`

```
docker-compose pull home-assistant
docker-compose up -d home-assistant 
docker image prune -f
```

**Reply by manny199** [reply]
Mi ero attenuto alla guida

**Reply by snakuzzo** [reply]
Controlla bene i container che già stanno girando.

`docker ps -a`

E verifica se torna tutto con quello che ti restituisce

`docker-coompose ps -a`

**Reply by manny199** [reply]
docker ps -a mi restituisce:

![cont_1](https://user-images.githubusercontent.com/50017898/148379717-81e29bc4-0b6b-4ab3-938d-0a573d481847.jpg)

mentre, docker-compose ps -a:

![cont_2](https://user-images.githubusercontent.com/50017898/148379737-024b1a16-1225-4a27-a19a-0039a08fa4e8.jpg)

**Reply by manny199** [reply]
Inoltre anche togliendo **build** mi dice:
```
Conflict. The container name "/home-assistant" is already in use by container
"10ad4cbnhhuynnne78mkkoo900suuudnndhscjfjurhhctgsyyyejwsjs4273929".
You have to remove (or rename) that container to be able to reuse that name
```

Che faccio?

**Reply by snakuzzo** [reply]
Come immaginavo.hai creato i container di ha e caddy fuori dal compose...e nel compose li hai definiti con lo stesso nome.

Devi prima eliminare quei contianer...

```
docker container stop home-assistant
docker container stop caddy
docker container rm home-assistant
docker container rm caddy
```

...e poi definirli nel `docker-compose.yaml` e ricrearli


```
docker-compose up -d caddy
docker-compose up -d home-assistant
```

**Reply by manny199** [reply]
ma eliminando i container perdo le configurazioni di HA e caddy e devo ricominciare da capo ...

**Reply by manny199** [reply]
@snakuzzo Infatti è successo. Non riesco più a connettermi dall'esterno in https e home assistant ha perso tutte le config ma per fortuna ho una copia su un altro SSD.
A questo punto, prima di procedere con le operazioni che mi hai seggerito, mi dici come salvare tutte le config in maniera d ripristinarle quando ricreerò i due container home-assistant e caddy?

**Reply by snakuzzo** [reply]
Se elimini i container creati come da nostra guida non perdi le configurazioni che sono in quelle directory. Se hai perso tutto vuol dire che hai sbagliato a fare tu qualcosa

**Reply by snakuzzo** [reply]
Per aiutarti non penso di poterlo fare così, dovrei accedere per capire che hai combinato...ed ora non posso farlo.
Il suggerimento è "choarisciti come funziona docker". Devi capire bene anche come funziona il mount dei volumi...altrimenti ogni volta avrai difficoltà per fare qualcosa. Apprendi prima e poi migri.

**Reply by manny199** [reply]
Ho eliminato i container come mi hai scritto sopra con stop e rm e poi ricreati

**Reply by manny199** [reply]
Io non ho fatto migrazione ma installazione pulita ex novo su docker. Adesso non voglio impegnarti; magari mi darai una mano quando potrai. Grazie mille

**Reply by snakuzzo** [reply]
Sì ma ti ripeto...dipende da come hai montato i volumi. Io più di questo non posso dirti

**Reply by manny199** [reply]
@snakuzzo Ho approfondito meglio il funzionamento di docker-compose e sono riuscito a far funzionare quasi tutto con i relativi update di compose tramite il comando "docker-compose up -d nomecontainer".
Dal momento che per riutilizzare la precedente configurazione di home assistant ho dovuto copiare tutta una serie di directory dentro /home/pi (prima erano altrove), ho un dubbio sui permessi delle cartelle e dei file; se devono essere tutti con proprietario **root** o **pi** e se **ricorsivamente?** Me ne preoccupo perché In precedenza proprietari e permessi errati non mi consentivano alcuni aggiornamenti automatici.
Inoltre, mentre per tutto il resto ho fatto chiarezza, ho ancora qualche problema con caddy su docker-compose. Se non effettuo alcuna configurazione e utilizzo esclusivamente la configurazione all'interno di docker-compose.yaml e poi lancio il comando "docker-compose up -d caddy" ottengo il seguente errore nell'avvio del servizio e nel mounting:
```
ERROR: for caddy  Cannot start service caddy: OCI runtime create failed: container_linux.go:380: starting container process
 caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/pi/caddy/Caddyfile" to rootfs at 
"/etc/caddy/Caddyfile" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a 
file (or vice-versa)? Check if the specified host path exists and is the expected type.
ERROR: Encountered errors while bringing up the project
```
Non riesco veramente a venirne fuori

**Reply by snakuzzo** [reply]
L'errore è scritto chiaramente qual è...hai letto? Stai montando una directory come un file...non fare confusione.

Per quanti riguarda i permessi puoi anche  forzare l'ownership al tuo account (pi) ricorsivamente, ma considera che alcuni file successivamente verranno comunque creati come root.

**Reply by manny199** [reply]
@snakuzzo Il problema di base è che non riesco ad installare caddy sotto docker-compose e il container risiede altrove, infatti me li trovo tutti ad eccezione del solo caddy che in compose non c'è.

![contain](https://user-images.githubusercontent.com/50017898/148472661-686cd86c-0877-442e-b907-b74c6bf24589.jpg)

Poiché l'errore dice che sto tentando di montare una directory come un file, forse dovrei modificare la configurazione caddy su compose ma come? La mia configurazione è quella della guida e il problema è su **Caddyfile**
```
  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/pi/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/pi/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    ports:
    - "80:80"
    - "443:443"
```
Ho seguito la guida https://indomus.it/guide/come-installare-e-configurare-caddy-con-docker-su-raspbian-di-raspberry-pi/ ma non ne vengo fuori.
Puoi dirmi quale punto di questa o altra guida devo seguire?
Grazie mille Diego per la pazienza

**Reply by snakuzzo** [reply]
Te l'ho scritto già...hai creato già un container di caddy con lo stesso nome che stai usando nel compose. Devi prima rimuovere quello e poi crei quello col compose

**Reply by manny199** [reply]
In questo modo mi perde la configurazione delle porte che diventa:
caddy            caddy run --config /etc/ca ...   Up      2019/tcp, 0.0.0.0:443->443/tcp,:::443->443/tcp, 0.0.0.0:80->80/tcp,:::80->80/tcp
dunque non ho più accesso dal subodmain duckdns su porta 9000.
Per ottenere il port forwarding da porta esterna 9000 a porta interna 8123 ho tentato di modificare il docker-compose.yaml ma senza successo.

Il mio docker-compose.yaml è quello della guida, ovvero:
```
  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/pi/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/pi/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    ports:
    - "80:80"
    - "443:443"
```

**Reply by snakuzzo** [reply]
Tu hai seguito la guida generica per l'installazione di Caddy.
Per HA...se ti serve esporre la porta 9000, basta aggiungerla sotto `ports:` ... e questo è scritto nella guida per la configurazione di Caddy.
Comunque...ammesso che la tua struttura directory sia corretta, dovresti istanziare Caddy in questo modo:

```yaml
  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/pi/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/pi/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
```

Poi nel Caddyfile gli specifichi che devi proxare Home Assistant...

Esempio:

```
#  When your config is ok comment block below to disable use of AMCE staging server
{
    acme_ca https://acme-staging-v02.api.letsencrypt.org/directory 
}

(https_header) {
	header {
		Strict-Transport-Security "max-age=31536000; includeSubdomains"
		X-XSS-Protection "1; mode=block"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Referrer-Policy "same-origin"
	}
}

https://tuodominio.duckdns.org:9000 {
	import https_header
	reverse_proxy http://ipraspberry:8123
}
```

Una volta verificato che tutto sia andato ok, ricordati di fermare Caddy, commentare questa parte...

```
#{
#    acme_ca https://acme-staging-v02.api.letsencrypt.org/directory 
#}
```

...e riavviare il container di Caddy

**Reply by manny199** [reply]
@snakuzzo
Avevi già eseguito aggiunta porta 9000 ma non andava.
Guardando bene ottengo il seguente errore:

{"level":"info","ts":1641557441.313246,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
{"level":"warn","ts":1641557441.3168561,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":3}
{"level":"info","ts":1641557441.3215275,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}

Mi dice che non è formattato come dovrebbe e manifesta errore linea 3 ... 
Ho provato a rifare tutto da zero con caddy ma nulla ...

**Reply by snakuzzo** [reply]
Quello non è un errore ma un warning e puoi tranquillamente ignorarlo.

Dopo quello che hai postato dovrebbe apparirti una cosa del genere...

```
{"level":"info","ts":1641558128.6172717,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1641558128.617306,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv1"}
...
```

...e così via.

Se non ti appare, vuol dire che hai sbagliato a mappare il Caddyfile.

Per verificare che sia mappato correttamente fai così...Entra nel container docker e vedi se nel file del container c'è quello che hai scritto nel tuo Caddyfile

```
docker exec -it caddy sh
/srv # cat /etc/caddy/Caddyfile
```

Se non c'è vuol dire che hai sbagliato a mappare il file

**Reply by manny199** [reply]
@snakuzzo 
Ho verificato ed è mappato correttamente in quanto vedo il contenuto del caddyfile.
Da container docker (no compose) tutto ha sempre funzionato correttamente, reindirizzamenti su porta 9000 etc. etc.; il problema è solo se voglio utilizzare compose.
A questo punto, dato che con docker-compose non ne vengo più fuori, lo lascio con docker classico.
Alla fine il problema riguarda solo caddy in quanto tutti gli altri container istanziati con compose (home-assistant, mosquitto, duckdns, zigbee2mqtt, etc.) funzionano correttamente.
Mi ero intestardito con compose perché mi piace la comodità di gestione ma pazienza ...
Grazie sempre per il tuo prezioso aiuto

**Reply by snakuzzo** [reply]
ma se mi fai vedere tutto quello che hai fatto...ti do una mano.
Ti stai perdendo in un bicchiere con una goccia d'acqua dentro :D

**Reply by manny199** [reply]
@snakuzzo 
Ti riepilogo tutta la procedura:

``docker container stop caddy``
``docker container rm caddy``
``docker-compose up -d `caddy``

Dopo avere installato caddy, nel Caddyfile inserisco:
```
#  When your config is ok comment block below to disable use of AMCE staging server
{
    acme_ca https://acme-staging-v02.api.letsencrypt.org/directory 
}

https://miodomxx.duckdns.org { 
  respond "Test_mio"
  file_server
}
```

nel file docker-compose.yaml inserisco:
```
  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/pi/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/pi/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
``` 
verifico con 
``` 
docker logs caddy
``` 
verifico i certificati con:
``` ls -latr /home/pi/caddy/data/caddy/certificates/acme-staging-v02.api.letsencrypt.org-directory/miodomxx.duckdns.org``` 
mi da permesso negato, dunque aggiungo sudo all'inizio della stringa.

cancello le prime quattro righe dal Caddyfile che dunque diventa:
```
https://miodomxx.duckdns.org { 
  respond "Test_mio"
  file_server
}
```
poi:
`docker restart caddy`
e
`docker logs caddy`
dunque verifico che tutto ok.

verifico **di nuovo** i certificati con:
``` ls -latr /home/pi/caddy/data/caddy/certificates/acme-staging-v02.api.letsencrypt.org-directory/miodomxx.duckdns.org``` 
mi da permesso negato, dunque aggiungo sudo all'inizio della stringa.
```
e riscontro che sono ok.

Poi modifico di nuovo il caddyfile come segue:
```
(https_header) {
  header {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}

https://miodomxx.duckdns.org { 
  respond "Test_mio"
  file_server
}
https://miodomxx.duckdns.org:9000 { 
  import https_header
  reverse_proxy http://192.168.1.125:8123
}
```
Fermo Caddy `docker container stop caddy`                                
Riavvio il container di Caddy con `docker restart caddy`

A questo punto, a differenza della procedura normale docker che reindirizza regolarmente dalla porta esterna 9000 a quella interna, con docker compose non reindirizza nulla, anche istanziando di nuovo con ``docker-compose up -d caddy``

**Reply by snakuzzo** [reply]
Hai formattato male il codice e la configurazione...va messa  con markdown !!!!!! Non so quante volte l'ho ripetuto :)
Ti devi dimenticare per un attimo il comando `docker` per avviare e creare i container...devi usare SOLO `docker-compose`.
Parti da una situazione pulita in cui non hai alcun container di Caddy attivo.
Poi...modifichi il compose aggiungendo

```yaml
  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/pi/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/pi/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
```

Assicurati che il Caddyfile sia questo:

```
{
  acme_ca https://acme-staging-v02.api.letsencrypt.org/directory 
}

(https_header) {
  header {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}

https://miodomxx.duckdns.org:9000 {
  import https_header
  reverse_proxy http://192.168.1.125:8123
}
```

Avvia caddy...

```
docker-compose up -d caddy
```

Lascia stare l' `ls` ed assicurati guardando il log che abbia generato i certificati puntando al server di staging...

`docker logs -f caddy`

Modifica il Caddyfile in questo modo:

```
(https_header) {
  header {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}

https://miodomxx.duckdns.org:9000 {
  import https_header
  reverse_proxy http://192.168.1.125:8123
}
```

Riavvia il container caddy...

`docker-copmose restart caddy`

Assicurati guardando il log che abbia generato i certificati puntando al server di produzione...

`docker logs -f caddy`

**Reply by manny199** [reply]
@snakuzzo 
Niente da fare. Lanciando `docker logs -f caddy` ottengo:
```
{"level":"info","ts":1641580625.594544,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
{"level":"warn","ts":1641580625.6163396,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
{"level":"info","ts":1641580625.622116,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
{"level":"info","ts":1641580625.6246574,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x3f003c0"}
{"level":"info","ts":1641580625.6244903,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1641580625.6244343,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
{"level":"info","ts":1641580625.62211,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["miodomxx.duckdns.org"]}
{"level":"info","ts":1641580625.6316799,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1641580625.6332938,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1641580625.6354204,"msg":"serving initial configuration"}
{"level":"info","ts":1641580721.7667072,"msg":"shutting down apps, then terminating","signal":"SIGTERM"}
{"level":"warn","ts":1641580721.3457393,"msg":"exiting; byeee!! 👋","signal":"SIGTERM"}
{"level":"info","ts":1641580721.5597903,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0x3f003c0"}
{"level":"info","ts":1641580721.449299,"logger":"admin","msg":"stopped previous server","address":"tcp/localhost:2019"}
{"level":"info","ts":1641580721.4493727,"msg":"shutdown complete","signal":"SIGTERM","exit_code":0}
{"level":"info","ts":1641580723.675871,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
{"level":"warn","ts":1641580723.9856065,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":1}
{"level":"info","ts":1641580723.4223526,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
{"level":"info","ts":1641580723.55366,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1641580723.323568,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x209a230"}
{"level":"info","ts":1641580723.7861635,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["miodomxx.duckdns.org"]}
{"level":"info","ts":1641580723.6104147,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
{"level":"info","ts":1641580723.6132743,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1641580723.5437886,"msg":"serving initial configuration"}
{"level":"info","ts":1641580723.434324,"logger":"tls","msg":"finished cleaning storage units"}
```
Per avvio e creazione container ho usato sempre e solamente `docker-compose`

**Reply by snakuzzo** [reply]
io però non vedo errori...mi sembra tutto corretto.
Hai controllato lato HA la configurazione dei `trusted_proxies` ?

**Reply by manny199** [reply]
@snakuzzo con normale container docker, dunque non istanziato con compose, reindirizza perfettamente. A questo punto il problema potrebbe essere nelle porte di docker-compose.yaml anche se mi sembra strano

**Reply by snakuzzo** [reply]
No...le porte non c'entrano.
Fai questa prova...dal compose per caddy togli tutta la parte delle porte ed usa `network_mode: host`... fai sapere se va

**Reply by manny199** [reply]
@snakuzzo 
Fatto ma non reindirizza lo stesso ... questa la sezione in compose ...
```
  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/pi/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/pi/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    network_mode: host
```

Però, in tutto questo c'è un però ... mi sono accorto che adesso, penso per la quantità di prove fatte, non mi genera più certificati, infatti mi dice ... per le prossime 168 ore ... mannaggia ...

aggiornamento:

Provato con altro subdomain duckdns ma il reindirizzamento non funziona lo stesso
