### DISCUSSION TITLE
sensor.yaml

### DISCUSSION THREAD

**Discussion by Oibaf7619** [indomus/forum#1278] [HUB: Home Assistant]
salve,
se inserisco questo sotto config.yaml funziona perfettamente se invece lo sposto in sensor.yaml non funziona, credo sia un problema dovuto a platform ma non ho idea di come risolvere.
grazie
```
sensor:
rest:
  headers:
    Content-Type: application/json
    Authorization: Bearer xxxxxxxxxxxxx
  scan_interval: 180
  resource: wwwwwwwww

sensor:
  name: "Temperatura Esterna"
  unit_of_measurement: "°C"
  value_template: "{{value_json[0]['temperature']}}"
  device_class: temperature
```

**Comment by KC-inDomus** [comment]
non devi aggiungere "sensor:" nel file sidecar. leggi qui https://indomus.it/guide/configuration-yaml-come-suddividere-il-file-di-configurazione-di-home-assistant/

se invece vuoi realizzare dei package, il discorso è diverso: https://indomus.it/formazione/i-package-di-home-assistant-cosa-sono-e-come-si-installano/

**Comment by Oibaf7619** [comment]
sensor lo ho tolto ma non va lo stesso 
grazie per le guide le leggerò

**Reply by snakuzzo** [reply]
Se nel `configuration.yaml` hai...

```yaml
sensor: !include sensor.yaml
```

nel file `sensor.yaml` devi scrivere i sensori senza utilizzare `sensor:` in cima al file, e soprattutto non va mai duplicato nello stesso file YAML come hai fatto tu (tra e altre cose mi pare tu abbia sbagliato proprio a scrivere il messaggio qui, perché mi pare si tratti dello stesso sensore).

Immagino quindi che avrai un qualcosa di simile...

```yaml
- platform: rest
  name: "Temperatura Esterna"
  resource: wwwwwwwww
  headers:
    Content-Type: application/json
    Authorization: Bearer xxxxxxxxxxxxx
  value_template: "{{value_json[0]['temperature']}}"
  unit_of_measurement: "°C"
  scan_interval: 180
  device_class: temperature
```

**Comment by dragorex71** [comment]
Questi sono dei sensori che ho in sensor.yaml, per farti capire.
Come vedi la "premessa" **sensor:** non c'è essendo nel file sensor.yaml è sottinteso sono tutti sensori. 
Spero ti possa aiutare a capire
```
- platform: mqtt
  name: Campanello
  state_topic: "shellies/shelly1-8CAAB505436E/input/0"
- platform: command_line
  name: CPUfreq
  command: "cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq" #"/opt/vc/bin/vcgencmd measure_clock arm"
  unit_of_measurement: "MHz"
  value_template: "{{ value | multiply(0.001) }}"
  scan_interval: 5
- platform: command_line
  name: RaspCPU
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(1)}}"
- platform: command_line
  name: RaspGPU
  command: "/opt/vc/bin/vcgencmd measure_temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | replace("temp=", "") | replace("''C", "") }}'
```

**Comment by Oibaf7619** [comment]
grazie per i consigli in realtà ho provato a formattarlo in vari modi ma restituisce sempre questo errore:
`Invalid config for [sensor]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 13).`
per questo credo che sia associato al valore platform, ma non riesco a capire che valore dare a platform
questa è l'ultima formattazione:
```
rest:
  name: "Temperatura Esterna"
  resource: wwwwwwwww
  headers:
    Content-Type: application/json
    Authorization: Bearer 
  value_template: "{{value_json[0]['temperature']}}"
  unit_of_measurement: "°C"
  scan_interval: 180
  device_class: temperature
```

**Reply by snakuzzo** [reply]
Riguarda [QUI](https://github.com/indomus/forum/discussions/1278#discussioncomment-1935364). Facendo copia-incolla del tuo sensore avevo fatto un errore.

**Reply by snakuzzo** [reply]
Comunque è tutto scritto sulla documentazione ufficiale... [QUI](https://www.home-assistant.io/integrations/sensor.rest/).

**Comment by Oibaf7619** [comment]
grazie mille scrivevo platform e non - platform
grazie ancora

**Comment by vincenzoca69** [comment]
Salve ho questo sensore, che in modelli funziona perfettamente, ma non mi riesce di farlo caricare alla configurazione, potete aiutarmi gentilmente sono 2 gg che provo tutte le formattazioni e quanto altro possibile.
mi restituisce sempre questo errore, ovunque lo posizioni
**Invalid config for [sensor]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 13)**
Grazie

```

sensor:
  name: POTENZA IMMESSA
  unit_of_measurement: W
  tate_class: measurement
  value_template: "{{ (((states.sensor.produzione_istantanea.state|float(0)) - (states.sensor.zcs_potenza_batteria.state|float(0)) 
  - (states.sensor.zcs_consumo_casa.state|float(0)))) }}"
```

**Reply by 50494554524F** [reply]
required key not provided @ data['platform']

**Reply by vincenzoca69** [reply]
questo lo avevo capito, molto illuminante

**Reply by 50494554524F** [reply]
non lo hai capito... devi aggiungere il campo "platform: template" alla definizione del sensore

**Reply by vincenzoca69** [reply]
`- platform: template`
- provato e non va, altrimenti non stavo qui a scrivere, le ho provate tutte, quelle a mia disposizione,
sei così gentile da formattarlo per me così riprovo, e se non va il problema è altrove, perchè non mi accetta niente in nessun file yaml che carica come file aggiuntivo.

Finalmente ho creato il sensore, ma non prende i dati come invece fa nel modello, cose da pazzi.
grazie per l'aiuto

**Comment by dragorex71** [comment]
> Salve ho questo sensore, che in modelli funziona perfettamente, ma non mi riesce di farlo caricare alla configurazione, potete aiutarmi gentilmente sono 2 gg che provo tutte le formattazioni e quanto altro possibile. mi restituisce sempre questo errore, ovunque lo posizioni **Invalid config for [sensor]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 13)** Grazie
> 
> ```
> 
> sensor:
>   name: POTENZA IMMESSA
>   unit_of_measurement: W
>   tate_class: measurement
>   value_template: "{{ (((states.sensor.produzione_istantanea.state|float(0)) - (states.sensor.zcs_potenza_batteria.state|float(0)) 
>   - (states.sensor.zcs_consumo_casa.state|float(0)))) }}"
> ```

A parte l'errore ortografico nella state_class che hai scritto tate_class io lo scriverei così:
```
template:
  - sensor:
      - name: POTENZA IMMESSA
        unit_of_measurement: W
        state_class: measurement
        state: "{{ states ('sensor.produzione_istantanea') | float(default=0) - states ('sensor.zcs_potenza_batteria') | float(default=0) - states ('sensor.zcs_consumo_casa') | float(default=0) }}"
```
Quindi significa che tutti i sensori template li dovrai mettere sotto:
```
template:
  - sensor:
      - 
```
@50494554524F la configurazione con il platform: template è deprecata e sconsigliata come dicono [qui ](https://www.home-assistant.io/integrations/template/#legacy-binary-sensor-configuration-format)
