### DISCUSSION TITLE
configurazione Caddy2

### DISCUSSION THREAD

**Discussion by gericom90** [indomus/forum#1280] [HUB: Home Assistant]
Buongiorno a tutti, sto configurando un Raspberry Pi4 seguendo le guide per Hassio.
In particolare sto seguento la guida    https://indomus.it/guide/installare-e-configurare-caddy-su-home-assistant-os-hassos-hassio/  
Al riguardo, ho un problema nella parte relativa alla configurazione del componente aggiuntivo Caddy2 (https://github.com/einschmidt/addon-caddy-2.git); in quanto se sostituisco quella di default con quella personalizzata, al momento del salvataggio mi viene salvato sempre e solo il testo della configurazione di default.

![immagine](https://user-images.githubusercontent.com/84856140/148691528-df0e7ce1-8dfc-48ea-9001-12891e5f6ba8.png)

In sostanza, qualunque modifica apportata alla configurazione di default di Caddy2 - premendo il pulsante salva - non viene mantenuta.
Grazie per le indicazioni

**Comment by snakuzzo** [comment]
se leggi la documentazione dell'addon, c'è scritto che la configurazione di default viene "ignorata" se viene trovato il Caddyfile.
Se vuoi utilizzare la configurazione che fai da GUI dovresti cancellare il Caddyfile.
Se invece vuoi usare il Caddyfile, nella configurazione di default puoi scrivere pure "pippo pulto e paperino", non verrà presa in considerazione.
Io su HassOS che ho in test ho impostato da GUI così (nel caso in cui dovessi avere problemi con il Caddyfile)...

```yaml
args: []
env_vars: []
log_level: info
non_caddyfile_config:
  destination: localhost
  domain: miodominio.duckdns.org:9000
  email: your@email.com
  port: 8123
```

ed il Caddyfile sotto la share...per la precisione il file è `/share/caddy/Caddyfile` (che è quello che viene cercato di default non impostando nulla) e contiene questo...

```
#  When your config is ok comment block below to disable use of AMCE staging server
#{
#    acme_ca https://acme-staging-v02.api.letsencrypt.org/directory 
#}

###############

(https_header) {
	header {
		Strict-Transport-Security "max-age=31536000; includeSubdomains"
		X-XSS-Protection "1; mode=block"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Referrer-Policy "same-origin"
	}
}

https://miodominio.duckdns.org:9000 {
	import https_header
	reverse_proxy http://localhost:8123
}
```

Fai attenzione che poi nel `configuration.yaml` di Home Assistant devi inserire la classe di IP tra i trusted proxy (aggiungi pure `::1`)

```
http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 127.0.0.1
  - ::1
  - <eventuali altri IP/subnet>
```
