### DISCUSSION TITLE
Aiuto automazione sensore movimento

### DISCUSSION THREAD

**Discussion by chemical76** [indomus/forum#1291] [HUB: Home Assistant]
ciao a tutti ho un problema con l'automazione di un sensore di movimento per accendere una luce.
allora ho un sensore di movimento (binary_sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_ias_zone) e luminosita' aqara  (sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_illuminance) e quando ci passo davanti deve accendere la luce (light.sonoff_1000eeea34) per 30 secondi ma solo quando la luminosita' e' sotto una certa soglia (tipo 30 lux) e se passo davanti mentre e' accesa riavvia l'automazione.
premessa che i sonoff non me li vede come dispositivi ma solo come entita'
Ne ho provate a fare di automazioni:
la prima quella preimpostata con bluprint solo che non c'e' la condizione riguardo la luminosita' inoltre si spegne la luce dopo i 30 secondi 

```yaml
- id: '1641675135544'
  alias: Luce Magazzino
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: 30
      motion_entity: binary_sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_ias_zone
      light_target:
        entity_id: light.sonoff_1000eeea34
```

la seconda l'ho creata da automazione vuota pero' non si accende nulla, nella parte delle azioni non ho messo dispositivo ma chiama servizio e l'entita' perche il sonoff non me lo vede come dispositivo

```yaml
- id: '1641848248675'
  alias: Luce Scala
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 1c4759d60ecba0ad508a56b433aa4214
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_ias_zone
    domain: binary_sensor
  condition:
  - condition: numeric_state
    entity_id: sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_illuminance
    below: '30'
  action:
  - service: light.turn_on
    target:
      entity_id: light.sonoff_1000eeea34
  mode: restart
```

dove sto' sbagliando?
grazie

**Comment by snakuzzo** [comment]
Innanzi tutto dovresti postare il codice utilizzando il markdown, altrimenti così non si capisce veramente niente ed è tutto indentato malissimo...per cui ti chiedo cortesemente di correggere il tuo post.

Quanto all'automazione...due consigli...
- lascia perdere le blueprint, per queste cose non servono a niente
- lascia perdere i device, è molto più semplice lavorare sulle entità

Ad ogni modo ti riporto l'automazione di seguito:

```yaml
- id: accensione_automatica_luce_sala
  alias: Accensione automatica luce sala
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_ias_zone
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_illuminance
    below: 30
  action:
  - service: light.turn_on
    target:
      entity_id: light.sonoff_1000eeea34
  - delay:
      seconds: 30
  - service: light.turn_off
    target:
      entity_id: light.sonoff_1000eeea34
  #mode: restart   #  rimosso dopo il suggerimento di xyzmauro
  mode: single
```

**Reply by xyzmauro** [reply]
Mmmmm @snakuzzo, sai che ho un dubbio su quel mode restart? A luce accesa difficilmente la luminosità sarà minore di 30 lux e quindi abortisce l’automazione non spegnendo più la luce…

**Reply by snakuzzo** [reply]
hai ragione

**Reply by xyzmauro** [reply]
A sto punto meglio 
mode: single
max_exceeded: silent
che stoppa il warning nel log e finisce l’automazione e spegne la luce,poi se triggera di nuovo riparte

**Reply by snakuzzo** [reply]
Perfetto...modifico il codice in alto.
Grazie @xyzmauro ... TOP ;)

**Reply by chemical76** [reply]
Grazie mille provo così e vi faccio sapere.  Ho già provato a modificare la formattazione del post cliccando le due frecce in alto con scritto insert code, escono 2 puntini e in mezzo ci ho incollato il codice di home assistant ma non cambia nulla e non esce il quadrato come nel tuo post.

**Reply by snakuzzo** [reply]
Ti ho modificato io il post...vai in edit e capirai da solo come si fa...se non hai capito, leggi il regolamento, l'abbiamo scritto nel regolamento.
Nella peggiore delle ipotesi, se fai una ricerca su google troverai scritto come fare

**Reply by chemical76** [reply]
Grazie mille

**Reply by chemical76** [reply]
ciao io ho messo come mi avete detto la luce si accende quando passi davanti al sensore ma dopo nemmeno un secondo si spegne inoltre se ripassi davanti subito non si riaccende piu'

```yaml
- id: '1641932594543'
  alias: Luce Magazzino
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_ias_zone
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_illuminance
    below: '30'
  action:
  - service: light.turn_on
    target:
      entity_id: light.sonoff_1000eeea34
  - delay:
      seconds: 30
  - service: light.turn_off
    target:
      entity_id: light.sonoff_1000eeea34
  mode: single  

```

**Reply by snakuzzo** [reply]
Mi sembra strano si spenga dopo un secondo. Se lo fa vuol dire che hai qualche altra automazione che scatena questo comportamento.
Ad ogni modo effettua le action una per volta e vedi come si comporta. Inoltre avendo impostato l'id puoi debugare l'automazione direttamente da GUI ... in fondo a destra, in corrispondenza dell'automazione, c'è il tastino apposito

**Comment by chemical76** [comment]
Niente da fare ho fatto esegui azioni e si accende solo un secondo, non ho nulla di installato, neanche una automazione e in plancia ho solo il meteo.
Ho visto il debug come faccio a capire se c'è qualcosa che non va?
![Screenshot_20220111-222436_Home Assistant](https://user-images.githubusercontent.com/94762261/149024316-fbcc5c5a-0da0-4986-949c-bbdf7a058569.jpg)

**Reply by snakuzzo** [reply]
Per favore, puoi evitare di postare questi screenshot giganti ?

**Reply by snakuzzo** [reply]
...e per favore rispondi sotto l'ultima risposta...non creare nuovi thread

**Reply by snakuzzo** [reply]
detto ciò...hai provato a fare come ti dicevo ? Commentando e tenendo solo la prima action ? a me sembra di no

**Reply by chemical76** [reply]
ciao scusa per la foto ma l'ho caricata da cellulare e sembrava non cosi' grande. 
ho provato a togliere prima una poi l'altra action ma rimane lo stesso
per il debug non ho capito cosa devo fare, devo farti lo screenshot con il log?
```yaml

Triggered by the state of binary_sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_ias_zone at 12 gennaio 2022, 11:14:40
Test numeric_state condition
Call service light.turn_on on entities light.sonoff_1000eeea34
Call service light.turn_off on entities light.sonoff_1000eeea34
luce magazzino (light.sonoff_1000eeea34) acceso
luce magazzino (light.sonoff_1000eeea34) spento
Finished at 12 gennaio 2022, 11:14:41 (runtime: 0.39 seconds)

```

**Reply by snakuzzo** [reply]
Quello che hai postato va bene, ma non mi torna affatto.
Se scrivi l'automazione così succede la stessa cosa ?

```yaml
- id: '1641932594543'
  alias: Luce Magazzino
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_ias_zone
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_illuminance
    below: '30'
  action:
  - service: light.turn_on
    target:
      entity_id: light.sonoff_1000eeea34
  mode: single  
```

P.S. quando posti il codice non c'è bisogno di scrivere...

![log](https://user-images.githubusercontent.com/7205371/149126413-c55a82ee-7a32-4166-9dca-b9415d3455d3.png)


...se non è yaml

**Reply by chemical76** [reply]
con questo codice non si accende nulla

**Reply by snakuzzo** [reply]
se non si accende è perché la condition non è verificata.

**Reply by chemical76** [reply]
Rettifico prima non andava forse la luce, ore fa lo stesso di prima si accende per meno di un secondo e si spegne.  Non ho capito cosa dovrei fare con la condition

**Reply by snakuzzo** [reply]
Toglierla...

```yaml
- id: '1641932594543'
  alias: Luce Magazzino
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_4ae92c05_ias_zone
    to: 'on'
  action:
  - service: light.turn_on
    target:
      entity_id: light.sonoff_1000eeea34
  mode: single
```

Ricorda che questa automazione scatta solo se il sensore passa da `stato diverso da on` -> `on`.
Se quando passi davanti al sensore è già ad `on` non scatta
