### DISCUSSION TITLE
Settare la temperatura target di più valvole insieme

### DISCUSSION THREAD

**Discussion by cmarcant** [indomus/forum#130] [GENERALE - Discussioni generiche]
Ciao, 
ho diverse valvole sui termosifoni che ho integrato in home assistant come dispositivi "climate". Vorrei controllarle insieme, cioè settare un valore della temperatura target per tutte invece che modificare la temperatura target una per una. Ho pensato di creare un input_number e di creare una automazione che legasse il valore dell'input alla temperature dei dispositivi, ma non sono riuscito a farlo. Avete consigli da darmi?

Grazie
Claudio

**Comment by snakuzzo** [comment]
Potresti fare qualcosa creando un package tipo questo (scritto ora al volo senza testare)...

```yaml
# Crei un gruppo con tutte le entità climate che vuoi controllare
group:

  termosifoni:
    name: Termosifoni
    entities:
    - climate.termosifone1
    - climate.termosifone2

# Input number da impostare per la temperatura target
input_number:

  temperatura_target:
    # imposta min, max e step a seconda di quello che è previsto dalle tue teste termostatiche
    name: Temperatura Target
    min: 18
    max: 25
    step: 0.1
    # il mode lo imposti come ti pare...box o slider
    mode: box

# Automazione per gestione temperatura target
automation:

- id: imposta_temperatura_target
  alias: Imposta Temperatura Target
  # Quando l'input number cambia stato
  trigger:
  - platform: state
    entity_id: input_number.temperatura_target
  action:
  # ...viene invocato il servizio di set temperature sul gruppo termosifoni
  - service: climate.set_temperature
    data:
      entity_id: group.termosifoni
      # (tramite template e l'oggetto trigger viene sfruttato lo stato dell'entità che ha fatto scattare il trigger)
      temperature: "{{ trigger.to_state.state }}"
      hvac_mode: heat  # Questo va impostato a seconda della modalità che vuoi impostare
```
