### DISCUSSION TITLE
errore di connessione al container mosquitto

### DISCUSSION THREAD

**Discussion by daiv87** [indomus/forum#1318] [Networking]
Come da titolo sto avendo difficoltà ad avviare il container eclipse-mosquitto.
L' ambiente operativo è un qnap ts231p3

questo è il compose
```
version: '3'
services:
  
  
  mosquitto:
    hostname: mosquitto
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
    - "1883:1883"
    volumes:
    -  "/share/domotica/config/mosquitto:/mosquitto/config"
    environment:
    -  "TZ=Europe/Rome"
    labels:
    - "diun.enable=true"
    - "diun.include.tags=stable"
    restart: always
```
e questo è il file mosquitto.config

```
persistence true
persistence_location /mosquitto/data
listener 1883

allow_anonymous true                                                                                                                                                                                                                                                                                            
password_file /mosquitto/config/pwfile

```
ho provato anche a commentare la parte riguardo la password commentandola ma continuo ad avere problemi...

posto il log completo
```
1642200819: mosquitto version 2.0.14 starting
1642200819: Config loaded from /mosquitto/config/mosquitto.conf.
1642200819: Starting in local only mode. Connections will only be possible from clients running on this machine.
1642200819: Create a configuration file which defines a listener to allow remote access.
1642200819: For more details see https://mosquitto.org/documentation/authentication-methods/
1642200819: Opening ipv4 listen socket on port 1883.
1642200819: Opening ipv6 listen socket on port 1883.
1642200819: Error: Address not available
```
inoltre tale errore lo riesco ad avere solo creando il container da GUI

da CLI quando faccio docker-compose up ho

```
mosquitto    | 1642202516: mosquitto version 2.0.14 starting
mosquitto    | 1642202516: Config loaded from /mosquitto/config/mosquitto.conf.
mosquitto    | 1642202516: Opening ipv4 listen socket on port 1883.
mosquitto    | 1642202516: Opening ipv6 listen socket on port 1883.
mosquitto    | 1642202516: mosquitto version 2.0.14 running
mosquitto    | 1642202516: mosquitto version 2.0.14 starting
mosquitto    | 1642202516: Config loaded from /mosquitto/config/mosquitto.conf.
mosquitto    | 1642202516: Opening ipv4 listen socket on port 1883.
mosquitto    | 1642202516: Opening ipv6 listen socket on port 1883.
mosquitto    | 1642202516: mosquitto version 2.0.14 running

```
nemmeno un errore .... tuttavia con un client esterno come mqtt_explore non si connette..

a furia di tentativi in passato sono riuscito a farlo partire.... ma è stato un colpo di fortuna e ora vorrei vederci un po ' più chiaro 
Grazie in anticipo

**Comment by xyzmauro** [comment]
Così,ad occhio,nel compose non hai montato ne il volume del log ma sopratutto quello dei dati…nel Mosquitto.config gli dici che li troverà la location ma poi non monti il volume

**Reply by daiv87** [reply]
scusa Mauro ma il fatto che non monto quei volumi puó secondo te influire sulla creazione del Container?
ad ogni modo potresti essere più specifico con un esempio

**Reply by xyzmauro** [reply]
Non so se possa essere quello il problema,cmq qui c’è il compose…
https://indomus.it/guide/come-installare-e-configurare-il-broker-mqtt-mosquitto-su-docker-su-raspbian/

**Reply by snakuzzo** [reply]
@daiv87 se non monti i volumi con le tue configurazioin e se non specifichi le porte, secondo te come fa a collegarsi un client esterno ?

**Reply by daiv87** [reply]
ho corretto l errore mappando il db del container mosquitto con una cartella creata nella propria dir chiamata data.
ho quindi creato anche una cartella contenente i file dei log di questo
per lo stack 
```
version: '3'
services:


  mosquitto:
    hostname: mosquitto
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    network_mode: host
#    ports:
#    - "1883:1883"
    volumes:
    -  "/share/domotica/config/mosquitto:/mosquitto/config"
    -  "/share/domotica/config/mosquitto/log:/mosquitto/log"
    -  "/share/domotica/config/mosquitto/data/:/mosquitto/data"
    environment:
    -  "TZ=Europe/Rome"

    restart: always
```
per la configurazione
```
persistence true
persistence_location /mosquitto/data
log_dest file /mosquitto/log/mosquitto.log
log_timestamp_format %Y-%m-%dT%H:%M:%S

listener 1883

allow_anonymous false                                                                                                                                                                                                                                                                                          
password_file /mosquitto/config/mosquitto.passwd
```


e  questi sono i log del container
```
1642431918: mosquitto version 2.0.14 running
1642431923: mosquitto version 2.0.14 terminating
1642431923: Saving in-memory database to /mosquitto/data/mosquitto.db.
1642431931: mosquitto version 2.0.14 starting
1642431931: Config loaded from /mosquitto/config/mosquitto.conf.
1642431931: Opening ipv4 listen socket on port 1883.
1642431931: Opening ipv6 listen socket on port 1883.
1642431931: mosquitto version 2.0.14 running
1642432017: mosquitto version 2.0.14 terminating
1642432017: Saving in-memory database to /mosquitto/data/mosquitto.db.
```
