### DISCUSSION TITLE
Accesso remoto HA su Docker con Caddy

### DISCUSSION THREAD

**Discussion by Juri78** [indomus/forum#1322] [HUB: Home Assistant]
Ciao a tutti!
Vi spiego la mia situazione:
- HA Core installato con Docker su Raspi pi4
- modem/router FRITZ!Box7590 con le porte TCP 9000 e TCP 443 abilitate
- configurato Caddy per connessione remota (ci sto provando!)

Purtroppo riesco a collegarmi ad HA solo con l'indirizzo ip interno http://192.XXX.XXX.X:8123
Se provo a digitare https://juxxxxxx.duckdns.org - mi restituisce "Saluti dal Crew inDomus" (mi piace e l'ho lasciato cosi!)
Se provo a digitare https://juxxxxxx.duckdns.org:8123 - mi restituisce "Impossibile connettersi con il server"

Nel log di Caddy mi riporta:
```
{"level":"info","ts":1642254737.9032743,"logger":"tls","msg":"served key authentication certificate","server_name":"juxxxxxx.duckdns.org","challenge":"tls-alpn-01","remote":"34.221.255.206:61628","distributed":false}
{"level":"info","ts":1642254738.3080401,"logger":"tls.issuance.acme.acme_client","msg":"validations succeeded; finalizing order","order":"https://acme-v02.api.letsencrypt.org/acme/order/365463170/55609676190"}
{"level":"info","ts":1642254739.4073727,"logger":"tls.issuance.acme.acme_client","msg":"successfully downloaded available certificate chains","count":2,"first_url":"https://acme-v02.api.letsencrypt.org/acme/cert/04e21023d1a34eff797cfce546256df969ab"}
{"level":"info","ts":1642254739.409448,"logger":"tls.obtain","msg":"certificate obtained successfully","identifier":"juxxxxxx.duckdns.org"}
{"level":"info","ts":1642254739.4095304,"logger":"tls.obtain","msg":"releasing lock","identifier":"juxxxxxx.duckdns.org"}
```

File di configurazione di HA compilato in questo modo:
```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/16
```

ho provato a ripetere la configurazione tre volte ma con nessun risultato positivo.
Dove sbaglio? Cosa ho omesso di fare?
Grazie in anticipo e un saluto, siete forti con le vostre guide!!

**Comment by snakuzzo** [comment]
Se hai impostato nel Caddyfile che HA risponde sulla 9000, perché stai provando a collegarti sulla 8123?
Dovresti poter raggiungere HA sulla 9000...il giro sarebbe questo:

```
INTERNET -> TUODOMINIO:9000 -> CADDY -> HOMEASSISTANT:8123
```

quindi...prova a collegarti su `https://juxxxxxx.duckdns.org:9000`

A questo punto, se hai impostato correttamente l'ip sotto `trusted_proxies` vedrai la GUI di HA, altrimenti ti restituirà errore HTTP 400.
A quel punto vai a guardare i log di HA e vedrai che ti indica l'IP del container di Caddy. Prendi quell'IP e mettilo al posto di quello che hai messo e vedrai che funzionerà

**Reply by Juri78** [reply]
@snakuzzo ti ringrazio per la risposta.

Ho modificato il file di configurazione in questo modo

```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.2
```
poichè dal log di HA mi restituiva quello come indirizzo IP.
Se provo a collegarmi `https://juxxxxxx.duckdns.org:9000` mi restituisce `400: Bad Request`

**Reply by snakuzzo** [reply]
Se ti dà bad request, hai sbagliato ad impostare l'ip sotto `trusted_proxies` (vedrai che troverai sempre errori simili nel log di HA).
Se invece l'IP è corretto...hai riavviato HA dopo la modifica ?

**Reply by Juri78** [reply]
il log di HA mi restituisce questo messaggio:
`2022-01-15 19:04:08 ERROR (MainThread) [homeassistant.components.http.forwarded] A request from a reverse proxy was received from 172.17.0.2, but your HTTP integration is not set-up for reverse proxies`

quindi di seguito ho modificato il file di configurazione in questo modo:

```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.2
```
ho riavviato HA con Docker-compose, ma il risultato è lo stesso `400: Bad Request`
Non capisco cosa sto sbagliando!!

**Reply by snakuzzo** [reply]
È impossibile...
Sicuro che hai modificatonil configuration.yaml di HA? Perché secondo me hai modificato altro.

Prova del 9...entra nel container...

```
docker exec -it home-assistant bash
```

E vedi cosa c'è nella config...

```
cat /config/configuration.yaml
```

**Reply by Juri78** [reply]
Hai ragione (non che io avessi dubbi sul tuo sapere!!)...

dal comando che mi hai indicato di fare il risultato è:

```
bash-5.1# cat /config/configuration.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
bash-5.1#  
```

Mentre se mi collego con Visual Studio al percorso di HA mi riporta:

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.2

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```

E' ufficiale, sono nella pappa più totale!!
Perché con uno strumento mi dice una cosa che invece con VS è l'opposto?
