### DISCUSSION TITLE
Caddy - error no container to start

### DISCUSSION THREAD

**Discussion by Juri78** [indomus/forum#1327] [Networking]
Buongiorno!!
Anche stamattina mi sto scontrando con il mondo Caddy.

Utilizzo docker-compose dove ho inserito nel file yaml questo blocco:

```yaml
version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
    - /home/pi/homeassistant:/config
    environment:
    - TZ=Europe/Rome
    network_mode: host
    restart: always

  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - /home/pi/caddy/Caddyfile:/etc/caddy/Caddyfile
    - /home/pi/caddy/data:/data
    environment:
    - TZ=Europe/Rome
    restart: always
    ports:
    - "80:80"
    - "443:443"

  deconz:
      container_name: deconz
      image: marthoc/deconz
      volumes:
      - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
      devices:
      - /dev/ttyACM0
      environment:
      - TZ=Europe/Rome
      - DECONZ_WEB_PORT=40850
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=40851
      - DECONZ_VNC_PASSWORD=06Iruj78
      network_mode: host
      restart: always
```

HomeAssistant e deConz vengono avviati correttamente senza problemi mentre per Caddy mirestituisce questo errore:

```
Starting caddy ... failed
ERROR: No containers to start
ERROR: 1
```
il blocco nel file docker-compose.yaml mi sembra corretto, l'ho controllato con quello della guida, ma non si avvia.
Chiedo il vostro aiuto, vi ringrazio in anticipo
