### DISCUSSION TITLE
Automation.yaml problema

### DISCUSSION THREAD

**Discussion by omarantelmi** [indomus/forum#1339] [HUB: Home Assistant]
Ciao a tutti

Uso Windows Docker con core HA

Ho un problema con le automazioni, non riesco a salvarle, anzi vengono salvate nel file automations.yaml ma non le vedo nel pannello delle automazioni

L'unica automazione che si è agganciata bene è quella di DUCKDNS ma non è presente nel file automations.yaml ma è presente in configuration.yaml

**Comment by snakuzzo** [comment]
Devi scegliere se scriverle nel `configuration.yaml` o nel file `automations.yaml`
Se vuoi usare il file `automations.yaml` devi specificare il file sidecar nel `configuration.yaml`.
Esempio

**configuration.yaml**

```
automation: !include automations.yaml
```

**automations.yaml**

```
- id: my_automation_1
  alias: My Automation 1
  trigger:
  - platform: state
...
...
...
- id: my_automation_2
  alias: My Automation 2
  trigger:
  - platform: state
```
