### DISCUSSION TITLE
platform state - inserire piu stati sintassi

### DISCUSSION THREAD

**Discussion by lucaxxaa** [indomus/forum#134] [GENERALE - Discussioni generiche]
Ciao, scusate la mia ignoranza. Avrei bisogno con platform state, sul sensore creato da openweathermap, che restituisce  dei codici numerici, per indicare esempio, pioggia, temporale, ecc... di attribuire piu valori, al triger per poi fargli fare un azione.
L' attuale sintassi mi sa che e' sbagliata. Come posso inserire piu valori nel campo " TO" ?

`alias: 'PROVA openweathermap '
description: ''
trigger:
  - platform: state
    entity_id: sensor.openweathermap_weather_code
    **to: >-
      200,201,202,210,211,212,221,230,231,232,302,312,314,501,502,503,504,511,522,531,602**
condition: []
action:`

**Comment by snakuzzo** [comment]
Per il codice devi usare il markdown. Ti chiedo cortesemente di sistemare altrimenti dovrò cancellare.
Grazie

**Reply by snakuzzo** [reply]
Prova così...

```yaml
trigger:
- platform: template
  value_template: "{{ states('sensor.openweathermap_weather_code') in ['200','201','202','210','211','212','221','230','231','232','302','312','314','501','502','503','504','511','522','531','602'] }}"
```
