### DISCUSSION TITLE
Installare MQTT su Home Assistant OS per Shelly Motion

### DISCUSSION THREAD

**Discussion by Picchios** [indomus/forum#1357] [HUB: Home Assistant]
Buonasera,
sto configurando broker e client MQTT per la prima volta, seguendo la guida, ma arrivato alla fine non và a buon fine.

- Ho creato un utente "mqtt_user"
- Ho aggiunto Mosquitto Broker, l'ho configurato come indicato
- Ho definito la Access Control List tramite Terminale, inserendo sia lo user mqtt, sia il mio nome utente col quale mi collego da amministratore, salva, chiudi --> `nano acl.conf` eseguito
- Riavviato HA --> avviato Mosquitto Broker (+ esegui all'avvio + whatchdog)

Vado ad aggiungere l'integrazione e inserisco come indicato:
Broker: 127.0.0.1 (è installato sulla stessa macchina)
Porta: 1883 inalterata
utente: mqtt_user
pwd: password dell'utente mqtt_user

Impossibile connettersi.

Ho provato a dare anche l'IP della macchina (192.168.x.xxx) ma nulla.
Cosa mi consigliate di fare?
Cosa posso fornirvi ulteriormente per farmi supportare?

Grazie

**Comment by Picchios** [comment]
Rispondo da me e faccio mea culpa, ho ripassato tutta la procedura più volte e c'era un errore in fase di compilazione nel Terminale.

**Comment by indomus** [comment]
Per i posteri, [la guida è qui.](https://indomus.it/guide/configurare-mqtt-broker-client-su-home-assistant/)

**Reply by Picchios** [reply]
Grazie, stavo seguendo pedissequamente la guida e difatti avevo fatto un errore di digitazione.

Ora che ho configurato Mosquitto (e ho configurato anche lo Shelly Motion che volevo integrare), volevo procedere all'integrazione dello stesso.

Questo è il codice inserito nel file di configurazione:

```
binary_sensor:
 - platform: mqtt
   name: "Shelly Motion - Sensore Movimento"
   state_topic: "shellies/Sensore_movimento_scale/status"
   value_template: "{{ 'ON' if value_json.motion == true else 'OFF'}}"
   qos: 2
   device_class: motion
 - platform: mqtt
   name: "Shelly Motion - Stato Sensore Movimento"
   state_topic: "shellies/Sensore_movimento_scale/status"
   value_template: "{{ 'ON' if value_json.active == true else 'OFF'}}"
   qos: 1

sensor:
  - platform: mqtt
    name: "Shelly Motion Battery"
    state_topic: "shellies/Sensore_movimento_scale/sensor/battery"
    value_template: "{{ value}}"
    unit_of_measurement: "%"
    icon: mdi:battery
    qos: 1
```

Effettivamente ora ho 2 binary_sensor per lo **stato** (acceso spento) e per il **movimento** che mi sembrano correttamente funzionanti ed ho il sensore per la **batteria**, che però mi dà sconosciuto.
Cosa sto sbagliando?
