### DISCUSSION TITLE
Forzare aggiornamento binary sensor

### DISCUSSION THREAD

**Discussion by lorenzoter** [indomus/forum#1359] [HUB: Home Assistant]
Buongiorno a tutti :)
Sono riuscito a domotizzare quasi totalmente un centralina di allarme europlus lince.
Dopo un lungo lavoro per intercettare i pin giusti, con un nodemcu e qualche relè sono riuscito ad inserire e disinserire i 3 programmi ed avere lo stato della centrale.
Ho 2 relè che chiudono il contatto in caso di centrale inserita e centrale in allarme.
Ho recuperato il valore con un binary sensor

```

binary_sensor:

  - platform: mqtt
    name: stato_centrale
    state_topic: "stat/tasmota_E41CC1/POWER6"


```

Se attivo l allarme, power6 diventa 1 e il binary sensor funziona normalmente.

Ora il problema è che se viene riavviato homeassistant il valore rimane 0 fino ad un successivo cambio di stato ( e mi sballano tutti gli automatismi).

Qualcuno sa come aiutarmi?

Grazie a tutti :)

**Comment by snakuzzo** [comment]
Ciao.
Come ti accennavo su Facebook, devi creare un'automazione che allo start faccia una publish MQTT per scatenare una publish del device Tasmota con lo stato dei vari `POWER`

Innanzi tutto ti consiglio di modificare il sensore aggiungendo l'availability topic basato sul LWT ([QUI](https://indomus.it/formazione/mqtt-cose-e-come-funziona-il-last-will-and-testament-lwt/) puoi trovare un articolo che ti spiega cos'è)

```yaml
binary_sensor:

- platform: mqtt
  name: 'stato_centrale'
  state_topic: "stat/stato_centrale/POWER"
  availability_topic: "tele/stato_centrale/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
```

Questa invece è l'automazione...

```yaml
automation:

- id: tasmota_announce
  alias: Tasmota Announce
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/POWER
```

Qui come vedi viene fatta una publish sul topic `tasmotas` che è il primo group topic di default di tutti i device tasmota. Vuol dire che tutti i device tasmota sottoscrivono quel topic e quindi quando viene pubblicato, in automatico tutti i device tasmota se ne accorgono e pubblicano lo stato di tutti i loro POWER
