### DISCUSSION TITLE
Automazione con conteggio

### DISCUSSION THREAD

**Discussion by Ale1975-Iron** [indomus/forum#136] [HUB: Home Assistant]
Ciao a tutti,
c'è qualcosa di sbagliato nella mia automazione, visto che non funziona?

vorrei contare i giorni trascorsi dall'ultima pioggia

```
alias: Ultima Pioggia
description: ''
trigger:
  - platform: sun
    event: sunrise
condition: []
action:
  - event: template
    event_data:
      service: >-
        {% if is_state("switch.sensore_pioggia" ,
        "off")%}counter.increment{%else%}counter.reset{%endif%}
      entity_id: counter.last_rain
mode: single
```
