### DISCUSSION TITLE
Input Select perde le opzioni di selezione

### DISCUSSION THREAD

**Discussion by NdR91** [indomus/forum#1361] [HUB: Home Assistant]
Buongiorno a tutti, ho un problema e non riesco a venirne a capo.
Da un pò di tempo a questa parte, un input_select che ha sempre funzionato, mi sta dando uno strano problema.
```
input_select:
  hue_play_telecomando:
    name: Hue Play - Telecomando
    options:
      - 0 #Spento
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    initial: 0
    icon: mdi:remote
```
In sostanza, dopo un "tot" che HA è avviato, l'input select perde tutte le opzioni a parte la "1".

L'unico errore che trovo a log è quello legato ad un'automazione che, allo spegnimento della TV, dovrebbe riportare l'input select a "0". Non trovando l'opzione "0", logga errore.

Non riesco a trovare nessun'altra info.

L'input select, su lovelace, si presenta così quando mi da problemi:
![2022-01-21_09-20-37_129](https://user-images.githubusercontent.com/52299148/150492925-e4b26f9c-436b-4437-a9f5-ae95117b0979.png)

Subito dopo il riavvio, torna tutto perfetto, ma per "poco tempo":
![2022-01-21_09-22-19_130](https://user-images.githubusercontent.com/52299148/150492994-284e328d-b677-4f68-a33e-7948d29a3144.png)

Vorrei capire dove potrei guardare per risalire al problema. Grazie a tutti in anticipo.
