### DISCUSSION TITLE
pannelli iframe https caddy reverse proxy

### DISCUSSION THREAD

**Discussion by Metus88** [indomus/forum#1366] [HUB: Home Assistant]
Ho migrato come consigliato dalle guide indomus a docker su raspberry (rispetto a core venv).
Per ora ho spostato mosquitto, homeassistant in docker. Ora ho aggiunto caddy per evitare di avere la generazione dei certificati con dehydrated (nella guida sconsigliate di utilizzare dehydrated con docker).
Sono riuscito a far funzionare tutto. Da fuori casa e incasa riesco a collegarmi sia da ip locale che tramite duckdns a home assistant con certificati validi.

docker-compose.yaml
```
  home-assistant:
    container_name: home-assistant
    privileged: true
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
    - "/home/homeassistant/.homeassistant:/config"
    - "/var/www/MyScripts:/MyScripts"
 .....
.....
  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/pi/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/pi/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    networks:
      main:
        ipv4_address: 172.28.1.7
    ports:
    - "443:443"
    - "5495:5495"
    - "5559:5559"
.....
.....
```

Caddyfile
```
(https_header) {
  header {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}

https://XXXXXXXXXXXX.duckdns.org:5495 { 
  import https_header
  reverse_proxy http://192.168.1.XXXX:8123
}

https://XXXXXXXXXXXX.duckdns.org:5559 { 
  import https_header
  reverse_proxy http://192.168.1.XXX:80
}
```

Se da qualsiasi browser navigo su https://XXXXXX.duckdns.org:5559 o https://XXXXX.duckdns.org:5495 visualizzo tutto e in modo sicuro dicendomi che la connessione è sicura e i certificati sono validi.
Anche navigando su https://XXXXXX.duckdns.org:5559/MyScripts/monitor/monitor.html visualizzo tutto e tutto si aggiorna e funziona.

Il problema sussiste quando vado a inserire questi url in un pannello iframe sia che sia in lovelace che nel file configuration di home assistant.
```
type: iframe
url: >-
  https://XXXXXXX.duckdns.org:5559/MyScripts/monitor/monitor.html

```
e persino nel configuration.yaml
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - XXX.XX.X.X
    - XXX.XX.X.X/XX
....
panel_iframe:
  orologi_cruscotto:
    title: 'Orologi Cruscotto'
    url: 'https://XXXXX.duckdns.org:5559/MyScripts/monitor/monitor.html'
    icon: mdi:gauge
....
```
Quello che ottengo è una pagina bianca con scritto "Connessione negata da XXXXXXX.duckdns.org."

Ora prima di passare a docker e caddy utilizzavo il medesimo metodo  duckdns + homeassistant venv + apache2 e il giochetto funzionava.
Non capisco come mai su browser gli url sopra citati vengano riconosciuti e considerati sicuri mentre quando li inserisco in un iframe no. Possibile che centri il fatto che ora ho homeassistant in un docker e in qualche modo debba aprigli qualcosa?
