### DISCUSSION TITLE
Notifica da Automazione in base all'assorbimento

### DISCUSSION THREAD

**Discussion by Jones1982** [indomus/forum#1368] [HUB: Home Assistant]
Buongiorno,
ho una presa shuko doppia, che però somma l'assorbimento in un unico valore di entrambi i carichi.
Ho l'entità sia per il valore in Watt che per Ampere.

Nell'automazione che ho fatto, 
dovrebbe annunciare negli speaker Google, [quando lo scaldabagno "finisce" di riscaldare l'acqua (con l'ovvio abbassamento di consumo)] che ha "finito".

Ora, il valore max di assorbimento che mi registra la multipresa smart (con entrambi i carichi), è max 1300w, mentre lo scaldabagno è max 1150w. 

Ho provato a scegliere la soglia dei 300w x fare scattare l'automazione, ma nn va.
P.s: ho messo 300 perché non sempre l'altro carico è acceso, quindi se metto 0, funziona...ma solo a carico totale 0
     ho cambiato anche il separatore decimale da virgola a punto, ma non cambia nulla. giusto x precisare!

Consigli?
Grazie sempre!

```
alias: Avvisa che lo Scaldabagno è pronto!
description: ''
trigger:
  - platform: template
    value_template: '{{ sensor.scaldabagno_assorbimento_watt_2 | int(default=0) > 300,0 }}'
condition: []
action:
  - service: tts.google_say
    data:
      entity_id: >-
        media_player.stanzetta
      message: Avviso! Lo Scaldabagno è pronto!
mode: single
```

----
questa è l'altra automazione che funziona con assorbimento totale 0

```
alias: Avvisa che lo Scaldabagno è pronto!
description: ''
trigger:
  - platform: state
    entity_id: sensor.scaldabagno_assorbimento_watt_2
    to: '0.0'
condition: []
action:
  - service: tts.google_say
    data:
      entity_id: >-
        media_player.stanzetta
      message: Avviso! Lo Scaldabagno è pronto!
mode: single
```

**Comment by xyzmauro** [comment]
Ciao, aldilà del template che va rivisto, ma qual'è la logica per cui hai messo maggiore di 300?
Comunque giocaci un pò col template su strumenti sviluppatori -> modelli partendo da una cosa così
{{ states('sensor.temperatura_sala') |float > 18.0 }} 
per funzionare nell'automazione di deve restituire True

**Reply by Jones1982** [reply]
I valori che ho segnato dei consumi, sono una media. A volte oscillano. Quindi x stare nel range..ho messo 300, ma anche con 200 o 150 non cambia il risultato finale: non va

**Reply by xyzmauro** [reply]
Il template è sbagliato e ti ho scritto come rivederlo,ma è sopratutto la logica che non hai chiara, devi usare minore di,non maggiore…
Accendi la resistenza e arriva a 1200w
L’acqua è calda e spegni la resistenza
A qst punto il valore scende sotto 300 e parte la notifica

**Reply by Jones1982** [reply]
Rivedrò il template come hai scritto tu, appena torno a casa. X il parametro del valore, ho provato sia maggiore che minore. Stesso risultato. Devo provare a sistemare il template come hai scritto. 
Stasera provo e faccio sapere
Grazie

**Reply by Jones1982** [reply]
Rieccomi, ora va bene, grazie.
devo solo mettere la soglia adeguata...
ora va!

```
alias: Avvisa che lo Scaldabagno è pronto! -2- 
description: ''
trigger:
  - platform: template
    value_template: "{{ states('sensor.scaldabagno_assorbimento_watt_2') |float < 160.00 }}"
condition: []
action:
  - service: tts.google_say
    data:
      entity_id: media_player.stanzetta
      message: Avviso! Lo Scaldabagno è pronto!
mode: single
```

GRAZIE!
