### DISCUSSION TITLE
Automazioni: comportamento inaspettato

### DISCUSSION THREAD

**Discussion by 2Max2Pax** [indomus/forum#1390] [HUB: Home Assistant]
Sto litigando con due automazioni apparentemente semplici:
L' automazione che genera il problema (per ora manda solamente una notifica):
```
- id: '1643062499488'
  alias: AscoltaClimate
  description: ''
  trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: climate
      service: set_temperature
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      message: '{{ trigger }}'
  mode: single
```
Il primo problema che incontro e' che a volte il cambio di temperatura tramite la card thermostat genera 2 oppure 3 notifiche (identiche).
Il secondo problema e' legato ad una seconda automazione, quella del cronotermostato che ogni 15 minuti verifica ed eventualmente setta la temperatura secondo quanto programmato:
```
- id: '1637949062115'
  alias: CTRV_run
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition: []
  action:
  - service: automation.turn_off
    target:
      entity_id: automation.ascoltaclimate
  - service: pyscript.ctrv_run
  - service: automation.turn_on
    target:
      entity_id: automation.ascoltaclimate
  mode: single
```
A volte, nonostante l'automazione precedente venga temporaneamente disabilitata, triggera comunque la notifica ...
Nel log mi si genera anche il warning:
```
Logger: homeassistant.components.automation.ascoltaclimate
Source: helpers/script.py:1382
Integration: Automation (documentation, issues)
First occurred: 8:45:22 AM (222 occurrences)
Last logged: 9:19:12 AM

AscoltaClimate: Already running
```
