### DISCUSSION TITLE
SENSORE CLIMATE E CALDAIA

### DISCUSSION THREAD

**Discussion by lorenzoter** [indomus/forum#1397] [HUB: Home Assistant]
buonasera a tutti...
prosegue la missione per migliorare la mia piccola stanzioncina domotica :)
sto partendo dall'ordinare e semplificare il configuration.yaml e correggere i vari problemi.

```
sensor:
  - platform: mqtt
    name: "Temperatura Sala"
    state_topic: "tele/tasmota_D77D85/SENSOR"
    unit_of_measurement: "°C"
    qos: 1
    value_template: "{{ value_json.SI7021.Temperature }}"

switch:
  - platform: mqtt
    name: unita_termica
    state_topic: "stat/tasmota_D77D85/POWER"
    command_topic: "cmnd/tasmota_D77D85/POWER"
    availability_topic: "tele/tasmota_D77D85/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

climate:
  - platform: generic_thermostat
    name: Riscaldamento
    heater: switch.unita_termica
    target_sensor: sensor.temperatura_sala
    min_temp: 15
    max_temp: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    ac_mode: false
```

allego il sensor che ho creato per prendere la temperatura, lo switch che uso per accendere la caldaia e l'entità climate.

Funziona tutto regolarmente... ma se riavvio homeassistant, il sensore climate non prende il vecchio stato ( e la caldaia rimane accesa o spenta senza curarsi della temperatura :D)

Qualcuno sa darmi qualche dritta? :)

grazie a tutti ;)
