### DISCUSSION TITLE
Shelly H&T

### DISCUSSION THREAD

**Discussion by mriitan** [indomus/forum#1401] [HUB: Home Assistant]
Ciao a tutti,
ho 4 di questi sensori temp/umidità della shelly.
Me li sono trovati integrati nella fase di installazione e autoricerca di HA.
Li vedo regolarmente tra i dispositivi con tutti i loro servizi, unico problema sembra che non si aggiornino i dati.
devo fare qualcosa per risvegliarli?
grazie

**Comment by mriitan** [comment]
ho capito che devo installare il mosquitto.
aggiornamento:
esce fuori
Configurazione non valida

Integration error: keyfile - Integration 'keyfile' not found.
Integration error: customize - Integration 'customize' not found.
Integration error: certfile - Integration 'certfile' not found.
Integration error: require_certificate - Integration 'require_certificate' not found.
Integration error: anonymous - Integration 'anonymous' not found.
Integration error: logins - Integration 'logins' not found.

ho verificato che eliminando le righe dal config:

```
logins:
  - username: "mqtt_user"
    password: "Omni001"
anonymous: false
customize:
  active: true
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```
gli errori scompaiono.
i 4 sensori funzionano, dialogano regolarmente, l'unico problema è che non hanno un id identita per cui posso solo vedere le informazioni, c'è un modo per dare loro un id entità univoco?
grazie
m
