### DISCUSSION TITLE
Sensore template conteggio termostatiche attive

### DISCUSSION THREAD

**Discussion by dante70** [indomus/forum#1407] [GENERALE - Discussioni generiche]
buonasera,
volevo implementare nella mia interfaccia HA una card che mi indicasse quante termostatiche sono ''aperte'' in modo da avere a colpo d'occhio una visione dello stato dell'impianto di riscaldamento.
Ho provato sostituendo ad un template che ho funzionante che mi indica quante tapparelle sono aperte i dati ma non funziona.
In realta' il sensore e' creato ma rimane a 0 pur facendo cambiare di stato i vari climate
Controllando negli strumenti sviluppatori l'attributo che ho messo (hvac_mode) e' presente e cambia da ''idle'' a ''heating'' a seconda dell'attivazione o meno della termostatica.
Allego codice 

NON FUNZIONA
```    
      termostati_in_chiamata:
        friendly_name: 'TERMOSTATI IN CHIAMATA'
        icon_template: 'mdi:fire'
        value_template: "{{ states.climate | selectattr('hvac_action', 'eq', 'heating') | list | count }}"
  

  ```
FUNZIONA
```
      tapparelle_aperte:
        friendly_name: 'TAPPARELLE APERTE'
        icon_template: 'mdi:window-shutter-open'
        value_template: "{{ states.cover | selectattr('state', 'eq', 'open') | list | count }}"
   ```
grazie a chi mi da una dritta
