### DISCUSSION TITLE
Ritorno a spento di pulsante

### DISCUSSION THREAD

**Discussion by mriitan** [indomus/forum#1409] [HUB: Home Assistant]
Ciao, credo sia una banalità, ma non trovo una soluzione.
Ho un tasto legato ad un trigger boleano, che al cambio di stato fa partire una automazione, vorrei al termine della stessa che il tasto ritorni su spento.
Come devo fare?
grazie

**Comment by mriitan** [comment]
trovato : evento input bolean

**Reply by snakuzzo** [reply]
```yaml
automation:

- id: test
  alias: Test
  trigger:
  - platform: state
    entity_id: input_boolean.pippo
    to 'on'
  action:
  - service: ...
    data:
      entity_id: ...
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.pippo 
```
