### DISCUSSION TITLE
SOLVED:ERROR FOR ZONE

### DISCUSSION THREAD

**Discussion by jimborm** [indomus/forum#141] [HUB: Home Assistant]
Ciao da qualche giorno noto nel log di homeassistant questo ERRORE:
```
2021-04-11 18:07:00 ERROR (MainThread) [homeassistant.components.hassio] Invalid config for [zone]: [platform] is an invalid option for [zone]. Check: zone->zone->7->platform. (See /config/configuration.yaml, line 135). 
```
la mia conf nel file configuration.yaml per la parte relativa alle zone e che non ho modificato di recente è di questo tipo:
```
zone:
  - name: Home
    latitude: xxx
    longitude: xxx
    radius: 2
    icon: mdi:account-multiple
  - name: 1
    latitude: xxx
    longitude: xxx
    radius: 5
  - name: 2
    latitude: xxx
    longitude: xxx
    radius: 2
  - name: 3
    latitude: xxx
    longitude: xxx
    radius: 100
  - name: 4
    latitude: xxx
    longitude: xxx
    radius: 100
  - name: 5
    latitude: xxx
    longitude: xxx
    radius: 100
  - name: 6
    latitude: xxx
    longitude: xxx
    radius: 100
```
Come posso verificare\correggere ?
