### DISCUSSION TITLE
Zigbee: Deconz non ha permessi su /dev/conbee

### DISCUSSION THREAD

**Discussion by labattazza** [indomus/forum#1411] [HUB: Home Assistant]
Ciao a tutti

ieri mi sono deciso e ho rimosso il "sarchiapone", ossia Home Assistant installato con supervisor.

Ho stoppato e rimosso tutti i container e immagini precedenti. L'unica cosa che non sono sicuro di aver portato a termine prima di ripartire è la cancellazione di tutto ciò che poteva esser stato creato sotto /var.

Ho seguito la guida e installato HA Core con docker-compose.
Tutto bene, ho anche aggiunto HACS.

Primi problemi quando sono andato a configurare l'integrazione per Zigbee.
Sto pensando di usare Zigbee2MQTT, ma prima per testare che l'hardware funzioni ho provato a usare la cara vecchia **integrazione Deconz**.
Bene, **quando chiede di indicare il dispositivo**, e inserisco il `/dev/conbee` (a suo tempo ho creato le regole per rendere statico il device tty collegato alla penna usb Conbee e a quello della penna Zwave: ha sempre funzionato sia con HA Core venv che con il supervisor) mi dice che **non può accedere**.

Per sfizio ho provato a installare **deconz con docker**: guardando i **log** quando completa l'installazione dice che non **può scrivere sul device tty della Conbee**: il fatto è che anche dando permessi 775 per provare a sbloccare, l'errore si ripete.

E questo mi fa pensare che sia lo stesso motivo per cui non funziona l'integrazione installata da pannello HA.

Avete qualche idea sulla causa? Potrebbe essermi sfuggito qualcosa che usa ancora quella porta?

Vorrei far funzionare il tutto per esser certo di non avere problemi di permessi/percorsi, e poi togliere e usare Zigbee2MQTT, che non conosco perché non ho ancora usato. Così se avessi dei problemi, potrei escludere delle cause.
Grazie mille!

**Comment by KC-inDomus** [comment]
parti direttamente con ZigBee2MQTT, evita di sbattere le corna ancora su Deconz. ciò detto vedi se Z2M ti dà lo stesso problema, eventualmente bisogna capirne le cause (ma prima mettiti nella condizione migliore)

**Reply by snakuzzo** [reply]
@labattazza mi fai vedere come hai creato il service nel docker-compose ?

**Reply by labattazza** [reply]
Ciao, questo è il mio docker-compose.yaml per i 3 servizi che ho attivato:

```
version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/intel-nuc-homeassistant:stable
    volumes:
    - /home/ennio/homeassistant/.homeassistant:/config
    - /media/ssd:/media
    environment:
    - TZ=Europe/Rome
    network_mode: host
    restart: always
    ports:
      - 8123:8123
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
  deconz:
    container_name: deconz
    image: marthoc/deconz
    volumes:
    - "/opt/deconz:/root/.local/share/dresden-elektronik/deCONZ"
    devices:
    - "/dev/conbee"
    environment:
    - "TZ=Europe/Rome"
    - "DECONZ_WEB_PORT=40850"
    - "DECONZ_VNC_MODE=1"
    - "DECONZ_VNC_PORT=40851"
    - "DECONZ_VNC_PASSWORD="XXXXXXX"
    network_mode: host
    restart: always

```

**Reply by snakuzzo** [reply]
Aggiungi...

```
privileged: true
```

...dove devi usare `/dev/conbee`...e riprova

**Reply by labattazza** [reply]
Chiedo scusa, l'altra sera ho digitato nella casella sbagliata... stanchezza molesta.

Inserendo `privileged: true` non mi ha dato l'errore che avevo in precedenza, ma quello che avevo evidenziato sotto:

```
20:49:06:514 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
20:49:06:514 device state timeout ignored in state 1
20:49:09:094 failed to reconnect to network try=4
20:49:14:094 failed to reconnect to network try=5
20:49:19:094 failed to reconnect to network try=6
```

**Reply by snakuzzo** [reply]
questo non penso c'entri qualcosa però

**Reply by labattazza** [reply]
Ciao, seguendo il consiglio, nel fine settimana ho lascaito perdere l'integrazione Deconz e ho installato, seguendo le vostre guide, sia Mosquitto ("Docker style") sia zwavejs2mqtt (che funziona) e per finire zigbee2mqtt.

Ecco, quest'ultimo container non si avvia.

Dall'errore che da sembrerebbe che ci sia qualcosa che non va nell'indentazione dei file di configurazione, ma ho verificato più volte e ho fatto anche un controllo con validatori online (come quello che consigliavate in un altro post). Non riesco proprio a capire... 

In docker-compose ho aggiunto questa sezione:

```
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
    - "/home/ennio/zigbee2mqtt:/app/data"
    devices:
    - "/dev/ttyACM1"
    environment:
    - "TZ=Europe/Rome"
    network_mode: host
    restart: always


```




Questo è il file configuration.yaml di zignee2mqtt (nella guida viene data l'indicazione di aggiungere una sezione 

```
serial:
  port: /dev/ttyXXX
  adapter: deconz
```
Ma siccome a metà circa è già presente  "serial: port" ho solo aggiunto "adapter: deconz", è corretto?


```
# Autodiscovery su Home Assistant abilitato
homeassistant: true
# Join alla rete MQTT disabilitato di default
permit_join: false
# MQTT settings
mqtt:
  # MQTT base topic per i messaggi di zigbee2mqtt
  base_topic: zigbee2mqtt
  # MQTT server - URL (indirizzo LAN)
  server: 'mqtt://localhost'
  # MQTT serveral broker MQTT
  user: mqtt
  password: password
serial:
  # Porta su cui è mappata l'antennza zigbee
  port: /dev/ttyACM1
  adapter: deconz
advanced:
  # Directory in cui verrà salvato il file di log
  log_directory: /var/log
experimental: {}
frontend:
  # porta su cui verrà esposta la webGUI
  port: 8080
ota:
  update_check_interval: 10
disable_automatic_update_check: false
```
Di sicuro è una minuzia, sono anche andato a controllare: _"**YAMLException: end of the stream or a document separator is expected** (2:14)"_ significa che l'errore è alla seconda riga, posizione 14?

E questo è l'errore: 
```
docker container logs zigbee2mqtt -f
Using '/app/data' as data directory
(node:7) UnhandledPromiseRejectionWarning: **YAMLException: end of the stream or a document separator is expected** (2:14)
 1 | kk# Autodiscovery su Home Assistant abilitato
 2 | homeassistant: true
------------------^
 3 | # Join alla rete MQTT disabilitato di default
 4 | permit_join: false
    at generateError (/app/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/app/node_modules/js-yaml/lib/loader.js:187:9)
    at readDocument (/app/node_modules/js-yaml/lib/loader.js:1645:5)
    at loadDocuments (/app/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/app/node_modules/js-yaml/lib/loader.js:1714:19)
    at Object.read (/app/lib/util/yaml.ts:7:21)
    at read (/app/lib/util/settings.ts:309:20)
    at getInternalSettings (/app/lib/util/settings.ts:405:21)
    at Object.reRead (/app/lib/util/settings.ts:683:5)
    at start (/app/index.js:85:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

```

**Reply by snakuzzo** [reply]
Ad occhio non vedo errori...comunque...prova così...

```yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
  user: mqtt
  password: password
serial:
  port: /dev/ttyACM1
  adapter: deconz
advanced:
  log_directory: /var/log
frontend:
  port: 8080
```

**Reply by labattazza** [reply]
Aggiornamento: partendo dal tuo esempio ho ricreato il container e.. sembra essersi avviato correttamente!
Ho dovuto chiudere tutto  in fretta e furia prima di fare altre verifiche, se riesco riprovo stasera col vecchio file, e provo anche a vedere se funziona  `port: /dev/conbee` invece che `port: /dev/ttyACM1` (perché se capita che a un riavvio ttyACM0/1 vengono invertite mi ritrovo zwave e zigbee che non funzionano. Invece `/dev/conbee` e `/dev/zwave` sono link simbolici che puntano sempre al device corretto.

Credo di aver capito quale fosse l'errore: 

```
mqtt:
  base_topic: zigbee2mqtt
  server: **'mqtt://localhost'**
```

Avevo lasciato gli apici

**Reply by snakuzzo** [reply]
Forse volevi dire "gli asterischi"
Così è corretto:

```yaml
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
```
