### DISCUSSION TITLE
Formattazione data e ora

### DISCUSSION THREAD

**Discussion by verialex79** [indomus/forum#1414] [HUB: Home Assistant]
Buonasera,
ho inserito nel configuration.yaml questo sensore:
...yaml
```
sensor:
  - platform: template
    sensors:
      data_formattata:
        friendly_name: Data
        value_template: >
            {% set numgiorno = ["Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato", "Domenica"]%}
            {% set giorno_della_settimana = numgiorno[now().weekday()] %}
            {{ giorno_della_settimana }}, {{ now().day }}  {{ now().month }}  {{ now().year }}  
```
nel button-card ho inserito questa configurazione:

```
type: custom:button-card
entity: sensor.time
layout: vertical
name: '[[[ return states[''sensor.data_formattata''].state; ]]]'
show_icon: false
show_label: true
show_name: true
show_state: true
styles:
  card:
    - height: 80px
  state:
    - font-size: 200%
    - font-weight: bold
    - justify-self: center
  label:
    - justify-self: center
    - font-size: 90%
    - color: var(--paper-item-icon-active-color)
  name:
    - justify-self: center
    - font-size: 120%
tap_action:
  action: none
```

ho 3 problemi nella visualizzazione:
1 vorrei vedere il nome del mese e non il numero
2 l'orario mi segna un'ora indietro
3 vorrei inserire all'interno dello stesso button-card il sensore di temperatura interno
Come potrei risolvere?
Grazie
