### DISCUSSION TITLE
MQTT Device Tracker

### DISCUSSION THREAD

**Discussion by Larry-78** [indomus/forum#1415] [HUB: Home Assistant]
Ciao a tutti, ho realizzato un progetto su GitHub che descrive come tracciare un dispositivo Bluetooth Low Energy con un ESP32, il protocollo MQTT e Home Assistant. Mi sono munito di scheda e un Tag BTLe tipo NUT mini e ho configurato il tutto.
La scheda rileva i dispositivi nelle vicinanze e pubblica topic e relativi payload di questo tipo
```
dss_ble2mqtt/FEAB6224/home/xxxxxxxxxxxx/state, payload: ON
dss_ble2mqtt/FEAB6224/home/xxxxxxxxxxxx/rssi, payload: -69
dss_ble2mqtt/FEAB6224/availability, payload: online
```
al posto delle x ci sono gli indirizzi MAC dei dispositivi tracciati.
Ho aggiunto le configurazioni del caso e aggiunto gli indirizzi MAC dei miei dispositivi e ho ottenuto le due entità binary_sensor per la presenza e due entità sensor per RSSI.

```yaml
sensor:
  - platform: mqtt   
    name: "Lorenzo Nut RSSI"
    state_topic: "dss_ble2mqtt/FEAB6224/home/xxxxxxxxxxxxx/rssi"
    availability_topic: "dss_ble2mqtt/FEAB6224/availability"
    unit_of_measurement: "dBm"
    expire_after: 300

  - platform: mqtt   
    name: "Adriana Nut RSSI"
    state_topic: "dss_ble2mqtt/FEAB6224/home/xxxxxxxxxxxxx/rssi"
    availability_topic: "dss_ble2mqtt/FEAB6224/availability"
    unit_of_measurement: "dBm"
    expire_after: 300
    icon: mdi:bluetooth-audio

binary_sensor:
  - platform: mqtt  
    name: "Lorenzo Nut"
    state_topic: "dss_ble2mqtt/FEAB6224/home/xxxxxxxxxxxxx/state"
    availability_topic: "dss_ble2mqtt/FEAB6224/availability"
    device_class: presence
    expire_after: 300

  - platform: mqtt  
    name: "Adriana Nut"
    state_topic: "dss_ble2mqtt/FEAB6224/home/xxxxxxxxxxxxx/state"
    availability_topic: "dss_ble2mqtt/FEAB6224/availability"
    device_class: presence
    expire_after: 300
```
Fin qui funziona tutto. 
Ora vengo alla questione in oggetto, è possibile creare degli MQTT device tracker? Preferirei trasformarli in device_tracker perché nelle impostazioni di tracciamento delle entità person che ho creato non vengono accettati i binary_sonsor. Attualmente utilizziamo il GPS attraverso la companion app e non sempre è precisa, molto spesso mia moglie risulta fuori casa per un pò di tempo a causa del suo smartphone, ecco la decisione di implementare un tracciamento aggiuntivo.
Leggendo la documentazione ufficiale é possibile integrare manualmente gli MQTT device tracker e ho provato in questo modo

```yaml
device_tracker:
  - platform: mqtt
    devices:
      lorenzo_tracker_nut: "dss_ble2mqtt/FEAB6224/home/xxxxxxxxxxxxx/state"
      adriana_tracker_nut: "dss_ble2mqtt/FEAB6224/home/xxxxxxxxxxxxx/state"
    qos: 1
    payload_home: "ON"
    payload_not_home: "OFF"
    source_type: bluetooth_le
```
Il problema è che vengono create due entità ma soltanto la mia funziona mentre quella di mia moglie rimane sempre con stato not_home.
Ovviamente mi sono messo in ascolto sul broker e arrivano i messaggi su quel topic con payload: ON e il binary_sensor MQTT creato funziona perfettamente 
Ho notato però che negli attributi dell'entità device_tracker.adriana_tracker_nut risulta source_type: null e pur nella configurazione è specificato, infatti negli attributi del mio device_tracker risulta source_type: bluetooth_le.
Ho provato anche a separare le due configurazioni

```yaml
device_tracker:
  - platform: mqtt
    devices:
      lorenzo_tracker_nut: "dss_ble2mqtt/FEAB6224/home/xxxxxxxxxxxxx/state"
    qos: 1
    payload_home: "ON"
    payload_not_home: "OFF"
    source_type: bluetooth_le

  - platform: mqtt
    devices:
      adriana_tracker_nut: "dss_ble2mqtt/FEAB6224/home/xxxxxxxxxxxxx/state"
    qos: 1
    payload_home: "ON"
    payload_not_home: "OFF"
    source_type: bluetooth_le

```
Ma comunque quella di mia moglie continua a non funzionare mantenendo gli stessi attributi e lo stesso stato.
Dove sto sbagliando? Oppure non ho compreso bene il funzionamento. Accetto volentieri suggerimenti. Grazie
