### DISCUSSION TITLE
SmartIR e card climate

### DISCUSSION THREAD

**Discussion by NTorto** [indomus/forum#1421] [HUB: Home Assistant]
Ciao a tutti,
ho seguito e preso spunto dalla guida di SmartIR per il controllo della stufa a pellet: https://indomus.it/progetti/domotizzare-un-condizionatore-tradizionale-con-broadlink-e-home-assistant-v2/

Funziona tutto correttamente con i comandi da card ma ho un funzionamento anomalo da telecomando: ho inserito il controllo dello stato della stufa (spento/acceso) tramite binary_sensor, dentro le impostazioni di smartir, in modo tale che sulla card thermostat abbia la visione di acceso/spento:
```
binary_sensor:
  - platform: template
    sensors:
      stato_stufa_pellet:
        friendly_name: "Stato Stufa a pellet"
        value_template: "{{ states('sensor.stufa_pellet_power') | int(default=0) > 20 }}"
        device_class: power
        delay_on:
          seconds: 20
        delay_off:
          seconds: 20
          
climate:
  - platform: smartir
    name: Fiorina 74
    unique_id: fiorina_74
    device_code: 1234
    controller_data: remote.broadlink_sala_remote
    temperature_sensor: sensor.broadlink_sala_temperature
    humidity_sensor: sensor.broadlink_sala_humidity
    power_sensor: binary_sensor.stato_stufa_pellet
```

Il problema è che quando la stufa è spenta, sulla card visualizzo correttamente la selezione su spento, ma quando si accende (da telecomando) la selezione varia da spento a qualcosa di indeterminato (non va su acceso) e quindi HA non capisce che è accesa e non la comanda tramite card, a meno che non la forzi in acceso da lì.
Vi posto i due screen di spento e acceso.
Spento
![image](https://user-images.githubusercontent.com/5862639/151693057-281709b7-8f6b-4e5f-9f80-fedae046573b.png)

Acceso
![image](https://user-images.githubusercontent.com/5862639/151693082-89b574b6-7b8d-43dd-9e96-b0900c0f4553.png)

Dove sbaglio?

Grazie a tutti
