### DISCUSSION TITLE
accensione lampada ...

### DISCUSSION THREAD

**Discussion by RobyBS** [indomus/forum#1425] [HUB: Home Assistant]
Buongiorno a tutti ... 
sono alle prime armi e stavo iniziando con la prima scrittura nel file automation.yaml ... 

devo fare in modo che all'apertura della Porta Finestra Soggiorno , si accenda la Luce Terrazzo collegata ad uno shelly1 ... tutto presente sotto mqtt ... 

sbirciando in internet ed adeguando le righe di comando alla mia situazione sono arrivato a quanto sotto : 

```
#accensione lampada esterna 
  - trigger:
      platform: mqtt
      entity_id: binary_sensor.porta_finestra_soggiorno_door
      payload_on: 'open'
    condition: []
    action:
      service: light.turn_on
      data:
        entity_id: light.lampada_esterna

```

non posso verificare la correttezza in quanto per alcuni giorni sono fuori casa ... 

che dite ? può essere corretto ... 
se ok , vado avanti con implementare anche il discorso sunset , etc .. 

grazie 1000 !

**Comment by snakuzzo** [comment]
No...è sbagliato il trigger. Stai mischiando MQTT con il sensore. O scegli la publish MQTT oppure lo stato del sensore su HA. Io ti direi di scegliere la strada "sensore". E poi manca la dichiarazione dell'automazione.

Quindi...

```yaml
automation:

- id: accensione_lampada_apertura_porta
  alias: "Accensione Lampada Apertura Porta"
  trigger:
  - platform: state
    entity_id: binary_sensor.porta_finestra_soggiorno_door
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.lampada_esterna
```

**Comment by RobyBS** [comment]
.. cercavo la soluzione più immediata come comunicazione tra dispositivo e HA .. 
.. shelly con cloud ha un ritardo "importante" .. mqtt mi sembrava la linea più velove .. 


ma come dici tu , e ti ringrazio per la risposta ed il servizio impeccabile che dai a questo forum, la tua soluzione in pratica , prevede di non usare il messaggio di MQTT, ma direttamente lo stato del sensore che assume in HA ...

giusto ? 

così la cosa è ancor più snella ... 

se ho sbagliato concetto , ti chiedo scusa, e se me lo puoi spiegare  ... 👍

**Reply by snakuzzo** [reply]
Fermati un secondo...chiarisciti un attimo le idee.
Innanzi tutto stai basando il tutto su un sensore finestra....è uno shelly ???
Poi...considera che sugli Shelly di prima generazione, se abiliti MQTT, non avrai il cloud e comunque se usi l'integrazione nativa non passi comunque per il cloud...è tutto in locale. Usare l'evento MQTT o lo stato del sensore su HA a livello di performance non cambia assolutamente nulla.
Poi ripeto, volendo puoi pure utilizzare la publish MQTT, è una tua scelta...ma di solito per queste necessità non ha alcun senso...ci si basa direttamente sullo stato del sensore

**Comment by RobyBS** [comment]
ultima cortesia .. 
sul logbook il sensore appare sempre come "aperto / chiuso " ... 

nell'automazione devo comunque usare " on / off " o devo usare "aperto / chiuso " o peggio ancora " open / close " ... 

più che altro , mi chiarivo la cosa anche per le prossime codifiche ... 

grazie !

**Reply by snakuzzo** [reply]
Non confondere quello che vedi (`Aperto/Chiuso`) con lo stato dell'entità (`on/off`) sensore.
`Aperto/Chiuso` è solo una label che si basa sulla device_class e sulla localizzazione scelta, ma tu ti basi sullo stato dell'entità, quindi sempre `on/off`

**Comment by RobyBS** [comment]
tutto chiaro ...perfetto! .. 👍 
appena posso provo ... 
grazie 1.000

**Comment by RobyBS** [comment]
```
  action:
  - service: light.turn_on
    data:
      entity_id: switch.lampada_esterna
```

mi sono collegato tramite dns ed ho provato ... 

è corretto che per me , l'entità che si attiva con shelly1 , sia "switch" ?
con light non trovo entità sotto shelly ... forse devo cambiare anche la action "light.turn_on" .. :( 

ovviamente la prova ha dato esito negativo ... :( 

facendo una prova ed aggiungendo l'entità switch su lovelace , posso accendere e spegnere la lampadina come voglio ... 

```
type: entities
entities:
  - switch.lampada_esterna
title: Lampada Terrazzo


```

**Comment by RobyBS** [comment]
studiato un pochino sulla guida light_switch .. 

inserito in configuration.yaml le entità switch come light : 
```
light:
  - platform: switch
    name: Lampada Esterna
    entity_id: switch.lampada_esterna

  - platform: switch
    name: Lampada Soggiorno
    entity_id: switch.lampada_soggiorno
```

ed infine automation.yaml : 

```
- id: accensione_lampada_apertura_porta
  alias: "Accensione Lampada Apertura Porta"
  trigger:
  - platform: state
    entity_id: binary_sensor.porta_finestra_soggiorno_door
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: switch.lampada_esterna
```

sembra no funzionare ancora ... 
dove sbaglio ?

**Reply by snakuzzo** [reply]
se i nomi delle entità sono corretti...l'automazione è corretta.
Controlla i log

**Reply by xyzmauro** [reply]
Se hai usato la light switch perché poi nel l’automazione usi lo switch?
Light.turn_on -> light
Switch.turn_on -> switch

**Comment by RobyBS** [comment]
qui sotto il log .. 

l'automazione non fa nulla ... 
nemmeno dopo la correzione di light.turn_on  --> light.lampada_esterna ... 

2022-01-31 21:19:15 WARNING (MainThread) [homeassistant.helpers.entity] Entity media_player.e679a4ca_b142ef77 (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) implements device_state_attributes. Please report it to the custom component author.
2022-01-31 21:19:15 WARNING (MainThread) [homeassistant.helpers.entity] Entity light.e679a4ca_b142ef77 (<class 'custom_components.browser_mod.light.BrowserModLight'>) implements device_state_attributes. Please report it to the custom component author.
2022-01-31 21:19:15 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.e679a4ca_b142ef77 (<class 'custom_components.browser_mod.sensor.BrowserModSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-01-31 21:19:15 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1183, in _sendfile_fallback
read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 514, in start
resp, reset = await task
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 460, in _handle_request
reset = await self.finish_response(request, resp, start_time)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 613, in finish_response
await prepare_meth(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 286, in prepare
return await self._sendfile(request, fobj, offset, count)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 99, in _sendfile
await loop.sendfile(transport, fobj, offset, count)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1162, in sendfile
return await self._sendfile_fallback(transport, file,
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1192, in _sendfile_fallback
await proto.restore()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 263, in restore
self._transport.resume_reading()
File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 343, in resume_reading
self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'2022-01-31 21:19:15 WARNING (MainThread) [homeassistant.helpers.entity] Entity media_player.e679a4ca_b142ef77 (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) implements device_state_attributes. Please report it to the custom component author.
2022-01-31 21:19:15 WARNING (MainThread) [homeassistant.helpers.entity] Entity light.e679a4ca_b142ef77 (<class 'custom_components.browser_mod.light.BrowserModLight'>) implements device_state_attributes. Please report it to the custom component author.
2022-01-31 21:19:15 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.e679a4ca_b142ef77 (<class 'custom_components.browser_mod.sensor.BrowserModSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-01-31 21:19:15 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1183, in _sendfile_fallback
read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 514, in start
resp, reset = await task
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 460, in _handle_request
reset = await self.finish_response(request, resp, start_time)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 613, in finish_response
await prepare_meth(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 286, in prepare
return await self._sendfile(request, fobj, offset, count)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 99, in _sendfile
await loop.sendfile(transport, fobj, offset, count)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1162, in sendfile
return await self._sendfile_fallback(transport, file,
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1192, in _sendfile_fallback
await proto.restore()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 263, in restore
self._transport.resume_reading()
File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 343, in resume_reading
self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'


se uso invece light.turn-on --> light.lampada esterna ...
ottengo questi log ...

2022-01-31 21:26:39 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration tesla_custom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-31 21:26:44 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547630012880] Received invalid command: browser_mod/connect
2022-01-31 21:26:45 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547630012880] Received invalid command: browser_mod/update

non mi sembra che siano di aiuto ... :( ...

**Comment by RobyBS** [comment]
se vado su strumenti per sviluppatori .. e chiamo i servizi light e switch .. on e off ... funzionano perfettamente !

che rabbia ! ...

**Reply by xyzmauro** [reply]
Ma lo hai scritto con le frecce?!? 🙄

  action:
  - service: light.turn_on
    data:
      entity_id: light.lampada_esterna

**Reply by RobyBS** [reply]
no ... riporto testualmente ... 
```

- id: accensione_lampada_apertura_porta
  alias: "Accensione Lampada Apertura Porta"
  trigger:
  - platform: state
    entity_id: binary_sensor.porta_finestra_soggiorno_door
    to: 'on'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.lampada_esterna
```

**Reply by xyzmauro** [reply]
Controlla il trigger,se non parte l’automazione è il trigger,magari il nome

**Comment by RobyBS** [comment]
questo il file debug json .. se può essere utile ...

```
{
  "trace": {
    "last_step": "action/0",
    "run_id": "e7554b11ab905f7ffd1ad1c611fc47f5",
    "state": "stopped",
    "script_execution": "finished",
    "timestamp": {
      "start": "2022-01-31T21:23:05.589618+00:00",
      "finish": "2022-01-31T21:23:05.628908+00:00"
    },
    "domain": "automation",
    "item_id": "accensione_lampada_apertura_porta",
    "trigger": null,
    "trace": {
      "trigger": [
        {
          "path": "trigger",
          "timestamp": "2022-01-31T21:23:05.589970+00:00",
          "changed_variables": {
            "this": {
              "entity_id": "automation.accensione_lampada_apertura_porta",
              "state": "on",
              "attributes": {
                "last_triggered": "2022-01-31T21:23:03.850447+00:00",
                "mode": "single",
                "current": 0,
                "id": "accensione_lampada_apertura_porta",
                "friendly_name": "Accensione Lampada Apertura Porta"
              },
              "last_changed": "2022-01-31T21:19:25.219275+00:00",
              "last_updated": "2022-01-31T21:23:03.895760+00:00",
              "context": {
                "id": "5cd1a20f17b2fe1d9117bc113d35e274",
                "parent_id": "f5640947a072b1ba1d05c186a36fc9e7",
                "user_id": null
              }
            },
            "trigger": {
              "platform": null
            }
          }
        }
      ],
      "action/0": [
        {
          "path": "action/0",
          "timestamp": "2022-01-31T21:23:05.592698+00:00",
          "changed_variables": {
            "context": {
              "id": "e0ef308dad783fbe072e173975416f20",
              "parent_id": "eddf7cf2a00ad1e839de6db1092bdeb4",
              "user_id": null
            }
          },
          "result": {
            "params": {
              "domain": "switch",
              "service": "turn_on",
              "service_data": {
                "entity_id": "switch.lampada_esterna"
              },
              "target": {}
            },
            "running_script": false,
            "limit": 10
          }
        }
      ]
    },
    "config": {
      "id": "accensione_lampada_apertura_porta",
      "alias": "Accensione Lampada Apertura Porta",
      "trigger": [
        {
          "platform": "state",
          "entity_id": "binary_sensor.porta_finestra_soggiorno_door",
          "to": "on"
        }
      ],
      "action": [
        {
          "service": "switch.turn_on",
          "data": {
            "entity_id": "switch.lampada_esterna"
          }
        }
      ]
    },
    "blueprint_inputs": null,
    "context": {
      "id": "e0ef308dad783fbe072e173975416f20",
      "parent_id": "eddf7cf2a00ad1e839de6db1092bdeb4",
      "user_id": null
    }
  },
  "logbookEntries": [
    {
      "name": "Accensione Lampada Apertura Porta",
      "message": "has been triggered",
      "source": null,
      "entity_id": "automation.accensione_lampada_apertura_porta",
      "context_id": "e0ef308dad783fbe072e173975416f20",
      "when": "2022-01-31T21:23:05.590647+00:00",
      "domain": "automation"
    }
  ]
}
```

**Comment by RobyBS** [comment]
tutto risolto ... 

forse uno spazio in meno prima di entity_id ... 
o forse .. ho tolto switch ... ed usato solo light ... 
ora sembra tutto funzionare ... 


grazie a tutti per il supporto e soprattutto la pazienza ! ... 👍 👍 👍

**Reply by snakuzzo** [reply]
comunque...
NON CREARE NUOVI THREAD...FAI REPLY SOTTO L'ULTIMA RISPOSTA. 
In questa discussione non si capisce niente...hai aperto ogni volta thread nuovi.

**Reply by RobyBS** [reply]
ok ... hai ragione ... 
grazie ancora per il supporto ! 👍

**Comment by RobyBS** [comment]
... adesso vorrei che la lampada si accendesse , solo un'ora prima che faccia notte ( tramonto ) e fino a mezz'ora dopo l'alba ...

questa la mia automation :

```
- id: accensione_lampada_apertura_porta
  alias: "Accensione Lampada Apertura Porta"
  trigger:
  - platform: state
    entity_id: binary_sensor.porta_finestra_soggiorno_door
    to: 'on'
  - condition: sun        **" qui Studio Code Server mi dice --> Missing property "device_id" .**
    after: sunset
    after_offset: "-01:00:00"
    before: sunrise
    before_offset: "+00:30:00"
  action:
  - service: light.turn_on
    data:
      entity_id: light.lampada_esterna
```

cosa sbaglio ? .. grazie ...

**Reply by RobyBS** [reply]
trovato il problema ... 
era un errore di sintassi della condition ... 

corretto in : 

```
  condition: 
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
      before: sunrise
      before_offset: "+00:30:00"
```

detto questo ... e fatto le opportune verifiche ... l'automazione non funziona ... :( ...
... sbaglio forse il concetto ? 
in configuration.yaml ho inserito la stringa : 
`sun:`

**Reply by snakuzzo** [reply]
Sì ma tu non puoi limitarti a dire "NON FUNZIONA".
Prendi l'automazione, togli la condition e prova. Se va devi cominciare a vedere cosa accade. Mai usato questa condition, quindi non so dirti se è scritta correttamente oppure no. Ad ogni modo, se hai impostato l'id all'automazione, vai su lovelace sotto configruations > Automations e in fondo a destra, in corrispondenza di questa automazione, c'è il tastino per fare il debug
Altra cosa...devi imparare a vedere cosa viene loggato da Core.
Imposta il livello di log a debug per le automazioni nel `configuratoin.yaml`

```
logger:
  default: warning
  logs:
    homeassistant.components.automation: debug
```

...e guarda cosa accade quando scatta.
