### DISCUSSION TITLE
Visualizzazione variabile in Plancia e evento correlato

### DISCUSSION THREAD

**Discussion by mriitan** [indomus/forum#1426] [HUB: Home Assistant]
Ciao a tutti,

ho questo quesito sperando di ricevere una soluzione applicabile.
Vorrei che ogni volta che il valore della temperatura del termostato viene variata, da dispositivo fisico o da app, una variabile che devo poi andare a visualizzare in plancia prenda quel valore di temperatura e lo moltiplichi per una dato numero.
Vorrei capire come intercettare la variazione della temperatura generata dalla richiesta da me fatta (sempre via termostato fisico che da app) e come pubblicare questa variabile che ho creato.
Grazie

**Comment by snakuzzo** [comment]
Crea un'automazione con trigger sulla variazione dell'attributo "current_temperature" dell'entità di tipo "climate" e poi nella action sfrutti il [trigger object](https://www.home-assistant.io/docs/automation/templating/#available-trigger-data) per fare quello che ti pare.

**Comment by mriitan** [comment]
Ciao, ho creato questa automazione, che in seguito ad un trigger boeano va a scrivere la temperatura del termostato a 4.
Fin qui tutto ok, vorrei però che quel 4 divenisse la temperatura di un "aiutante" numerico.
Insomma scrivo il numero di questo aiutante, premo un tasto e l'automazione va a impostare la temperatura.
Il top sarebbe che il dto dell'aiutante fosse non da scrivere ma da settare come una manopola, e che al termine della selezione faccia l'operazione di scrivere verso il termostato.
Grazie

```
id: '1643910772603'
alias: Trasforma in Gradi
description: ''
trigger:
  - platform: state
    entity_id: automation.trasforma_in_gradi
    from: 'off'
    to: 'on'
condition: []
action:
  - service: climate.set_temperature
    data:
      temperature: 4
    target:
      device_id: 37ad0bf4ce3d1cf1531753741b0c081f
mode: single
```

**Reply by xyzmauro** [reply]
Ciao,non ho sinceramente capito come questa automazione risponda all’esigenza del tuo primo post ma ok…
Per qst seconda necessità non potresti usare una thermostat card che serve proprio per controllare un’entità climate? 🤔

**Reply by mriitan** [reply]
certo che potrei, peccato che il termostato in questione è uno di quelli che non si integra correttamente e riporta la temperatura in modo non corretto, di qui la mia esigenza

**Reply by xyzmauro** [reply]
Puoi usare un imput_number a slider che sarà trigger della tua automazione e nell’action come diceva già @snakuzzo usi il trigger object per settare la temperatura sul climate

**Reply by xyzmauro** [reply]
https://www.home-assistant.io/integrations/input_number/
la prima automazione di esempio fa proprio quel che cerchi,se ho ben capito cosa vuoi fare

**Reply by mriitan** [reply]
ho scritto questa: 
```
- id: '1643910772603'
  alias: 1)Trasforma in Gradi 16
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.1_setta_temperatura
    attribute: options
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_select.1_temperatura_scelta
    state: '16'
    attribute: options
  action:
  - service: climate.set_temperature
    data:
      temperature: 3.2
    target:
      device_id: 37ad0bf4ce3d1cf1531753741b0c081f
  mode: single
```
funziona, se eseguo l'automazione da esegui azioni funziona, se invece trigger il tasto non si aggiorna la temp sul termostato.... come mai secondo voi?
grazie

**Reply by mriitan** [reply]
```
- id: '1643910772603'
  alias: 1)Trasforma in Gradi 16
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.1_setta_temperatura
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_select.1_temperatura_scelta
    state: '16'
  action:
  - service: climate.set_temperature
    data:
      temperature: 3.3
    target:
      device_id: 37ad0bf4ce3d1cf1531753741b0c081f
  mode: single
```
andava tolto l'attributo, funziona, grazie mille
