### DISCUSSION TITLE
Integrazione lampada Yeelight

### DISCUSSION THREAD

**Discussion by Picchios** [indomus/forum#1433] [HUB: Home Assistant]
Buongiorno,
ho una lampada smart Yeelight che ha funzionato regolarmente con Hassio con la sua integrazione ufficiale fino a ieri, configurata con IP statico dal router.
Ho cambiato SSID e password alla wifi, e ora, riconfigurandola, non viene vista minimamente dall'integrazione, nè lasciando il campo dell'host vuoto in modalità "ricerca", nè scrivendo l'IP.

![immagine](https://user-images.githubusercontent.com/97951117/152143991-525af39b-4e1d-4347-b325-9847317edfc7.png)

Allora ho provato a scrivere nel file di configurazione quanto segue:

```
discovery:
  ignore:
    - yeelight

yeelight:
  devices:
    192.168.1.65:
      name: Lampada Camera
```

Non cambia nulla, non sò cosa sto sbagliando.
PS. la lampada funziona regolarmente con l'app Xiaomi/Yeelight e viene riconosciuta subito in Alexa.

Cosa posso fare? Grazie
