### DISCUSSION TITLE
integrare impianto eurotherm riscaldamento/raffrescamento

### DISCUSSION THREAD

**Discussion by dibummer** [indomus/forum#1439] [HUB: Home Assistant]
Buongiono,
un saluto a tutti, sono un nuovo iscritto e solo da pochi giorni ho installato Home Assistant OS sul Qnap  in modo virtuale.
gentilmente qualcuno potrebbe aiutarmi ad integrare il mio sistema di riscaldamento e raffreddamento marca eurotherm, siccome pare, anzi non ho trovato il modo in cui farlo. il sistema lo gestisco da SmartComfort 365.
grazie della collaborazione.

**Comment by virgafox** [comment]
Ciao, leggo dalle specifiche di smartcomfort365 che supporta Modbus TCP tramite la porta di rete, quindi immagino che questo potrebbe essere un modo per farlo, ma più di questo non saprei dirti.

**Comment by FabrizioFarnetI** [comment]
per caso è poi riuscito a fare questa integrazione? anche io sarei interessato.
Grazie

**Comment by dibummer** [comment]
No. Sarebbe notevole trovare una soluzione.

**Comment by sbetelgeuse** [comment]
Anche io sarei interessato

**Comment by FabrizioFarnetI** [comment]
Se ci fosse un'anima gentile che ne sa più di me ci aiuta ad integrare questo apparato ne sarei davvero felice.
Io ho ottenuto questo documento che riporta le specifiche per l'integrazione tramite MODBUS, ma non sono in grado di sfruttarlo.
[Communication Protocol SmartComfort 365_Rev05.pdf](https://github.com/indomus/forum/files/12831878/Communication.Protocol.SmartComfort.365_Rev05.pdf)

**Comment by FabrizioFarnetI** [comment]
Sono riuscito a leggere tutti i dati disponibili da Eurotherm usando il MODDBUS TCP,  E' stato molto semplice.
Nel mio caso ho lo smartcontrol365 ed un deumidificatore (che però non sono certo di avere interpretato bene).
il Modbus era già attivo (viene usato dal Eurotherm) per cui per leggere i dati di tutti i sensori delle stanze basta aggiungere queste righe al CONFIGURATION.YAML

# CONFIGURAZIONE MODBUS PER EUROTHERM SMARTCONTROL365
modbus:
  - name: modbus_smart365
    type: tcp
    host: 192.168.1.25
# INDICATE QUI SOPRA l'indirizzo IP che è usato dallo smartcontrol (nel mio caso wifi)
    port: 502
    retries: 3
    timeout: 5
    
    sensors:
      - name: temp_esterna_smart365
        unit_of_measurement: °C
        slave: 1
        address: 58
        scale: 0.1
        precision: 1
        data_type: int16
        scan_interval: 30
        
      - name: freddo_caldo_smart365
        slave: 1
        address: 101
        data_type: int16
        scan_interval: 30
        
      - name: modalita_smart365
        slave: 1
        address: 102
        data_type: int16
        scan_interval: 30
        
      - name: Air_boost_smart365
        slave: 1
        address: 103
        data_type: int16
        scan_interval: 30
        
# STANZA 1 CAMERA LETTO
      - name: temp_stanza1
        unit_of_measurement: °C
        address: 1205
        slave: 1
        scale: 0.1
        precision: 1
        data_type: int16
        scan_interval: 30

      - name: umidita_stanza1
        unit_of_measurement: "%"
        slave: 1
        precision: 1
        address: 1206
        scan_interval: 30
        
      - name: temp_target_stanza1
        unit_of_measurement: °C
        scale: 0.1
        slave: 1
        address: 1208
        precision: 1
        data_type: int16
        scan_interval: 30
        
      - name: mode_stanza1
        address: 1209
        slave: 1
        precision: 1
        data_type: int16
        scan_interval: 30
        
# STANZA 2 PALESTRA        
      - name: temp_stanza2
        unit_of_measurement: °C
        address: 1605
        slave: 1
        scale: 0.1
        precision: 1
        data_type: int16
        scan_interval: 30

      - name: umidita_stanza2
        unit_of_measurement: "%"
        slave: 1
        precision: 1
        address: 1606
        scan_interval: 30
        
      - name: temp_target_stanza2
        unit_of_measurement: °C
        scale: 0.1
        slave: 1
        address: 1608
        precision: 1
        data_type: int16
        scan_interval: 30
        
      - name: mode_stanza2
        address: 1609
        slave: 1
        precision: 1
        data_type: int16
        scan_interval: 30

# STANZA 3 BAGNO
      - name: mode_stanza3
        address: 2009
        slave: 1
        precision: 1
        data_type: int16
        scan_interval: 30

      - name: temp_stanza3
        unit_of_measurement: °C
        address: 2005
        slave: 1
        scale: 0.1
        precision: 1
        data_type: int16
        scan_interval: 30

      - name: umidita_stanza3
        unit_of_measurement: "%"
        slave: 1
        precision: 1
        address: 2006
        scan_interval: 30
        
      - name: temp_target_stanza3
        unit_of_measurement: °C
        scale: 0.1
        slave: 1
        address: 2008
        precision: 1
        data_type: int16
        scan_interval: 30
        
# STANZA 4 SOGGIORNO
      - name: mode_stanza4
        address: 2409
        slave: 1
        precision: 1
        data_type: int16
        scan_interval: 30

      - name: temp_stanza4
        unit_of_measurement: °C
        address: 2405
        slave: 1
        scale: 0.1
        precision: 1
        data_type: int16
        scan_interval: 30

      - name: umidita_stanza4
        unit_of_measurement: "%"
        slave: 1
        precision: 1
        address: 2406
        scan_interval: 30
        
      - name: temp_target_stanza4
        unit_of_measurement: °C
        scale: 0.1
        slave: 1
        address: 2408
        precision: 1
        data_type: int16
        scan_interval: 30 
        
# STANZA 5 CUCINA
      - name: mode_stanza5
        address: 2809
        slave: 1
        precision: 1
        data_type: int16
        scan_interval: 30

      - name: temp_stanza5
        unit_of_measurement: °C
        address: 2805
        slave: 1
        scale: 0.1
        precision: 1
        data_type: int16
        scan_interval: 30

      - name: umidita_stanza5
        unit_of_measurement: "%"
        slave: 1
        precision: 1
        address: 2806
        scan_interval: 30
        
      - name: temp_target_stanza5
        unit_of_measurement: °C
        scale: 0.1
        slave: 1
        address: 2808
        precision: 1
        data_type: int16
        scan_interval: 30

Fatto questo, solo per avere i valori descrittivi della modalità impostata e del modo 'casa' scrivete anche questo nella sezione SENSOR (io l ho in un file separato)

#smartcontro365

  - platform: template
    sensors:
      modo_circolazione_smart365:
        friendly_name: "modo_circolazione_smart365"
        entity_id: sensor.freddo_caldo_smart365
        value_template: >-
          {% if states('sensor.freddo_caldo_smart365') == '0' %}
            Raffrescamento
          {% elif states('sensor.freddo_caldo_smart365') == '1' %}
            Riscaldamento
          {% endif %}
      modo_presenza_smart365:
        friendly_name: "Modo Presenza"
        entity_id: sensor.modalita_smart365
        value_template: >-
          {% if states('sensor.modalita_smart365') == '0' %}
            in Casa
          {% elif states('sensor.modalita_smart365') == '1' %}
            Spento
          {% elif states('sensor.modalita_smart365') == '2' %}
            Fuori casa
          {% elif states('sensor.modalita_smart365') == '3' %}
            in Vacanza            
          {% endif %}

Questo è il risultato
![image](https://github.com/indomus/forum/assets/25442874/169ee228-ec94-4141-b5ea-cc0ae8af46c0)
 
Spero di aver fatto cosa gradita, riallego il manuale senza il quale non sarei riuscito
Se riuscite a fare altro (tipo pilotarlo da HA) condividetelo, 
Grazie

**Reply by FabrizioFarnetI** [reply]
[Communication Protocol SmartComfort 365_Rev05.pdf](https://github.com/indomus/forum/files/12846735/Communication.Protocol.SmartComfort.365_Rev05.pdf)
manuale modbus

**Reply by lucacristofori** [reply]
Ciao Fabrizio e grazie della preziosa consulenza. Con Communication Protocol SmartComfort 365_Rev05.pdf riesco a vedere ed eventulamente scrivere tutti i registri indicati, putroppo però nel protocollo non ho trovato alcuni registri che vorrei controllare (ad esempio portata dell'aria di rinnovo, abilitazione o meno del rinnovo ecc ecc). Ho chiesto ad Eurotherm ma la loro risposta è stata "Le portate della macchina aria vengono definite a bordo macchina aria ... Per quanto riguardano i registri della macchina aria, questi non sono fornibili." 
Visto che comunque li posso modificare tramite Smartcomfort 365 sicuramente l'informazione tramite ModBus verrà data alla macchina, qualcuno sa come "sniffare" i dati inviati e/o come trovare gli indirizzi di questi registri?
Grazie a tutti

**Comment by dibummer** [comment]
Ciao Fabrizio, grazie dello sforzo e la condivisione del lavoro che hai fatto; 
nel copiare le righe di configurazione in un file .yaml nella sessione package e il file dei sensori in un file separato nella sessione sensori non funziona;
nella verifica della configurazione mi dà errore del package.
se hai la possibilità di suggerirmi qualche idea ti ringrazio.

**Reply by FabrizioFarnetI** [reply]
ti allego un file con il codice copiato dal mio configuration.yaml

[codice_yaml.txt](https://github.com/indomus/forum/files/12897766/codice_yaml.txt)
l indentazione è quella che vedi qui sotto
prova a vedere se cos riesci oppure segnalami l'errore ma non sono esperto di yaml


![image](https://github.com/indomus/forum/assets/25442874/6c994abf-357b-4947-94cd-1a2a99b89584)

**Comment by dibummer** [comment]
grazie, non mi dà errore, riconosciuto al primo colpo.
quale scheda hai utilizzata per le rilevare le informazioni.
grazie di nuovo

**Comment by FabrizioFarnetI** [comment]
Una normale scheda Entità


Il ven 13 ott 2023, 22:53 dibummer ***@***.***> ha scritto:

**Reply by dibummer** [reply]
Perfetto. Grazie

**Comment by dibummer** [comment]
un'ultimo aiuto, almeno spero:
scrivi"Fatto questo, solo per avere i valori descrittivi della modalità impostata e del modo 'casa' scrivete anche questo nella sezione SENSOR (io l ho in un file separato)
ho scritto nella sessione sensor della mia configurazione yaml le tue righe di comando, tuttavia risulta invalida la configurazione, credo che sia l'indentazione ecco lo screenshot:
<img width="1033" alt="Screenshot 2023-10-14 alle 18 08 42" src="https://github.com/indomus/forum/assets/98668218/cb137f22-220e-453f-8cc5-62edd47a2480">

**Comment by GeomDiego** [comment]
Scusatemi, potete togliermi un dubbio??????
ma tramite protocollo modbus posso solo vedere i valori o posso anche modificarli per dare "input" al termostato?
tipo cambiare la temperatura terghet?

**Comment by FabrizioFarnetI** [comment]
Se ti riferisci allo smart 365, io posso sono vedere i valori senza
modificarli, ma non ho fatto tentativi in tal senso, magari è solo un
problema di interfaccia perchè se lo setto dagli STATI in MODO
SVILUPPATORE, accetta la modifica.
Invece la PDC DAIKIN si setta anche da interfaccia di HA

Il giorno mar 19 dic 2023 alle ore 23:16 GeomDiego ***@***.***>
ha scritto:

> Scusatemi, potete togliermi un dubbio??????
> ma tramite protocollo modbus posso solo vedere i valori o posso anche
> modificarli per dare "input" al termostato?
> tipo cambiare la temperatura terghet?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/indomus/forum/discussions/1439#discussioncomment-7902369>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGCDUOTE5772FOXVPN34RNDYKIG2FAVCNFSM5NOE57F2U5DIOJSWCZC7NNSXTOKENFZWG5LTONUW63SDN5WW2ZLOOQ5TOOJQGIZTMOI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>


-- 
Fabrizio Farneti

**Comment by Bergoglio** [comment]
Piccola notazione : nella tabella dei parametri / indirizzi sul manuale c'è la colonna "Access": se il valore è RO si può solo leggere (Read Only), se il valore è RW si può leggere e modificare da Home Assistant (Read Write)

**Reply by GeomDiego** [reply]
oddio quanto ti adoro per questa risposta.
anche se questi parametri dovrebbero essere nelle impostazioni avanzate dove serve la password dell'installatore per accedere.
sbaglio?

**Reply by Bergoglio** [reply]
Non ho sottomano il componente specifico, ma a naso direi che sono parametri da impostazioni avanzate e non da utente qualunque.

**Comment by alexdev03** [comment]
Scusate ma questo sistema si può fare senza accessi da tecnico?

**Reply by GeomDiego** [reply]
la parte che riguarda i valori dei sensori, ovvero ottenere i dati di temperatura, umidità ed attuale impostazione del termostato (se automatico o manuale o se in casa o fuori casa), si si può fare senza l'accesso del tecnico.
mentre quello che riguarda il poter modificare le impostazioni di temperatura e tutto il resto, non lo so ma ho il sospetto che serva accedere alle impostazioni avanzate che sono protette dalla password del tecnico

**Reply by alexdev03** [reply]
Grazie, come posso ricavare i dati dei sensori da inserire poi nel yaml?

**Reply by GeomDiego** [reply]
lo ha scritto sopra FabrizioFarneti
https://github.com/indomus/forum/discussions/1439#discussioncomment-7276782

**Comment by Bergoglio** [comment]
Domanda : ma qualcuno ha provato a scrivere un parametro da modbus ?

**Reply by GiulioBen** [reply]
https://github.com/indomus/forum/discussions/1439#discussioncomment-12126097

**Comment by alsadamo** [comment]
Buonasera, qualcuno è riuscito a gestire/comandare lo smartcomfort365 di Eurother tramite MODBUS TCP? Leggendo i passaggi qui sopra sono riuscito a leggere tutti i valori, ma ora vorrei comandarlo per modificare i vari stadi e creare qualche automazione.

Grazie.

**Reply by GeomDiego** [reply]
ho provato a chiedere alla ditta che lo ha prodotto, ma dopo vari tentativi in più giorni dove ogni volta attendevo una risposta da parte della sezione tecnica,, mi hanno detto di no, si possono solo visualizzare i valori egli stati ma non modificarli.

non sono sicuro che sia realmente così, ma questa è la risposta che mi hanno dato

**Reply by GiulioBen** [reply]
> ho provato a chiedere alla ditta che lo ha prodotto, ma dopo vari tentativi in più giorni dove ogni volta attendevo una risposta da parte della sezione tecnica,, mi hanno detto di no, si possono solo visualizzare i valori egli stati ma non modificarli.
> 
> non sono sicuro che sia realmente così, ma questa è la risposta che mi hanno dato

ovviamente ciò è falso, tuttavia non sembra possibile impostare su off una stanza. Vedi https://github.com/indomus/forum/discussions/1439#discussioncomment-12126097

**Comment by FabioG85** [comment]
Ciao, sì è possibile comandarlo. Io ho lo smartone, ma ho visto che bene o male i registri sono gli stessi dello smart control 365
Qui sotto il codice di configurazione per accendere / spegnere da cui si può prendere spunto.
PS:
@FabrizioFarnetI vedi se ti può interessare

 ```
# CONFIGURAZIONE MODBUS PER EUROTHERM SMARTONE
modbus:
  - name: modbus_smartone_1
    type: tcp
    host: ----ip_address----
    port: 502
    
    switches:
      - name: modbus_smartone_1.funzionamento
        unique_id: "modbus_smartone_1.funzionamento-on-off"
        slave: 1
        address: 102
        command_on: 0
        command_off: 1
        write_type: holding
        verify:
            input_type: holding
            address: 102
            state_on: 0
            state_off: 1

    sensors:
      - name: temp_esterna_smartone_1
        unit_of_measurement: °C
        slave: 1
        address: 58
        scale: 0.1
        precision: 1
        data_type: int16
        
      - name: freddo_caldo_smartone_1
        slave: 1
        address: 101
        data_type: int16
        
      - name: air_boost_smartone_1
        slave: 1
        address: 103
        data_type: int16

# Sensore
      - name: temp_smartone_1
        unit_of_measurement: °C
        address: 1205
        slave: 1
        scale: 0.1
        precision: 1
        data_type: int16

      - name: umidita_smartone_1
        unit_of_measurement: "%"
        slave: 1
        precision: 1
        address: 1206
        
      - name: temp_target_smartone_1
        unit_of_measurement: °C
        scale: 0.1
        slave: 1
        address: 1208
        precision: 1
        data_type: int16

      - name: mode_smartone_1
        address: 1209
        slave: 1
        data_type: int16
 ```

**Reply by GeomDiego** [reply]
provato e funziona benissino !!!!!!!!!
in questo momento ti sto adorando, sei il numero 1 🥇

**Reply by alsadamo** [reply]
@FabioG85 miticoooo! Funziona perfettamente, grazie mille! Con lo stesso principio ho già impostato anche lo switch riscaldamento/raffrescamento. Grazie ancora! ☺️

**Reply by M-Foroni** [reply]
> @FabioG85 miticoooo! Funziona perfettamente, grazie mille! Con lo stesso principio ho già impostato anche lo switch riscaldamento/raffrescamento. Grazie ancora! ☺️

lo puoi incollare?

**Reply by Diego79S** [reply]
Buongiorno, ho anche io uno SmartOne e non riesco a collegarlo a Home Assistant... ho inserito l'IP del dispositivo (che è in WIFI) ed ho provato a copiare il codice sopra in configuration.yaml e dopo il riavvio mi indica sensori non disponibili. mi confermate che con Smart One è possibile la connessione Wifi? grazie

**Reply by narco85spam** [reply]
> Buongiorno, ho anche io uno SmartOne e non riesco a collegarlo a Home Assistant... ho inserito l'IP del dispositivo (che è in WIFI) ed ho provato a copiare il codice sopra in configuration.yaml e dopo il riavvio mi indica sensori non disponibili. mi confermate che con Smart One è possibile la connessione Wifi? grazie

Devi abilitare il modbus sullo smartone, altrimenti non funziona

**Reply by Diego79S** [reply]
Grazie, potresti spiegarmi come si fa? devo contattare Eurotherm? grazie per il supporto

**Reply by narco85spam** [reply]
Devi guardare nel menù dello smartone, non ricordo se avanzate o preferenze, prova a guardare li dentro

**Reply by Diego79S** [reply]
Perfetto! questa sera verifico... grazie ancora!

**Reply by Diego79S** [reply]
Ciao, ho trovato il menu avanzate però per l’a cesso chiede il codice di sicurezza.. penso sia uguale per tutti.. però non so qual’e’.. potete indicarmelo? Grazie

**Reply by matteomioni** [reply]
Per caso qualcuno ha poi condiviso il codice di sicurezza per il menu avanzato? Grazie

**Comment by M-Foroni** [comment]
Qualcuno sa come creare i vari sensori tipo  zone mode, o settaggio temperatura in ogni zona?

**Reply by GiulioBen** [reply]
https://github.com/indomus/forum/discussions/1439#discussioncomment-12126097
descritto a seguire

**Comment by GiulioBen** [comment]
Visto che molti lo chiedono ma nessuno sembra aver capito bene come fare butto lì due idee:

Nel file configuration.yaml ho aggiunto

```
# CONFIGURAZIONE MODBUS PER EUROTHERM SMARTCONTROL365
modbus: !include eurotherm.yaml
```

aggiunto il file eurotherm.yaml nella stessa folder con codice come segue:

```
name: modbus_smart365
type: tcp
host: 192.168.14.220
port: 599


climates:
  - name: "giu_soggiorno"
    address: 1205
    slave: 1
    scale: 0.1
    precision: 1
    data_type: int16
    target_temp_register: 1210
    target_temp_write_registers: true
    hvac_mode_register:
      address: 1209
      write_registers: false
      values:
        state_off: 0
        state_auto: 1
        state_heat: 2

sensors:
  - name: temp_ext_smart365
    unit_of_measurement: °C
    slave: 1
    address: 58
    scale: 0.1
    precision: 1
    data_type: int16
    scan_interval: 30
    
  - name: freddo_caldo_smart365
    slave: 1
    address: 101
    data_type: int16
    scan_interval: 30
    
  - name: modalita_smart365
    slave: 1
    address: 102
    data_type: int16
    scan_interval: 30
    
  - name: air_boost_smart365
    slave: 1
    address: 103
    data_type: int16
    scan_interval: 30
    
    
# STANZA 1 SOGGIORNO
    
  - name: umid_giu_soggiorno
    unit_of_measurement: "%"
    slave: 1
    precision: 1
    address: 1206
    scan_interval: 30
    
  - name: temp_target_giu_soggiorno
    unit_of_measurement: °C
    scale: 0.1
    slave: 1
    address: 1208
    precision: 1
    data_type: int16
    scan_interval: 30
```


ovviamente IP, porta e vari sensori vanno configurati a piacere ricordandosi che se si ha più di una scheda (io ne ho una per piano) bisogna aggiungere 3260 al valore del registro.

L'integrazione più attinente risulta la seguente (nella plancia)

```
type: thermostat
entity: climate.giu_soggiorno
features:
  - style: icons
    type: climate-hvac-modes
    hvac_modes:
      - "off"
      - auto
      - heat
grid_options:
  columns: 12
  rows: 6
name: Soggiorno
```


![image](https://github.com/user-attachments/assets/c85adb1c-ba51-433e-ad12-bceb842a08bf)

Sfortunatamente il valore "off" è RO, quindi non si può modificare. Bisognerà impostare una temperatura bassa nell'automazione.

Qualcuno sa come scrivere "off" sul modbus per una specifica ZONA?

Grazie
