### DISCUSSION TITLE
Problema proximity sensor

### DISCUSSION THREAD

**Discussion by metcrl** [indomus/forum#1447] [HUB: Home Assistant]
Buongiorno,
come avevo accennato in chat, di recente ho problemi col proximity sensor. Nello specifico: ho impostato un sensore proximity basato sulla lontananza da casa, il problema è che a volte è come se "seguisse" un solo device/person tra quelle in lista. Ad esempio ieri 2 device su 3 erano in casa (confermato anche dal gruppo famiglia in stato "home" e dallo stato degli stessi), mentre il terzo device si stava allontanando.
Ebbene, il sensore proximity, che ho anche in una scheda lovelace, segnava il dispositivo più vicino a 15km (ovvero dove si trovava il terzo device). Questo ovviamente ha fatto scattare tutte le automazioni che lo utilizzano.
Ho provato a creare 2 sensori identici, uno che usa "device.tracker" e uno che usa "person" e ora come ora uno segna distanza 0 (giustamente, visto che ci sono smartphone a casa) mentre l'altro segna 5 (cioè la distanza alla quale si trova uno solo dei 3 device).
C'è qualcosa che mi sfugge?
p.s. la posizione in mappa, lo stato home/not_home dei dispositivi e del gruppo famiglia funzionano perfettamente.

Questo il codice:
```
proximity:
  casa:
    zone: home
    devices:
      - person.tizio
      - person.caio
      - person.ciccio
    tolerance: 100
    unit_of_measurement: km
  casa2:
    zone: home
    devices:
      - device_tracker.sm_aaa
      - device_tracker.sm_bbb
      - device_tracker.sm_ccc
    tolerance: 100
    unit_of_measurement: km
```

Se possibile vi manderei anche uno screen che mostra la differenza tra i due sensori (nello stesso momento uno segna 0, l'altro 5)
Grazie mille
