### DISCUSSION TITLE
Passaggio da Watt a KW

### DISCUSSION THREAD

**Discussion by mriitan** [indomus/forum#1450] [HUB: Home Assistant]
![image](https://user-images.githubusercontent.com/98173792/152522846-b9c0aa40-f2ea-4784-914f-aa576ad95301.png)
ciao ho questa situazione in alto.
Il sensore potenza è dichiarato in config con:
```
  - platform: template
    sensors:
      voltaggio:
        value_template: "{{ state_attr('switch.sonoff_100147ba1a', 'voltage') }}"
      amperaggio:
        value_template: "{{ state_attr('switch.sonoff_100147ba1a', 'current') }}"
      potenza:
        value_template: "{{ state_attr('switch.sonoff_100147ba1a', 'power') }}"
```
poi ho visto la possibilità di usare integrazione Riemann e quindi ho inserito sempre in config:

```
  - platform: integration
    source: sensor.potenza
    name: Potenza_istantanea
    unit_prefix: k
    round: 2
```

ma il risultato è quello dell'immagine, Potenza 384, Potenza istantanea 0,09 ma non vedo nemmeno il prefisso k, mi sta sfuggendo qualcosa?
la potenza istantanea la considera in KWh? per cui 384/24? è questa la formula che adotta?

inoltre per i consumi mese/giorno come faccio anche li a passare a KW, grazie
