### DISCUSSION TITLE
Home Assistant Docker Compose - Accesso a i file negato

### DISCUSSION THREAD

**Discussion by DaviBax** [indomus/forum#1465] [HUB: Home Assistant]
Ho seguito passo passo tutte queste vostre guide per creare una nuova installazione di `HA` su `Docker Compose`:

[Installare e configurare Raspberry Pi con Raspberry Pi OS (Raspbian)](https://indomus.it/guide/come-installare-e-configurare-raspberry-pi/)	
[Le prime cose da fare dopo aver installato Raspberry Pi OS (Raspbian)](https://indomus.it/guide/le-prime-cose-da-fare-dopo-aver-installato-raspberry-con-raspbian/)	
[Come installare Docker su Raspberry Pi OS (Raspbian) di Raspberry Pi](https://indomus.it/guide/come-installare-docker-su-raspberry-pi-con-raspbian/)
[Installare e configurare Home Assistant Core con Docker su Raspberry Pi
](https://indomus.it/guide/come-installare-e-configurare-home-assistant-core-con-docker-su-un-raspberry-pi-gia-in-uso/)

Poi seguendo questa altra guida ho configurato `VSCode`:

[Modificare i file di configurazione Home Assistant Core (su Docker, su Raspberry) con Visual Studio Code (VSCode)](https://indomus.it/progetti/modificare-i-file-di-configurazione-home-assistant-core-su-docker-su-raspberry-con-visual-studio-code-vscode/)

Tutto bene, vedo la cartella `homeassistant` e file contenuti, ma non posso modificarli, stessa cosa da `PI Desktop`, mentre da shell by SSH con il terminale Putty nessun problema riesco a modificare i file e salvarli.

**Comment by snakuzzo** [comment]
Se non fornisci i dettagli impossibile darti una mano.

**Comment by DaviBax** [comment]
Queste sono le impostazioni di `dockercompose.yaml`:

```
version: '3.9'
services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
    - /home/pi/homeassistant:/config
    environment:
    - TZ=Europe/Rome
    network_mode: host
    restart: always
    #user: "${LOCAL_USER}:${LOCAL_USER}"
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
    #user: "${LOCAL_USER}:${LOCAL_USER}"
  duckdns:
    container_name: duckdns
    image: ghcr.io/linuxserver/duckdns
    environment:
    - "TZ=Europe/Rome"
    - "SUBDOMAINS=casettabax"
    - "TOKEN=b64eb671-d3aa-4dbe-bca4-bca9efa56e52"
    restart: always
  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/pi/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/pi/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    ports:
    #- "80:80"
    - "443:443"
```

Questo è il messaggio di errore che mi restituisce `VSCode` se tento di salvare un file modificato dentro la cartella `home/pi/homeassitant`

`Non è stato possibile salvare 'scenes.yaml': Non è possibile scrivere il file 'vscode-remote://ssh-remote+192.168.19.103/home/pi/homeassistant/scenes.yaml' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/pi/homeassistant/scenes.yaml')`
