### DISCUSSION TITLE
Installazione Caddy su Dockers-Compose

### DISCUSSION THREAD

**Discussion by DaviBax** [indomus/forum#1468] [HUB: Home Assistant]
Dopo una serie di tentativi con `Raspbian` e `Phyton` mi sono convinto a passare a `Docker` per `Home Assistant,` ma sono alle prime armi e ora mi sto scontrando con `Caddy`:

Seguendo le Vs guide sono arrivato ad installare `Caddy ` in `Dockers-Compose` con la seguente configurazione, dopo aver aperto la porta 443 sul mio router.

```
  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/pi/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/pi/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    ports:
    #- "80:80"
    - "443:443"
```

Lanciando il log di caddy da shell:

```
{"level":"info","ts":1644186285.916116,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
{"level":"warn","ts":1644186285.9203746,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":3}
{"level":"info","ts":1644186285.9243548,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
{"level":"info","ts":1644186285.925213,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
{"level":"info","ts":1644186285.9253037,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1644186285.925336,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x40004f17a0"}
{"level":"info","ts":1644186285.926667,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
{"level":"info","ts":1644186285.9281394,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["casamia.duckdns.org"]}
{"level":"info","ts":1644186285.9314167,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1644186285.9357562,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1644186285.9359033,"msg":"serving initial configuration"}
```

I certificati non riesco a vederli con il comando:

`ls -latr /home/pi/caddy/data/caddy/certificates/acme-staging-v02.api.letsencrypt.org-directory/casamia.duckdns.org`

perchè ho accesso negato, come posso sistemare?
