### DISCUSSION TITLE
platform: systemmonitor per unità disco esterna

### DISCUSSION THREAD

**Discussion by gians-it** [indomus/forum#1470] [GENERALE - Discussioni generiche]
Ciao,

Vorrei monitorare disk_use_percent in  un disco che si trova in un' altra macchina.

da riga di comando:
` df -h --output='avail','pcent' /dev/sda1"`

ho il seguente risultato:
```
 Avail Use%
   70G   1%
```
che dorebbe essre letto da 
  ### platform: command_line .... 
    
come si fa per:
 ```
- type: disk_use_percent
   arg: /home
```
   
 penso usando command: ssh 
   
   Grazie

**Comment by snakuzzo** [comment]
Non puoi usare quel platform per leggere la percentuale di un disco remoto (a meno che tu non lo abbia montato via NFS).

Se l'hai montato sul server di HA (attenzione che se hai HA su Docker...il container deve poter vedere questo volume), il sensore è semplice

```
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_free
```

Se non l'hai montato ma devi andare sulla macchina remota, innanzi tutto devi fare in modo di poter lanciare il comando dal server su cui hai HA verso il server remoto.
Quindi ti consiglierei di generare sul client una chiave SSH (attenzione che se hai HA su Docker devi crearla nel container Docker e non sull'host) 

`ssh-keygen -t rsa`

Ti genererà dei file sotto `/home/<tuoutente>/.ssh` e se lasci tutto di default la chiave pubblica sarà `/home/<tuoutente>/.ssh/id_rsa.pub`

A questo punto la esporti sul server remoto...

`ssh-copy-id -i /home/<tuoutente>/.ssh/id_rsa.pub <utenteremoto>@<ipremoto>`

Modifica (se ti va) il file `/home/<tuoutente>/.ssh/config` (qui ad esempio ho dato il nome `qnap` alla connessione verso il server remoto

```
Host qnap
  Hostname <ipremoto>
  User <utenteremoto>
  IdentityFile ~/.ssh/id_rsa
```

Verifica che questo comando funzioni (qui come vedi mi restituisce la percentuale del disco remoto `/mnt/Disk1`... 64%)

```
snakuzzo@SnakuzzoWork:~$ ssh qnap df -h --output='pcent' /mnt/Disk1 | awk 'NR>1' | sed 's/^ *//g' | sed 's/%//'
64
```

A questo punto puoi fare un sensore su HA così...

```yaml
sensor:

- platform: command_line
  name: Ext Disk Free Percentage
  command: "ssh qnap df -h --output='pcent' /mnt/Disk1 | awk 'NR>1' | sed 's/^ *//g' | sed 's/%//'"
  unit_of_measurement: "%"
```
