### DISCUSSION TITLE
aqara sensore porta, non esiste il solo cambiamento di stato ?

### DISCUSSION THREAD

**Discussion by ik1zyq** [indomus/forum#1479] [ZigBee, Z-Wave, Thread, Matter]
Chiedo aiuto su una cosa che probabilmente è una banalità ma mi sono bloccato.
Ho un sensore porta aqara in rete zigbee: non esiste il modo di rilevare il solo 'cambiamento' di stato e non necessariamente On e Off ?
Se non ricordo male su quelli sonoff c'era.
Grazie

**Comment by snakuzzo** [comment]
certo che puoi...ma di preciso cosa vuoi fare?
Un automazione ?

Una roba del genere...

```yaml
automation:

- id: prova
  alias: prova
  trigger:
  - platform: state
    entity_id: binary_sensor.sensore_porta
  action:
  - service: persistent_notification.create
    data:
      title: HA Info
      message: "Stato sensore porta rilevato -> {{ 'aperto' if states('binary_sensor.sensore_porta') == 'on' else 'chiuso' }}"
```
