### DISCUSSION TITLE
Errore nella creazione di gruppi

### DISCUSSION THREAD

**Discussion by ik1zyq** [indomus/forum#1480] [GENERALE - Discussioni generiche]
Ho seguito degli esempi nelle guide per la creazione dei gruppi ma questo inserito in groups.yaml

group:
  speaker_google:
  name: Google_gruppo_tuttiglispeaker
  entities:
    - Google-Home-Mini
    - Google-Home-Mini-2

Mi genera invalid config...

![image](https://user-images.githubusercontent.com/98024250/153008900-17b42e8b-7ea1-4c34-bf89-30fe57802d64.png)

Mi aiutate a capire cosa sbaglio ?
grazie

**Comment by snakuzzo** [comment]
Innanzi tutto **DEVI USARE IL MARKDOWN QUANDO PUBBLICHI IL CODICE**. Così come hai scritto non si capisce NIENTE a livello di sintassi. Leggi [QUI](https://github.com/indomus/forum/discussions/1311)
Poi... Se usi file sidecar (caso tuo) non devi replicare `group:` in prima riga...perché è già scritto nel `configuration.yaml` (questo fa parte del linguaggio YAML ... che ti consiglio di guardare un attimino)
Infine...non hai usato i nomi dell'entità `media_player` ma un `friendly_name`.

Quindi...alla luce di quanto appena scritto:

Nel `configuration.yaml` avrai sicuramente questo:

```yaml
group: !include groups.yaml
```

Quindi nel file `groups.yaml` metterai questo:

```yaml
google_speakers:
  entities:
  - media_player.google_home_mini_1
  - media_player.google_home_mini_2
```

e se infine vuoi dargli un friendly name **fisso**, usi il file `customizations.yaml`

```yaml
group.google_speakers:
  friendly_name: "Tutti gli speaker Google"
  icon: mdi:google-home
```
