### DISCUSSION TITLE
Ip generic camera non si vede nulla

### DISCUSSION THREAD

**Discussion by mriitan** [indomus/forum#1485] [HUB: Home Assistant]
ciao, sto provando ad integrare delle ip camera che non sono nativamente integrabili con HA.
Ho seguito la guida di indomus: https://indomus.it/formazione/integrare-ip-cam-webcam-sugli-hub-personali-da-dove-partire/
 e 
https://www.home-assistant.io/integrations/generic
così facendo digitando il percorso della camera vedo regolarmente il flusso video dal browser, al momento di integrare il tutto però su HA non vedo nulla:
```
  - platform: generic
    name: Soggiorno-cam
    still_image_url: http://admin:pass@192.168.1.16/MJPEG.CGI
    username: admin
    password: pass
    stream_source: http://pass@192.168.1.16/MJPEG.CGI
```
quando vado a usare la card Colpo d'occhio non si vede nulla. chi può aiutarmi?
Grazie

**Comment by indomus** [comment]
`username` e `password` comincia col non metterli come chiavi, dato che li espliciti nell'url. il secondo url, a proposito (`stream source`), è mancante eventualmente dell'username.

**Reply by mriitan** [reply]
```
camera:
  - platform: generic
    name: Cucina_cam
    still_image_url: http://admin:pass@192.168.1.15/MJPEG.CGI
    stream_source: http://admin:pass@192.168.1.15/MJPEG.CGI
```
nulla da fare
m

**Reply by indomus** [reply]
butta un occhio ai log, vedi che dicono

**Reply by mriitan** [reply]
Logger: homeassistant.components.generic.camera
Source: components/generic/camera.py:157
Integration: generic ([documentation](https://www.home-assistant.io/integrations/generic), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+generic%22))
First occurred: 00:16:57 (55 occurrences)
Last logged: 14:47:20

Error getting new camera image from Soggiorno-cam2: Request URL has an unsupported protocol 'rtsp://'.
Error getting new camera image from Soggiorno-cam: Server error '501 Method Not Implemented' for url 'http://admin:omnitel@192.168.1.16/MJPEG.CGI' For more information check: https://httpstatuses.com/501

ovviamente nel config ci sono le due Soggiorno-cam e Soggiorno-cam2
aiuto

**Reply by indomus** [reply]
ma scusa, perché http://admin:pass@192.168.1.15/MJPEG.CGI? semmai
rtsp://admin:pass@192.168.1.15/MJPEG.CGI

**Reply by mriitan** [reply]
da quello che ho capito andando sul sito del database delle telecamere, ti genera una riga a seconda delle caratteristiche della telecamera. Nello specifico io ho 2 dlink e 1 x cam.
per cui mi ha generato queste righe:

```
camera:
  - platform: generic
    name: Cucina_cam
    still_image_url: http://admin:omnitel@192.168.1.15/MJPEG.CGI
    stream_source: http://admin:omnitel@192.168.1.15/MJPEG.CGI
    
  - platform: generic
    name: Soggiorno-cam
    still_image_url: http://admin:omnitel@192.168.1.16/MJPEG.CGI
    stream_source: http://admin:omnitel@192.168.1.16/MJPEG.CGI

  - platform: generic
    name: Soggiorno-cam2
    still_image_url: rtsp://admin:Omnitel001@192.168.1.24/live/ch1
    stream_source: rtsp://admin:Omnitel001@192.168.1.24/live/ch1
```
ma dal og vedo solo quello che ti ho postato in alto, per le altre due non vedo nulla nemmeno nel log.
