### DISCUSSION TITLE
Feed RSS in card di HA

### DISCUSSION THREAD

**Discussion by mriitan** [indomus/forum#1487] [HUB: Home Assistant]
Ciao a tutti,
ho esigenza di pubblicare news rss in home assistant di un sito specifico, diciamo l'ansa.

con l'integrazione feedparser sono riuscito ad avere un sensore che mi incanale le notizie, aggiungendo in config le righe:
```
  - platform: feedparser
    name: FeedRSS
    feed_url: 'https://www.ansa.it/sito/ansait_rss.xml'
    date_format: '%a, %d %b %Y %H:%M:%S %Z'
    scan_interval:
      hours: 3
    inclusions:
      - title
      - link
      - description
      - image
      - pubDate
    exclusions:
      - language  
      
```
vedo il sensore che mi dice il valore delle notizie caricate, in valore numerico, vedo le notizie tra gli attributi dei sensori, come faccio a pubblicarli in una card?
Chi può aiutarmi? sono ben accette anche altre soluzioni.
Grazie
