### DISCUSSION TITLE
Circuito Luci con ESP+esphome

### DISCUSSION THREAD

**Discussion by mrgoodcat** [indomus/forum#1488] [HUB: Home Assistant]
Ciao, 
ho iniziato da poco a giocare con HA (core in docker su raspi4),ESP32 e ESPHome (il tutto grazie alla vostre guide). 
Ho fatto qualche semplice prova e sono in grado di pilotare un'uscita di ESP da HA e di leggere un ingresso sempre da HA. 
Ora vorrei fare un qualcosa in più, tipo simulare da HA un pulsante (momentary switch) che comandi l'uscita con un impulso. Questo nell'ottica di integrare, in impianto esistente con circuito a relay (finder 26), un pulsante "remoto". Lo step successivo è quello di acquisire lo stato del finder da usare come feedback luce accesa\spenta. Il "pulsante remoto" è un contatto pulito NO di relay 5V. 
Esiste un qualcosa che si presti a tal scopo o avete qualche suggerimento sul come impostare la cosa ?
Si ok potrei semplicemente usare degli shelly, ma prima di cedere volevo capire se riesco a farne a meno. 
Grazie,

**Comment by KC-inDomus** [comment]
ciao, benvenuto. il momentary lo devi configurare lato esphome, di modo che all'attivazione funga il quel modo. tra l'altro da poco su esphome hanno introdotto il componente [Button](https://esphome.io/components/button/index.html), il quale ha la sua controparte su Home Assistant.

in pratica devi definire all'interno di esphome uno switch (_internal_) che agisca come momentary, dopodiché un button che agisca sull'id di tale switch.

**Reply by mrgoodcat** [reply]
Grazie KC. Provo a inserirlo e vedo cosa ne esce.

**Reply by Scialla** [reply]
lo stato però così non lo recuperi, se usi un relé con un pulsante non avrai mai lo stato, devi usare altri sistemi, ad esempio un sensore che misuri l'assorbimento e ti riporti lo stato

**Reply by mrgoodcat** [reply]
Grazie per i vostri feedback.
@KC-inDomus ci sto ragionando e abbozzando il codice, ma non colgo alcune questioni. Perchè devo fare uno switch interno? Perchè così non lo vedo su HA ma vedo solo il button ? 
Interno come lo definisco ? 
La bozza sarebbe 
```
switch:
  - platform: template
    name: "momentary switch"
    id: mom_sw
button:
  - platform: template
    name: "button1"
    on_press:
      then:
        - logger.log: Button Pressed
        - switch.turn_on: mom_sw
    on_release:
      then:
        - logger.log: Button Released
        - switch.turn_off: mom_sw
```
ho un pò reinterpreatato l'esempio ma non sono molto convinto. Il logger se ho capito bene serve solo per registrare l'evento pressione\rilascio, corretto?

@Scialla ragionavo anche su quello, l'idea sarebbe mettere un icona "Luce" che cambia colore con il feedback del finder26. O almeno è come facevo sugli SCADA, qui è ancora un pò confusa la cosa. L'assorbimento complica un pò anche lato HW credo.

**Reply by KC-inDomus** [reply]
configura lo switch come "internal"
in modo che si, non venga esposto come switch a home assistant. a te interessa esporre solo il button

**Reply by mrgoodcat** [reply]
Il button l'ho aggiunto e lo vedo su HA. Se premo lo rilevo sul log correttamente. Il problema è lo switch che non riesco a definirlo correttamente. 
mettendo
```
switch:
  - platform: template
    name: "momentary switch"
    id: mom_switch
```
mi da errore, anche omettendo l'ID, che è come ho letto che va messo per renderlo implicitamente internal. Al di là che non và, se ometto l'ID poi come lo attacco alla pressione del button ?
Scusate le domande stupide, 
Grazie

**Reply by indomus** [reply]
grazie, se ti inventi la sintassi... :)

prova qualcosa del genere:

```
switch:
  - platform: gpio
    pin: 25
    id: relay
    name: "Gate Remote"
    icon: "mdi:gate"
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay
```

vedi meglio [qui](https://esphome.io/components/switch/gpio.html#momentary-switch)

**Reply by mrgoodcat** [reply]
eh eh , è l'internal che mi ha mandato in confusione. Come mi hai indicato è il "classico" switch con turn-off automatico. L'idea di KC (se ho capito bene) è quella di creare uno switch fittizio non visibile da HA comandato dal button, quindi con turn-off già incorporato. Il problema (o uno dei) è agganciare la pressione del button allo switch-on dello switch, dando per scontato che al rilascio del button avvenga anche lo switch-off (ma un passo alla volta). :)

**Reply by mrgoodcat** [reply]
forse c'è un modo migliore, ma così funziona. Da come ho capito output è uno switch ma "interno".
```
button:
  - platform: template
    name: "button1"
    on_press:
      then:
        - logger.log: Button Pressed
        - output.turn_on: generic_out
        - delay: 500ms
        - output.turn_off: generic_out
output:
  - platform: gpio
    pin: GPIO18
    id: generic_out
```
su HA è mostrato solo il pulsante e non l'uscita. 
![immagine](https://user-images.githubusercontent.com/13080499/153634770-5d79d8d9-fc7b-4b1b-9501-71f547678ab4.png)

Ora sarebbe interessante capire se si può fare qualcosa sull'icona di HA. Pensavo (ma non so bene come metterla giù ne se è possibile farlo) di parametrizzare la variabile icona e legarla allo stato di un ingresso. Idee ? :)
