### DISCUSSION TITLE
Shelly Plug S

### DISCUSSION THREAD

**Discussion by dibummer** [indomus/forum#1491] [HUB: Home Assistant]
un saluto a tutti.
ho il problema ad inserire il sensore del solo consumo giornaliero, quello mensile funziona, del prodotto Shelly Plug S.
nei log appare il seguente errore:
```
Logger: homeassistant.components.sensor
Source: components/utility_meter/sensor.py:322 
Integration: Sensore (documentation, issues) 
First occurred: 12:17:50 (2 occurrences) 
Last logged: 12:17:50

Error adding entities for domain sensor with platform utility_meter
Error while setting up utility_meter platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 778, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/utility_meter/sensor.py", line 322, in async_added_to_hass
    float(state.attributes.get(ATTR_LAST_PERIOD))
ValueError: could not convert string to float: 'None'

```
la configurazione del componente utility.meter è la seguente:
```
#### presa rack studio ####

shelly_plug_consumo_giornaliero:
    source: sensor.shelly_plug_consumo
    cycle: daily
    
shelly_plug_consumo_mensile:
    source: sensor.shelly_plug_consumo
    cycle: monthly

```
il problema è sopra giunto dopo aver modificato nella configurazione.yaml, il nome del prodotto perché inserito non correttamente, altrimenti il sensore giornaliero lo rilevava, ovviamente non correttamente e cioè sconosciuto.
spero di avere dato informazioni utili relativo al problema.
ringrazio anticipatamente dell'aiuto.

**Comment by snakuzzo** [comment]
Uno di quei sensori è la causa del problema.
Restituisce `None` e "giustamente" non può fare il cast di `None` a `float`.
Fai vedere come hai definito le entità dei sensori (immagino siano MQTT), perché quasi sicuramente non hai specificato il valore di default nel caso in cui non arrivi un valore (`None`)

**Comment by dibummer** [comment]
grazie della veloce risposta.
confermo ho integrato con MQTT, ecco la configurazione dello switch e dei sensori: 
```
- platform: mqtt
    name: "spina_studio"
    state_topic: "shellies/shellyplug-s-C16E7F/relay/0"
    command_topic: "shellies/shellyplug-s-C16E7F/relay/0/command"
    availability_topic: "shellies/shellyplug-s-C16E7F/online"
    qos: 1
    value_template: "{% if value == 'on' %} on {% else %} off {% endif %}" 
    payload_on: "on"
    payload_off: "off"
    payload_available: "true"
    payload_not_available: "false"
    optimistic: false
    retain: false
```
```
#### presa rack studio ####      
  - platform: mqtt
    name: "Shelly Plug Assorbimento"
    state_topic: "shellies/shellyplug-s-C16E7F/relay/0/power"
    unit_of_measurement: "Watt"
    
  - platform: integration
    source: sensor.shelly_plug_assorbimento
    name: "Shelly Plug Consumo"
    unit_prefix: k
    round: 2
```
    intendevi queste informazioni?
grazie ancora.

**Reply by snakuzzo** [reply]
in realtà intendevo `sensor.shelly_plug_consumo` alla quale sicuramente fanno capo tutte quelle che espongono il valore in `Watt`

**Reply by snakuzzo** [reply]
e per cortesia fai reply sotto l'ultimo messaggio, non aprire ogni volta nuovi thread (come hai appena fatto)

**Reply by dibummer** [reply]
scusa della precedente risposta.

forse non ho capito bene, anzi sicuramente.
in ogni caso ti invio questi:

```
Shelly Plug Consumo
IMPOSTAZIONI
CORRELATO
Questa entità ("sensor.shelly_plug_consumo") non ha un ID univoco, pertanto le sue impostazioni non possono essere gestite dall'interfaccia utente. Vedi [documentazione](https://www.home-assistant.io/faq/unique_id) per maggiori dettagli.

``````
#### presa rack studio ####

shelly_plug_consumo_giornaliero:
    source: sensor.shelly_plug_consumo
    cycle: daily
    
shelly_plug_consumo_mensile:
    source: sensor.shelly_plug_consumo
    cycle: monthly

```

**Reply by snakuzzo** [reply]
non c'è niente di utile qui...
Scusa, ma i sensore 

```
sensor.shelly_plug_consumo
```

dove e come lo hai definito ?

**Comment by dibummer** [comment]
_**RIMOSSO**_

**Reply by dibummer** [reply]
ho seguito questa guida:

`https://indomus.it/guide/integrare-shelly-plug-s-a-home-assistant-via-mqtt/#shelly`

ho risposto con delle screnschot della configurazione alla tua mail per non fare casino qui.
grazie

**Reply by snakuzzo** [reply]
infatti hai fatto più casino che altro:
1. hai aperto un nuovo thread
2. hai risposto via mail
3. non si vede niente

**Reply by dibummer** [reply]
eccola:
grazie

```
 - platform: mqtt
    name: "spina_studio"
    state_topic: "shellies/shellyplug-s-C16E7F/relay/0"
    command_topic: "shellies/shellyplug-s-C16E7F/relay/0/command"
    availability_topic: "shellies/shellyplug-s-C16E7F/online"
    qos: 1
    value_template: "{% if value == 'on' %} on {% else %} off {% endif %}" 
    payload_on: "on"
    payload_off: "off"
    payload_available: "true"
    payload_not_available: "false"
    optimistic: false
    retain: false

```
```
#### presa rack studio ####      
  - platform: mqtt
    name: "Shelly Plug Assorbimento"
    state_topic: "shellies/shellyplug-s-C16E7F/relay/0/power"
    unit_of_measurement: "Watt"
    
  - platform: integration
    source: sensor.shelly_plug_assorbimento
    name: "Shelly Plug Consumo"
    unit_prefix: k
    round: 2
    
```
```

#### presa rack studio ####

shelly_plug_consumo_giornaliero:
    source: sensor.shelly_plug_consumo
    cycle: daily
    
shelly_plug_consumo_mensile:
    source: sensor.shelly_plug_consumo
    cycle: monthly

``````

- alias: MQTT Announce
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: mqtt.publish
    data:
      payload: announce
      topic: shellies/command
```
```
#### spina rack studio ####
  - platform: mqtt
    name: "Shelly Plug Surriscaldamento"
    state_topic: "shellies/shellyplug-s-C16E7F/overtemperature"
    payload_on: 1
    payload_off: 0
    device_class: problem
    qos: 1
    
  - platform: mqtt
    name: "Shelly Plug Overpower"
    state_topic: "shellies/shellyplug-s-C16E7F/relay/0"
    value_template: "{% if value == 'overpower' %} on {% else %} off {% endif %}" 
    payload_on: "on"
    payload_off: "off"
    device_class: "problem"
    qos: 0
```

**Reply by snakuzzo** [reply]
non si capisce niente...correggi utilizzando bene il markdown

**Reply by dibummer** [reply]
così va bene? questa è la configurazione riportata nella guida.
```
        SWITCH
  - platform: mqtt
    name: "spina_studio"
    state_topic: "shellies/shellyplug-s-C16E7F/relay/0"
    command_topic: "shellies/shellyplug-s-C16E7F/relay/0/command"
    availability_topic: "shellies/shellyplug-s-C16E7F/online"
    qos: 1
    value_template: "{% if value == 'on' %} on {% else %} off {% endif %}" 
    payload_on: "on"
    payload_off: "off"
    payload_available: "true"
    payload_not_available: "false"
    optimistic: false
    retain: false
              
                 SENSORI
#### presa rack studio ####      
  - platform: mqtt
    name: "Shelly Plug Assorbimento"
    state_topic: "shellies/shellyplug-s-C16E7F/relay/0/power"
    unit_of_measurement: "Watt"
    
  - platform: integration
    source: sensor.shelly_plug_assorbimento
    name: "Shelly Plug Consumo"
    unit_prefix: k
    round: 2
    
                     UTILITA METER
#### presa rack studio ####

shelly_plug_consumo_giornaliero:
    source: sensor.shelly_plug_consumo
    cycle: daily
    
shelly_plug_consumo_mensile:
    source: sensor.shelly_plug_consumo
    cycle: monthly

            BYNARI SENSOR
#### spina rack studio ####
  - platform: mqtt
    name: "Shelly Plug Surriscaldamento"
    state_topic: "shellies/shellyplug-s-C16E7F/overtemperature"
    payload_on: 1
    payload_off: 0
    device_class: problem
    qos: 1
    
  - platform: mqtt
    name: "Shelly Plug Overpower"
    state_topic: "shellies/shellyplug-s-C16E7F/relay/0"
    value_template: "{% if value == 'overpower' %} on {% else %} off {% endif %}" 
    payload_on: "on"
    payload_off: "off"
    device_class: "problem"
    qos: 0

                 AUTOMAZIONE
- alias: MQTT Announce
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: mqtt.publish
    data:
      payload: announce
      topic: shellies/command

```
