### DISCUSSION TITLE
Aggiungere variabili ad automazione tramite Template

### DISCUSSION THREAD

**Discussion by NdR91** [indomus/forum#1514] [HUB: Home Assistant]
Ciao, avrei bisogno di una mano su un'automazione.

Parto da questa "base" appena creata per verificarne il funzionamento:

```yaml
  # Volume Echo
  - id: dd4479b2-eb5f-488e-be7f-851c6144c44b
    alias: Alexa Echo - Gestione Volume Dot Camera
    trigger:
      - platform: state
        entity_id: input_number.dot_studio
        id: input_studio
      - platform: state
        entity_id: media_player.dot_studio
        attribute: volume_level
        id: volume_studio
      # --------------------------------------------
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: input_studio
        sequence:
          - service: media_player.volume_set
            target:
              entity_id: media_player.dot_studio
            data: 
              volume_level: "{{ ((states('input_number.dot_studio'))|float(default=0) / 100) }}"
      - conditions:
        - condition: trigger
          id: volume_studio
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.dot_studio
            data: 
              value: "{{ ((states.media_player.dot_studio.attributes.volume_level)|float(default=0) * 100) }}"
  # ------------------------------------------------------------------
  # Slider Volume Echo
input_number:
  dot_studio:
    name: Volume - Echo Dot Studio
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
    mode: slider
```

Questa automazione non fa altro che permettermi di regolare il volume di un Media Player tramite uno slider su Lovelace ed al contemo adegua lo slider stesso nel caso in cui il volume del Media Player venga cambiato tramite altri input.
![2022-02-17_11-20-46_139](https://user-images.githubusercontent.com/52299148/154455932-6b645d86-1c4b-4194-98e9-a24f085914fd.png)

Quello che vorrei fare, è creare una variabile che mi eviti di fare un'automazione chilometrica con due choose per ogni Echo che ho.
Per farlo, sto provando così:

```yaml
  - id: dd4479b2-eb5f-488e-be7f-851c6144c44b
    alias: Alexa Echo - Gestione Volume Dot Camera
    trigger:
      - platform: state
        entity_id: input_number.dot_studio
        id: input_studio
      - platform: state
        entity_id: media_player.dot_studio
        attribute: volume_level
        id: volume_studio
    variables:
      device: '{{trigger.entity_id[''after''][''.'']}}'
      # --------------------------------------------
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: input_studio
        sequence:
          - service: media_player.volume_set
            target:
              entity_id: media_player.{{device}}
            data: 
              volume_level: "{{ ((states.input_number.{{device}})|float(default=0) / 100) }}"
      - conditions:
        - condition: trigger
          id: volume_studio
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.{{device}}
            data: 
              value: "{{ ((states.media_player.{{device}}.attributes.volume_level)|float(default=0) * 100) }}"
```

Ma ritorna errore:

```
Invalid config for [automation]: template value should be a string for dictionary value @ data['action'][0]['choose'][1]['sequence'][0]['data']. Got None. (See ?, line ?).

Invalid config for [automation]: template value should be a string for dictionary value @ data['action'][0]['choose'][0]['sequence'][0]['data']. Got None. (See ?, line ?). 
```

Qualcuno riesce a darmi una dritta?
Grazie in anticipo.

**Comment by NdR91** [comment]
Ho fatto un piccolo progresso:

Se in dev tools inserisco:

```yaml
{% set entity_id = 'media_player.dot_studio' %}
{{ entity_id.split('.')[1] }}
```
Il valore restituito è:
`dot_studio`

Quindi il template corretto da usare dovrebbe essere:
```yaml
variables:
  device: "{{ trigger.entity_id.split('.')[1] }}"
```

Però continuo a ricevere errore:
```
 Invalid config for [automation]: template value should be a string for dictionary value @ data['action'][0]['choose'][0]['sequence'][0]['data']. Got None. (See ?, line ?). 
 ```

L'automazione aggiornata è questa:
```yaml
  - id: dd4479b2-eb5f-488e-be7f-851c6144c44b
    alias: Alexa Echo - Gestione Volume Dot Camera
      - platform: state
        entity_id: 
        - input_number.dot_studio
        - input_number.dot_bagno
        - input_number.dot_camera
        - input_number.echo_sala
        - input_number.show_sala
        id: input_echo
      - platform: state
        entity_id: 
        - media_player.dot_studio
        - media_player.dot_bagno
        - media_player.dot_camera
        - media_player.echo_sala
        - media_player.show_sala
        attribute: volume_level
        id: volume_echo
    variables:
      device: "{{ trigger.to_state.entity_id.split('.')[1] }}"
      # --------------------------------------------
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: input_echo
        sequence:
          - service: media_player.volume_set
            target:
              entity_id: media_player.{{device}}
            data: 
              volume_level: "{{ ((states.input_number.{{device}})|float(default=0) / 100) }}"
      - conditions:
        - condition: trigger
          id: volume_echo
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.{{device}}
            data: 
              value: "{{ ((states.media_player.dot_studio.attributes.volume_level)|float(default=0) * 100) }}"
```

**Reply by NdR91** [reply]
Nuovo aggiornamento, mi sto avvicinando ma ancora non ci sono.

Sono riuscito ad ottenere la sintassi corretta del template, in quanto non ricevo più errore:

```yaml
  # Volume Echo
  - id: dd4479b2-eb5f-488e-be7f-851c6144c44b
    alias: Alexa Echo - Gestione Volume Dot Camera
    mode: restart
    trigger:
      - platform: state
        entity_id: 
        - input_number.dot_studio
        - input_number.dot_bagno
        - input_number.dot_camera
        - input_number.echo_sala
        - input_number.show_sala
        id: input_echo
      - platform: state
        entity_id: 
        - media_player.dot_studio
        - media_player.dot_bagno
        - media_player.dot_camera
        - media_player.echo_sala
        - media_player.show_sala
        attribute: volume_level
        id: volume_echo
    variables:
      device: "{{ trigger.entity_id.split('.')[1] }}"
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: input_echo
        sequence:
          - service: media_player.volume_set
            target:
              entity_id: media_player.{{device}}
            data: 
              volume_level: |
                {% set device = '{{device}}' %}
                {{ (states('input_number.' ~ device )|float(default=0) / 100) }}
      - conditions:
        - condition: trigger
          id: volume_echo
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.{{device}}
            data: 
              value: |
                {% set device = '{{device}}' %}
                {{(state_attr('media_player.' ~ device, 'volume_level')|float(default=0) * 100)}}
```

Ora, il problema che resta da risolvere:

Provando l'automazione, ho visto che il `volume_level` risulta sempre 0. Questo significa che il template del volume in realtà non sta usando la variabile `device` definita a monte dell'automazione.

Screen del debug dell'automazione:
![2022-02-17_16-42-29_148](https://user-images.githubusercontent.com/52299148/154517039-3b9628de-f659-4dde-a517-9339352c2a75.png)

Idee?

**Comment by NdR91** [comment]
Finalmente ho risolto:

Riporto tutto il codice per chi potesse averne bisogno:

```yaml
  # Slider Echo
  - id: dd4479b2-eb5f-488e-be7f-851c6144c44b
    alias: Alexa Echo - Gestione Volume Slider
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: 
        - input_number.dot_studio
        - input_number.dot_bagno
        - input_number.dot_camera
        - input_number.echo_sala
        - input_number.show_sala
        - input_number.soundbar
        id: input_echo
      - platform: state
        entity_id: 
        - media_player.dot_studio
        - media_player.dot_bagno
        - media_player.dot_camera
        - media_player.echo_sala
        - media_player.show_sala
        - media_player.soundbar
        attribute: volume_level
        id: volume_echo
    variables:
      device: "{{ trigger.entity_id.split('.')[1] }}"
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: input_echo
        sequence:
          - service: media_player.volume_set
            target:
              entity_id: media_player.{{device}}
            data: 
              volume_level: "{{ (states('input_number.' + device )|float(default=0) / 100) }}"
      - conditions:
        - condition: trigger
          id: volume_echo
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.{{device}}
            data: 
              value: "{{(state_attr('media_player.' + device, 'volume_level')|float(default=0) * 100)}}"
  # ------------------------------------------------------------------
  # Slider Volume Echo
input_number:
  dot_studio:
    name: Volume - Echo Dot Studio
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
    mode: slider
    icon: phu:echo-dot-gen-3
  echo_sala:
    name: Volume - Echo Sala
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
    mode: slider
    icon: phu:echo-plus
  show_sala:
    name: Volume - Echo Show Sala
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
    mode: slider
    icon: phu:echo-show-8-gen-2
  dot_bagno:
    name: Volume - Echo Dot Bagno
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
    mode: slider
    icon: phu:echo-dot-gen-3
  dot_camera:
    name: Volume - Echo Dot Camera
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
    mode: slider
    icon: phu:echo-dot-gen-3
  soundbar:
    name: Volume - Soundbar
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
    mode: slider
    icon: phu:sonos-beam
  ```
