### DISCUSSION TITLE
Esphome e lambda: stato sensore dopo un riavvio

### DISCUSSION THREAD

**Discussion by Nik71git** [indomus/forum#1517] [Hardware & Firmware]
mi servirebbe un esperto di Esphome, in particolare della funzione lambda,
ho questa parte implementata che però manca del riconoscimento dello stato dopo un riavvio, ritorna sempre "sconosciuto" fino all'attivazione della cover... idee? basterebbe che al riavvio si "ricordasse" dello stato in cui era

```
# stato tende
  - platform: template
    name: "tende"
    device_class: opening
    id: tende       
    
cover:
  - platform: template
    device_class: awning
    name: Somfy
    lambda: !lambda |-
      if (id(tende).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }    
    open_action:
      homeassistant.service:
        service: homeassistant.turn_on
        data:
          entity_id: switch.tende_aperte
    close_action:
      homeassistant.service:
        service: homeassistant.turn_on
        data:
          entity_id: switch.tende_chiuse
    stop_action:
      homeassistant.service:
        service: homeassistant.turn_on
        data:
          entity_id: script.1589465909393
    #optimistic: true
    #assumed_state: true
```

**Comment by snakuzzo** [comment]
Puoi pubblicare tutto lo YAML ? (esclusa la tua personalizzione, si intende)

**Reply by xyzmauro** [reply]
Nick,credo dipenda dallo stato del sensor(??) tende che al riavvio sarà unknown per qlc motivo, dal codice postato non si capisce

**Reply by snakuzzo** [reply]
Come già detto a nik in chat, se non ricordo male deve forzare la valorizzazione nell' `on_boot`, ma resta il fatto che...se si tratta di un sensore inutile ai fini del funzionamento della tenda, ma necessario solo su HA, potrebbe creare quel sensore direttamente su HA recuperando lo stato dall'entità cover esposta da esphome

**Reply by KC-inDomus** [reply]
sì, ha molto più senso così

**Reply by snakuzzo** [reply]
Comunque @Nik71git ... con riferimento alle note presenti [QUI](https://esphome.io/components/cover/template.html#cover-template-publish-action), prova un attimo a...

- aggiungere un id alla cover:

```
  id: somfy
```

- ad aggiungere sotto `esphome:` questo...

```yaml
  on_boot:
    then:
      - lambda: 'id(somfy).publish_state();'
```

**Reply by Nik71git** [reply]
intanto grazie a tutti che mi avete dedicato la vostra attenzione, qui sotto pubblico il codice completo (in pratica il firmware...) della cover delle tende, quella con il sensore che non riconosce lo stato dopo un riavvio.
<details>

```
# Device Basic Configuration
esphome:
  name: bridge
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# Optional manual IP
#  manual_ip:
#    static_ip: 192.168.1.27
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0 

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bridge Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  baud_rate: 0

web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret api_password
  
ota:
  password: !secret ota_password
  
remote_receiver:
  pin: 
    number: GPIO4
#    inverted: true
  dump: rc_switch
  filter: 50us
  tolerance: 50%
  idle: 5ms

sensor:
  - platform: wifi_signal
    name: "RF Bridge segnale wifi" 
    update_interval: 3600s  
    
status_led:
  pin:
    number: GPIO13
    inverted: yes  

switch:
  - platform: restart
    name: bridge restart    

text_sensor:
  - platform: version
    name: bridge esphome version
    hide_timestamp: true
    
  - platform: wifi_info
    ip_address:
      name: bridge IP address   
      icon: mdi:ip-network-outline

binary_sensor:
  - platform: status
    name: "stato RF Bridge"

# sensori per tenda da sole  

# aperte
  - platform: remote_receiver
    name: "somfy aperte"
    internal: yes
    filters:
      - delayed_off: 2s
    rc_switch_raw:
      code: '111000010110010000001010'
      protocol: 1
    on_press:
      - binary_sensor.template.publish:
          id: tende
          state: ON  
# chiuse     
  - platform: remote_receiver
    name: "somfy chiuse"
    internal: yes
    filters:
     - delayed_off: 2s
    rc_switch_raw:
      code: '111000010110010000001110'
      protocol: 2
    on_press:
      - binary_sensor.template.publish:
          id: tende
          state: OFF

# stato tende
  - platform: template
    name: "tende"
    device_class: opening
    id: tende       
    
cover:
  - platform: template
    device_class: awning
    name: Somfy
    lambda: !lambda |-
      if (id(tende).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }    
    open_action:
      homeassistant.service:
        service: homeassistant.turn_on
        data:
          entity_id: switch.tende_aperte
    close_action:
      homeassistant.service:
        service: homeassistant.turn_on
        data:
          entity_id: switch.tende_chiuse
    stop_action:
      homeassistant.service:
        service: homeassistant.turn_on
        data:
          entity_id: script.1589465909393
    #optimistic: true
    #assumed_state: true
```

questa invece la cover del garage che non sbaglia un colpo, e confrontandole ora forse ho capito dove sta l'inghippo... adesso provo e vi aggiorno.

```
esphome:
  name: d1mini-sezionale
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# Optional manual IP
#  manual_ip:
#    static_ip: 192.168.1.41
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0 

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1 Sezionale Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
switch:  
  - platform: restart
    name: D1 mini sezionale restart
    
text_sensor:
  - platform: version
    name: D1 mini sezionale esphome version
    hide_timestamp: true    

  - platform: wifi_info
    ip_address:
      name: D1 mini sezionale ip address
      icon: mdi:ip-network-outline     
  
### Sensore apertura sezionale
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4 #D2
      mode: 
        input: true
        pullup: true
#      inverted: TRUE
    name: sensore sezionale
    id: sensore
    device_class: garage_door
    
### sensore di connessione alla rete    
  - platform: status
    name: "D1 Mini Sezionale"  
    
### sensore segnale wifi
sensor:
  - platform: wifi_signal
    name: "D1 Mini Sezionale segnale wifi" 
    update_interval: 3600s       
    
cover:
  - platform: template
    device_class: garage
    name: Sezionale
    lambda: !lambda |-
      if (id(sensore).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }            
    open_action:
      homeassistant.service:
        service: homeassistant.turn_on
        data:
          entity_id: switch.sezionale
    close_action:
      homeassistant.service:
        service: homeassistant.turn_on
        data:
          entity_id: switch.sezionale
    stop_action:
      homeassistant.service:
        service: homeassistant.turn_on
        data:
          entity_id: switch.sezionale
    optimistic: true
```
