### DISCUSSION TITLE
Pannello Energia e apparecchiature modbus

### DISCUSSION THREAD

**Discussion by vinny74man** [indomus/forum#1524] [HUB: Home Assistant]
Ciao a tutti sto leggendo consumi e assorbimenti da dispositivi connessi ad HA tramite modbus tcp, ho creato i sensori e HA li legge e visualizza la lettura in modo corretto, il mio problema è come assegnare questi sensori al pannello energia, quando cerco di configurare il pannello energia ho il problema "non hai alcuna statistica".

Grazie

**Comment by vinny74man** [comment]
Ok ho risolto, tenevo i record disattivati, quindi non memorizzavo nulla nello storico e non potevo avere statistiche.
Grazie

**Reply by carlexweb** [reply]
Ciao come hai fatto a generare i sensori tramite Modbus? Potresti postare il codice così da capire meglio?
Grazie

**Reply by vinny74man** [reply]
questa è la configurazione nel file configuration.yaml


`modbus:
  - name: 'Power Tag Link HD'
    type: tcp
    host: '192.168.172.121'
    port: 502
    sensors: !include_dir_merge_list modbus/sensors/powertag_hd

  - name: 'Link 150'
    type: tcp
    host: '192.168.172.125'
    port: 502
    sensors: !include_dir_merge_list modbus/sensors/link_150

  - name: 'Smartlink SI B - DX'
    type: tcp
    host: '192.168.172.124'
    port: 502
    sensors: !include_dir_merge_list modbus/sensors/smartlink_dx

  - name: 'Smartlink SI B - SX'
    type: tcp
    host: '192.168.172.123'
    port: 502
    sensors: !include_dir_merge_list modbus/sensors/smartlink_sx`

**Reply by vinny74man** [reply]
questa è la configurazione in uno dei file che ho creato per i vari dispositivi precisamente il link_150

`
- name: 'Potenza Attiva Quadro Distribuzione'
  slave: 1
  data_type: float32
  address: 3059
  count: 2
  unit_of_measurement: kW
  device_class: power
  state_class: measurement
  precision: 3
  scan_interval: 60

- name: 'Potenza Attiva Quadro Fotovoltaico'
  slave: 2
  data_type: float32
  address: 3059
  count: 2
  unit_of_measurement: kW
  device_class: power
  state_class: measurement
  precision: 3
  scan_interval: 60


- name: 'Contatore Quadro Distribuzione'
  slave: 1
  data_type: float32
  address: 45165
  count: 2
  precision: 3
  unit_of_measurement: kWh
  device_class: energy
  state_class: total
  scan_interval: 60
  unique_id: 000001

- name: 'Contatore Quadro Fotovoltaico'
  slave: 2
  data_type: float32
  address: 45165
  count: 2
  precision: 3
  unit_of_measurement: kWh
  device_class: energy
  state_class: total
  scan_interval: 60
  unique_id: 000002


- name: 'Contatore Reso Quadro Distribuzione'
  slave: 1
  data_type: float32
  address: 45167
  count: 2
  precision: 3
  unit_of_measurement: kWh
  device_class: energy
  state_class: total
  scan_interval: 60

- name: 'Potenza Attiva Top Spina'
  slave: 3
  data_type: float32
  address: 3059
  count: 2
  unit_of_measurement: kW
  device_class: power
  state_class: measurement
  precision: 3
  scan_interval: 60

- name: 'Contatore Top Spina'
  slave: 3
  data_type: float32
  address: 45165
  count: 2
  precision: 3
  unit_of_measurement: kWh
  device_class: energy
  state_class: total
  scan_interval: 60

- name: 'Potenza Attiva Quadro Caricabatterie'
  slave: 4
  data_type: float32
  address: 3059
  count: 2
  unit_of_measurement: kW
  device_class: power
  state_class: measurement
  precision: 3
  scan_interval: 60

- name: 'Contatore Quadro Caricabatterie'
  slave: 4
  data_type: float32
  address: 45165
  count: 2
  precision: 3
  unit_of_measurement: kWh
  device_class: energy
  state_class: total
  scan_interval: 60
`

**Reply by vinny74man** [reply]
Ho preferito creare varie configurazioni per i vari dispostivi e ho dovuto quindi creare un file yaml per ogni dispositivo

**Comment by carlexweb** [comment]
Ciao grazie,, fammi capire una cosa, nei vari file che hai creato per he non hai meno "sensor:",non serve per creare i sensori?
Poi i sensori creati dove li trovi? Sotto la voce dispositivi?

**Comment by vinny74man** [comment]
Per il modbus non serve sensor,  poi i dispositivi li trovi in entità

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Reply by carlexweb** [reply]
Ti posto quello che ho aggiunto al file configuration.yaml

```
#modbus PER SDM120
modbus:
  - name: modbus
    type: serial
    method: rtu
    port: /dev/ttyUSB0
    baudrate: 9600
    stopbits: 1
    bytesize: 8
    parity: N
sensor:
  platform: modbus
  registers:
    - name: "Tensione"
      unit_of_measurement: Volts
      register: 30001
      register_type: input
      count: 2
      slave: 1
      precision: 2
      data_type: float
      device_class: voltage    
    - name: "Corrente"
      unit_of_measurement: Amps
      register: 30007
      register_type: input
      count: 2
      slave: 1
      precision: 2
      data_type: float
      device_class: current
    - name: "Potenza"
      unit_of_measurement: W
      register: 30085
      register_type: input
      count: 2
      slave: 1
      precision: 2
      data_type: float
      device_class: powere
    - name: "Freq"
      unit_of_measurement: Hz
      register: 30071
      register_type: input
      count: 2
      slave: 1
      precision: 2
      data_type: float
    - name: "Kwh"
      unit_of_measurement: kwh
      register: 30073
      register_type: input
      count: 2
      slave: 1
      precision: 2
      data_type: float
      device_class: power

```
non capisco dove sbaglio, non mi crea i sensori
