### DISCUSSION TITLE
aggiornamento stato sensori

### DISCUSSION THREAD

**Discussion by bf69** [indomus/forum#155] [HUB: Home Assistant]
ciao, c'è un modo per sapere se l'aggiornamento dello stato di un sensore dell'app companion è andato a buon fine? oppure se l'app è attiva e quindi i sensori affidabili? mi spiego meglio: sono a casa e il tracker mi da la posizione corretta e risulto a "casa", spengo il telefono e il tracker continua a darmi la stessa posizione, non si riesce a fare in modo che dia "non rilevabile" o qualcosa del genere...? stessa cosa per gli altri sensori...
grazie

**Comment by snakuzzo** [comment]
quei sensori sono esposti dall'app nativa. Quello che puoi fare è controllare tra la miriade di sensori che puoi esportare se c'è qualcosa che ti possa tornare utile. Oppure nel caso devi crearti un sensor template ad hoc

**Reply by bf69** [reply]
ho controllato e non mi sembra che ci sia qualcosa di utile... per creare un sensore avrei bisogno dell'ora dell'ultimo aggiornamento, ma non mi sembra che si riesca ad estrapolare.. o mi sbaglio?

**Reply by snakuzzo** [reply]
Il timestamp dell'ultimo stato di un sensore dovresti già averlo tra gli attributi dello stesso sensore

**Reply by bf69** [reply]
sotto strumenti per sviluppatori-stati si vede il timestamp dell'ultimo aggiornamento, ma in uno script o in un'automazione non riesco ad inserirlo

**Reply by snakuzzo** [reply]
Sì ma dettaglia cosa ti serve fare

**Reply by bf69** [reply]
vorrei che se lo stato di un sensore qualsiasi (per esempio la geolocalizzazione) non risponde o non è aggiornato non mantenesse l'ultimo stato ma venisse impostato su "sconosciuto" o qualcosa di simile. Se il cellulare è spento HA mantiene l'ultimo stato dei sensori, mi servirebbe che indicasse "sconosciuto". Grazie

**Reply by snakuzzo** [reply]
Prova a fare così...

Abilita per comodità il sensore [Time & Date](https://www.home-assistant.io/integrations/time_date/)

```yaml
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'
```

Poi ti crei un template sensor come questo, sostituendo `mio_sensore` con il nome del tuo sensore e a te la scelta se usare `last_changed` o `last_updated` 

```yaml
sensor:

  - platform: template
    sensors:
      mio_sensore:
        friendly_name: "Mio Sensore"
        value_template: >-
          {% if (as_timestamp(now()) - as_timestamp(states.sensor.mio_sensore.last_changed)) | int  > 1800 %}
            sconosciuto
          {% else %}
            {{ states('sensor.mio_sensore') }}
          {% endif %}
```

In pratica se la differenza tra "ORA" e l'ultimo cambio stato (o aggiornamento) è maggiore di 1800 secondi (quindi  30 minuti) restituisce stato `sconosciuto`, altrimenti ti restituisce lo stato del sensore
