### DISCUSSION TITLE
Status Unknown per tapparella tasmota

### DISCUSSION THREAD

**Discussion by Hypn0sis** [indomus/forum#1552] [HUB: Home Assistant]
Ciao a tutti, ho un problema con una tapparella tasmota configurata tramite mqtt.
Premetto che sia quella che tutte le altre tapparelle funzionano correttamente, sia coi tasti fisici che con quelli di home assistant.
Il problema nasce quando home assistant viene riavviato: al riavvio invia il messaggio per conoscere lo stato di tutti i device mqtt, tutti rispondono correttamente tranne uno.
Dimostrato dal fatto che in tutte le tapparelle configurate riesco a vedere lo stato, mentre su quella incriminata rimangono i 3 pulsanti (su, giù e stop) cliccabili.
Ho provato anche a fare un test con MQTT, pubblicando sul topic cmnd/tasmotas/shutterposition e in contemporanea messo in ascolto sul topic stat/camera/RESULT e lo status viene restituito:
Message 0 received on stat/camera/RESULT at 18:04:
{
    "Shutter1": {
        "Position": 100,
        "Direction": 0,
        "Target": 100,
        "Tilt": 0
    }
}
QoS: 0 - Retain: false

Inoltre aggiungo per completezza, che se aziono la tapparella con uno qualsiasi dei pulsanti fisici e non, lo stato ritorna disponibile.

GRAZIE a chi mi saprà aiutare!
Matteo

**Comment by snakuzzo** [comment]
Sei sicuro di aver configurato correttamente il position topic ?
Ti riporto la mia configurazione perfettamente funzionante (appena testato)
il topic del mio Dual R2 è `tasmota-tappatest` ed il group topic è `tasmotas`

```yaml
cover:
- platform: mqtt
  name: "test"
  availability_topic: "tele/tasmota-tappatest/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  command_topic: "cmnd/tasmota-tappatest/Backlog"
  payload_open: "ShutterOpen1"
  payload_close: "ShutterClose1"
  payload_stop: "ShutterStop1"
  set_position_topic: 'cmnd/tasmota-tappatest/ShutterPosition1'
  position_topic: "stat/tasmota-tappatest/RESULT"
  position_open: 100
  position_closed: 0
  position_template: >
    {% if ('Shutter1' in value_json) and ('Position' in value_json.Shutter1) %}
      {{ value_json.Shutter1.Position }}
    {% else %}
      {% if is_state('cover.test', 'unknown') %}
        50
      {% else %}
        {{ state_attr('cover.test','current_position') }}
      {% endif %}
    {% endif %}
  retain: false
  optimistic: false
  qos: 1
```
