### DISCUSSION TITLE
Automazione non parte se il sensore è già in STATO "ON"

### DISCUSSION THREAD

**Discussion by jard159** [indomus/forum#1559] [HUB: Home Assistant]
Salve a tutti, sto impazzendo con una automazione e non riesco a venirne a capo.
in pratica ho un sensore (binary_sensor) che va su ON se la temperatura all'interno di una stanza è superiore a 20°C.
Connesso a questo "stato ON" c'è una automazione che fa partire un ventilatore. Tale automazione la abilito da un controllo `input_boolean.partenza_fan`

Tuttavia, se il mio input_boolean è spento (off) ma il binary_sensor rileva 21° e quindi il suo stato è già ad "ON" e provo a far partire l'automazione portando ad on l'input_boolean, questa non ne vuole sapere di partire. Se manualmente da "strumenti per sviluppatori" cambio lo stato del binary_sensor da off e poi di nuovo ad on (con input_boolean attivato) l'automazione parte......

credo di aver capito che l'automazione parte solo se c'è il cambio di stato verso on ma come fare invece per farla partire comunque? che tipo di controllo dovrei implementare???

grazie mille a chi mi vorrà aiutare. 

```
- alias: 005_fan_ON
  trigger:
    - platform: state
      entity_id: binary_sensor.alarm_temperature
      to: 'on'
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.fan
mode: single
```
