### DISCUSSION TITLE
container openvpn

### DISCUSSION THREAD

**Discussion by giacomo-git** [indomus/forum#1566] [HUB: Home Assistant]
Ciao sto seguendo questa giuda
https://indomus.it/guide/collegare-raspberry-pi-a-una-vpn-con-openvpn-client-raspberry-pi-os-e-docker/
Quando provo ad avviare il cotainer

`docker container start openvpn`

ottengo

```
Error response from daemon: No such container: openvpn
Error: failed to start containers: openvpn
```

temo dipenda da un punto che non mi è molto chiaro

In openvpn-client.ovpn
ho inserito

```
pull-filter ignore "route-gateway"
askpass /**vpn**/NOME_UTENTE.pwd
ping-restart 10
```

Su  compose ho inserito

```
  openvpn:
    image: dperson/openvpn-client
    container_name: openvpn
    cap_add:
    - net_admin
    network_mode: host
    volumes:
    - /home/pi/openvpn**:/vpn**
    restart: always
```

quindi immagino vada a cercare l'account nella direcory **/vpn**
Tuttavia seguendo la guida no ho creato la dir **vpn** ma solo
`/home/pi/openvpn`
all'interno della quale ci sono i 2 file
```
xxx.pwd
xxx.ovpn
```

avrei dovuto creare ache la directory /**vpn**??

Grazie
