### DISCUSSION TITLE
Notifica da App HA con pulsante per comando apertura Cancello

### DISCUSSION THREAD

**Discussion by bondeste** [indomus/forum#1572] [HUB: Home Assistant]
Ciao a tutti, sto cercando di creare una notifica tramite l'app di HA.
L'idea è quella che se viene premuto il citofono di casa mi arriva una notifica tramite HA con un flusso video della video camera con un pulsante per apertura cancello.
Per il momento sono riuscito ad integrare la videocamera in HA, e sto cercando di ricreare la notifica seguendo la guida del seguente link: "https://companion.home-assistant.io/docs/notifications/actionable-notifications".
Ma non riesco a capire come posso abbinare al pulsante della notifica la chiamata ad un service come ad esempio `switch.turn_on`.
Qualcuno di voi a mai fatto qualcosa di simile oppure sa darmi qualche dritta?

**Comment by Larry-78** [comment]
Ciao, in realtà è semplice. Devi creare due automazioni, per esempio ho ipotizzato che tu abbia un `binary_sensor` che rilevi la pressione del pulsante del citofono, ovviamente valido per qualsiasi tipo di trigger in riferimento alla prima automazione.
```yaml

#Prima automazione
alias: actionable_ notification
trigger:
  - platform: state
    entity_id: binary_sensor.citofono
    to: 'on'

action:
  - service: notify.mobile_app #questo servizio sarà personalizzato con il nome che hai dato alla tua app
    data:
      message: Qualcuno ha suonato #questo messaggio sarà visibile al di sopra del pulsante nella notifica
      data:
        actions:
          - action: apri_cancello #questo è un nome personalizzabile da assegnare alla action
            title: Apri Cancello #questo è il titolo che comparirà sul pulsante da premere nella notifica
mode: single


#Seconda automazione
alias: actionable_ notification_2
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: apri_cancello #questo è il nome assegnato nella prima automazione

action:
  - service: switch.turn_on
    target:
      entity_id: switch.cancello
mode: single
```
Volendo puoi creare più pulsanti  e molto altro, il mio è un semplice esempio.
