### DISCUSSION TITLE
Assorbimenti non corretti

### DISCUSSION THREAD

**Discussion by braudoo** [indomus/forum#1573] [HUB: Home Assistant]
Ciao a tutti,
mi trovo davanti a questo dilemma.
Due prese identiche una sul forno e l'altro sul frigo, integrate con LocalTuya e di cui valori di assorbimento li verifico anche dalla app.
Trovo che la lavatrice mi restituisce valori corretti, mentre il forno no.

![image](https://user-images.githubusercontent.com/58866563/158064882-7cdbadca-07e8-465a-a222-44ad36fce156.png)

Quale potrebbe essere il problema?
La potenza di entrambi gli elettrodomestici sono corretti, gli assorbimenti purtroppo no.

Grazie per un eventuale aiuto.

**Comment by indomus** [comment]
Fatti un sensore [tramite integrale](https://www.home-assistant.io/integrations/integration/) e calcolatelo a partire dalla potenza.

**Comment by braudoo** [comment]
Ciao, come puoi vedere i senori di assorbimento me li sono già ricavati tramite integrale:

```
sensor:
  - platform: integration
    source: sensor.forno_power
    name: forno_energy
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.lavatrice_power
    name: lavatrice_energy
    unit_prefix: k
    round: 2
```

L'unica cosa che posso provare a fare è andare a ritoccare i valori di assorbimento nel file _core.restore_state_
