### DISCUSSION TITLE
Gestione tapparelle in base al sole e pioggia

### DISCUSSION THREAD

**Discussion by bircastri** [indomus/forum#1576] [HUB: Home Assistant]
Buongiorno a tutti.
Ho installato home assistant sul mio Mac e ho iniziato a fare qualche automatismo. Il primo che ho implementato è quello legato alle tapparelle. Ho le tapparelle elettriche comandate dagli shelly 2.5

Volevo far si che le tapparelle della zona notte + quella del bagno si chiudessero al tramonto (1.0h prima del tramonto), il sole è quasi nullo e tenere le tapparelle chiuse fornisce un piccolo isolamento termico in più. 

Fin qui tutto ok, ci sono riuscito, adesso però volevo fare in modo che se il sistema riconosce che sta piovendo, mi chiude le tapparelle in automatico sempre quelle della zona notte + bagno in quanto sono le tapparelle che quando piove si bagnano.

Non riesco a capire come poter fare ? 

qualcuno di voi saprebbe aiutarmi?

**Comment by indomus** [comment]
Beh non è difficile: ti basta integrare un [sensore di pioggia](https://indomus.it/componenti/netatmo-pluviometro-wireless/) e metterlo in automazione.
Volendo, [pure così](https://indomus.it/progetti/realizzare-un-sensore-di-pioggia-domotico-modificandone-uno-di-allagamento/).

**Reply by bircastri** [reply]
Grazie per la risposta. Io in realtà volevo fare qualcosa basandomi sulle previsioni meteo piuttosto che inserire un altro sensore però sono aperto a tutte le soluzioni.

**Reply by indomus** [reply]
Dipende dalla precisione che vuoi :)

**Reply by bircastri** [reply]
guarda per la questione tapparelle, a me non dispiaceva farlo senza sensori ma con le previsioni meteo. sai darmi qualche consiglio su come poter implementare il tutto ?

**Reply by KC-inDomus** [reply]
Beh di base ha un'entità weather.* che contiene solitamente un array con le previsioni, o direttamente lo stato ("rainy" o "light rain" penso sia lo stato che ti serve).
fatti un sensor template del tipo:

```
sensor:
  - platform: template
    sensors:
      precipitazione:
        friendly_name: "Quantità di pioggia +6h"
        value_template: '{{ states.weather.whateveristhename.attributes.forecast[0].precipitation|float }}'
        unit_of_measurement: "mm" 
```

e poi mettiti l'entità in automazione (trigger numeric_state, above x mm), tipo

```
  trigger:
    - platform: numeric_state
      entity_id: sensor.precipitazione
      above: 0
```

**Reply by bircastri** [reply]
Grazie della risposta. 
Sono un novellino di Home Assistant quindi perdonami, perdonatemi se faccio delle domande sciocche o idiote. Come faccio a creare un sensore ???
Con questo codice `states.weather.whateveristhename.attributes.forecast[0].precipitation|float` praticamente stai dicendo che il sensore mi restituirà il valore della precipitazione come valore FLOAT in mm. quindi esempio pioggia di 2mm o qualcosa del genere giusto ?

**Reply by indomus** [reply]
esatto, corretto.
per creare il sensore devi aggiungere un blocco sensor [nel file di configurazione di home assistant](https://indomus.it/guide/configuration-yaml-capire-il-file-di-configurazione-di-home-assistant/), e riavviarlo.

**Reply by bircastri** [reply]
Allora nel file "Configuration.yaml" ho scritto questo (anche se non ho capito cosa indica quel +6h) so che è solo testo, ma volevo capire perchè lo avevi pensato cosi.:

```
sensor:
  - platform: template
    sensors:
      precipitazione:
        friendly_name: "Quantità di pioggia +6h"
        value_template: '{{ states.weather.whateveristhename.attributes.forecast[0].precipitation|float }}'
        unit_of_measurement: "mm" 
```

Nel file "automation.yaml" ho scritto questo invece (premetto che questo mi è stato generato automaticamente utilizzando la funzione Automazione e scene del mio home assistant):

```
- id: '1647435454358'
  alias: Chiudi tapparelle se Piove
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.precipitazione
    attribute: unit_of_measurement
    from: '5'
    to: '10'
  condition:
  - condition: trigger
    id: ''
  action:
  - device_id: 6b2fec6275ed1ebdf4381XYZa45d023a
    domain: cover
    entity_id: cover.tapparella_camera_da_letto
    type: set_position
    position: 0
  mode: single
```

Adesso chiedo se ho capito bene il senso: 
quando il sensore pioggia dice che piove da 5 a 10 mm di pioggia, chiude la tapparelle camera da letto, giusto ? 

Questo evento viene eseguito ogni X minuti ? viene triggerato in automatico ? inoltre i valori 5 e 10 mm di pioggia vanno bene sono soglie troppo basse ???

**Reply by KC-inDomus** [reply]
ti consiglio piuttosto:

```
  - platform: numeric_state
    entity_id: sensor.precipitazione
    attribute: unit_of_measurement
    above: 5
```

il trigger così configurato fa sì che l'automazione scatti sopra i 5mm previsti entro le 6 ore (+6h).

**Reply by bircastri** [reply]
L ho modificato come da te consigliato:

```
- id: '1647435454358'
  alias: Chiudi tapparelle se Piove
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.precipitazione
    attribute: unit_of_measurement
    above: '2'
  condition:
  - condition: trigger
    id: ''
  action:
  - device_id: 6b2fec6275ed1ebdf43817a4a45d023a
    domain: cover
    entity_id: cover.tapparella_camera_da_letto
    type: set_position
    position: 0
  mode: single
```

Però come fa il sistema a capire che è entro le 6h ??? In più secondo te è plausibile farlo quasi real time, mi spiego se tra 6h è prevista pioggia io non vorrei chiudere le tapparelle, io vorrei chiudere le tapparelle, solo se è magari prevista pioggia oltre i 2mm entro i prossimi 30 minuti "esempio", come si può modificare ???

**Reply by KC-inDomus** [reply]
no, non l'hai corretto come ti ho consigliato, vedi bene. la condition, inoltre, è tutta sbagliata (cosa serve?).
le 6+ sono calcolate nell'array dell'entità weather, è la sua integrazione a generare e aggiornare le previsioni.

**Reply by bircastri** [reply]
Ho corretto cosi:
```

- id: '1647435454358'
  alias: Chiudi tapparelle se Piove
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.precipitazione
    attribute: unit_of_measurement
    above: 2
  action:
  - device_id: 6b2fec6275ed1ebdf43817a4a45d023a
    domain: cover
    entity_id: cover.tapparella_camera_da_letto
    type: set_position
    position: 0
  mode: single
```

io ho messo 2 mm piuttosto che 5.

La questione del 6+ però non l ho capita perdonami...

**Reply by Scialla** [reply]
il forecast del sensore da le previsioni di pioggia per le successive sei ore quindi il trigger scatta se nelle previsioni delle prossime sei ore danno piu dei mm di pioggia che glil indichi
above 2 significa che se le previsioni danno più di 2 mm di pioggia l'automazione triggera
se metti from 5 to 10 non triggererà mai perchè dovrebbe passare da una previsione di 5mm a una previsione di 10mm
il trigger scatta quando la condizione richiesta si avvera e da 5 a 10 non si avvererà mai

**Reply by KC-inDomus** [reply]
il trigger è sbagliato

**Reply by bircastri** [reply]
ho capito grazie per la delucidazione.
Il trigger che ho messo adesso però è above 2 cioè se nelle prossime 6 ore c'è più di 2 mm di pioggia in cosa ho sbagliato ???

perdonatemi ma sono novello di home assistant e alcuni concetti per me sono ancora ostici

**Reply by KC-inDomus** [reply]
usa `- platform: numeric_state`, non `- platform: state`, il resto è corretto. above e below si usano con `numeric_state`

**Reply by bircastri** [reply]
Modificato cosi:

```
- id: '1647435454358'
  alias: Chiudi tapparelle se Piove
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.precipitazione
    attribute: unit_of_measurement
    above: 2
  action:
  - device_id: 6b2fec6275ed1ebdf43817a4a45d023a
    domain: cover
    entity_id: cover.tapparella_camera_da_letto
    type: set_position
    position: 0
  mode: single
```

Mi spieghi la differenza tra numeric_state e state ???

Inoltre con questo sistema io posso gestire le tapparelle in base allo stato del sensore pioggia nelle prossime 6 ore. Non c'è la possibilità di fare qualcosa più a corto tempo non 6ore ma 1 ???

**Reply by indomus** [reply]
Le varie piattaforme _trigger_ le trovi spiegate [qui](https://www.home-assistant.io/docs/automation/trigger/). 
Se vuoi lo stato "istantaneo", devi creare diversamente il sensore, ovvero devi prendere l'attributo dello stato principale, non il record 0 dell'array.

```
sensor:
  - platform: template
    sensors:
      precipitazione:
        friendly_name: "Quantità di pioggia +6h"
        value_template: '{{ states.weather.whateveristhename.attributes.precipitation|float }}'
        unit_of_measurement: "mm" 
```
