### DISCUSSION TITLE
Problema con gli storici

### DISCUSSION THREAD

**Discussion by edifabio-72** [indomus/forum#1578] [HUB: Home Assistant]
Buonasera ragazzi ho un problema con la visualizzazione degli storici.
Dopo il reboot, vedo lo storico di un breve periodo e poi il valore rimane fisso senza aggiornamenti fino al reboot successivo.
Consigli?

Questa la mia configurazione:
```

history:

logbook:
  include:
    domains:
      - automation
      - person
      - light
    entity_globs:
      - sensor.temp*
      - sensor.umi*
      - sensor.acquario*
      - sensor.shelly*
      - sensor.potenza*
      - sensor.sensore*
      - sensor.ener*
      - sensor.durata*
      - sensor.ult*
      - sensor.cur*
      - sensor.hp*
      - light.*
      - switch.*
    entities:
      - binary_sensor.sensore_pir
      - binary_sensor.porta_congelatore
      - sensor.shelly_shem_3_8caab561d312_1_current_consumption
      - sensor.apertura_tenda
      - sensor.sm_g975f_livello_della_batteria
      - sensor.s10_plus_lisa_livello_della_batteria
      - sensor.samsung_galaxy_tab_s6_livello_della_batteria
      - sensor.a71_francesca_livello_della_batteria
      - sensor.galaxy_tab_5_federico_livello_della_batteria
      - sensor.tablet_acer_francesca_livello_della_batteria
# Redirect output to Docker into Synology NAS influxdb
influxdb:
  host: !secret influxdb_host
  port: 3004
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: homeassistant
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - automation
      - person
      - light
    entity_globs:
      - sensor.temp*
      - sensor.umi*
      - sensor.acquario*
      - sensor.shelly*
      - sensor.potenza*
      - sensor.sensore*
      - sensor.ener*
      - sensor.durata*
      - sensor.ult*
      - sensor.cur*
      - sensor.hp*
      - light.*
      - switch.*
    entities:
      - binary_sensor.sensore_pir
      - binary_sensor.porta_congelatore
      - sensor.shelly_shem_3_8caab561d312_1_current_consumption
      - sensor.apertura_tenda
      - sensor.sm_g975f_livello_della_batteria
      - sensor.s10_plus_lisa_livello_della_batteria
      - sensor.samsung_galaxy_tab_s6_livello_della_batteria
      - sensor.a71_francesca_livello_della_batteria
      - sensor.galaxy_tab_5_federico_livello_della_batteria
      - sensor.tablet_acer_francesca_livello_della_batteria
# Redirect output to Synology NAS Maria DB
recorder:
  db_url: !secret MariaDB_url
#  purge_keep_days: 5
  purge_keep_days: 30
  purge_interval: 1
  #purge_interval: 60
  include:
    domains:
    - switch
    - light    
    - sensor    
    #- climate
    - binary_sensor
    - device_tracker
    - person
    entity_globs:
      - sensor.temp*
      - sensor.umi*
      - sensor.acquario*
      - sensor.shelly*
      - sensor.potenza*
      - sensor.sensore*
      - sensor.ener*
      - sensor.durata*
      - sensor.ult*
      - sensor.cur*
      - sensor.hp*
      - light.*
      - switch.*
    entities:
      - binary_sensor.sensore_pir
      - binary_sensor.porta_congelatore
      - sensor.shelly_shem_3_8caab561d312_1_current_consumption
      - sensor.apertura_tenda
      - sensor.sm_g975f_livello_della_batteria
      - sensor.s10_plus_lisa_livello_della_batteria
      - sensor.samsung_galaxy_tab_s6_livello_della_batteria
      - sensor.a71_francesca_livello_della_batteria
      - sensor.galaxy_tab_5_federico_livello_della_batteria
      - sensor.tablet_acer_francesca_livello_della_batteria    
  exclude:
    domains:
      - automation
      - updater  
    entities:
    - sensor.last_boot
    - sensor.date
    - sensor.time
    - sensor.workday
    - sun.sun
    - sensor.moon
    - sensor.fasi_lunari
    - sensor.stagioni
    - sensor.season
    - sensor.date_time_iso # Don't record date and time
    - sensor.yr_symbol # Ignore this as well
    - group.weather # Don't save weather     

```
