### DISCUSSION TITLE
MotionEye su Raspberry1 con Docker + Ha Supervisor su Raspberry2

### DISCUSSION THREAD

**Discussion by diaz66** [indomus/forum#1584] [HUB: Home Assistant]
Un saluto alla community Indomus.

Ho ripreso in mano un Raspy pi 4b 4 Giga che avevo in un cassetto (che, considerando quello che costano adesso non era il caso di lasciarlo li ). Mi sto "dilettando" , grazie alle vostre guide ,  ad installare Container Docker vari , a cominciare da  Portainer e poi MotionEye.

MotionEye funziona e vedo correttamente la mia Cam Tapo e pure una ep32cam con Tasmota. Ora, volevo "gestire" dall' atro Raspberry dove gira HA , sulla stessa rete locale, il MotionEye , tramite per esempio Iframe Lovelance.

Ma quì mi blocco. 

Su Iframe metto ip locale http di MotionEye ma ad HA non piace: 
![image](https://user-images.githubusercontent.com/32227980/159092951-b143d1c8-af17-4653-8474-61436194b018.png)

Ho visto "googlando" che probabilmente si potrebbe risolvere con NgInx , Caddy etc. , ho installato Container Nginx dove gira Motion ma per le mie conoscenze la faccenda si complica.

Capisco che sto chiedendo troppe cose in una  , magari esistono modi più semplici, o magari mi basterebbe un punto di partenza per proseguire.

Grazie comunque.

**Comment by snakuzzo** [comment]
devi fare in modo che la URL che imposti in panel iframe sia esposta in https e con certificato valido rilasciato da una CA...e questo vuol dire esporre direttamente su internet quella URL

**Reply by diaz66** [reply]
mmmh ... grazie 1000 per la risposta snakuzzo....mi sa che  e meglio se vado a dormire.... [penso che mi leggerò con calma questo ](https://indomus.it/guide/come-installare-e-configurare-caddy-con-docker-su-raspbian-di-raspberry-pi/)...(e te pareva) non capisco cosa si intende per "esporre" , capisco il discorso del CA, quindi...forse , anche se sono entrambi sulla stessa rete locale, devo crearmi un nuovo FQDM , per esempio con DUCKDNS, per il secondo raspberry , solo per ottenere un CA....boh, va beh....piano piano ci arrivo eheheh....

**Comment by Nik71git** [comment]
approfitto del topic per evitare di crearne un altro: siete certi della seguente config per motioneye su docker compose:
 ```
motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:master-armhf
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/home/pi/motioneye:/etc/motioneye"
    - "/home/pi/motioneye/storage:/var/lib/motioneye"
    services:
      dns:
        hostname: 'motioneye'
    network_mode: host
    restart: always
```
in quanto la parte service (dns) mi ritorna errore. commentandola funziona tutto
