### DISCUSSION TITLE
Utilizzo di input_boolean e input_number

### DISCUSSION THREAD

**Discussion by Virgilio123** [indomus/forum#1586] [HUB: Home Assistant]
Buongiorno a Tutti, e scusate se chiedo qualcosa già affrontato.

ho una esp32 che tramite esphome dialoga con la mia installazione di Home Assistant.

Quindi ho la necessita di creare 4 input_number e 1 input_boolean

al momento la mia configurazione è la seguente:

```
input_boolean:
   notify_on:
   name: "Salvataggio"
   icon: mdi:alarm-panel-outline
input_number:
   slider1:
     name: "Temperatura 1"
     initial: 0
     min: 0
     max: 25
     step: 0.5
  slider2:
     name: "Temperatura 2"
     initial: 0
     min: 0
     max: 25
    step: 0.5
  box1:
    name: "Ora"
    initial: 0
    min: 0
    max: 23
    step: 1
   mode: box 
  box2:
    name: "Minuti"
    initial: 0
    min: 0
    max: 59
    step: 1
   mode: box 
```
Le entità vengono correttamente create e condivise con esphome.
il mio problema è che vorrei dare a queste entità dei nomi più chiari, perché poi nelle automazioni devo scrivere "input_number.box1" "input_number.box2" etc. etc. mentre sarebbe più chiaro scrivere "input_number.Ora" "input_number.Minuti" etc. etc.

Grazie.
