### DISCUSSION TITLE
Temporizzare switch

### DISCUSSION THREAD

**Discussion by nicolacampagnolo** [indomus/forum#159] [GENERALE - Discussioni generiche]
Ciao a tutti,
sto provando ad accendere la resistenza del bollitore ACS tramite uno switch, quando la produzione del FTV supera una determinata soglia, e vorrei che restasse accesa per un tempo determinato.
Scopiazzando qua e la ho elaborato questo script, ma senza esito. 
O meglio, se metto solo la prima parte dello script "accensione ACS" al superamento dei 2500 w la resistenza si accende e ovviamente non si spegne. 
Se metto anche la seconda parte (che dovrebbe andare a spegnere dopo un determinato delay) la resistenza non si accende più al superamento dei 2500 w, ma se accendo manualmente la resistenza tramite lo switch, poi dopo il delay impostato si spegne (i 10 secondi sono impostati per la fase di test).

Ho fatto altre prove ma non ne vado fuori.

Ecco il codice:

```
automation:
  alias: "Accensione ACS"
  trigger:
    platform: numeric_state
    entity_id: sensor.tasmota_energy_power
    above: 2500
  condition: []
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_10011171a0
      
automation:
  alias: "Spegnimento ACS"
  trigger:
   - platform: state
     entity_id: switch.sonoff_10011171a0
     to: 'on'
  condition: []
  action:
    - delay: 10
    - service: switch.turn_off
      data:
        entity_id: switch.sonoff_10011171a0
```

Grazie.
Nicola.

**Comment by snakuzzo** [comment]
Per come le hai impostate non si riaccenderà mai se non scende prima sotto i 2500.

**Comment by nicolacampagnolo** [comment]
Lo switch è in off, quando si superano i 2500 w deve andare in on per un determinato tempo.
Questo lo fa correttamente se inserisco solo la prima parte di script.
Se inserisco la seconda parte per lo spegnimento il meccanismo si blocca. 
Non capisco dove però


Edit: forse ho capito. Devo lavorare al contrario ovvero under 2500 off?

**Reply by snakuzzo** [reply]
Sì...da quello che hai scritto, se non ho capito male, deve comportarsi esattamente come un termostato...solo che il tuo sensore non è in ⁰C ma in W.
Poi...se proprio vuoi gestirla come hai indicato, userei una sola automazione sfruttando il trigger object e i template

**Comment by nicolacampagnolo** [comment]
Grazie per la risposta. Domani provo a sostituire "above" con "under"

Per quanto riguarda il trigger object e i template Purtroppo per ora non sono alla mia portata. Devo studiare ancora....

Domani provo e poi ti faccio sapere.

**Reply by snakuzzo** [reply]
Ma no...se sostituisci `above` con `under` si accenderà solo quando va sotto i 2500W.

**Reply by snakuzzo** [reply]
```yaml
automation:

- id: gestione_acs
  alias: "Gestione ACS"
  trigger:
    # L'unico trigger è quando supera i 2500 W
    - platform: numeric_state
      entity_id: sensor.tasmota_energy_power
      above: 2500
      # ...se ci rimane per almeno 30s
      for:
        seconds: 30
  action:
    # Accende lo switch
    - service: switch.turn_on
      target:
        entity_id: switch.sonoff_10011171a0
    # Aspetta un tempo stabilito
    - delay: 10
    # Spegne lo switch
    - service: switch.turn_off
      target:
        entity_id: switch.sonoff_10011171a0
```

**Comment by nicolacampagnolo** [comment]
Stasera riprovo con il tuo codice e ti faccio sapere. Grazie.

**Comment by nicolacampagnolo** [comment]
Testato ora, funziona tutto perfettamente. Grazie ancora per l'aiuto.

Buona serata. Nicola.

**Comment by nicolacampagnolo** [comment]
Rieccomi.
Purtroppo ora ho notato un problema. 
Avevo configurato precedentemente, seguendo una guida trovata su indomus, l'avviso del superamento di una soglia di produzionde del FTV tramite speaker google. Ora, dopo l'aggiunta della nuova automazione, non funziona più. In pratica funziona la nuova automazione ma la vecchia no. Se rimuovo la nuova automazione , quella vecchia torna a funzionare perfettamente.
Escluderei un problema di script, ma sembra che non gestica le due automazioni insieme. 
Qualche suggerimento?

Vi allego il file completo configuration.yaml 

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'it'


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

automation:
  alias: "Notifica superamento soglia"
  trigger:
    platform: numeric_state
    entity_id: sensor.tasmota_energy_power
    above: 5000
  condition: []
  action:
    - service: tts.google_say
      entity_id: media_player.cucina
      data:
        message: "La produzione ha superato i 5000 watt"
    - service: tts.google_say
      entity_id: media_player.googlehome3400
      data:
        message: "La produzione ha superato i 5000 watt"        
        
hacs:
  token: ***************************************
  
sonoff:
  username: username
  password: password
  reload: always


automation:

- id: gestione_acs
  alias: "Gestione ACS"
  trigger:
    # L'unico trigger è quando supera i 2500 W
    - platform: numeric_state
      entity_id: sensor.tasmota_energy_power
      above: 2500
      # ...se ci rimane per almeno 30s
      for:
        seconds: 30
  action:
    # Accende lo switch
    - service: switch.turn_on
      target:
        entity_id: switch.sonoff_10011171a0
    # Aspetta un tempo stabilito
    - delay: 10
    # Spegne lo switch
    - service: switch.turn_off
      target:
        entity_id: switch.sonoff_10011171a0
```

**Reply by snakuzzo** [reply]
Non puoi scrivere automation: nello stesso file due volte :|
Raga...studiate come si scrivono i file YAML

**Comment by nicolacampagnolo** [comment]
Grazie per il suggerimento. Oggi studio un po e provo a sistemare.....

**Reply by snakuzzo** [reply]
in generale...nel file yaml le automazioni le metti sotto un solo `automation:`, i sensori sotto un solo `sensor:`, e così via...

es.

```yaml
automation:
- automazione1
- automazione2

sensor:
- sensore1
- sensore2

etc.
```

Aiutati con un linter (es. [YAMLINT](http://www.yamllint.com/)...oppure con un editor/IDE decente tipo VSCode, SublimeText, etc
