### DISCUSSION TITLE
camera.c3wn.. does not support record service

### DISCUSSION THREAD

**Discussion by calz64** [indomus/forum#1590] [HUB: Home Assistant]
Buongiorno, è cambiato qualcosa con ultimi aggiornamenti? Ho un'automazione, come quella sotto riportata, per registrare video (fatta seguendo la guida ufficiale), prima funzionava perfettamente ora da questo errore: 'camera.c3wn... does not support record service', bisogna cambiare servizio? grazie
```
service: camera.record
target:
  device_id: 20452834acfa........
data:
  duration: 60
  filename: ' /share/motioneye/Camera1/camera...._{{now().strftime("%Y%m%d-%H%M%S")}}.mp4 '
```
Aggiungo la directory dei file video è nella whitelist.

EDIT. ho provato anche con il servizio snapshot per catturare una foto jpg ma il file viene creato nella directory ma è di 0 kB e ovviamente non si apre.
