### DISCUSSION TITLE
Sonoff lan

### DISCUSSION THREAD

**Discussion by Elio60** [indomus/forum#1591] [GENERALE - Discussioni generiche]
Buongiorno, sono un neofita e spero di trovare risposte ai miei quesiti.
Ho vari dispositivi Sonoff con firmware 3.5.1 originale. Per prova ho installato una versione portable di Hassio (scaricata da GitHub) su pc fisso. Nel file configuration.yaml ho inserito la stringa sotto per far riconoscere i sonoff attuali e quelli futuri

```
sonoff:
  Username: mia mail dell'app Ewelink
  Password: mia psw dell'app Ewelink
  reload: always
```

Il tutto funziona e i Sonoff vengono rilevati e si possono tutti gestire, ma se cambio Username e Psw inserendo ad esempio quella di mia moglie (che ha l'account per la condivisione di alcuni dispositivi sul suo smartphone) oppure un altro mio account che però attualmente non uso per l'app di Ewelink, al riavvio di HAssio i Sonoff vengono rilevati con il loro ID (e non con il nome dato al Sonoff ad esempio Luci scale, luci cantina ecc) ma sono in ombra e non si possono gestire. Ho provato anche a cancellare il file .sonoff.json e riavviare Hassio ma l'anomalia permane. 

Inoltre sempre nel file configuration.yaml ho inserito un contatore (sotto le righe) per verificare quanti dipositivi sono in stato di ON (non è farina del mio sacco)

```
# conta i dispositivi SonOff in stato di ON.
sensor:
  - platform: template
    sensors:
      luci_accese:
        friendly_name: 'Luci Accese'
        icon_template: 'mdi:lightbulb-group-outline'
        value_template: "{{ states.switch | selectattr('state', 'eq', 'on') | list | count }}"

Il tutto funziona sino ma se  inserisco (sempre nel file configuration.yaml) questa stringa per visualizzare Data o Ora

```
# Example configuration.yaml entry
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
     ```
al successivo riavvio della macchina il contatore dei dispositivi non c'è ed al suo posto compare un tringolo giallo con un avviso di entità non disponibile: sensor.luci_accese.

Ringrazio sin d'ora chi mi risponderà

elio
