### DISCUSSION TITLE
Automazione, aggiungere consumo

### DISCUSSION THREAD

**Discussion by rowiz** [indomus/forum#1592] [HUB: Home Assistant]
Ciao a tutti, ho la seguente automazione che mi avverte di quando un dato elettrodomestico termina il ciclo inviandomi un messaggio su telegram, riportandomi anche la durata dello stesso
```
- alias: "statistiche ultimo fine lavatrice"
  id: "statistiche_ultimo_ciclo_lavatrice"
  trigger:
   - platform: state
     entity_id: sensor.tempo_ultimo_ciclo_lavatrice
  condition: "{{ not is_state('binary_sensor.lavatrice_accesa','on') }}"
  action:
    - service: notify.ros
      data:
        message: >
          "Durata ciclo lavatrice: {{ trigger.from_state.attributes.value }}"
```

come posso fare per poter aggiungere anche il consumo? Mi era venuto in mente di aggiungere anche il sensore di tipo energy (quindi in questo caso sensor.lavatrice_energy) tra i trigger e poi andare a valutare nella action la variazione (non che sappia come si faccia, ma intanto almeno avevo avuto una mezza idea 😄 ), ma poi non potrei più referenziarmi alla durata con quel from_state.attributes, avendo più di un trigger....avevo letto anche qualcosa in merito agli input_number ma non so se possono fare al caso mio. 
Riuscite ad aiutarmi? Non so proprio da dove cominciare a studiare...
Grazie mille!

**Comment by xyzmauro** [comment]
Raccolgo l’invito di @snakuzzo Intanto per rassicurarti che se metti più trigger il to_state o from_state sa quale trigger ha fatto scattare l’automazione e di conseguenza avrai il value relativo..
Venendo a quello che vorresti fare, io userei come trigger il binary_sensor.lavatrice_accesa poi una choose con
- Binary on -> msg “lavatrice partita” e in un imput_number di appoggio scrivi il valore in quel momento del sensor.lavatrice_energy
- binary off -> msg “lavatrice terminata”, tempo ultimo lavaggio uguale al valore di sensor.tempo_ultimo_ciclo_lavatrice e consumo dato dalla differenza tra sensor.lavatrice_energy e il valore precedentemente salvato nell’input_number

spero di esser stato d’aiuto 😉

**Comment by rowiz** [comment]
L'idea è chiara, ora devo litigare con l'attuazione.

Direi che visto che ho questo

```
  - binary_sensor:
      - name: "lavatrice_accesa"
        delay_on:
          seconds: 90
        delay_off:
          seconds: 90
        state: >
          {{ states('sensor.lavatrice_power')|float(default=0.0)  > 1.9 }}
```

aggiungerei sul configuration.yaml:

```
input_number:
  consumo_lavatrice:
    name: "consumo lavatrice"
    initial: 0
```

ora, penso: dovrei modificare lo scheletro della automazione così


```
- alias: "statistiche ultimo fine lavatrice"
  id: "statistiche_ultimo_ciclo_lavatrice"
  trigger:
   - platform: state
     entity_id: binary_sensor.lavatrice_accesa
  action:
	- choose:
		- alias: "Notifica Lavatrice Accesa"
		  conditions:
			- condition: state
			  entity_id: binary_sensor.lavatrice_accesa
			  state:  "{{ is_state('binary_sensor.asciugatrice_accesa','on') }}"
	      sequence:
		    - service: notify.ros
			  data:
              message: >
                "Lavatrice partita"
		- alias: "Notifica Ciclo Finito"
		  conditions:
			- condition: state
			  entity_id: binary_sensor.lavatrice_accesa
			  state:  "{{ is_state('binary_sensor.asciugatrice_accesa','off') }}"
	      sequence:
		    - service: notify.ros
			  data:
              message: >
                ""Durata ciclo lavatrice: {{ sensor.tempo_ultimo_ciclo_lavatrice }}"
``` 

e inserire nella prima choose la valorizzazione dell'input number, mettendoci il valore di sensor.lavatrice_energy, mentre nella seconda andrei a inserire nel corpo del messaggio il nuovo valore di sensor.lavatrice_energy sottratto dal valore prima immagazzinato. Corretto?
In tal caso, come faccio a fargli memorizzare il valore? Che service devo specificare?

**Reply by xyzmauro** [reply]
Esatto,il service da usare nella 1ª choose è input_number.set_value con entity_id il tuo input_number e value lo stato di sensor.lavatrice_energy , nella 2ª la differenza dei valori (ricordati il cast a float nel fare il calcolo)

**Comment by rowiz** [comment]
Quindi una cosa del genere

```
- alias: "statistiche ultimo fine lavatrice"
  id: "statistiche_ultimo_ciclo_lavatrice"
  trigger:
   - platform: state
     entity_id: binary_sensor.lavatrice_accesa
  action:
	- choose:
		- alias: "Notifica Lavatrice Accesa"
		  conditions:
			- condition: state
			  entity_id: binary_sensor.lavatrice_accesa
			  state:  "{{ is_state('binary_sensor.asciugatrice_accesa','on') }}"
	      sequence:
		    - service: notify.ros
			  data:
              message: >
                "Lavatrice partita"
                    - service: consumo_lavatrice.set_value
                       value: states(sensor.lavatrice_energy) | float (default=0.0)
		- alias: "Notifica Ciclo Finito"
		  conditions:
			- condition: state
			  entity_id: binary_sensor.lavatrice_accesa
			  state:  "{{ is_state('binary_sensor.asciugatrice_accesa','off') }}"
	      sequence:
		    - service: notify.ros
			  data:
              message: >
                ""Durata ciclo lavatrice: {{ sensor.tempo_ultimo_ciclo_lavatrice }} , consumo { {{ states(sensor.lavatrice_energy) | float }} - {{ input_number.consumo_lavatrice }} } "
```

mi sa che ho inventato un po' di sintassi

**Reply by xyzmauro** [reply]
Direi di sì,un po’ inventata 😅
Guarda negli esempi di automazione, il 3º usa il service input_number.set_value
https://www.home-assistant.io/integrations/input_number#automation-examples

Il template per il calcolo testalo in strumenti sviluppatori che anche li c’è qualche parentesi graffa di troppo 😉

**Comment by rowiz** [comment]
Grande @xyzmauro, questa mi sembra andar bene (nel senso che almen non ho errori di sintassi)

```
- alias: "statistiche ultimo fine lavatrice"
  id: "statistiche_ultimo_ciclo_lavatrice"
  trigger:
   - platform: state
     entity_id: binary_sensor.lavatrice_accesa
  action:
    - choose:
        - alias: "Notifica Lavatrice Accesa"
          conditions:
            - condition: state
              entity_id: binary_sensor.lavatrice_accesa
              state:  "{{ is_state('binary_sensor.asciugatrice_accesa','on') }}"
          sequence:
            - service: notify.ros
              data:
                message: >
                  "Lavatrice partita"
            - service: input_number.set_value
              target:
              entity_id: input_number.consumo_lavatrice
              data:
              value: "{{states('sensor.lavatrice_energy') | float (default=0.0)}}"
        - alias: "Notifica Ciclo Finito"
          conditions:
            - condition: state
              entity_id: binary_sensor.lavatrice_accesa
              state:  "{{ is_state('binary_sensor.asciugatrice_accesa','off') }}"
          sequence:
            - service: notify.ros
              data:
                message: >
                  {% set differenza = states('sensor.lavatrice_energy') | float - states('input_number.consumo_lavatrice') | float %} "Durata ciclo lavatrice
```

dalle verifiche fatte sui developer tools mi sembra valorizzare tutto, ricevo qualche warning all'avvio di HA che non capisco ma ho imparato a convivere con i miei dubbi :D

**Comment by rowiz** [comment]
Riuppo la questione, l’automazione mi funziona a metà; quando infatti entra nel secondo punto del choose (ossia quando la lavatrice finisce il ciclo) non accade niente e il debug automazione mi mostra questo:
`Error: Error rendering data template: UndefinedError: 'sensor' is undefined`

ma di quale sensor parla?!?

**Reply by xyzmauro** [reply]
Nel 2º message in effetti usi un set che poi non si capisce a cosa serva,dovrebbe essere solo
{{ states('sensor.lavatrice_energy') | float - states('input_number.consumo_lavatrice') | float }}

**Reply by xyzmauro** [reply]
A meno che poi mancasse un pezzo di codice…

**Reply by rowiz** [reply]
si mancava un pezzo, ho scasinato col copincolla:

`service: notify.ros
data:
  message: >
    {% set differenzalava = states('sensor.lavatrice_energy') | float -
    states('input_number.consumo_lavatrice') | float %} "Durata ciclo lavatrice:
    {{ sensor.tempo_ultimo_ciclo_lavatrice }} , consumo {{ differenzalava }}
    kwh"`

avevo pensato di usare una variabile d'appoggio, c'avevo giocato in fase di debug e me la sono tenuta 😄

**Reply by xyzmauro** [reply]
Azzardo un’ipotesi…siccome il binary_sensor.lavatrice_accesa lo basi sul valore di potenza superiore/inferiore a 1.9 quando scatta ad off in realtà la lavatrice non è ancora finita e non ti valorizza ancora il tempo dell’ultimo ciclo (verifica mentre il ciclo è in corso che valore ha)
Prova a togliere quella parte di messaggio e vedi se esce ancora l’errore

**Reply by rowiz** [reply]
Ho capito qual è l'errore, ed ha ragione lui.
Il problema è effettivamente nel ```sensor.tempo_ultimo_ciclo_lavatrice```, la automazione lo usava in questo modo
```
- alias: "statistiche ultimo fine lavatrice"
  id: "statistiche_ultimo_ciclo_lavatrice"
  trigger:
   - platform: state
     entity_id: sensor.tempo_ultimo_ciclo_lavatrice
  condition: "{{ not is_state('binary_sensor.lavatrice_accesa','on') }}"
  action:
    - service: notify.ros
      data:
        message: >
          "Durata ciclo lavatrice: {{ trigger.from_state.attributes.value }}"
```
ora invece lo vado a referenziare come valore  che però non setto mai.
Ora penso come sistemarlo
