### DISCUSSION TITLE
Automazioni if/then/else

### DISCUSSION THREAD

**Discussion by calcioscacchi** [indomus/forum#1596] [HUB: Home Assistant]
Ciao a tutti!

HO integrato con successo un deviatore vimar a zigbee2mqtt, ora vorrei integrare un telecomando tradfri ikea (il 5 tasti) per accendere e spegnere la luce.

Potrei sicuramente fare 2 automazioni, entrambe si attivano quando premo il tasto e in base allo stato del deviatore, accendono o spengono la luce. 
Ma siccome lo trovo poco versatile e ho voglia di imparare... se volessi creare un'unica automazione di tipo if/then/else (struttura nota a vari codici di programmazione: C, VBA...) in HA, come potrei fare?

Qualcosa del tipo: 
```
if deviatore=on then deviatore = off
else deviatore = on
```

il mio dubbio, guardando dentro a automation.yaml e studiando una automazione che ho creato, è che non posso creare una struttura fatta così:

```
-condition1
   -action1
-condition2
  -action2
```

Per completezza, questo è il codice dell'automazione costruita via HA core che prevede che, alla pressione del tasto centrale toggle, se le luci sono spente, accende le luci:

```
	- id: '1648296774740'
  alias: gestione luce bagno
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 762c04eec87724332811cee444a0e48a
    type: action
    subtype: toggle
    discovery_id: 0x588e81fffe0be999 action_toggle
  condition:
  - condition: device
    type: is_off
    device_id: 0aaff95053b11210959404527cd269e2
    entity_id: switch.luce_bagno_matrimoniale
    domain: switch
  action:
  - service: script.accendi_bagno_matrimoniale
    data: {}
  mode: single
```
mi date una dritta? :)
Grazie

**Comment by Scialla** [comment]
si che puoi  crearla, guardati la choose nella action, puoi dare diverse condizioni e relative action

Impara a fare le automazioni autonomamente e non tramite GUI, è molto più facile e comprensibile

**Reply by calcioscacchi** [reply]
eh si, tramite codice è sempre più versatile. 
Per il momento uso la GUi come "guida", ma spero di abbandonarla presto. Al momento, sono nella fase più difficile, quella dove devi imparare XD.

Una volta digerito il codice e le sue entità, spero che la strada sia in discesa.

**Reply by calcioscacchi** [reply]
@Scialla grazie della dritta, mi sono documentato un po' e ho capito che non è proprio come pensavo: praticamente il blocco è costruito da trigger e action, ma dentro l'action, inserisco le condizioni in quanto il loro controllo è parte integrante dell'action dell'automazione. 

Comincio a capire perchè il mio codice, scritto sulla base di uno trovato in rete, non mi faceva partire nemmeno HA XD.

**Comment by calcioscacchi** [comment]
Ho studiato un po', ma non riesco a farlo girare. Sento che sono sulla buona strada. Per comodità, vi posto il codice completo del'automation.yaml (fatto solo da automazioni create via GUI, tranne l'ultima) e l'automazione che non riesco a far girare:

```
automation:
- id: '1634679979119'
  alias: pompa di calore mattina Andrea
  description: Accende la pompa di calore ogni mattina per Andrea
  trigger:
  - platform: time
    at: 05:00
    id: Accensi_pompa_di_calore_notte_tempo
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: script.accendi_condizionatore
  - delay:
      hours: 1
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: script.spegni_condizionatore
  mode: single
- id: '1634763432150'
  alias: pompa di calore mattina patrizia
  description: Accende la pompa di calore ogni mattina per Patrizia
  trigger:
  - platform: time
    at: 08:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - thu
    - fri
  action:
  - service: script.accendi_condizionatore
  - delay:
      hours: 0
      minutes: 40
      seconds: 0
      milliseconds: 0
  - service: script.spegni_condizionatore
  mode: single
- id: '1638038899377'
  alias: Preriscaldamento Soggiorno
  description: ''
  trigger:
  - platform: time
    at: '18:15'
  condition:
  - type: is_temperature
    condition: device
    device_id: 60220210b023f6d9184cf748d4e4aab8
    entity_id: sensor.reparto_giorno_temperature
    domain: sensor
    below: 18
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: script.accendi_condizionatore
  - service: notify.mobile_app_sne_lx1
    data:
      message: Attivato preriscaldamento in soggiorno
      title: Preriscaldamento Soggiorno
  - service: notify.mobile_app_huawei_patrizia
    data:
      message: Attivato preriscaldamento in soggiorno
      title: Preriscaldamento Soggiorno
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: script.spegni_condizionatore
  - service: notify.mobile_app_sne_lx1
    data:
      message: ultimato preriscaldamento in soggiorno
      title: preriscaldamento spento
  - service: notify.mobile_app_huawei_patrizia
    data:
      message: ultimato preriscaldamento in soggiorno
      title: preriscaldamento spento
  mode: single
- id: '1638270204068'
  alias: Preriscaldamento reparto Notte
  description: ''
  trigger:
  - platform: time
    at: '21:15'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: script.accendi_pompa_di_calore
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: script.spegni_condizionatore_reparto_notte
  mode: single
- id: '1644772539248'
  alias: Accensione Led TV
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 5558cdae63b5fc77acb4e4dae1badb76
    entity_id: switch.tv_soggiorno
    domain: switch
  condition: []
  action:
  - type: turn_on
    device_id: 67399a082461767320f9b9d66293eb37
    entity_id: light.led_tv
    domain: light
  mode: single
- id: '1644772617326'
  alias: Spegnimento led tv
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 5558cdae63b5fc77acb4e4dae1badb76
    entity_id: switch.tv_soggiorno
    domain: switch
  condition: []
  action:
  - type: turn_off
    device_id: 67399a082461767320f9b9d66293eb37
    entity_id: light.led_tv
    domain: light
  mode: single
- id: '1648296774740'
  alias: Accendi luce bagno
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 762c04eec87724332811cee444a0e48a
    type: action
    subtype: toggle
    discovery_id: 0x588e81fffe0be999 action_toggle
  condition:
  - condition: device
    type: is_off
    device_id: 0aaff95053b11210959404527cd269e2
    entity_id: switch.luce_bagno_matrimoniale
    domain: switch
  action:
  - service: script.accendi_bagno_matrimoniale
    data: {}
  mode: single
- id: '1648373791879'
  alias: Spegni luce bagno
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 762c04eec87724332811cee444a0e48a
    type: action
    subtype: toggle
    discovery_id: 0x588e81fffe0be999 action_toggle
  condition:
  - condition: device
    type: is_on
    device_id: 0aaff95053b11210959404527cd269e2
    entity_id: switch.luce_bagno_matrimoniale
    domain: switch
  action:
  - service: script.spegni_bagno_matrimoniale
    data: {}
  mode: single


#GESTIONE LUCI BAGNO
- alias: "Gestione luce bagno matrimoniale"
  description: "Gestione della luce"
  trigger:
    - platform: device
      domain: mqtt
      type: action
      subtype: toggle
      device_id: 762c04eec87724332811cee444a0e48a
  action:
     - choose:
       - conditions:
           - condition: device
             device_id: 0aaff95053b11210959404527cd269e2   
             entity_id: switch.luce_bagno_matrimoniale
             type: is_off
         sequence:
           - service: script.accendi_bagno_matrimoniale
       default:
         - service: script.spegni_bagno_matrimoniale

```


il codice dell'automazione, che vi spiego:

Quando premo il bottone centrale del remote IKEA, l'automazione controlla se la luce (switch.luce_bagno_matrimoniale) è spento. Se lo è, parte lo script di accensione. Se non lo è (default) parte lo script di spegnimento. Ho preso spunto dall'automazione della GUI e ho cercato di modificarla secondo la logica del choose.
```
#GESTIONE LUCI BAGNO
- alias: "Gestione luce bagno matrimoniale"
  description: "Gestione della luce"
  trigger:
    - platform: device
      domain: mqtt
      type: action
      subtype: toggle
      device_id: 762c04eec87724332811cee444a0e48a
  action:
     - choose:
       - conditions:
           - condition: device
             device_id: 0aaff95053b11210959404527cd269e2         
             entity_id: switch.luce_bagno_matrimoniale
             type: is_off
         sequence:
           - service: script.accendi_bagno_matrimoniale
       default:
         - service: script.spegni_bagno_matrimoniale
```
L?errore che home asisstant mi da è il seguente:

`Invalid config for [automation]: required key not provided @ data['action'][0]['choose'][0]['conditions'][0]['device_id']. Got None required key not provided @ data['action'][0]['choose'][0]['conditions'][0]['domain']. Got None. (See ?, line ?).`

Qualche aiuto? Ho provato a modificare il codice a sentimento una decina di volte ma non riesco a trovare l'errore.
