### DISCUSSION TITLE
Problema PING

### DISCUSSION THREAD

**Discussion by millenniumy2k** [indomus/forum#1600] [HUB: Home Assistant]
Ciao, da quando ho aggiornato HA (docker su Windows), non mi funzionano più alcuni automatismi che usavo per notificare l'accensione e spegnimento ti stampante, tv, ecc..:

```
binary_sensor:
 - platform: ping
   host: 192.168.1.15
   name: stampante
   count: 2
   scan_interval: 100
 - platform: ping
   host: 192.168.1.10
   name: server
   count: 2
   scan_interval: 100
 - platform: ping
   host: 192.168.1.5
   name: tvsalotto
   count: 2
   scan_interval: 100

device_tracker:
  - platform: ping
    hosts: 
      stampante: 192.168.1.15
      tvsalotto: 192.168.1.5
      server: 192.168.1.10
```
hanno sempre funzionato, da un po non funzionano più, ho provato a ricrearli, ma nulla... sbaglio qualcosa io?
