### DISCUSSION TITLE
Abilitazione API: 401: Unauthorized

### DISCUSSION THREAD

**Discussion by LuigiPzz** [indomus/forum#1602] [HUB: Home Assistant]
Salve a tutti,

sono su hassio, l'instanza è su da perlomendo 1 anno. Sto provado da diverso tempo ad abilitare le api, ma qualsiasi tentativo abbia provato il risultato è sempre il 401.

premetto che sto provado ad accedervi da https://XXXXXXXXXXXX:8123/api/ e che risulta raggiungibile dall'esterno.

Uno dei 1000 tentativi 
```
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  
api:
  homeassistant_api: true
```
