### DISCUSSION TITLE
Automazione con trigger >=

### DISCUSSION THREAD

**Discussion by millenniumy2k** [indomus/forum#1604] [HUB: Home Assistant]
Ho un NETATMO anemometro, e vorrei un automazione che mi avvisi se il vento supera i 6 km/h.

in questo modo:

```
trigger:
  - platform: state
    entity_id: sensor.netatmo_stazione_meteo_anemometro_wind_strength
    to: '6'
```

non mi avvisa mai, a meno che non sia esattamente 6...

**Comment by indomus** [comment]
```
trigger:
  - platform: numeric_state
    entity_id: sensor.netatmo_stazione_meteo_anemometro_wind_strength
    above: '6'
```
