### DISCUSSION TITLE
Utilizzo di wait.trigger in Automazione

### DISCUSSION THREAD

**Discussion by NdR91** [indomus/forum#1605] [HUB: Home Assistant]
Ciao a tutti,

Sto cercando di creare un'automazione. I passaggi, in sostanza, devono essere i seguenti:

Trigger: gruppo "tutti" fuori casa da 15 minuti.
Azione:
- Invio messaggio su telegram, avente dei `inline_keyboard`;
- Wait for Trigger, con timeout, in attesa di un evento `telegram_callback` avente come `data`  un `command` che per semplificare qui ho chiamato `/bot_test`
- Se il trigger si avvera, esegue un azione
- Se va in timeout, ne esegue un altra.

```yaml
automation:
  - id: 7a9ca822-4429-4515-b7d7-5d2f1ef03922
    alias: Test
    trigger:
      - platform: state
        entity_id: group.tutti
        to: 'not_home'
        for: '00:15:00'
    action:
      - service: telegram_bot.send_message
        data:
          target: !secret chat_id_andre
          disable_notification: false
          message: |
            ...
            - '🧹 Test:/bot_test'
      - wait_for_trigger: 
          - platform: event
            event_type: telegram_callback
            event_data: {}
        timeout: '00:00:05' # TODO: da aumentare
      - choose:
          - conditions: '{{ wait.trigger.event.data.command == "/bot_test" }}'
            sequence: 
              - service: telegram_bot.send_message
                data:
                  target: !secret chat_id_andre
                  disable_notification: false
                  message: |
                    ...
        default:
        - service: telegram_bot.edit_message
          data: 
            message_id: "{{ trigger.event.data.message.message_id }}" 
            chat_id: !secret chat_id_andre 
            disable_notification: true
            message: |
              ...

```
<details><summary>Estratto dell'evento</summary>

```
{
    "event_type": "telegram_callback",
    "data": {
        "user_id": xxxxx,
        "from_first": "xxxx",
        "from_last": "xxxxxx",
        "chat_id": xxxxxxx,
        "data": "/bot_test",
        "command": "/bot_test",
        "args": [],
        "message": {
            "message_id": 6108,
            "date": 1648639271,
            ...
```
</details>
Purtroppo, però, ricevo questo errore:

`Error while executing automation automation.ecovacs_n8_pulizia: Error rendering data template: UndefinedError: 'dict object' has no attribute 'event'`

Qualcuno potrebbe darmi una mano?
Tks!

**Comment by maxcanna** [comment]
Stai accedendo a `wait.trigger.event` ma, come da doc, `wait` ha il campo `trigger` solo se il trigger si è verificato. Se va in timeout no

> Exists only after wait_for_trigger. Contains information about which trigger fired. (See [Available-Trigger-Data](https://www.home-assistant.io/docs/automation/templating/#available-trigger-data).) Will be none if no trigger happened before timeout expired

**Reply by NdR91** [reply]
Mhmm, si avevo visto.

Però appunto l'automazione dovrebbe prendere la choose nel caso in cui appunto il trigger si avveri (ovvero con il telegram_callback), altrimenti dovrebbe prendere il default.

Sbaglio?

**Reply by maxcanna** [reply]
Non può essere valutata la condizione della choose per via di un errore runtime. Devi usare l'attributo `completed`

**Reply by xyzmauro** [reply]
Comunque se non rispondi col callback non avrai il message_id e non riuscirai ad editare il messaggio mi sa…

**Reply by NdR91** [reply]
Ah, mi pareva di aver letto che wait.completed si potesse usare solo in caso si usi il wait_template...

**Comment by NdR91** [comment]
Aggiornamento,

sono riuscito a far funzionare l'automazione, ma come diceva @xyzmauro , senza callback non riesco a modificare il messaggio originale.
C'è un modo di "portarsi" il `message_id` dal primo messaggio?

```yaml
automation:
  - id: 7a9ca822-4429-4515-b7d7-5d2f1ef03922
    alias: Ecovacs N8 - Pulizia
    trigger:
      - platform: state
        entity_id: group.tutti
        to: 'not_home'
        for: '00:15:00'
    action:
      - service: telegram_bot.send_message
        data:
          target: !secret chat_id_andre
          disable_notification: false
          message: |
            *🧹 Pulizia 🧹*
            
            Siete fuori da un pò, tra poco inizio a pulire...
          inline_keyboard:
            - '🧹 Pulizia:/bot_pulizia, ❌ Non Pulire:/bot_no_pulizia'
            - '🤖 Avvia Bot:/bot'
      - wait_for_trigger: 
          - platform: event
            event_type: telegram_callback
            event_data:
              data: /bot_no_pulizia
            id: no_pulizia
        timeout: '00:00:05' # TODO: da aumentare
      - choose:
          - conditions: '{{ wait.trigger.id == "no_pulizia" }}'
            sequence: 
              - service: telegram_bot.send_message
                data:
                  target: !secret chat_id_andre
                  disable_notification: false
                  message: |
                    Ok, non avvio N8
        default:
        - service: telegram_bot.edit_message
          data: 
            message_id: "{{ trigger.event.data.message.message_id }}"  # <--- 
            chat_id: !secret chat_id_andre 
            disable_notification: true
            message: |
              *🧹 Pulizia 🧹*
              
              Siete fuori da un pò, inizio a pulire...
            inline_keyboard:
              - '🧹 Pulizia:/bot_pulizia'
              - '🤖 Avvia Bot:/bot'
```
