### DISCUSSION TITLE
cambio immagine dinamico su card mappa

### DISCUSSION THREAD

**Discussion by jard159** [indomus/forum#1606] [HUB: Home Assistant]
Salve a tutti,
secondo vuoi si potrebbe utilizzare la funzionalità "template" per cambiare l'icona/foto all'interno della card map?

Attualmente ho una immagine personalizzata settata in `know_devices.yaml` in questo modo:

```
fra:
  name: fra
  mac:
  icon:
  picture: /local/pin-gps.png
  track: true
```

e nella card mappa mi richiamo l'entità `device_tracker.fra`

Quello che vorrei realizzare è una roba del genere:
if state == home > picture1; if state == not_home > picture2

Grazie mille
