### DISCUSSION TITLE
Errore riguardo Entity_ID

### DISCUSSION THREAD

**Discussion by Zagor4** [indomus/forum#1625] [HUB: Home Assistant]
Ciao a tutti,
Random mi trovo questo tipo di errore nel log di HA:  (questo script è un esempio ma succede anche in altri script).

TV_Sala_Mute: Error executing script. Invalid data for call_service at pos 1: Entity ID is an invalid entity ID for dictionary value @ data['entity_id']

Però le entità non sono state modificate, il codice è il medesimo e lo script funziona correttamente e se richiamo la funzione successivamente all'errore, l'errore non si ripresenta... 
Cosa sto sbagliando ?

Di seguito lo script:

```
  tv_sala_mute:
    alias: TV_Sala_Mute
    icon: mdi:television
    sequence:
      - service: homeassistant.turn_on
        data_template:
          entity_id: >-
            {%- set dispositivo = states("sensor.last_alexa")-%}
            {%- if dispositivo == "media_player.echo_sala" -%}
              script.tv_mute
            {%- elif dispositivo == "media_player.echo_camera" -%}
              script.tv_mute_camera
            {%- endif -%}

  tv_mute:
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.rm_pro_sala_remote
        data:
          command: b64:JgDYAAABJ5QUERM3FBETNxI4EzcSExI3ExITEhMSExIS
  tv_mute_camera:
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.rm_mini_camera_remote
        data:
          command: b64:JgBGAJSUEjcSNxI4ERMSExITEhMRExI4ETgSNxITEhMRExITEhMROBI4
```
Grazie mille a chi potrà darmi qualche dritta

**Comment by Zagor4** [comment]
Risolto modificando lo script:

```
  tv_sala_mute:
    alias: TV_Sala_Mute
    icon: mdi:television
    sequence:
      choose:
        - conditions:
            - condition: state
              entity_id: sensor.last_alexa
              state: "media_player.echo_sala"
          sequence:
            - service: remote.send_command
              target:
                entity_id: remote.rm_pro_sala_remote
              data:
                command: b64:JgDYAAABJ5QUERM3FBETNxI4EzcSExI3ExITEhMSExISExI4EhMSN
        - conditions:
            - condition: state
              entity_id: sensor.last_alexa
              state: "media_player.echo_camera"
          sequence:
            - service: remote.send_command
              target:
                entity_id: remote.rm_mini_camera_remote
              data:
                command: b64:JgBGAJSUEjcSNxI4ERMSExITEhMRExI4ETgSNxIT
      default:
        delay: 1
    mode: single

```
