### DISCUSSION TITLE
Limitare esecuzione di una automazione ad uno specifico utente

### DISCUSSION THREAD

**Discussion by teleoltre** [indomus/forum#1630] [HUB: Home Assistant]
Buongiorno a tutti,
ho una automazione che si attiva alla scansione di un tag NFC.

Avrei la necessità di inserire una condizione per cui l'automazione venga eseguita solo alla scansione del tag di uno specifico utente.

Ho letto in giro che tramite la variabile "trigger.event.context.userid " questo sia possibile.
Ma non avendo nozioni in merito, non sono in grado di farlo.

Qualcuno mi può aiutare ?
grazie

**Comment by snakuzzo** [comment]
Guarda questo esempio (provato ora e funziona perfettamente)...

```yaml
input_boolean:

  prova:

automation:

- alias: Prova User ID
  trigger:
  - platform: state
    entity_id: input_boolean.prova
  condition:
  - "{{ trigger.to_state.context.user_id == '<tuo id utente>' }}"
  action:
  - service: persistent_notification.create
    data:
      message: "CIAO"
```

**Comment by teleoltre** [comment]
Grazie mille per il codice.

Il codice di esempio che mi hai fornito funziona effettivamente perfettamente.
Ma appeno modifico il trigger con il seguente codice :
```
- alias: Prova User ID
  trigger:
  - platform: tag
    tag_id: <id del tag da scannerizzare>
  condition:
  - "{{ trigger.to_state.context.user_id == '<tuo id utente>' }}"
  action:
  - service: persistent_notification.create
    data:
      message: "CIAO"
```
Non va più.... Nel senso che l'automazione non viene più eseguita, qualunque sia l'ID utente a farlo...
Logicamente se elimino la condizione, l'automazione funziona.

Come è possibile sta cosa ?

**Reply by snakuzzo** [reply]
ma tu sei sicuro che nel trigger sia presente l'id utente ?
E' quello a cui accennavo questa mattina in chat...non è detto che il trigger abbia l'utente.
Fatti stampare il `context` completo nella action...

```yaml
  action:
  - service: persistent_notification.create
    data:
      message: "{{ trigger.to_state.context }}"
```

**Reply by teleoltre** [reply]
Mi sa che è proprio questo il problema...

Se uso questo codice 
```
- alias: Prova User ID
  trigger:
  - platform: state
    entity_id: input_boolean.prova
  action:
  - service: persistent_notification.create
    data:
      message: "{{ trigger.to_state.context }}"
```
Mi scrive il seguente messaggio
```
Context(user_id='1c2d50573c5744d8808e05c974586ec1', parent_id=None, id='b8e392e669d7116f9f499e2dda069f09')
```

Appena sostiuisco il trigger con
```
- alias: Prova User ID 2
  trigger:
  - platform: tag
    tag_id: xxxxxxxxx
  action:
  - service: persistent_notification.create
    data:
      message: "{{ trigger.to_state.context }}"

```
Scannerizzando il tag non mi scrive nessun messaggio...

A questo punto il trigger tag non ha l'utente ?
In questo caso come si risolve ?

**Reply by snakuzzo** [reply]
non c'è l'id utente...ed è anche giusto così. Perché utente e tag c'entrano come le alici con la nutella

**Reply by snakuzzo** [reply]
non devi risolvere nulla...devi semplicemente trovare un altro modo di fare quello che vuoi fare

**Reply by teleoltre** [reply]
Trovato ! Grazie ad un altro utente su facebook

```
alias: Test Tag Automazione
description: ''
trigger:
  - platform: event
    event_type: tag_scanned
    context:
      user_id:
        - 1e16e1xxxxxxxxxxxx4fff86
    event_data:
      tag_id: 99822f85-xxxxxxxxxxxxxx
condition: []
action:
  - service: notify.gianvi_telegram
    data:
      message: Tag attivato
mode: single
```
