### DISCUSSION TITLE
Errore in automazione per collegare 2 Dimmer Sonoff.

### DISCUSSION THREAD

**Discussion by Zagor4** [indomus/forum#1631] [HUB: Home Assistant]
Ciao a tutti,
Considerando questo codice di automazione a volte mi trovo questo genere di errore. 
Trattasi di 2 Dimmer King Art (Placche a muro fisiche) che funzionano con Ewelink, purtroppo questi 2 dimmer non supportano la funzionalità LAN e quindi sono gli unici 2 dispositivi Sonoff (o simili) ad essere integrati in HA ancora in cloud per mezzo di sonoff lan.

```
  - id: "1639422593789"
    alias: Dimmer2 modifica Dimmer1
    description: ""
    trigger:
      - platform: state
        entity_id: light.sonoff_10004828c3
        attribute: brightness
    condition: []
    action:
      - service: light.turn_on
        data:
          brightness: "{{ state_attr('light.sonoff_10004828c3', 'brightness')}}"
        target:
          entity_id: light.sonoff_1000482ac1
    mode: restart

```

Dimmer2 modifica Dimmer1: Error executing script. Invalid data for call_service at pos 1: expected int for dictionary value @ data['brightness']

Nonostante l'errore l'operatività è Ok... quindi i 2 dimmer sono collegati e le 2 luci variano all'unisono.

Grazie mille

**Comment by snakuzzo** [comment]
Come scritto in chat, il problema dovrebbe essere legato al fatto che gli passi un valore NON numerico.
Quando recuperi la luminosità usando il template, devi sapere che i template restituiscono SEMPRE una stringa e non un numero. Quindi dovresti fare il cast...

Prova così...

```yaml
  - id: "1639422593789"
    alias: Dimmer2 modifica Dimmer1
    description: ""
    trigger:
      - platform: state
        entity_id: light.sonoff_10004828c3
        attribute: brightness
    condition: []
    action:
      - service: light.turn_on
        data:
          brightness: "{{ state_attr('light.sonoff_10004828c3', 'brightness') | int }}"
        target:
          entity_id: light.sonoff_1000482ac1
    mode: restart
```
