### DISCUSSION TITLE
Utilizzo custom components nella dashboard

### DISCUSSION THREAD

**Discussion by fenestren** [indomus/forum#1632] [GENERALE - Discussioni generiche]
Ciao a tutti,
vorrei iniziare a costruirmi una dashboard usando componenti custom come la UI Minimalist o la Room-Cards.
Purtroppo, nonostante abbia seguito le guide sui wiki dei rispettivi cutom components la mia dashboard non li riconosce.
Sicuramente è un errore di impostazione da qualche parte che però non riesco a trovare.
La struttura delle mie cartelle è quella in foto [https://imgur.com/GmNtj07](url)
Inoltre ho notato che non funziona l'autocompletamento delle entity modificando i file .yaml (ad esempio quello nella foto del link che si riferisce ad un tentativo di creazione di una button card come quella nella foto qui [https://ui-lovelace-minimalist.github.io/UI/assets/img/ulm_cards/room-card.png](url) ).
Come deve essere la dichiarazione all'nterno del file .yaml della mia dashboard affinché vengano riconosciute le mie entity in automatico durante la digitazione e, soprattutto, affinché io possa usare i custom components UI Minimalist e Room-Card, per favore?

Posto il codice del file Cameretta.yaml per cui vorrei creare una Button-Card di tipo Room-Card.
```
- title: "Camera"
  theme: "minimalist-desktop"
  background: "var(--background-image)"

  path: Camera
  icon: "mdi:bed"
  cards:
    - type: "vertical-stack"
      cards:
        type: "custom:button-card"
        template:
          - card_room
          - red_no_state
        name: Bathroom
        entity:
        icon: mdi:shower-head
        tap_action:
          action: navigate
          navigation_path: "/ui-lovelace-minimalist/bathroom"
        variables:
          label_use_temperature: false
          label_use_brightness: true
          entity_1:
            entity_id: 
            templates:
              - yellow_on
            tap_action:
              action: toggle
```

Questo il mio configuration.yaml

```
# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  # packages: !include_dir_named packages
default_config:

frontend:
  themes: !include_dir_merge_named themes

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

browser_mod:

zone:
  # Questo sovrascrive l'eventuale entità zone.home già esistente, per renderla più accurata
  - name: Home
    latitude: xxxxxxx
    longitude: xxxxxx
    radius: 10
    icon: mdi:home-heart

# Text to speech

tts:
  - platform: google_translate
    base_url: https://casamia.duckdns.org:8123
    service_name: google_translate_say
    language: "it"

# group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

wake_on_lan:

# Telegram

telegram_bot:
  - platform: polling
    api_key: "xxxxxxxxxxxxxxxxxx"
    allowed_chat_ids:
      - "yyyyyyyy"

notify:
  - name: luca
    platform: telegram
    chat_id: "yyyyyyy"

  # Open Hardware Monitor
sensor:
  - platform: openhardwaremonitor
    host: 192.168.xxx.xxx


  # Sensors from systemmonitor

  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
      - type: disk_free
        arg: /
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: memory_free
      - type: memory_use_percent
      - type: memory_use
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
      - type: network_in
        arg: eno1
      - type: network_out
        arg: eno1
      - type: load_15m



  # Sensore Scadenza Certificato DuckDNS

  - platform: template
    sensors:
      certificate_expiry:
        friendly_name: "Scadenza certificato"
        value_template: "{{ (( as_timestamp(states('sensor.cert_expiry_timestamp_casamia_duckdns_org_8123')) | int - as_timestamp(now()) | int ) /60/60/24 ) | int }}"
        unit_of_measurement: "Giorni"
        icon_template: mdi:certificate
        


  # Integrazione Google Mini
google_assistant:
  project_id: zzzzzzzzzz
  service_account: !include zzzzzzzz.json
  exposed_domains:
    - light
    - switch
    - climate
    - cover
    - sensor
    - binary sensors
    - camera
    - group
    - input boolean
    - media_player
    - scene
    - script
    - vacuum

  # Example configuration.yaml entry
webostv:
  host: 192.168.zzz.zzz
  name: TV Cucina
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: 
  customize:
    sources:
      - LiveTV
      - Amazon Prime Video
      - youtube
      - DAZN
      - netflix
      - plex
      - Spotify

media_player:

simpleicons:
  # HTC Flipclock with Weather card

  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - date_time_utc
      - date_time_iso
      - time_date
      - time_utc
      - beat

# Alarm Panel

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    arming_time: 30
    delay_time: 0
    trigger_time: 0
    disarmed:
      trigger_time: 0

```
Grazie mille.
