### DISCUSSION TITLE
shelly2.5+mqtt in HA

### DISCUSSION THREAD

**Discussion by p-marco** [indomus/forum#1636] [HUB: Home Assistant]
Ciao a tutti,
Mi trovo ad avere qualche problema nel configurare Shelly 2.5 in Home Assistant attraverso MQTT.
Nonostante abbia seguito il tutorial, il problema è che gli interruttori della dashboard non presentano funzioni - forse per via dell'errore per cui quelle entità "non hanno un ID univoco". 
Qualcuno saprebbe aiutarmi?
Grazie

**Comment by snakuzzo** [comment]
Se non indichi di preciso configurazione, errori, etc ... uno come fa ad aiutarti ?

**Reply by p-marco** [reply]
Grazie,
Questa è la parte di configuration.yaml relativa allo shelly:
```
switch:
  - platform: mqtt
    name: "office10"
    icon: mdi:power-socket-eu
    state_topic: "shellies/shelly_Office1/relay/0"
    command_topic: "shellies/shelly_Office1/relay/0/command"
    availability_topic: "shellies/shelly_Office1/online"
    optimistic: false
    payload_on: "on"
    payload_off: "off"
    payload_available: "true"
    payload_not_available: "false"
    retain: false
    qos: 1
  - platform: mqtt
    name: "office11"
    icon: mdi:power-socket-eu
    state_topic: "shellies/shelly_Office1/relay/1"
    command_topic: "shellies/shelly_Office1/relay/1/command"
    availability_topic: "shellies/shelly_Office1/online"
    optimistic: false
    payload_on: "on"
    payload_off: "off"
    payload_available: "true"
    payload_not_available: "false"
    retain: false
    qos: 1
```
Nella pagina web dello Shelly ho configurato:
```
Server: {IP di Home assistant}:1883
MQTT Prefix: shelly_Office1
```
Nella schermata delle entità in HA gli switch sono unavailable:
```
This entity ('switch.office10') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.
```

Grazie in anticipo
