### DISCUSSION TITLE
Sun

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#1638] [HUB: Home Assistant]
A mezzanotte e qualche minuto è andata via la corrente per alcuni secondi e HA è impazzito.
```
- id: azioni_mattina
  alias: Mattina alba
  description: Apre le tapparelle zona giorno
  trigger:
  - platform: sun
    event: sunrise
    offset: '- 00:15:00'
  action:
  - service: cover.open_cover
  ```
L'automazione di cui sopra ha aperto le tapparelle zona giorno a **mezzanotte e 15 minuti**.
C'è qualcosa di sbagliato nel codice?
Se il codice è corretto, qualcuno ha idea di cosa possa essere successo?
