### DISCUSSION TITLE
aiuto su configurazione sensori ipertrofici

### DISCUSSION THREAD

**Discussion by jard159** [indomus/forum#1643] [HUB: Home Assistant]
ciao a tutti, seguendo [questa guida su indomus.it](https://indomus.it/guide/ridurre-le-scritture-dati-di-sensori-ipertrofici-su-home-assistant/) ho provato a configurare un nuovo sensore per generare un grafico relativo ad un carico 220v (shelly 1pm).

Tuttavia nello storico di HA, anche dopo svariate ore dallo spegnimento del carico, mi ritrovo sempre con l'ultimo valore registrato (ad es. 1500 W) e non 0 come dovrebbe essere.... questo il mio codice:

```
  - platform: filter
    name: "GRAFICO ASSORBIMENTO A/C"
    entity_id: sensor.assorbimento_a_c
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2
      - filter: time_simple_moving_average
        window_size: 00:05
        precision: 2
```
Se ovviamente disabilito questo sensore nel file history.yaml ripristinando quello originale tutto funziona!!!

Qualcuno potrebbe darmi una dritta???
Grazie mille
