### DISCUSSION TITLE
shelly 2.5 integrazione nativa

### DISCUSSION THREAD

**Discussion by willi4m26** [indomus/forum#1647] [HUB: Home Assistant]
buongiorno,
tramite integrazione nativa, come posso sostuire questi comandi "shellies/shellyswitch-12345/roller/0" ecc, ad uno shelly 2.5

```

cover:
  - platform: mqtt
    name: "Tenda da sole"
    state_topic: "shellies/shellyswitch-12345/roller/0"
    command_topic: "shellies/shellyswitch-12345/roller/0/command"
    position_topic: "shellies/shellyswitch-12345/roller/0/pos"
    set_position_topic: "shellies/shellyswitch-12345/roller/0/command/pos"
    qos: 0
    retain: false
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
    position_open: 100
    position_closed: 0
    optimistic: false
    value_template: '{{ value }}'

sensor:
  - platform: mqtt
    state_topic: "shellies/shellyswitch-12345/roller/0/pos"
    name: "Posizione Tenda da sole"

input_number:
  pos_tenda_da_sole:
    name: pos tenda da sole
    min: 0
    max: 100
    step: 1

```

**Comment by snakuzzo** [comment]
Non ho capito la domanda e non ho capito qual è lo scopo.

**Reply by willi4m26** [reply]
ti dico lo scopo,  vorrei creare , per una tapparella, una barra sotto che si aggiorna quando la apro o la chiudo, oppure aprirla o chiuderla direttamente dalla barra

**Reply by snakuzzo** [reply]
e che c'entra questo con la presunta "sostituzione" di alcuni parametri ?
Puoi usare delle custom card per fare quello che dici

![aaa](https://user-images.githubusercontent.com/7205371/164740338-7e5a3ba7-c45c-4644-8ce0-8c6c613ba6df.png)

Qui nello specifico ho usato [slider-entity-row](https://github.com/thomasloven/lovelace-slider-entity-row)

Questo lo YAML della card...

```yaml
entities:
  - entity: cover.matrimoniale
    type: custom:slider-entity-row
  - entity: cover.matrimoniale
    full_row: true
    type: custom:slider-entity-row
show_header_toggle: false
title: slider-entity-row
type: entities
```
