### DISCUSSION TITLE
Automazione riavvio se connessione assente

### DISCUSSION THREAD

**Discussion by davide1295** [indomus/forum#1654] [HUB: Home Assistant]
Ciao a tutti, vorrei creare un'automazione che controlli ogni ora lo stato della connessione ad internet e se questa è assente riavvii home assistant.
Ho creato un nuovo sensore binario:

```
binary_sensor:
 - platform: ping
   host: 8.8.8.8
   count: 2
   scan_interval: 1800
   name: stato_connessione
```

E la relativa automazione:

```
alias: Riavvio connessione assente
description: ''
trigger:
  - platform: time_pattern
    hours: '1'
condition:
  - condition: state
    entity_id: binary_sensor.stato_connessione
    state: 'off'
action:
  - service: homeassistant.restart
    data: {}
mode: single
```
Se effettuo il debug dell'automazione mi compare il messaggio "**_No traces found_**" e non riesco a capire se l'automazione funzionerebbe o meno.
Inoltre, nelle impostazioni del sensore ho questo messaggio "**_Questa entità ("binary_sensor.stato_connessione") non ha un ID univoco, pertanto le sue impostazioni non possono essere gestite dall'interfaccia utente. Vedi [documentazione](https://www.home-assistant.io/faq/unique_id) per maggiori dettagli._**"

Il sensore funziona perfettamente. Come potrei risolvere questi errori?
