### DISCUSSION TITLE
comportamento anomalo automazione spegnere le luci

### DISCUSSION THREAD

**Discussion by willi4m26** [indomus/forum#1656] [HUB: Home Assistant]
ciao ragazzi,
ho questa automazione che spegne le luci del "salone" e di "samuel" e accende quella della cucina.
Quando parte, accende e spegne le luci del salone, anche se sono spente. Come mai? Perchè sono state accese dall'interruttore e non dallo shelly?

```
- id: '1645190631621'
  alias: Ora di cena
  description: spegne tutte le luci e tv , accende cucina
  trigger:
  - platform: device
    domain: mqtt
    device_id: 1f7862271786483cc5f01168415dd896
    type: action
    subtype: 1_double
    discovery_id: 0xa4c138429f95915d action_1_double
  condition: []
  action:
  - type: turn_off
    device_id: eaa451f5cfa9c903836f7b6f46ad63c4
    entity_id: light.salone_luce
    domain: light
  - type: turn_off
    device_id: a910d946f80877f11d2993be065a6151
    entity_id: light.samuel_luce
    domain: light
  - service: media_player.turn_off
    data: {}
    target:
      device_id: 41fbcab99d874cb245a70f060a4c0620
  - type: turn_on
    device_id: e769e23d81be8230023fd87c5ac95e4d
    entity_id: light.cucina_luce
    domain: light
  - type: turn_off
    device_id: 1f0703acc366e3c9ca33a44414496f35
    entity_id: switch.piantana
    domain: switch
  mode: single
```
