### DISCUSSION TITLE
Ottenere valore entità previsioni meteo

### DISCUSSION THREAD

**Discussion by MARIOROSSINI** [indomus/forum#1658] [HUB: Home Assistant]
Buonasera
ho la necessità per regolare l'irrigazione del giardino di ottenere i valori PREVISTI di mm di PIOGGIA e PROBABILITA' di PIOGGIA.
Nella sezione per sviluppatori leggo oggi 24/04 gli attributi sotto dall'entità "weather.openweathermap".
Avrei bisogno di poter creare un automazione condizionata dai valori di forecast "precipitation" e "precipitation_probability" per X giorni successivi.
In pratica l'automazione irrigazione non verrà eseguita se per gli X (variabile) giorni successivi i valori di "precipitation" e "precipitation_probability" saranno superiori ai valori definiti.
Vi ringrazio anticipatamente per i suggerimenti.

```

temperature: 12.4
humidity: 90
pressure: 1007
wind_bearing: 72
wind_speed: 4.32
forecast: 
- datetime: '2022-04-24T21:00:00+00:00'
  precipitation: 0
  precipitation_probability: 0
  pressure: 1006
  wind_speed: 1.28
  wind_bearing: 23
  condition: cloudy
  clouds: 78
  temperature: 11.1
- datetime: '2022-04-25T00:00:00+00:00'
  precipitation: 0
  precipitation_probability: 0
  pressure: 1007
  wind_speed: 1.38
  wind_bearing: 338
  condition: cloudy
  clouds: 61
  temperature: 9.2
- datetime: '2022-04-25T03:00:00+00:00'
  precipitation: 0
  precipitation_probability: 0
  pressure: 1007
  wind_speed: 1.42
  wind_bearing: 2
  condition: cloudy
  clouds: 99
  temperature: 7.3
- datetime: '2022-04-25T06:00:00+00:00'
  precipitation: 0
  precipitation_probability: 0
  pressure: 1008
  wind_speed: 1.01
  wind_bearing: 36
  condition: cloudy
  clouds: 90
  temperature: 9.4
- datetime: '2022-04-25T09:00:00+00:00'
  precipitation: 0
  precipitation_probability: 0
  pressure: 1009
  wind_speed: 2.04
  wind_bearing: 190
  condition: cloudy
  clouds: 74
  temperature: 14.4
- datetime: '2022-04-25T12:00:00+00:00'
  precipitation: 0
  precipitation_probability: 0
  pressure: 1009
  wind_speed: 1.9
  wind_bearing: 167
  condition: cloudy
  clouds: 66
  temperature: 17.2
- datetime: '2022-04-25T15:00:00+00:00'
  precipitation: 0.68
  precipitation_probability: 38
  pressure: 1009
  wind_speed: 2.44
  wind_bearing: 151
  condition: rainy
  clouds: 79
  temperature: 15.6
- datetime: '2022-04-25T18:00:00+00:00'
  precipitation: 1.1
  precipitation_probability: 51
  pressure: 1010
  wind_speed: 1.75
  wind_bearing: 115
  condition: rainy
  clouds: 81
  temperature: 12.8
- datetime: '2022-04-25T21:00:00+00:00'
  precipitation: 0.15
  precipitation_probability: 39
  pressure: 1012
  wind_speed: 2.15
  wind_bearing: 70
  condition: rainy
  clouds: 100
  temperature: 11.6
```
