### DISCUSSION TITLE
[RISOLTO] Riconoscere attivazione via Cloud

### DISCUSSION THREAD

**Discussion by BigMiura** [indomus/forum#1659] [HUB: Home Assistant]
Ciao a tutti,
questa è la prima volta che scrivo nel forum, ho iniziato a conoscere Home Assistant grazie a inDomus.

Vorrei sapere se è possibile discernere se l'attivazione e lo spegnimento di un dispositivo è stata richiesta dal Cloud, per attivare una automazione. Dallo storico del dispositivo vedo che è evidente la scritta "_Spento da Home Assistant Cloud_".

Quello che vorrei fare è una funzionalità automatica della deumidificazione in una stanza in base ai valori di umidità rilevati da un sensore esterno. Ho creato un aiutante binario che si accede alla richiesta dell'attivazione dello script "Deumidificazione auto stanza" e che si spegne con lo script "Spegni condizionatori". Ma dovrei spegnerlo anche se tramite Alexa qualcuno richiede lo spegnimento del condizionatore senza passare dallo script citato prima.

Spero di essere stato chiaro, grazie per l'aiuto,
Fabio.

**Comment by snakuzzo** [comment]
Ciao.
Secondo me potresti evitare quel riconoscimento attivazione da cloud e anche gli script.
Potresti esporre il dispositivo/entità di HA verso Alexa con [haaska](https://indomus.it/guide/integrare-gratuitamente-amazon-echo-alexa-con-home-assistant-via-haaska-e-aws/) e poi gestire la deumidificazione con una sola automazione come indicato [QUI](https://indomus.it/progetti/muffa-e-domotica-come-mitigare-il-problema-tramite-home-assistant/)

**Comment by BigMiura** [comment]
Ciao snakuzzo, grazie per il consiglio, ma purtroppo non vorrei utilizzare una automatizzazione "assoluta" come quella del link.
Gli script li ho creati per una configurazione veloce dei condizionatori. In più vorrei che in una stanza l'umidità non scendesse troppo, quindi l'informazione richiesta mi consentirebbe di monitorare i livelli di umidità solo quando richiesto effettivamente.

**Comment by BigMiura** [comment]
Ciao a tutti,
sono riuscito a risolvere il problema con un po' di ricerca sul forum principale, [https://community.home-assistant.io/t/solved-detect-which-ha-user-toggled-entity-state/192615/4](url).
In pratica ho creato una automazione che mi cambia lo stato dell'aiutante binario quando il condizionatore viene spento via Cloud o dai 2 utenti. Il sensore binario "stato_cond_cuci" è una semplificazione delle modalità del condizionatore.

```yaml
- alias: Cond Cucina spento via Cloud
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.stato_cond_cuci
    to: 'off'
  condition:
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ trigger.to_state.context.user_id == ''aa883.....acd07'' }}' # By Cloud
      - condition: template
        value_template: '{{ trigger.to_state.context.user_id == ''c0784.....7a608'' }}' # By X
      - condition: template
        value_template: '{{ trigger.to_state.context.user_id == ''9e8a7.....5b9e5'' }}' # By Y
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.cucina_cucina
```
