### DISCUSSION TITLE
RaspBee II Deconz e ZigBee2MQTT - sto inferno non funziona (più)

### DISCUSSION THREAD

**Discussion by auanasgheps** [indomus/forum#1661] [HUB: Home Assistant]
Ciao ragazzi,
Questo è il mio setup:
- Raspberry Pi 4B - 4GB RAM
- HASS OS su SSD M2 con prolunga
- RaspBeeII connesso su GPIO

Sono arrivato al limite di sopportazione visto che non riesco più a far funzionare la parte Zigbee. Spero in qualche anima pia che mi possa aiutare.

Tempo fa installo RaspBee II con Deconz, poi mi accorgo che fa schifo e passo a Zigbee2MQTT. Una fatica metterlo su, ma va. Tutto ok.
Poi all'improvviso non vede più una mazza. Niente. Morte totale.

Questa è la situazione attuale:

**Zigbee2MQTT** 
Dalla dashboard non riesco a fare nessuna azione. Se clicco su "Permetti Join (Tutto)" non parte il countdown.
I log mi fanno inutire che qualcosa non va:

```
Zigbee2MQTT:info  2022-04-27 16:15:30: Zigbee: disabling joining new devices.
Zigbee2MQTT:error 2022-04-27 16:16:30: Failed to set permit join to false
```

E qui c'è il primo limite di questo addon: se qualcosa va in mona, come faccio a capire se l'addon sta comunicando con l'hub Zigbee? Non sembra possibile.

Va bene: fermo Z2MQTT e avvio deCONZ, che sembra non riuscire a "entrare" in rete. Ho provato a cercare in lungo e in largo e non trovo spiegazioni chiare.

![image](https://user-images.githubusercontent.com/20586878/165541776-678fa582-986f-49cf-a2e1-3b623383a7e2.png)

**Comment by auanasgheps** [comment]
Non so per quale stregoneria ora risulta In network, lato UI Phoscon vedo il firmware quindi il gateway sembra connesso e funzionante ma... Non trova alcun dispositivo.

Come faccio a sapere cosa c'è che non va?

**Reply by snakuzzo** [reply]
Per zigbee2mqtt...
Innanzi tutto metti i log a debug -> LEGGI [QUI](https://www.zigbee2mqtt.io/guide/usage/debug.html#enabling-logging)
Se non risolvi...apri issue sul progetto su github -> [QUI](https://github.com/Koenkk/zigbee2mqtt/issues)

Per le tue prove prova anche a cambiare canale (il cambio canale comporta la disconnessione di tutti i device). LEGGI anche [QUI](https://www.zigbee2mqtt.io/advanced/zigbee/02_improve_network_range_and_stability.html#reduce-wi-fi-interference-by-changing-the-zigbee-channel)

**Reply by indomus** [reply]
pubblichi per favore la configurazione zigbee2mqtt che usi?

**Reply by auanasgheps** [reply]
Ciao,
Ho messo i log in verbose ma non si evince molto, anche quando clicco su "Permetti Join (Tutto") non dice molto. Come al solito non funziona perché non c'è il timer che parte:

```
Zigbee2MQTT:debug 2022-04-29 12:42:51: Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data '{"device":null,"time":254,"transaction":"ul2tp-1","value":true}'
Zigbee2MQTT:info  2022-04-29 12:42:51: Zigbee: allowing new devices to join.
```

Idem per l'errore iniziale:

```
Zigbee2MQTT:info  2022-04-29 12:39:59: Currently 0 devices are joined:
Zigbee2MQTT:info  2022-04-29 12:39:59: Zigbee: disabling joining new devices.
Zigbee2MQTT:error 2022-04-29 12:40:59: Failed to set permit join to false
Zigbee2MQTT:info  2022-04-29 12:40:59: Connecting to MQTT server at mqtt://core-mosquitto
Zigbee2MQTT:debug 2022-04-29 12:40:59: Using MQTT login with username: mqtt_user
Zigbee2MQTT:info  2022-04-29 12:40:59: Connected to MQTT server
```

Di fatto debug serve davvero a poco.

Non sono sicuro se debba chiedere aiuto a Zigbee2MQTT o a Deconz, visto che neanche con il loro software sono in grado di fare il pairing. Secondo me c'è qualcosa nella comunicazione con il gateway che non sta funzionando.

Faccio la prova di cambio canale, tanto non ho più alcun dispositivo associato...

**Reply by auanasgheps** [reply]
@indomus trovi la configurazione in basso. Ho seguito la vostra guida e all'inizio sembrava funzionare.

`pan_id`, `network_key` e `ext_pan_id` li ho ricavati da Deconz, i due software usano parametri diversi e stavo cercando di armonizzarli. Anche se dai log sembra che ignoriil valore extendedPanID e continua a usare quello che vuole lui.

Ho anche cambiato il canale da 11 a 25, ma sembra ignorarlo, mah:
`Zigbee2MQTT:debug 2022-04-29 12:51:26: Zigbee network parameters: {"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754}`



```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: mqtt_user
  password: xxxxx
serial:
  port: /dev/ttyAMA0
  adapter: deconz
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
advanced:
  log_level: debug
  pan_id: 6754
  network_key: 1.3449068558044012e+36
  ext_pan_id: 0
  channel: 25
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
```
