### DISCUSSION TITLE
Un file .sh e command _shell

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#1670] [HUB: Home Assistant]
(Hassio) Devo spegnere il raspberry e vorrei farlo con la corretta procedura.
In Strumenti per sviluppatori->Servizi, ho modo di attivare :
Home Assistant Supervisor: _Poweroff the host system_
A questo punto potrei spegnere l'interuttore fisico del raspberry? Mi sa di no.

Se invece seguissi questa strada strada: eseguire uno script .sh che contiene un comando per shutdown del raspberry. 
In configuration.yaml:
```
shell_command:
  rasp_exit: bash /config/spegni.sh

```
spegni.sh è un file a cui ho dato l'autorizzazione di esecuzione da terminale con chmod e contiene questa riga di comando: 
 sudo shutdown -n now
Richiamando poi il comando con uno script:  - service: shell_command.rasp_exit
Mi date qualche consiglio/correzione?

**Comment by 50494554524F** [comment]
certo che puoi staccare l'alimentazione, dopo aver aspettato che finisca la procedura di spegnimento naturalmente

**Reply by Dregi56** [reply]
Dopo _Home Assistant Supervisor: Poweroff the host system_  ?

**Reply by 50494554524F** [reply]
si, aspetti un paio di minuti e poi stacchi..

**Reply by Dregi56** [reply]
Secondo te sarebbe possibile attuare uno script del genere:
```
spegnirasp:
  alias: spegne raspberry
  sequence:
  - service: hassio.host_shutdown
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: shell_command.rasp_exit
  mode: single
```
cosa dovrei aggiungere allo script per farlo funzionare?
