### DISCUSSION TITLE
Automazione

### DISCUSSION THREAD

**Discussion by gideonklein** [indomus/forum#1673] [HUB: Home Assistant]
Ciao a tutti, 
vorrei aiuto con una automazione in HA. 
Come condizione vorrei che parta l'azione dopo 3 o più volte che il trigger viene riconosciuto. Il trigger ha un valore numerico scatta l'azione ma deve scattare dopo 3 volte che viene riconosciuto in un determinato numero di minuti. L'automazione è funzionante ma senza la condizione e quindi parte l'azione ogni volta.
Non so se sono stato chiaro, ma non riesco proprio a dargli una condizione. Potete aiutarmi? Grazie comunque

**Comment by xyzmauro** [comment]
Ciao,con una condition ci fai poco,quello che ti serve è un input_number dove andrai a sommare il numero di volte in cui è triggerata l’automazione e un timer, a qst punto gestisci il tutto con una choose…
- Con condition input_numer 0 aggiungi 1 all’input_number e fai partire il timer
- Con condition 1 e timer ancora attivo aggiungi 1 all’input_number
- Con condition 3 e timer ancora attivo scatta la action
Metti nel trigger anche il timer e 
- con condition timer scaduto resetti timer e input_number
Non dovrebbe essere così complicata 😉

**Reply by xyzmauro** [reply]
Ti servono
https://www.home-assistant.io/integrations/input_number/ e il service increment
https://www.home-assistant.io/integrations/timer/ coi suoi possibili stati, e la choose
https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions

**Reply by gideonklein** [reply]
Grazie Mauro, sempre gentile. Mi ci vorranno giorni se non settimane per capire per me che sono profano. Speriamo bene

**Reply by xyzmauro** [reply]
Se riesco entro il weekend ti butto giù un esempio 😉

**Reply by gideonklein** [reply]
Grazie Mauro, sarebbe fantastico, non credo di riuscire senza. A presto, grazie ancora

**Reply by xyzmauro** [reply]
Ho trovato un attimo di calma per mettere giù l'idea che ti avevo suggerito, provala e adattala alle tue esigenze....

```
input_boolean:
  gideonklein:
    name: gideonklein
    initial: off

input_number:
  gideonklein: 
    name: gideonklein
    min: 0
    max: 5
    initial: 0
    step: 1

timer:
  gideonklein:    

automation:
  - alias: action dopo 3 trigger entro tempo
    trigger:    
      - platform: state
        entity_id: input_boolean.gideonklein
        to: "on"
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.gideonklein
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ states('input_number.gideonklein') == '0.0' }}"                   
            sequence:
              - service: input_number.increment
                data:
                  entity_id: input_number.gideonklein
              - service: timer.start
                data:
                  entity_id: timer.gideonklein
                  duration: '00:00:30'
          - conditions:
              - condition: template
                value_template: "{{ states('input_number.gideonklein') == '1.0' and states('timer.gideonklein') == 'active'}}"                   
            sequence:
              - service: input_number.increment
                data:
                  entity_id: input_number.gideonklein
          - conditions:
              - condition: template
                value_template: "{{ states('input_number.gideonklein') == '2.0' and states('timer.gideonklein') == 'active'}}"                   
            sequence:
              - service: persistent_notification.create
                data:
                  message: "scattato per 3 volte il trigger entro il timer" 
              - service: input_number.set_value
                data:
                  entity_id: input_number.gideonklein
                  value: 0
              - service: timer.cancel
                data:
                  entity_id: timer.gideonklein  
              - service: input_boolean.turn_off
                data:
                  entity_id: input_boolean.gideonklein      
        default:
          - service: input_number.set_value
            data:
              entity_id: input_number.gideonklein
              value: 0
          - service: timer.cancel
            data:
              entity_id: timer.gideonklein
          - service: persistent_notification.create
            data:
              message: "scaduto timer" 
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.gideonklein
```

**Reply by gideonklein** [reply]
Gentilissimo, grazie non ci sarei mai riuscito da solo. Ho adattato alle mie esigenze ma forse ho sbagliato qualcosa. L'azione scatta sempre non tiene conto che deve scattare dopo 3 volte. Incollo il codice:
`  mode: single
- id: '987823883739548'
  alias: Autoclave action dopo 3 trigger entro tempo
  trigger:
  - platform: numeric_state
    entity_id: sensor.sonoff_1000dd2821_power
    above: '780'
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.autoclave
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ states(''input_number.autoclave'') == ''0.0'' }}'
      sequence:
      - service: input_number.increment
        data:
          entity_id: input_number.autoclave
      - service: timer.start
        data:
          duration: 00:09:30
        target:
          entity_id: timer.autoclave
    - conditions:
      - condition: template
        value_template: '{{ states(''input_number.autoclave'') == ''1.0'' and states(''timer.autoclave'')
          == ''active''}}'
      sequence:
      - service: input_number.increment
        data:
          entity_id: input_number.autoclave
    - conditions:
      - condition: template
        value_template: '{{ states(''input_number.autoclave'') == ''2.0'' and states(''timer.autoclave'')
          == ''active''}}'
      sequence:
      - service: persistent_notification.create
        data:
          message: scattato per 3 volte il trigger entro il timer
      - service: input_number.set_value
        data:
          entity_id: input_number.autoclave
          value: 0
      - service: timer.cancel
        data:
          entity_id: timer.autoclave
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.autoclave
    default:
    - service: input_number.set_value
      data:
        entity_id: input_number.autoclave
        value: 0
    - service: timer.cancel
      data:
        entity_id: timer.autoclave
    - service: persistent_notification.create
      data:
        message: scaduto timer
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.autoclave
  - service: notify.persistent_notification
    data:
      message: ATTENZIONE! L'autoclave si accende in continuazione
  - service: notify.telegram
    data:
      message: ATTENZIONE! L'autoclave si accende in continuazione
  - service: tts.google_translate_say
    data:
      entity_id: media_player.studio
      message: Attenzione! L'autoclave si accende in continuazione
      language: it`

**Reply by xyzmauro** [reply]
Non hai usato il markdown e non si capisce molto…
Comunque nel mio esempio avevo lasciato apposta un grosso errore di concetto proprio x farti ragionare e non fare copia/incolla brutalmente…
Cosa succede se dopo aver attivato il boolean la prima volta metti manualmente il number a 5 e attivi per la seconda volta il boolean? Perché smette di funzionare correttamente l’automazione?

**Reply by gideonklein** [reply]
```
- id: '987823883739548'
  alias: Autoclave action dopo 3 trigger entro tempo
  trigger:
  - platform: numeric_state
    entity_id: sensor.sonoff_1000dd2821_power
    above: '780'
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.autoclave
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ states(''input_number.autoclave'') == ''0.0'' }}'
      sequence:
      - service: input_number.increment
        data:
          entity_id: input_number.autoclave
      - service: timer.start
        data:
          duration: 00:09:30
        target:
          entity_id: timer.autoclave
    - conditions:
      - condition: template
        value_template: '{{ states(''input_number.autoclave'') == ''1.0'' and states(''timer.autoclave'')
          == ''active''}}'
      sequence:
      - service: input_number.increment
        data:
          entity_id: input_number.autoclave
    - conditions:
      - condition: template
        value_template: '{{ states(''input_number.autoclave'') == ''2.0'' and states(''timer.autoclave'')
          == ''active''}}'
      sequence:
      - service: persistent_notification.create
        data:
          message: scattato per 3 volte il trigger entro il timer
      - service: input_number.set_value
        data:
          entity_id: input_number.autoclave
          value: 0
      - service: timer.cancel
        data:
          entity_id: timer.autoclave
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.autoclave
    default:
    - service: input_number.set_value
      data:
        entity_id: input_number.autoclave
        value: 0
    - service: timer.cancel
      data:
        entity_id: timer.autoclave
    - service: persistent_notification.create
      data:
        message: scaduto timer
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.autoclave
  - service: notify.persistent_notification
    data:
      message: ATTENZIONE! L'autoclave si accende in continuazione
  - service: notify.telegram
    data:
      message: ATTENZIONE! L'autoclave si accende in continuazione
  - service: tts.google_translate_say
    data:
      entity_id: media_player.studio
      message: Attenzione! L'autoclave si accende in continuazione
      language: it
```

**Reply by gideonklein** [reply]
Dove devo mettere il number 5?
```
##### Autoclave ##################################
input_boolean:
  autoclave:
    name: autoclave
    initial: off

input_number:
  autoclave: 
    name: autoclave
    min: 0
    max: 5
    initial: 0
    step: 1

timer:
  autoclave:
```
questo l'ho messo su configuration.yaml

**Reply by gideonklein** [reply]
initial: off . In questo caso forse non va bene? non è off/on ma l'azione di attiva con il valore numerico superiore di

**Reply by xyzmauro** [reply]
![Senza titolo](https://user-images.githubusercontent.com/56839356/167089051-d62e1691-a0af-40d0-adc0-c8a6acc8d129.png)
qui intendevo, sempre che tu abbia almeno provato il mio esempio per capire come funziona prima di buttarti ad adattarlo...
cmq il concetto è che se in una choose utilizzi il default devi prima aver gestito TUTTE le possibili condition...
nel tuo caso finisce nel default probabilmente perchè hai sbagliato ad usare apici e doppi apici nei template, almeno così sembra
PS a te il boolean neanche serve, era solo per simulare un trigger nel mio esempio

**Reply by gideonklein** [reply]
ah si ho trovato era a 0 e ho impostato a 5 come suggerito. Posso fare la prova più tardi e rivedo il tutto e ti faccio sapere. Intanto ancora grazie

**Reply by gideonklein** [reply]
Ho Tolto imput boleano ma non funziona
Facendo test in tutte e 3 le opzioni mi dà questo errore: 
template value should be a string for dictionary value @ data['value_template']. Got None
Incollo il codice dell'automazione
```
- id: '987823883739548'
  alias: Autoclave action dopo 3 trigger entro tempo
  trigger:
  - platform: numeric_state
    entity_id: sensor.sonoff_1000dd2821_power
    above: '780'
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.autoclave
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ states(''input_number.autoclave'') == ''0.0'' }}'
      sequence:
      - service: input_number.increment
        data:
          entity_id: input_number.autoclave
      - service: timer.start
        data:
          duration: 00:09:30
        target:
          entity_id: timer.autoclave
    - conditions:
      - condition: template
        value_template: '{{ states(''input_number.autoclave'') == ''1.0'' and states(''timer.autoclave'')
          == ''active''}}'
      sequence:
      - service: input_number.increment
        data:
          entity_id: input_number.autoclave
    - conditions:
      - condition: template
        value_template: '{{ states(''input_number.autoclave'') == ''2.0'' and states(''timer.autoclave'')
          == ''active''}}'
      sequence:
      - service: persistent_notification.create
        data:
          message: scattato per 3 volte il trigger entro il timer
      - service: input_number.set_value
        data:
          entity_id: input_number.autoclave
          value: 0
    default:
    - service: input_number.set_value
      data:
        entity_id: input_number.autoclave
        value: 0
    - service: timer.cancel
      data:
        entity_id: timer.autoclave
    - service: persistent_notification.create
      data:
        message: scaduto timer
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.autoclave
  - service: notify.persistent_notification
    data:
      message: ATTENZIONE! L'autoclave si accende in continuazione
  - service: notify.telegram
    data:
      message: ATTENZIONE! L'autoclave si accende in continuazione
  - service: tts.google_translate_say
    data:
      entity_id: media_player.studio
      message: Attenzione! L'autoclave si accende in continuazione
      language: it
```

**Reply by xyzmauro** [reply]
Riguarda gli apici, ‘ oppure ‘’ o “ son cose diverse

**Reply by gideonklein** [reply]
Funziona! Grazie mille. Dopo 2 ore ho capito e corretto. In pratica funzionava anche prima solo che avevo messo alla fine le azioni delle notifiche che non tenevano conto delle opzioni 1, 2 e 3. Quindi le ho messo le azioni nell'opzione 3 e ora è tutto ok
Grazie Mauro, senza il tuo codice non ci sarei mai arrivato
incollo il codice ora funzionante

```
- id: '987823883739548'
  alias: Autoclave action dopo 3 trigger entro tempo
  trigger:
  - platform: numeric_state
    entity_id: sensor.sonoff_1000dd2821_power
    above: '780'
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.autoclave
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ states(''input_number.autoclave'') == ''0.0'' }}'
      sequence:
      - service: input_number.increment
        data:
          entity_id: input_number.autoclave
      - service: timer.start
        data:
          duration: 00:09:30
        target:
          entity_id: timer.autoclave
    - conditions:
      - condition: template
        value_template: '{{ states(''input_number.autoclave'') == ''1.0'' and states(''timer.autoclave'')
          == ''active''}}'
      sequence:
      - service: input_number.increment
        data:
          entity_id: input_number.autoclave
    - conditions:
      - condition: template
        value_template: '{{ states(''input_number.autoclave'') == ''2.0'' and states(''timer.autoclave'')
          == ''active''}}'
      sequence:
      - service: persistent_notification.create
        data:
          message: AUTOCLAVE, scattato per 3 volte il trigger entro il timer
      - service: input_number.set_value
        data:
          value: 0
        target:
          entity_id: input_number.autoclave
      - service: notify.persistent_notification
        data:
          message: ATTENZIONE! L'autoclave si accende in continuazione
      - service: notify.telegram
        data:
          message: ATTENZIONE! L'autoclave si accende in continuazione
      - service: tts.google_translate_say
        data:
          language: it
          entity_id: media_player.studio
          message: Attenzione! L'autoclave si accende in continuazione
    default:
    - service: input_number.set_value
      data:
        value: 0
      target:
        entity_id: input_number.autoclave
    - service: timer.cancel
      data:
        entity_id: timer.autoclave
    - service: persistent_notification.create
      data:
        message: AUTOCLAVE, scaduto timer

**Reply by xyzmauro** [reply]
Non avevo dubbi funzionasse,mi resta il dubbi di quegli apici ma forse è solo colpa del markdown…
Non sono sicuro tu abbia capito il “difetto” di usare il default in una choose,ma se ti va bene così ok…io limiterei il max a 2 dell’input_number e proverei a gestire lo stato “unavailable” o “unknown” che potrebbe avere il sonoff altrimenti avrai problemi…

**Comment by gideonklein** [comment]
Buongiorno Mauro, gli apici non mi danno nessun errore sia in automation.yaml che nella configurazione su pannello automazioni di HA. Poi sono riuscito ad inserire il codice correttamente con il markdown qui ed è identico a quello che ho io nel mio file yaml, quindi presumo sia giusto. Cosa intendi per usare il default nella choose? e come si fa a limitare a 2? intendi qui?:
``` 
input_number:
  autoclave: 
    name: autoclave
    min: 0
    max: 5
    initial: 0
    step: 1
````
e per  “unavailable” o “unknown”  intendi quando il sonoff perde connessione^ e che tipo di problemi? In ogni caso almeno per i devices che ho non ho nessun problema, ho circa 100 device (pochi sonoff) che funzionano tutti perfettamente e sempre online con 1 modem e 2 router mesh perfettamente settati (ci ho perso mesi per settare tutto)
