### DISCUSSION TITLE
Problema BLE Beacon ESPHOME

### DISCUSSION THREAD

**Discussion by razorbac91** [indomus/forum#1674] [HUB: Home Assistant]
Ciao a tutti.
Ho integrato due beacon BLE che uso come sensori presenza tramite esphome e fino a qui tutto bene. 
Ho poi provveduto a integrare anche il loro pulsante come dalle istruzioni presenti sul sito esphome "itag button" e la percentuale batteria e tutto funziona, PER CINQUE MINUTI. 
Passati i 5 minuti il sensore perde la connessione con il tracker BLE. aumentando la variabile "duration" di esp32_ble_tracker, aumenta anche il tempo per cui il beacon rimane connesso, ma altresi il tracker non effettua il passaggio a off del binary sensor (se per esempio spengo manualmente il beacon)  fino allo scadere di "duration" se non attivo pulsante e batteria, il solo sensore di presenza funziona benissimo senza timeout

allego il codice che utilizzo

```
esp32_ble_tracker:
  scan_parameters:
   interval: 2000ms
   window: 500ms
   active: false
   duration: 5min

ble_client:
  - mac_address: F8:7B:AD:78:73:F7
    id: beacon_razorbac_button

binary_sensor:

  - platform: template
    id: razorbac_button
    name: "Beacon Razorbac Button"
    filters:
      delayed_off: 200ms

  - platform: ble_presence
    mac_address: FB:70:65:51:75:E8
    name: "Beacon Otacon"
    device_class: presence
    id: beacon1
    filters:
    - delayed_off: 10s

  - platform: ble_presence
    mac_address: F8:7B:AD:78:73:F7
    name: "Beacon Razorbac"
    device_class: presence
    id: beacon2
    filters:
    - delayed_off: 10s

sensor:

  - platform: ble_client
    ble_client_id: beacon_razorbac_button
    name: "Beacon Razorbac btn"
    service_uuid: '6E400001-B5A3-F393-E0A9-E50E24DCCA9E'
    characteristic_uuid: '6E400003-B5A3-F393-E0A9-E50E24DCCA9E'
    notify: true
    update_interval: never
    on_notify:
      then:
        - binary_sensor.template.publish:
            id: razorbac_button
            state: ON
        - binary_sensor.template.publish:
            id: razorbac_button
            state: OFF
  
  - platform: ble_client
    ble_client_id: beacon_razorbac_button
    name: "Beacon Razorbac Battery"
    service_uuid: '1800'
    characteristic_uuid: '2A00'
    icon: 'mdi:battery'
    unit_of_measurement: '%'`
```
