### DISCUSSION TITLE
Automazione che spegne tutte le luci

### DISCUSSION THREAD

**Discussion by calcioscacchi** [indomus/forum#1678] [HUB: Home Assistant]
CIao a tutti, prendendo spunto da questa guida: 
[https://indomus.it/formazione/uscire-e-rientrare-a-casa-lautomazione-domotica-via-home-assistant/](url)

Ho leggermente modificato l'automazione di uscita per spegnere ,oltre alle entità lights, anche le entità switch:

```
- alias: "USCITA"
  initial_state: true
  trigger:
    platform: state
    entity_id: group.famiglia
    from: 'home'
  action:
    - service: light.turn_off
      entity_id: group.all_light
    - service: switch.turn_off  
      entity_id: group.all_switch
```

purtroppo, al momento non funziona: se tutti i membri della famiglia vanno in stato not home, le luci rimangono accese. Sicuramente quella che  è rimasta accesa (ne ho tenuta accesa 1 per prova) è uno switch (nello specifico uno shelly 2.5. 

A livello di yaml è tutto a posto, l'automazione è riconosciuta da HA (versione core su docker).
Avete dei suggerimenti? 
Grazie
