### DISCUSSION TITLE
Trigger in automazione

### DISCUSSION THREAD

**Discussion by skizz0to** [indomus/forum#1684] [HUB: Home Assistant]
Salve,
ho un'automazione che nel momento in cui legge che ci sono più di x mm di pioggia mi attiva un input_boolean.
Il sensore restituisce un valore string e quindi ho usato i template.
Nel codice ho riportato i due template che ho provato. Nei modelli entrambi funzionano restituendomi true/false a seconda
della soglia che metto, nell'automazione invece non funziona nessuna delle due.
Qualcuno sa aiutarmi?
Grazie

```

- id: '1652011575569'
  alias: Sta Piovendo
  description: ''
  trigger:
    platform: template
    # value_template: "{% if states.sensor.openweathermap_rain.state | float > 10.1 %} true {% endif %}"
    value_template: "{{ (states.sensor.openweathermap_rain.state|float(0)) > 0.1}}"
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.sta_piovendo
  - service: persistent_notification.create
    data:
      message: Pioggia in corso
  mode: single

```
