### DISCUSSION TITLE
Alexa come Sirena

### DISCUSSION THREAD

**Discussion by Cusu95** [indomus/forum#170] [GENERALE - Discussioni generiche]
Ciao a tutti ragazzi,
Ho integrato tutti i sensori di movimento/varchi su home Assistant tramite deconz, e ho anche correttamente impostato alarm panel.
La domanda è: è possibile far riprodurre ad Alexa una sirena o un qualche suono di dissuasione? Al momento riesco solo a farla parlare tramite notify.alexa, ma mi servirebbe che continuasse a riprodurre un suono finché non disattivo l’allarme.
Grazie a tutti!!!

**Comment by Larry-78** [comment]
Ciao, prova a dare una occhiata qui,
https://github.com/custom-components/alexa_media_player/wiki#play-sounds
c'è anche un link dove troverai molti esempi di suoni utilizzabili. 
Nel tuo caso utilizzerei REPEAT UNTIL se desideri ripetere il suono fino al verificarsi di un a determinata condizione.
https://www.home-assistant.io/docs/scripts/#repeat-until
Ho provato ad approfondire utilizzando gli esempi della wiki ufficiale ma non funziona con tutti i suoni, invece con l'esempio che propongo basta sostituire il `message:` e incollare il source code dell'elenco suoni disponibili; ovviamente bisogna sostituire anche il  `service:` con il servizio legato al proprio dispositivo Alexa integrato.
Provalo in Developer Tools/SERVICES
Questo è un esempio per far riprodurre un suono di sirena:

```yaml
service: notify.alexa_media
data:
  data:
    type: tts
  message: <audio src="soundbank://soundlibrary/alarms/beeps_and_bloops/sirens_01"/>
  ```
  ...mi rimane soltanto un dubbio... durante i vari test, non capisco perché funziona soltanto se utilizzo `data:` due volte, un parere di un esperto sarebbe gradito.

**Reply by Larry-78** [reply]
....ho approfondito, mi sa che questa è la configurazione giusta.
```yaml
service: notify.alexa_media
data:
  target: 
    - media_player.alexa
  data:
    type: tts
  message: <audio src="soundbank://soundlibrary/alarms/beeps_and_bloops/sirens_01"/>
````
