### DISCUSSION TITLE
Problema sensor dopo aggiornamento 2022.6

### DISCUSSION THREAD

**Discussion by manny199** [indomus/forum#1718] [GENERALE - Discussioni generiche]
Salve, ci sbatto da un po' ma non ne esco fuori.
L'errore è: "Manually configured MQTT sensor(s) found under platform key 'sensor', please move to the mqtt integration key"

Ho modificato la configurazione come segue ma si presentano altri errori. Cosa mi sgugge?

```
mqtt:
  sensor:
    - name: "Zigbee2mqtt Bridge state"
      state_topic: "zigbee2mqtt/bridge/state"
      icon: mdi:router-wireless

    - name: "Zigbee2mqtt Version"
      state_topic: "zigbee2mqtt/bridge/config"
      value_template: "{{ value_json.version }}"
      icon: mdi:zigbee

    - name: "Coordinator Version"
      state_topic: "zigbee2mqtt/bridge/config"
      value_template: "{{ value_json.coordinator }}"
      icon: mdi:chip
```
Manifesta errore expected <block end>, but found '-'
Ho provato a togliere il trattino ma nulla ...

Grazie
