### DISCUSSION TITLE
Aiuto per comparare trigger.from_state e trigger.to_state

### DISCUSSION THREAD

**Discussion by Topolynx** [indomus/forum#1729] [HUB: Home Assistant]
Ciao a tutti, mi potreste aiutare per cortesia? Sto cercando di modificare questa automazione perché per come è ora mi notifica ogni due minuti l'aggiornamento dell'ip pubblico anche se in realtà è sempre lo stesso.
Ho provato ad inserire la condizione per cui il valore "from_state" e il "to_state" debbono essere diversi ma ricevo un messaggio di errore _**"template value should be a string for dictionary value @ data['value_template']. Got None"**_
Come faccio a cavare fuori questi valori? Grazie per il vostro aiuto!

```
alias: '[WAN] [01] - Nuovo IP Pubblico'
description: Avvisa al cambio di IP Pubblico
trigger:
  - platform: state
    entity_id:
      - sensor.ip_pubblico
condition:
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
action:
  - service: notify.mobile_app_iphone_3
    data:
      message: '{{ states.sensor.ip_pubblico.state }}'
      title: Il Tuo IP Pubblico è cambiato in
mode: single
```

**Comment by snakuzzo** [comment]
la condition è del tutto inutile, per come hai scritto Il trigger, senza specificare to e from, scatta ad ogni "cambio" di stato, quindi la condizione che hai scritto è del tutto superflua.
Se l'automazione scatta, il problema non è tanto l'automazione, ma il sensore. Fai vedere come hai scritto il sensore (se l'hai scritto tu). In caso diverso, verifica l'history del sensore...vedi come cambia stato. Dall'errore che hai postato sul template, credo che il problema sia proprio legato al fatto che il sensore ogni tanto diventa `None`.

**Reply by Topolynx** [reply]
Il sensore è scritto così preso paro paro dagli esempi del sito di Home Assistant. 

```
- platform: rest
  name: IP Pubblico
  resource: http://ip.jsontest.com
  value_template: "{{ value_json.ip }}"
```

**Reply by snakuzzo** [reply]
Magari questa chiamata qualche volta fallisce...e quindi non riesce ad estrare l'IP dal JSON (perché magari non hai un JSON come risultato). Prova a guardare i log di HA.
Ad ogni modo, se può esserti utile, io lo recupero così...e non ho problemi del genere

```yaml
sensor:
  - platform: rest
    name: public_ip
    resource: https://ipinfo.io/ip
```

**Reply by Topolynx** [reply]
@snakuzzo anzitutto grazie, sei sempre pronto a dare una mano :)
Il sensore come il tuo l'ho anche io, anzi è stato il primo sensore che ho usato (mutuato poi dalla guida indomus per aggiornare duckdns), e si, ogni tanto lo stato diventa `none`o `unavailable`.
Ho provato a testare l'automazione con un'altra entità e funziona, anche se mi manda anche tre o quattro messaggi di fila a random. Ho provato a mettere un ritardo di 5 secondi per vedere se fosse un problema di "timing" ma no. 
```
alias: TEST from state to state
description: Avvisa al cambio di stato se from_state è diverso da to_state
trigger:
  - platform: state
    entity_id:
      - switch.piantana_salotto_switch
    for:
      hours: 0
      minutes: 0
      seconds: 5
condition:
  - condition: template
    value_template: '{{ trigger.from_state != trigger.to_state }}'
action:
  - service: notify.mobile_app_iphone_3
    data:
      message: '{{ states.switch.piantana_salotto_switch.state }}'
      title: La piantana è cambiata in
mode: single
```

EDIT: ed ho ripristinato comunque il sensore basato su ipinfo.io.
