### DISCUSSION TITLE
Automazione che non parte

### DISCUSSION THREAD

**Discussion by baurbr** [indomus/forum#173] [HUB: Home Assistant]
Ciao, sto cercando di impostare un'automazione che dovrebbe aprire la tenda da sole al mattino se c'è sole. 
Per debug come azione ho messo una notifica Telegram. 
Non capisco perchè non si esegue... ho provato con == sunny che != sunny. Vedete qualcosa di sbagliato? 
Esiste un modo per fare un debug delle automazioni e capire quale trigger non scatta? 
Grazie

```
alias: Abbassa la tenda al mattino
description: ''
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: '20'
  - platform: template
    value_template: '{{ states(''weather.casa'') != sunny }}'
condition:
  - condition: device
    device_id: 2f560625bc983ae88273d26b4ded64c7
    domain: cover
    entity_id: cover.tenda
    type: is_closed
action:
  - service: notify.robert
    data:
      message: Abbasso la tenda
mode: single
```
`

**Comment by snakuzzo** [comment]
1. `"sunny"` deve essere una stringa, tu la stai passando senza apici
2. Il valore di `above` deve essere un numero, tu gli stai passando una stringa (visto che hai messo gli apici). Questo non dovrebbe comunque essere un problema
3. Consiglio...non usare "device" per le action ma usa i servizi passando le entità
4. Altro consiglio...nei template usa apici doppi fuori e singoli dentro...o viceversa

```yaml
- id: abbassa_tenda_mattino
  alias: Abbassa la tenda al mattino
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: 20
  - platform: template
    value_template: "{{ states('weather.casa') != 'sunny' }}"
  condition:
  - condition: state
    entity_id: cover.tenda
    state: 'closed'
  action:
  - service: notify.robert
    data:
      message: 'Abbasso la tenda'
```

Infine, se vuoi debuggare le automazioni, impostando anche l'id come ho fatto io, puoi vedere il debug direttamente da Configuration > Automations cliccando sull'icona sulla destra dell'automazione.
Volendo puoi anche debuggare aggiungendo questo nel file `configuration.yaml`:

```yaml
logger:
  default: warning
  logs:
    homeassistant.components.automation: debug
```

Fai sapere se va...ho scritto di getto senza provare e/o controllare la sintassi

**Reply by baurbr** [reply]
grazie.. facendo qualche correzione che mi hai suggerito l'automazione funziona!!

Ti chiedo un altro aiuto...
Vorrei mandarmi una notifica su telegram con il valore degli attributi al monento dell'attivazione. 
Non capisco perchè se nel messaggio scrivo
```
service: notify.robert
data:
  message: Meteo {{states('weather.casa') }} - Vento {{state_attr('weather.casa', 'wind_speed')}} 
```
la notifica arriva, mentre se aggiungo lo stato di sun.sun non parte la notifica e non vengono segnalati errori
```
service: notify.robert
data:
  message: Meteo {{states('weather.casa') }} - Vento {{state_attr('weather.casa', 'wind_speed')}} - Sole {{ states('sun.sun') }}
```
Anche provando a forzare la chiamata da developer tools->service
![Immagine 2021-04-18 135628](https://user-images.githubusercontent.com/55288934/115144611-e7fd5f80-a04d-11eb-8640-8880feb3227d.jpg)

**Reply by snakuzzo** [reply]
Usando la funzione `states()` in questo specifico caso ti darà un errore di parsing nel log. Prova usando la dot notation per l'entità `sun.sun`... dovrebbe funzionare

```
​service: notify.robert
data:
  message: Meteo {{states('weather.casa') }} - Vento {{state_attr('weather.casa', 'wind_speed')}} - Sole {{ states.sun.sun.state') }}
```

Per la prossima volta...controlla in CONFIGURATION > DEVELOPER TOOLS > TEMPLATE

**Reply by baurbr** [reply]
Purtroppo non funziona... se provo con 

```
service: notify.robert
data:
  message: Test {{ states.sun.sun.state }}
```

Nel log mi trovo questo
`2021-04-18 19:20:34 ERROR (SyncWorker_4) [homeassistant.components.telegram_bot] Error sending message: Can't parse entities: can't find end of the entity starting at byte offset 10. Args: (94757517, 'Test above_horizon'), kwargs: {'parse_mode': 'Markdown', 'disable_web_page_preview': None, 'disable_notification': False, 'reply_to_message_id': None, 'reply_markup': None, 'timeout': None}`

Mi sta venendo un mal di testa... :-)

**Reply by baurbr** [reply]
Errata corrige... 
Ho risolto mettendo 
`parse_mode: html`
nella configurazione del bot telegram.

Thanks for all

**Reply by snakuzzo** [reply]
perfetto. Bravo! :)

**Comment by corri57** [comment]
Mi collego a questa discussione, la mia prima automazione non parte, e da un po di giorni non trovo soluzione.
Vorrei semplicemente accendere o spegnere una luce verificando se luce rilevata  e' maggiore o meno di una soglia (per semplicita' nella condizione metto direttamente un valore numerico). 
l'automazione e':
```
alias: Luci esterne
description: ON/OFF luci esterne con crepuscolare
trigger:
  - platform: mqtt
    topic: Luce-Rilevata
condition:
  - condition: template
    value_template: "{{ ((states.sensor.luce |int(default=0) ) >= 200 ) }}"
action:
  - type: toggle
    device_id: a23650e516d00d04d343e1745dd60534
    entity_id: switch.sonoff_10002e1aad
    domain: switch
```

e il risultato in strumenti....modelli e':
```
Tipo di risultato: string
alias: Luci esterne
description: ON/OFF luci esterne con crepuscolare
trigger:
  - platform: mqtt
    topic: Luce-Rilevata
condition:
  - condition: template
    value_template: "False"
action:
  - type: toggle
    device_id: a23650e516d00d04d343e1745dd60534
    entity_id: switch.sonoff_10002e1aad
    domain: switch
Questo modello non ascolta alcun evento e non si aggiornerà automaticamente
```

Il problema sembra sia come vado a scrivere la condizione, il valore int assume sempre il default 0. Se non metto alcuna condizione, l'azione viene esguita ogni qualvolta si verifica il trigger.

Ancora, nel confronto con la soglia, invece di usare direttamente il numerico 200, posso confrontarlo in qualche modo con il valore soglia che nel file di configurazione definisco cosi:

```
mqtt:
  number:
    name: mqtt-number-Soglia
    state_topic: "valore_soglia_crepuscolare"
    command_topic: "soglia_crepuscolare"
#    availability_topic
    min: 0
    max: 1024
    mode: "slider"
```

**Reply by snakuzzo** [reply]
Innanzi tutto il template usato nella condizione che hai indicato è sbagliata.
Puoi scrivere

```
value_template: "{{ states('sensor.luce') | int(default=0)  >= 200 ) }}"
```

oppure

```
value_template: "{{ states.sensor.luce.state |int(default=0) ) >= 200 ) }}"
```

(ma è consigliata la prima, per questo motivo...

![image](https://user-images.githubusercontent.com/7205371/216847270-9f821c87-198c-467c-899b-8131eb63d5d8.png)

Ad ogni modo, non credo sia il modo corretto di impostare l'automazione.
Dovresti postare qui un esempio del payload legato al topic che hai indicato nel trigger

**Reply by corri57** [reply]
OK, grazie, finalmente vedo funzionare la mia prima automazione.

il topic del trigger e' cosi descritto:

```
    
  sensor:
  - name: "Luce-Rilevata"
    state_topic: "Luce-Rilevata"
    icon: mdi:theme-light-darkmqtt
    unique_id: "Luce-Rilevata"   

```

e nella scheda delle viste:

```
type: gauge
entity: sensor.luce
min: 0
max: 1024
severity:
  green: 0
  yellow: 0
  red: 0

```

Per quanto riguarda il payload, se intendi quello della publish() di mqtt e' un vettore di char[7] in cui converto con itoa()  il valore letto dal sensore.

**Reply by snakuzzo** [reply]
non hai capito.
Mi serve vedere il payload di quel topic che viene pubblicato

**Reply by corri57** [reply]
Scusami ma sono all'inizio dell'utilizzo di HA e non riesco a capire bene quello che ti interessa vedere.
Ho tracciato gli eventi tramite strumenti..../eventi/ascolto...
e quello che vedo e' questo ma non so se e' quello che vuoi vedere, diversamente dammi qualche indicazione su come acquisisre questo payload.

```
event_type: state_changed
data:
  entity_id: sensor.luce
  old_state:
    entity_id: sensor.luce
    state: "165"
    attributes:
      icon: mdi:theme-light-darkmqtt
      friendly_name: Luce-Rilevata
    last_changed: "2023-02-06T12:13:31.923331+00:00"
    last_updated: "2023-02-06T12:13:31.923331+00:00"
    context:
      id: 01GRKAAJCKE0WPRFSQ3P59KRZH
      parent_id: null
      user_id: null
  new_state:
    entity_id: sensor.luce
    state: "167"
    attributes:
      icon: mdi:theme-light-darkmqtt
      friendly_name: Luce-Rilevata
    last_changed: "2023-02-06T12:13:38.441097+00:00"
    last_updated: "2023-02-06T12:13:38.441097+00:00"
    context:
      id: 01GRKAARR900WJKE49FWR82X4S
      parent_id: null
      user_id: null
origin: LOCAL
time_fired: "2023-02-06T12:13:38.441097+00:00"
context:
  id: 01GRKAARR900WJKE49FWR82X4S
  parent_id: null
  user_id: null
```
