### DISCUSSION TITLE
Problema con automazione per fade led

### DISCUSSION THREAD

**Discussion by giangi007** [indomus/forum#1741] [HUB: Home Assistant]
Ciao a tutti, non riesco a inserire in una automazione il valore  preso da un sensore tempalte mi spiego: ho installato un pyscript per il fade [https://gist.github.com/tal/b36f963c2b04bae52a1c1a4889592eee](url) e funziona regolarmente se prova ad attivare lo script da "servizi" impostando tutti i dati in manuale. Volevo però prendere due variabili da due sensor, un sensor template e da un input number, ma non funziona. questi i codici:

```
sensor:
##############################################################
####sensore con un decimale per tempo fade       #############
##############################################################
  - platform: template
    sensors:
      fadein_minuti:
        value_template: "{{ states('input_number.durata_fadein') | int(0) }}"
##############################################################
####sensore potenza led luci automatiche acquario#############
##############################################################
  - platform: template
    sensors: 
      quantitalucegiorno:
        friendly_name: Potenza led giorno
        value_template: '{{ states.input_number.day_brightness.state | int(0) }}

#################################################################
##      Automazione fade in                                    ##                                                 
#################################################################
- id: '1655630928644'
  alias: Nuova auttest fadeinomazione
  description: Automazione Fade in acquario
  trigger:
  - platform: time
    at: input_datetime.fade_in_start
  condition:
  - condition: state
    entity_id: input_boolean.global_brightness
    state: 'on'
  action:
  - service: script.light_fader
    data:
      light: light.acquario_led1
      end_pct: 60
      transition: states.sensor.fadein_minuti 
  mode: parallel

```

grazie
