### DISCUSSION TITLE
Automazione spesso non esegue azioni nonostante parta il trigger

### DISCUSSION THREAD

**Discussion by cosimopan** [indomus/forum#1752] [GENERALE - Discussioni generiche]
Ciao a tutti,
Sotto consiglio di un utente nella chat Telegram ([link al mio messaggio](https://t.me/indomus_chat/384795)) apro qui una discussione in modo da trattare il tema più approfonditamente.

Ho un'automazione molto semplice che "fa le bizze". La riporto qui:

```
alias: Presa - Caricatore letto ON
description: Ogni giorno alle 5:00 e alle 10:00
trigger:
  - platform: time
    at: '05:00:00'
  - platform: time
    at: '10:00:00'
condition: []
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
        - switch.pe10_nooie_ah_ou_gui_cha_zuo_3_socket_1
        - switch.caricatore_letto_savernano_socket
mode: single
```

Dovrebbe partire alle 5:00 e alle 10:00 del mattino, ma sistematicamente funziona solo una volta al giorno. 

Questo alle 5:00:
![image](https://user-images.githubusercontent.com/103329141/177152168-989a1a3c-021f-4cbc-b34b-531f47351196.png)

Questo alle 10:00:
![image](https://user-images.githubusercontent.com/103329141/177152233-329f2e65-f14c-4ee1-9a7d-633988428f09.png)

Se tolgo uno dei due trigger, l'automazione sembra partire sempre senza problemi

Ho provato a cambiare orario e ad impostare l'accensione alle 5:00 e alle 10:01. La prima volta ha funzionato tutto correttamente
![image](https://user-images.githubusercontent.com/103329141/177154584-06860b13-78df-4665-8d53-01314d6b2c4c.png)

ma dal giorno seguente l'automazione parte sempre o alle 10:01 o alle 5:00 in modo apparentemente casuale:
![image](https://user-images.githubusercontent.com/103329141/177152883-c5e5436b-ede4-450d-8269-c5ce6e5d8062.png)
![image](https://user-images.githubusercontent.com/103329141/177152923-913d7810-e3d4-4e32-a389-0584444b9e29.png)

Idee su quale potrebbe essere la causa? Resto a disposizione in caso debba postare altri dati, grazie a chi vorrà provare a cercare una soluzione!

**Comment by cosimopan** [comment]
Cercando su internet, ho scoperto che probabilmente si tratta di un bug dell'integrazione Tuya-Smart Life. Ho notato che occasionalmente anche le altre automazioni che hanno le prese come action non funzionano, ma è molto meno evidente rispetto al caso qui riportato.

Ho risolto con una pezza poco elegante, ovvero ripetere l'action 3 volte a distanza di due minuti. La prima va quasi sempre a vuoto, mentre la seconda viene sempre eseguita e c'è comunque la terza per essere sicuri. Spero che il bug venga risolto in futuro perché è abbastanza fastidioso, ma spero così di non doverci più rimettere le mani per un po'

```
alias: Presa - Caricatore letto ON
description: Ogni giorno alle 5:00 e alle 10:00
trigger:
  - platform: time
    at: '05:00:00'
    enabled: true
  - platform: time
    at: '10:00:00'
condition: []
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
        - switch.pe10_nooie_ah_ou_gui_cha_zuo_3_socket_1
        - switch.caricatore_letto_savernano_socket
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
        - switch.pe10_nooie_ah_ou_gui_cha_zuo_3_socket_1
        - switch.caricatore_letto_savernano_socket
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
        - switch.pe10_nooie_ah_ou_gui_cha_zuo_3_socket_1
        - switch.caricatore_letto_savernano_socket
mode: single
```
