### DISCUSSION TITLE
Broadlink IR - acquisizione codici

### DISCUSSION THREAD

**Discussion by Jocman** [indomus/forum#1769] [HUB: Home Assistant]
Ciao a tutti.
Dopo aver combattuto con la configurazione del primo dei 4 attuatori IR della broadlink, sono passato finalmente all'acquisizione dei codici dei miei telecomandi, che ovviamente non sono già presenti in comunità....
Altrettanto ovviamente, il comodo programma Broadlink Manager non è utilizzabile ("Writing compatible device not detected!"), e quindi dovrei acquisire i codici direttamente dal servizio remote.learn_command.
Seguendo le varie guide (indomus in primis), credo di aver fatto tutto quello che serviva, quando invoco il comando mi viene restituita una spunta verde, quindi suppongo che il servizio abbia fatto il suo dovere.
Tuttavia dovrei trovare il file json relativo al servizio nella cartella .storage, peccato che questa cartella non esista assolutamente, non la riesco a vedere nè nel file manager di HA nè sotto windows tramite samba share.
Francamente non so come regolarmi adesso.
Attualmente ho installata la versione 2022.6.7.
Grazie a tutti per il supporto

**Comment by KC-inDomus** [comment]
quale guida stai seguendo?

**Reply by Jocman** [reply]
a dire il vero, seguo quelle di indomus
[https://indomus.it/guide/integrare-attuatori-a-infrarossi-radiofrequenza-broadlink-a-home-assistant/](https://indomus.it/guide/integrare-attuatori-a-infrarossi-radiofrequenza-broadlink-a-home-assistant/)
[https://indomus.it/guide/catturare-e-inviare-codici-infrarossi-radiofrequenza-tramite-broadlink-e-home-assistant/](https://indomus.it/guide/catturare-e-inviare-codici-infrarossi-radiofrequenza-tramite-broadlink-e-home-assistant/)
e questa per il fatto che Broadlink Manager non ne vuole sapere di funzionare:
[https://indomus.it/guide/gestire-telecomandi-virtuali-su-home-assistant-via-broadlink-parte-1/](https://indomus.it/guide/gestire-telecomandi-virtuali-su-home-assistant-via-broadlink-parte-1/)

Oltre a ciò gironzolando qua e là ritrovo guide (anche in inglese) che ricalcano quanto descritto da indomus.

**Reply by KC-inDomus** [reply]
L'ultima che hai citato - che è forse l'unica che ti serve realmente - non usa Broadlink Manager, leggila e applicala bene.

**Reply by Jocman** [reply]
é da ieri che la leggo e rileggo, e che controllo passo per passo, ma francamente non capisco dove sbaglio (perchè sicuramente sbaglio).
Tuttavia, mi viene da rilevare che se seguo pedissequamente la guida, il comando di evocazione del servizio non viene attivato:
```
service: remote.learn_command
device: Clima_LG
command: On_Off
alternative: true
timeout: 20
entity_id: remote.ir_batcave_remote
```
mentre se utilizzo l'interfaccia per creare il file yaml da utilizzare ottengo:
```
service: remote.learn_command
data:
  device: Clima_LG
  command: On_Off
  alternative: true
  timeout: 20
  command_type: ir
target:
  entity_id: remote.ir_batcave_remote
```
ed il comando di evocazione del servizio adesso risulta attivato.
Non è proprio la stessa cosa, e suppongo sia dovuto al fatto che la guida forse si riferisca a qualche versione precedente.
Ho provato anche a lanciare il servizio 
` remote.turn_on` come descritto dalla guida 
[https://indomus.it/guide/integrare-attuatori-a-infrarossi-radiofrequenza-broadlink-a-home-assistant/](url)
non si sa mai che per qualche motivo dovess essere spento...
In ogni caso, dopo aver evocato il servizio, premuto il pulsante sul telecomando e atteso il segno di spunta, nè quella cartella .storage nè ciò che vi dovrei trovare all'interno è presente.

**Reply by Jocman** [reply]
Ho risolto il problema dell'acquisizione codici installando Broadlink Manager tramite Pyton e accedendo tramite web browser alla sua interfaccia.
Sembra andare che una bellezza, registra e invia i comandi senza problemi.
Fino ad ora sto giocherellando con il primo Clima, un LG.
Poi sarà la volta di SmartItClimate.
E se tutto va bene, passerò ai Mitsubishi.

Riguardo la cartella .storage, stupidamente, essendo nascosta, ero convinto di aver impostato la visibilità, ma non era così.
Adesso la vedo.
Peccato però che al suo interno avrei dovuto trovare il file nel formato come da guida indomus

```
broadlink_remote_MAC_ADDRESS_codes

```
che invece non c'è....

**Reply by KC-inDomus** [reply]
non c'è perché non stai creando telecomandi virtuale - perché non stai leggendo la guida.

**Reply by auanasgheps** [reply]
Ciao, se può tornarti utile, ritengo che questo script sia il modo più rapido per catturare i codici, perché puoi farlo in sequenza. Questo script nasce per i comandi di un condizionatore, ma puoi scriverci quello che vuoi e digitarli in sequenza (ne parlo in #1786)

```yaml
sequence:
  - service: remote.learn_command
    target:
      entity_id: !entitàbroadlink
    data:
      device: !nomeapiacere
      command:
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
mode: single
alias: Learn Remote Commands
```
