### DISCUSSION TITLE
Come salvare le immagini inviate nelle notifiche

### DISCUSSION THREAD

**Discussion by avvalex** [indomus/forum#1771] [HUB: Home Assistant]
Buondì, qualcuno sa dirmi se è possibile trovare un modo per conservare gli snapshot che mi invio tramite notifica nel modo sotto descritto?
Il problema è che le immagini le vedo perfettamente nelle notifiche, ma non trovo alcun modo per tenerle in caso potessero servirmi. Appena le clicco mi aprono HA e le perdo.
Ho provato a inserirle in notifiche mail via SMTP, ma non ci sono riuscito.
Esiste un qualche modo per salvarle sul dispositivo che le riceve, che non sia Telegram? Qualche esperienza al riguardo, che non sia passare tramite camera.snapshot?
Grazie mille a tutti!!!

```
service: notify.mobile_xxxxx
data:
  message: Prova
  data:
    image: >-
      http://xxx.xxx.xxx.xxx:xxxx{{states.camera.xxxxxxxxxxxxxxxxxxx.attributes.entity_picture}}
```
