### DISCUSSION TITLE
Come spegnere un dispositivo dopo 12 ore a cavallo di due giorni

### DISCUSSION THREAD

**Discussion by roverix** [indomus/forum#1773] [HUB: Home Assistant]
Ciao a tutti, sono nuovo di GitHub e anche di domotica con Home Assistant ed avrei bisogno di un piccolo aiuto su un'automazione che sto cercando di creare.
L'automazione prevede che intervenendo sul pulsante di una presa wifi, un timer inizi a contare 12 ore e allo scadere delle 12 ore spenga la presa wifi.
L'automazione che ho creato fa quello che ho descritto, ma solo se le 12 ore sono nello stesso giorno.
Infatti se supero la mezzanotte con le 12 ore, lo spegnimento non avviene.
Dico la verità, ho il dubbio che al passaggio della mezzanotte qualcosa azzeri questo timer, ma non saprei cosa, se non HASSIO stesso.

Ho creato questa automazione, potete dirmi se è corretta oppure bisogna fare ciò che mi serve in un altro modo?

Ringrazio per eventuali risposte

```

alias: Avvia yogurtiera
description: ''
trigger:
  - platform: state
    entity_id:
      - switch.presa_volante
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
condition: []
action:
  - delay:
      hours: 12
      minutes: 0
      seconds: 0
      milliseconds: 0
   - type: turn_off
    device_id: 1e40fd140a1294365350cb0144601024
    entity_id: switch.presa_volante
    domain: switch
mode: single
```

**Comment by indomus** [comment]
corretta è corretta, magari leveremmo il `for:` che è abbastanza inutile, e imposteremmo `mode: restart` come modalità di esecuzione.

**Reply by roverix** [reply]
Ok, provo le modifiche che mi hai suggerito e vediamo se questa notte esegue l'azione.
Grazie mille!!

**Reply by 50494554524F** [reply]
```
trigger:
  - platform: state
    entity_id: switch.presa_volante
    to: 'on'
    for:
      hours: 12
action:
  - service: switch.turn_off
    target:
      entity_id: switch.presa_volante
mode: single
```
