### DISCUSSION TITLE
Automazione all'orario di tramonto con ritardo/anticipo variabile #RISOLTO

### DISCUSSION THREAD

**Discussion by cl-7k-01** [indomus/forum#1778] [HUB: Home Assistant]
Ciao a tutti,
sto tentando di creare una automazione che, ad un dato orario (orario di tramonto + un valore, in minuti, settabile dall'utente) compia una determinata azione (l'accensione di una linea di lampioncini in giardino..). In sostanza vorrei ritardare o anticipare l'accensione dei lampioncini sempre partendo dall'orario di tramonto.
Allo scopo ho creato un sensore che, a partire dall'orario di tramonto, sommi un "delta" preso da un input number. In interfaccia il sensore funziona correttamente e se lo visualizzo vedo l'orario esattamente come dovrebbe essere. Esempio: tramonto alle 21:04, input number settato su + 35, risultato correttamente visualizzato = 21:39.
Di seguito il sensore e l'automazione.
Dove sbaglio?

```
#SENSORE ORA TRAMONTO DELTA
- platform: template
  sensors:
    orario_tramonto_delta:
      value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_setting) + states.input_number.delta_minuti_accensione_lampioncini.state | int *60) | timestamp_custom("%H:%M:%S") }}'
```
```
#AUTOMAZIONE ACCENSIONE SERALE
alias: Accensione serale lampioncini giardino
description: ''
trigger:
  - platform: time
    at: sensor.orario_tramonto_delta
condition:
  - condition: state
    entity_id: input_boolean.attiva_accensione_al_tramonto_lampioncini
    state: 'on'
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.shelly_4pro_pm_relay_8
mode: single
```

**Comment by 50494554524F** [comment]
per trovare un problema comincia a togliere tutto e poi riaggiungi poco alla volta; togli la condition e prova ad inserire un orario come stringa...

**Reply by cl-7k-01** [reply]
Grazie per il suggerimento. Ho già fatto un tentativo in tal senso ma non riesco a capire dove sta il problema.
La condition non è inutile ne sbagliata, serve per far eseguire l'automazione solo nel caso quel determinato input boolean venga messo in ON.
La riprova è nel fatto che, al cambiare del trigger (con un input per es. date_time) tutto funziona come voluto.

**Reply by Larry-78** [reply]
Ciao mi interessa l'argomento perché qualche tempo fa volevo creare qualcosa del genere.
Secondo me il problema è nel trigger. Secondo la documentazione ufficiale Il  Time trigger accetta sensori soltanto se come attributo ci sia un device_class: timestamp , puoi leggere [qui](https://www.home-assistant.io/docs/automation/trigger#sensors-of-datetime-device-class). 
Volendo potresti utilizzare un template trigger, per esempio in questo modo

```yaml
#AUTOMAZIONE ACCENSIONE SERALE
alias: Accensione serale lampioncini giardino
description: ''
trigger:
  - platform: template
    value_template: '{{ states("sensor.time") == states("sensor.orario_tramonto_delta") }}'
condition:
  - condition: state
    entity_id: input_boolean.attiva_accensione_al_tramonto_lampioncini
    state: 'on'
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.shelly_4pro_pm_relay_8
mode: single
```
Per far si che gli orari coincidano e di conseguenza rendere il trigger True dovresti modificare il sensore eliminando i secondi, tanto sono superflui.

```yaml
#SENSORE ORA TRAMONTO DELTA
- platform: template
  sensors:
    orario_tramonto_delta:
      value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_setting) + states.input_number.delta_minuti_accensione_lampioncini.state | int *60) | timestamp_custom("%H:%M", False) }}'
```

**Reply by cl-7k-01** [reply]
Ciao e grazie per la risposta.
Ho fatto un po' di tentativi seguendo i tuoi accorgimenti ma senza risultato.
Ho tolto i secondi dal sensor, erano inutili e frutti dei mille tentativi per venirne a capo.
Mi permetto di approfittare di te e fare qualche domanda:
- il "sensor.time" usato nel trigger è un sensore di "sistema" o devo crearlo ad hoc?
- tu indichi, come trigger, la condizione "==", non sarebbe meglio usare un "maggiore o uguale" così facendo, la action partirebbe anche nel momento in cui sia già stata superata l'ora di trigger? (se per esempio in quel preciso minuto ho riavviato HA, il minuto successivo il trigger non è verificato e resterei senza illuminazione per tutta la notte..);
- nel sensor "orario_tramonto_delta", alla fine hai inserito un "False", che utilità ha? se lo inserisco mi da un orario totalmente diverso.. Ora, con un delta zero, l'orario di tramonto è effettivamente corretto  (ad oggi attorno alle 21.00), se inserisco quel False, mi viene sballato di qualche ora, quasi fosse legato ad una UTC diversa..
Grazie per l'attenzione.

**Reply by Larry-78** [reply]
Ciao di nulla. 
Risposta 1 
Si giusto, davo per scontato che lo avessi già integrato visto il tuo interesse ad automazioni con platform time. È semplice da integrare puoi leggere [qui](https://www.home-assistant.io/integrations/time_date/)
Risposta 2
Il mio era un suggerimento, ovviamente lo puoi modificare in base alle tue esigenze. Il discorso iniziale era puntato su come eventualmente modificare il trigger, poi a te la scelta su come procedere.
Risposta 3
Mi dispiace ma non ho avuto modo di testare il tuo sensor sulla mia istanza. Conoscendo lo stato del sensor.time che espone un'orario formato da ore e minuti e paragonandolo al tuo template sensor, ho notato che hai impostato la visualizzazione dei secondi con il timestamp_custom, quindi ho pensato fosse necessario eliminarli, ecco il motivo di quel False. Prova a rimettere la visualizzazione dei secondi e vedi cosa succede.

**Reply by cl-7k-01** [reply]
Mi hai risolto il problema. GRAZIE.
Seguendo le tue indicazioni ho ottenuto quello che volevo.
Ho escluso i minuti dal sensore "tramonto", come dicevi anche te, erano inutili e li avevo inseriti nei vari tentativi effettuati precedentemente, senza però usare il False, semplicemente non li ho inseriti nella formattazione.
Ho creato il sensore per l'ora esatta (ampliandolo a tutte le display option possibili per averli a disposizione un domani).
Ed infine ho usato entrambi nel trigger della mia automazione con un ">=" al posto del "==", per le ragioni di cui sopra.
Questo il sensore per l'ora esatta:
```
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'
```
Questo il sensore per l'ora di tramonto:
```
- platform: template
  sensors:
    orario_tramonto_delta:
      value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_setting) + states.input_number.delta_minuti_accensione_lampioncini.state | int *60) | timestamp_custom("%H:%M") }}'
```
ed infine l'automazione:
```
alias: Accensione serale lampioncini giardino al tramonto
description: ''
trigger:
  - platform: template
    value_template: '{{ states("sensor.time") >= states("sensor.orario_tramonto_delta") }}'
condition:
  - condition: state
    entity_id: input_boolean.attiva_tramonto_accensione_lampioncini
    state: 'on'
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.shelly_4pro_pm_relay_8
mode: single
```
Con gli stessi criteri ho creato un sensore analogo per l'alba e impostato una automazione per lo spegnimento dei lampioncini.
Senza riportare i codici (la logica è la stessa ma "invertita"), riporto il solo sensore per l'orario di alba:
```
- platform: template
  sensors:
    orario_alba_delta:
      value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_rising) + states.input_number.delta_minuti_spegnimento_lampioncini.state | int *60) | timestamp_custom("%H:%M") }}'
```
