### DISCUSSION TITLE
Spia Bagno Occupato

### DISCUSSION THREAD

**Discussion by marsal-75** [indomus/forum#178] [HUB: Home Assistant]
Ciao a tutti, dopo innumerevoli giorni passati a leggere le guide di indomus ed essere riuscito ad integrare abbastanza bene la domotica in molti aspetti di casa mia sono qui a scrivervi per chiedere consiglio a chi è più esperto di me.
Il problema forse sarà per qualcuno banale ma, per le mie capacità, non lo è affatto: accendere una spia esterna al bagno quando questo è occupato e spegnerla quando non lo è. I dispositivi che ho a disposizione sono: sensore aperto/chiuso sulla porta, sensore di movimento interno, switch luce, switch spia esterna.
Gli scogli a mio modesto avviso peggiori da superare sono:
1- Evitare che la spia "occupato" resti accesa quando si esce e si richiude la porta dietro di se.
2- Evitare che la spia "occupato" si spegnesse quando qualcuno resta seduto sul water per un po' senza muoversi troppo (tipo figlio adolescente con cellulare) 
Le automazioni che sto utilizzando adesso sono le seguenti:
```
- id: '1615450765396'
  alias: Bagno Occupato
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.movimento_bagno
    to: 'on'
  condition: []
  action:
  - wait_template: '{{ is_state(''binary_sensor.porta_bagno'', ''off'')
      }}'
    timeout: 00:00:30
    continue_on_timeout: 'false'
  - type: turn_on
    device_id: 032fadd51ec9ad98db2acbc77ad20ee9
    entity_id: switch.spia_bagno
    domain: switch
  mode: single
```
E
```
- id: '1615450697301'
  alias: Bagno Libero
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 244e4b9a7b4ec7bae652a5605366a465
    entity_id: binary_sensor.porta_bagno
    domain: binary_sensor
  - platform: state
    entity_id: binary_sensor.movimento_bagno
    to: 'off'
    for: 00:05:00
  condition:
  - condition: device
    type: is_on
    device_id: 032fadd51ec9ad98db2acbc77ad20ee9
    entity_id: switch.spia_bagno
    domain: switch
  action:
  - type: turn_off
    device_id: 032fadd51ec9ad98db2acbc77ad20ee9
    entity_id: switch.spia_bagno
    domain: switch
  mode: single
```
Consigli su come migliorarle? Grazie in anticipo
