### DISCUSSION TITLE
Resettare stato sensore di allagamento

### DISCUSSION THREAD

**Discussion by array81** [indomus/forum#1780] [GENERALE - Discussioni generiche]
Ho un sensore di allagamento acquistato su un famoso sito cinese. Ho provveduto ad installate Tasmota e l'ho configurato con 2 regole come suggerito si questo sito: https://templates.blakadder.com/Y09.html
La prima regola di fatto mi permette di conoscere lo stato (CHIUSO o APERTO) del contatto del sensore (e quindi se c'è acqua sul pavimento), mentre la seconda mi permette di conoscere lo stato della batteria.
Il sensore ha un comportamento estremamente semplice di defualt si trova in uno stato di "ibernazione" e quando l'acqua chiude il contatto viene risvegliato, si collega quindi alla rete e manda il topic relativo allo stato di allarme (CHIUSO). A quel punto il sensore si iberna nuovamente.

Il mio problema è che in questo modo su Home Assistant ottengo il passaggio dallo stato APERTO allo stato CHIUSO e quindi l'allarme ma poi lo stato del sensore su Home Assistant non torna più su APERTO perchè il sensore di allegamento invia solo il topic di allarme (ovvero CHIUSO).

Come posso risolvere il problema? A me basterebbe anche avere la possibilità una volta asciugato il pavimento di poter inviare un topic a Mosquitto relativo allo stato APERTO.

**Comment by snakuzzo** [comment]
Da quello che vedo su blakadder prevede stato sia aperto che chiuso e se imposti bene le RULE (indicate come Function), dovrebbe pubblicare entrambi gli stati

**Reply by array81** [reply]
In realtà no, nel senso che i sensore una volta riattivato dall'acqua rimane attivi circa 5 secondi dopo di che va il sleep. Se in quei 5 secondi lo si asciuga effettivamente manda anche anche lo stato APERTO, ma nel normale utilizzo, si la stanza si allaga lo stato non cambierà fino a quando qualcuno non asciuga il pavimento quindi nel frattempo il sensore sarà di nuovo in sleep. 
Ho risolto creando nella plancia una scheda pulsante con il seguente codice:

```
type: conditional
conditions:
  - entity: sensor.allagamento_lavanderia_stato
    state: CLOSED
card:
  type: button
  icon: mdi:water
  name: Sensore Allagamento Lavanderia
  tap_action:
    action: call-service
    service: mqtt.publish
    data:
      topic: stat/tasmota_0C43FE/STATUS
      qos: 1
      retain: false
      payload: OPEN
    target: {}
```
In questo modo il pulsante compare solo quando effettivamente avviene l'allagamento e ho la possibilità di resettare lo stato manualmente.
