### DISCUSSION TITLE
Codici climatizzatori Samsung AR**TXHZ*** (AR09TXHZAWKNEU, AR12TXHZAWKNEU ecc)

### DISCUSSION THREAD

**Discussion by auanasgheps** [indomus/forum#1786] [HUB: Home Assistant]
Ciao,
Da qualche giorno mi hanno installato i climatizzatori Samsung comprati da Mediaworld in promozione.
Non sono smart e purtroppo nessuno aveva già caricato i codici, quindi mi sono preso l'onere di catturare tutti i codici del telecomando. 

Gli articoli su [come domotizzazione il clima](https://indomus.it/progetti/domotizzare-un-condizionatore-tradizionale-con-broadlink-e-home-assistant-v2/) e sulla [cattura dei codici](https://indomus.it/guide/acquisire-codici-infrarossi-radiofrequenza-tramite-broadlink-e-home-assistant/) sono stati ESSENZIALi e vi ringrazio molto, ritengo però che il vostro archivio collaborativo non sia adatto a prodotti come questo, dove ogni prodotto richiede centinaia di codici.

Per questo motivo [ho fatto una pull request](https://github.com/smartHomeHub/SmartIR/pull/906) direttamente sulla repo Github di SmartIR, così il file è già pronto all'uso.

I modelli da me in possesso sono `AR09TXHZAWKNEU `e `AR12TXHZAWKNEU`, ma il manuale è per `AR**TXHZ***`, quindi ho citato questa nomenclatura. E visto che è ancora in offerta da Mediaworld, magari qualcuno di voi li ha presi :)

Segnalo anche un miglioramento per la guida. C'è un modo molto comodo per velocizzare la cattura dei codici, basta creare uno script così:

```yaml
sequence:
  - service: remote.learn_command
    target:
      entity_id: !entitàbroadlink
    data:
      device: !nomeapiacere
      command:
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
mode: single
alias: Learn Remote Commands
```

Avviando lo script, verranno richiesti i codici in sequenza e salvati in un file sotto `/config/storage.` Visto che per i climatizzatori queste operazioni vanno ripetute molte volte per svariate combinazioni, ritengo che attualmente sia il modo più rapido per prenderli. L'immissione richiede pochissimi secondi e il filefile è già formattato in json, quindi il risultato è copiabile nel file principale per smartir.
