### DISCUSSION TITLE
SmartIR - Entità Climate multiple # RISOLTO

### DISCUSSION THREAD

**Discussion by reiner348** [indomus/forum#1788] [HUB: Home Assistant]
Ciao a tutti! Dopo aver faticato per integrare 3 broadlink nel mio hub, volevo usarli per controllare i tre split del condizionatore.

Premetto che da un po' ero riuscito, tramite la guida "Domotizzare un climatizzatore tradizionale con Broadlink e Home Assistant (v2)" a integrare il primo e funziona perfettamente. Il problema è nato quando ho voluto creare le altre due entità climate... Non riesco a capire perchè ma non me li riconosce, è come se ci fosse un conflitto perchè a volte mi fa vedere quello della sala, a volte quello della camera e comunque non funzionano... Il codice è il seguente:
```
# Infrarossi
smartir:

climate:
  - platform: smartir
    name: Condizionatore_cameretta
    device_code: 1400
    controller_data: remote.broadlink_cameretta_remote
    temperature_sensor: sensor.broadlink_cameretta_temperature
    humidity_sensor: sensor.broadlink_cameretta_humidity
    power_sensor: binary_sensor.stato_accensione
climate:
  - platform: smartir
    name: Cond_cameretta
    unique_id: cond_cameretta
    device_code: 1400
    controller_data: remote.broadlink_cameretta_remote
    temperature_sensor: sensor.broadlink_cameretta_temperature
    humidity_sensor: sensor.broadlink_cameretta_humidity
    # power_sensor: binary_sensor.stato_accensione
climate:
  - platform: smartir
    name: Cond_camera
    unique_id: cond_camera
    device_code: 1400
    controller_data: remote.broadlink_camera_remote
    temperature_sensor: sensor.broadlink_camera_temperature
    humidity_sensor: sensor.broadlink_camera_humidity
    # power_sensor: binary_sensor.stato_accensione2
climate:
  - platform: smartir
    name: Cond_sala
    unique_id: cond_sala
    device_code: 1400
    controller_data: remote.broadlink_sala_remote
    temperature_sensor: sensor.sala_t
    humidity_sensor: sensor.sala_hum
    # power_sensor: binary_sensor.stato_accensione3
```
Il primo blocco, "Condizionatore_cameretta" è quello che, da solo, funziona. Se lo quoto e attivo gli altri tre, va in pappa e non funziona più niente...
Non riesco a capire dove sbaglio e purtroppo non ho trovato niente che spieghi come aggiungere più entità climate. Qualcuno che riesce a illuminarmi? E a rinfrescarmi casa 😄
