### DISCUSSION TITLE
Cover mqtt hanno smesso di funzionare

### DISCUSSION THREAD

**Discussion by Hypn0sis** [indomus/forum#1791] [HUB: Home Assistant]
Ciao, buongiorno a tutti. La mia integrazione MQTT con le tapparelle ha smesso di funzionare  (il widget ha pulsanti e status non available) dopo un aggiornamento di core. Ho provato anche a ripristinare un vecchio backup ma il problema non si risolve. Ho anche testato mqtt provando a mettermi in ascolto sui topic delle tapparelle che vengono pubblicati correttamente. Qualcuno ha qualche idea? Lo stato delle entities di tipo cover rimane sempre unavailable. Grazie in anticipo. Si tratta di dispositivi tasmotas configurati come segue: 

```
- platform: mqtt
  name: "Balcone"
  device_class: shade
  availability_topic: "tele/balcone/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  command_topic: "cmnd/balcone/Backlog"
  payload_open: "ShutterOpen1"
  payload_close: "ShutterClose1"
  payload_stop: "ShutterStop1"
  set_position_topic: 'cmnd/balcone/ShutterPosition1'
  position_topic: "stat/balcone/RESULT"
  position_open: 100
  position_closed: 0
  position_template: >
    {% if ('Shutter1' in value_json) and ('Position' in value_json.Shutter1) %}
      {{ value_json.Shutter1.Position }}
    {% else %}
      {% if is_state('cover.balcone', 'unknown') %}
        50
      {% else %}
        {{ state_attr('cover.balcone','current_position') }}
      {% endif %}
    {% endif %}  
  retain: false
  optimistic: false
  qos: 1
 
```

Aggiungo che ho fatto test mettendomi in ascolto sui topic delle telemetrie e i messaggi vengono pubblicati correttamente, sia con MQTT da home assistant, sia con MQTT Explorer.

Grazie per l'aiuto

**Comment by indomus** [comment]
https://indomus.it/news/hot-aggiornamento-2022-6-per-home-assistant-core/#mqtt

**Comment by Hypn0sis** [comment]
Pensavo di aver scongiurato la possibilità che fosse qualcosa del genere ripristinando un backup di metà giugno... Ci lavoro su e vedo se riesco a sistemare... Grazie

**Comment by Hypn0sis** [comment]
Sistemata la configurazione, ma ancora non va. Idee?

**Reply by KC-inDomus** [reply]
vedi i log, avrai sbagliato a migrarla

**Reply by snakuzzo** [reply]
@Hypn0sis mi pare di capire che hai un sonoff dual.
Io ne ho uno già pronto. Stasera lo rimetto in campo e vedo se c'è da adeguare qualcosa.
Ti faccio sapere.

P.S. Fai Reply sotto l'ultima risposta...non aprire sempre thread nuovi come hai fatto ora e con il messaggio precedente

**Reply by Hypn0sis** [reply]
RISOLTO tutto!! Grazie.
Ho utilizzato la nuova sintassi per mqtt reintegrando anche tutti gli altri device mqtt che avevo.
Non capisco però perchè abbia smesso di funzionare (se la vecchia sintassi sarà deprecata da settembre) anche ripristinando un backup del core di maggio... Curioso. Comunque grazie ancora per il supporto!

**Reply by snakuzzo** [reply]
bene...meglio così ;)

**Comment by wokhen** [comment]
Ciao a tutti,
intanto grazie per le vs guide.
Recentemente ho spostato la domotica (HA) su VM in Proxmox per implementare replication ed alta affidabilità.
Funziona tutto molto bene, ho solo un problema con gli scuri ed il broker.

Cosa ho installato:
- Impostazioni, Componenti aggiuntivi --> Mosquitto Broker (broker)
- Impostazioni, Dispositivi e Servizi --> Mosquitto Broker (qui compaiono i dispositivi caricati con zigbee2mqtt)
- Impostazioni, Dispositivi e Servizi --> Tasmota (qui compaiono i dispositivi tasmotati)
 
Ho molti dispositivi integrati con mqtt, come dicevo funzionano tutti tranne gli scuri che sono gestiti da un Sonoff Dual R2 con Tasmota v12.1.0:
![image](https://user-images.githubusercontent.com/53829124/185744085-0c19adc4-ddcb-40da-a32d-1603b246d983.png)

Entità create:
- l'integrazione Tasmota ha automaticamente identificato i Sonoff Dual, creandomi il dispositivo 'Scuro Cucina'. I dettagli del dispositivo mostrano 2 switch (switch.scuro_cucinagiu e switch.scuro_cucinasu): attivando questi switch la tapparella funziona.
![image](https://user-images.githubusercontent.com/53829124/185744224-590164d8-bf99-4054-b018-5aaf13528554.png)

- la configurazione con mqtt: invece ha creato le entità 'cover.scurocucina' e 'cover.scuropranzo':

```
cover:
   - name: "ScuroCucina"
     device_class: shade
     availability_topic: "tele/tasmota-2658/LWT"
     payload_available: "Online"
     payload_not_available: "Offline"
     command_topic: "cmnd/tasmota-2658/Backlog"
     payload_open: "ShutterOpen1"
     payload_close: "ShutterClose1"
     payload_stop: "ShutterStop1"
     set_position_topic: 'cmnd/tasmota-2658/ShutterPosition1'
     position_topic: "stat/tasmota-2658/RESULT"
     position_open: 100
     position_closed: 0
     position_template: >
       {% if ('Shutter1' in value_json) and ('Position' in value_json.Shutter1) %}
         {{ value_json.Shutter1.Position }}
       {% else %}
         {% if is_state('cover.scurocucina', 'unknown') %}
           50
         {% else %}
           {{ state_attr('cover.scurocucina','current_position') }}
         {% endif %}
       {% endif %}  
     retain: false
     optimistic: false
     qos: 1
```

Queste hanno correttamente generato il pannello degli scuri che però non fa muovere gli scuri:
![image](https://user-images.githubusercontent.com/53829124/185744312-eedad16a-376e-42c3-8850-af0509b1dcd9.png)


Il registro del broker non mi da alcuna info utile.


Prima utilizzavo la vecchia configurazione con 'platform: mqtt' che funzionava con il seguente template:

```
- platform: template
  covers:
    scuro_cucina_cover:
      friendly_name: "Scuro Cucina"
      position_template: "{{ (states.input_number.scuro_cucina_posizione.state | int) }}"
      open_cover:
        - service: mqtt.publish
          data:
            topic: 'cmnd/tasmota-2658/power2'
            payload: 'OFF'
        - service: mqtt.publish
          data:
            topic: 'cmnd/tasmota-2658/power1'
            payload: 'ON'
      close_cover:
        - service: mqtt.publish
          data:
            topic: 'cmnd/tasmota-2658/power1'
            payload: 'OFF'
        - service: mqtt.publish
          data:
            topic: 'cmnd/tasmota-2658/power2'
            payload: 'ON'
      stop_cover:
        - service: mqtt.publish
          data:
            topic: 'cmnd/tasmota-2658/power1'
            payload: 'OFF'
        - service: mqtt.publish
          data:
            topic: 'cmnd/tasmota-2658/power2'
            payload: 'OFF'
```

Se riuscite a darmi qualche suggerimento vi ringrazio.
Grazie

**Reply by snakuzzo** [reply]
Prima di tutto ti chiediamo di correggere i blocchi di codice utilizzando correttamente il markdown, così come hai scritto è un casino e non si capisce niente.
Per quanto riguarda il tuo discorso...

1. Per l'integrazione tasmota dovresti guardare la documentazione ufficiale [QUI](https://tasmota.github.io/docs/Blinds-and-Shutters/#operation)

2. Quanto alla configurazione dell'entità manuale, in attesa che tu sistemi la parte interessata con il markdown, dando per scontato che tu abbia seguito correttamente le ultime indicazioni per la definizione di entità MQTT, ti dico già che parti da un'osservazione sbagliata, perché dalla coda del broker e dai messaggi che passano puoi capire TUTTO.
Probabilmente hai sbagliato i command topic...per vedere quali sono quelli corretti puoi metterti in ascolto sulla coda del broker ed azionare da interfaccia tasmota i comandi su e giù per vedere cosa viene pubblicato.

**Reply by wokhen** [reply]
Provo a rivedere la coda del broker come hai suggerito, appena riesco do riscontro grazie

**Reply by wokhen** [reply]
Ciao,
ho aggiornato i markdowns nel post sopra.

Ho controllato la coda del broker, ho modificato la cover:  (ho cambiato il nome del topic in 'scurocucina'), in questo modo funziona solo il primo motore (Power1):

```
cover:
  - name: "Scuro_Cucina"
    device_class: shade
    availability_topic: "tele/scurocucina/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    command_topic: "cmnd/scurocucina/POWER"
    payload_open: "ON"
    payload_close: "OFF"
    payload_stop: "STOP"
    set_position_topic: 'cmnd/scurocucina/ShutterPosition1'
    position_topic: "stat/scurocucina/RESULT"
    position_open: 100
    position_closed: 0
    position_template: >
      {% if ('Shutter1' in value_json) and ('Position' in value_json.Shutter1) %}
        {{ value_json.Shutter1.Position }}
      {% else %}
        {% if is_state('cover.scuro_cucina', 'unknown') %}
          50
        {% else %}
          {{ state_attr('cover.scuro_cucina','current_position') }}
        {% endif %}
      {% endif %}  
    retain: false
    optimistic: false
    qos: 1
```

![image](https://user-images.githubusercontent.com/53829124/185801979-27be524a-b862-44c5-aff4-59043f83b357.png)

I messaggi POWER2 ON, POWER2 OFF e POWER1 OFF li ho dati direttamente dal pulsante del tasmota, il messaggio POWER1 ON è partito correttamente dalla cover:.

Visto che il sonoff dual utilizza 2 switch, come posso modificare lo script perchè tenga conto di entrambi e delle posizioni?
Grazie

**Reply by wokhen** [reply]
Quoto da:
https://tasmota.github.io/docs/MQTT/#examples

'For Sonoff Dual or Sonoff 4CH the relays need to be addressed with cmnd/tasmota/POWER<x>, where {x} is the relay number from 1 to 2 (Sonoff Dual) or from 1 to 4 (Sonoff 4CH). cmnd/tasmota/POWER4 off turns off the 4th relay on a Sonoff 4CH.'

quindi presumo di dover inserire 'cmnd/scurocucina/Power1' e 'cmnd/scurocucina/Power2' per gestire i 2 switch.

**Reply by snakuzzo** [reply]
Allora...se hai seguito correttamente la guida ufficiale che ti ho linkato l'altro giorno ([QUI](https://tasmota.github.io/docs/Blinds-and-Shutters/#operation)), la configurazione del Sonoff Dual R2 devi farla come indicato di seguito (è la mia configurazione del mio  Sonoff Dual R2) ...

Il topic è `tasmota-tappatest` e questo è il blocco YAML:

```yaml
mqtt:

  cover:

  - name: "test"
    availability_topic: "tele/tasmota-tappatest/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    command_topic: "cmnd/tasmota-tappatest/Backlog"
    payload_open: "ShutterOpen1"
    payload_close: "ShutterClose1"
    payload_stop: "ShutterStop1"
    set_position_topic: 'cmnd/tasmota-tappatest/ShutterPosition1'
    position_topic: "stat/tasmota-tappatest/RESULT"
    position_open: 100
    position_closed: 0
    position_template: >
      {% if ('Shutter1' in value_json) and ('Position' in value_json.Shutter1) %}
        {{ value_json.Shutter1.Position }}
      {% else %}
        {% if is_state('cover.test', 'unknown') %}
          50
        {% else %}
          {{ state_attr('cover.test','current_position') }}
        {% endif %}
      {% endif %}
    retain: false
    optimistic: false
    qos: 1
```
