### DISCUSSION TITLE
SmartIR - problemi con Climate

### DISCUSSION THREAD

**Discussion by Jocman** [indomus/forum#1793] [HUB: Home Assistant]
Ciao a tutti.
Dopo aver combattuto con l'integrazione dei Broadlink ed essere riuscito finalmente a registrare tutti i codici dei telecomandi dei miei 3 climatizzatori, mi sono cimentato con la creazione dei relativi file JSON (perchè ovviamente i miei climatizzatori non esistono in comunità...).
Al di là di problemi relativi alla sintassi JSON, e che per il momento non mi preoccupano (semmai ci tornerò in secondo momento), mi sto esaurendo un pò nel definire i controlli per i climatizzatori.
Mi spiego. Ho integrato il primo climatizzatore inserendo in config.yaml
```
#CONFIGURAZIONE SMART IR
smartir:

#Climatizzatore 1
climate:
    - platform: smartir
      name: Clima_Batcaverna
      unique_id: AC_BatCaverna
      device_code: 9000
      controller_data: remote.ir_batcave_remote
    #temperature_sensor: sensor.temperature
    #humidity_sensor: sensor.humidity
    #power_sensor: binary_sensor.stato_accensione
```
A parte qualche malfunzionamento dovuto a errori del file JSON, tuttavia il primo climatizzatore lo accendo e lo spengo; quindi c'è solo da lavorarci di fino. I 3 sensori sono remmati in quanto  non esistono fisicamente (per ora)
Dopo il primo, ho provato a integrare il secondo climatizzatore, per cui, unito al codice del primo climatizzatore, è diventato:
```
#CONFIGURAZIONE SMART IR
smartir:

#Climatizzatore Batcaverna
climate:
    - platform: smartir
      name: Clima_Batcaverna
      unique_id: AC_BatCaverna
      device_code: 9000
      controller_data: remote.ir_batcave_remote
    #temperature_sensor: sensor.temperature
    #humidity_sensor: sensor.humidity
    #power_sensor: binary_sensor.stato_accensione
      
#Climatizzatore Sala
    - platform: smartir
      name: Clima_Sala
      unique_id: AC_Sala
      device_code: 9002
      controller_data: remote.ir_fm_sala_remote
     #temperature_sensor: sensor.temperature
     #humidity_sensor: sensor.humidity
     #power_sensor: binary_sensor.stato_accensione  
```
Ed ecco che non va più: il secondo climatizzatore non esiste.
Sicuramente è un problema (a parte la mia ignoranza) dovuto ad errori nel file di configurazione.
Ma dove?
