### DISCUSSION TITLE
Automazione

### DISCUSSION THREAD

**Discussion by gideonklein** [indomus/forum#18] [HUB: Home Assistant]
Buonasera a tutti, ho creato un'automazione per ricaricare la batteria del tablet montato a muro con HA. Cioè ricaricare quando la batteria sta per scaricarsi togliere l'alimentazione quando si è caricato. Un'automazione che ho praticamente copiato (cambiando i sensori ovviamente). ma non funziona. Qualcuno può aiutarmi? Incollo i codici, entrambi purtroppo non funzionano:
```
- id: '1615489759840'
  alias: Batteria Tablet TEST
  description: TEST CARICA SCARICA BATTERIA Tablet
  trigger:
  - platform: numeric_state
    entity_id: sensor.gt_n8000_livello_della_batteria
    attribute: unit_of_measurement
    above: '1'
  condition: []
  action:
  - condition: numeric_state
    entity_id: sensor.gt_n8000_livello_della_batteria
    above: '86'
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.sonoff_100053b45e
  - condition: numeric_state
    entity_id: sensor.gt_n8000_livello_della_batteria
    below: '20'
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.sonoff_100053b45e
  mode: single
  max: 10
```

```
- alias: automazione ricarica_batteria
  trigger:
    platform: numeric_state
    entity_id: sensor.batteria
    above: 1
  action:
   - choose:
     - conditions:
         - condition: numeric_state
           entity_id: sensor.batteria
           above: 99
       sequence:
         - service: switch.turn_off
           data:
             entity_id: switch.presa_carica_batteria
     - conditions:
         - condition: numeric_state
           entity_id: sensor.batteria
           below: 20
       sequence:
         - service: switch.turn_on
           data:
             entity_id: switch.presa_carica_batteria
```

**Comment by Scialla** [comment]
la prima automazione, così com'é scritta, triggera quando la carica è superiore a 1 poi verifica se è superiore a 86 e, se si, spegne la presa, poi continua e verifica se è inferiore a 20 (e come può esserlo, per arrivare a quel punto è sicuramente superiore a 86)

Insomma mi sa che non hai le idee chiare...

la seconda automazione triggera di nuovo quando la carica è superiore a 1 per poi scegliere tra due condizioni, se superiore a 99 spegne, se inferiore a 20 accende, un casino insomma....

Tu devi mettere due trigger sul sensore di livello carica, uno se superiore a, ad esempio, 99, l'altro se inferiore, ad esempio, a 20, poi nella action usi dei template con una if ed else con controllo sullo stato del trigger, se superiore a 99 accende, se inferiore a 20 spegne.

La strada da seguire è questa, ora non sono nelle condizioni di postarti esempi, magari lo farà qualcun altro, oppure poi lo farò io, ma prova a ragionare sulla cosa, deve triggerare solo quando serve e non di continuo!

**Reply by gideonklein** [reply]
Grazie per la risposta. Purtroppo non sono in condizione di modificare nulla perchè mi sono avvicinato a HA da 2 settimane e non ho nessuna competenze in materia di codice. Ma posso dirti che le 2 automazioni, così come anche tu hai confermato, sono giuste. Cioè quando la batteria è carica (al 99% in un caso o 86% nell'altro) lo switch si spegne, viceversa si accende quando la batteria arriva sotto il 20%. Il principio è perfetto ma non funziona. O meglio se eseguo l'azione manualmente l'automazione funziona perfettamente (andando su automazioni e cliccando su ESEGUI AZIONI). Quindi credo che sia qualcosa che ha a che fare con la partenza dell'automazione che non va.
Le automazioni le ho provate ad una ad una e non assieme. Ed entrambi i codici non vanno bene

**Reply by gideonklein** [reply]
Considera pure che i codici li ho copiati pari pari

**Comment by Scialla** [comment]
Non hai capito cosa ho scritto... sono completamente sbagliate, per forza non funzionano. Dopo provo a postare un esempio di come dovrebbe essere

**Comment by Scialla** [comment]
Allora, visto che ne hai usata una con lo choose (che spero tu sappia cosa sia) te ne metto una che usa lo choose, ma si può anche fare con gli operatori if - elif - else

```yaml
  - alias: 'Automazione ricarica batteria'
    trigger:
      # L'automazione scatta se il livello di carica è inferiore al 20% per 2 min
      - platform: numeric_state
        entity_id: sensor.tuo_sensore_batteria
        below: 20
        for:
          minutes: 2
      # ...oppure se il livello di carica è superiore a 99% per 2 min    
      - platform: numeric_state
        entity_id: sensor.tuo_sensore_batteria
        above: 99
        for:
          minutes: 2
    action:
      - choose:
        - conditions:
          # se lo stato del trigger è < 20
          - condition: template
            value_template: "{{ trigger.to_state.state | float < 20 }}"
          sequence:
          # accende la presa per la ricarica
          - service: switch.turn_on
            data:
              entity_id: switch.tuo_switch_caricabatteria
        # in tutti gli altri casi, ovvero solo uno perché l'altro trigger è se > di 99
        default:
          # spegne la tua presa col caricabatteria
          - service: switch.turn_off
            data:
              entity_id: switch.tuo_switch_caricabatteria
```
Questa già dovrebbe funzionare bene, non l'ho testata ma dovrebbe andare, ovviamente devi cambiare le entità mettendo le tue, ti ho anche commentato tutto per farti capire cosa succede.
Poi c'è l'altra possibilità, peraltro molto simile, di fare la stessa automazione:
```yaml
  - alias: 'Automazione ricarica batteria'
    trigger:
      # L'automazione scatta se il livello di carica è inferiore al 20% per 2 min
      - platform: numeric_state
        entity_id: sensor.tuo_sensore_batteria
        below: 20
        for:
          minutes: 2
      # ...oppure se il livello di carica è superiore a 99% per 2 min    
      - platform: numeric_state
        entity_id: sensor.tuo_sensore_batteria
        above: 99
        for:
          minutes: 2
    action:
      - service: >
          {% if trigger.to_state.state | float < 20 %}
            switch.turn_on
          {% else %}
            switch.turn_off
          {% endif %}
        entity_id: switch.tuo_switch_caricabatteria
```
Anche questa non testata ma dovrebbe andare, usa quella che ti piace di più..

...e, come dice Diego, Pappa Pronta!!! :D :D :D

PS sempre per cercare di farti capire, quelle che hai postato tu si ATTIVANO quando la carica passa sopra a 1 e non quando vuoi tu, e poi funzionano ad cazzum
