### DISCUSSION TITLE
Sveglia fai da te

### DISCUSSION THREAD

**Discussion by dragorex71** [indomus/forum#182] [HUB: Home Assistant]
Salve a tutti, recentemente mi sono cimentato nel realizzare una sveglia con l'aiuto di HA ed Alexa.
Il mio sistema prevede appunto HA in versione HASSIO con integrata Alexa come custom component. Il progetto prevede che si possa impostare ora e giorno e poi HA innesca una routine in Alexa che riproduce determinati suoni impostati.
La sveglia deve essere flessibile quindi prevedere di poter essere impostata accesa/spenta singolarmente per ogni giorno della settimana e, per ciascun giorno, avere un orario personalizzato. Premetto che tutta la parte di interazione con Alexa funziona perfettamente e quindi non è oggetto del post, la pubblicherò se dovesse essere di interesse per qualcuno. Il problema è la logica di scelta: HA deve sapere che giorno è oggi (esempio LUN), verificare che la sveglia per LUN sia ATTIVA, vedere a che ora e poi, al momento giusto, attivare Alexa.
Ero arrivato a scrivere questo codice per la logica di scelta ma non ha funzionato:
```
- id: Sveglia_fede
  alias: Sveglia Federica
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.fh_lunedi.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.fh_martedi.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.fh_mercoledi.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.fh_giovedi.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.fh_venerdi.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.fh_sabato.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.fh_domenica.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: or
    conditions:
    - condition: template
      value_template: '{{ (now().strftime("%a") == "Mon") and (states.input_boolean.fede_lunedi.state=="on")}}'
    - condition: template
      value_template: '{{ (now().strftime("%a") == "Tue") and (states.input_boolean.fede_martedi.state=="on")}}'
    - condition: template
      value_template: '{{ (now().strftime("%a") == "Wed") and (states.input_boolean.fede_mercoledi.state=="on")}}'
    - condition: template
      value_template: '{{ (now().strftime("%a") == "Thu") and (states.input_boolean.fede_giovedi.state=="on")}}'
    - condition: template
      value_template: '{{ (now().strftime("%a") == "Fri") and (states.input_boolean.fede_venerdi.state=="on")}}'
    - condition: template
      value_template: '{{ (now().strftime("%a") == "Sat") and (states.input_boolean.fede_sabato.state=="on")}}'
    - condition: template
      value_template: '{{ (now().strftime("%a") == "Sun") and (states.input_boolean.fede_domenica.state=="on")}}'
  action:
  - service: script.sveglia_fede_script
  mode: single
```
Come vedete ci sono 7 input_datetime per impostare l'ora della sveglia, uno per ogni giorno della settimana, così come ci sono 7 input_boolean per decidere se attivare o no la sveglia il determinato giorno della settimana.
Il problema è che non fa le giuste scelte: così scritta il trigger si attiva quando l'ora attuale corrisponde ad un'ora presente in uno qualunque dei 7 giorni (anche se non è il giorno corrente) e le condizioni non condizionano niente :( ... basta che uno dei giorni della settimana sia attivato, anche se non è quello corrente. In pratica suonerà ad ognuna delle ore impostate nei sette input_datetime, ogni giorno della settimana a condizione che almeno uno degli input_boolean sia attivato.
Io non sono riuscito a fare di meglio e ho scelto una via molto poco elegante: ho scritto 7 automazioni, una per ogni giorno della settimana, che però moltiplicato per 3 diverse sveglie fanno 21 automazioni. Allego la versione del giovedì:
```
- id: Sveglia_fede_GIO
  alias: Sveglia Federica GIO
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.fh_giovedi.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: template
    value_template: '{{ (now().strftime("%a") == "Thu") and (states.input_boolean.fede_giovedi.state=="on")}}'
  action:
  - service: script.sveglia_fede_script
  mode: single
```
Qualcuno ha una idea più raffinata per raggiungere lo scopo?

**Comment by sky7176** [comment]
Ciao,
non sono esperto ma se nelle condizioni di verifica del giorno e del fatto che la sveglia sia attiva o meno ci metti anche la verifica dell'ora?

Giuseppe

**Comment by Larry-78** [comment]
Ciao
è interessante il tuo progetto ma utilizzerei un approccio diverso, utilizzerei quelle condizioni per realizzare un template binary_sensor, uno per ogni giorno della settimana in modo da ottenere per esempio un _binary_sensor.sveglia_lun "ON"_ se il giorno è quello giusto, se è in sincronia con l'orario impostato e se l'input_boolean è ON. In seguito ti basterà creare una singola automazione e come trigger metterai lo stato ON dei sensori creati così da poter eseguire il tuo script.

```yaml
binary_sensor:
  - platform: template
    sensor: 

      sveglia_lun:
        value_template: >-
           {{ states('sensor.time') == state_attr('input_datetime.fh_lunedi', 'timestamp') | int | timestamp_custom('%H:%M', False) and (now().strftime("%a") == "Mon") and (states.input_boolean.fede_lunedi.state=="on") }}

      sveglia_mar:
        value_template: >-
           {{ states('sensor.time') == state_attr('input_datetime.fh_martedi', 'timestamp') | int | timestamp_custom('%H:%M', False) and (now().strftime("%a") == "Tue") and (states.input_boolean.fede_martedi.state=="on") }}

      sveglia_mer:
        value_template: >-
           {{ states('sensor.time') == state_attr('input_datetime.fh_mercoledi', 'timestamp') | int | timestamp_custom('%H:%M', False) and (now().strftime("%a") == "Wed") and (states.input_boolean.fede_mercoledi.state=="on") }}

      sveglia_gio:
        value_template: >-
           {{ states('sensor.time') == state_attr('input_datetime.fh_giovedi', 'timestamp') | int | timestamp_custom('%H:%M', False) and (now().strftime("%a") == "Thu") and (states.input_boolean.fede_giovedi.state=="on") }}     

      sveglia_ven:
        value_template: >-
           {{ states('sensor.time') == state_attr('input_datetime.fh_venerdi', 'timestamp') | int | timestamp_custom('%H:%M', False) and (now().strftime("%a") == "Fri") and (states.input_boolean.fede_venerdi.state=="on") }}

      sveglia_sab:
        value_template: >-
           {{ states('sensor.time') == state_attr('input_datetime.fh_sabato', 'timestamp') | int | timestamp_custom('%H:%M', False) and (now().strftime("%a") == "Sat") and (states.input_boolean.fede_sabato.state=="on") }}

      sveglia_dom:
        value_template: >-
           {{ states('sensor.time') == state_attr('input_datetime.fh_domenica', 'timestamp') | int | timestamp_custom('%H:%M', False) and (now().strftime("%a") == "Sun") and (states.input_boolean.fede_domenica.state=="on") }}
```
Ho fatto dei test con un mio input_boolean e un input_datetime e funziona, dovresti prima verificare in Developer Tools/Template se i value_template ti restituiscono True/False provando a modificare orario e input_boolean ON/OFF.
Volendo potresti provare un'automazione di questo tipo

```yaml
- id: Sveglia_fede
  alias: Sveglia Federica
  trigger:
    - platform: state
      entity_id: 
         - binary_sensor.sveglia_lun
         - binary_sensor.sveglia_mar
         - binary_sensor.sveglia_mer
         - binary_sensor.sveglia_gio
         - binary_sensor.sveglia_ven
         - binary_sensor.sveglia_sab
         - binary_sensor.sveglia_dom
      to: "on" 
  action:
    - service: script.sveglia_fede_script
```
aggiornami e dimmi come va

**Comment by dragorex71** [comment]
Allora ragazzi, grazie per i suggerimenti, hanno avuto entrambi successo anche perchè entrambi si basano sul verificare contemporaneamente le tre condizioni (ora, giorno e attivazione del giorno).
Diciamo che nel caso della strada suggerita da @sky7176 è il caso di modificare il trigger: così com'è ha poco senso perchè parte quando trova un orario corrispondente a prescindere dal giorno ed è la verifica della condizione poi a correggere il tiro. Magari si può creare un trigger temporale: una volta al minuto.
Non so per il sistema se è meno dispendioso attivare una automazione ogni minuto o lasciargli verificare in tempo reale lo stato del binary_sensor; ma si parla di pettinare le bambole :)

**Reply by sky7176** [reply]
In ogni caso copio a mani basse HI
Giuseppe

**Reply by Larry-78** [reply]
@dragorex71 in fine quale strada adotterai? non mi è chiaro il ragionamento fatto nel tuo ultimo messaggio, cosa intendi per attivare un'automazione ogni minuto, verifica in tempo reale etc? e poi sarei curioso di sapere come hai gestito la parte Alexa, cosa hai fatto di bello?

**Reply by dragorex71** [reply]
Alla fine ho usato la tua soluzione ma tipo testa o croce.
Per attivare l'automazione ogni minuto intendevo che nell'altra soluzione, per quanto alla fine funzionasse, i trigger non erano molto validi; la soluzione sarebbe stata cambiare trigger ed usare un time pattern:
```
  trigger:
    - platform: time_pattern
      minutes: "/1"
```
con questo trigger l'automazione sarebbe partita ogni minuto e poi le condizioni gestivano tutto. 
La considerazione poi era: creo una automazione (in realtà 3 visto che gestisco tre sveglie) che h24 7/7 ogni minuto parte o uso il binary_sensor? Quale delle due è meno dispendiosa in termini di risorse del sistema? La risposta non la so ma mi è sembrata migliore l'ipotesi dei binary_sensor.
Per quanto riguarda Alexa segui queste istruzioni [https://github.com/custom-components/alexa_media_player/wiki#automation-routines](url). In pratica:

1. Crei la routine sulla app. (come trigger ho usato un comando vocale ma ovviamente poi non lo userai mai perchè verrà attivata da HA)
2. in customize.yaml inserisci il richiamo allo script
```
script.sveglia_fede_script:
  friendly_name: Sveglia F
```

3. crei lo script (io ho lo script.yaml e l'ho messo li)
```
sveglia_fede_script:
  sequence:
  - service: media_player.play_media
    data:
      media_content_id: SvegliaFede # SvegliaFede è il nome che avrai messo nell'app alla routine
      media_content_type: routine
    entity_id: media_player.echo_federica
  mode: single
```
4. richiamo lo script dall'automazione che abbiamo scritto insieme. Ovviamente la mia non si limita a far emettere suoni ad Alexa ma accende il comodino, ecc.

Ci sarebbe stata questa opzione [https://github.com/custom-components/alexa_media_player/wiki#triggering-a-skill](url) che sarebbe stata ancora più diretta perchè avrebbe attivato direttamente la skill da HA senza passare da una routine ma non ho capito come ottenere lo Skill-ID.
Ecco uno screen dell'interfaccia grafica, magari se avete suggerimenti per farla più carina ...

![Immagine](https://user-images.githubusercontent.com/57069335/115405775-d7381f80-a1ee-11eb-8781-05abce542b01.jpg)

**Reply by Larry-78** [reply]
ok è chiaro, alla fine non saprei nemmeno io quale è il migliore, ad ogni modo sono contento di sapere che funziona e la mia idea non era male. Ora ho capito che ti riferivi a Ruotine impostate su app Alexa e conoscevo quella guida così come le altre. Una cosa però non mi è chiara, perché utilizzare Routine per ​impostare suoni, accendere comodino etc, se puoi fare tutto con gli script di HA?
Cosa imposti con le Routine che con HA non puoi fare? Lo trovo più semplice creare uno script e richiamarlo direttamente dal servizio di HA. Per quanto riguarda l'interfaccia ho visto quelle che hai fatto ma io sono uno che preferisce le cose semplici e funzionali, mi sono limitato a modificare solo poche cose, se vuoi migliorare ti consiglio per esempio button-card che ti permette una personalizzazione molto ampia, per esempio puoi creare bottoni che possono cambiare lo stato delle tue entità e volendo cambiare anche il colore. L'ho utilizzato e ti garantisco che il risultato è ottimo.

**Reply by dragorex71** [reply]
Sono passato dalla routine perchè non so come fare su HA ad impostare la riproduzione di un determinato suono. Anche non fosse quello della skill che ho scelto ma un altro suono che potrei sempre trovare, come faccio a farglielo suonare?

**Reply by Larry-78** [reply]
sempre nel wiki del custom-component Alexa c'è play sounds
[https://github.com/custom-components/alexa_media_player/wiki#play-sounds](url)
ho provato gli esempi e funziona solo con alcuni suoni, questo perché c'è un avviso che dice di utilizzare i suoni all'interno di messaggi text-to-speech 
se invece fai così:

```yaml
service: notify.alexa_media
data:
  target: 
    - media_player.alexa
  data:
    type: tts
  message: <audio src="soundbank://soundlibrary/alarms/beeps_and_bloops/sirens_01"/>`
  ```
  ti basta sostituire il source code che trovi nell'elenco al posto di `message`, questo è l'esempio di una sirena ma ne trovi moltissimi suddivisi per categoria. Questo è il link della libreria 
https://developer.amazon.com/en-US/docs/alexa/custom-skills/ask-soundlibrary.html

**Reply by dragorex71** [reply]
Mi ero scordato! Lo avevo studiato tempo fa, prima che mi venisse l'esigenza della sveglia. Però mi sembra di ricordare che il catalogo dei suoni riproducibili era piuttosto scarso, come hai visto anche te.
Gli ridarò una occhiata, grazie

**Reply by Larry-78** [reply]
ho trovato un'alternativa, volendo si potrebbe caricare un mp3 personale, l'importante è che non superi i 240s l'unica cosa negativa e che è disponibile per 24h, almeno così ho capito. Collegandosi a questo sito
https://www.jovo.tech/audio-converter
è possibile caricare il file mp3, verrà convertito e verrà creato un URL da copiare e incollare in `message`.
Io avevo un file audio di un'ambulanza e ho provato e funziona
```yaml
service: notify.alexa_media_echo_show
data:
  message: "<audio src='https://www.jovo.tech/audio/Sr02Gbv8-ambulanza.mp3'/>"
  data:
    type: tts
  target: media_player.alexa_media_echo_show
  ```
