### DISCUSSION TITLE
Monitoraggio consumi pellet

### DISCUSSION THREAD

**Discussion by array81** [indomus/forum#1820] [HUB: Home Assistant]
Sto cercando di gestire il ritornamento della mia stufa pellet tramite Home Assistant. L'idea è semplice, vorrei tener traccia dei consumi. Ho quindi creato 2 counter, uno per avere i sacchi consumati durante tutta la stagione e l'altro i sacchi medi giornalieri. Ho quindi creato un sensore che mi permette di calcolare la media giornaliera dei sacchi consumati sulla base della data odierna e di una data di inizio stagione impostata tramite un input_datetime.
Ho quindi creato 3 pulsanti, uno resetta i dati per iniziare la nuova stagione, mentre gli altri 2 mi permettono di aggiungere/sottrarre i sacchi (il pulsante sottrai serve solo a correggere eventuali errori).

![pellet](https://user-images.githubusercontent.com/9898768/184108135-31901aa0-6a79-44fa-970b-b797bfe87a80.jpg)

La cosa sembra funzionare ma ho un paio di inconvenienti che mi piacerebbe risolvere.
Il primo inconveniente è che nonostante abbia impostato l'attributo minimum dei counter a 0, spingendo il pulsante sottrai posso avere valori del counter negativi. Il pulsante avvia uno script a cui sono associate 2 azioni di chiamata servizio Counter: Decrement per i 2 contatori (quello dei sacchi stagione e quello dei sacchi giornalieri).
Il secondo inconveniente riguarda invece un'automazione che alla mezzanotte resetta il contatore giornaliero e forza upgrade del sensore che calcola la media giornaliera (visto che è passato un giorno in più). Il sensore non aggiorna il suo valore che invece viene aggiornato (tramite trigger) quando cambia il valore del counter relativo ai sacchi stagione.

Qui il codice del sensore:

```
template
  - trigger:
    - platform: state
      entity_id: counter.stufa_numero_sacchi_stagione
      
    sensors:
      stufa_media_sacchi:
        friendly_name: Media sacchi pellet
        unique_id: stufa_media_sacchi
        value_template: "{{ (((states('counter.stufa_numero_sacchi_stagione')|int) / ((as_timestamp(now()) - states.input_datetime.stufa_data_inizio_stagione.attributes.timestamp|int)/86400)|int)|float|round(3))|abs }}"
```

qui quello dell'automazione
```
- id: '1660142439738'
  alias: Aggiornamento dati stufa
  description: Questa automazione resetta i sacchi giornalieri alla mezzanotte. Inoltre
    aggiorna il calcolo della media dei sacchi.
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: counter.reset
    data: {}
    target:
      entity_id: counter.stufa_numero_sacchi_giorno
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.stufa_media_sacchi
  mode: single
```

qui counter e input_datetime
```
input_datetime:
  stufa_data_inizio_stagione:
    name: Inizio stagione invernale
    has_date: true
    has_time: false
    
counter:
  stufa_numero_sacchi_stagione:
    name: Sacchi pellet stagione
    icon: 'mdi:bag-personal'
    initial: 0
    step: 1
    minimum: 0
  stufa_numero_sacchi_giorno:
    name: Sacchi pellet giornalieri
    icon: 'mdi:bag-personal'
    initial: 0
    step: 1
    minimum: 0
```

Qualcuno ha consigli da darmi?
