### DISCUSSION TITLE
Caddy non lavora!

### DISCUSSION THREAD

**Discussion by CesareDebian** [indomus/forum#1833] [HUB: Home Assistant]
Salve, ho questo problema:
non riesco ad accedere da remoto al mio homeassistant con https, ma solo con http.
Per capire gli errori commessi posterò sia il caddyfile che il configuration.yaml.
```
(https_header) {
  header {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}

https://xxxxxxxxxxxxxxxx.duckdns.org:9000 {
  import https_header
  reverse_proxy http:// ip server:8123
}
```

```
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
###################INCLUSIONI####################

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml
camera: !include camera.yaml
cover: !include cover.yaml
light: !include light.yaml
media_player: !include media_player.yaml

####################HTTP##########################
http:
   use_x_forwarded_for: true
   trusted_proxies:
     - 172.18.0.1
     - 172.18.0.0/16

config_editor:
    url: /hacsfiles/config-editor-card/config-editor-card.js
    type: module
```
```
"Name": "homeassistant_default",
        "Id": "c20ff78a1bc
  "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
```
```
"ConfigOnly": false,
        "Containers": {
            "1d9cd0640436e
"Name": "caddy",
                "EndpointID": "adf81706
"IPv4Address": "172.18.0.4/16",
```

**Comment by snakuzzo** [comment]
Premesso che non hai specificato il tipo di problema che hai, ma hai solo scritto che non riesci a collegarti...e questo NON basta, quello che devi verificare è:

1. corretta configurazione port forwarding sul router... per quello che hai scritto devi reindirizzare la porta 9000 verso la porta 9000 dell'ip del raspberry
2. una volta assicurato quanto descritto al punto 1, devi innanzi tutto utilizzare la configurazione di staging di let's encrypt (come indicato in guida ed assicurarti che il certificato "di prova" sia generato correttamente:

```
{
    acme_ca https://acme-staging-v02.api.letsencrypt.org/directory 
}
```

Solo dopo puoi rimuovere questo blocco e riavviare Caddy per la generazione del certificato corretto. Se parti direttamente senza il server di staging e fallisce per più di tot volte (mi pare 3 o 5), non potrai generare il certificato prima di qualche giorno se non ricordo male.

3. Assicurarti che la subnet che hai indicato tra i trusted proxy sia corretta (nella guida c'è scritto come fare)
4. Se hai attiva la configurazione ipv6 sul tuo server, potrebbe verificarsi che le chiamate dal reverse proxy verso HA arrivino con da `::1`. Se così fosse, lo vedresti nel log di home assistant e ti basterà aggiungerlo ai trusted proxy:

```
http:
   use_x_forwarded_for: true
   trusted_proxies:
     - '::1'
     # - 172.18.0.1   # questo non serve se hai specificato la subnet qui sotto
     - 172.18.0.0/16
```

**Reply by CesareDebian** [reply]
Ovviamente grazie anticipatamente.
Vorrei procedere per ordine, se sei d'accordo!
Il router lo configurato così:

<img width="693" alt="Schermata 2022-08-13 alle 23 43 15" src="https://user-images.githubusercontent.com/109909412/184511724-5ef8e9bc-9eea-4f58-bae9-2f97c936afd8.png">

Pensi che questo sia errato? Dovrei fare diversamente?

**Reply by snakuzzo** [reply]
Le immagini non vanno postate con markdown (ho corretto il tuo post).
Le regole sono ok. Quella di home assistant la puoi disattivare o eliminare...non ti serve se utilizzi il reverse proxy (Caddy)

**Reply by CesareDebian** [reply]
Se faccio così:
<img width="697" alt="Schermata 2022-08-13 alle 23 59 36" src="https://user-images.githubusercontent.com/109909412/184512069-de4c9672-ca13-4d8d-8be8-7f4684c8f2e5.png">

Non riesco a collegarmi in remoto neppure con http

**Reply by snakuzzo** [reply]
E NON devi collegarti in http da remoto. Se mi rispondi così vuol dire che non hai capito cosa stai facendo e a che serve tutto ciò

**Reply by CesareDebian** [reply]
Una volta inserito in caddyfile la seguente configurazione 
```{
    acme_ca https://acme-staging-v02.api.letsencrypt.org/directory 
}
```
ho lanciato il seguente comando:
```docker run --init -d --name="caddy" -e "TZ=Europe/Rome" -v /home/deb/caddy/Caddyfile:/etc/caddy/Caddyfile -v /home/deb/caddy/data:/data --restart always -p 443:443 -p 80:80 caddy:latest
```
ed ho avuto un errore:
```docker: Error response from daemon: Conflict. The container name "/caddy" is already in use by container "1d9cd0640436e82e3e etc etc  You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```
Lanciando il comando
```
docker run --help
```
ottengo una lista interminabile!!! Cosa faccio?

**Reply by CesareDebian** [reply]
Scusa, era per dirti che Il problema è proprio di Caddy.

**Reply by snakuzzo** [reply]
Il problema è tuo...non di caddy.
Non si capisce niente di cosa tu abbia fatto in base alle ultime cose che hai scritto

**Reply by CesareDebian** [reply]
Come mai non vedo cosa ho incollato? Ho sbagliato ad usare markdown? Devo scrivere senza?

**Reply by CesareDebian** [reply]
Mi dice che c'è un conflitto

**Reply by CesareDebian** [reply]
Scusa è possibile eliminare il container di caddy e instanziarlo ex novo?

**Reply by snakuzzo** [reply]
Fai troppe domande a caso :(
Dovresti prima capire come funziona docker...e questo non posso o devo insegnartelo io

Non puoi andare a caso

**Reply by snakuzzo** [reply]
Altro consiglio... Visto che ti trovi, usa docker-compose, dovrebbe semplificarti parecchio la vita

**Reply by CesareDebian** [reply]
Ho questa situazione:
```deb@debian:~$ cd /home/deb/caddy
deb@debian:~/caddy$ ls
Caddyfile  config  data
deb@debian:~/caddy$ ls -A
Caddyfile  config  data
deb@debian:~/caddy$ ls -a
.  ..  Caddyfile  config  data
deb@debian:~/caddy$ ls -ls
total 12
4 -rw-r--r-- 1 deb  deb   424 Aug 14 00:03 Caddyfile
4 drwxr-xr-x 3 root root 4096 Jul 16 13:29 config
4 drwxr-xr-x 3 deb  deb  4096 Aug 13 18:46 data
deb@debian:~/caddy$ cd config
deb@debian:~/caddy/config$ ls
caddy
deb@debian:~/caddy/config$ 
```
Vedo un caddy in config, è normale? 
Io sto seguendo la guida per mini-pc, ma penso di aver fatto confusione tra installare Caddy su Docker e Docker Compose.
A questo punto cosa mi consigli di fare, oltre a quello che non si può dire esplicitamente?

**Reply by CesareDebian** [reply]
Sto usando Docker-Compose

**Reply by snakuzzo** [reply]
Hai fatto casino con i file. Rifai tutto da capo

**Reply by snakuzzo** [reply]
Caddyfile dovrebbe stare sotto config

**Reply by snakuzzo** [reply]
Ma poi se non posti il docker-compose uno come fa a dirti se è corretto? Con la palla di vetro?
Comunque se ne riparla nei prossimi giorni...appena ho tempo.

**Reply by snakuzzo** [reply]
Ti faccio vedere come dovrebbe essere in base a quello che hai scritto.
Ammettiamo tu abbia il file `docker-compose.yaml` e la directory `caddy` sotto la tua home; e all'interno della directory `caddy` tu abbia le due directory `config` (con il `Caddyfile`) e `data` (dove andranno a finire i file dei certificati):

```
/home/<tuoutente>
├── docker-compose.yaml
├── caddy
│   ├── config
│   │   └── Caddyfile
│   └── data
└──log
```

In base a questa struttura il servizio di `Caddy` nel `docker-compose.yaml` dovrà essere questo...

```yaml
caddy:
  hostname: caddy
  image: caddy:latest
  container_name: caddy
  restart: always
  ports:
    - "80:80"    # Needed for HTTP-01 challenge (https://letsencrypt.org/docs/challenge-types/#http-01-challenge)
    #- "443:443"  # Needed for TLS-ALPN-01 challenge (https://letsencrypt.org/docs/challenge-types/#tls-alpn-01 challenge)
    - "9000:9000"
  environment:
    - "TZ=Europe/Rome"
  volumes:
    - "${HOME}/<tuoutente>/caddy/config/Caddyfile:/etc/caddy/Caddyfile"
    - "${HOME}/<tuoutente>/caddy/data:/data"
```

La prima volta, prima di creare ed avviare il container, dovrai usare il `Caddyfile` con il server di staging (attento alle parentesi graffe all'inizio che in quello che hai scritto ieri ne mancava una):

```
{
    acme_ca https://acme-staging-v02.api.letsencrypt.org/directory 
}

(https_header) {
  header {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}

https://<tuodominio>:9000 {
  import https_header
  reverse_proxy http://<ip_lan_server_homeassistant>:8123
}
```

Avvii il container...

```
docker-compose up caddy
```

il servizio in questo modo verrà avviato in foreground e dovrai vedere alla fine il messaggio 

```
certificate obtained successfully
```

Fatto questo dai `CTRL+C` ... il container si fermerà.

Modifica il `Caddyfile` "TOGLIENDO" la parte iniziale per il server di staging:

```
(https_header) {
  header {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}

https://<tuodominio>:9000 {
  import https_header
  reverse_proxy http://<ip_lan_server_homeassistant>:8123
}
```

Avvia il container (questa volta in background)

```
docker-compose up -d caddy
```

Guarda i log con il seguente comando...

```
docker logs -f caddy
```

e dovrai vedere lo stesso messaggio di prima...

```
certificate obtained successfully
```

**Reply by CesareDebian** [reply]
Buonasera,
Ovviamente grazie per la disponibilità!
ho dovuto eliminare tutto in quanto avevo fatto troppi sbagli!
Ho ottenuto quanto segue modificando Caddyfile:
```tls.obtain","msg":"certificate obtained successfully"
```
Attualmente riesco ad accedere in locale anche con questa configurazione:
<img width="692" alt="Schermata 2022-08-15 alle 22 32 32" src="https://user-images.githubusercontent.com/109909412/184713537-5dc18ce8-25ad-44f1-b65d-ad5bbc176821.png">
Cosa che non riuscivo a fare prima.
Purtroppo, ancora non riesco ad accedere in remoto con https.
Forse devo attendere visto gli errori fatti in precedenza?
Allego anche il docker-compose.yaml:
```
 caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/xxxx/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/xxxx/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    ports:
    - "80:80"
    - “443:443"
```
