### DISCUSSION TITLE
Asciugatrice Miele

### DISCUSSION THREAD

**Discussion by CesareDebian** [indomus/forum#1843] [HUB: Home Assistant]
Buonasera a tutti,
vorrei far rilevare ad Homeassistant Core la mia asciugatrice Miele.
Ho scaricato "Miele Integration" da HACS ed adesso devo inserire nel file di configurazione questo comando
```
miele:
    client_id: <your Miele ClientID>
    client_secret: <your Miele ClientSecret>
    lang: <optional. en=english, de=german>
    cache_path: <optional. where to store the cached access token>
```
Purtroppo non riesco a trovare il client_id, il client_secret e il cache_path. Ho provato, inutilmente, a mandare un'email alla Miele.
Devo resettare l'asciugatrice?
Inoltre, come potrei creare il file sidecar? Potrebbe andar bene questo:
```
# Asciugatrice
dryer: !include dryer.yaml
```
Fatemi sapere, grazie.
