### DISCUSSION TITLE
sensorRest per file json

### DISCUSSION THREAD

**Discussion by DigoGibin** [indomus/forum#1845] [HUB: Home Assistant]
Buongiorno , per la prima volta mi sto cimentando nella creazione di alcuni sensori su piattaforma rest  in un local web server e trovo alcune difficolta nel corretto utilizzo.
ho un sensore creato in questo modo:
```
  - platform: rest
    name: INIM scena attuale
    resource: "http://IP:PORTA/cgi-bin/web.cgi?mod=sce&par=now&user=***&pass=***&code=***"
    method: POST
```
se immetto il link del resource nel browser ho come risposta questa:
```
{"lb":"spento          ","id":"1"}
```
che è quella che mi aspetto e visualizzo correttamente nell'entita in home assistant

invece con un altro sensore 
```
  - platform: rest
     name: INIM zone
     resource: "http://IP:PORTA/cgi-bin/web.cgi?mod=zone&user=***&pass=***&code=***"
     method: POST
```
se immetto il link del resource nel browser ho come risposta questa:
```
{"zone":[{"lb":"PORTONE P.T.    ","tl":"0","st":"1","mm":"0","by":"1","id":"0"},{"lb":"PORTONE P.INT.  ","tl":"1","st":"1","mm":"0","by":"1","id":"1"},{"lb":"BASCULANTE      ","tl":"2","st":"1","mm":"0","by":"1","id":"2"},{"lb":"PORTA BOX       ","tl":"3","st":"1","mm":"0","by":"1","id":"3"},{"lb":"RADAR TAVERNA   ","tl":"4","st":"1","mm":"0","by":"1","id":"4"},{"lb":"OFF TOTALE      ","tl":"6","st":"1","mm":"0","by":"1","id":"7"},{"lb":"ON PERIMETRALE  ","tl":"7","st":"1","mm":"0","by":"1","id":"8"},{"lb":"FINESTRA CUCINA ","tl":"15","st":"2","mm":"0","by":"1","id":"15"},{"lb":"PERSIANA CUCINA ","tl":"16","st":"2","mm":"0","by":"1","id":"16"},{"lb":"FINESTRA CAM.MAT","tl":"17","st":"1","mm":"0","by":"1","id":"17"},{"lb":"PERSIANA CAM.MAT","tl":"18","st":"2","mm":"0","by":"1","id":"18"},{"lb":"FINESTRA BAGNO  ","tl":"19","st":"1","mm":"0","by":"1","id":"19"},{"lb":"PERSIANA BAGNO  ","tl":"20","st":"2","mm":"0","by":"1","id":"20"},{"lb":"FINESTRA CAMERET","tl":"21","st":"1","mm":"0","by":"1","id":"21"},{"lb":"PERSIANA CAMERET","tl":"22","st":"2","mm":"0","by":"1","id":"22"},{"lb":"FINESTRA SALA   ","tl":"23","st":"1","mm":"0","by":"1","id":"23"},{"lb":"PERSIANA SALA   ","tl":"24","st":"2","mm":"0","by":"1","id":"24"},{"lb":"RADAR SALA      ","tl":"45","st":"1","mm":"0","by":"1","id":"110"}]}
```
ma purtroppo in home assistant non viene visualizzato.
Immagino sia dovuto alla conformazione del file JSON ma in questo campo sono una frana e anche leggendo la documentazione non riesco a venirne a capo, anche perchè avrei bisogno di estrapolare delle informazioni da questo file per provare a creare altri sensori dedicati.

Fiducioso di un vostro aiuto vi ringrazio anticipatamente.

**Comment by snakuzzo** [comment]
Devi usare i template per estrarre il valore che ti interessa, non solo nel secondo caso, ma anche nel primo.
Avere un sensore che ti restitusca un JSON del genere non ha alcun senso. Oltre a questo va considerato che il valore di un sensore rest non può superare i 255 caratteri, come indicato sulla [documentazione ufficiale](https://www.home-assistant.io/integrations/sensor.rest/) e come ti evidenzio di seguito per comodità...
Se proprio vuoi "buttare" quel JSON in un sensore, devi metterlo in un attributo, non nel `value`.

![ccc](https://user-images.githubusercontent.com/7205371/185402664-6b8a2b59-ae88-453c-9a4d-60dd523912db.png)

Ad ogni modo, per quanto riguarda il primo sensore, ammesso che tu voglia valorizzarlo con il valore di `lb`, andrebbe scritto in questo modo: 

```yaml
- platform: rest
  name: stato_attuale 
  resource: "http://IP:PORTA/cgi-bin/web.cgi?mod=sce&par=now&user=***&pass=***&code=***"
  method: POST
  value_template: "{{ value_json.lb | trim }}"
```

![aaa](https://user-images.githubusercontent.com/7205371/185400285-53fe77fb-040e-4117-abc1-a1173e6e5224.png)

Nel secondo caso invece, immagino tu abbia necessità di creare N sensori diversi, visto che in quel JSON per la zona sono presenti porte, basculanti, persiane, etc.
Ammettiamo tu voglia un sensore per la finestra della cucina con il valore uguale a quello del rispettivo `tl`...
visto che non hai un id che identifichi quel "blocco", dovrai recuperarlo in maniera posizionale. Visto che la cucina è l'ottavo elemento e visto che si parte da zero, scriverai così...

```yaml
- platform: rest
  name: stato_tl_finestra_cucina
  resource: "http://IP:PORTA/cgi-bin/web.cgi?mod=zone&user=***&pass=***&code=***"
  method: POST
  value_template: "{{ value_json['zone'][7].tl }}"
```
![bbb](https://user-images.githubusercontent.com/7205371/185401873-1946f205-8b8d-484d-98ce-dc15250d2de0.png)

**Reply by snakuzzo** [reply]
Se poi vuoi metterlo tutto in un sensore, devi fare come ho scritto poco fa. Inserirlo come attributo...e come valori imposti qualcosa "a piacere"...

```yaml
- platform: rest
  name: stato_tl_finestra_cucina
  resource: "http://IP:PORTA/cgi-bin/web.cgi?mod=zone&user=***&pass=***&code=***"
  method: POST
  value_template: "zone"
  json_attributes:
    - zone
```

e a quel punto creerai N sensor template dove ognuno prenderà il proprio valore dall'attributo di questo sensore. In questo modo con una sola request valorizzi N sensori. Se invece fai N sensori rest, per ognuno di essi avrai una request (meno performante sicuramente)...

**Comment by DigoGibin** [comment]
Ciao Diego, grazie per l'aiuto.
Sono riuscito a visualizzare il primo sensore come volevo per il secondo ho seguito i tuoi consigli ed ho fatto cosi:
```
rest:
  - scan_interval: 5
    resource: "http://IP:PORTA/cgi-bin/web.cgi?mod=zone&user=***&pass=***&code=***"
    sensor:
      - name: "PORTONE P T"
        #        value_template: "{{ value_json['zone'][0].st }}"
        value_template: >
          {% if value_json['zone'][0].st == "1" %}
            Chiusa
          {% else %}
            Aperta
          {% endif %}
      - name: "PORTONE P INT"
        value_template: "{{ value_json['zone'][1].st }}"
      - name: "BASCULANTE"
        value_template: "{{ value_json['zone'][2].st }}"
      - name: "PORTA BOX"
        value_template: "{{ value_json['zone'][3].st }}"
      - name: "RADAR TAVERNA"
        value_template: "{{ value_json['zone'][8].st }}"
      - name: "FINESTRA CUCINA"
        value_template: "{{ value_json['zone'][15].st }}"
      - name: "PERSIANA CUCINA"
        value_template: "{{ value_json['zone'][16].st }}"
      - name: "FINESTRA CAM MAT"
        value_template: "{{ value_json['zone'][17].st }}"
      - name: "PERSIANA CAM MAT"
        value_template: "{{ value_json['zone'][18].st }}"
      - name: "FINESTRA BAGNO"
        value_template: "{{ value_json['zone'][19].st }}"
      - name: "PERSIANA BAGNO"
        value_template: "{{ value_json['zone'][20].st }}"
      - name: "FINESTRA CAMERET"
        value_template: "{{ value_json['zone'][21].st }}"
      - name: "PERSIANA CAMERET"
        value_template: "{{ value_json['zone'][22].st }}"
      - name: "FINESTRA SALA"
        value_template: "{{ value_json['zone'][23].st }}"
      - name: "PERSIANA SALA"
        value_template: "{{ value_json['zone'][24].st }}"
      - name: "RADAR SALA"
        value_template: "{{ value_json['zone'][110].st }}"
```
ho provato anche a personalizzarne uno per capire se fosse fattibile. 


grazie ancora per le dritte

**Reply by hexesoft-stefano-rossi** [reply]
Io ho provato a inserire questo codice nel mio configuration.yaml, ma leggendo i vostri commenti volevo sapere se lo posso migliorare con una sola lettura invece di leggerlo per ogni sensore.  La mia centrale Inim Prime PR500 ma lo stato che restituisce è uguale al vostro tracciato. Grazie

```
rest:
  - resource: https://192.168.20.34/cgi-bin/api.cgi?apikey=524c136ca-bac5-4e13-ab95-44327242426340&cmd=get_zones_status
    scan_interval: 10
    binary_sensor:
    
      - name: "EC sirena tetto"
        device_class: motion
        value_template: >-
          {% if (value_json.Data.zone[0].st | int) > 1 %}
            on
          {% else %}
            off
          {% endif %}
      - name: "ER ponte nord"
        device_class: motion
        value_template: >-
          {% if (value_json.Data.zone[1].st | int) > 1 %}
            on
          {% else %}
            off
          {% endif %}
      - name: "ER ponte sud"
        device_class: motion
        value_template: >-
          {% if (value_json.Data.zone[2].st | int) > 1 %}
            on
          {% else %}
            off
          {% endif %}
```

**Reply by snakuzzo** [reply]
1. DEVI USARE IL MARKDOWN QUANDO POSTI IL CODICE!!!! NON SO QUANTE VOLTE L'ABBIAMO RIPETUTO!!!!!!!! Non si capisce un cavolo così !!!!
2. Se magari posti il contenuto del JSON si riesce a darti una risposta migliore.

**Reply by hexesoft-stefano-rossi** [reply]
hai ragione ma è tutto nuovo per me 
**_ALLEGATO RIMOSSO_**

**Reply by hexesoft-stefano-rossi** [reply]
credo che dovrei scrivere anche un controllo che la centrale sia raggiungibile e risponde ancora alle mie richieste. Ho notato infatti che se provo a interrogarla ogni 5 secondi lei non risponde più e si blocca anche HA

**Reply by snakuzzo** [reply]
> hai ragione ma è tutto nuovo per me [inim.txt](https://github.com/indomus/forum/files/14236696/inim.txt)

Non ti ho detto di allegare un file, ma di postare usando il markdown. Leggi [QUI](https://github.com/indomus/forum/discussions/1311)
Il fatto che per te sia tutto nuovo, non giustifica il fatto di fare le cose male.

**Reply by snakuzzo** [reply]
Qui devi scegliere...per evitare di fare 1 request verso la centralina per ogni sensore le strade sono diverse...

1. Puoi fare una sola request salvando in locale il JSON di risposta (e sovrascrivendolo ogni volta) e poi facendo le entità diverse puntando al file json locale
2. Fare un solo sensore con il JSON di risposta da posizionare come attributo di un'entità di tipo REST sensor (non lo stato, perché il contenuto sarebbe troppo grande e sopra i 255 caratteri ti darebbe errore, mentre inserirlo come attributo no). Da questo sensore poi, generi n template sensor sulla base degli attributi del sensore con cui recuperi lo stato dalla centralina

**Reply by hexesoft-stefano-rossi** [reply]
Se hai i due esempi riesco a seguirti meglio
grazie

**Reply by snakuzzo** [reply]
Ti faccio direttamente l'esempio al punto 2...per il punto 1 ci puoi arrivare benissimo da solo

In base al JSON restituito dalla tua request (che è questo)...

```json
{
   "Status":0,
   "Data":{
      "zone":[
         {
            "lb":"EC SirenaTetto  ",
            "tl":"0",
            "st":"1",
            "mm":"0",
            "by":"1",
            "id":"0"
         },
         {
            "lb":"ER-PonteNord    ",
            "tl":"2",
            "st":"1",
            "mm":"0",
            "by":"1",
            "id":"2"
         },
         {
            "lb":"ER-PonteSud     ",
            "tl":"1007",
            "st":"1",
            "mm":"0",
            "by":"1",
            "id":"1007"
         },
         {
            "lb":"1R-PonteNord    ",
            "tl":"3",
            "st":"1",
            "mm":"0",
            "by":"1",
            "id":"3"
         },
         {
            "lb":"1R-PonteSud     ",
            "tl":"1008",
            "st":"1",
            "mm":"0",
            "by":"1",
            "id":"1008"
         }
      ]
   }
}
```

Innanzi tutto definisci un sensore Rest che avrà come stato `Status` e come unico attributo tutto il `Data` della response

```yaml
sensor:

  - platform: rest
    name: test_json
    json_attributes_path: "$.Data"
    json_attributes:
      - zone
    resource: https://tuaurl
    value_template: "{{ value_json.Status }}"
```

E dai qui poi, puoi fare "n" sensor di tipo template per recuperare dagli attributi del sensore Rest tutto quello che ti pare. Ad esempio te ne riporto solo uno, poi gli altri li puoi fare da te cambiando l'indice (1,2,3,etc) ...

```yaml
template:

    sensor:

      - name: "EC SirenaTetto"
        state: "{{ state_attr('sensor.test_json','zone')[0].tl }}"
        attributes:
          id: "{{ state_attr('sensor.test_json','zone')[0].id }}"
          st: "{{ state_attr('sensor.test_json','zone')[0].st }}"
          mm: "{{ state_attr('sensor.test_json','zone')[0].mm }}"
          by: "{{ state_attr('sensor.test_json','zone')[0].by }}"
```

Il risultato su HA...

il sensore Rest (non fare caso a come vedi gli attributi, è solo una questione di visualizzazione su lovelace, ma se guardi nel dettaglio sotto dev tools vedrai che è un JSON)...

![image](https://github.com/indomus/forum/assets/7205371/797bf62d-30e8-43fa-91ce-30a0d6d380c1)

questo invece il sensor template legato al sensore Rest...

![image](https://github.com/indomus/forum/assets/7205371/e02773df-1f69-489c-bf4b-34d229a26907)

P.S. Ovviamente a te il compito di modificare la tipologia di sensori e gli stati in base al significato di quella roba che c'è nel json

**Comment by hexesoft-stefano-rossi** [comment]
Grazie Diego, ho provato questo codice. Funziona. C'è modo di usare un loop o un ciclo for per creare in automatico 150 sensori senza inserirli uno ad uno ? nel mio esempio il numero 105 si può sostituire per esempio con un indice X che va da 0 a 150 ? 

```YAML
sensor:
  - platform: rest
    name: CentraleInim 
    json_attributes_path: "$.Data"
    json_attributes:
      - zone
    resource: http://192.168.10.39/cgi-bin/api.cgi?apikey=1xxxxxxxxxxxxxd&cmd=get_zones_status
    scan_interval: 10
    value_template: "{{ value_json.Status }}"

template:
    sensor: 
      - name: "{{ state_attr('sensor.CentraleInim','zone')[105].lb }}"
        state: >
          {% if state_attr('sensor.CentraleInim','zone')[105].st | float > 1 %}
            True
          {% else %}
            False
          {% endif %}
```
