### DISCUSSION TITLE
Gestione tariffe energia

### DISCUSSION THREAD

**Discussion by Robyxxx** [indomus/forum#1850] [GENERALE - Discussioni generiche]
Ho trovato un ottimo articolo che spiega come gestire la contabilizzazione delle tariffe dell'energia elettrica (F1, F2 e F3)
https://indomus.it/progetti/configurare-dei-contabilizzatori-di-consumo-energetico-su-home-assistant-v2/
Tuttavia la tariffa F3 vale così come per le domeniche anche per i giorni festivi. Come sarebbe possibile aggiungere questa correzione all'automazione presentata nell'articolo? Avete qualche suggerimento? Ho visto che c'è qualcosa qui (https://www.home-assistant.io/integrations/workday/) ma non saprei come integrarlo...

**Comment by westminzer** [comment]
Ciao questo è il mio primo messaggio. Sono davvero approdato da pochissimo nel mondo home assistant e nelle mie ricerche trovai proprio la guida per il contatore a fasce e sono riuscito a integrarlo con i festivi... sembra funzionare, visto che oggi, 1° Novembre i conteggi sono rimasti in F3 anziché essere passati in F2 e poi in F1.

Il concetto è che, nell'automazione presente qui: [https://indomus.it/progetti/configurare-dei-contabilizzatori-di-consumo-energetico-su-home-assistant-v2/](url), ai trigger 7, 8 e 19 andava aggiunta la condizione  non solo di ora e giorno della settimana ma anche che quel giorno fosse **lavorativo**, con operatore AND.

Ciò premesso, prima bisogna abilitare e configurare il sensore binario dove sia in stato ON per tutti i giorni feriali dal Lun al Sab incluso, mentre sia OFF per Dom e festivi. il risultato qui sotto:
```
binary_sensor:
  - platform: workday
    country: IT
    workdays: [mon, tue, wed, thu, fri, sat]
    excludes: [sun, holiday]
```
Risultato come segue:
![image](https://user-images.githubusercontent.com/116517282/199238563-5e28eb5f-0ec3-4eb0-bf09-5da834a4b33e.png)

Il 30/10 era domenica, il 31/10 Lunedì e il 1° Nov è Martedi, e non risulta, giustamente, _"lavorativo"_

L'implementazione con l'automazione dei contabilizzatori risulta come segue:

```
automation:
  - alias: "Tariffe energetiche"
    id: "tariffe_energetiche"
    initial_state: true
    trigger:
      - platform: time
        id: "7"
        at: '7:00:00'
        variables:
          tariff: "F2"
      - platform: time
        id: "8"
        at: '8:00:00'
        variables:
          tariff: "F1"
      - platform: time
        id: "19"
        at: '19:00:00'
        variables:
          tariff: "F2"
      - platform: time
        id: "23"
        at: '23:00:00'
        variables:
          tariff: "F3"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "7"
	      - condition: and
	        conditions:
	          - condition: state
		    entity_id: binary_sensor.workday_sensor
		    state: "on"
            sequence:
              - condition: time
                weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
                - sat
              - service: select.select_option
                target:
                  entity_id: select.montly_energy
                data:
                  option: "{{ tariff }}"
          - conditions:
              - condition: trigger
                id: "8"
		- condition: and
		  conditions:
		    - condition: state
		      entity_id: binary_sensor.workday_sensor
		      state: "on"				
            sequence:
              - condition: time
                weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
              - service: select.select_option
                target:
                  entity_id: select.montly_energy
                data:
                  option: "{{ tariff }}"
          - conditions:
              - condition: trigger
                id: "19"
	      - condition: and
	        conditions:
	          - condition: state
		    entity_id: binary_sensor.workday_sensor
		    state: "on"
            sequence:
              - condition: time
                weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
              - service: select.select_option
                target:
                  entity_id: select.montly_energy
                data:
                  option: "{{ tariff }}"
          - conditions:
              - condition: trigger
                id: "23"
            sequence:
              - service: select.select_option
                target:
                  entity_id: select.montly_energy
                data:
                  option: "{{ tariff }}"
```
il risultato finale è il seguente:
![image](https://user-images.githubusercontent.com/116517282/199243789-a83a12d0-97c2-465e-ac0f-c79271ad9f8b.png)

Visto che sono un pivello, spero sia tutto chiaro e di non aver fatto errori con i copia e incolla.
Spero sia di aiuto
Ciao

**Comment by Robyxxx** [comment]
Grazie mille per le indicazioni. Il binary sensor che indica i giorni festivi funziona correttamente, ma sulla porzione di codice aggiunta al codice tratto da indomus, non funzione. Mi restituisce un errore di sintassi. LA parte incriminata è quella in rosso


![Clipboard01](https://user-images.githubusercontent.com/87856265/199280450-8bff6527-bf58-441d-94f5-fee11a1437e1.jpg)

**Comment by westminzer** [comment]
Ciao, ho ricontrollato e deve essere un problema di indentazione: da quel che ho letto il codice in yaml deve seguire una indentazione rigorosa con un rientro di due spazi. Ora il codice è ordinato nel modo corretto e dovrebbe funzionare, puoi riprovare.

Io su HA, la parte incriminata, la vedo così:

![image](https://user-images.githubusercontent.com/116517282/199324179-f6c84d5e-0356-4505-97d7-775a0f620e13.png)

**Reply by Robyxxx** [reply]
Così sembra funzionare. Vedremo il primo giorno festivo che dovrebbe essere l'8 dicembre ;-)
Grazie comunque!

**Comment by Stomodine** [comment]
ciao

ho inserito l'automazione ma non sembra funzionare; forse perchè non è "retroattiva"?
![tariffa](https://user-images.githubusercontent.com/96614159/199604891-83a9702c-78a6-4a74-95ec-d9d02c904cb7.PNG)

**Comment by Robyxxx** [comment]
sì certo non è retroattiva.

**Reply by Stomodine** [reply]
ok,resta comunque il problema che non sta funzionando visto che alle 22,57 non dovrebbe essere in F1

![tariffa](https://user-images.githubusercontent.com/96614159/199610320-81b8305e-4a18-4825-80e6-dc1b47438c67.PNG)

**Comment by Stomodine** [comment]
per vostra info ho dovuto inserire l'AND prima del trigger altrimenti non c'era modo di farlo digerire

```
automation tariffes:
  - alias: "Tariffe energetiche"
    id: "tariffe_energetiche"
    initial_state: true
    trigger:
      - platform: time
        id: "7"
        at: '7:00:00'
        variables:
          tariff: "F2"
      - platform: time
        id: "8"
        at: '8:00:00'
        variables:
          tariff: "F1"
      - platform: time
        id: "19"
        at: '19:00:00'
        variables:
          tariff: "F2"
      - platform: time
        id: "23"
        at: '23:00:00'
        variables:
          tariff: "F3"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: "7"
                  - condition: state
                    entity_id: binary_sensor.workday_sensor
                    state: "on"
            sequence:
              - condition: time
                weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
                - sat
              - service: select.select_option
                target:
                  entity_id: select.home_monthly_energy
                data:
                  option: "{{ tariff }}"
          - conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: "8"
                  - condition: state
                    entity_id: binary_sensor.workday_sensor
                    state: "on"
            sequence:
              - condition: time
                weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
              - service: select.select_option
                target:
                  entity_id: select.home_monthly_energy
                data:
                  option: "{{ tariff }}"
          - conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: "19"
                  - condition: state
                    entity_id: binary_sensor.workday_sensor
                    state: "on"
            sequence:
              - condition: time
                weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
              - service: select.select_option
                target:
                  entity_id: select.home_monthly_energy
                data:
                  option: "{{ tariff }}"
          - conditions:
              - condition: trigger
                id: "23"
            sequence:
              - service: select.select_option
                target:
                  entity_id: select.home_monthly_energy
                data:
                  option: "{{ tariff }}"
```

**Comment by Nunu00** [comment]
Ho provato ad abilitare anch'io questa funzione ma l'automazione non funziona. Sia che la triggero manualmente sia che aspetto il trigger automatica la fascia non cambia. Il codice è corretto e l'automazione non da errori nell'esecuzione quindi non riesco a trovare dove sia il problema.
Questa è la mia configurazione. Suggerimenti??
```
#Sensore giorni lavorativi 
binary_sensor:
  - platform: workday
    country: IT
    workdays: [mon, tue, wed, thu, fri, sat]
    excludes: [sun, holiday]
    
#Utility meter consumo elettrico bimestrale
utility_meter:
  bimonthly_energy:
    source: sensor.power_meter_energia_giornaliera
    cycle: bimonthly
    tariffs:
      - F1
      - F2
      - F3 
    
#Configurazione fasce orarie
automation: 
  - alias: "Tariffe energetiche"
    id: "tariffe_energetiche"
    initial_state: true
    trigger:
      - platform: time
        id: "7"
        at: '7:00:00'
        variables:
          tariff: "F2"
      - platform: time
        id: "8"
        at: '8:00:00'
        variables:
          tariff: "F1"
      - platform: time
        id: "19"
        at: '19:00:00'
        variables:
          tariff: "F2"
      - platform: time
        id: "23"
        at: '23:00:00'
        variables:
          tariff: "F3"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "7"
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.workday_sensor
                    state: "on"
            sequence:
              - condition: time
                weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
                - sat
              - service: select.select_option
                target:
                  entity_id: select.bimonthly_energy
                data:
                  option: "{{ tariff }}"
          - conditions:
              - condition: trigger
                id: "8"
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.workday_sensor
                    state: "on"				
            sequence:
              - condition: time
                weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
              - service: select.select_option
                target:
                  entity_id: select.bimonthly_energy
                data:
                  option: "{{ tariff }}"
          - conditions:
              - condition: trigger
                id: "19"
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.workday_sensor
                    state: "on"
            sequence:
              - condition: time
                weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
              - service: select.select_option
                target:
                  entity_id: select.bimonthly_energy
                data:
                  option: "{{ tariff }}"
          - conditions:
              - condition: trigger
                id: "23"
            sequence:
              - service: select.select_option
                target:
                  entity_id: select.bimonthly_energy
                data:
                  option: "{{ tariff }}"
```
