### DISCUSSION TITLE
Automazione con trigger composto da input_number e sensor [RISOLTO]

### DISCUSSION THREAD

**Discussion by cl-7k-01** [indomus/forum#1858] [HUB: Home Assistant]
Ciao a tutti,
ho provato a scrivere questa automazione. Purtroppo qualcosa non va, credo a livello di trigger. L'azione invece, se eseguita "forzatamente" funziona come vorrei.
Secondo voi dove sbaglio?
```
- id: notifica_temperatura
  alias: Notifica temperatura
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states("sensor.temperatura_cpu_raspberry") >= states("input_number.soglia_notifica_temperatura_raspberry")
      }}'
  condition: []
  action:
  - service: notify.mobile_app_redmi_note_10_pro
    data:
      message: 'Superata la soglia di {{ states(''input_number.soglia_notifica_temperatura_raspberry'')
        }} C°, la temperatura rilevata è di: {{ states(''sensor.temperatura_cpu_raspberry'')
        }} C°'
  mode: single
```
Grazie in anticipo a chi risponderà

**Comment by snakuzzo** [comment]
Credo dipenda dal fatto che stai confrontando due stringhe. Tutti i template restituiscono sempre stringhe.
Tu ora gli stai dicendo di vedere se `'40' >= '30'` ... e non va bene (dovresti anche trovare degli errori o warning nel log.
Dovresti fare il cast a float.

Prova ad usare...

```yaml
value_template: '{{ states("sensor.temperatura_cpu_raspberry") | float( default = 0 ) >= states("input_number.soglia_notifica_temperatura_raspberry") | float( default = 0 ) }}'
```

**Comment by cl-7k-01** [comment]
Ciao snakuzzo,
grazie per la risposta.
Ho provato ma l'automazione non parte neppure con questa correzione.
```
- id: notifica_temperatura
  alias: Notifica temperatura
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states("sensor.temperatura_cpu_raspberry") | float( default = 0) >= states("input_number.soglia_notifica_temperatura_raspberry") | float( default = 0)
      }}'
  condition: []
  action:
  - service: notify.mobile_app_redmi_note_10_pro
    data:
      message: 'Superata la soglia di {{ states(''input_number.soglia_notifica_temperatura_raspberry'')
        }} C°, la temperatura rilevata è di: {{ states(''sensor.temperatura_cpu_raspberry'')
        }} C°'
  mode: single
```
ho fatto però una prova cambiando completamente il trigger e neppure scritta così sembra funzionare
```
- id: '1661287603622'
  alias: Prova
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.temperatura_cpu_raspberry
    above: '50'
  condition: []
  action:
  - service: notify.mobile_app_redmi_note_10_pro
    data:
      message: Messaggio notifica di prova
      title: Titolo notifica
  mode: single
```

**Reply by snakuzzo** [reply]
L'automazione ricorda che scatta solo se passa da un valore SOTTO O UGUALE ai 50 ad uno SUPERIORE ai 50

**Reply by snakuzzo** [reply]
Ad ogni modo...se qualcosa non ti torna...fai il debug delle automazioni (lo puoi fare via gui) e se non trovi soluzione abilità logger mettendo le automazioni a debug...e guarda i log di core

**Reply by cl-7k-01** [reply]
> L'automazione ricorda che scatta solo se passa da un valore SOTTO O UGUALE ai 50 ad uno SUPERIORE ai 50

Si, in effetti, non ci avevo pensato.

> Ad ogni modo...se qualcosa non ti torna...fai il debug delle automazioni (lo puoi fare via gui) e se non trovi soluzione abilità logger mettendo le automazioni a debug...e guarda i log di core

In questo caso però dovrebbe dare la notifica "sempre", o meglio sempre se superiore o uguale al parametro di confronto.
Per fare il debug ho dovuto dare un "esegui azioni" e il nodo del trigger noto che non viene eseguito..

Forse devo cambiare approccio?

**Reply by snakuzzo** [reply]
No...ti ripeto...devi prima avere un valore inferiore e poi passare ad un valore superiore....e ti partirà la action...e non ripartirà se prima non torna sotto quel valore.
Puoi simulare forzando lo stato sotto devi tools > states

**Reply by snakuzzo** [reply]
Come esegui non fai alcun debug...scateni solo la action.

**Comment by cl-7k-01** [comment]
L'automazione scritta così funziona:
```
- id: notifica_temperatura
  alias: Notifica temperatura
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states("sensor.temperatura_cpu_raspberry") | float( default = 0) >= states("input_number.soglia_notifica_temperatura_raspberry") | float( default = 0)
      }}'
  condition: []
  action:
  - service: notify.mobile_app_redmi_note_10_pro
    data:
      message: 'Superata la soglia di {{ states(''input_number.soglia_notifica_temperatura_raspberry'')
        }} C°, la temperatura rilevata è di: {{ states(''sensor.temperatura_cpu_raspberry'')
        }} C°'
  mode: single
```
Come mi hai suggerito, forzando lo stato del sensore temperatura cpu raspberry (portato a 40 e poi a 60) utilizzando dev tool - states (non lo conoscevo ammetto), l'automazione parte.
Il mio errore era nella logica del trigger: è stato illuminante il tuo chiarimento riguardo il cambio di stato. Senza la variazione il trigger non viene validato e l'automazione non parte (permettimi la banalizzazione..)
Grazie mille per l'aiuto!
