### DISCUSSION TITLE
bug (?!) ritardo automazione quando come trigger si usano timer o for?!

### DISCUSSION THREAD

**Discussion by 50494554524F** [indomus/forum#1864] [HUB: Home Assistant]
ad esempio...
```
  - platform: template

    value_template: "{{  states( xxx1 ) != states( xxx2 )  }}"

    for: "00:05:00"

```
invece che scattare dopo 5 minuti scatta dopo 7-8 minuti... capita ad altri?! sicuramente funzionava, non so con quale versione son cominciati i problemi... ora sto con 2022.6.7, se mi verificate apro un bug

grazie

**Comment by snakuzzo** [comment]
Appena provato su HA 2022.8.6 così (cambia il for a tuo piacimento) ... e funziona perfettamente

```yaml
input_text:

  text1:
    name: Text 1
    initial: Pippo

  text2:
    name: Text 2
    initial: Pippo

automation:

- alias: Prova testo
  trigger:
  - platform: template
    value_template: "{{  states('input_text.text1') != states('input_text.text2')  }}"
    for: 
      seconds: 5
  action:
  - service: persistent_notification.create
    data:
      message: "CIAO"
  mode: restart
```
