### DISCUSSION TITLE
set termostato per un certo tempo

### DISCUSSION THREAD

**Discussion by toposodo** [indomus/forum#1871] [HUB: Home Assistant]
Sto cercando di migrare da Domoticz a homeassistant core su raspberry pi4 con installazione su raspibian. Non so programmare e mi affido molto a goggle per risolvere le cose. Veniamo al dunque. Gestisco la caldaia con sonoff TH-16 + tasmota. In HA ho creato un termostato con il seguente codice

```
#termostato
climate:
  - platform: generic_thermostat
    name: Termostato
    heater: switch.cronotermostato
    target_sensor: sensor.cronotermostato_si7021_temperature
    min_temp: 15
    max_temp: 24
    target_temp: 16
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 30
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1
```

Adesso vorrei creare un pulsante virtuale che premendolo setti la temperatura desiserata per un prempo prestabilito. Per esempio mezzora o un'ora. Ho cercato ma non ho trovato niente. Forse non ho usato i termini giusti
Grazie Sandro
