### DISCUSSION TITLE
Problema con script

### DISCUSSION THREAD

**Discussion by Pioppo1995** [indomus/forum#1879] [HUB: Home Assistant]
Ciao a tutti, vi chiedo aiuto per questo script.
Sto cercando (dopo aver appurato che  non mi è possibile usare "transition" su questa lampadina smart), di creare uno script che aumenti la luminosità di una lampadina smart. Grazie all'aiuto dei membri dello staff sono arrivato a questo codice, ma salvando lo script, il salvataggio non va a buon fine: "Message malformed: extra keys not allowed @ data['sequence'][0]['service'] ".
Dovrei inoltre mettere un delay in modo che la transizione di luminosità venga ritardata.
Un grazie in anticipo a tutti quelli che vorranno aiutarmi.

```
alias: Script Repeat
sequence:
  # accendo luce
  - service: light.turn_on
    data:
      entity_id: light.luce_studio_2
      brightness_step_pct: 1
    repeat:
      # ripete 8 volte...
      count: 8
      # questa sequence...
      sequence: 
        - service: light.turn_on
          data:
            brightness_pct: "{{ state_attr('light.luce_studio_2','brightness_pct') | int + 10 }}" ```

**Comment by snakuzzo** [comment]
Scusa, ma perché non ti aiuti con i dev tools su lovelace ?
Ad ogni modo...

```yaml
script:

  script_repeat:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.luce_studio_2
          brightness_step_pct: 1
      - alias: "ciclo"
        repeat:
          count: 8
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.luce_studio_2
                brightness_pct: "{{ state_attr('light.luce_studio_2','brightness_pct') | int + 10 }}"
```
