### DISCUSSION TITLE
Problema con automazione "rientro a casa"

### DISCUSSION THREAD

**Discussion by Paoloc66** [indomus/forum#1880] [HUB: Home Assistant]
Ciao a tutti, 
seguendo varie guide ed esempi (inDomus) ho creato questa automazione che quando rientro a casa (apertura porta) mi accende la luce e mi comunica la temperatura ed umidità della casa.
Non capisco come mai a volte non funziona.
```
alias: Rientro
description: ""
trigger:
  - platform: state
    entity_id: group.famiglia
    to: home
condition: []
action:
  - wait_template: "{{ is_state('binary_sensor.sensore_porta_contact', 'on') }}"
    timeout: "00:30:00"
    continue_on_timeout: "false"
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - type: turn_on
    device_id: 838ff1----------------
    entity_id: light.luce_entrata
    domain: light
  - delay:
      hours: 0
      minutes: 0
      seconds: 4
      milliseconds: 0
  - service: notify.alexa_media
    data:
      target:
        - media_player.echo_sala
      data:
        type: tts
      message: >
        {{ [ "Bentornato a casa!", "Guarda chi si vede!", "Ciao!"] | random }}
        La temperatura media in casa è di {{
        ((states("sensor.temperatura_sala_temperature")|float +
        states("sensor.temperatura_cucina_temperature")|float
        )/2)|float|round(1)}} gradi, l'umidità è {{
        states.sensor.temperatura_sala_humidity.state }} %
mode: single
```
Non so se può essere la causa, quando rientro a casa parcheggio sempre l'auto in garage che è posto 2 piani sotto l'appartamento. A volte mi fermo qualche minuto (ma meno di 30) in garage e potrebbe perdere la connessione wifi essendo al limite della portata. Ma non credo possa annullare l'automazione...

**Comment by KC-inDomus** [comment]
Dentro il gruppo `group.famiglia` cosa c'è? Che entità derivanti da quale integrazione

**Comment by Paoloc66** [comment]
Ci sono 3 person
```
group:
  famiglia:
    entities:
      - person.paolo
      - person.daniele
      - person.diego

```

**Reply by KC-inDomus** [reply]
le tre `person` hanno al loro interno più `device_tracker`? derivanti da quali integrazioni

**Reply by Paoloc66** [reply]
il cellulare ed il mio portatile che però quando entro in casa è sempre spento (per ora lo sto testando solo io, le altre 2 persone sono integrate nel gruppo famiglia ma non sono mai entrate in casa prima di me).

**Reply by KC-inDomus** [reply]
pulisci tutto e metti una sola entità nel tuo gruppo, metti direttamente (e solo) il `device tracker` del cell sul quale hai Home Assistant Companion. assicurati che nelle impostazioni mandi la posizione gps precisa. in primis così dovrebbe funzionare in modo corretto; poi vai per gradi, rimetti solo la tua `person` (la quale raggruppa a sua volta cell e portatile) e fai delle prove. se hai dei problemi, controlla i log e lo storico delle entità che popolano la `person`.

forza gli stati così https://indomus.it/formazione/esercizi-di-domotica-su-home-assistant-2-definire-diversi-trigger-per-innescare-automazioni/

**Reply by Scialla** [reply]
Questa funziona perfettamente, prendi spunto e modificala come ti pare:
```
  - alias: "saluto alexa al rientro"
    id: saluto_alexa_al_rientro
    mode: parallel
    trigger:
      - platform: zone
        entity_id: 
          - person.scialla
          - person.silvia
          - person.giovanna
        zone: zone.home
        event: enter
    action:
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.porta_casa_contact
            to: 'on'
        timeout:
          minutes: 20
        continue_on_timeout: false 
      - delay: '00:00:03'
      - service: notify.alexa_media
        data:
          target: 
            - media_player.altoparlante
          data:
            type: tts
            method: spoken
          message: >
            {% if trigger.entity_id == 'person.scialla' %}
              "Bentornato Scialla"
            {% elif trigger.entity_id == 'person.silvia' %}
              "Bentornata Silvia"
            {% elif trigger.entity_id == 'person.giovanna' %}
              "Bentornata Giovanna"
            {% else %}
              {{ states('trigger.entity_id') }}
            {% endif %} 
```
