### DISCUSSION TITLE
Telegram servizio Notify non disponibile

### DISCUSSION THREAD

**Discussion by jimborm** [indomus/forum#1887] [HUB: Home Assistant]
Ciao a tutti. Ho creato un bot Telegram integrato nel mio HomeAssistant per far aprire il cancello del residence ai condomini che ne chiedono la possibilità. Funziona a tutti tranne a 2 di loro. Ho inserito in configurazione il loro chat_id, come del resto per gli altri, ma dopo il riavvio di HomeAssistant mi sono accorto che i servizi Notify.Pippo e Notify.Pluto non vengono creati. 
Qualcuno ha avuto problemi simili o mi saprebbe aiutare a capire il motivo?

**Comment by snakuzzo** [comment]
Devi condividere configurazione ed eventualmente i log di Core in fase di start...altrimenti è impossibile aiutarti

**Reply by jimborm** [reply]
Hai ragione sorry
Nel configurato.yaml ho messo questo

```
telegram_bot:
#PIAVE
#https://api.telegram.org/bot<YOUR_API_TOKEN>/getUpdates
# https://api.telegram.org/bot<xxxxxxxxxx>getUpdates
  - platform: polling
    api_key: <xxxxxxxxxxxxxxxxxxxxxxxx>
    allowed_chat_ids:
      - <12345678>
      - <12345678>
      - <12345678>
      - <12345678>
      - <12345678>
      - <12345678>

notify:
  - name: Pippo
    platform: telegram
    chat_id: <12345678>

  - notify: pluto
    platform: telegram
    chat_id: <12345678>

  - name: giancarlo
    platform: telegram
    chat_id: <12345678>

  - name: Int18
    platform: group
    services:
      - service: Pippo
      - service: pluto
```
 con l'impostazione di logging seguente  
```
logger:
  default: info
  logs:
    #homeassistant.automations: debug
    homeassistant.components.telegram_bot:
    #homeassistant.components.light: debug
```
questo il log grappando per telegram
<img width="1833" alt="Schermata 2022-09-07 alle 10 31 02" src="https://user-images.githubusercontent.com/52866001/188830812-f23fca59-26bd-4f99-ae16-f00f3e0830d4.png">

**Comment by jimborm** [comment]
Qualcuno ha qualche suggerimento per analizzare il motivo per cui solo questi 2 servizi non vengano creati ?

**Reply by Lorenzo1922** [reply]
sto avendo lo stesso problema 
premetto che prima la notifica telegram mi funzionava su tutte le chat id
ora la notifica telegram mi funziona solo alla prima chat id nella lista
il workaround che ho usato e creare un gruppo in cui ho messo tutti gli user telegram) ed usare la group chat id al primo posto

**Reply by jimborm** [reply]
Perdonami io sono novello del mondo programmazione. Ho necessità che riesca a notificare al singolo user perché ho un automazione che viene lanciata dai inline Command e prevede una risposta al terminale che la scaturisce. 
Sicuramente se ti metto il codice qui sotto tu capisci subito.
```
- alias: Telegram_Bot_Start
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /start
  action:
  - service: notify.{{ trigger.event.data["from_first"] }}
    data_template:
      #title: RESIDENCE
      message: '*RESIDENCE*'
      data:
        inline_keyboard:
        - '{{ "\U0001F698" }} APRI RESIDENCE:/residence,{{ "\U0000267B" }} DIFFERENZIATA:/tasto_mastello'
```

```
- alias: apricarraio_residence_telegram
  id: 4756382
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: /residence
  action:
  - service: switch.turn_on
    entity_id: switch.citofono_carraio_residence
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      #title: 'ATTENDI {{ trigger.event.data["from_first"] }}!'
      message: "Sto aprendo il cancello!"
  - service: notify.{{ trigger.event.data["from_first"] }}
    data_template:
      message: '*{{ trigger.event.data["from_first"] }} attendi!* ... sto aprendo il cancello.'
```
