### DISCUSSION TITLE
Lettura sensori fotovoltaico su plancia "Energia"

### DISCUSSION THREAD

**Discussion by kvegeta** [indomus/forum#1896] [HUB: Home Assistant]
Buongiorno a tutti, ho installato l'altrogiorno il fotovoltaico in casa e smanettando nelle impostazioni sono riuscito ad aprirmi le api e leggerle tramite implementazione rest, unico problema, la sezione energia di "HomeAssistant" non mi visualizza questi sensori come disponibili.
Qualcuno ha dei consigli su come agire o modificare la configurazione?

Grazie mille!

```
sensor:
  - platform: rest
    name: fotovoltaico
    resource: https://qhome-ess-g3.q-cells.eu/proxyApp/proxy/api/getRealtimeInfo.do?tokenId=****************&sn=**********
    json_attributes:
      - result
    scan_interval: 60
    value_template: "OK"
  - platform: template
    sensors:
        fv_produzione:
            unique_id: fv_produzione_corrente
            friendly_name: "Produzione pannelli"
            value_template: "{{ state_attr('sensor.fotovoltaico', 'result')['acpower'] }}"
            device_class: energy
            unit_of_measurement: "kWh"
            entity_id: sensor.fotovoltaico
        fv_batterie_carica:
            friendly_name: "Carica batterie"
            value_template: "{{ state_attr('sensor.fotovoltaico', 'result')['soc'] }}"
            device_class: battery
            unit_of_measurement: "%"
            entity_id: sensor.fotovoltaico
        fv_batterie_utilizzo:
            unique_id: fv_batterie_utilizzo
            friendly_name: "Utilizzo batterie"
            value_template: "{{ state_attr('sensor.fotovoltaico', 'result')['batPower'] }}"
            device_class: energy
            unit_of_measurement: "kWh"
            entity_id: sensor.fotovoltaico
        fv_consumo_rete_elettrica:
            unique_id: fv_consumo_rete_elettrica
            friendly_name: "Consumo Enel"
            value_template: "{{ state_attr('sensor.fotovoltaico', 'result')['feedinpower'] }}"
            device_class: energy
            unit_of_measurement: "kWh"
            entity_id: sensor.fotovoltaico
        fv_produzione_giornaliera:
            friendly_name: "Produzione giornaliera"
            value_template: "{{ state_attr('sensor.fotovoltaico', 'result')['yieldtoday'] }}"
            device_class: energy
            unit_of_measurement: "kWh"     
            entity_id: sensor.fotovoltaico
        fv_produzione_totale:
            friendly_name: "Produzione totale"
            value_template: "{{ state_attr('sensor.fotovoltaico', 'result')['yieldtotal'] }}"
            device_class: energy
            unit_of_measurement: "kWh" 
            entity_id: sensor.fotovoltaico       
```

**Comment by kvegeta** [comment]
Aggiornamento:
Impostando come di seguito sono riuscito a far visualizzare i sensori alla plancia di energia ma mi da questo errore che non riesco a bypassare: "Le seguenti entità hanno la classe di stato 'measurement', ma manca 'last_reset':"
Qui di seguito il codice che mi fornisce regolarmente i parametri dal registro

```
template:
  - sensor:
      - name: "Produzione Pannelli solari"
        state: "{{ state_attr('sensor.fotovoltaico', 'result')['powerdc1'] + state_attr('sensor.fotovoltaico', 'result')['powerdc2']}}"
        unit_of_measurement: "kWh"
        icon: mdi:solar-power
        state_class: "measurement"
        unique_id: "fv_solar_production"
        device_class: "energy"
      - name: "Consumo da rete elettrica"
        state: "{{ state_attr('sensor.fotovoltaico', 'result')['feedinpower'] }}"
        unit_of_measurement: "kWh"
        icon: mdi:solar-power
        unique_id: "fv_enel_consumption"
        state_class: "measurement"
        device_class: "energy"
      - name: "Batterie OUT"
        state: >-
          {% set out = state_attr('sensor.fotovoltaico', 'result')['batPower'] %}
          {% if out > 0 %} 0
          {% else %} out
          {% endif %}
        unit_of_measurement: "kWh"
        icon: mdi:solar-power
        state_class: "measurement"
        unique_id: "fv_battery_power"
        device_class: "energy"
      - name: "Batterie IN"
        state: >-
          {% set i = state_attr('sensor.fotovoltaico', 'result')['batPower'] %}
          {% if i > 0 %} i
          {% else %} 0
          {% endif %}
        unit_of_measurement: "kWh"
        icon: mdi:solar-power
        state_class: "measurement"
        unique_id: "fv_battery_charging"
        device_class: "energy"
```
