### DISCUSSION TITLE
Sensore Energia Virtuale

### DISCUSSION THREAD

**Discussion by RazorCopter** [indomus/forum#1916] [HUB: Home Assistant]
Ciao Ragazzi, spero che qualcuno mi possa aiutare, sto cercando di configurare per bene il pannello energia nello specifico assegnare un sensore
alla voce "restituito alla rete" 
Ho creato un sensore virtuale derivato dalla differenza da quanto prodotto a consumato dalla casa 
```
- platform: template
  sensors:
    home_consumption_kwh:
      friendly_name: 'Bilancio Energetico kWh'
      value_template: "{{ (states('sensor.ghome_solar_energy_today') |float - states('sensor.pow_generale_energy_today') |float) | round(2) }}" 
      unit_of_measurement: "kWh"     
      device_class: energy
```

1) Problema questo sensore non è visto dal panello energia che devo fare?
2) Problema il sensore può avere valori negativi ovviamente quando la produzione dei pannelli è 0, come faccio a dargli una costante ( 0 KWH) quando il valore risulta negativo? 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/5910480/189976817-a75a67c2-ac83-4984-a010-69d42c439c1f.png">

**Comment by Scialla** [comment]
Lo hai aggiunto nello storico?
Per essere visto deve essere incluso nel recorder (e ci va poi qualche ora prima che lo veda)

**Reply by RazorCopter** [reply]
ho fatto qualche passo avanti, in template.yaml ho creato questo sensore:
```
- sensor:
    - name: "Bilancio Energetico Today"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: measurement
#      last_reset: '1970-01-01T00:00:00+00:00'
      state: >-
        {{ (states('sensor.ghome_solar_energy_today') |float - states('sensor.pow_generale_energy_today') |float) | round(2)}}
```
in questo modo la dash Energy lo vede:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/5910480/190106501-49173b59-6068-4d90-b785-2f02973bcbdb.png">

Attivandolo mi da questo warning:
```
Ultimo ripristino mancante
Le seguenti entità hanno la classe di stato 'measurement', ma manca 'last_reset':
sensor.bilancio_energetico_today
```
Ma se abilito il last_reset quindi cosi:

```
- sensor:
    - name: "Bilancio Energetico Today"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: measurement
      last_reset: '1970-01-01T00:00:00+00:00'
      state: >-
        {{ (states('sensor.ghome_solar_energy_today') |float - states('sensor.pow_generale_energy_today') |float) | round(2)}}
```

Ho un errore dai log:
```
Dettagli registro (ERRORE)
Logger: homeassistant.config
Source: config.py:820
First occurred: 10:56:41 (1 occurrences)
Last logged: 10:56:41

Invalid config for [template]: [last_reset] is an invalid option for [template]. Check: template->sensor->0->last_reset. (See /config/yaml/template.yaml, line 0).
```

suggerimenti?

**Comment by RazorCopter** [comment]
```
- sensor:
    - name: "Bilancio Energetico Today"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
#      state_class: measurement
#      last_reset: '1970-01-01T00:00:00+00:00'
      state: >-
        {{ (states('sensor.ghome_solar_energy_today') |float - states('sensor.pow_generale_energy_today') |float) | round(2)}}
```

In questo modo si rispetta il template e viene visto correttamente dalla scheda Energia 

Ora il problema si sposta sul valore negativo:
```
L'entità ha uno stato negativo
Le seguenti entità hanno uno stato negativo mentre è previsto uno stato positivo:
sensor.bilancio_energetico_today (-1.3)
```

**Comment by RazorCopter** [comment]
**AGGIORNAMENTO**

**Legenda Entità:**
- sensor.ghome_solar_current_power : [W] Potenza istantanea in uscita PV
- sensor.pow_generale_energy_power : [W] Potenza istantanea (assorbimento casa) 
- sensor.nrg_potenza_in_uscita_today: [W] Filtro (valori > 0W quindi immessi in rete)
- sensor.nrg_today_energy_exp: [Wh] Calcolo Energia 
- sensor.nrg_export_energy: [kWh] Conversione in kWh



**template.yaml**

```
- sensor:
    - name: "NRG Potenza in uscita Today"
      unit_of_measurement: "W"
      device_class: energy
      state_class: total_increasing
      state: >-
        {{ (states('sensor.ghome_solar_current_power') |float - states('sensor.pow_generale_energy_power') |float) | round(2)}}

- sensor:
      name: "NRG Export Power"
      icon: mdi:solar-power
      unit_of_measurement: 'W'
      state: >
        {% if states('sensor.nrg_potenza_in_uscita_today')|float >= 0 %}
          {{ states('sensor.nrg_potenza_in_uscita_today') }} 
        {% else %}
          0
        {% endif %}

- sensor:
      name: "NRG Export Energy"
      icon: mdi:solar-power
      unit_of_measurement: 'kWh'
      state: >
        {% if states('sensor.nrg_today_energy_exp')|float >= 0 %}
          {{ states('sensor.nrg_today_energy_exp')|float / 1000 }}
        {% else %}
          0
        {% endif %}
      device_class: energy
      state_class: total_increasing 
```

**configuration.yaml**

```
utility_meter:
  nrg_today_energy_exp:
    source: sensor.nrg_export_power
    cycle: daily 
```

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/5910480/190165788-ea7c5792-450b-4210-8fa1-4dcd665879ca.png">

**Comment by RazorCopter** [comment]
## **AGGIORNAMENTO**: **[SOLVED]**
Creati due sensori di energia virtuali andando a integrare la potenza nel tempo sia in ingresso che in uscita:
```
- sensor:                                         #Calcolo Energia immessa in rete
    - name: "NRG Potenza uscita Now"
      unique_id: nrg_potenza_uscita_now
      icon: mdi:solar-power
      unit_of_measurement: "W"
      state: >-
        {% if (states('sensor.ghome_solar_current_power') |float - states('sensor.pow_generale_energy_power') |float     )|float  > 0 %}
          {{  states('sensor.ghome_solar_current_power') |float - states('sensor.pow_generale_energy_power') |float }} 
        {% else %}
          0
        {% endif %}


# Creo il sensore sensor.nrg_export_power_int nato dall'integrazione nel tempo di sensor.nrg_export_power
# Device&Service > helper (Aiutanti) > Integration - Sensor sum Riemann [input parameter nrg_potenza_uscita_now ]   
# Vedi screenshot in basso 


- sensor:
      name: "NRG Export Energy Today"  #aggiunti attibuti a sensor.nrg_export_power_int (integrale automatico)
      unique_id: nrg_export_energy_today
      icon: mdi:solar-power
      state: >
        {{ (states('sensor.nrg_export_power_int') | float) }}
      device_class: energy
      state_class: total_increasing 
      unit_of_measurement: 'kWh'
```



```
##################################################################
- sensor:                                         #Calcolo Energia Prelevata da rete
    - name: "NRG Potenza in ingresso Now"
      unique_id: nrg_potenza_in_ingresso_now
      icon: mdi:solar-power
      unit_of_measurement: "W"
      state: >-
        {% if (states('sensor.pow_generale_energy_power') |float - states('sensor.ghome_solar_current_power') |float     )|float  > 0 %}
          {{ (states('sensor.pow_generale_energy_power') |float - states('sensor.ghome_solar_current_power') |float ) }} 
        {% else %}
          0
        {% endif %}


# Creo il sensore sensor.nrg_export_power_int nato dall'integrazione nel tempo di sensor.nrg_export_power
# Device&Service > helper (Aiutanti) > Integration - Sensor sum Riemann [input parameter nrg_potenza_in_ingresso_now ]
# Vedi screenshot in basso 

- sensor:
      name: "NRG Import Energy Today"  #aggiunti attibuti a sensor.nrg_export_power_int (integrale automatico)
      unique_id: nrg_import_energy_today
      icon: mdi:solar-power
      state: >
        {{ (states('sensor.nrg_import_power_int') | float) }}
      device_class: energy
      state_class: total_increasing 
      unit_of_measurement: 'kWh'
##################################################################


```

![image](https://user-images.githubusercontent.com/5910480/193403715-efbfa20a-05f6-4bae-8c05-1223c6b448a1.png)
