### DISCUSSION TITLE
Spegnimento ritardato

### DISCUSSION THREAD

**Discussion by barbatrukko** [indomus/forum#1917] [HUB: Home Assistant]
Buonasera,
io ho una luce nel corridoio, collegata ad un sonoff mini collegato ad un relè, che posso accendere e spegnere indifferentemente dai pulsanti ai bordi del corridoio, dall'app di sonoff, da Home assistant (le app e HA conoscono sempre lo stato di accensione/spegnimento della luce)
Vorrei aggiungere un trigger che:
quando la luce viene accesa, aspetta un certo numero di secondi (ad esempio 60) e poi la spegne (se non è già spenta di suo). E magari aggiungere un interruttore su home assistant, che abilita/disabilita questo comportamento.
la luce è in realtà vista come uno switch percui
```
type: entities
entities:
  - switch.sonoff_XXXXXXXXX
title: Corridoio
```

**Comment by snakuzzo** [comment]
Ti basta fare una semplice automazione...

```yaml
- id: auto_spegnimento_sonoff
  alias: 'Autospegnimento SonOFF'
  description: 'Spegne la luce dopo 60 secondi dall'accensione'
  trigger:
  - platform: state
    entity_id: switch.sonoff_XXXXXXXXX
    from: 'off'
    to: 'on'
  action:
  - delay:
      seconds: 60
  - service: switch.turn_off
    data:
      entity_id: switch.sonoff_XXXXXXXXX
```

oppure

```yaml
- id: auto_spegnimento_sonoff
  alias: 'Autospegnimento SonOFF'
  description: 'Spegne la luce dopo 60 secondi dall'accensione'
  trigger:
  - platform: state
    entity_id: switch.sonoff_XXXXXXXXX
    from: 'off'
    to: 'on'
    for:
      minutes: 1
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.sonoff_XXXXXXXXX
```

... che metterai su una qualsiasi card di tipo `Entities` dove potrai abilitarla e disabilitarla a piacimento:

![image](https://user-images.githubusercontent.com/7205371/190002002-082d499d-0bd4-49dd-8f94-80f7ba2c1ab3.png)

**Comment by barbatrukko** [comment]
Io avevo provato con questo senza successo (tramite la wizard)
```
`alias: Spegnimento Automatico Corridoio
description: Spegnimento Automatico Corridoio
trigger: []
condition:
  - condition: device
    type: is_on
    device_id: YYYYYYYYYYYYYYYYYYYY
    entity_id: switch.sonoff_XXXXXXXX
    domain: switch
    for:
      hours: 0
      minutes: 1
      seconds: 0
action:
  - type: turn_off
    device_id: YYYYYYYYYYYYYYYYYYYY
    entity_id: switch.sonoff_XXXXXXXX
    domain: switch
mode: single`
```

Domani provo il tuo codice.
GRazie
