### DISCUSSION TITLE
PROGRAMMA (scheduler) da aiutanti

### DISCUSSION THREAD

**Discussion by nromagna** [indomus/forum#1921] [HUB: Home Assistant]
Ciao a tutti ho visto che su aiutanti nelle ultimeversioni trovo la possibilità si aggiungere un "Programma" che permette di selzionare ore prestabilite ogni giorno per tutta la settimana.
Se lo compilo mi si crea il "schedule.nome_programma" ma come lo posso utilizzare in un'automazione?
Cioè se lo progammo giorno per giorno a determinati orari come posso far si che "una lampadina" si accenda a programma?
Mi sono capito?
Grazie

**Comment by indomus** [comment]
> Ciao a tutti ho visto che su aiutanti nelle ultimeversioni trovo la possibilità si aggiungere un "Programma" che permette di selzionare ore prestabilite ogni giorno per tutta la settimana. Se lo compilo mi si crea il "schedule.nome_programma" ma come lo posso utilizzare in un'automazione? Cioè se lo progammo giorno per giorno a determinati orari come posso far si che "una lampadina" si accenda a programma? Mi sono capito? Grazie

https://www.home-assistant.io/integrations/schedule/

**Reply by nromagna** [reply]
Ciao allora il default_config: dentro configuration.yaml c'è. Solo che non capisco una volta creato in aiutanti il schedule.xxx come lo posso utilizzare all'interno di un'automazoine?
Mi spiego ho creato la schedulazione con determinati orari nella giornata/settimana e vorrei che in questi orari un particolare switch si accendesse per l'appunto:

```
alias: XXX
description: ""
trigger:
  - platform: state
    entity_id:
      - schedule.xxx
    from: "off"
    to: "on"
condition: []
action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.sonoff_xxx
mode: single

```


Ma non sembra funzionare. 

Grazie.

**Reply by nromagna** [reply]
O meglio funziona solo in ON...

**Reply by nromagna** [reply]
Fatta piccola modifica e sembra funzionare:

```
alias: XXX
description: ""
trigger:
  - platform: state
    entity_id:
      - schedule.xxx
condition: []
action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.sonoff_xxx
mode: single
```
Dove su schedule ho impostato:
![image](https://user-images.githubusercontent.com/79841098/191429010-877ef8f1-d831-4839-a899-b48ff3797bb1.png)


**Però** il "service: switch.toggle" dell'automazione non mi piace molto; ossia se per qualche motivo il sonoff viene spento manualmente l'automazione funziona al contrario.

Mi piacerebbe che si accendesse (a prescindere dallo stato) SOLO negli orari in blu... qualche aiutino? 

Grazie.
