### DISCUSSION TITLE
Restituire valore RGB di un lampadina

### DISCUSSION THREAD

**Discussion by cecov74** [indomus/forum#1923] [HUB: Home Assistant]
Ciao a tutti, sto preparando una dashboard e ho messo le 4 lampadine in un blocco, con un semplice if (se spenta bianco, se accesa nera) ma vorrei che invece se è accesa mettesse il colore della lampadina (se è rossa mi mette il colore rosso), ma posso leggere il sensore del colore per avere l'RGB?

```yaml
type: custom:button-card
entity: light.cucina1_msl120d_main_channel
color_type: card
show_name: false
state:
  - value: 'off'
    color: rgb(255, 255, 255)
    brightness: 0
  - value: 'on'
    color: rgb(0,0,0)
icon: mdi:numeric-1-circle-outline```

**Comment by snakuzzo** [comment]
Hai letto la documentazione della custom card ?
[QUI](https://github.com/custom-cards/button-card#examples) trovi proprio quello che serve a te. Lo vedi dove c'è l'esempio _**Light card with card color type, name, and automatic color**_

Ho appena provato...lo fai facilmente così...

```yaml
type: custom:button-card
entity: light.cucina1_msl120d_main_channel
icon: mdi:numeric-1-circle-outline
color: auto
color_type: card
show_name: false
```
