### DISCUSSION TITLE
Media Player Alexa

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#193] [HUB: Home Assistant]
Qualcunoi mi può dire se c'è qualcosa di sbagliato in questo script?
Alexa mi dice _non posso riprodurre questo elemento_ .
```
radio:
    alias: Radio
    sequence:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.echoshow_mio
        media_content_id: "Radiofreccia" 
        media_content_type: "TUNEIN"
    mode: single
```
