### DISCUSSION TITLE
nextsunrise  e  nextsunset

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#194] [HUB: Home Assistant]
Con il codice che segue visualizzo tramite due sensori il prossimo tramonto ed alba. Il tutto funziona, ma nel log di avvio trovo una eccezione:
_The 'entity_id' option near /config/sensors.yaml: 23 is deprecated, please remove it from your configuration_
che si ripete anche per la riga 29, il numero di riga segnalato si riferisce a nextsunrise e nextsunset

```
 - platform: template
    sensors:
      nextsunrise:
        entity_id: sun.sun
        friendly_name: "La prossima alba"
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      nextsunset:
        entity_id: sun.sun
        friendly_name: 'Il prossimo tramonto'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down
```
Devo rinunciare ai due sensori? posso correggere qualcosa?
