### DISCUSSION TITLE
creazione sensori in template.yaml

### DISCUSSION THREAD

**Discussion by drako92** [indomus/forum#1951] [HUB: Home Assistant]
Ciao a tutti, sto impazzendo cercando di capire cosa sto sbagliando nella creazione di questi due sensori (ovviamente presi da internet) all'interno del file template.yaml
Ho provato a leggere la documentazione sui Template, ma continuo a non capire dove sto sbagliando
I sensori che dovrei creare sono i seguenti:
```
- sensors:
    ssl_days_left:
      friendly_name: Il certificato SSL scade tra
      unit_of_measurement: Giorni
      value_template: >-
        {{ ( ( states('sensor.cert_expiry_timestamp_nome_certificato') | as_timestamp(0) - now().timestamp() ) / 86400 ) | round(0) }}
```
e questo:

```
- sensor:
    - name: "Low Battery Devices"
      unique_id: ba292875-ae67-480d-9867-29cdb20afaea
      icon: >
        mdi:battery-low
      state: >
        {% set threshold = states('input_number.livello_batterie') | int %}
        {%- set ns = namespace(sensors=[]) -%}
        {%- for state in states.sensor 
          | selectattr('attributes.device_class', 'defined') 
          | selectattr('attributes.state_class', 'defined') 
          | selectattr('attributes.device_class', '==', 'battery') 
          | selectattr('attributes.state_class', '==', 'measurement') 
          | selectattr('state', 'is_number') -%}
          {%- if state.state | int <= threshold -%}
            {% set ns.sensors = ns.sensors + [dict(name = state.name | replace(' battery', '') | replace(' Battery', ''), state = state.state | int)] %}
          {%- endif -%}
        {%- endfor -%}
        {%- set batt = ns.sensors | sort(attribute='state') %}
        {%- set ns = namespace(batt='') -%}
        {%- for state in batt -%}
            {% set ns.batt= ns.batt + (state.name  ~ ' (' ~ state.state ~'%)' ~ "\n") %}
        {%- endfor -%}

        {% if ns.batt | count > 0 %}
          {{ ns.batt | truncate(255, true, '...') }}
        {% else %}
          {{ 'unavailable' }}
        {% endif %}
```
Se li inserisco singolarmente nel file funzionano, ma se cerco di inserirli entrambi no.
Chi può darmi una mano?

Grazie
