### DISCUSSION TITLE
ESPHOME: pulse_counter vs pulse_meter

### DISCUSSION THREAD

**Discussion by array81** [indomus/forum#1960] [Hardware & Firmware]
Qualcuno mi potrebbe spiegare la differenza tra pulse_counter e pulse_meter? Ho letto le relative descrizione sul sito di ESPHome ma non riesco a capire in cosa differiscono.
Sto realizzando un sensore per la lettura remota del contatore. Per farlo mi sono basato su un paio di progetti che ho trovato in rete che mi hanno portato al seguente codice:

```
sensor:
  - platform: pulse_counter
    pin: GPIO12
    update_interval : 6s
    name: "Water Pulse Counter"
    id: water_pulse_counter

  - platform: pulse_meter
    pin: GPIO12
    name: "Water Pulse Meter"
    icon: "mdi:water-sync"
    id: water_pulse_meter
    internal_filter: 300ms
    internal_filter_mode: PULSE
    accuracy_decimals: 1
    unit_of_measurement: "l/min"
    timeout: 15s

    total:
      name: "Water Total"
      icon: "mdi:water"
      unit_of_measurement: "liter"
      accuracy_decimals: 1

  - platform: template
    name: "Water Usage Liter"
    id: water_flow_rate
    accuracy_decimals: 1
    unit_of_measurement: "l/min"
    icon: "mdi:water"
    lambda: return (id(water_pulse_counter).state * 10);
    update_interval: 6s
```

In sostanza uso un sensore di prossimità per catturare il giro che compie la lancetta del contatore dell'acqua. Ho notato che Water Pulse Meter e Water Total mi forniscono i valori corretti mentre Water Pulse Counter e Water Usage Liter sono sempre 0.

Come detto il codice non è mio quindi vorrei capire a cosa servirebbero Water Pulse Counter e Water Usage Liter entrambi collegati a pulse_counter.
