### DISCUSSION TITLE
Spegnimento host con HA Core istanziato su docker

### DISCUSSION THREAD

**Discussion by matteo-vannucchi** [indomus/forum#1966] [Hardware & Firmware]
Ciao mi chiamo Matteo e seguendo le vostre guide sono riuscito a mettere su un mini PC con Debian, Docker e HA Core.

Ho seguito i passaggi descritti nelle guide, tranne la parte relativa a sudo: sono l'unico con l'accesso alla macchina e SSH è configurato per permettere l'accesso solo tramite certificato.

L'acquisto più recente che ho fatto è stato un UPS NetPower800 della Riello che sono riuscito a integrare correttamente in HA. Il problema viene al momento dello shutdown: ho provato diversi comandi, ma nessuno sembra funzionare correttamente.

HA Core è aggiornato all'ultima versione 2022.10, questo è il contenuto del file di Docker Compose
```yaml

version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/homeassistant/.homeassistant:/config
#      - /etc/localtime:/etc/localtime:ro
#      - "/run/shutdown_signal:/run/shutdown_signal"
#      - "/run/reboot_signal:/run/reboot_signal"
      - "/run/dbus:/run/dbus/:ro"
    environment:
      - TZ=Europe/Rome
#    restart: unless-stopped
    restart: always
#    privileged: true
    network_mode: host

  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/homeassistant/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/homeassistant/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    - "10500:10500"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
    - "/srv/mosquitto/config:/mosquitto/config"
    - "/srv/mosquitto/log:/mosquitto/log"
    - "/srv/mosquitto/data:/mosquitto/data"
    restart: always
    ports:
    - "1883:1883"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
    - "/home/homeassistant/zigbee2mqtt:/app/data"
    devices:
    - "/dev/ttyUSB1"
    environment:
    - "TZ=Europe/Rome"
    network_mode: host
    restart: always

  nut-upsd:
    container_name: nut-upsd
    image: instantlinux/nut-upsd
    volumes:
    - "/home/homeassistant/nut-upsd-password:/run/secrets/nut-upsd-password"
    environment:
    - "PORT=auto"
    - "NAME=rielloUSB"
    - "DESCRIPTION=Riello USB NetPower 800"
    - "DRIVER=riello_usb"
    - "API_USER=nutAdmin"
    network_mode: host
    privileged: true
    restart: always

```
Mentre questo è il file di configurazione di HA:

```yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

recorder:
  purge_keep_days: 60
#  db_url: sqlite:////home/homeassistant/.homeassistant/test
  exclude:
    domains:
#      - sensor
      - automation
      - script
#    entities:
#      - light.ingresso
    event_types:
      - service_executed
      - platform_discovered
      - service_registered
      - call_service
      - component_loaded
      - logbook_entry
      - system_log_event
      - automation_triggered
      - script_started
      - timer_out_of_sync
  include:
    domains:
      - energy
      - sensor
    entities:
      - binary_sensor.stufa_accesa

history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sensor.last_boot
      - sensor.date
  include:
    domains:
      - sensor
      - switch
      - media_player

logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
    domains:
      - sun
      - weblink
  include:
    domains:
      - sensor
      - switch
      - media_player
      - automation

http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 172.0.0.0/8


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'it'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
smartir: !include smartir.yaml
climate: !include smartirClimate.yaml
media_player: !include smartirMediaPlayer.yaml
google_assistant: !include googleassistant.yaml

hacs:
     token: _token-hacs_

# Example configuration.yaml entry
#device_tracker:
#  - platform: fritz

#device_tracker:
#  - platform: bluetooth_tracker

sensor:
  - platform: template
    sensors:
      indice_thom:
        friendly_name: "Indice Thom"
        value_template: "{{ (states('sensor.rm4_cucina_temperature')|float - (0.55-0.0055 * states('sensor.rm4_cucina_humidity')|float)*(states('sensor.rm4_cucina_temperature')|float - 14.5))|round(1) }}"
        unit_of_measurement: 'index'
      ore_funzione_stufa:
        friendly_name: "Ore stufa"
        value_template: "{{ (states('counter.ore_lavoro_stufa')|float / 60.0) | round(1) }}"
        #unit_of_measurement: 'index'

binary_sensor:
  - platform: template
    sensors:
      stufa_accesa:
        friendly_name: "Stufa accesa"
        unique_id: sensore_stufa_accesa
        device_class: power
        value_template: "{{ states('sensor.smart_plug_20072915404688251h5448e1e927b597_power')| float > 10.0}}"
        delay_on:
         seconds: 30

      soundbar_acceso:
        friendly_name: "Soundbar JBL accesa"
        unique_id: sensore_soundbar_accesa
        device_class: power
        value_template: "{% if is_state('device_tracker.b8_69_c2_16_5e_4f', 'home') %} 'on' {% else %} 'off' {% endif %}"

homeassistant:
  packages: !include_dir_named packages

shell_command:
  reboot_pc_cmd: "echo 'true' > /run/reboot_signal/go"
  shutdown_pc_cmd: "echo 'true' > /run/shutdown_signal/go"
  shutdown_pc_cmd_true: "/sbin/shutdown now"


```
è necessario il passaggio di sudo o ci sono altre strategie da utilizzare?

Grazie dell'aiuto
