### DISCUSSION TITLE
ZHA with docker

### DISCUSSION THREAD

**Discussion by jovannig** [indomus/forum#1983] [ZigBee, Z-Wave, Thread, Matter]
I have HA installed as a docker container on a raspberry.
I tried to add ZHA integration from HA, but when I select my conbee II usb key I’m asked for a serial device path (which is /dev/ttyACM0 on raspberry).
I don’t know how to map the port from raspberry to the container.
I tried inserting these lines in the docker compose file, however it did not work.

What’s wrong ?

```yaml
services:
  home-assistant:
  container_name: home-assistant
  image: ghcr.io/home-assistant/home-assistant:stable
  volumes:
  - /home/pi/homeAssistant:/config
  devices:
  - /dev/bus/usb/001/007:/dev/ttyACM0
  environment:
  - TZ=Europe/Rome
  privileged: true
  restart: always
  ports:
  - “8123:8123”
```

**Comment by snakuzzo** [comment]
If you have no other connected USB devices, probably is `/dev/ttyUSB0` or `/dev/ttyACM0`

Yo can try to run...

```bash
ls -lart /dev | grep -e ttyUSB -e ttyACM
```

But you can also find the right device address using this script...

Create a new file...

```bash
#!/bin/bash

for sysdevpath in $(find /sys/bus/usb/devices/usb*/ -name dev); do
    (
        syspath="${sysdevpath%/dev}"
        devname="$(udevadm info -q name -p $syspath)"
        [[ "$devname" == "bus/"* ]]
        eval "$(udevadm info -q property --export -p $syspath)"
        [[ -z "$ID_SERIAL" ]]
        echo "/dev/$devname - $ID_SERIAL"
    )
done
```

...set right permissions (give execution permission to script `chown +x file`) and run...

And in your output you can find something like this (in my case I have a CC2531)...

```
...
/dev/bus/usb/001/011 - Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0019369F73
/dev/ttyACM0 - Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0019369F73
...
```

So...your `docker-compose.yml` will be...

```yaml
services:
  home-assistant:
  container_name: home-assistant
  image: ghcr.io/home-assistant/home-assistant:stable
  volumes:
  - /home/pi/homeAssistant:/config
  devices:
  - /dev/ttyACM0:/dev/ttyACM0
  environment:
  - TZ=Europe/Rome
  privileged: true
  restart: always
  ports:
  - “8123:8123”
```
