### DISCUSSION TITLE
HA: creazione card con parametri ?

### DISCUSSION THREAD

**Discussion by edoardomariconda** [indomus/forum#2009] [HUB: Home Assistant]
Ciao a tutti.

Mi sono avvicinato ad HA da un paio di mesi e sto scoprendo i tanti aspetti che mi affascinano.

Ho creato alcune card personalizzate (abbastanza corpose di codice) relativamente a varie entità (termostatiche, tapparelle, clima, ...) e dovendole "duplicare" per le varie entità rischio di fare qualche errore di trova/sostituisci. Inoltre ogni volta che modifico la devo riportare su tutte le altre.

Mi chiedevo se c'è un modo di creare una card "master" che mi permettesse di indicare quelle 2-3 variabili necessarie per duplicarle (un pò come fare uno script che viene richiamato con le varie variabili).

Mi sapreste indicare come fare?
Grazie.

**Comment by 50494554524F** [comment]
usa lovelace_gen, lo trovi in hacs

**Comment by edoardomariconda** [comment]
Buongiorno, grazie per la dritta.

Ho installato l'integrazione e copiato le righe
```
lovelace_gen:

lovelace:
  mode: yaml
```
nel file `configuration.yaml`.
Una volta riavviato HA mi sono ritrovato con la plancia predefinita completamente riscritta in automatico con le varie entità presenti; presumo che in qualche modo abbia configurato HA per la gestione automatica.
Cancellando le righe e riavviando è tutto tornato come prima.

La domanda che ho è semplice: come si usa "lovelace_gen" ?
E' necessario inserire tali righe nel file `configuration.yaml` ?
Devo modificare a manina il codice della singola plancia o posso continuare a modificare le singole card come faccio ora ?
Eventualmente come faccio a dividere i file/integrare i file e quali directory utilizzare ?
C'è una guida più completa di quella scritta dall'utente che spieghi qualcosa in più ?
Grazie.

**Reply by 50494554524F** [reply]
leggi la guida e fai delle prove, è scritto tutto lì... ti posto un mio template di esempio per creare una card con un grafico

```
# lovelace_gen



#
#     template:
#
#       name: template-chart.yaml
#
#       description: generates the yaml code for a chart card
#
#       dependencies:
#
#         integrations:
#
#           - hass-lovelace_gen
#
#         modules:
#
#           - lovelace-card-mod
#
#       usage:
#
#         - !include
#
#           - template-chart.yaml
#
#           - params:
#
#               entity: entity_id                                   #  entity_id of the entity to show
#
#               name: string                                        #  override the name to show [ optional ]
#
#               icon: string                                        #  override the icon to show [ optional ]
#
#               hours_to_show: int                                  #  number of hours to show in the graph [ optional ]
#
#               tap_action:                                         #  [ optional ]
#
#                 ......
#
#               double_tap_action:                                  #  [ optional ]
#
#                 ......
#
#               hold_action:                                        #  [ optional ]
#
#                 ......
#



type: 'vertical-stack'

cards:



  - type: sensor

    entity: {{  params.entity  }}
    
    {%  if params.name is defined  %}
    
    name: '{{  params.name  }}'

    {%  else  %}

    name: ' '
    
    {%  endif  %}
    
    {%  if params.icon is defined  %}
    
    icon: '{{  params.icon  }}'
    
    {%  endif  %}

    graph: none

    detail: 2

    card_mod:

      style: |

        ha-card {

          background: none !important;

        }
        
        .header {

          display: none !important;
          
        }
        
        .name {
        
          font-weight: normal !important;
          
        }
  
        .name::after {
          
          {%  if params.name is not defined  %}

          content:
          
            '{%  raw  %}{{{%  endraw  %}
            
                state_attr( '{{  params.entity  }}', 'localization_name' )
            
            {%  raw  %}}}{%  endraw  %}';
          
          {%  endif  %}
          
        }
        
        .icon {
        }
        
        .info {
        
          margin: 12px 0px -1.5em 6px !important;
          
        }



  - type: history-graph

    card_mod:

      style:

        .: |

          ha-card {

            background: none !important;

          }

        state-history-charts $ state-history-chart-line $ ha-chart-base $: |

          .chartLegend {

            display: none !important;

          }

    {%  if params.hours_to_show is defined  %}
    
    hours_to_show: {{  params.hours_to_show  }}
    
    {%  endif  %}

    entities: 

      - entity: {{  params.entity  }}
```
c'è un po' tutto per imparare a creare template...

**Comment by edoardomariconda** [comment]
Buonasera.

Sono riuscito a suddividere la dashboard in più files e creare degli oggetti card parametrizzati come volevo.
Grazie per la dritta e per gli esempi.

**Comment by edoardomariconda** [comment]
Buongiorno.

Sono di nuovo qui perchè, nonostante l'interfaccia funzionasse come volevo, appena ho riavviato HA mi sono ritrovato in modalità provvisoria.
Dopo vari tentativi ho visto che il problema sembrerebbe verificarsi se provo a includere un file passando dei parametri.
In pratica:

`ui-lovelace.yaml`:
```
resources:
  - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
  - url: /hacsfiles/bar-card/bar-card.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/stack-in-card/stack-in-card.js
    type: module
  - url: /hacsfiles/light-entity-card/light-entity-card.js
    type: module
  - url: /hacsfiles/battery-state-card/battery-state-card.js
    type: module
  - url: /hacsfiles/tesla-style-solar-power-card/tesla-style-solar-power-card.js
    type: module
  - url: /hacsfiles/lovelace-hui-element/hui-element.js
    type: module
  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /hacsfiles/apexcharts-card/apexcharts-card.js
    type: module


views:
  - !include lovelace/tapparelle/tapparelle_view_test_single.yaml
```

Il file `tapparelle view_test_single.yaml` è:
```
# lovelace_gen
theme: Backend-selected
icon: mdi:window-shutter
title: Tapparelle
path: tapparelle
badges: []
cards:
  - !include 
    - tapparella_card_test_single.yaml
    - title: Tapparella Balcone Cucina
      cover_entity_id: cover.tapparella_balcone_cucina
      cover_state: sensor.tapparella_balcone_cucina_stato
      cover_pos_act_counter: counter.tapparella_balcone_cucina_posizione_attuale
      cover_pos_act_sensor: sensor.tapparella_balcone_cucina_posizione_attuale
```

mentre il file `tapparella_card_test_single.yaml` è:

```
# lovelace_gen
type: entities
title: {{ title }} 
show_header_toggle: false
entities:
  - entity: {{ cover_pos_act_sensor }} 
    name: 'Posizione (0:chiusa - 100:aperta) :'
    tap_action:
      action: none
```

In questo modo provo a ricaricare l'interfaccia (e puntini in alto a destra e poi "aggiorna") e funziona bene, mentre al riavvio HA va in modalità provvisoria.
Dai test la parte incriminata sembrerebbe essere:
```
  - !include 
    - tapparella_card_test_single.yaml
    - title: Tapparella Balcone Cucina
      cover_entity_id: cover.tapparella_balcone_cucina
      cover_state: sensor.tapparella_balcone_cucina_stato
      cover_pos_act_counter: counter.tapparella_balcone_cucina_posizione_attuale
      cover_pos_act_sensor: sensor.tapparella_balcone_cucina_posizione_attuale
```

Ho provato a dare uno spazio dopo l'esclamativo (`-! include` invece di `- !include`) ed HA parte senza problemi, salvo poi mostrare la scritta "mapping values are not allowed here in "/config/lovelace/tapparelle/tapparelle_view_test_single.yaml", line 10, column 12".
Sembra che non gli "piaccia" il passaggio di parametri dal `- title:` in poi.
Dai vari post online e vari forum la sintassi mi sembra corretta.
Cosa mi potete dire ?
Grazie.

**Reply by 50494554524F** [reply]
lovelace_gen non funziona dentro ui-lovelace.yaml, riorganizza di nuovo per lasciare questo file vuoto e nella directory principale...

**Reply by edoardomariconda** [reply]
Grazie della risposta, ma non ho capito.....
Se guardi i miei files, in `ui-lovelace.yaml` non c'è la stringa `# lovelace_gen` all'inizio, perchè ho letto (e sperimentato) che non funziona.
Il file in questione contiene solo le risorse ed il singolo file da includere (che fa da master).
La stringa `# lovelace_gen` è presente solo negli altri files.
Cosa c'è di sbagliato ?
Grazie.

**Reply by 50494554524F** [reply]
il file ui-lovelace lascialo vuoto e cambia con qualcosa del tipo

`lovelace: !include /config/casa/lovelace/dashboards.yaml`

in configuration.yaml... ci metti la lista delle dashboard, per ogni dashboard ti crei un file con le views (come hai già fatto)

in questo modo si previene qualsiasi problema con ui-lovelace, poi  vediamo se c'è altro, senza provarlo mi sembra giusto :D

**Reply by edoardomariconda** [reply]
Sei andato veloce .... non ti ho capito ....
Il mio file `configuration.yaml` è il seguente:
```
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages/

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# SSL Certificate Remote Connection
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  
# activation of python_scripts
python_script:

logger:
  default: critical
  logs:
    # log level for HA core
    homeassistant.core: fatal

api:

lovelace_gen:

lovelace:
  mode: yaml  #yaml/storage
```

Se metto `lovelace: !include ...` e nel nuovo file metto il contenuto di `ui-lovelace.yaml` lasciando quest'ultimo completamente commentato, mi dà errore.
Come metto la dashboard che mi interessa ?
Considera che ne ho solo una con varie viste.
Grazie.

**Reply by 50494554524F** [reply]
in configuration.yaml metti
`lovelace: !include /config/casa/lovelace/dashboards.yaml`
e cancella la riga con mode etc
nel file dashboards.yaml
```
mode: yaml
resources:
  qui le risorse
dashboards:
  nomedashboard:
    title: 'nomedashboard'
    icon: 'hass:iconadashboard'
    mode: yaml
    filename: /config/casa/lovelace/views.yaml
    show_in_sidebar: true
```
in views.yaml ci metti la definizione delle views che già hai fatto... cancella il contenuto del file ui-lovelace.yaml ma lascialo lì
così non ci dovrebbe essere nessun tipo di problema con ui-lovelace.yaml e se il codice ti funziona con aggiorna dovrebbe andare anche con riavvio.... si spera
(cambia percorsi ed aggiungi dashboars/views secondo necessità)
