### DISCUSSION TITLE
Home Assistant automazione per data

### DISCUSSION THREAD

**Discussion by merovese** [indomus/forum#2014] [HUB: Home Assistant]
Ciao a tutti, mi piacerebbe ricevere delle direttive sul come creare un automazione perenne che gestisca l'accensione delle luci di natale (collegata ad una opportuna identità) al tramonto tutti i giorni e lo spegnimento tutti i giorni a partire dll'8 dicembre al 6 gennaio di ogni anno. ho sbattuto il muso sull'input_datetime ma credo che il template faccia di più al caso mio, voi che ne pensate? consigli? grazie mille.

**Comment by nromagna** [comment]
Capisco _la domotica deve fare i lavori per te_... ma fare una semplice automazione di on off luci e il 06 Gennaio la disattivi sino all'anno prossimo??? Tanto già a Settembre ti trovi i panettoni al supermercato quindi di sicuro te lo ricordi di riattivarla in tempo!

**Reply by nromagna** [reply]
Aspetta va che aggiugo che il **mio era un commento puramente sarcastico per fare una battuta**, prima di prendere parole dal capo...
Scherzi a parte potrebbe essere veramente interessante avere un'automazione in basa ad una data...

**Reply by merovese** [reply]
ahahah infatti prima di utilizzare ha facevo così ma credo che la vastità delle automazioni Home Assistant possa aiutarmi a gestirla in modo migliore

**Comment by 50494554524F** [comment]
creati un'automazione che attivi/disattivi un'altra automazione per la gestione delle luci... in questo modo l'avrai attiva solo nei giorni nei quali ti serve ( precisino :D )... la gestione del tramonto la trovi tra gli esempi sul sito di home assistant, oppure alla gestione del tramonto gli aggiungerai una condition sulla data
`

**Reply by merovese** [reply]
Mmmm non mi è molto chiaro, potresti riportarmi un esempio?

**Reply by merovese** [reply]
Io pensavo di poter segnare su google calendar gli eventi dal giorno 8 dicembre al giorno 6 gennaio, del tipo “luci on” ed ha agisse di conseguenza, ma non riesco a capire come far interagire il calendario con l’automazione

**Reply by snakuzzo** [reply]
questo lo puoi fare facile...basta che leggi qui -> https://www.home-assistant.io/integrations/google/

**Reply by merovese** [reply]
Scusa il ritardo ma tra lavoro e bambini….
Ho provato a districarmi tra le guide di automazioni con Google calendar, ma ad essere sincero ho capito come funziona ma non ho capito come attivarla, cioè io ho il trigger “Luci di Natale On” ma non capisco dove indicargli di leggere questo calendario per sapere quando attivare l’automazione…potresti darmi una mano?

**Reply by snakuzzo** [reply]
Ciao.
Allora...ho fatto delle prove in locale. Il giro è abbastanza semplice.
Crei un evento con ad esempio data inizio e fine su google calendar.

![image](https://user-images.githubusercontent.com/7205371/202170251-4dfe8e69-37aa-493f-ae5f-651844f07e4a.png)

Se hai integrato il tuo Google Calendar su core, avrai l'entità di tipo calendar. Mettiamo che ad esempio si chiami `calendar.home_assistant`.

![image](https://user-images.githubusercontent.com/7205371/202169867-31268bde-1884-4492-b0c1-5a54a855b4d0.png)

Sulla dashboard ti crei una card di tipo calendar con l'entità `calendar.home_assistant` e verifichi che ci sia effettivamente l'evento che hai impostato su Google Calendar

![image](https://user-images.githubusercontent.com/7205371/202170560-43383bee-8ad1-455d-a712-9ce7d1a0d9c4.png)

(NOTA: se non trovi l'evento o non è aggiornato ti basta aspettare oppure ricaricare l'integrazione Google Calendar)

A questo punto ti crei l'automazione...

```yaml
automation:

- alias: Esempio accensione luce cameretta
  trigger:
  - platform: calendar
    event: start
    entity_id: calendar.home_assistant
  condition:
  - condition: template
    value_template: "{{ 'accendi luce cameretta' in trigger.calendar_event.description }}"
  action:
  - service: light.turn_on
    data:
      entity_id: light.luce_cameretta 
```
Ovviamente è solo un esempio semplice tra i tanti esempi che puoi trovare [QUI](https://www.home-assistant.io/integrations/calendar#automation)
[QUI](https://www.home-assistant.io/docs/automation/templating/#calendar) invece i dettagli sul trigger

**NOTA IMPORTANTE** ho fatto un test poco fa, ma non scattano i trigger. C'è una issue su core dove ho appena postato anche io ( https://github.com/home-assistant/core/issues/80022 )

**Reply by merovese** [reply]
Quindi potrebbero non funzionare?

**Reply by snakuzzo** [reply]
esatto...segui la issue che ti ho linkato

**Reply by merovese** [reply]
Sto piano piano provando a fare il tutto, minè venuto un dubbio, avendo creato l’evento per tutto il giorno, l’automazione di in automatico si attiverà alla mezzanotte del primo giorno utile?

**Reply by snakuzzo** [reply]
Leggi la doc ufficiale... c'è scritto tutto

**Reply by merovese** [reply]
Ho partorito questo:

```yaml
- alias: NATALE INTERNO ON
  description: ""
  trigger:
    - platform: time
      at: "16:00:00"
    - platform: calendar
      event: start
      entity_id: calendar.luci_di_natale
  condition: 
    - condition: tenplate
      value_templates: "{{ 'accendi luce cameretta' in trigger.calendar_event.description }}"
    action:
    - type: turn_on
      device_id: 832cbd9b52a88124885dfb65b75b19f5
      entity_id: switch.albero_di_natale
      domain: switch
    - type: turn_on
      device_id: 6b8c662737a47e1a2f3d51865b37616c
      entity_id: switch.sonoff_1000b49a01
      domain: switch
  mode: single
```


Ma qualcosa non va

**Reply by snakuzzo** [reply]
mi sono permesso di usare il markdown correttamente nel tuo post.
Quello che hai fatto non ha alcun senso e dovresti riguardarti un attimo cosa sono e come funzionano i trigger.
Quelli sono due trigger separati che non c'entrano nulla l'uno con l'altro.
- Il primo fa scattare l'automazione alle 16, ma la condizione non sarà mai verificata perché nell'oggetto trigger non ci sarà mai un oggetto di tipo `calendar`
- il secondo è quello che abbiamo visto tutto il giorno oggi...e come ti ho detto "non sta funzionando".

Gli eventi senza data inizio e data fine (all day) hanno comunque una data inizio e fine quando viene sincronizzato l'evento con l'entità calendar presente su HA e corrispondono alla mezzanotte del giorno stesso e del giorno dopo.


In sostanza...se non fixano quel problema che ti dicevo, quella action non verrà mai eseguita.
L'unica cosa che puoi fare, in aggiunta, è giocare con l'offset per provare a vedere cosa succede. All'altro utente funziona perché:
- il trigger, visto il bug, non scatta all'orario preciso (gli ho chiesto di fare una prova per verificarlo anche lui, ma non l'ha voluta fare)
- c'è il `wait_for_trigger` per un'altra cosa...e magari prima di arrivare a quanto previsto dal `wait_for_trigger` per qualche motivo (legato probabilmente ad un offset sbagliat) il trigger sull'event start scatta prima.

Infine decidi...o usi il calendar oppure ti fai l'automazione senza il calendar impostando il trigger in maniera diversa con orari specifici e date specifiche

**Comment by blakdog1978** [comment]
Ciao scusa usi editor visuale ?

**Reply by merovese** [reply]
Si

**Comment by blakdog1978** [comment]
Ciao a me semplicemente così sembra funziona come attivazione 

```
alias: Luci portico natale
description: ""
trigger:
  - platform: state
    entity_id:
      - calendar.home_assistant
    attribute: message
    to: luci di natale
condition: []
action:
  - wait_for_trigger:
      - platform: sun
        event: sunset
        offset: "30"
  - service: script.luci_portico_natale
    data: {}
mode: single

```
