### DISCUSSION TITLE
aiuto automazione climatizzatore

### DISCUSSION THREAD

**Discussion by lucaxxaa** [indomus/forum#2035] [HUB: Home Assistant]
Ho due automazioni, Clima On e Clima Off, che agiscono in base alla temperatura di Casa e la disponibilita di potenza del fotovoltaico.

Il problema nasce, che se accendo manualmente il clima, l'automazione clima Off, lo spegne se non c'e' potenza F.V.

E' possibile creare un entità, che assuma valore 1, se il climatizzatore e' accesso manualmente , cosi la userei nelle condition, dell' automazione  clima off, per non fare intervenire l automazione
GRAZIE per i suggerimenti su come si crea 

PS Ho provato a fare un automazione che, se attivo clima manualmente, dai tre utenti di HA spegne l' altra automazione, ma l' attivazione non va. Sbaglio qualcosa nella sintassi ???

```

alias: 7-disabilita Clima OFF
description: "se attivo manualmente clima, spegne automazione \"clima OFF\" "
trigger:
  - platform: event
    event_type: climate.turn_on
    context:
      user_id:
        - 185a812427ee4a5d826d70587a783c7b
        - 73c7c4e234be4236b059a7be5e778707
        - b9379f0f1b944f0fb8e7eddbfec2eb17
    event_data:
      target:
        device_id: 35f5695a25ead8cc527829be5d83ee53
condition: []
action:
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.7_clima_turn_off
mode: single

```

**Comment by lucaxxaa** [comment]
RISOLTO con due automazioni. 
Il Triger e' lo "state" del clima , le condizioni sono , attivazione da parte  utenti fisici ( e non dalle automazioni ) 

Di seguito un esempio , di una, se puo servire :

```

alias:` 7.1-disabilita aut clima/FV
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.condizionatore
    to: heat
  - platform: state
    entity_id:
      - climate.condizionatore
    to: cool
  - platform: state
    entity_id:
      - climate.condizionatore
    to: dry
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: >-
          {{ trigger.to_state.context.user_id ==
          '185a812427ee4a5d826d70587a783c7b' }}
      - condition: template
        value_template: >-
          {{ trigger.to_state.context.user_id ==
          '73c7c4e234be4236b059a7be5e778707' }}
      - condition: template
        value_template: >-
          {{ trigger.to_state.context.user_id ==
          '185a812427ee4a5d826d70587a783c7b' }}
action:
  - service: automation.turn_off
    data: {}
    target:
      entity_id:
        - automation.7_clima_turn_off
        - automation.0_clima_turn_on
mode: `single

```
`
