### DISCUSSION TITLE
Sleep Monitor Withings

### DISCUSSION THREAD

**Discussion by Cusu95** [indomus/forum#204] [GENERALE - Discussioni generiche]
Ciao a tutti ragazzi,
ho un sensore di monitoraggio sonno della withings che sto cercando di integrare. Sarebbe molto utile per alcune automazioni dato che rileverebbe se sono nel letto o meno.
Ho seguito la guida di integrazione, ma tutti i sensori che vengono creati dall'integrazione risultano non disponibili.
Ho cercato su internet ma non ho trovato nulla che potesse aiutarmi.

C'è qualcosa in particolare che va configurato?

**Comment by gforment** [comment]
Io ho una pesa che ho integrato con
```
withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_consumer_secret
  use_webhook: true
```
Tuttavia tutte le misure sono "unknown". 
Attivando i log (homeassistant.components.withings: debug) ho visto che la comunicazione funziona ma anche leggendo forum ufficiali sembra che le API di Withings siano cambiate.
Dovessi avere notizie un merito o dovessi riuscire a farlo funzionare, fammi sapere!
