### DISCUSSION TITLE
esphome anemometro

### DISCUSSION THREAD

**Discussion by lucaxxaa** [indomus/forum#2043] [HUB: Home Assistant]
Buongiorno, ho realizzato con esphome, il mio primo progetto, con anemometro che chiude contatto ed un wemos d1mini esp8266, alimentato con alimentatore a 5 volt specifico da basetta. 
I  due contatti dell anemometro, vanno uno direttamente a GND ed il secondo al pin GPIO14 del esp
I valori del multiply li ho ricavati da grafico fornitomi dalla ditta che produce anemometro  
Nel codice ho inserito il valore "internal_filter: 60ms" per filtrare gli impulsi troppo veloci, magari causati da interferenze

Il problema e' il seguente, stranamente ogni tanto, mi restituisce valori di velocita' non reali esempi 80 km/h di vento, quando invece c'e' un vento debolissimo.
PS il multiply, dovrebbere essere esatto, ed effettivamente la maggior parte del tempo in cui e' in funzione restituisce valori veritieri

Ho  provato a variare i valori di "sliding_window_moving_average" diverse volte oer risolvere

qui il codice 

```
sensor:
  - platform: pulse_meter 
    pin:
      number: GPIO14    #d5
      mode: INPUT_PULLUP
    name: 'windspeed meter'
    icon: 'mdi:weather-windy'
    id: wind_meter
    unit_of_measurement: 'km/h'
    accuracy_decimals: 0
    timeout: 5s
    internal_filter: 60ms   # AGGIUNTA
    filters:
     - multiply: 0.09625  # formula 1/60 * 1.6041667 
     - sliding_window_moving_average: # Helps prevent too many datapoints
         window_size: 2
         send_every: 1

```
