### DISCUSSION TITLE
Climate SmartIR

### DISCUSSION THREAD

**Discussion by SerpikoIT** [indomus/forum#2045] [HUB: Home Assistant]
Buongiorno vorrei usare 3 condizionatori, ho 3 bradlink mini3 che vengono regolarmente visti da HA sono riuscito a configurare configurazione.yaml per 1 solo condizionatore ma appena inserisco un secondo mi da problemi di duplicati il file configuration, mi sapere dare una mano per inserire i 3 condizionatori se possibile ??

Grazie

**Comment by snakuzzo** [comment]
Ciao. Ma se non posti il codice YAML che hai usato, uno come fa ad aiutarti?
Di sicuro hai duplicato le chiavi che NON possono essere duplicate.

**Reply by SerpikoIT** [reply]
Ciao sono Carlo che già aveva postato sul commento della guida e ho provveduto per come mi hai consigliato di scrivere sul forum. 
Questo è Il tuo codice 
```
smartir:

  remote:

  - platform: broadlink
    name: IR Soggiorno
    host: 192.168.188.165
    mac: '78:0F:77:EC:11:4D'

  - platform: broadlink
    name: IR Corridoio
    host: 192.168.188.166
    mac: 'C8:F7:42:16:D0:57'

  climate:

  - platform: smartir
    name: Mitsubishi_Ponente
    device_code: 1124
    controller_data: 192.168.188.165
    temperature_sensor: sensor.router_2_si7021_temperature
    humidity_sensor: sensor.router_2_si7021_humidity
    power_sensor: switch.ponente_pow
```
Questo è ancora valido????

Io ho duplicato il codice e come dici tu mi l'errore è proprio che duplico il codice.

Grazie

**Reply by snakuzzo** [reply]
Ma io cosa ho scritto di là? 
1. Devi usare il markdown quando scrivi il codice, altrimenti non si capisce se hai indentato bene oppure no
2. Ho scritto precisando che ti ho sistemato solo il codice YAML che sintatticamente è corretto, ma non ho provato. Appena posso do un'occhiata

P.S. correggi ed usa il markdown altrimenti elimineremo la discussione

**Reply by SerpikoIT** [reply]
> Ma io cosa ho scritto di là?
> 
> 1. Devi usare il markdown quando scrivi il codice, altrimenti non si capisce se hai indentato bene oppure no
> 2. Ho scritto precisando che ti ho sistemato solo il codice YAML che sintatticamente è corretto, ma non ho provato. Appena posso do un'occhiata
> 
> P.S. correggi ed usa il markdown altrimenti elimineremo la discussione

Spero di esserci riuscito  ad usare il markdown

**Reply by snakuzzo** [reply]
No...hai sbagliato...ritenta

**Reply by SerpikoIT** [reply]
Spero ora di si scusami ma con il cellulare non riuscivo a trovare il tag giusto

**Comment by SerpikoIT** [comment]
Buongiorno allora ho cosi configurato il mio file configuration.ymal 

```
smartir:

  remote:

  - platform: broadlink
    name: AC Cameretta
    host: 192.168.1.10
    mac: 'cameretta'

  - platform: broadlink
    name: AC Cucina
    host: 192.168.1.6
    mac: 'cucina'
    
  - platform: broadlink
    name: AC Salotto
    host: 192.168.1.8
    mac: 'salotto'

  climate:

  - platform: smartir
    name: AC Cameretta
    device_code: 1023
    controller_data: 192.168.1.10
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.stato_accensione

  - platform: smartir
    name: AC Cucina
    device_code: 1023
    controller_data: 192.168.1.6
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.stato_accensione

  - platform: smartir
    name: AC Salotto
    device_code: 1023
    controller_data: 192.168.1.8
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.stato_accensione
```

mi da questo errore il file configuration 

Invalid config for [smartir]: [remote] is an invalid option for [smartir]. Check: smartir->smartir->remote. (See /config/configuration.yaml, line 39).

**Reply by snakuzzo** [reply]
E' errata l'indentazione. Semanticamente quello che hai scritto non è corretto...e te lo dice pure il messaggio di log.
Hai letto la [documentazione](https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md) prima di provare ?

```yaml
smartir:

remote:

- platform: broadlink
  name: AC Cameretta
  host: 192.168.1.10
  mac: 'cameretta'

- platform: broadlink
  name: AC Cucina
  host: 192.168.1.6
  mac: 'cucina'
  
- platform: broadlink
  name: AC Salotto
  host: 192.168.1.8
  mac: 'salotto'

climate:

- platform: smartir
  name: AC Cameretta
  device_code: 1023
  controller_data: 192.168.1.10
  temperature_sensor: sensor.temperature
  humidity_sensor: sensor.humidity
  power_sensor: binary_sensor.stato_accensione

- platform: smartir
  name: AC Cucina
  device_code: 1023
  controller_data: 192.168.1.6
  temperature_sensor: sensor.temperature
  humidity_sensor: sensor.humidity
  power_sensor: binary_sensor.stato_accensione

- platform: smartir
  name: AC Salotto
  device_code: 1023
  controller_data: 192.168.1.8
  temperature_sensor: sensor.temperature
  humidity_sensor: sensor.humidity
  power_sensor: binary_sensor.stato_accensione
```
