### DISCUSSION TITLE
problema con automazione continue_on_error:true

### DISCUSSION THREAD

**Discussion by jard159** [indomus/forum#2058] [HUB: Home Assistant]
Ciao a tutti!
Avrei bisogno di una mano con una automazione utilizzando la funzionalità `continue_on_error:true` introdotta da un pò di tempo in HA. Nella zona in cui mi trovo spesso salta la connessione ad internet e quindi la mia automazione (penultima versione HA) si "pianta"... leggendo sul sito ufficiale di HA mi sembra di capire che la funzionalità `continue_on_error:true` serva proprio a saltare una azione che non riesce ad essere eseguita in modo tale da riuscire ad andare avanti... riporto di seguito il mio codice:

```
- alias: ALARM-WATER
  initial_state: false
  trigger:
  - platform: state
    entity_id: binary_sensor.alarm_water
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_water
    state: 'on'
  action:

  - continue_on_error: true
    repeat:
      until:
      - condition: template
        value_template:  '{{ repeat.index >= 20  }}'

      sequence:
####################################################
# BUZZER ON
####################################################
      - service: switch.turn_on
        continue_on_error: true
        data: {}
        entity_id: switch.buzzer

      - service: persistent_notification.create
        data:
          title: ALARM
          message: "<b>ALARM WATER!</b>"
      - delay: 00:00:01
####################################################
#  SMS
####################################################
      - service: rest_command.sms_allarm_water
        continue_on_error: true
        data: {}
      - delay: 00:00:01
####################################################
# MAIL
####################################################
      - service: notify.mail
        continue_on_error: true
        data:
          message: 'ALARM WATER'
          title: ALARM
      - delay: '00:00:10'


  - service: switch.turn_off
    data: {}
    entity_id: switch.buzzer
  - service: persistent_notification.create
    data:
      title: INFO
      message: "STOP NOTIFICATIONS"
  mode: single

```

In pratica senza internet (quindi senza sms in rest_command e mail in notify) l'automazione si pianta sulla attivazione del buzzer che rimane acceso... dove sbaglio??? grazie mille a tutti!
