### DISCUSSION TITLE
delay non "aspetta"

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#206] [HUB: Home Assistant]
```
- id: '1619243893382'
  alias: Forno off
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: 0490d58acfe808ea5bbe21d5f8860434
    entity_id: switch.bf42664182f59a6aa3iaxe
    domain: switch
  action:
  - type: turn_off
    device_id: 0490d58acfe808ea5bbe21d5f8860434
    entity_id: switch.bf42664182f59a6aa3iaxe
    domain: switch
  mode: single
```
Preciso che l'ho testato solo con ESEGUI AZIONI. Quel _delay_ non viene rispettato e _condition_ viene verificato immediatamente ottenendo (in prova) come risultato lo spegnimento immediato. Il _delay_ mi serve per dare il tempo alla WiFi di riconnettere i dispositivi una volta che è tornata la corrente.
L'automazione invece dovrebbe essere un controllo aggiuntivo su un dispositivo che già di suo è configurato off al ritorno della corrente.

**Comment by snakuzzo** [comment]
```
- id: '1619243893382'
  alias: Forno off
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay:
        hours: 0
        minutes: 5
        seconds: 0
        milliseconds: 0
    - condition: device
      type: is_on
      device_id: 0490d58acfe808ea5bbe21d5f8860434
      entity_id: switch.bf42664182f59a6aa3iaxe
      domain: switch
    - type: turn_off
      device_id: 0490d58acfe808ea5bbe21d5f8860434
      entity_id: switch.bf42664182f59a6aa3iaxe
      domain: switch
  ```
