### DISCUSSION TITLE
Integrazione ZigBee2MQTT e Home Assistant - non crea entità

### DISCUSSION THREAD

**Discussion by Matty1184** [indomus/forum#2072] [HUB: Home Assistant]
Ciao a tutti,
sto configurando ha e mqtt e mi sto perdendo!
ho associato un dispositivo in Zigbee2Mqtt, tutto ok lo vede nell'interfaccia web ma non vedo come entità in HA.
ho provato a riconfiguare MQTT (core-mosquito) ma nulla.
unico dubbio che mi viene è il fatto che in riconfigurazione avanzata compare user e pw e come user c'è home-assistant, come password una stringa infinita. immagino che siano impostazioni di default che ha generato in automatico all'installazione in quanto non li ho inseriti io. vanno variati?
da dove posso iniziare a controllare?
ringrazio tutti in anticipo!

**Comment by KC-inDomus** [comment]
> Ciao a tutti, sto configurando ha e mqtt e mi sto perdendo! ho associato un dispositivo in Zigbee2Mqtt, tutto ok lo vede nell'interfaccia web ma non vedo come entità in HA. ho provato a riconfiguare MQTT (core-mosquito) ma nulla. unico dubbio che mi viene è il fatto che in riconfigurazione avanzata compare user e pw e come user c'è home-assistant, come password una stringa infinita. immagino che siano impostazioni di default che ha generato in automatico all'installazione in quanto non li ho inseriti io. vanno variati? da dove posso iniziare a controllare? ringrazio tutti in anticipo!

devi attivare l'integrazione automatica con Home Assistant nelle impostazioni di ZigBee2MQTT e assicurarti di aver configurato MQTT su Home Assistant in auto-discovery attivo.

**Reply by Matty1184** [reply]
è quello che avevo già fatto 
lato Zigbee2Mqtt
![1](https://user-images.githubusercontent.com/106579001/201482258-7def90e7-270c-4265-8e9a-1f608d0a8bac.jpg)
lato MQTT in ha
![2](https://user-images.githubusercontent.com/106579001/201482290-c3447312-4a09-45e7-bb78-eaa1a99a0f88.jpg)
l'unico dubbio che ho è nell'utente e password che mostra in automatico nella configurazioni avanzate di MQTT che sono di default

**Reply by KC-inDomus** [reply]
guarda i log. se c'è un problema di autenticazione, lo vedi facilmente da lì

**Reply by Matty1184** [reply]
@KC-inDomus intendi i log di HA o di Zigbee2Mqtt?
Zigbee2Mqtt nessun log, 
mosquitto broker ----  2022-11-12 16:42:17: Client <unknown> closed its connection.
HA nessun log

**Reply by Matty1184** [reply]
scusa riporto meglio il log
2022-11-12 16:42:17: Client <unknown> closed its connection.
2022-11-12 16:42:49: Client 2e7DPqpJxGLAnY3LLLmd8I closed its connection.

**Reply by KC-inDomus** [reply]
controlla i log di mosquitto HA e ZigBee2MQTT

**Reply by Matty1184** [reply]
non avevo messo gli apici in user e password di MQTT ma aimè non mi cambia nulla..
la cosa strana la trovo nei log di HA.

```
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Unknown option 'include_device_information' for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'ota' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:57 WARNING (SyncWorker_7) [supervisor.addons.options] Option 'disable_automatic_update_check' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
22-11-12 22:10:58 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.28.2-1
```

**Reply by snakuzzo** [reply]
Hai sbagliato la configurazione di zigbee2mqtt!
E' completamente sbagliata...avrai sbagliato l'indentazione o qualcosa di simile

**Reply by Matty1184** [reply]
ho preso quella della guida (monto una sonoff 3.0 plus)
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
  restartdelay: 1
  initialdelay: 1
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: mqtt_user
  password: mia pw
  version: 5
  include_device_information: true
serial:
  port: /dev/ttyUSB0
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
advanced:
  log_level: info
  pan_id: 6754
  channel: 15
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8080
experimental:
  new_api: true
availability: false
ota:
  update_check_interval: 10
```
