### DISCUSSION TITLE
Automazione, stato della condition

### DISCUSSION THREAD

**Discussion by lucaxxaa** [indomus/forum#2081] [HUB: Home Assistant]
Buongiorno.
Quando scatta il trigger di un automazione , che ha varie condizioni , è possibile nella action, riportare lo stato della condizione che è stata confermata? Se si quel è la sintassi. Grazie

**Comment by snakuzzo** [comment]
Non ho capito.
Se hai una bozza di YAML postalo qui (usando il markdown)

**Reply by snakuzzo** [reply]
@lucaxxaa  posta una bozza di YAML, spiegando bene cosa ti serve.
Così uno cerca di darti un suggerimento.

**Comment by indomus** [comment]
> Buongiorno. Quando scatta il trigger di un automazione , che ha varie condizioni , è possibile nella action, riportare lo stato della condizione che è stata confermata? Se si quel è la sintassi. Grazie

non ha molto senso. Se il blocco condition viene verificato (che ci siano delle or al suo interno o meno), le action vengono eseguite. Se vuoi verificare delle condizioni specifiche nel blocco action, lo fai usando dei template o gli altri costrutti disponibili allo scopo.

**Reply by lucaxxaa** [reply]
Vorrei solo che nella action, mi venga riportato esempio con un messaggio, quale condition, e stata superata. Il trigger è ogni 5 minuti, le condizioni sono due in or, e mi piacerebbe sapere quale è passata.
Pomeriggio posto il codice. Grazie

**Reply by indomus** [reply]
puoi solo e devi verificare le singole condition nell'action.

**Comment by blakdog1978** [comment]
Ciao  io uso l'edir visuale, puoi fare nelle azioni un scegli se la condizione 1 si verifica esegui l'azione e mandi un messaggio x, se la condizione 2 si verifica esegui l'azione e mandi un messaggio y.
Lo so è macchinoso ma io risolverei così... non sono esperto

**Reply by snakuzzo** [reply]
Vai sull'automazione, clicca sui tre puntini in alto a destra e seleziona Edit in YAML

**Reply by blakdog1978** [reply]
ciao lo so come vedere il YAML ...

verrebbe tipo cosi vuota...

```
description: ""
mode: single
trigger:
  - platform: time_pattern
    minutes: /5
condition: []
action:
  - choose:
      - conditions: []
        sequence: []
      - conditions: []
        sequence: []
```

**Reply by snakuzzo** [reply]
Ok.
@lucaxxaa quello che viene chiesto nel primo post però non ha alcun senso.

In parole povere...

Innanzi tutto devi sapere che con la choose le condizioni vengono verificate in OR (e non tutte insieme in AND). La prima che viene verificata (`true`) fa si che vanga eseguita la `sequence`. Da ciò deriva che, nel caso di questo esempio semplice, "solo una sequence" può essere eseguita. Se poi nessuna `condition` è verificata, c'è poi la possibilità (IMHO sempre consigliato) di impostare il `default`. Guardalo come un `if`, `else if`, `else if`, `else`.

Poi considera che sei sempre "tu" a scrivere cosa vuoi eseguire nella `sequence`, quindi sei sempre tu a scegliere cosa farti "notificare"

Es.

```yaml
automation:

- id: prova
  alias: "mia prova"
  trigger:
  - platform: time_pattern
    minutes: /5
  action:
  - choose:
    # IF (Se è mattina)
    - conditions:
      - condition: template
        value_template: "{{ now().hour < 9 }}"
      sequence:
      - service: persistent_notification.create
        data:
          message: "mattina"
    # ELSE IF (Se è sera)
    - conditions:
      - condition: template
        value_template: "{{ now().hour < 18 }}"
      sequence:
      - service: persistent_notification.create
        data:
          message: "sera"
    # ELSE (Se è notte)
    default:
        sequence:
        - service: persistent_notification.create
          data:
            message: "notte"

```
