### DISCUSSION TITLE
DIMINUZIONE DIMENSIONE DATABASE

### DISCUSSION THREAD

**Discussion by manny199** [indomus/forum#2095] [GENERALE - Discussioni generiche]
Ciao a tutti,
il database home-assistant_v2.db raggiunge dimensioni particolarmente importanti di parecchi gigabyte e non trovo rimedio per fare in modo che vi siano scritte quante meno informazioni possibili.
Ho inserito in configuration.yaml le dovute esclusioni come sotto:

```
recorder:
  exclude:
    entities:
      - climate._heating
      - sensor.studio_last_seen
      - sensor.studio_linkquality
      - sensor.studio_battery
      - sensor.studio_battery
      - sensor.studio_linkquality
      - sensor.temperatura_linkquality
      - sensor.temperatura_battery
      - sensor.temperatura_humidity
      - sensor.temperatura_pressure
```
e tante altre che non elenco ma purtroppo continua a crescere a dismisura.
Ho anche creato un'automazione di purge ma poiché voglio monitorare i dati statistici su base annuale, é come se non l'avessi inserita.

C'è qualche altra soluzione più efficace?
