### DISCUSSION TITLE
EspHome - problemi con buzzer

### DISCUSSION THREAD

**Discussion by Pietrogramma** [indomus/forum#2099] [HUB: Home Assistant]
Ciao a tutti, sono un novellino di EspHome.
Ho realizzato un progetto che utilizza un sensore MQ-2 e tre LED, uno verde che si accende quando i valori del gas sono normali, uno giallo che si accende quando i valori del gas sono in un range di allerta e uno rosso quando il i valori del gas sono pericolosi.
In quest'ultimo caso il progetto prevede anche un cicalino sonoro.
Sono riuscito a programmare le automazioni in esphome per fare tutto questo, l'unica cosa che non riesco a fare è il suono continuo del cicalino.
Al momento suona per qualche secondo e poi si ferma, vorrei che suonasse finché il led rosso rimane acceso.
Un altro problema è che il volume del buzzer è basso, come posso alzarlo?
Incollo qui di seguito il docide che ho creato.
Ciao e grazie.
```
esphome:
  name: esp-tutorial
  platform: esp8266
  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:
  

ota:
  password: "084ee2a40de4502d812f603bf7d39c18"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.131
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Tutorial Fallback Hotspot"
    password: "op5zTE1POuUc"

captive_portal:

output:
  - platform: gpio
    id: "green_LED"
    pin: D3

  - platform: gpio
    id: "red_LED"
    pin: D2

  - platform: gpio
    id: "yellow_LED"
    pin: D1
  
  - platform: esp8266_pwm
    pin: D5
    id: passive_buzzer
    
rtttl:
  output: passive_buzzer  

##########

light:
  - platform: binary
    output: "green_LED"
    id: "green"

  - platform: binary
    output: "red_LED"
    id: "red"
  
  - platform: binary
    output: "yellow_LED"
    id: "yellow"
 
###########

sensor:
  - platform: adc
    pin: A0
    id: "gas"
    name: "valore gas"
    update_interval: 1s
    filters:
      - multiply: 100
    unit_of_measurement: "%"
    icon: "mdi:percent"
    on_value_range:
        - above: 40
          then:
            - light.turn_on: red
            - light.turn_off: green
            - light.turn_off: yellow
            - rtttl.play: 'long:d=1,o=5,b=100:e6'
            
            
        - above: 30
          below: 40
          then:  
            - light.turn_on: yellow
            - light.turn_off: green
            - light.turn_off: red
            - rtttl.stop
            
        - below: 30.0
          then:
            - light.turn_on: green
            - light.turn_off: red
            - light.turn_off: yellow
```
