### DISCUSSION TITLE
Sensore di impronte

### DISCUSSION THREAD

**Discussion by eros27sbt** [indomus/forum#2102] [Hardware & Firmware]
Buonasera a tutti,

sto seguendo la guida di InDomus per integrare un sensore di impronte R503:
https://indomus.it/componenti/integrare-un-lettore-di-impronte-digitali-a-home-assistant-via-nodemcu-ed-esphome/

sembrerebbe però che il sensore non riesca a dialogare con ESPHome, ottengo  l'errore "No response received from reader":
<img width="807" alt="Schermata 2022-11-23 alle 01 00 53" src="https://user-images.githubusercontent.com/49732249/203867569-1c5e586f-46fa-462a-b926-83582ba89d64.png">

L'unica differenza rispetto alla guida è che il mio R503 ha un cavo marrone al posto di quello verde, ma ne ho comprati due e sono arrivati entrambi così.

Qualcun altro ha avuto lo stesso problema?

**Comment by fizzi** [comment]
Ciao potresti documentare con qualche foto i collegamenti che hai fatto ? Cosi non saprei aiutarti. Fai vedere il file yaml.

**Reply by eros27sbt** [reply]
Ciao, certo!

Ho cercato di seguire il più possibile lo schema riportato nella guida, le uniche differenze sono:

- il nodeMCU è alimentato via micro USB collegata al portatile
- il sensore di impronte è alimentato a 3,3V da un Arduino (questo perchè posizionando il nodeMCU sulla breadboard mi rimangono accessibili solo i pin su uno dei due lati, mentre per alimentare il sensore direttamente dal nodeMCU avrei bisogno anche del GND che si trova nel lato non accessibile)

![PXL_20221127_194514818](https://user-images.githubusercontent.com/49732249/204157734-c6b2afa7-cd27-451e-bd0c-0f5358da2af3.jpg)

Aggiungo inoltre che il sensore con Arduino funziona correttamente, quindi non è danneggiato.

Di seguito la configurazione yaml di ESPHome:

```yaml
esphome:
  name: esp-fingerprint

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

ota:
  password: "ed986bbd295b4827931083280c2a6851"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Fingerprint Fallback Hotspot"
    password: "4L7h9BuAV4Pg"

captive_portal:
    
uart:
  rx_pin: GPIO14
  tx_pin: GPIO13
  baud_rate: 57600
    
fingerprint_grow:
  sensing_pin: GPIO12
  on_finger_scan_matched:
    - logger.log: "scan matched"
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Impronta autorizzata"
    - delay: 3000ms
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Attesa"
    - fingerprint_grow.aura_led_control:
        state: BREATHING
        speed: 200
        color: BLUE
        count: 1
  on_finger_scan_unmatched:
    - logger.log: "scan unmatched"
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Impronta non autorizzata"
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 2
  on_enrollment_scan:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Impronta acquisita"
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Impronta acquisita"
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: BLUE
        count: 2
    - fingerprint_grow.aura_led_control:
        state: ALWAYS_ON
        speed: 0
        color: PURPLE
        count: 0
  on_enrollment_failed:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Acquisizione impronta fallita"
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 4

api:
  encryption:
    key: "Irl7QrFQs/qaAOaTlcl0zXy5xAKww9e2vvD+b2a24vI="
  services:
  - service: enroll
    variables:
      finger_id: int
      num_scans: int
    then:
      - fingerprint_grow.enroll:
          finger_id: !lambda 'return finger_id;'
          num_scans: !lambda 'return num_scans;'
  - service: cancel_enroll
    then:
      - fingerprint_grow.cancel_enroll:
  - service: delete
    variables:
      finger_id: int
    then:
      - fingerprint_grow.delete:
          finger_id: !lambda 'return finger_id;'
  - service: delete_all
    then:
      - fingerprint_grow.delete_all: 

text_sensor:
  - platform: template
    id: fingerprint_state
    name: "Stato impronta"

binary_sensor:
  - platform: fingerprint_grow
    id: fingerprint_enrolling
    name: "Acquisendo impronta"

sensor:
  - platform: fingerprint_grow
    fingerprint_count:
      name: "Conta impronte"
    last_finger_id:
      name: "Ultimo ID impronta"
    last_confidence:
      name: "Affidabilità ultima impronta"
    status:
      name: "Stato impronta"
    capacity:
      name: "Capacità impronta"
    security_level:
      name: "Livello di sicurezza"
```
