### DISCUSSION TITLE
Termostato non si avvia all'orario programmato

### DISCUSSION THREAD

**Discussion by manny199** [indomus/forum#2104] [GENERALE - Discussioni generiche]
Ciao a tutti,
oggi mi sono accorto che il termostato che comanda lo switch di accensione dei termosifoni non si avvia all'orario programmato.
Nella directory packages ho il seguente script:

```
input_boolean:
  prog1:
    name: Prog1
  prog2:
    name: Prog2
  prog3:
    name: Prog3
  prog4:
    name: Prog4
  riscaldamento:
    name: Riscaldamento
switch:
  - platform: template
    switches:
      riscaldamento:
        value_template: "{{ is_state('input_boolean.riscaldamento', 'on') }}"
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.riscaldamento
        turn_off:
          - service: input_boolean.turn_off
            entity_id: input_boolean.riscaldamento
input_datetime:
  prog1_on:
    name: Prog1 ON
    has_date: false
    has_time: true
  prog1_off:
    name: Prog1 OFF
    has_date: false
    has_time: true    
  prog2_on:
    name: Prog2 ON
    has_date: false
    has_time: true
  prog2_off:
    name: Prog2 OFF
    has_date: false
    has_time: true
  prog3_on:
    name: Prog3 ON
    has_date: false
    has_time: true
  prog3_off:
    name: Prog3 OFF
    has_date: false
    has_time: true
  prog4_on:
    name: Prog4 ON
    has_date: false
    has_time: true
  prog4_off:
    name: Prog4 OFF
    has_date: false
    has_time: true

sensor:
- platform: template
  sensors:
    riscaldamento_prog1:
      value_template: >-
          {% if states('sensor.time') >= state_attr('input_datetime.prog1_on', 'timestamp') | int | timestamp_custom('%H:%M', False) and states('sensor.time') < state_attr('input_datetime.prog1_off', 'timestamp') | int | timestamp_custom('%H:%M', False) %}
            on
          {% else %}
            off
          {% endif %}
    riscaldamento_prog2:
      value_template: >-
          {% if states('sensor.time') >= state_attr('input_datetime.prog2_on', 'timestamp') | int | timestamp_custom('%H:%M', False) and states('sensor.time') < state_attr('input_datetime.prog2_off', 'timestamp') | int | timestamp_custom('%H:%M', False) %}
            on
          {% else %}
            off
          {% endif %}
    riscaldamento_prog3:
      value_template: >-
          {% if states('sensor.time') >= state_attr('input_datetime.prog3_on', 'timestamp') | int | timestamp_custom('%H:%M', False) and states('sensor.time') < state_attr('input_datetime.prog3_off', 'timestamp') | int | timestamp_custom('%H:%M', False) %}
            on
          {% else %}
            off
          {% endif %}
    riscaldamento_prog4:
      value_template: >-
          {% if states('sensor.time') >= state_attr('input_datetime.prog4_on', 'timestamp') | int | timestamp_custom('%H:%M', False) and states('sensor.time') < state_attr('input_datetime.prog4_off', 'timestamp') | int | timestamp_custom('%H:%M', False) %}
            on
          {% else %}
            off
          {% endif %}
input_select:
  modalita:
    name: Modalità
    options:
      - Automatico
      - Manuale
    initial: Automatico
climate:
- platform: generic_thermostat
  name: Termostato
  heater: switch.termosifoni
  target_sensor: sensor.temperatura_temperature
  min_temp: 5
  max_temp: 39
automation:
  alias: Gestione Riscaldamento
  trigger:
  - platform: state
    entity_id: sensor.riscaldamento_prog1, sensor.riscaldamento_prog2, sensor.riscaldamento_prog3, sensor.riscaldamento_prog4
  condition:
  - condition: state
    entity_id: input_select.modalita
    state: 'Automatico'
  - condition: template
    value_template: "{{ states('input_boolean.' + (trigger.entity_id | replace('sensor.riscaldamento_',''))) == 'on' }}"
  action:
  - service_template: >-
      {% if trigger.to_state.state == 'on' %}
        climate.turn_on
      {% else %}
        climate.turn_off
      {% endif %}
    data:
      entity_id: climate.termostato
```
Prima tutto funzionava regolarmente. E' come se eludesse l'input orario
Mi aiutate?
Sto morendo di freddo!!!
Grazie
