### DISCUSSION TITLE
Settagio luminosità minima

### DISCUSSION THREAD

**Discussion by ster1um** [indomus/forum#2111] [HUB: Home Assistant]
è possibile settare un modulo dimmer che per es. vada 100 a 255 come luminosità?

**Comment by snakuzzo** [comment]
Leggi [questa discussione](https://community.home-assistant.io/t/template-light-limit-maximum-and-minimum-brightness-of-light/246128/12)

**Reply by ster1um** [reply]
sto cercando di capirci qualcosa ma risulta assai complesso.
Non capisco come fare l'equazione corretta

**Comment by ster1um** [comment]
questo è il template che sto usando, funziona tutto perfettamente ma mi restituisce due errori.
```
  - platform: template
    lights:
      luce_blu:
        value_template: >
          {% if is_state('light.luce_l1', 'on') %}
            on
          {% elif is_state('light.luce_l1', 'off') %}
            off
          {% endif %}
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.luce_l1
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.luce_l1
        level_template: >
          {% set b = state_attr('light.luce_l1', 'brightness') | float(0) %}
          {{ (1.29 * b - 75.07) | int }}
        set_level:
          service: light.turn_on
          data_template:
            entity_id: light.luce_l1
            brightness: "{{ ((brightness + 75.07) / 1.29) | int }}"
```

```
ERROR (MainThread) [homeassistant.components.template.light] Received invalid light is_on state: for entity light.luce_blu. Expected: on, off, true, false
ERROR (MainThread) [homeassistant.components.template.light] Received invalid brightness : -75 for entity light.luce_blu. Expected: 0-255
```

**Reply by snakuzzo** [reply]
il blocco relativo al `value_template` mi sa che non serve a niente...lo puoi togliere...e così facendo il primo `ERROR` scompare.
Per quanto riguarda il secondo, mi sa che si verifica "SOLO" quando la luce passa ad `off` a causa del fatto che il valore della luminosità (`brightness`) non è proprio presente quando l'entità `light` ha stato `off`.

Così dovrebbe andare...ho testato sulla mia istanza di test e non dà errori

```yaml
light:

  - platform: template
    lights:

      luce_blu:
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.luce_l1
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.luce_l1
        level_template: >
          {% set b = 0 if (state_attr('light.luce_l1', 'brightness') == none) else (state_attr('light.luce_l1', 'brightness') | float(0)) %}
          {{ '0' if (b==0) else (1.29 * b - 75.07) | int }}
        set_level:
          service: light.turn_on
          data_template:
            entity_id: light.luce_l1
            brightness: "{{ ((brightness + 75.07) / 1.29) | int }}"
```
