### DISCUSSION TITLE
HA core e Nginx su docker con docker compose

### DISCUSSION THREAD

**Discussion by array81** [indomus/forum#2119] [HUB: Home Assistant]
Ho HA core su docker tramite docker compose su un Raspberry. Ho attivato l'accesso da remoto tramite duckdns e SSL.
Ora ho la necessità di installare Nginx per far funzionare correttamente l'estensione di terze parti IMOU LIFE (https://github.com/user2684/imou_life).

Per farla breve i server IMOU inviano una richiesta di tipo POST al Raspberry malformata e quindi HA non intercetta la webhook. La cosa è facilmente risolvibile facendo passare la richiesta attraverso Nginx il quale prende in carico al richiesta dalla porta, la "sistema" e la invia a HA. Vorrei far funzionare anche Nginx su docker e usare docker compose.
La mia configurazione tuttavia non funziona:

DOCKER COMPOSE
```
   nginx:
    container_name: nginx
    image: 'nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/MYUSER/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/MYUSER/nginx/log:/var/log/nginx
      - /home/MYUSER/nginx/ssl:/home/MYUSER/nginx/ssl
      - /home/MYUSER/homeassistant/dehydrated/certs/MYNAME.duckdns.org:/home/MYUSER/homeassistant/dehydrated/certs/MYNAME.duckdns.org
    restart: always
```

NGINX
```
user  nginx;
worker_processes  auto;

error_log  stderr;
#pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server_tokens off;
    server_names_hash_bucket_size 64;
    log_format  info  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    log_format debug '[$time_local] "$request" "$status" "$request_body"';

    server {
        server_name MYNAME.duckdns.org;
        ssl_session_timeout 1d;
        
        ssl_session_tickets off;
        ssl_certificate /home/MYUSER/homeassistant/dehydrated/certs/MYNAME.duckdns.org/fullchain.pem;
        ssl_certificate_key /home/MYUSER/homeassistant/dehydrated/certs/MYNAME.duckdns.org/privkey.pem;
        ssl_dhparam /home/MYUSER/nginx/ssl/dhparams.pem;
        
        listen 443 default_server ssl http2;
        listen [::]:443 ssl http2;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:MozSSL:10m;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        proxy_buffering off;

        location /{
            access_log /var/log/nginx/server_access.log debug;
            proxy_pass http://192.168.188.98:8123/;
            proxy_set_header Host $host;
            proxy_redirect http:// https://;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

    }

}
```

Non sono un esperto, c'è qualcuno che può darmi una mano?
Da quanto ho capito Nginx non controlla analizza nessuna richiesta, il file log infatti è vuoto.
Vorrei inoltre limitare la cosa alle sole richieste che avvengono tramite SSL sulla porta di HA e non a tutte.
