### DISCUSSION TITLE
Automazione attivazione switch in funzione di differenza di temperature

### DISCUSSION THREAD

**Discussion by sp2003** [indomus/forum#2120] [HUB: Home Assistant]
ciao a tutti

vorrei realizzare un'automazione con la quale attivare un sonoff con fw tasmota in funzione di una differenza di 2 sensori di temperature e a condizione che una superi 50°C

in pratica se 
sensor.camino_ds18b20_temperature > 50
e 
sensor.camino_ds18b20_temperature > (sensor.puffer_ds18b20_1_temperature + 1)

allora pubblica 

cmnd/tasmotas/camino/POWER ON

ho realizzato questo, secondo voi è giusto?

```
automation:
  - alias: "Attivazione circolatori camino"
    trigger:
      - platform: numeric_state
	entity_id: sensor.camino_ds18b20_temperature
        above: 50
        value_template: {% if (states('sensor.camino_ds18b20_temperature')|int > states(('sensor.puffer_ds18b20_1_temperature')|int +1) ) %}
  
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/tasmotas/camino/POWER"
          payload: "ON"
          retain: false
```

**Comment by snakuzzo** [comment]
Leggendo la documentazione, è sbagliato per quello che serve a te.
Leggi [QUI](https://www.home-assistant.io/docs/automation/trigger/#numeric-state-trigger) ... nello specifico le note in questa parte qui...

![image](https://user-images.githubusercontent.com/7205371/204355161-90c532c3-6907-46e9-9a9d-90b22017a268.png)

**Comment by sp2003** [comment]
ho modificato così

```
automation:
  - alias: "Attivazione circolatori camino"
    trigger:
      - platform: numeric_state
        entity_id: sensor.camino_ds18b20_temperature
        value_template: "{{ state.attributes.value }}"
        above: 50
	  
    condition:
	{% set camino = states('sensor.camino_ds18b20_temperature')|float %}
        {% set puffer = states('sensor.puffer_ds18b20_1_temperature')| float %}
        {{ (camino - puffer)|round(1)  > 1 }}

    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/tasmotas/camino/POWER"
          payload: "ON"
          retain: false
```

la parte della condition l'ho presa dal canale.
siccome vorrei che camino > (puffer + 1) per l'attivazione allora ho corretto così

`{{ (camino - puffer)|round(1)  > 1 }}`

può funzionare?

**Reply by snakuzzo** [reply]
Premesso che credo tu faccia prima a provare con i dev tools, questa automazione, in base a quanto scritto prima, scatta solo quando la temperatura passa da sotto o uguale a 50 ...a sopra 50.
Per riscattare deve prima tornare sotto o uguale a 50 per poi ripassare sopra i 50

**Comment by sp2003** [comment]
dev tool?
c'è documentazione?

**Reply by snakuzzo** [reply]
Per favore fai reply sotto l'ultima risposta. Non creare ogni volta thread nuovi (come hai fatto ora e prima).
Sì che c'è...ma perché chiedi qui e non cerchi prima ? :D

Primo risultato su Google -> https://www.home-assistant.io/docs/tools/dev-tools/

**Reply by snakuzzo** [reply]
Scherzi a parte...lì simulare tutto quanto...dai template alla forzatura degli stati e attributi delle entità.

**Reply by sp2003** [reply]
ho cambiato con il trigger con il template binary sensor. Così può andare?

```
template:
  - binary_sensor:
      - name: "circolatori camino"
	    entity_id: binary_sensor.circolatori
	    device_class: power
            state: >
                {% set camino = states('sensor.camino_ds18b20_temperature')|float %}
                {% set puffer = states('sensor.puffer_ds18b20_1_temperature')| float %}
                {{ camino > 50 }}
                    and {{ (camino - puffer)|round(1)  > 1 }}
			 
automation:
   - alias: "Attivazione circolatori camino"
      trigger:
        - platform: state
	  entity_id: binary_sensor.circolatori
	  to: "on"
		
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/tasmotas/camino/POWER"
          payload: "ON"
          retain: false
```


il mio scopo è sempre quello, attivare i circolatori quando la t camino è > 50 e quando la t camino > (t puffer +1)
queste condizioni devono essere vere entrambe

**Reply by snakuzzo** [reply]
Sì, dovrebbe andare...ma ripeto...testala, non chiedere a noi se può andare :)

**Reply by sp2003** [reply]
ho dovuto fare un po di modifiche poiché la verifica della configurazione andava a buon fine, ma il logs riporta errori. 
sono riuscito a correggere (credo) quasi tutto, ma l'ultimo errore mi sta bloccando, probabilmente c'è un errore di sintassi ma no capisco dove....
```
template:
  - binary_sensor:
      - name: "circolatori_camino"
#        entity_id: binary_sensor.circolatori_camino
        device_class: power
        state: >
          {% set camino = states('sensor.camino_ds18b20_temperature')|float %
          {% set puffer = states('sensor.puffer_ds18b20_1_temperature')| float %}
          {{ camino > 50 }}
             and {{ (camino - puffer) | round(1)  > 1 }}
             
automation:
  - alias: "Attivazione circolatori camino"
    trigger:
    - platform: state
      entity_id: binary_sensor.circolatori_camino
      to: "on"
      
    action:
    - service: mqtt.publish
      data:
        topic: cmnd/tasmotas/camino/POWER
        payload: ON
        retain: false

```

`2022-11-29 17:33:37.952 ERROR (MainThread) [homeassistant.config] Invalid config for [template]: invalid template (TemplateSyntaxError: unexpected '%') for dictionary value @ data['binary_sensor'][0]['state']. Got "{% set camino = states('sensor.camino_ds18b20_temperature')|float % {% set puffer = states('sensor.puffer_ds18b20_1_temperature')| float %} {{ camino > 50 }}\n and {{ (camino - puffer) | round(1) > 1 }}\n \n". (See /config/configuration.yaml, line 182).
2022-11-29 17:33:53.563 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform template is taking over 10 seconds.`

**Reply by snakuzzo** [reply]
Manca la parentesi alla fine di set camino

**Reply by sp2003** [reply]
niente, non va e il problema è il binary_sensor perché se forzo lo stato a on lo switch camino commuta

non so se centri anche il fatto che in avvi di HA il sensore ha lo stato di "sconoscito".
leggevo sul portale di is_states ma a questop punto non sono neanche sicuro che il sensore sia scritto bene.
le due temperature le legge, ma forse le altre condizioni no
<img width="715" alt="Immagine 2022-11-29 212338" src="https://user-images.githubusercontent.com/34820831/204640238-d191a9b2-ae4d-462b-9079-65b792ee1993.png">

**Reply by snakuzzo** [reply]
Hai sbagliato il template nel `binary_sensor`
Come l'hai scritto tu...

```
{{ camino > 50 }} and {{ (camino - puffer) | round(1)  > 1 }}
```

...restituisce `True and True`, invece il template deve restituire `True`. Quindi devi correggere così...

```
{{ camino > 50 and (camino - puffer) | round(1)  > 1 }}
```
 
Quanto allo start di HA invece, ti consiglio di mettere anche il `from: "off"`, proprio per fare in modo che scatti solo quando passa da `off` a `on`

Di seguito il codice corretto...testato...e funzionante:

```yaml
template:
  - binary_sensor:
    - name: "circolatori_camino"
      device_class: power
      state: >
        {% set camino = states('sensor.camino_ds18b20_temperature') | float %}
        {% set puffer = states('sensor.puffer_ds18b20_1_temperature') | float %}
        {{ camino > 50 and (camino - puffer) | round(1)  > 1 }}
             
automation:
  - alias: "Attivazione circolatori camino"
    trigger:
    - platform: state
      entity_id: binary_sensor.circolatori_camino
      from: "off"
      to: "on"
    action:
    - service: mqtt.publish
      data:
        topic: "cmnd/tasmotas/camino/POWER"
        payload: "ON"
        retain: false
```

**Reply by sp2003** [reply]
riprendo la discussione perchè non riesco a far funzionare l'automazione come di deve.
Lo switch.camino si chiude regolarmente quando il binay sensor (t. camino - t. puffer >1 and t. camino >50) passa da spento a acceso ma non si apre quando il binary sensor si apre.
Ho provato a modificare prendendo spunto dalle lezioni sulle automazioni ma lo switch del camino non si apre
```

template:
  - binary_sensor:
      - name: "circolatori_camino"
        device_class: power
        state: >
          {% set camino = states('sensor.camino_ds18b20_temperature')|float %}
          {% set puffer = states('sensor.puffer_ds18b20_1_temperature')| float %}
          {{ camino > 50 and (camino - puffer) | round(1)  > 1 }}
          
automation:
  - alias: "Attivazione circolatori camino"
    trigger:
    - platform: state
      entity_id: binary_sensor.circolatori_camino
      from: "off"
      to: "on"
      
    action:
      - if:
          - entity_id: switch.camino
            condition: state
            state: 'off'
        then:
          - entity_id: switch.camino
            service: switch.turn_on
        else:
          - entity_id: switch.camino
            service: switch.turn_off
```
<img width="374" alt="Immagine 2022-12-10 092817" src="https://user-images.githubusercontent.com/34820831/206842621-6a96d645-08f7-4e02-a571-424d7c19c37c.png">

**Reply by snakuzzo** [reply]
Non ha alcun senso logico quello che hai scritto. Ti serve aggiungere un trigger più una choose (se non vuoi usare una semplice if con un template), non mettere quell'if nella action (che sarebbe eseguita, nel tuo caso, solo quando il binary passa da off a on.

**Reply by sp2003** [reply]
non saprei da dove iniziare...

possibile che comandare uno switch in funzione i un sensore sia così complesso?

**Reply by sp2003** [reply]
```
template:
  - binary_sensor:
      - name: "circolatori_camino"
        device_class: power
        state: >
          {% set camino = states('sensor.camino_ds18b20_temperature')|float %}
          {% set puffer = states('sensor.puffer_ds18b20_1_temperature')| float %}
          {{ camino > 50 and (camino - puffer) | round(1)  > 0 }}
switch:
  - platform: template
    switches:
      camino:
        value_template: "{{ is_state('binary_sensor.circolatori_camino', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.camino
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.camino
```

così può funzionare?

**Reply by sp2003** [reply]
mi rispondo da solo, no

**Reply by snakuzzo** [reply]
Scusa, ma non capisco cosa tu stia facendo.
Per il discorso del sensore hai usato il sensore secondo quella logica.
Ora che c'entra creare uno switch MQTT del camino (pilotato da un device tasmota) che abbia lo stato di un binary sensor?  Anche provando a crearlo così, farai solo un casino enorme.

Il device con tasmota deve essere un'entità a parte di tipo switch.
Ammesso che tu abbia configurato il device tasmota con il topic `camino`, avrai un qualcosa del genere...

```yaml
template:
  - binary_sensor:
    - name: "circolatori_camino"
      device_class: power
      state: >
        {% set camino = states('sensor.camino_ds18b20_temperature') | float %}
        {% set puffer = states('sensor.puffer_ds18b20_1_temperature') | float %}
        {{ camino > 50 and (camino - puffer) | round(1)  > 1 }}


mqtt:

  switch:

  - name: "Camino"
    state_topic: "stat/camino/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/camino/POWER"
    availability_topic: "tele/camino/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false


automation:

  - alias: "Attivazione circolatori camino"
    trigger:
    - id: to_on
      platform: state
      entity_id: binary_sensor.circolatori_camino
      from: "off"
      to: "on"
    - id: to_off
      platform: state
      entity_id: binary_sensor.circolatori_camino
      from: "on"
      to: "off"
    action:
    - service: >
        {% if trigger.id == 'to_on' %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      data:
        entity_id: switch.camino
```

P.S. Non scrivere più sulla chat telegram per sollecitare risposte perché hai fretta di trovare soluzioni. Hai scritto qui, aspetti qui...sempre che qualcuno abbia tempo e possibilità di risponderti. Se non ti sta bene, chiedi altrove.
