### DISCUSSION TITLE
Frigate non funziona perfettamente

### DISCUSSION THREAD

**Discussion by CesareDebian** [indomus/forum#2129] [HUB: Home Assistant]
Buongiorno, riesco a vedere la ipcam con Fregate, ma non riesco a fare altro tipo registrare.
Ecco il file frigate.yaml

```
mqtt:
  host: xxxxxxxxx
  user: xxxxxxxx
  password: xxxxxxxxxxxx
detectors:
  cpu1:
    type: cpu
    num_threads: 3
record:
  enabled: False
  expire_interval: 60
  retain:
    days: 0
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
objects:
  track:
    - person
cameras:
  NC450:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxxxxx
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
```

**Comment by CesareDebian** [comment]
<img width="480" alt="Schermata 2022-11-30 alle 10 54 29" src="https://user-images.githubusercontent.com/109909412/204768791-d451393a-4539-4af6-9dff-aa20be916c6a.png">

**Comment by CesareDebian** [comment]
<img width="1420" alt="Schermata 2022-11-30 alle 11 12 37" src="https://user-images.githubusercontent.com/109909412/204769001-8f5846b3-0088-4f77-8849-ed51fb84b613.png">

**Comment by CesareDebian** [comment]
Inoltre Frigate non rileva movimenti.

**Reply by NdR91** [reply]
C'è molta confusione in quella configurazione.

Ti giro la mia, occhio che sono fermo a Frigate 0.9, ho tutto spento in quanto ho casa nuova ancora col cantiere aperto. Quindi potrebbero essere necessari aggiustamenti.

```
mqtt:
  host: 192.168.1.149
  topic_prefix: frigate
  client_id: frigate
  user: xxxxxx
  password: xxxxxx

detectors:
  coral:
    type: edgetpu
    device: usb
  # cpu1:
  #   type: cpu
  #   num_threads: 2
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

rtmp:
  enabled: True

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: False
  retain:
    default: 10
    objects:
      person: 15

timestamp_style:
  effect: shadow

birdseye:
  enabled: False

objects:
  track:
    - person
  filters:
    person:
      min_area: 35000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7

cameras:
  # SCALE
  scale:

    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.1.143/ch0_0.h264
          roles:
            - detect
            - record
            - rtmp  
  

    detect:
      fps: 5

    motion:
      mask:  566,0,585,35,541,141,655,147,1035,150,1027,487,875,462,798,530,615,720,0,720,0,0
      
    objects:
      track:
        - person
        - cat
        - dog

    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
        required_zones: []
        retain:
          default: 5
```

Questo è solo per darti un punto di riferimento.
