### DISCUSSION TITLE
Aggiornamento fallito di Zigbee2MQTT MQTT error: connect ECONNREFUSED

### DISCUSSION THREAD

**Discussion by Newreader** [indomus/forum#2134] [ZigBee, Z-Wave, Thread, Matter]
Salve,
utilizzo come coordinatore Zigbee2MQTT il SONOFF Zigbee 3.0 USB Dongle Plus ormai da svariati mesi senza problemi. Ho apportato le opportune modifiche al file configuration .yaml che nella mia installazione si trova sotto la directory /opt/zigbee2mqtt/data. Tutto ha sempre funzionato senza problemi.
Adesso mi trovo ad aggiornare la versione di Zigbee2MQTT alla 1.28.4 dalla 1.28.2 (che funziona perfettamente) e purtroppo ho avuto dei problemi.
Dopo aver lanciato i canonici comandi:

sudo docker container stop zigbee2mqtt
sudo docker rm -f zigbee2mqtt
sudo docker rmi -f koenkk/zigbee2mqtt:latest

eseguo l’ulteriore comando per istanziare Zigbee2MQTT su Docker
sudo docker run --init -d --name="zigbee2mqtt" -e TZ=Europe/Rome -v /opt/zigbee2mqtt/data:/app/data --device=/dev/ttyUSB0 --restart unless-stopped --network host koenkk/zigbee2mqtt

e lancio per verifica:
sudo docker logs zigbee2mqtt

ottenendo come risultato (in sintesi):
Zigbee2MQTT:info  2022-12-03 00:58:05: Starting Zigbee2MQTT version 1.28.4 (commit #52e545f)
Zigbee2MQTT:info  2022-12-03 00:58:05: Starting zigbee-herdsman (0.14.76)
Zigbee2MQTT:info  2022-12-03 00:58:07: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2022-12-03 00:58:07: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:info  2022-12-03 00:58:07: Currently 6 devices are joined:
Zigbee2MQTT:warn  2022-12-03 00:58:07: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2022-12-03 00:58:07: Allowing new devices to join.
Zigbee2MQTT:warn  2022-12-03 00:58:07: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2022-12-03 00:58:07: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2022-12-03 00:58:07: Connecting to MQTT server at mqtt://localhost
Zigbee2MQTT:error 2022-12-03 00:58:08: MQTT error: connect ECONNREFUSED ::1:1883
Zigbee2MQTT:error 2022-12-03 00:58:08: MQTT failed to connect, exiting...
Zigbee2MQTT:info  2022-12-03 00:58:08: Stopping zigbee-herdsman...

A questo punto ho dovuto reinstallare la versione 1.28.2 che funziona senza alcun problema.
Ho fatto delle ricerche in rete e nella documentazione di Zigbee2MQTT ma sono state infruttifere.
Per completezza di informazione ho Home Assistant Core con Docker aggiornato all’ultima versione Installato su un Raspberry Pi 3 Model B+.
Qualcun altro ha riscontrato le stesse problematiche? Potete darmi una mano a risolvere il problema? Grazie.

**Comment by KC-inDomus** [comment]
non fate le cose a caso, dico io.
leggi il log: `Zigbee2MQTT:error 2022-12-03 00:58:08: MQTT error: connect ECONNREFUSED ::1:1883`

c'è un problema a livello di connessione col broker. perché ti possa funzionare la precedente questo non lo so e non indago, ma l'indagine che devi fare tu è in questo senso.

**Reply by Newreader** [reply]
Grazie per la risposta. Tuttavia non capisco "non fate le cose a caso, dico io."  non è il mio caso. So bene che dal log si evince che c'è un problema di connessione tra Zigbee2MQTT e il broker MQTT. Quello che non capisco è legato al fatto che da 10 mesi uso il SONOFF Zigbee 3.0 USB Dongle Plus e aggiorno regolarmente le nuove versioni; non ho mai avuto problemi. Ho fatto dei test (anche quelli proposti dalle guide InDomus tipo ./ports.sh | grep USB ) ed è tutto a posto. D'altronde ho installato e configurato ZigBee2MQTT con Docker su Raspberry Pi OS (anch'esso si Docker) e per gli aggiornamenti seguo la procedura descritta sopra. Mai avuto problemi. Con la versione 1.28.2 mi connetto tranquillamente attraverso il  web e vedo tutti i dispositivi collegati. L'unica cosa che dovrei fare in aggiunta è aggiornare il firmware del dongle, ma non penso che possa essere dirimente (ma può darsi che mi sbagli).
Il comando sudo docker ps mi restituisce tutti i docker attivi e con uno status UP per un tempo che è uguale per tutti i docker stessi, mentre quando installo la versione 1.28.4 il docker di Zigbee2MQTT dopo in po' di secondi, disconnettendosi, riparte con il conteggio dello Status.
Ha questo punto vorrei sapere cortesemente quale altro tipo di indagine poteri fare.
Allego screenshot della situazione attuale (anche se parziale perché non riporta tutti i dispositivi Zigbee collegati) del Zigbee2MQTT

![Zigbee2MQTT](https://user-images.githubusercontent.com/49215325/205444595-958cbe06-007d-4bb2-a152-9e7b00405a19.PNG)

**Reply by Scialla** [reply]
Prova a riavviare il container del broker (mosquitto)

**Reply by snakuzzo** [reply]
@Newreader è inutile che posti le schermate di HA, al limite dovresti condividere i log di mosquitto (o comunque del broker MQTT che usi)...oltre alle configurazioni sia di zigbee2mqtt che di mosquitto.

**Reply by Newreader** [reply]
il file di configurazione di zigbee2mqtt (/opt/zigbee2mqtt/data/configuration.yaml) è
```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
  user: XXXXXXXX
  password: xxxxxxxx
serial:
  port: /dev/ttyUSB0
advanced:
  log_directory: /var/log
  log_level: info
devices:
  '0x00178801045c2161':
    friendly_name: '0x00178801045c2161'
    availability: true
  '0x00158d0003134075':
    friendly_name: '0x00158d0003134075'
  '0x00158d00034d7981':
    friendly_name: '0x00158d00034d7981'
  '0xa4c138e8eaafb849':
    friendly_name: '0xa4c138e8eaafb849'
  '0x00124b0025137749':
    friendly_name: '0x00124b0025137749'
  '0x00124b002352b6dc':
    friendly_name: '0x00124b002352b6dc'
  '0x00124b00251421ee':
    friendly_name: '0x00124b00251421ee'
  '0x00124b0025141bcd':
    friendly_name: '0x00124b0025141bcd'
experimental:
  new_api: true
frontend:
  port: 8080
```
il file di configurazione di mosquitto (/srv/mosquitto/config/mosquitto.conf) è:
pid_file /var/run/mosquitto.pid

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

password_file /mosquitto/config/mosquitto.passwd
allow_anonymous false

Non era mia intenzione postare qualcosa di inutile
Il log di  mosquitto ottenuti con il comando:
sudo docker logs mosquitto
è molto lungo, almeno quando tutto funziona con la versione 1.28.2, non so se devo filtrarli con grep (fatemi sapere onde evitare di mettere sul post ancora cose inutili).
Con la versione 1.28.2 di Zigbee2MQTT tutto funziona bene, come ho già scritto, accedo all'interfaccia web e questa sera ho aggiunto altri due dispositivi riconosciuto senza alcun problema, per cui penso che se nelle configurazioni ci fosse stato qualcosa che non andava il sistema avrebbe dovuto segnalarlo prima.
Aggiungo inoltre che attraverso MQTT ho installato una pletora di dispositivi (Tasmota e Shelly) tutti funzionanti.
Vi ringrazio ancora per l'aiuto.
