### DISCUSSION TITLE
Aiuto produzione pannelli fotovoltaici

### DISCUSSION THREAD

**Discussion by tagor-github** [indomus/forum#2147] [HUB: Home Assistant]
Salve a tutti,

ho un sistema FV della Fronius e sto usando la loro integrazione per valorizzare la dashboard Energia.
Spiego brevemente la mia configurazione.

```
template:
  - sensor:
      - name: "Battery Power Charging"
        unit_of_measurement: W
        device_class: power
        state: "{{ max(0, 0 - states('sensor.solarnet_power_battery') | float(default=0)) }}"
      - name: "Battery Power Discharging"
        unit_of_measurement: W
        device_class: power
        state: "{{ max(0, states('sensor.solarnet_power_battery') | float(default=0)) }}"
      - name: "Power Photovoltaics"
        unit_of_measurement: W
        device_class: power
        state: "{{ states('sensor.solarnet_power_photovoltaics') | float(default=0) }}"
```

Queste tre entity, come riportato nella loro documentazione,  le ho poi date in pasto all'integrazione Riemann e usate all'intento della dashboard Energia.
Fino a questo punto tutto funziona correttamente, e i valori prodotti sono uguali a quelli proprietari della app Fronius.

<img width="212" alt="image" src="https://user-images.githubusercontent.com/74494593/206447413-6f9883f1-0a6b-433f-969d-ce4a6fb33d0b.png">

C'è una cosa che però mi sta facendo impazzire.
Avrei bisogno di lavorare giornalmente sul valore "parziale" di energia FV prodotta, ovvero su quel 7,1 che si vede nello screen.
E mi serve a metà giornata, lo devo poter leggere ogni qualvolta ne abbia la necessità.
Non riesco a recuperarlo da nessuna parte, perché Power Photovoltaics è un "totale" che poi immagino la dashboard manipoli per tirare fuori il valore giornaliero.
Quindi anche l'integrazione Riemann è un totale.
Oltretutto lo devo poter resecare a fine giornata, per avere il dato corretto anche il giorno seguente.
Provando a resettare (dai dev tools) lo stato di queste entità, vedo apparire 0 per alcuni secondi e poi riprende il conteggio dal valore che aveva prima.
Pensavo quindi di usare utility_meter, ma non riesco a tirar fuori lo stesso valore (corretto) di produzione FV per poterlo resettare con ciclo daily.

```
utility_meter:
  produzione_fv_giornaliera_prova:
    source: sensor.solarnet_power_photovoltaics
    cycle: daily
  produzione_fv_giornaliera_totale_prova:
    source: sensor.solarnet_energy_total
    cycle: daily
  produzione_fv_giornaliera_totale_prova_3:
    source: sensor.power_photovoltaics
    cycle: daily
```

Ottengo valori che probabilmente non hanno la stessa unità di misura, o comunque sono completamente sballati.

Qualcuno può darmi una mano ??

Grazie mille.
