### DISCUSSION TITLE
Automazioni: assegnare output di un comando ad una variabile

### DISCUSSION THREAD

**Discussion by depahk** [indomus/forum#2149] [HUB: Home Assistant]
Ci ho provato ma non so più dove sbattere la testa, come ho scritto sul gruppo la situazione generale giusto per dare contesto è:

Ho configurato tutto Frigate e sarebbe funzionante, mi manca il Coral che non vorrei pagare 2-3 volte il suo costo quindi mi son messo a giocare con altro e casualmente su AgentDVR (iSpy) che volevo usare temporaneamente solo per la registrazione h24 ho notato che c'è la detection con ReolinkAI che utilizza la detection integrata in alcune sue telecamere (io ho le 410w) per appunto fare detection.
Volendo quindi sostituire le automazioni di invio foto e video al rilevamento di "cose" che avevo su Frigate, mi son messo a clonare la situazione su AgentDVR (anche se più complessa, se poi funzionerà e avrà senso farò anche una specie di guida).

Ho configurato MQTT e praticamente è tutto funzionante se non fosse per questo passaggio mancante: dato che su AgentDVR tramite MQTT non viene inviato un ID per identificare quell'evento, l'unica cosa che vedo possibile è andarsi a ripescare gli ultimi eventi e prendere il nome del file per poi inviarne il contenuto; praticamente rispetto a Frigate bisogna fare un passaggio in più (dove potrebbero esserci anche errori di logica a causa di eventi ravvicinati) per prendersi quel nome file. 

Non ho e non dovrei avere altri problemi oltre al nocciolo della questione: mettere il json ottenuto dalla curl dentro una variabile (a cui poi andrò a leggere il contenuto tramite tempalte e json per recuperare quel che serve).

Di seguito uno snippet dell'automazione

```
  action:
    - service: notify.gruppocontroller
      data:
        message: "{{trigger.payload.split(',')[5]}} detected a {{trigger.payload.split(',')[8]}}"
    - variables:
        ispyevents:
          - service: shell_command.curl_get
            data:
              url: "http://agentdvr:8090/q.json?cmd=getevents&oid={{trigger.payload.split(',')[1]}}&ot={{trigger.payload.split(',')[2]}}"
    - service: notify.gruppocontroller
      data:
        message: "{{ispyevents}}"
```

il service `shell_command.curl_get` è semplicemente questo
```
shell_command:
  curl_get: "curl {{ url }}"
```

Così ovviamente non funziona, stavo guardando anche [Command line Sensor](https://www.home-assistant.io/integrations/sensor.command_line/#usage-of-templating-in-command) e [RestfulCommand](https://www.home-assistant.io/integrations/rest_command/) ma il problema è sempre che non si può (o non riesco) ad utilizzarli nelle automazioni oppure con i valori dei template presenti all'interno dell'automazione.

Qualcuno ci è già passato in situazioni simili o ha idee? Il sunto di quel che servirebbe è manipolare l'output di una curl.
