### DISCUSSION TITLE
template per raggruppare due entità

### DISCUSSION THREAD

**Discussion by ster1um** [indomus/forum#2152] [HUB: Home Assistant]
Buongiorno, vorrei raggruppare due entità luci.

In pratica ho la striscia led sotto pensile della cucina a 24v con un modulo zigbee varialuce che però non ha la memoria in caso di blackout.
Avevo pensato di abbinare uno switch 220v sempre zigbee e creare un template che li raggruppasse.

Ho fatto uno template però non funziona il varioluce, mi riporta la corretta soglia di luminosità ma mi dà errore quando provo a variarla da HA.

```
hall:
        friendly_name: "hall"
        value_template: >-
          {% if is_state('light.220v', 'on') %}
            on
          {% elif is_state('light.220v', 'off') %}
            off
          {% else %}
            unknown
          {% endif %}
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.220v
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.220v
        set_level:
          service: light.turn_on
          data_template:
            entity_id: light.dcmodule
            brightness: "{brightness}"

```

**Comment by snakuzzo** [comment]
Prova a correggere il template alla fine (mancano delle parentesi)...

```yaml
        set_level:
          service: light.turn_on
          data_template:
            entity_id: light.dcmodule
            brightness: "{{ brightness }}"
```
