### DISCUSSION TITLE
Componente "Situazione Vaccini COVID-19"

### DISCUSSION THREAD

**Discussion by sainz** [indomus/forum#216] [HUB: Home Assistant]
Ciao a tutti,
mi sono avvicinato da qualche mesetto al mondo di Home Assistant, e sperimentando tra le varie cose, un po' per divertimento, un po' per imparare meglio le "integrazioni custom", mi sono dilettato nel creare un componente che raccogliesse un po' di statistiche sulla situazione attuale delle vaccinazioni COVID-19 in Italia.
I dati sono (o perlomeno dovrebbero esserlo) quelli ufficiali e recuperati dagli opendata messi a disposizione dal Ministero della Salute.
Di fatto ho semplicemente aggiunto un nuovo "sensore" di tipo rest, integrato un nuovo template per rendere più leggibili i dati, ed aggiunto il tutto alla mia dashboard.

Di seguito quindi le porzioni di codice da integrare (io ho preferito creare un nuovo file sensors.yaml, e referenzialo all'interno del file configuration.yaml)

```
  #=========================
  #=== Vaccini COVID-19 IT
  #=========================
  - platform: rest
    resource: https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/anagrafica-vaccini-summary-latest.json
    name: vaccinations_first_dose
    scan_interval: 60
    json_attributes_path: "$.[1]"
    json_attributes:
        - prima_dose
    value_template: "{{ value_json.data | sum(attribute='prima_dose')}}"
  - platform: rest
    resource: https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/anagrafica-vaccini-summary-latest.json
    name: vaccinations_second_dose
    scan_interval: 60
    json_attributes_path: "$.[1]"
    json_attributes:
        - prima_dose
    value_template: "{{ value_json.data | sum(attribute='seconda_dose')}}"
  - platform: rest
    resource: https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/anagrafica-vaccini-summary-latest.json
    name: vaccinations_total_dose
    scan_interval: 60
    json_attributes_path: "$.[1]"
    json_attributes:
        - prima_dose
    value_template: "{{ value_json.data | sum(attribute='totale')}}"
  - platform: rest
    resource: https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/anagrafica-vaccini-summary-latest.json
    name: vaccinations_date_update
    scan_interval: 60
    json_attributes_path: "$.[1]"
    json_attributes:
        - prima_dose
    value_template: "{{ value_json['data'][0]['ultimo_aggiornamento'] }}"


  - platform: template
    sensors:           
        #=========================
        #=== Vaccini COVID-19 IT
        #=========================
        firstdose:
            friendly_name: "Prima Dose"
            value_template: "{{ '{0:_.0f}'.format(states.sensor.vaccinations_first_dose.state | int).replace('_', '.')}}"
        seconddose:
            friendly_name: "Seconda Dose"
            value_template: "{{ '{0:_.0f}'.format(states.sensor.vaccinations_second_dose.state | int).replace('_', '.')}}"
        totaldose:
            friendly_name: "Totali Dosi Somministrate"
            value_template: "{{ '{0:_.0f}'.format(states.sensor.vaccinations_total_dose.state | int).replace('_', '.')}}"
        vaccinedate:
            friendly_name: "Data Aggiornamento"
            value_template: "{{ as_timestamp(states.sensor.vaccinations_date_update.state) | timestamp_custom('%d/%m/%Y') }}"
        populationfirstvaccination:
            friendly_name: "Percentuale Popolazione Prima Dose"
            value_template: "{{ (states.sensor.vaccinations_first_dose.state | float / 59257566 * 100) | round(1) }}"
            unit_of_measurement: '%'
        populationsecondvaccination:
            friendly_name: "Percentuale Popolazione Vaccinata"
            value_template: "{{ (states.sensor.vaccinations_second_dose.state | float / 59257566 * 100) | round(1) }}"
            unit_of_measurement: '%'
```

Una volta riavviato HA, basterà aggiungere una nuova card:

```
type: entities
entities:
  - entity: sensor.vaccinedate
    icon: 'mdi:update'
    name: Data Ultimo Aggiornamento
  - entity: sensor.totaldose
    icon: 'mdi:needle'
    name: Totale Dosi Somministrate
  - entity: sensor.firstdose
    icon: 'mdi:needle'
    name: Totale Prima Dose
  - entity: sensor.seconddose
    icon: 'mdi:needle'
    name: Totale Seconda Dose
  - entity: sensor.populationfirstvaccination
    icon: 'mdi:account-multiple-check'
    name: Percentuale Prime Dose
  - entity: sensor.populationsecondvaccination
    name: Percentuale Popolazione Vaccinata
    icon: 'mdi:account-multiple-check'
title: COVID-19 Vaccinazioni Italia
state_color: false
```

Sicuramente è migliorabile in alcune o tutte delle sue parti :)

![Immagine 2021-04-25 183758](https://user-images.githubusercontent.com/5576977/116001586-667d7280-a5f5-11eb-90aa-d7204322ee9e.png)
