### DISCUSSION TITLE
configurazione entità light con mqtt

### DISCUSSION THREAD

**Discussion by Virgilio123** [indomus/forum#2163] [HUB: Home Assistant]
Buongiorno a Tutti,

Sono passato all'ultima versione di Home Assistant e il vecchio file di configurazione per gli elementi light non funzionano più.
Infatti, per le entità che utilizzano mqtt è cambiata la modalità di configurazione.
Ora, Io ho un file cosi fatto, che  allegavo con il comando : **light: !include light.yaml**

Cortesemente mi potete fornire uno scheletro di un file per includere le entità light?
Grazie.

```yaml
#------------------------------#
# File Luci                    #
#------------------------------#
# Camera di Alessandra 1 Piano
#------------------------------#
- platform: mqtt
  name: "CameraAlessandra"
  state_topic: "stat/CameraAlessandra/POWER"
  command_topic: "cmnd/CameraAlessandra/POWER"
  availability_topic: "tele/CameraAlessandra/LWT"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  retain: false
#------------------------------#
# Camera di Federica 1 Piano
#------------------------------#
- platform: mqtt
  name: "CameraFederica"
  state_topic: "stat/CameraFederica/POWER"
  command_topic: "cmnd/CameraFederica/POWER"
  availability_topic: "tele/CameraFederica/LWT"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  retain: false
#------------------------------#
# Camera di Martina 1 Piano
#------------------------------#
- platform: mqtt
  name: "CameraMartina"
  state_topic: "stat/CameraMartina/POWER"
  command_topic: "cmnd/CameraMartina/POWER"
  availability_topic: "tele/CameraMartina/LWT"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  retain: false
#------------------------------#
# Cameretta 1 Piano
#------------------------------#
- platform: mqtt
  name: "Cameretta"
  state_topic: "stat/Cameretta/POWER"
  command_topic: "cmnd/Cameretta/POWER"
  availability_topic: "tele/Cameretta/LWT"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  retain: false
#------------------------------#
# Salotto Piano Terra
#------------------------------#
- platform: mqtt
  name: "Salotto"
  state_topic: "stat/Salotto/POWER"
  command_topic: "cmnd/Salotto/POWER"
  availability_topic: "tele/Salotto/LWT"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  retain: false
```

**Comment by snakuzzo** [comment]
Come già scritto nei commenti sul blog, per le entità di tipo MQTT non puoi più separarle per logica (luci, switch, etc) con i file sidecar.
Ti consiglio di utilizzare i package. Se non sai cosa sono leggi -> [QUI](https://indomus.it/formazione/i-package-di-home-assistant-cosa-sono-e-come-si-installano/).
Una volta abilitati, ti crei un package per le luci fatto così...

```yaml
#---------------------------------#
# Package Luci                    #
#---------------------------------#
mqtt:

  light:

  #------------------------------#
  # Camera di Alessandra 1 Piano
  #------------------------------#
  - name: "CameraAlessandra"
    state_topic: "stat/CameraAlessandra/POWER"
    command_topic: "cmnd/CameraAlessandra/POWER"
    availability_topic: "tele/CameraAlessandra/LWT"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
  #------------------------------#
  # Camera di Federica 1 Piano
  #------------------------------#
  - name: "CameraFederica"
    state_topic: "stat/CameraFederica/POWER"
    command_topic: "cmnd/CameraFederica/POWER"
    availability_topic: "tele/CameraFederica/LWT"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
  #------------------------------#
  # Camera di Martina 1 Piano
  #------------------------------#
  - name: "CameraMartina"
    state_topic: "stat/CameraMartina/POWER"
    command_topic: "cmnd/CameraMartina/POWER"
    availability_topic: "tele/CameraMartina/LWT"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
  #------------------------------#
  # Cameretta 1 Piano
  #------------------------------#
  - name: "Cameretta"
    state_topic: "stat/Cameretta/POWER"
    command_topic: "cmnd/Cameretta/POWER"
    availability_topic: "tele/Cameretta/LWT"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
  #------------------------------#
  # Salotto Piano Terra
  #------------------------------#
  - name: "Salotto"
    state_topic: "stat/Salotto/POWER"
    command_topic: "cmnd/Salotto/POWER"
    availability_topic: "tele/Salotto/LWT"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
```
