### DISCUSSION TITLE
Automazioni con eventi con il nuovo Calendar di HA 2022.12

### DISCUSSION THREAD

**Discussion by nromagna** [indomus/forum#2167] [HUB: Home Assistant]
Ciao a tutti!
Ho aggiunto il nuovo calendario in HA e riesco ad aggiungere correttamente i nuovi impegni, ma non capisco come utilizzarli dopo nelle automazioni.
Cioè creo l'evento "Accendi albero di natale" (visto il periodo) tutti i gg dalle 17.00 alle 20.00, però nelle automazioni come posso dire di utilizzare quel determinato evento... sbaglio mi sembra di vedere solo il "calendario" e NON lo specifico evento...
![image](https://user-images.githubusercontent.com/79841098/207005379-b49edfc9-e97d-4909-b371-f9747c96dd24.png)

Grazie in anticipo.

**Comment by snakuzzo** [comment]
Semplice esempio

```yaml
automation:

- alias: Calendar
  trigger:
  - platform: calendar
    event: start
    entity_id: calendar.mio_calendario
  action:
  - service: persistent_notification.create
    data:
      message: "{{ trigger.calendar_event }}"
```

**Reply by Scialla** [reply]
Mi permetto di aggiungere l'altro esempio della doc, visto che vuole accendere una presa/luce, dove si capisce un po meglio:
```
automation:
  alias: Front Light Schedule
  trigger:
    - platform: calendar
      event: start
      entity_id: calendar.device_automation
    - platform: calendar
      event: end
      entity_id: calendar.device_automation
  condition:
    - condition: template
      value_template: "{{ 'Front Lights' in trigger.calendar_event.summary }}"
  action:
    - if:
        - "{{ trigger.event == 'start' }}"
      then:
        - service: light.turn_on
          entity_id: light.front
      else:
        - service: light.turn_off
          entity_id: light.front
  mode: queued
  ```

**Reply by nromagna** [reply]
Dove sbaglio?

```
alias: Accendi Luce
description: ""
trigger:
  - platform: calendar
    event: start
    entity_id: calendar.home_assistant    --> nome calendario
  - platform: calendar
    event: end
    entity_id: calendar.home_assistant      --> nome calendario
condition:
  - condition: template
    value_template: "{{ 'Front Lights' in trigger.calendar_test }}"      --> test = nome dell'evento nel calendario
action:
  - if:
      - "{{ trigger.event == 'start' }}"
    then:
      - service: light.turn_on
        entity_id: light.retro  ###   --> nome luce
    else:
      - service: light.turn_off
        entity_id: light.retro    --> nome luce
mode: queued

```
