### DISCUSSION TITLE
Integrazione Legrand Home + Control

### DISCUSSION THREAD

**Discussion by Matty1184** [indomus/forum#2170] [GENERALE - Discussioni generiche]
Ciao a tutti, sto integrando Legrand Home+Control in HA tramite api.
vi spiego con esattezza cosa ho fatto in modo che capiate se ho saltato un passaggio.
registrato come da https://www.home-assistant.io/integrations/home_plus_control/#subscription_key su sito legrand
creato una nuova app inserendo nel "First Reply Url" l'indirizzo web di HA esterno tramite duckdns esempio https://mioindirizzo.duckdns.org:portaha, approvata da Legrand e riveto via mail Client ID e Secret ID.
inserito nel configuration.yaml
```
home_plus_control:
  client_id: codice_ricevuto
  client_secret: codice_ricevuto
  subscription_key: mai_mail_di_registrazione_legrand
```
riavvio, tento di scaricare l'intergrazione "Legrand Home + Control" avvio e mi apre una pagine web esterna con questo codice/errore
```
{
  "error": "invalid_request",
  "error_description": "The reply url host my.home-assistant.io doesn't match with the ones configured on the application"
}
```
dove sto sbagliando?
