### DISCUSSION TITLE
Notifiche a più destinatari tramite Pushbullet

### DISCUSSION THREAD

**Discussion by reiner348** [indomus/forum#2179] [HUB: Home Assistant]
Ciao a tutti!
Ho un problema, probabilmente banale ma che non riesco a risolvere... 
Vorrei che all'attivazione di una automazione, HA mandi sul mio cellulare e quello di mia moglie una notifica. Ho provato separatamente, commentando un blocco service, e funziona perfettamente, ma se attivo entrambi i service arriva solo a uno dei due. Credo sia un errore di sintassi... Il codice è questo:
```
 - id: '1669979887591'
  alias: Test tag nfc
  description: ''
  trigger:
  - platform: tag
    tag_id: nascosto
  action:
  - service: notify.reiner
    data:
      title: Lavatrice
      message: 'La lavatrice ha finito'
  - service: notify.cri
    data:
      title: Lavatrice
      message: 'La lavatrice ha finito'
```
Qualche suggerimento?
Già che ci sono, avrei anche una domanda sugli id delle automazioni: posso metterci il numero che voglio purché univoco o ci sono restrizioni?
