### DISCUSSION TITLE
Condizioni

### DISCUSSION THREAD

**Discussion by nromagna** [indomus/forum#2180] [HUB: Home Assistant]
Ciao a tutti, una paio di domadine... ho creato la seguenre automazione che in teoria mi dovrebbe avvisare se un toner scarseggia.

```
alias: Toner in esautimento
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.dcp_9270cdn_black_toner_remaining
    below: 10
    id: BLACK
  - platform: numeric_state
    entity_id: sensor.dcp_9270cdn_yellow_toner_remaining
    below: 10
    id: YELLOW
  - platform: numeric_state
    entity_id: sensor.dcp_9270cdn_cyan_toner_remaining
    below: 10
    id: CIANO
  - platform: numeric_state
    entity_id: sensor.dcp_9270cdn_magenta_toner_remaining
    below: 10
    id: MAGENTA
condition:
  - condition: zone
    entity_id: person.nicola
    zone: zone.ufficio
action:
  - if:
      - condition: or
        conditions:
          - condition: trigger
            id: BLACK
          - condition: trigger
            id: YELLOW
          - condition: trigger
            id: CIANO
          - condition: trigger
            id: MAGENTA
    then:
      - service: notify.telegram_nicola
        data:
          message: Toner in esaurimento
mode: single
```

Non capisco se funziona, ossia se eseguo SOLO l'azione non da errore, ma se eseguo per test tutta l'automazione non mi arriva nessun messagio. Cosa che se non metto il notify nella condizione ma nell'azione mi arriva.

Sbaglio io o cosa?

Grazie a tutti.
