### DISCUSSION TITLE
Problemi con Modbus

### DISCUSSION THREAD

**Discussion by jo69t** [indomus/forum#2202] [HUB: Home Assistant]
Ciao a tutti, innanzi tutto complimenti per questa comunità, ho un problema con la comunicazione in modbus, premetto sono un vero e proprio dilettante,
il mio scopo è quello di visualizzare e scrivere dei parametri su una scheda della Carel che gestisce una pompa di calore.
ho seguito tutti gli esempi delle splendide guide che avete fatto, modo particolare "Integrare componenti Modbus via TCP o seriale su Home Assistant", purtroppo non riesco a collegarmi, inoltre quando nel file YAML scrivo il codice non riesco neanche a trovare i sensori.
Chiedo vivamente un vostro aiuto.
Utilizzo come adattatore Usb/Modbus questo come da voi consigliato https://indomus.it/link/search-adattatore-modbus-usb/, il codice scritto su configuration.yaml è il seguente:
```
modbus:
  - name: hub1
    close_comm_on_error: true
    delay: 5
    timeout: 5
    type: serial
  - name: hub1
    type: serial
    baudrate: 9600
    bytesize: 8
    method: rtu
    parity: N
    stopbits: 1
    port: serial/dev/ttyUSB0    
 
    sensors:
      - name: Ritorno_acqua
        slave: 1
        address: 3
        input_type: holding
        unit_of_measurement: °C
        state_class: measurement
        count: 1
        scale: 0.1
        offset: 0
        precision: 1
        data_type: integer      
   ```    
e mi pongo qualche domandina:  " port: serial/dev/ttyUSB0" è corretto?, o bisogna immettere in che porta si inserisce?, eventualmente come si trova l'indirizzo della porta USB?
Perchè se configuro un sensore non lo vedo nell'elenco dei sensori?
Grazie spero tanto di un vostro grande aiuto
