### DISCUSSION TITLE
Automazione HA incremento di temperatura - Sonoff TH : Test Caldaia OK

### DISCUSSION THREAD

**Discussion by piano9191** [indomus/forum#2204] [HUB: Home Assistant]
Buongiorno, 
Ho scritto questa automazione ma non funziona nel mio HA, ci devono essere errori di sintassi nel codice yaml:
Voglio creare un'automazione che quando la temperatura aumenta --> mi mandi una mail: Caldaia funziona bene

Codice:

```
- alias: Controller_Boiler_works_good
  trigger:
    - platform: numeric_state
      entity_id: sensor.sonoff_XXXXX_temperature
      #value_template: '{{ #states.sensor.sonoff_XXXXX_temperature.attributes.current_temperature }}'
      value_template: '{{ states(sensor.sonoff_XXXXX_temperature) }}'
  condition:
  - condition: template
    value_template: '{{ trigger.from_state.state < trigger.to_state.state }}'
  - platform: state
    entity_id: switch.sonoff_XXXXX
    from: 'off'
    to: 'on'
  action:
    - service: notify.mail
      data:
        message: OK Boiler works good
        title: OK Boiler works good
```

**Comment by snakuzzo** [comment]
Due cose...
1. utilizza il markdown per il codice (mi sono permesso di editare ed inserire i backtick. A tal proposito leggi [QUI](https://github.com/indomus/forum/discussions/1311))
2. Non è molto chiaro cosa tu voglia fare, ma comunque credo sia sbagliata.

Nello specifico io capisco che vuoi che ad ogni variazione della temperatura scatti l'automazione e venga verificato che la nuova temperatura sia maggiore di quella precedente e che lo switch sia su on. Ma se aumenta la temperatura ti serve davvero questa seconda condizione...dovrebbe essere implicita, credo.

Ad ogni modo prova così (scritta al volo senza testare):

```yaml
automation:

- alias: Controller_Boiler_works_good
  trigger:
  - platform: state
    entity_id: sensor.sonoff_XXXXX_temperature
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state > trigger.from_state.state }}"
  - condition: state
    entity_id: switch.sonoff_XXXXX
    state: "on"
  action:
  - service: notify.mail
    data:
      message: OK Boiler works good
      title: OK Boiler works good
```

**Reply by piano9191** [reply]
Grazie mille per la risposta!!!

Codice funzionate ma non al livello operativo(poiché subito mi arriva la mail senza che effettua la verifica sull'incremento di temperatura):

```
- alias: Controller_Caldo_ON
  trigger:
  - platform: state
    entity_id: switch.sonoff_XXXXX
    from: "off"
    to: "on"
  action:
  - service: automation.trigger
    entity_id: automation.CALDAIA_FUNZIONANTE_DOPO_CALDO_ON

- alias: CALDAIA_FUNZIONANTE_DOPO_CALDO_ON
  trigger:
  - platform: state
    entity_id: sensor.sonoff_XXXX_temperature
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state > trigger.from_state.state }}"
  action:
  - service: notify.mail
    data:
      message: OK CALDAIA FUNZIONANTE DOPO CALDO ON
      title: OK CALDAIA FUNZIONANTE DOPO CALDO ON
```

in seguito alla tua dritta ho modificato l'automazione, ma purtroppo non funziona ancora bene come vorrei 
perchè appena lo switch passa da off ad on --> subito mi arriva la mail senza che effettui il controllo "condizione di incremento di temperatura"
Secondo me il problema sta sul tipo di trigger (non deve essere un platform state) ma dovrebbe essere un platform ' numeric state ' -->
--> il mio problema è che non trovo guide o materiale per i comandi value_template, template , ecc ...

Codice dell'automazione che desidero (Codice non funzionante al momento)

```
- alias: Controller_302_Caldo_ON
  trigger:
  - platform: state
    entity_id: switch.sonoff_100077847f
    from: "off"
    to: "on"
  action:
  - service: automation.trigger
    entity_id: automation.CALDAIA_FUNZIONANTE_DOPO_302_CALDO_ON

- alias: CALDAIA_FUNZIONANTE_DOPO_302_CALDO_ON
  trigger:
  - platform: numeric_state
    entity_id: sensor.sonoff_1000fe0851_temperature
    #value_template: "{{ states(sensor.sonoff_1000fe0851_temperature) }}"
    value_template: "{{ sensor.sonoff_1000fe0851_temperature }}"
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state > trigger.from_state.state }}"
  action:
  - service: notify.mail
    data:
      message: OK CALDAIA FUNZIONANTE DOPO 302 CALDO ON
      title: OK CALDAIA FUNZIONANTE DOPO 302 CALDO ON
```

appena avete tempo possiamo vedere se insieme e grazie alle vostre dritte possiamo aggiustare qsto codice con nuemeric_state e value_template ...
grazie mille e auguri di buone feste a tutti voi !!!

**Reply by snakuzzo** [reply]
Così com'è scritto non ha assolutamente senso e non funzionerà mai.
Devi spiegare meglio cos'hai intenzione di fare, ma nel dettaglio.
Io da quello che leggo capisco che tu vuoi semplicemente verificare che la caldaia stia funzionando confrontando la temperatura prima e dopo.

Così potrebbe andare (non testata...scritta al volo) ?

```yaml
automation:

- alias: Controller_Boiler_works_good
  trigger:
  - platform: state
    entity_id: switch.sonoff_XXXXX
    to: "on"
  action:
  - variables:
      start_temperature: "{{ states('sensor.sonoff_XXXXX_temperature') }}"
  - delay:
      seconds: 120
  - variables:
      new_temperature: "{{ states('sensor.sonoff_XXXXX_temperature') }}"
  - service: notify.mail
    data:
      title: "Boiler status"
      message: >
        {% if start_temperature < new_temperature %}
          Bolier OK
        {% else %}
          Boiler KO
        {% endif %}
```

in pratica...
- L'automazione scatta quando accendi la caldaia.
- Istantaneamente salva la temperatura in una variabile.
- Aspetta 2 minuti
- Salva la nuova temperatura in un'altra variabile
- Confronta le temperature
- Se la nuova è più alta della vecchia ti manda un messaggio OK, altrimenti KO

**Reply by piano9191** [reply]
PERFETTOOOOO, GRAZIEEEE !!! Ho modificato il delay a 30 min (1800 sec ) e funziona perfettamente. Però adesso volevo chiederti se è possibile inserire un ciclo repeat until per controllare ogni 30 secondi se c'è stato incremento di temperatura....

EX DI Codice che ho pensato (NON FUNZIONANTE) per questo ipotetico repeat until : 
```
- alias: CALDAIA_FUNZIONANTE_DOPO_CALDO_ON_SEC
  trigger:
  - platform: state
    entity_id: switch.sonoff_XXXX
    from: "off"
    to: "on"
  action:
  - variables:
      start_temperature: "{{ states('sensor.sonoff_XXXX_temperature') }}"
  - variables: a=1
  - repeat:
      sequence:
        - variables: a=a+1
        - delay: 
            seconds: 30
        - variables: 
            new_temperature: "{{ states('sensor.sonoff_XXXX_temperature') }}"
      until:
        - condition:  ??? (AD ESEMPIO a<=60 OPPURE T2>T1+0.1 con T1=temp_iniziale)
          ???
          ????

      - service: notify.mail
    data:
      title: "STATO CALDAIA ENTRO 30 MIN DA ACCENSIONE CALDO "
      message: >
        {% if start_temperature+0.1 < new_temperature %}
          OK_CALDAIA FUNZIONANTE ENTRO 30 MIN_DOPO CALDO ON
        {% else %}
          ALERT_CALDAIA NON FUNZIONANTE ENTRO 30 MIN_DOPO CALDO ON
        {% endif %}
```
Grazie mille , TOP !

**Reply by snakuzzo** [reply]
non ho capito niente dell'automazione che hai scritto

**Reply by piano9191** [reply]
scusami, volevo sapere se è possibile inserire dentro alla sezione action:  un ciclo repeat until che controllare ogni 30 secondi se c'è stato incremento di temperatura ?
Giusto per vedere come si inserisce un ciclo che ogni 30 secondi verifica se si è verificato un aumento, allora esce dal ciclo repeat e mi invia la mail prima dello scadere dei 30 minuti (1800 secondi)

è possibile inserire ciclo repeat , var contatore ecc dentro alle automazioni ? Non l'ho mai fatto o/e visto qualcuno negli esempi online ...

**Reply by snakuzzo** [reply]
Beh.. [QUI](https://www.home-assistant.io/docs/scripts/#repeat-until) c'è l'esempio chiarissimo di come fare.
Potresti usare anche il [WHILE LOOP](https://www.home-assistant.io/docs/scripts/#while-loop).

Esempio (lasciando perdere l'automazione che hai scritto perché non capisco nulla di quello che hai scritto...e prendendo come esempio sempre quella che ti ho scritto io)...

```yaml
automation:

- alias: Controller_Boiler_works_good
  trigger:
  - platform: state
    entity_id: switch.sonoff_XXXXX
    to: "on"
  action:
    repeat:
      while:
      - condition: state
        entity_id: switch.sonoff_XXXXX
        state: "on"
      sequence:
      - variables:
          start_temperature: "{{ states('sensor.sonoff_XXXXX_temperature') }}"
      - delay:
          seconds: 30
      - variables:
          new_temperature: "{{ states('sensor.sonoff_XXXXX_temperature') }}"
      - service: notify.mail
        data:
          title: "Boiler status"
          message: >
            {% if start_temperature < new_temperature %}
              Bolier OK
            {% else %}
              Boiler KO
            {% endif %}
```

in pratica...

- L'automazione scatta quando accendi la caldaia.
- Scatta il ciclo while e...
- Finché la caldaia è accesa...
- Istantaneamente salva la temperatura in una variabile.
- Aspetta 30 secondi
- Salva la nuova temperatura in un'altra variabile
- Confronta le temperature
- Se la nuova è più alta della vecchia ti manda un messaggio OK, altrimenti KO

**Comment by piano9191** [comment]
purtroppo non mi compare nelle automazioni e quindi non va.. anche se l'editor fornisce spunta verde

Codice:

```
- alias: Controller_CALDAIA
  trigger:
  - platform: state
    entity_id: switch.sonoff_XXXX
    from: "off"
    to: "on"
  action:
  - variables:
      a: 1
      start_temperature: "{{ states('sensor.sonoff_XXXXX_temperature') }}"
    repeat:
      sequence:
      - delay:
          seconds: 30
      - variables:
          new_temperature: "{{ states('sensor.sonoff_XXXXX_temperature') }}"
      - if:
          - condition: template
            value_template: "{{ start_temperature+0.1 < new_temperature }}"
        then:
          - service: notify.mail
            data:
              title: "Boiler status"
              message: Bolier OK
          - variables:
            a: 31
        else:
          - variables:
            a: a+1
          - if:
              - condition: template
                value_template: "{{ a > 30 }}"
            then:
              - service: notify.mail
                data:
                  title: "Boiler status"
                  message: Bolier KO
      until:
        - condition: template
          value_template: "{{ a <= 30 }}"
```

**Reply by snakuzzo** [reply]
Non capisco cosa intendi con quello che hai scritto

**Reply by piano9191** [reply]
Ho riscritto per bene il tutto, per farti capire, in 2 modi diversi 

secondo me il nocciolo della questione è la riga di codice
to: "{{ states.sensor.sonoff_XXXX_temperature.state | float + 0.1 }}"

ti posto il 1° modo di codice che ho scritto ed in qsto caso nelle automazioni non mi compare proprio la seguente automazione -> quindi HA non la riconosce e non la eseguirà mai 

1° Modo di codice (scritto da me) : il codice è scritto bene perchè mi compare la spunta verde nell'editor ma quando  riavvio non mi compare nelle automazioni , ovvero non mi compare ' PROVA_Check_for_temperature_increase_302 ' ...

```
- alias: PROVA_Check_for_temperature_increase_302
  trigger:
  - platform: state
    entity_id: switch.sonoff_XXXX
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: sensor.sonoff_1000fe0851_temperature
      to: "{{ states.sensor.sonoff_XXXX_temperature.state | float + 0.1 }}"
      for:
        seconds: 1800
  action:
    - service: notify.mail
      data:
        title: "302 INCREMENTO DI TEMP ENTRO 30 MIN DA ACCENSIONE CALDO 302"
        message:
            OK 302 INCREMENTO DI TEMP ENTRO 30 MIN_DOPO 302 CALDO ON

```

**Reply by snakuzzo** [reply]
La spinta verde ti indica che sintatticamente è corretta, ma non vuol dire che quando va ad eseguirla sia ok.
Controlla i log

**Reply by piano9191** [reply]
2° Modo di codice (scritto da me) : il codice è scritto bene perchè mi compare la spunta verde nell'editor ma quando riavvio mi compare nelle automazioni soltanto 'Check for temperature increase 302' 
MA NON mi compare ' Check temperature302 ' ...

come ti dicevo all'inizio il nocciolo secondo me è la riga 
to: "{{ states.sensor.sonoff_XXXX_temperature.state | float + 0.1 }}"

codice: 
```
- alias: Check for temperature increase 302
  trigger:
    platform: state
    entity_id: switch.sonoff_XXXX
    from: "off"
    to: "on"
  action:
    - event: time_pattern
      event_data:
        seconds: '/10'
        event_type: 'custom_event.check_temperature_302'

- alias: Check temperature302
  trigger:
    platform: event
    event_type: custom_event.check_temperature302
  condition:
    - condition: state
      entity_id: sensor.sonoff_XXXX_temperature
      to: "{{ states.sensor.sonoff_XXXX_temperature.state | float + 0.1 }}"
      for:
        seconds: 10
  action:
    - service: notify.mail
      data:
        title: "302 INCREMENTO DI TEMP ENTRO 30 MIN DA ACCENSIONE CALDO 302"
        message:
            OK 302 INCREMENTO DI TEMP ENTRO 30 MIN_DOPO 302 CALDO ON
```
