### DISCUSSION TITLE
Problema con Caddy

### DISCUSSION THREAD

**Discussion by Matty1184** [indomus/forum#2205] [GENERALE - Discussioni generiche]
Ciao a tutti,
ho installato caddy per fare il reverse proxy, aperto la porta 443 del router facendo un nat della porta stessa.
dall'esterno raggiungo una pagina di prova di caddy ma se digito la porta che in ho assegnato nel file caddy per fare il forward la si apre la pagina dove aggiunge l'estensione /lovelace, al centro il logo di HA e la scritta:
"Unable to connect to Home Assistant.
Retrying in 16 seconds..."

dove sto sbagliando?

**Comment by snakuzzo** [comment]
Devi ricontrollare tutto il cucuzzaro.
Uno non può beccare l'errore al volo se non dettagli meglio.
Il port forwarding è ok ? A parte la 443 hai forwardato anche l'altra porta che vuoi utilizzare per HA ?
Come hai scritto il `Caddyfile`?
Hai controllato che Caddy sia ok ?
Hai controllato i log di Core ?

**Comment by Matty1184** [comment]
CIao Diego, 
porte aperte sul modem la 443 su 443  e 1984 su 1984 (porta assegnata da me).
caddy impostatao in questo modo:
```
args:
  - "--watch"
env_vars: []
log_level: info
non_caddyfile_config:
  destination: localhost
  domain: mydomain.com
  email: your@email.com
  port: 8123
config_path: /config/caddy/Caddyfile
```

Caddyfile 
```
(https_header) {
  header {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}

https://miodominio.duckdns.org { 
  respond "Saluti dal Crew inDomus"
  file_server
}
https://miodominio.duckdns.org:1984 { 
  import https_header
  reverse_proxy http://iphomeassistant:8123
}
```

configuration aggiunto
```
homeassistant:
  external_url: "https://miodominio.duckdns.org:1984"
  internal_url: "http://iphomeassistant:8123"

http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 127.0.0.1
  ```

se digito https://miodominio.duckdns.org mi compare la pagina web con i saluti (riga lasciata nel Caddyfile)
se digito https://miodominio.duckdns.org:1984 mi compare la pagine HA come descritto sopra

quello che trovo strano è che dal mio punto di vista caddy gira porta corretta perchà mostra HA, non capisco il perchè non mi dial il logon

**Reply by snakuzzo** [reply]
Ma come hai installato Caddy ?
Se Core e Caddy sono su Docker e Caddy non è configurato con network mode host, non va bene la parte dei trusted proxies.
In tal caso ricontrolla bene la guida di Caddy, alla fine c'è un ultimo step da seguire

**Reply by Matty1184** [reply]
Caddy sta girando su HA OS

**Reply by snakuzzo** [reply]
è uguale...vale lo stesso discorso.
Inoltre l'addon lo configuri  semplicemente così...

![image](https://user-images.githubusercontent.com/7205371/209483562-c3ca7091-571e-471d-a0f0-85c04ba2ba57.png)

**Reply by Matty1184** [reply]
> è uguale...vale lo stesso discorso. Inoltre l'addon lo configuri semplicemente così...
> 

modificato ma purtroppo non cambia nulla, unica differenza che hopo 60sec. compare il messaggio di errore 400: Bad Request

**Reply by snakuzzo** [reply]
Perché devi seguire le indicazioni sui trusted proxy, come già ti ho detto prima

Leggi [QUI](https://indomus.it/guide/collegarsi-da-remoto-a-home-assistant-via-reverse-proxy/#homeassistant)

**Reply by Matty1184** [reply]
> Perché devi seguire le indicazioni sui trusted proxy, come già ti ho detto prima
> 
> Leggi [QUI](https://indomus.it/guide/collegarsi-da-remoto-a-home-assistant-via-reverse-proxy/#homeassistant)

in teoria l'ho già inserita nella categoria http:
```
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies: 
    - 127.0.0.1
```
ovviamnte ho indicato 127.0.0.1 in quanto essendo addon di HA l'ip è lo stesso.
