### DISCUSSION TITLE
Docker swarm e mysql

### DISCUSSION THREAD

**Discussion by f4b1ux** [indomus/forum#2206] [HUB: Home Assistant]
Ciao, 
sto tentando di portare la mia installazione dockerizzata di HA su uno swarm a 3 nodi. 

Tutto funziona correttamente, il problema è che nello stack non posso definire le dependencies tra i servizi, per cui se parte il servizio ha mentre mysql è ancora in fase di avvio, ha parte senza il recorder in pratica e non ho lo storico.

L'ideale sarebbe che il container ha fallisse lo start fino a quando non riesce a connettersi a mysql, e continuasse a restartarsi nello swarm fino a che finalmente non riesce a connettersi al db, ma non credo sia possibile.

Qualcuno ha affrontato lo stesso problema?

Ciao
Fabio

**Comment by snakuzzo** [comment]
Ciao.
Al volo...mi verrebbe da pensare ad una cosa del genere, non è pulitissima ma se Core viene startato correttamente potrebbe funzionare:

Intercettare l'errore di connessione al DB e forzare il restart di Core utilizzando le [API](https://developers.home-assistant.io/docs/api/rest/)

In sostanza...

Creare un'automazione che abbia:

- come trigger un [event trigger](https://www.home-assistant.io/docs/automation/trigger/#event-trigger) e che faccia scopa con l'errore di connessione al DB

- come action una chiamata alle API di HA per fare il restart. A titolo di esempio ecco una curl:

```bash
curl -s -X POST -H "Authorization: Bearer <token>" -H "Content-Type: application/json" http://localhost:8123/api/services/homeassistant/restart 
```

**Reply by snakuzzo** [reply]
Pensavo che forse così non puoi farlo, perché l'errore è immediato, Core non è ancora startato e quindi mi sa che negli eventi non troverai nulla.
Potresti fare un sensore che faccia una grep sul file di log per vedere se ci sono errori.

Esempio in bash appena provato

```
#!/bin/bash

if grep -q MySQLdb.OperationalError home-assistant.log; then
    echo ERROR
else
    echo OK
fi
```

portarlo su HA con un command line sensor del genere:

```yaml
sensor:

  - platform: command_line
    name: db_status
    command: "if grep -q MySQLdb.OperationalError /config/home-assistant.log; then echo ERROR; else echo OK; fi"
``` 

![image](https://user-images.githubusercontent.com/7205371/209432611-557ec2ab-2e32-42bf-81e2-3882abcdba0d.png)

Puoi crearti quindi uno shell command con il comando per il restart

```yaml
shell_command:

  ha_restart: 'curl -s -X POST -H "Authorization: Bearer <token>" -H "Content-Type: application/json" http://localhost:8123/api/services/homeassistant/restart'
```

e fare quindi un'automazione del genere...

```yaml
automation:

- id: ha_restart_on_db_failure
  alias: HA Restart on error
  trigger:
  - platform: homeassistant
    event: start
  condition:
  - platform: state
    entity_id: sensor.db_status
    state: "ERROR"
  action:
  - service: shell_command.ha_restart
```

valuta ovviamente se aggiungere qualche delay, se necessario
