### DISCUSSION TITLE
Contatore consumi un pò complesso (almeno per me :-)

### DISCUSSION THREAD

**Discussion by rbau68** [indomus/forum#2221] [HUB: Home Assistant]
Ciao, vi chiedo aiuto per create in HA 2 contatori dei consumi elettrici. il primo dovrà conteggaire i consumi dal luned' al sabato (escluse le festività italiane) dalle 07.00 alle 23.00 e l'altro i consumi dal lunedì al sabato dalle 23.00 alle 07.00 più tutta la domenica più tutte le festività italiane
In pratica

Contatore 1: 
- dal lundì al sabato (escluse le feste naszionali) dalle 07 alle 23

Contatore 2: 
- dal lundì al sabato dalle 23 alle 7
- domenica dalle 00 alle 23:59
-  feste nazionali dalle 00 alle 23:59

grazie in anticipo per l'aiuto.

**Comment by KC-inDomus** [comment]
https://indomus.it/progetti/configurare-dei-contabilizzatori-di-consumo-energetico-su-home-assistant-v2/

**Comment by duedipicche** [comment]
Bello il progetto, ma mi chiedevo se si possano inserire anche i giorni festivi.
Io ho fatto così, ma non so se è corretto.
Le aggiunte sono quelle tra gli asterischi nel codice **.........**
La verifica della configurazione è OK e lo stato dell'automazione è on.
Grazie per l'eventuale risposta
```
utility_meter:
  monthly_energy:
    name: Consumi mensili
    source: sensor.energy_energy_today
    cycle: monthly
    tariffs:
      - F1
      - F2
      - F3
      
automation:
  - alias: "Tariffe energetiche"
    id: "tariffe_energetiche"
    initial_state: true
    trigger:
      - platform: time
        id: "7"
        at: '7:00:00'
        variables:
          tariff: "F2"
      - platform: time
        id: "8"
        at: '8:00:00'
        variables:
          tariff: "F1"
      - platform: time
        id: "19"
        at: '19:00:00'
        variables:
          tariff: "F2"
      - platform: time
        id: "23"
        at: '23:00:00'
        variables:
          tariff: "F3"
      
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "7"
            sequence:
              - condition: time
                weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
                - sat
              **- condition: state
                entity_id: binary_sensor.workday
                state: "on"**
              - service: select.select_option
                target:
                  entity_id: select.monthly_energy
                data:
                  option: "{{ tariff }}"
          - conditions:
              - condition: trigger
                id: "8"
            sequence:
              - condition: time
                weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
              **- condition: state
                entity_id: binary_sensor.workday
                state: "on"**
              - service: select.select_option
                target:
                  entity_id: select.monthly_energy
                data:
                  option: "{{ tariff }}"
          - conditions:
              - condition: trigger
                id: "19"
            sequence:
              - condition: time
                weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
              - condition: state
                entity_id: binary_sensor.workday
                state: "on"
              - service: select.select_option
                target:
                  entity_id: select.monthly_energy
                data:
                  option: "{{ tariff }}"
          - conditions:
              - condition: trigger
                id: "23"
            sequence:
              **- condition: state
                entity_id: binary_sensor.workday
                state: "on"**
              - service: select.select_option
                target:
                  entity_id: select.monthly_energy
                data:
                  option: "{{ tariff }}"   
          **- conditions:
              - condition: state
                entity_id: binary_sensor.workday
                state: "off"
            sequence:
              - service: select.select_option
                target:
                  entity_id: select.monthly_energy
                data:
                  option: "F3"**   
```
