### DISCUSSION TITLE
Actionable Notifications su iOS

### DISCUSSION THREAD

**Discussion by Picchios** [indomus/forum#2226] [GENERALE - Discussioni generiche]
Buongiorno,
sto utilizzando da poco le Actionable Notifications di HA.
Per l'automazione che ho creato, la notifica arriva correttamente sui dispositivi (iPhone e Watch), ma non vengono eseguite le azioni scelte.
Preciso che le azioni, eseguite singolarmente, funzionano regolarmente.
Questa l'automazione che genera la notifica con le azioni da intraprendere:

```
alias: Notifica -- Termostato OFF
description: ""
trigger:
  - platform: time
    at:
      - "11:30:00"
condition:
  - condition: state
    entity_id: input_boolean.vacanza
    state: "on"
action:
  - service: notify.entità_mio_iphone
    data:
      message: Termostati spenti. Premere per scegliere.
      data:
        actions:
          - action: ACCENDI_TERMO
            title: Accendili
            destructive: true
          - action: MANTIENI_TERMO_OFF
            title: Mantieni spento
mode: single
```

Queste sono le due azioni:

```
alias: iOS -- Accendi Termo
description: ""
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: ACCENDI_TERMO
condition: []
action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.vacanza
mode: single
```
```
alias: iOS -- Mantieni Termo Off
description: ""
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: MANTIENI_TERMO_OFF
condition: []
action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.vacanza
mode: single
```
iPhone con iOS 16.2, HA Core su container Docker, versione 2022.12.8
Qualche suggerimento?
Grazie
