### DISCUSSION TITLE
Aggiungere costo al consumo a PUN aggiornato

### DISCUSSION THREAD

**Discussion by blakdog1978** [indomus/forum#2232] [HUB: Home Assistant]
Buongiorno,
sto usando multiscrape per creare un sensore con PUN aggiornato per calcolare il meglio possibile quanto mi costa l'energia elettrica,
questo è il sensore che ho creato:
```
multiscrape:    
  - resource: 'https://luce-gas.it/guida/mercato/andamento-prezzo/energia-elettrica'
    scan_interval: 3600
    name: PUN MPG Monthly
    sensor:
      - select: 'table > tfoot > tr:nth-child(2) > td:nth-child(2)'
        name: 'PUN AGGIORNATO'
        unique_id: 'PUN AGGIORNATO'
        icon: 'mdi:currency-eur'
        unit_of_measurement: '€/kWh'
        value_template: '{{ value  | replace (",", ".") | float }}'
```
Ora vorrei aggiungere al modello il costo al consumo che mi applica la mia compagnia cioè di 0,015 € ma non ci sto riuscendo...
Consigli ?

Niente ho trovato... vorrei cancellare ma non so come fare.
