### DISCUSSION TITLE
Spostare file da una cartella di HA su un server esterno

### DISCUSSION THREAD

**Discussion by rciotola** [indomus/forum#224] [HUB: Home Assistant]
Salve 
non so se esiste da home assistant il modo di spostare in automatico dei file jpg
Ho una camera che mi salva delle immagini in formato jpg e vorrei poi spostare in modo automaticvo queste immagini o su di un nas in reter locale o su un servizio tipo dropobox o google drive

**Comment by 50494554524F** [comment]
comando linux mv + integrazione shell_command o command (non mi ricordo) + ovviamente un'automazione da lanciare ogni tot...

**Reply by rciotola** [reply]
c''è qualceh esempio a riguardo ?

**Reply by vebto53** [reply]
Io ho provato con shell_command ma non mi funziona ho fatto milioni di prove, ma nisba
Ho trovato questo addon nel servizio: hassio.addon_stdin e mi funziona. Ho fatto questo script e poi lo metti in una automation

```
alias: cp_file_consumi_scaldabagno_su_nas
sequence:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: mv -f /config/consumo_g_scaldabagno.csv /mnt/NewNAS/HomeAssistant/
mode: single
```
