### DISCUSSION TITLE
Automazione con molteplici condizioni

### DISCUSSION THREAD

**Discussion by array81** [indomus/forum#2242] [HUB: Home Assistant]
Mi trovo a dover creare un'automazione, non è la prima che creo ma con questa sto avendo qualche problema.
Ho 5 sensori binari che per comodità chiamerò S1, S2, S3, S4 e S5 e uno switch che chiamerò SW.
La mia automazione dovrebbe essere qualcosa del genere:

se (S1 = on) e ((S2 = on) o (S3 = on) o (S4 = on)) e (S5 = off) allora SW = on altrimenti SW = off

Qualcuno potrebbe darmi una mano?

**Comment by snakuzzo** [comment]
Tutto quello che hai scritto può finire dentro una `action` con l'utilizzo della `choose`.
Esempio...

```yaml
automation:

- id: prova
  alias: Prova
  trigger:
  # qui ci va il tuo trigger, questo è solo un esempio
  - platform: state
    entity_id: binary_sensor.altro_sensore
    state: 'on'
  # qui non mettiamo alcuna condition, perché la verifica va fatta nella action
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.s1
        state: 'on'
      - condition: state
        entity_id: binary_sensor.s2
        state: 'on'
      - condition: state
        entity_id: binary_sensor.s3
        state: 'on'
      - condition: state
        entity_id: binary_sensor.s4
        state: 'on'
      - condition: state
        entity_id: binary_sensor.s5
        state: 'off'
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.sw
    default:
      - service: switch.turn_off
        target:
          entity_id: switch.sw
```

**Comment by array81** [comment]
Intanto grazie della risposta. Vorrei qualche delucidazione a riguardo perchè non sono sicuro che quanto indicato funzioni nel mio caso.

Il trigger se non sbaglio è l'elemento che scatena l'automazione, nel mio caso l'automazione deve avviarsi quando S1 assume lo stato di ON e fin qui tutto bene (non l'avevo specificato nel mio post). A quel punto devo valutare una doppia condizione ovvero che almeno uno dei sensori S2, S3 e S4 sia in ON ma al tempo stesso che il sensore S5 sia in OFF.
Ultimo punto ma non meno importante e che il controllo delle condizioni deve avvenire non solo quando il sensore S1 diventa ON ma da quel momento fino al suo ritorno ad OFF, voglio dire se S1 va in ON fino al ritorno in OFF vorrei che SW cambi stato a seconda delle condizioni indicate per S2, S3, S4 e S5 per poi tornare ad OFF quando S1 torna a OFF.

Spero di essermi spiegato.

A me pare che il codice di cui sopra (fermo restando il trigger che non avevo specificato fosse S1) cambi lo stato di SW solo se S2=S3=S4=ON e S5=OFF (a me verse che anche solo uno dei S2,S3,S4 sia ON e non necessariamente tutti e 3) e poi non sono sicuro che ci sia un controllo ricorsivo, mi pare di capire che il controllo è fatto solo nel momento in cui la condizione di trigger viene verificata poi non succede più nulla fino a che S1 torna a OFF.

Finora ho fatto solo automazioni semplici quindi potrei anche sbagliare ad aver interpretare il codice.

**Reply by snakuzzo** [reply]
Ah scusa...avevo letto male il tuo primo post sul tipo di condizione. Quindi è da riscrivere...ma...

Ad ogni modo non avevi specificato alcun controllo "ricorsivo"
Inoltre non ho ben capito che cavolo di cambi stato vuoi che avvengano. Nello specifico...

> se S1 va in ON fino al ritorno in OFF vorrei che SW cambi stato a seconda delle condizioni indicate per S2, S3, S4 e S5 per poi tornare ad OFF quando S1 torna a OFF.

che vorrebbe dire ???

Ammettiamo che S1 diventi ON, ogni quanto vuoi che venga fatto un controllo ? Ma poi, scusa...essendo uno switch lui può avere solo due stati ON e OFF. Quali sarebbero gli stati che dovrebbe avere finché S1 non diventa OFF ? Perdonami, ma da come l'hai esposta non si capisce una fava :D

Intanto ti posto l'automazione modificata, in attesa di capire il discorso della "ricorsività"...

```yaml
automation:

- id: prova
  alias: Prova
  trigger:
  - platform: state
    entity_id: binary_sensor.s1
    state: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.s2
          state: 'on'
        - condition: state
          entity_id: binary_sensor.s3
          state: 'on'
        - condition: state
          entity_id: binary_sensor.s4
          state: 'on'
      - condition: state
        entity_id: binary_sensor.s5
        state: 'off'
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.sw
    default:
      - service: switch.turn_off
        target:
          entity_id: switch.sw
```

**Comment by array81** [comment]
Per rendere più comprensiva la cosa la descrivo per filo e per segno, o almeno ci provo.
Ho una stufa che può alimentare 3 piani della casa e un accumulo per l'acqua calda. Ognuno dei 3 piani ha un termostato. Ho creato dei sensori binari che fanno quanto segue:

- S1: mi dice se la stufa è accesa o spenta;
- S2, S3, S4: mi dicono se il singolo termostato di piano è acceso o spento;
- S5: mi dice se l'accumulo richiede o meno acqua calda dalla stufa;

Oltre a ciò ho un relè normalmente aperto SW.
Io ho bisogno che se, mentre la stufa è accesa, l'accumulo NON richieda acqua calda e almeno uno dei termostati è acceso, allora il relè SW si chiuda. In tutti gli altri casi ovvero se la stufa è spenta o se è accesa ma l'accumulo chiede acqua calda (a questo punto indipendentemente dallo stato dei termostati) il relè deve rimanere aperto. Dal momento che la stufa si accende il controllo deve essere costante fino allo spegnimento perché in ogni momento lo stato dei termostati o dell'accumulo potrebbero cambiare.

Così è più chiaro?

Non so se la ricorsività è prevista in HA io infatti ho sempre e solo fatto automazioni che si attivavano con un trigger ma era una cosa per così dire puntuale.

**Reply by snakuzzo** [reply]
la ricorsività è prevista, certo...ma tocca fare un po' di ordine in base alle casistiche che hai riportato

**Reply by snakuzzo** [reply]
L'ho riletta 20 volte ma continuo a non capire come possa funzionare con una singola automazione.
Mi spiego...
Se S1 (stufa che si accende) è il trigger che fa scattare l'automazione, tu dici di...
voler fare quel controllo indipendentemente dallo stato della stufa, ma allo stesso tempo dici che quel controllo va fatto finché la stufa non va in off.
Perdonami...ma mi sembra un controsenso.

**Comment by array81** [comment]
Il controllo va fatto da quando la stufa si accende a quando si spegne (solo a stufa accesa per capirci).
Fermo restando che allo spegnimento il relè debba ritornare nella posizione di riposo (aperto).

**Reply by snakuzzo** [reply]
Così potrebbe andare ?

```yaml
automation:

- id: prova
  alias: Prova
  mode: restart
  trigger:

  # scatta quando si accende la stufa...
  - id: stufa_on
    platform: state
    entity_id: binary_sensor.s1
    from: 'off'
    to: 'on'
  
  # ...e quando c'è bisogno di accumulo 
  - id: accumulo_on
    platform: state
    entity_id: binary_sensor.s5
    from: 'off'
    to: 'on'
  action:
  - choose:

    # Se la stufa si accende
    - conditions:
      - condition: trigger
        id: stufa_on
      # Se almeno uno dei termostati è acceso
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.s2
          state: 'on'
        - condition: statet
          entity_id: binary_sensor.s3
          state: 'on'
        - condition: state
          entity_id: binary_sensor.s4
          state: 'on'
      # e non è richiesto accumulo
      - condition: state
        entity_id: binary_sensor.s5
        state: 'off'
      # il relè si chiude
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.sw

    # Se è richiesto accumulo
    - conditions:
      - condition: trigger
        id: accumulo_on
      sequence:
        # ripeti...
        repeat:
          # finché è richiesto accumulo
          while:
          - condition: state
            entity_id: binary_sensor.s5
            state: "on"
          # il relè si chiude
          sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.sw
```
