### DISCUSSION TITLE
Alexa vede solo alcune eneità

### DISCUSSION THREAD

**Discussion by evirci** [indomus/forum#2277] [HUB: Home Assistant]
Buonasera a tutti,
da poco ho integrato alexa mediante la guida di indomus, ma ho qualche problema di integrazione....
Una lampadina zigbee di osram viene vista correttamente e risulta usabile anche dall'app di alexa, ma non viene vista qualsiasi altra entità presente in HA... ho provato anche a cambiare una presa zigbee in light, ma non viene comunque vista
Allego codice yalm
`alexa:
 smart_home:
    filter:
      include_domains:
        - alarm_control_panel
        - switch
        - light
        - temperature_sensor
        - air_conditioner
        - binary_sensor`
Spero di non aver commesso errori, è il mio primo messaggio nel forum, grazie a tutti

**Comment by snakuzzo** [comment]
1. si scrive `yaml`
2. è formattato male...leggi come si usa il markdown [QUI](https://github.com/indomus/forum/discussions/1311)
3. hai commesso un errore. Non esiste un dominio `temperature_sensor` e nemmeno `air_conditioner`
4. Gli errori dovresti trovarli nei log di core...e sono abbastanza parlanti.

Dovresti scrivere così:

```yaml
alexa:
  smart_home:
    filter:
      include_domains:
        - alarm_control_panel
        - switch
        - light
        - sensor
        - climate
        - binary_sensor
```

**Reply by evirci** [reply]
Grazie mille per la celere risposta e mi scuso per la sintassi del markdown...
Ho corretto come da te indicato, riavviato, ma non noto cambiamenti.
La lampada osram sempre funzionante, cambio di luminosità e on/off ok, ma non riesco a vedere altro...
Posso aver sbagliato qualcosa nella configurazione? Però se la lampada funziona non credo ci possano essere errori, sbaglio?

**Reply by snakuzzo** [reply]
se hai sbagliato qualcosa lo vedi nel log

**Reply by snakuzzo** [reply]
hai riavviato HA dopo aver corretto ?
Se non riavvii non funzionerà mai

**Reply by evirci** [reply]
> hai riavviato HA dopo aver corretto ? Se non riavvii non funzionerà mai
certo

**Reply by evirci** [reply]
> se hai sbagliato qualcosa lo vedi nel log
Il percorso è:
Impostazioni -> Sistema -> Registro
Giusto? quel registro è vuoto, se scarico quelli completi mi avverte che certi componenti, come alexa media non è stato testato da HA

**Reply by snakuzzo** [reply]
`alexa_media_player` è un custom component e non ha nulla a che vedere con l'integrazione di cui stiamo parlando.
I Warning...ne avrai sempre uno per ogni custom component...è normale.

Oltre a questo non so che dirti

**Reply by evirci** [reply]
Quello mi domando è, come fa a vedere correttamente la lampadina zigbee e non altri dispositivi? Ho tenuto il codice più semplice possibile nel configuration.yaml proprio per non avere problemi...

**Comment by evirci** [comment]
```
api:  
  
alexa:
  smart_home:
    filter:
      include_domains:
        - alarm_control_panel
        - switch
        - light
        - sensor
        - climate
        - binary_sensor
```
Questo è esattamente il codice scritto nel file configuration.yaml
