### DISCUSSION TITLE
Home Assistant - recupero stati entità MQTT dopo il riavvio.

### DISCUSSION THREAD

**Discussion by evil-life** [indomus/forum#2287] [HUB: Home Assistant]
buongiorno a tutti. 
Avrei bisogno di una mano con la configurazione MQTT di alcuni switch (Ankuoo REC flashati con firmware HFEasy).
Il mio problema è recuperare lo stato dei dispositivi dopo il reboot di HA e Mosquitto (Mosquitto gira su Home Assistant come componente aggiuntivo).
Potete aiutarmi? Avete idea di cosa devo far pubblicare all'avvio per farmi restituire lo stato?
Ecco un esempio di configurazione:

```
switch:
#GARAGE
  - unique_id: switch.ufficio
    name: "Ufficio"
    state_topic: "stat/Ufficio/POWER"
    command_topic: "cmnd/Ufficio/POWER"
    qos: 2
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
    optimistic: false
```
Grazie a tutti

**Comment by snakuzzo** [comment]
Ho dato un'occhiata al volo alla repo di questo firmware che hai menzionato (che non conoscevo).
La doc è fatta uno schifo, non c'è niente... però da quello che vedo usa la stessa struttura dei topic del firmware Tasmota.

Prova così...

```yaml
automation:

- id: ufficio_get_state
  alias: "Ufficio Get State"
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: "cmnd/Ufficio/POWER"
      payload: ""

**Reply by evil-life** [reply]
grazie per l'input.
Confermo che la documentazione è scarna, prima di chiedere aiuto ho tentato l'impossibile, ma non ne sono venuto fuori.
Ho già provato a pubblicare il messaggio che hai inserito nell'esempio di automazione, cioè il comando POWER con payload vuoto, ma il dispositivo non risponde...
inizio a pensare che manchi proprio l'implementazione all'interno del FW per fare quello che cerco.

**Reply by snakuzzo** [reply]
Secondo me ti conviene aprire una issue e chiedere direttamente a chi ha sviluppato il firmware

**Reply by snakuzzo** [reply]
In teoria, per fare una cosa pulita, dovresti anche verificare se è gestito il LWT

**Reply by evil-life** [reply]
si, lo farò. Ho una 20ina di questi switch e devo risolvere assolutamente.
Grazie per il tuo tempo!

**Reply by evil-life** [reply]
> In teoria, per fare una cosa pulita, dovresti anche verificare se è gestito il LWT

il LWT è gestito, ho trovato i messaggi con MQTT Explorer:

Topic: tele/Ufficio/LWT
payload: Online

**Reply by snakuzzo** [reply]
Ok...Sarebbe cosa buona e giusta se il LWT fosse conigurato con la retain.
Una volta che ti sei assicurato di questo, dovresti cambiare configurazione e farla diventare così...

```yaml
switch:
#GARAGE
  - unique_id: switch.ufficio
    name: "Ufficio"
    state_topic: "stat/Ufficio/POWER"
    command_topic: "cmnd/Ufficio/POWER"
    availability_topic: "tele/Ufficio/LWT"
    qos: 2
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
    optimistic: false
```

in questo modo, nel momento in cui il device per qualche motivo è offline, su HA lo vedresti giustamente indisponibile.
Senza questo invece, lo vedresti erroneamente sempre online, anche quando non è collegato
