### DISCUSSION TITLE
esphome termostato

### DISCUSSION THREAD

**Discussion by gianlucaw** [indomus/forum#2292] [Hardware & Firmware]
ciao, vorrei delle info sulla creazione di un termostato per comandare una pompa di riscaldamento. ho creato un firmware con esphome ed un d1mini provando sia la modalita termostato che il bang-bang. 
vorrei avere la regolazione della temperatura tramite il suo webserver, ma non riesco a creare lo slide. con la tastiera riesco a regolarlo ma tramite mouse o cellulare no. mi occorre di impostare la max temperatura ad 80, ma me la cambia a 30. avete qualche info su come posso procedere?

**Comment by Nik71git** [comment]
posta qui lo yaml (con markdown)

**Comment by gianlucaw** [comment]
esphome:
  name: sonde_riscaldamento
  platform: ESP8266
  board: d1_mini

wifi:
  networks:
  - ssid: ----------------
    password: -----------

  manual_ip:
    static_ip: --------------
    gateway: ---------------
    subnet:

  ap:
    ssid: "Fallback Hotspot-riscaldamento"
    password: "gianluca"

captive_portal:

# Enable logging
logger:

web_server:
  port: 80
  version: 2

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

  # Example configuration entry
dallas:
  - pin:  D4
    update_interval:  5s
# Individual sensors
sensor:
  - platform: dallas
    address: 0x513c4bf64990f028
    name: "temperatura puffer"
    id:  puffer

  - platform: dallas
    address: 0x933c94f649f98b28
    name: "temperatura ritorno"
    id: ritorno

  - platform: wifi_signal
    name: Wi-Fi Signal
    update_interval: 30s

# Example configuration entry
text_sensor:
  - platform: wifi_info
    ip_address:
      name: Indirizzo IP
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Wifi Address
    scan_results:
      name: Latest Scan Results

time:
  - platform: sntp
    id: my_time
    timezone: Europe/Rome
binary_sensor:
  - platform: status
    name: EspHome Node Status

  - platform: gpio
    pin:
      number: D3
      mode:
        input: true
        pullup: true
      inverted: True
    name: "pompa_riscaldamento"
    id: sensore_pompa
    device_class: door
    icon: "mdi:SunThermometer"

  - platform: gpio
    pin:
      number: D5
      mode:
        input: true
        pullup: true
      inverted: True
    name: "Button 1"
    on_press:
      - switch.toggle: relay1

switch:
  - platform: gpio
    name: "1CH"
    pin: D7
    id: relay1

# Example single-point configuration entry (for heating only)
climate:
  - platform: thermostat
    name: "Thermostat Climate Controller"
    sensor: puffer
    min_heating_off_time: 60s
    min_heating_run_time: 60s
    min_idle_time: 60s
    heat_action:
      - switch.turn_off: relay1
    idle_action:
      - switch.turn_on: relay1
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 50 °C


    visual:
      min_temperature: 10
      max_temperature: 80
      temperature_step: 1


Il giorno mer 18 gen 2023 alle ore 21:13 Nik71git ***@***.***>
ha scritto:

**Reply by snakuzzo** [reply]
IL MARKDOWN !!!!
Se non correggi il messaggio verrà cancellato

E devi fare reply sotto l'ultimo messaggio, non creare un nuovo thread come hai fatto ora

**Reply by Nik71git** [reply]
Prova ad implementare il bang bang guardando all'esempio sotto, vedi se ti viene meglio

```
climate:
  - platform: bang_bang
    name: "riscaldamento zona notte"
    sensor: t_notte
    default_target_temperature_low: 20.0 °C
    default_target_temperature_high: 20.2 °C
    visual:
      min_temperature: 19°C
      max_temperature: 21 °C
      temperature_step: 0.1 °C 
    heat_action:
      - switch.turn_on: $relay_R1
    idle_action:
      - switch.turn_off: $relay_R1
    away_config:
      default_target_temperature_low: 19 °C 
      default_target_temperature_high: 19.5 °C 
```
