### DISCUSSION TITLE
Configurazione Telecomando Ikea Styrbar E2002 in Z2M

### DISCUSSION THREAD

**Discussion by Picchios** [indomus/forum#2296] [ZigBee, Z-Wave, Thread, Matter]
Buonasera,
ho preso un pulsante Ikea Styrbar (4 pulsanti - su/giu dx/sx) e ho installato su Home Assistant il blueprint per la gestione del pulsante. Sono riuscito a configurare accensione e spegnimento di una data entità light ed in parte anche aumento e diminuzione luminosità, ma non riesco a gestirla come vorrei; difatti dico "in parte" perché per aumentare la luminosità, tenendo premuto, aumenta di un delta, poi devo lasciare e tenere premuto di nuovo per un altro delta e così via (non è continuativo). Non mi sembra un modo corretto per come l'ho impostato. Volevo poi usare i pulsanti dx/sx per cambiare i colori con un set di predefiniti. Ho trovato delle guide ma sono tutte su ZHA. Io utilizzo HA Core e Z2M 1.29.2. Potreste darmi qualche suggerimento?
Grazie

**Comment by Scialla** [comment]
Ti passo il codice del mio pulsante (stesso modello):
```

input_select:
  colori_striscia:
    name: Colori Striscia
    options:
      - "0,0,0"
      - "255,255,255"
      - "255,0,0"
      - "255,63,0"
      - "255,127,0"
      - "255,191,0"
      - "255,255,0"
      - "191,255,0"
      - "0,255,0"
      - "0,255,127"
      - "0,255,255"
      - "0,191,255"
      - "0,127,255"
      - "127,0,255"
      - "255,0,255"
      - "255,0,191"
      - "255,0,127"
    initial: "0,0,0"

input_text:
  striscia_selected_color:

automation:     

- alias: automazione_ikea_multi_switch #Cappa
  id: automazione_ikea_multi_switch
  initial_state: true
  # Imposto modalità restart perché se arriva un'altra publish dello stesso device...
  # ...devo interrompere quello che sto facendo e rieseguire l'automazione da capo
  mode: restart
  trigger:
  # L'automazione viene triggerata quando viene pubblicato il topic del pulsante IKEA...
  - platform: mqtt
    topic: 'zigbee2mqtt/IkeaMultiLightSwitch/action'
  action:
  # Qui utilizzo la choose per valutare se dimmerare oppure fermarmi...
  - choose:
    ########################
    # BLOCCO PER DIMMERARE #
    ########################
    - conditions:
      - condition: or
        conditions:
        # Se brightness_down...
        - condition: template
          value_template: "{{ trigger.payload == 'brightness_move_down' }}"
        # ...oppure brightness_up
        - condition: template
          value_template: "{{ trigger.payload == 'brightness_move_up' }}"
      sequence:
      - repeat:
          # Finché...
          until:
          - condition: or
            conditions:
            # ...la luce non si spegne...
            - condition: state
              entity_id: light.cappa
              state: 'off'
            # ...oppure la luce non è alla massima luminosità (la luminosità va da 1 a 255)...
            - condition: template
              value_template: "{{ state_attr('light.cappa','brightness') | int == 255 }}"
          # ...ripeto i seguenti passaggi:
          sequence:
          # Chiamo il servizio light.turn_on...
          - service: light.turn_on
            entity_id: light.cappa
            data:
              # ...aumentando o diminuendo la luminosità di 10...
              brightness: >-
                {% if trigger.payload == 'brightness_move_up' %}
                  {{ state_attr('light.cappa','brightness') | int(0) + 10 }}
                {% else %}
                  {{ state_attr('light.cappa','brightness') | int(6) - 10 }}
                {% endif %}
          # ...e aspetto un numero preciso di millisecondi
          # ...per rallentare e rendere più fluido il cambio di luminosità
          - delay:
              milliseconds: 70
    ######################
    # BLOCCO PER FERMARE #
    ######################
    - conditions:
      # Se brightness_stop
      - condition: template
        value_template: "{{ trigger.payload == 'brightness_stop' }}"
      # ...Aspetto 1 millisecondo. In pratica non faccio nulla. 
      # Mi serve solo per interrompere il dimmer
      sequence:
      - delay:
          milliseconds: 1
      # Questo accade perché l'automazione è impostata con mode repeat e quindi quando viene
      # ...nuovamente triggerata, interrompe quello che stava facendo e viene eseguita da capo
    #################
    # BLOCCO ON/OFF #
    #################
    - conditions:
      # Se off spegne
      - condition: template
        value_template: "{{ trigger.payload == 'off' }}"
      sequence:
      - service: light.turn_off
        entity_id: light.cappa
    - conditions:
      # Se on imposta bianco freddo max luminosità
      - condition: template
        value_template: "{{ trigger.payload == 'on' }}"
      sequence:
      - service: light.turn_on
        entity_id: light.cappa
        data:
          brightness: 255
          color_temp: 150
    #################
    # Cambio Colore #
    #################
    - conditions:
      - condition: or
        conditions:
        - condition: template
          value_template: "{{ trigger.payload == 'arrow_left_click' }}"
        - condition: template
          value_template: "{{ trigger.payload == 'arrow_right_click' }}"
      sequence:
      - service: script.turn_on
        data:
          entity_id: >
            {% if trigger.payload == 'arrow_left_click' %}
              script.striscia_colors_down
            {% else %}
              script.striscia_colors_up
            {% endif %}

script:
  striscia_colors_up:
    alias: striscia_colors_up
    sequence:
    # Se la luce è accesa
    - condition: state
      entity_id: light.cappa
      state: 'on'
    # Imposto il prossimo indice dell'array per recuperare il colore RGB
    - service: input_text.set_value
      data:
        entity_id: input_text.striscia_selected_color
        value: >-
          {% if state_attr('input_select.colori_striscia','options')[states('input_text.striscia_selected_color') | int(0) + 1 ] != null -%}
            {{ states('input_text.striscia_selected_color') | int(0) + 1 }}
          {%- else -%}
            0
          {%- endif %}
    # Imposto la terna RGB recuperando l'indice dell'array dall'input_text
    - service: input_select.select_option
      data:
        entity_id: input_select.colori_striscia
        option: >-
          {{ state_attr('input_select.colori_striscia','options')[states('input_text.striscia_selected_color') | int(0)] }}
    - service: light.turn_on
      data:
        entity_id: light.cappa
        rgb_color: "{{ state_attr('input_select.colori_striscia','options')[states('input_text.striscia_selected_color') | int(0)] }}"
  striscia_colors_down:
    alias: striscia_colors_down
    sequence:
    # Se la luce è accesa
    - condition: state
      entity_id: light.cappa
      state: 'on'
    # Imposto il precedente indice dell'array per recuperare il colore RGB
    - service: input_text.set_value
      data:
        entity_id: input_text.striscia_selected_color
        value: >-
          {% if state_attr('input_select.colori_striscia','options')[states('input_text.striscia_selected_color') | int(1) - 1 ] != null -%}
            {{ states('input_text.striscia_selected_color') | int(1) - 1 }}
          {%- else -%}
            0
          {%- endif %}
    # Imposto la terna RGB recuperando l'indice dell'array dall'input_text
    - service: input_select.select_option
      data:
        entity_id: input_select.colori_striscia
        option: >-
          {{ state_attr('input_select.colori_striscia','options')[states('input_text.striscia_selected_color') | int(0)] }}
    - service: light.turn_on
      data:
        entity_id: light.cappa
        rgb_color: "{{ state_attr('input_select.colori_striscia','options')[states('input_text.striscia_selected_color') | int(0)] }}"
```

Ovviamente da adattare alle tue entità e da modificare eventualmente per la velocità di reazione, nonché ai tuoi payload e topic.

Premetto che sto facendo tutto da cellulare e non so se sono riuscito correttamente.

Se tutto è andato, cerca di capire l'automazione e se hai problemi chiedi, appena posso ti risponderò
