### DISCUSSION TITLE
Richiamare servizio tramite template

### DISCUSSION THREAD

**Discussion by matteo-vannucchi** [indomus/forum#2308] [HUB: Home Assistant]
Salve, ho provato a creare la seguente automazione sul mio HA core:

```yaml
alias: AccendiJBL
description: Accende la soundbar JBL mentre NestMini riproduce musica
trigger:
  - platform: device
    type: changed_states
    device_id: 3832ca0f1e5c72e526f20df23248cfd2
    entity_id: media_player.nestmini
    domain: media_player
    for:
      hours: 0
      minutes: 0
      seconds: 5
condition: []
action:
  - service: >-
      media_player.+"{% if is_state('media_player.nestmini','playing') %}
      turn_on {% else %} turn_off {% endif %} "
    data: {}
    target:
      entity_id: media_player.jbl_boost_tv
mode: single
```

Non funziona. HA si riavvia correttamente e non sono riuscito a trovare un'indicazione di un errore. Si tratta di una sintassi lecita? Può funzionare?

Grazie

**Comment by snakuzzo** [comment]
```yaml
automation:

- id: accendi_jbl
  alias: Accendi JBL
  description: Accende la soundbar JBL mentre NestMini riproduce musica
  trigger:
  - platform: state
    entity_id: media_player.nestmini
    for:
      seconds: 5
  action:
    - service: >-
        {% if is_state('media_player.nestmini','playing') %}
          media_player.turn_on
        {% else %}
          media_player.turn_off
        {% endif %}
      data:
        entity_id: media_player.jbl_boost_tv
```
