### DISCUSSION TITLE
Controautomazione

### DISCUSSION THREAD

**Discussion by barbatrukko** [indomus/forum#2315] [HUB: Home Assistant]
Salve, ho creato una automazione che quando accendo la luce del corridoio (vari pulsanti a relè sparsi in casa che convergono in un sonoff mini) dopo 40 secondi la luce si spenga da sola (anche per evitare che venga sempre lasciata accesa dai figli).
Tuttavia alle volte servirebbe che stesse di più accesa (per esempio mentre si fanno lavori, si sistema qualcosa, etc).
Vorrei fare una seconda automazione che in base ad una qualche sequenza specifica (ad esempio accendo e chiudo due volte velocemente o similare) si metta in modalità "acceso fino al prossimo spegnimento manuale"
L'automazione attuale è questa

```
alias: Autospegnimento Corridoio
description: Spegne la luce dopo 60 secondi dall accensione
trigger:
  - platform: state
    entity_id: switch.sonoff_XXXXXXXXXX
    from: "off"
    to: "on"
action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data:
      entity_id: switch.sonoff_XXXXXXXXXX

```

**Comment by snakuzzo** [comment]
Puoi fare una seconda automazione che (ad esempio), in base allo stato di un altro switch, attivi o disattivi la prima automazione

Es.

```yaml
automation:

# PRIMA AUTOMAZIONE

- id: autospegnimento_corridoio
  alias: "Autospegnimento Corridoio"
  description: "Spegne la luce dopo 60 secondi dall accensione"
  trigger:
  - platform: state
    entity_id: switch.sonoff_XXXXXXXXXX
    from: "off"
    to: "on"
  action:
  - delay:
      minutes: 1
  - service: switch.turn_off
    data:
      entity_id: switch.sonoff_XXXXXXXXXX

# SECONDA AUTOMAZIONE

- id: autospegnimento_corridoio_on_off
  alias: "Autospegnimento Corridoio On/Off"
  description: "Abilita/Disabilita lo spegnimento automatico corridoio"
  trigger:
  - platform: state
    entity_id: switch.sonoff_YYYYYYYYYY
    from: "off"
    to: "on"
  - platform: state
    entity_id: switch.sonoff_YYYYYYYYYY
    from: "on"
    to: "off"
  action:
  - service: >
      {% if trigger.to_state.state == 'on' %}
        automation.turn_off
      {% else %}
        automation.turn_on
      {% endif %}
    data:
      entity_id: automation.autospegnimento_corridoio
```
