### DISCUSSION TITLE
MotionEye Telegram notification

### DISCUSSION THREAD

**Discussion by Al3eRtO** [indomus/forum#2322] [GENERALE - Discussioni generiche]
Buongiorno a tutti, 
cerco aiuto per configurare l'invio di foto/video alla rilevazione del movimento sul telegram bot.
Al momento ho settato l'invio delle mail di notifica ma la vorrei sostituire con l'invio al bot
Ho fatto un test con Run A Command su motioneye:
mosquitto_pub -h 192.168..... -u mqtt_user -P .... -t stat/motionEye/motion -m '{"ipcam":"Dietro_on"}'

e un automazione che mi manda una stringa quando si attiva.
Qualcuno ha fatto qualcosa di simile?
Premetto che sono alle prime armi...
grazie

**Comment by snakuzzo** [comment]
Devi fare qualcosa del genere (scritta al volo senza testare...ma la logica è questa)...

```yaml
- id: notifica_me
  alias: "Notifica ME"
  description: "Automazione Notifica ME"
  trigger:
  - platform: mqtt
    topic: "stat/motionEye/motion"
  action:
  - service: notify.telegram_pippo
    data:
      title: Notifica ME
      message: "Rilevato qualcosa da {{ trigger.payload_json.ipcam }}"
```

Il trigger è la pubblicazione del topic
Nella action mandi un messaggio con Telegram recuperando l'ID della camera indicata nel payload JSON della publish MQTT che  ha triggerato l'automazione
