### DISCUSSION TITLE
variabile su rest_command

### DISCUSSION THREAD

**Discussion by kimuss** [indomus/forum#2327] [HUB: Home Assistant]
salve, qualcuno sa se è possibile avere una roba del genere dentro uno yaml:

```
base_url: '192.168.1.1/api/command.php?'   
uuid: xxxx-xxxxxxxx-xxxxxxx-xxx

rest_command:
  studio_on:
    resource: '{{ base_url }}uuid={{ uuid }}_cmd=[{"mod":5,"reg":1,"val":10}]'
```
grazie anticipatamente

ps: ovviamente HA mi da "the configuration is not valid: expected dict  for dictionary value @ data"

**Comment by snakuzzo** [comment]
Non mi pare esista la key `resource`

Dovresti usare `url` e, come indicato dalla [documentazione](https://www.home-assistant.io/integrations/rest_command/#url), è previsto l'uso dei template

**Comment by kimuss** [comment]
si hai ragione die, non so perché ho scritto `resource`, si anche con `url` stesso problema, ho provato con la doc (per quello pensavo che magari le graffe mi aiutavano) ma non riesco a trovare un punto degli esempi dei template che fanno usare le variabili, però chiedevo se magari vi era già capitato e sto sbagliando sintassi.. o vi veniva in mente un altro modo per ottimizzare la riga` url `che nel file la ripeto 20 volte sempre uguale

gazie

**Reply by snakuzzo** [reply]
Puoi utilizzare degli `input_text` e "FORSE" dei secret

es.

```yaml
rest_command:
  studio_on:
    url: "{{ states('input_text.base_url') }}"
```

**Reply by kimuss** [reply]
si così va.. grande 
però me lo prende solo se metto solo template..
es:   `url: "{{ states('input_text.base_url') }}{{ states('input_text.cmd_on') }}"`
posso comporre l'url facendo una parte stato dell'input text e un'altra parte solo testo?

**Reply by snakuzzo** [reply]
certo che puoi

**Reply by kimuss** [reply]
mmm ho provato più strade ma l'unica cosa che non riesco a fargli digerire è `[{"mod":5,"reg":1,"val":10}]`
ho provato sul template di developer tools e lì sembra scriverlo bene, però quando fa il check configuration da sempre errore:
`expected <block end>, but found <'scalar'>`
cercando in giro parlano di problemi di indentazione... ma l'ho controllato mille volte e in teoria non ce ne dovrebbero essere...

**Comment by kimuss** [comment]
scrivo la versione corretta magari può essere utile a qualcuno, anche se era proprio banale :)

```
rest_command:
  studio_on:
    url: >
      {{ states('input_text.base_url')}}_cmd=[{"mod":5,"reg":1,"val":10}]
```
