### DISCUSSION TITLE
Spotcast - liste e canzoni

### DISCUSSION THREAD

**Discussion by ronyn77** [indomus/forum#2332] [HUB: Home Assistant]
Ciao,

sto provando una cosa semplice ma non mi funziona e non riesco a capirne il problema.
Partiamo da questo semplice script : 

```
service: spotcast.start
data:
  random_song: false
  offset: 0
  device_name: Google nest audio
  uri: spotify:track:3BzO3H3k4iU70Cn6YpriYA
```
Dove "3BzO3H3k4iU70Cn6YpriYA" e' l'id della canzone precedentemente trovata da spotify attraverso il browser oppure usando HA dalla finestra degli stati.
Il problema che a prescindere dall'id della canzone o della lista, non mi viene mai riprodotta quella specifica.
Se metto l'id di una lista creata da me, vengono riprodotte altre canzoni che non sono presenti nella lista.
Lo stesso dicasi se e' l'id di un canzone. Me ne riproduce un'altra.
Se spotify e' in esecuzione sul dispositivo google, dal browser se scelgo la canzone, me la riproduce senza problemi. Usando invece l'integrazione da home assistant, non va.

Da cosa può dipendere? Non ho spotify premium.
