### DISCUSSION TITLE
Colore delle Card in base allo stato

### DISCUSSION THREAD

**Discussion by Tempesta72** [indomus/forum#2333] [HUB: Home Assistant]
Buongiorno, per molti sarà una cosa semplice, ma mi stò incartando nel meccanismo che di seguito descrivo.
Semplicemente far cambiare il colore di una card in base allo stato `home`, `not_home` ecc
Ho recuperato in rete un layout già pronto e lo sto modificando in base alle mie esigenze.
La card con `sensor.person` sarebbe questa:
![immagine](https://user-images.githubusercontent.com/120799307/218316657-f700e8be-5d53-48e2-827e-b6b37b6a0762.png)
in lovelace nel file button_card_templates.yaml c'è questo:
```
#######################
### SENSOR TEMPLATE ###
#######################

sensor_card:
  layout: icon_name_state2nd
  show_state: true
  styles:
    card:
      - padding-top: 2%
      - padding-bottom: 2%
    state:
      - font-size: 140%
      - font-weight: bold
      - justify-self: start
      - align-self: center
    name:
      - font-size: 85%
      - justify-self: start
      - color: var(--secondary-text-color)
  tap_action:
    action: none
sensor_card_text:
  show_icon: false
  show_state: true
  styles:
    card:
      - height: 200px
    name:
      - font-size: 80%
      - color: var(--secondary-text-color)
    state:
      - font-size: 20%
      - font-weight: bold
  tap_action:
    action: none
sensor_person:
  label: |
    [[[
      var h = states[variables.battery_entity].state;
      return 'Batteria: '+h+'%';
    ]]]
  layout: vertical
  show_icon: false
  show_entity_picture: true
  show_name: false
  show_state: true
  show_label: true
  styles:
    card:
      - height: 200px
    state:
      - font-size: 150%
    name:
      - font-size: 15px
      - font-weight: 500
      - color: var(--secondary-text-color)
    label:
      - margin-bottom: 8px
      - color: var(--secondary-text-color)
      - font-size: 80%
    entity_picture:
      - border-radius: 50%
      - border: 4px solid
      - width: 100px
      - border-color: rgb(62, 71, 65) 
  state:
    - value: home
      operator: '!='
      styles:
        card: 
          - color: rgb(196, 47, 47)
    - value: not_home
      operator: '!='
      styles:
        card:
          - color: rgb(56, 128, 55)
```
mentre nel layout della pagina c'è questo:

```
type: horizontal-stack
cards:
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        entity: person.matti
        name: Matteo
        template: sensor_person
        variables:
          battery_entity: sensor.battery_level_matteo
      - type: 'custom:button-card'
        entity: person.ale
        name: Alessio
        template: sensor_person
        variables:
          battery_entity: sensor.battery_level_alessio
```

in questo modo cambia il colore solo della scritta "in casa" o "fuoro casa", ma mi piacerebbe invece far cambiare colore a tutta la card
grazie
scusate se ho sbagliato qualche cosa nel post
