### DISCUSSION TITLE
Automazione - accensione luce al passaggio

### DISCUSSION THREAD

**Discussion by Matty1184** [indomus/forum#2356] [HUB: Home Assistant]
CIao a tutti, 
mi sto perdendo a fare una banalissima automazione...
vorrei che alla rilevazione della presenza, se i lux in quell'ambiente sono inferiori a 30, la luce è spenta si accenda per x secondi.
premesso... l'entità light è l'interruttore vero e proprio che corrisponde al pulsante di accensione e spegnimento (bticino smart).
vorrei che la luce si attivasse x secondi dopo la rilevazione in modo tale che se nel frattempo accendo manualmente la luce prevalga la mia azione rispetto all'automazione.
ho usato l'interfaccia grafica ma purtroppo la luce mi si accende per 5 secondi all'ingresso nell'area senza attendere, riporto qui il codice.

```
alias: Accensione Luce Sottoscala da movimento
description: ""
trigger:
  - type: motion
    platform: device
    device_id: 012fd3e8d7d2ae72cd4ed19d731fe406
    entity_id: binary_sensor.rilevamento_sottoscale_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - type: illuminance
    platform: device
    device_id: 012fd3e8d7d2ae72cd4ed19d731fe406
    entity_id: sensor.rilevamento_sottoscale_illuminance_lux
    domain: sensor
    below: 30
condition:
  - condition: device
    type: is_off
    device_id: f072edecd43e6c6319be4ca8db7b9795
    entity_id: light.luce_sottoscala_lightbulb
    domain: light
    for:
      hours: 0
      minutes: 0
      seconds: 5
action:
  - wait_for_trigger: []
    timeout:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
    continue_on_timeout: true
  - if:
      - condition: device
        type: is_off
        device_id: f072edecd43e6c6319be4ca8db7b9795
        entity_id: light.luce_sottoscala_lightbulb
        domain: light
    then:
      - type: turn_on
        device_id: f072edecd43e6c6319be4ca8db7b9795
        entity_id: light.luce_sottoscala_lightbulb
        domain: light
      - wait_for_trigger: []
        timeout:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
        continue_on_timeout: false
      - type: turn_off
        device_id: f072edecd43e6c6319be4ca8db7b9795
        entity_id: light.luce_sottoscala_lightbulb
        domain: light
mode: single
```

**Comment by snakuzzo** [comment]
Il discorso è che se stai usando un pulsante...

1. rilevazione
2. accensione luce
3. nel frattempo ripremi il pulsante la luce si spegne

Stesso dicasi per un interruttore (salvo eventuali impostazioni sul verso dell'interruttore così come puoi fare con Shelly)...

1. rilevazione
2. accensione luce
3. nel frattempo premi l'interruttore la luce si spegne

Come la gestiresti questa cosa ?

**Reply by snakuzzo** [reply]
Mettici poi che la rilevazione potrebbe anche causare dei falsi positivi e far scattare nuovamente l'automazione.
Io la semplificherei facendo solo un `on` e `off` con dei `for` sui trigger...tanto se sei nella stanza, a meno che non sia una stanza così grande, vieni rilevato

**Reply by snakuzzo** [reply]
una roba del genere...

```yaml
alias: Accensione Luce Sottoscala da movimento
description: ""
mode: restart # così viene interrotto quello che sta facendo se scatta altro trigger
trigger:
  - id: outside
    platform: state
    entity_id: binary_sensor.rilevamento_sottoscale_occupancy
    from: "on"
    to: "off"
    for:
      seconds: 120
  - id: inside
    platform: state
    entity_id: binary_sensor.rilevamento_sottoscale_occupancy
    from: "off"
    to: "on"
action:
  - choose:
      # Presenza non più rilevata
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'outside' }}"
        sequence:
          # spegne la luce
          - service: light.turn_off
            target:
              entity_id: light.luce_sottoscala_lightbulb
      # Presenza rilevata
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'inside' }}"
          # Se la luminosità è inferiore a 30
          - condition: numeric_state
            entity_id: sensor.rilevamento_sottoscale_illuminance_lux
            below: 30
        sequence:
          # accende la luce
          - service: light.turn_on
            target:
              entity_id: light.luce_sottoscala_lightbulb
    # per non avere errori quando lo stato passa da/a "unknown/unavailable"
    default:
      - delay:
          seconds: 1
```
