### DISCUSSION TITLE
Rilevamento assorbimento (Watt) MQTT

### DISCUSSION THREAD

**Discussion by drako92** [indomus/forum#2357] [HUB: Home Assistant]
Un saluto a tutti,
vorrei rilevare l'assorbimento generato dal carico (luci in questo caso) collegate a 2 canali di uno shelly 2.5, che attualmente interfaccio ad HA tramite MQTT. Avendo voi già discusso di questo argomento in una guida dedicata presente sul vostro sito, ho provato a seguirla, però lo stato dei sensori "assorbimento" appena creati rimane su "Non disponibile". La cosa che non capisco è che se provo ad ascoltare il topic direttamente da broker, mi restituisce le letture corrette. 

Cosa sto sbagliando?
Grazie per le risposte.

Il codice inserito è il seguente:
(la prima parte definisce la parte di accensione/spegnimento delle luci, mentre la seconda è per l'assorbimento)
```
mqtt:
  light:
    - command_topic: "shellies/shelly25-box/relay/0/command"
      name: "Luce Box Principale"
      state_topic: "shellies/shelly25-box/relay/0"
      qos: 0
      payload_on: "on"
      payload_off: "off"
      retain: false
    - command_topic: "shellies/shelly25-box/relay/1/command"
      name: "Luce Box Secondaria"
      state_topic: "shellies/shelly25-box/relay/1"
      qos: 0
      payload_on: "on"
      payload_off: "off"
      retain: false

  sensor:
  - name: "Assorbimento Luce Box Principale"
    state_topic: "shellies/shelly25-box/relay/0/power"
    availability_topic: "shellies/shelly25-box/online"
    payload_available: "true"
    payload_not_available: "false"
    unit_of_measurement: "Watt"
  - name: "Assorbimento Luce Box Secondaria"
    state_topic: "shellies/shelly25-box/relay/1/power"
    availability_topic: "shellies/shelly25-box/online"
    payload_available: "true"
    payload_not_available: "false"
    unit_of_measurement: "Watt"
```

**Comment by snakuzzo** [comment]
Ricorda che se usi l' `availability_topic` devi fare l'automazione di announce allo start di HA. E se non vuoi restartare HA, devi forzare l'availability topic con una publish mqtt

```yaml
- service: mqtt.publish
  data:
    topic: shellies/command
    payload: "announce"
    retain: false
```
