### DISCUSSION TITLE
testare funzionamento rilevatore movimento

### DISCUSSION THREAD

**Discussion by Sabream** [indomus/forum#2359] [HUB: Home Assistant]
Ciao a tutti,
sto testando qualche automazione con un sensore di movimento (aqara motion sensor) integrato in HA.
Il dispositivo si vede correttamente operativo con batteria al 100% sia su z2mqtt che su homeassistant, ma se provo a creare qualche automazione con trigger rilevamento movimento non succede assolutamente niente.

Nello specifico ho creato:
```
alias: luce notturna cucina
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.0x00158d000836ab58_occupancy
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    from: "off"
condition:
  - condition: time
    after: "23:00:00"
    before: "06:00:00"
action:
  - service: scene.turn_on
    target:
      entity_id: scene.cucina_luce_notturna
    metadata: {}
mode: single
```

ma non si è attivato durante quegli orari nonostante ogni tipo di sollecito fisico e manuale davanti al sensore.
Allora ho provato a creare qualcosa di basilare per testare il funzionamento del sensore:
```
alias: Nuova automazione test
description: ""
trigger:
  - type: motion
    platform: device
    device_id: 938c9d0fefeb8429e3cdb39aacf8cfcb
    entity_id: binary_sensor.0x00158d000836ab58_occupancy
    domain: binary_sensor
condition: []
action:
  - type: turn_on
    device_id: d9934b9aa006e9c90f173e0b4b1a37b4
    entity_id: light.cucina
    domain: light
    brightness_pct: 10
mode: single
```
ma anche qui non succede niente...
Sto sbagliando qualcosa probabilmente, ma secondo voi cosa posso fare per testare ulteriormente il sensore per capire se non è difettoso?

**Comment by snakuzzo** [comment]
Prova con un'automazione semplice.
Imposta un ID e poi da GUI puoi anche fare il trace dell'automazione per debuggarla.
Sotto "Impostazioni > Automazioni e scene" ... in corrispondenza dell'automazione che vuoi testare, click sui tre puntini a destra e seleziona "Tracce"

```yaml
automation:

- id: 
  alias: test
  trigger:
  - platform: state
    entity_id: binary_sensor.0x00158d000836ab58_occupancy
    to: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.cucina
```

Quando sei sicuro che funziona, aggiungi altri vincoli nel trigger e nelle condition
