### DISCUSSION TITLE
Integrare Shelly 2.5 con MQTT per controllare tapparelle - status unavailable

### DISCUSSION THREAD

**Discussion by federoco** [indomus/forum#2361] [HUB: Home Assistant]
Ciao a tutti,
sto seguendo [questa](https://indomus.it/guide/integrare-shelly-2-5-a-home-assistant-via-mqtt/) guida per integrare lo Shelly 2.5 su HA.

Ho incontrato due problemi, che ho risolto.
Segnalo come ho fatto, se può essere utile.

**1) l'entità creata su HA non è modificabile, perche HA segnala che non ha un id unico.**
Per risolvere si deve aggiungere alla fine del codice suggerito nella guida:

```
    unique_id: ID_SHELLY
```

dove ID_SHELLY è una stringa univoca. Io ho messo l'ID del device, consultabile dall'interfaccia web dello shelly.

Ecco il codice che ho usato.

```
mqtt:
  cover:
  - name: "NOME_SHELLY"
    command_topic: "shellies/NOME_SHELLY/roller/0/command"
    position_topic: "shellies/NOME_SHELLY/roller/0/pos"
    state_topic: "shellies/NOME_SHELLY/roller/0"
    set_position_topic: "shellies/NOME_SHELLY/roller/0/command/pos"
    availability_topic: "shellies/NOME_SHELLY/online"
    payload_available: "true"
    payload_not_available: "false"
    retain: false
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
    state_opening: "open"
    state_closing: "close"
    state_stopped: "stop"
    position_open: 100
    position_closed: 0
    optimistic: false
    qos: 1
    unique_id: ID_SHELLY
```

Riavviato HA, lo Shelly è visibile come entità.
E qui c'è il problema n.2

**2) l'entità è sempre in stato "unavailable"**
Per risolvere bisogna aprire l'interfaccia web dello Shelly --> Internet & Security --> Advanced - Developer settings e abilitare il CoIoT. Usare il solito IP del broker già inserito per configurare MQTT ma stavolta usando la porta 5683.
Riavviare lo Shelly e HA.
Adesso l'entità è utilizzabile da HA. 
[QUI](https://imgur.com/a/Hk1m0ph) uno screenshot di esempio, ipotizzando che il broker MQTT risponda all'IP 192.168.1.5:5683

NB: se aprite di nuovo l'interfaccia web dello Shelly nel tab "Advanced - Developer settings" si noterà che le impostazioni CoIoT sono tornate come prima della modifica, cioè al posto dell'IP è tornata la dicitura "mcast".
Non è un problema, non so come mai. Ma il problema non si ripresenta più, neppure dopo un'interruzione di corrente.
