### DISCUSSION TITLE
Configurazione add-on ZigBee2MQTT su Home Assistant Supervised

### DISCUSSION THREAD

**Discussion by PiuCurioso** [indomus/forum#2365] [HUB: Home Assistant]
Buonasera,
vi scrivo per un chiarimento:
sto seguendo questo articolo https://indomus.it/guide/come-installare-e-configurare-zigbee2mqtt-su-home-assistant-hassio/#port
per configurare su HA Supervised l'add-on ZigBee2MQTT. Dopo averlo installato mi sono recato alla sezione “Configurazione“, cliccando poi sui tre puntini in alto a destra, ho selezionato la voce “Modifica in YAML“, l’add-on riporta la seguente configurazione 
`data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial: {}
`
mentre nell'articolo su indomus ci sono piu righe di codice
Vi posso chiedere,gentilmente, come devo procedere a configurare l'add-on? quali sono le righe mancanti da inserire?  I campi da personalizzare di cui si parla nell'articolo: “server“, “user” e “password” e infine “port“. nel mio add-on non compaiono, devo inserire manualmente delle righe, potreste indicarmi quali? tenendo conto che sto utilizzando l'antenna di Giovanni ( Z-Bee Duo con il modulo wifi ) per cui dovrei inserire in configurazione anche il seguente codice  port: tcp://IP_DELLO_ESP-01:23
Grazie mille per il vostro aiuto
Notte

**Comment by snakuzzo** [comment]
Ti basta semplicemente fare come scritto [QUI](https://github.com/indomus/forum/discussions/2363#discussioncomment-5116416)

...che poi in YAML risulterà essere così...

```yaml
logins:
  - username: tuauser
    password: tuapassword
require_certificate: true
certfile: fullchain.pem
keyfile: privkey.pem
customize:
  active: false
  folder: mosquitto

```

**Reply by PiuCurioso** [reply]
Grazie mille Snakuzzo ho letto l'esempio del link che mi hai postato,  la configurazione si riferisce all'add on Mosquitto(Mosquitto,l'ho configurato e funziona) siccome devo configurare l'add on Zigbee2mqtt, volevo capire se l'esempio che mi hai postato va bene anche per configurare l'add-on Zigbee2mqtt! Grazie ancora Ciao

**Reply by snakuzzo** [reply]
Hai ragione...ho fatto confusione.
Allora...

Da GUI risulta così 

![Screenshot_20230227-173830.jpg](https://user-images.githubusercontent.com/7205371/221624621-df04d275-92c3-422a-a8e5-f7df848a0334.jpg)

In YAML...

```yaml
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial:
  port: /dev/ttyACM0
  adapter: ezsp
```
