### DISCUSSION TITLE
condition "sun" ... help ...

### DISCUSSION THREAD

**Discussion by RobyBS** [indomus/forum#2366] [HUB: Home Assistant]
Ciao a tutti ! ... 

ho questa automazione qui sotto , per l'avviso quando si supera il grado di umidità stabilito oltre tot. minuti ... 

vorrei che funzionasse però solo dal mattino alla sera, evitando di ricevere messaggi tramite google hubdurante le ore serali e notturne .. 
ho messo la "condition" ma qualcosa non va , visto che continuo a ricevere messaggi anche di notte , ahimè ... 
altra cosa se possibile , come faccio a dare un nome più friendly al sensore "camera_humidity" ad esempio soltanto "camera" in modo che quando google hub fa il suo annuncio dica " .... camera / cameretta ... etc ... " e non " .. camera_humidity .. "  ...

```
- id: notifica_umidità
  alias: Notifica umidità
  trigger:
  - platform: numeric_state
    entity_id: sensor.camera_humidity
    above: 65
    for:
      minutes: 10
  - platform: numeric_state
    entity_id: sensor.cameretta_humidity
    above: 65
    for:
      minutes: 10
  - platform: numeric_state
    entity_id: sensor.bagno_humidity
    above: 70
    for:
      minutes: 10
  - platform: numeric_state
    entity_id: sensor.corridoio_humidity
    above: 65
    for:
      minutes: 10
  - platform: numeric_state
    entity_id: sensor.ingresso_humidity
    above: 65
    for:
      minutes: 10
  condition:
  - condition: or
    conditions:
    - condition: sun
      after: sunrise
      after_offset: -00:15:00
    - condition: sun
      before: sunset
      before_offset: +01:00:00
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.soggiorno
      language: it
      message: ' Ehi ragazzi! , In {{ trigger.to_state.attributes.friendly_name }}
        c''è troppa umidità. In {{ trigger.to_state.attributes.friendly_name }} c''è
        troppa umidità '
```

Grazie
RobyBS

**Comment by Larry-78** [comment]
Ciao, secondo me l'errore è nella `condition: or` 
invece dovrebbe essere 
`condition: and` 
perché in `or` è come se gli stessi chiedono di farti notificare in entrambi i casi, infatti se scatta di notte risulta valida la prima condizione. Invece se vuoi che scatti in un range temporale dovresti utilizzare `and` così solo quando entrambe le condizioni risultano valide riceverai la notifica. 
Per quanto riguarda il `friendly_name` io invece utilizzo `{{ trigger.to_state.name }}` .
Puoi modificare i nomi in Settings/Device & Services/Entities e cerca i sensori in questione.

**Reply by RobyBS** [reply]
studio meglio la situazione e torno da te per conferma ... 

la stessa "condition" la uso su l'accensione di una lampada esterna da sera a mattina con il "or" e funziona benissimo ...ahimè ...

grazie intanto per avermi risposto ...

**Reply by Larry-78** [reply]
...ma anche in quel caso non dovresti utilizzare `or` ti basterebbe fare in questo modo

```yaml
condition:
  - condition: sun
    after: sunset
    before: sunrise
```
Ad ogni modo ti consiglio di dare un'occhiata [qui](https://www.home-assistant.io/docs/scripts/conditions#sunsetsunrise-condition)
