### DISCUSSION TITLE
Cambio effetto luci con un pulsante

### DISCUSSION THREAD

**Discussion by braudoo** [indomus/forum#2370] [HUB: Home Assistant]
Salve a tutti,
sto cercando di impostare uno switch con un bottone, per poter cambiare gli effetti a rotazione ogni volta che premo.
Sono riuscito ad impostare un template in modo tale che mi cambi le scene, ma solo random.
Questo è il codice:

```
service: light.turn_on
data:
  effect: >-
    {{ (["Cozy", "Wake up", "Bedtime" ,"Warm White" ,"Daylight" ,"Cool white"
    ,"Night light" ,"Focus" ,"Relax"]  | random) }}
  transition: 3
target:
  entity_id: light.luce_tavolo
```

Qualcuno  riuscirebbe ad aiutarmi in modo tale che mi cambi gli effetti a rotazione, poi re-iniziare?

Grazie.

**Comment by snakuzzo** [comment]
Io anni fa ho fatto una cosa simile per switchare in maniera sequenziale dei preset RGB per una striscia LED.
Ho usato come entità "di appoggio" un `input_select` e un `input_text`. Magari si può fare tutto in maniera più elegante e semplice...ma non ci metto mano da quando ho scritto il package.

Potresti usare la stessa logica adattandola a ciò di cui hai bisogno tu...

```yaml
input_select:

  magichome_colors:
    name: Magichome Colors
    options:
      - "0,0,0"
      - "255,255,255"
      - "255,0,0"
      - "255,63,0"
      - "255,127,0"
      - "255,191,0"
      - "255,255,0"
      - "191,255,0"
      - "0,255,0"
      - "0,255,127"
      - "0,255,255"
      - "0,191,255"
      - "0,127,255"
      - "127,0,255"
      - "255,0,255"
      - "255,0,191"
      - "255,0,127"
    initial: "0,0,0"

input_text:

  magichome_selected_color:

script:

  # Cambio colori
  magichome_colors:
    alias: Magichome Switch Colors
    sequence:
    # Se la luce è accesa
    - condition: state
      entity_id: light.led_cameretta
      state: 'on'
    # Imposto il prossimo indice dell'array per recuperare il colore RGB
    - service: input_text.set_value
      data:
        entity_id: input_text.magichome_selected_color
        value: >-
          {% if state_attr('input_select.magichome_colors','options')[states('input_text.magichome_selected_color') | int + 1 ] != null -%}
            {{ states('input_text.magichome_selected_color') | int + 1 }}
          {%- else -%}
            0
          {%- endif %}
    # Imposto la terna RGB recuperando l'indice dell'array dall'input_text
    - service: input_select.select_option
      data:
        entity_id: input_select.magichome_colors
        option: >-
          {{ state_attr('input_select.magichome_colors','options')[states('input_text.magichome_selected_color') | int] }}
    - service: light.turn_on
      data:
        entity_id: light.led_cameretta
        rgb_color: "{{ state_attr('input_select.magichome_colors','options')[states('input_text.magichome_selected_color') | int] }}"
```

Per farla più striminzita e usando solo quel service che hai scritto avresti bisogno di recuperare l'indice dell'array relativo all'effetto attualmente impostato e basarti poi sulla lunghezza dello stesso array per tornare al primo valore una volta raggiunto l'indice massimo.

Vedi se ti basta l'esempio che ho scritto, altrimenti possiamo provare a perderci un po' di tempo per cercare di fare tutto nel template del service.

Un dettaglio da tenere in considerazione...se la luce è spenta, l'attributo relativo all'effetto non è valorizzato

**Reply by Scialla** [reply]
Allora, anche questa è molto simile a quella scritta da Diego, in effetti l'aveva scritta inizialmente lui poi io ho aggiunto qualcosa; io la uso con un pulsante Ikea e cambio gli effetti di una striscia LED con firmware WLED
Questa la `input_select` e gli `script` :

```
input_select:
  effetti_wled:
    name: Effetti Wled
    options:
      - "Android"
      - "Aurora"
      - "Blends"
      - "Blink"
      - "Blink Rainbow"
      - "Bouncing Balls"
      - "Bpm"
      - "Breathe"
      - "Candle"
      - "Candle Multi"
      - "Candy Cane"
      - "Chase"
      - "Chase 2"
      - "Chase 3"
      - "Chase Flash"
      - "Chase Flash Rnd"
      - "Chase Rainbow"
      - "Chase Random"
      - "Chunchun"
      - "Colorful"
      - "Colorloop"
      - "Colortwinkles"
      - "Colorwaves"
      - "Dancing Shadows"
      - "Dissolve"
      - "Dissolve Rnd"
      - "Drip"
      - "Dynamic"
      - "Dynamic Smooth"
      - "Fade"
      - "Fairy"
      - "Fairytwinkle"
      - "Fill Noise"
      - "Fire 2012"
      - "Fire Flicker"
      - "Fireworks"
      - "Fireworks 1D"
      - "Fireworks Starburst"
      - "Flow"
      - "Glitter"
      - "Gradient"
      - "Halloween"
      - "Halloween Eyes"
      - "Heartbeat"
      - "ICU"
      - "Juggle"
      - "Lake"
      - "Lighthouse"
      - "Lightning"
      - "Loading"
      - "Meteor"
      - "Meteor Smooth"
      - "Multi Comet"
      - "Noise 1"
      - "Noise 2"
      - "Noise 3"
      - "Noise 4"
      - "Noise Pal"
      - "Oscillate"
      - "Pacifica"
      - "Palette"
      - "Percent"
      - "Phased"
      - "Phased Noise"
      - "Plasma"
      - "Police"
      - "Popcorn"
      - "Pride 2015"
      - "Railway"
      - "Rain"
      - "Rainbow"
      - "Rainbow Runner"
      - "Random Colors"
      - "Ripple"
      - "Ripple Rainbow"
      - "Running"
      - "Running Dual"
      - "Saw"
      - "Scan"
      - "Scan Dual"
      - "Scanner"
      - "Scanner Dual"
      - "Sine"
      - "Sinelon"
      - "Sinelon Dual"
      - "Sinelon Rainbow"
      - "Solid"
      - "Solid Glitter"
      - "Solid Pattern"
      - "Solid Pattern Tri"
      - "Sparkle"
      - "Sparkle Dark"
      - "Sparkle+"
      - "Spots"
      - "Spots Fade"
      - "Stream"
      - "Stream 2"
      - "Strobe"
      - "Strobe Mega"
      - "Strobe Rainbow"
      - "Sunrise"
      - "Sweep"
      - "Sweep Random"
      - "TV Simulator"
      - "Tetrix"
      - "Theater"
      - "Theater Rainbow"
      - "Traffic Light"
      - "Tri Fade"
      - "Tri Wipe"
      - "Twinkle"
      - "Twinklecat"
      - "Twinklefox"
      - "Twinkleup"
      - "Two Dots"
      - "Washing Machine"
      - "Wipe"
      - "Wipe Random"
    initial: "Android"

script:
  wled_effect_up:
    alias: wled_effect_up
    sequence:
    # Se la luce è accesa
    - condition: state
      entity_id: light.wled
      state: 'on'
    # Imposto il prossimo indice dell'array per recuperare l'effetto
    - service: input_text.set_value
      data:
        entity_id: input_text.wled_selected_effect
        value: >-
          {% if state_attr('input_select.effetti_wled','options')[states('input_text.wled_selected_effect') | int(0) + 1 ] != null -%}
            {{ states('input_text.wled_selected_effect') | int(0) + 1 }}
          {%- else -%}
            0
          {%- endif %}
    # Imposto l'effetto recuperando l'indice dell'array dall'input_text
    - service: input_select.select_option
      data:
        entity_id: input_select.effetti_wled
        option: >-
          {{ state_attr('input_select.effetti_wled','options')[states('input_text.wled_selected_effect') | int(0)] }}
    - service: light.turn_on
      data:
        entity_id: light.wled
        effect: "{{ state_attr('input_select.effetti_wled','options')[states('input_text.wled_selected_effect') | int(0)] }}"
  wled_effect_down:
    alias: wled_effect_down
    sequence:
    # Se la luce è accesa
    - condition: state
      entity_id: light.wled
      state: 'on'
    # Imposto il precedente indice dell'array per recuperare l'effetto
    - service: input_text.set_value
      data:
        entity_id: input_text.wled_selected_effect
        value: >-
          {% if state_attr('input_select.effetti_wled','options')[states('input_text.wled_selected_effect') | int(1) - 1 ] != null -%}
            {{ states('input_text.wled_selected_effect') | int(1) - 1 }}
          {%- else -%}
            0
          {%- endif %}
    # Imposto l'effetto recuperando l'indice dell'array dall'input_text
    - service: input_select.select_option
      data:
        entity_id: input_select.effetti_wled
        option: >-
          {{ state_attr('input_select.effetti_wled','options')[states('input_text.wled_selected_effect') | int(0)] }}
    - service: light.turn_on
      data:
        entity_id: light.wled
        effect: "{{ state_attr('input_select.effetti_wled','options')[states('input_text.wled_selected_effect') | int(0)] }}"
```

Poi l'automazione che a me gestisce l'uso di un pulsante ikea multiswitch zigbee, ma l'ultimo blocco usa il cambio di effetto con i due pulsanti a destra e a sinistra:

```
- alias: ikea_multi_switch_2 #Libreria
  id: ikea_multi_switch_2
  initial_state: true
  # Imposto modalità restart perché se arriva un'altra publish dello stesso device...
  # ...devo interrompere quello che sto facendo e rieseguire l'automazione da capo
  mode: restart
  trigger:
  # L'automazione viene triggerata quando viene pubblicato il topic del pulsante IKEA...
  - platform: mqtt
    topic: 'zigbee2mqtt/IkeaMultiLightSwitch2/action'
  action:
  # Qui utilizzo la choose per valutare se dimmerare oppure fermarmi...
  - choose:
    ########################
    # BLOCCO PER DIMMERARE #
    ########################
    - conditions:
      - condition: or
        conditions:
        # Se brightness_down...
        - condition: template
          value_template: "{{ trigger.payload == 'brightness_move_down' }}"
        # ...oppure brightness_up
        - condition: template
          value_template: "{{ trigger.payload == 'brightness_move_up' }}"
      sequence:
      - repeat:
          # Finché...
          until:
          - condition: or
            conditions:
            # ...la luce non si spegne...
            - condition: state
              entity_id: light.wled
              state: 'off'
            # ...oppure la luce non è alla massima luminosità (la luminosità va da 1 a 255)...
            - condition: template
              value_template: "{{ state_attr('light.wled','brightness') | int == 255 }}"
          # ...ripeto i seguenti passaggi:
          sequence:
          # Chiamo il servizio light.turn_on...
          - service: light.turn_on
            entity_id: light.wled
            data:
              # ...aumentando o diminuendo la luminosità di 10...
              brightness: >-
                {% if trigger.payload == 'brightness_move_up' %}
                  {{ state_attr('light.wled','brightness') | int(0) + 10 }}
                {% else %}
                  {{ state_attr('light.wled','brightness') | int(6) - 10 }}
                {% endif %}
          # ...e aspetto un numero preciso di millisecondi
          # ...per rallentare e rendere più fluido il cambio di luminosità
          - delay:
              milliseconds: 70
    ######################
    # BLOCCO PER FERMARE #
    ######################
    - conditions:
      # Se brightness_stop
      - condition: template
        value_template: "{{ trigger.payload == 'brightness_stop' }}"
      # ...Aspetto 1 millisecondo. In pratica non faccio nulla. 
      # Mi serve solo per interrompere il dimmer
      sequence:
      - delay:
          milliseconds: 1
      # Questo accade perché l'automazione è impostata con mode repeat e quindi quando viene
      # ...nuovamente triggerata, interrompe quello che stava facendo e viene eseguita da capo
    #################
    # BLOCCO ON/OFF #
    #################
    - conditions:
      # Se off spegne
      - condition: template
        value_template: "{{ trigger.payload == 'off' }}"
      sequence:
      - service: light.turn_off
        entity_id: light.wled
    - conditions:
      # Se on imposta bianco freddo max luminosità
      - condition: template
        value_template: "{{ trigger.payload == 'on' }}"
      sequence:
      - service: light.turn_on
        entity_id: light.wled
        data:
          brightness: 255
          color_temp: 150
          effect: "Solid"
    ##################
    # Cambio Effetto #
    ##################
    - conditions:
      - condition: or
        conditions:
        - condition: template
          value_template: "{{ trigger.payload == 'arrow_left_click' }}"
        - condition: template
          value_template: "{{ trigger.payload == 'arrow_right_click' }}"
      sequence:
      - service: script.turn_on
        data:
          entity_id: >
            {% if trigger.payload == 'arrow_left_click' %}
              script.wled_effect_down
            {% else %}
              script.wled_effect_up
            {% endif %}
```
