### DISCUSSION TITLE
Zigbee2mqtt - configurazione mqtt devices

### DISCUSSION THREAD

**Discussion by reiner348** [indomus/forum#2376] [GENERALE - Discussioni generiche]
Ciao a tutti!
Ho appena installato un'antenna zigbee e configurato zigbee2mqtt, con "false sull'autodiscovery di home assistant. Fin qui tutto bene!
Ho aggiunto un sensore di apertura della finestra su zigbee2mqtt. Fin qui tutto bene!
Dal log vedo che il payload è 
```
MQTT publish: topic 'zigbee2mqtt/sala-finestra', payload '{"battery":100,"contact":true,"device":{"applicationVersion":3,"friendlyName":"sala-finestra","ieeeAddr":"0x00158d0008c984a2","manufacturerID":4151,"manufacturerName":"LUMI","model":"MCCGQ11LM","networkAddress":35744,"powerSource":"Battery","type":"EndDevice"},"device_temperature":23,"linkquality":255,"power_outage_count":11,"voltage":3155}'
```
E fin qui tutto bene!
Su home assistant mi serve vedere solo contact e battery, quindi ho creato due sensori mqtt così configurati:
```
sensor:
  - unique_id: 'sala_finestra_battery'
    name: 'sala_finestra_battery'
    state_topic: 'zigbee2mqtt/sala-finestra'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'
    icon: mdi:battery
  - unique_id: 'sala_finestra_status'
    name: 'sala_finestra_status'
    state_topic: 'zigbee2mqtt/sala-finestra'
    value_template: '{{ value_json.contact }}'
    icon: mdi:window-closed-variant
```
Fin qui mi andrebbe anche bene, quello della batteria è perfetto! Il problema è che non mi piace quello del contatto, mi restituisce un sensor che è 'true' o 'false' a seconda se il contatto è chiuso o aperto. Vorrei avere qualcosa che posso usare come trigger nelle automazioni, così com'è non ci riesco...
Probabilmente si può configurare diversamente la lettura del payload su mqtt su home assistant, però non so come... Suggerimenti?
Grazie a tutti!

**Comment by snakuzzo** [comment]
Innanzi tutto, a prescindere dal fatto che sia `true`, `false` o altro, puoi sempre usare lo stato di un'entità come trigger.

Detto ciò...

1. Quel tipo di sensore andrebbe configurato come `binary_sensor`. Ed in base allo stato ti restituirà `'on'` oppure `'off'`. Hai poi sempre a disposizione le [device class](https://www.home-assistant.io/integrations/binary_sensor/#device-class) per visualizzare quello che più ti aggrada, ma sotto il binary avrà sempre stato `'on'` oppure `'off'.

2. Quel tipo di sensore andrebbe configurato lato zigbee2mqtt con la retain abilitata. Questo perché, se riavvii HA, essendo un sensore che vai in Deep sleep, ti troveresti con il sensore in stato `unknown` fino al prossimo cambio stato

3. Dovresti usare anche l' `availability_topic` (leggasi anche LWT) per capire se il device e/o  zigbee2mqtt è offline per qualche motivo. Senza questo non vedresti correttamente in `unavailable` l'entità, ma la vedresti fissa con l'ultimo stato...e così rimarrà anche aprendo e chiudendo la finestra o comunque fino al ritorno online di zigbee2mqtt

**Reply by snakuzzo** [reply]
Esempio di un mio `binary_sensor`

```yaml
mqtt:

  binary_sensor:

  - name: "finestra_bagno"
    state_topic: "zigbee2mqtt/finestra_bagno"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ 'true' if value_json.contact == true else 'false' }}"
    payload_on: "false"
    payload_off: "true"
    device_class: "window"
```

**Reply by snakuzzo** [reply]
Esempio automazione con il `binary_sensor` sopra indicato come trigger:

```yaml
automation:

- id: allarme_finestra_bagno
  alias: Allarme finestra bagno
  trigger:
  - platform: state
    entity_id: binary_sensor.finestra_bagno
    from: 'off'
    to: 'on'
  action:
  - service: notify.telegram_diego
    data:
      message: Cambio stato sensore finestra bagno
      title: Home Assistant

```
