### DISCUSSION TITLE
Parere su automazione VMC

### DISCUSSION THREAD

**Discussion by Ices-Eyes** [indomus/forum#2382] [HUB: Home Assistant]
Ciao a tutti. Siccome maxcanna è cattivo e mi caccia sempre sul forum dove non mi risponde nessuno 😂 io ci provo lo stesso...
Secondo voi c'è u modo migliore per fare quello che fa questa automazione?

```
switch:
  - platform: template
    switches:
      vmc_manual_action:
        unique_id: 'vmc_manual_action'
        friendly_name: "Attivazione manuale VMC"
        icon_template: mdi:air-filter
        #value_template: "{{ is_state('switch.vmc', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.vmc
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.vmc
            
automation:
  alias: Gestione VMC
  mode: single
  trigger:
  - platform: numeric_state
    id: turn_on_vmc
    entity_id: sensor.consumo_power
    for:
      hours: 0
      minutes: 10
      seconds: 0
    below: -50
  - platform: numeric_state
    id: turn_off_vmc
    entity_id: sensor.consumo_power
    for:
      hours: 0
      minutes: 15
      seconds: 0
    above: -50
  condition:
  - condition: state
    entity_id: switch.vmc_manual_action
    state: "off"
  action:
  - choose:
      - conditions:
          - condition: trigger
            id: turn_on_vmc
        sequence:
          - service: switch.turn_on
            entity_id: switch.vmc
      - conditions:
          - condition: trigger
            id: turn_off_vmc
        sequence:
          - service: switch.turn_off
            entity_id: switch.vmc
```

E inoltre, per far si che lo switch abbia un interruttore per accendere/spegnere, e non due fulmini, non ho trovato cosa dovrei cambiare... Penso sia qualcosa su value_template, ma non ho trovato come impostarlo!
Grazie!
