### DISCUSSION TITLE
Assegnare nomi persistenti alle porte USB in Docker

### DISCUSSION THREAD

**Discussion by AlainGH** [indomus/forum#2384] [HUB: Home Assistant]
Salve,
prima di migrare HA Core su Docker, usavo alcuni symlink salvati in un file dentro la cartella `etc/udev/rules.d` per evitare che alcuni dispositivi collegati alle porte USB del raspberry non venissero trovati al riavvio poichè talvolta variavano la loro numerazione ttyUSB.
Purtroppo ora (in Docker) questo trucchetto non funziona più e mi piacerebbe sapere se qualcuno i voi conosce un modo semplice per aggirare il problema.

**Comment by snakuzzo** [comment]
Se le definisci con `udev` sull'host, dopo scegli tu come mapparle sotto `devices:`

**Comment by AlainGH** [comment]
Questo lo faccio editando il file di configurazione di compose, giusto?

**Reply by snakuzzo** [reply]
sì

**Comment by AlainGH** [comment]
Sembrava una cosa semplice... ma non ci sono ancora riuscito :-((
Il mio compose.yaml è il seguente
```
services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
    - /home/homeassistant/.homeassistant:/config
    - /run/dbus:/run/dbus:ro
#    - /dev/serial/by-id/:/dev/serial/by-id 
#    - /etc/udev/rules.d
    devices:
#      - /dev/ttyUSB-jkbms:/dev/ttyUSB-jkbms
      - /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0:/dev/USB_jkbms
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_220ffa06b2c9eb11a5898d4f1d69213e-if00-port0:/dev/USB_zigbee
#      - /dev/ttyUSB-zigbee:/dev/ttyUSB-zigbee
    environment:
    - TZ=Europe/Rome
    network_mode: host
    restart: always
    privileged: true 
```
Naturalmente questa non è che l'ennesima variante, ma ne ho testato innumerevoli altre, anche inserendo ulteriori path nella sezione `volumes:` (le righe commentate ne sono la prova).
Alla fine il risultato non cambia: non riesco a creare dei percorsi per le porte usb con nomi persistenti che siano accessibili dal container
