### DISCUSSION TITLE
lettura livello batterie sensori sparsi

### DISCUSSION THREAD

**Discussion by elcino75** [indomus/forum#2394] [GENERALE - Discussioni generiche]
Buongiorno a tutti,
mi sono avvicinato da poco nel mondo della domotica con esphome e ho trovato in "indomus" una vera guida fatta veramente bene da professionisti del settore!
Volevo chiedere al forum se qualcuno ha mai implementato questa funzione, in quanto ho provato a cercare ma trovo poche informazioni che non fanno al caso mio...
Ho due semplicissimi sensori DHT22 dentro e fuori casa, pilotati da un esp01 e alimentati da una 18650. Lo yaml è veramente semplice:

```
esphome:
  name: temp-esterna
  friendly_name: temp-esterna

esp8266:
  board: esp01_1m
......
deep_sleep:
  run_duration: 5min
  sleep_duration: 30min

sensor:
  - platform: adc
    id: vcc_esp
    pin: VCC
    id: temp_esterna_vcc_voltage
    name: "Volt VCC"
    
  - platform: dht
    pin: GPIO02
    temperature:
      name: "Temperatura Esterna"
    humidity:
      name: "Umidita Esterna"
    update_interval: 60s
```

Ora, il mio problema è vedere su un tft pilotato da un ESP32 ed esphome, il valore delle 2 batterie dei due sensori esterni.
Li vedo già in HomeAssistant e prendendo il nome del sensore e, stampandolo sul tft, appare sempre "nan". 
Non capisco come vedere queste due entità da un display tft a sua volta configurato in HA correttamente tramite Esphome...
Qui sotto ci sono le due righe che dovrebbero stamparmi a video le informazioni sulla batteria...

```
sensor:
- platform: homeassistant
    id: vcc_esp
    name: "Vcc_esp"
    entity_id: sensor.temp_esterna_vcc_voltage


it.printf(5, 60, id(roboto20), "Volt ESP esterno: %.2f%  V", id(vcc_esp).state); 

```

Ringrazio anticipatamente 
Cristian
