### DISCUSSION TITLE
Variabile non globale resistente al delay su firmware esphome

### DISCUSSION THREAD

**Discussion by pillolola** [indomus/forum#2395] [Hardware & Firmware]
Ciao a tutti, un aiuto:
ho scritto un firmware per shelly1 in esphome che comanda una lampada e prende in input-switch un fine corsa posto sul carrello della serratura. 
Il comportamento desiderato ( che ho raggiunto) è quello che in condizioni normali, all'apertura del cancello 1 impulso del finecorsa accenda la luce per 60 secondi; ora siccome alla chiusura del cancello il finecorsa si riattiva un altra volta, vorrei utilizzare questo secondo impulso per incrementare il delay e far partire i 60 secondi dalla chiusura del cancello; per ottenere questo, ho pensato di creare una sorta di variabile che sia interna alla sola istanza delay: cioè la prima volta che attivo il finecorsa è un istanza, la seconda volta è un altra istanza; se io memorizzo il valore di una viariabile globale count che incremento ad ogni istanza, basta che io controlli che una varibile interna all'istanza (che andrò a memorizzare all'accensione della luce con il valore attuale della global precedentemente definita) sia uguale alla variabile globale count e solo in questo caso spegnere la luce.
Cosa posso usare per memorizzare una variabile internamente all'istanza (dove per istanza intendo l'intero ciclo click dello switch)?
allego comunque porzione del codice dell'attuale firmware.
``` 
switch:
  - platform: gpio
    name: Luce Vialetto Pedonale
    pin: GPIO4
    id: shelly_relay
    restore_mode: restore_default_off
    on_turn_off:
      if:
        condition:
          - lambda: return  (id(AccensioneFissa) == true);
        then:
          - globals.set:
              id: AccensioneFissa
              value: 'false'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: Vialetto Ingresso Switch
    # config for multi click actions
    on_multi_click:
      # click-click_lungo-click     accendo o spengo permanentemente la luce
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at least 1.5s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - if:
              condition:
                - lambda: return  (id(AccensioneFissa) == false);
              then:
                - lambda: ESP_LOGD("info", "variabile è false"); // visualizzo un log di debug
                - globals.set:
                    id: AccensioneFissa
                    value: 'true'
                - switch.turn_off: shelly_relay
                - delay: 0.5s    
                - switch.turn_on: shelly_relay
                - delay: 1s
                - switch.turn_off: shelly_relay
                - delay: 1s
                - switch.turn_on: shelly_relay
                - lambda: ESP_LOGD("info", "impostata variabile a true"); // visualizzo un log di debug
              else:
                - lambda: ESP_LOGD("info", "variabile è true"); // visualizzo un log di debug
                - globals.set:
                    id: AccensioneFissa
                    value: 'false'
                - switch.turn_off: shelly_relay
                - delay: 0.5s    
                - switch.turn_on: shelly_relay
                - delay: 1s
                - switch.turn_off: shelly_relay   
                - lambda: ESP_LOGD("info", "impostata variabile a false"); // visualizzo un log di debug       
      # double click
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:

      # long click
      - timing:
          - ON for at least 1.5s
          #- OFF for at least 0.5s
        then:
          - if:
              condition:
                - lambda: return  id(AccensioneFissa) == false;
              then:
                - lambda: ESP_LOGD("info", "variabile è false"); // visualizzo un log di debug
                - switch.turn_on: shelly_relay
                - delay: 60s
                - if: # controllo se nel frattempo ho attivato manualmente la luce
                    condition:
                      - lambda: return  id(AccensioneFissa) == false;
                    then:
                      - switch.turn_off: shelly_relay
          
      # single click                accendo la luce temporizzata per 60 secondi
      - timing:
          - ON for at most 1s # on per massimo x secondi
          #- OFF for at least 0.2s #off per almeno x secondi
        then:
          - if:
              condition:
                - lambda: return  id(AccensioneFissa) == false;
              then:
                - lambda: ESP_LOGD("info", "variabile è false"); // visualizzo un log di debug
                - switch.turn_on: shelly_relay
                - delay: 60s
                - if: # controllo se nel frattempo ho attivato manualmente la luce
                    condition:
                      - lambda: return  id(AccensioneFissa) == false;
                    then:
                      - switch.turn_off: shelly_relay
              else:
                #- lambda: ESP_LOGD("info", "variabile è true"); // visualizzo un log di debug
                #- switch.turn_off: shelly_relay
                #- globals.set:
                #    id: AccensioneFissa
                #    value: 'false'
                #- lambda: ESP_LOGD("info", "impostata variabile a false"); // visualizzo un log di debug 
    internal: False
    id: button


globals:
  - id: AccensioneFissa
    type: bool
    restore_value: no  
    initial_value: 'false'

```

Nella speranza di essere stato chiaro, ringrazio anticipatamente chi riuscirà a darmi qualche dritta.
