### DISCUSSION TITLE
Dubbi sulla configurazione recorder

### DISCUSSION THREAD

**Discussion by Matty1184** [indomus/forum#2401] [HUB: Home Assistant]
Ciao a tutti,
volevo limitare il salvataggio dei dati su ha ma temo di aver interpretato male la funzione.
vorrei salvare i record perenni di tutte le entità di quelli idicati nella sezione include, mentre gli altri solo 15gg poi eliminati.
è corretta?
lo chiedo in quanto ho dimenticato di inserire nella lista include un entità temperatura e interrongando questa praticamente non ho storico, quando in teoria dovevo avere almeno 15gg.

```
recorder:
  purge_keep_days: 15
  auto_repack: true
  exclude:
    domains:
      - automation
      - binary_sensor
      - button
      - calendar
      - cover
      - device_tracker
      - group
      - input_boolean
      - input_datetime
      - input_number
      - input_select
      - light
      - media_player
      - persistent_notification
      - person
      - scene
      - script
      - sensor
      - sun
      - switch
      - update
      - zone
  include:
    entities:
      - sensor.energia_anno_server
      - sensor.energia_ieri_server
      - sensor.energia_mese_server
      - sensor.energia_oggi_server
      - sensor.l1_current
      - sensor.l1_energy
      - sensor.l1_energy_returned
      - sensor.l1_power
      - sensor.l1_power_factor
      - sensor.l1_voltage
      - sensor.l2_current
      - sensor.l2_energy
      - sensor.l2_energy_returned
      - sensor.l2_power
      - sensor.l2_power_factor
      - sensor.l2_voltage
      - sensor.l3_current
      - sensor.l3_energy
      - sensor.l3_energy_returned
      - sensor.l3_power
      - sensor.l3_power_factor
      - sensor.l3_voltage
      - sensor.energia_anno_server
      - sensor.energia_ieri_server
      - sensor.energia_mese_server
      - sensor.energia_oggi_server
      - sensor.consumo_totale
      - sensor.allagamento_tecnico_battery
      - sensor.allagamento_tecnico_device_temperature
      - sensor.allagamento_tecnico_power_outage_count
```

**Comment by reiner348** [comment]
Scritto così, tu hai escluso tutte le entità nei domain elencati, poi gli hai detto di includere soltanto le entità listate; quindi nel database ti troverai il record di tutte e solo le entità listate. Se ne hai dimenticata una, quella non ha storico esattamente come tutte le altre non listate.
Per quanto riguarda il purge, cancella tutti i dati più vecchi di 15 giorni, di tutte le entità di cui li sta salvando (cioè soltanto quelle sotto include). Non credo sia possibile differenziare il purge a seconda delle entità...

**Reply by Matty1184** [reply]
ok, in parte era corretta come l'avevo pensata...
io l'avevo interpretata che includesse nello storico solo le entità incluse listate e non venissero mai cancellate, le altre non listate invece rimassero solo per 15 gg come indicato.
quindi nel mio caso l'entità inclusa "sensor.l1_energy" storicizza solo 15gg giusto? se fosse cosi nel mio caso non storicizza nulla!
se volessi storicizzare alcuni 15gg altri a vita non è quindi possibile?

**Reply by Moxser** [reply]
Poacerebbe anche a me capire meglio come gestire il recorder. 
Ci sarebbe qualcuno che può condividere una buona configurazione da prendere come spunto?

**Comment by 50494554524F** [comment]
vi metto questo script, deve essere sistemato e ripulito, non mi chiedete come sistemarlo che ho ancora un sacco di cose da sistemare :D, prendete spunto... cmq il purge è lento, con il controllo sullo stato di avanzamento rallenta ancora, bisognerebbe intervenire direttamente usando comandi sql, ma non sapendo cosa cancellare nel db possiamo fare solo così... questo con sqllite su raspberry, con altri db o sui pc probabilmente andrà meglio




```
#
#     script:
#
#       name: system-database-purge-entities.yaml
#
#       description: delete entities data
#
#       dependencies:
#
#         entities:
#
#           - sensor.system_database_size
#
#         components:
#
#           - variable
#
#       usage:
#
#         action: call-service
#
#         service: script.system_database_purge_entities
#
#         data:
#
#           exclude:                    #  list of entities to exclude from the purge [ optional ]
#
#             - entity_id               #  entity_id of an entity
#
#           repack: boolean             #  true to save disk space rewriting the system database, false otherwise [ optional ]
#



#  System - Database - Purge Entities

system_database_purge_entities:



  alias: 'System - Database - Purge Entities'
  
  description: 'Delete entities data'

  mode: restart


  
  fields:



    exclude:
    
      name: 'Exclude'
      
      description: 'List of entities to exclude from the purge'
      
      required: false
      
      selector:
      
        entity:
        
          multiple: true



    keep_days:
    
      name: 'Days to keep'
      
      description: 'Number of history days to keep in database after purge'
      
      required: false
      
      selector:
      
        number:
        
          min: 0
          
          mode: box
          
          unit_of_measurement: 'giorni'



    repack:
    
      name: 'Repack'
      
      description: 'Save disk space rewriting the system database'
      
      required: false
      
      selector:
      
        boolean:



  sequence:



    - service: recorder.disable






    - service: persistent_notification.create

      data:
              
        #TODO
        title: 'Pulizia Database'

        message: |-
        
          La pulizia del database è iniziata

          {{  states( 'sensor.system_time' )  }} &nbsp; &nbsp; {{  states( 'sensor.system_date' )  }}



    #  Entities to purge
    
    - variables:
    
        database_entities: >-

          {{

              states

                  | rejectattr( 'entity_id', 'in', exclude if exclude is defined else [] )

                  | map( attribute = 'entity_id' )

                  | list

          }}



    #  Purge
    
    - repeat:

        for_each: >-

          {{

              database_entities

          }}
          
        sequence:



          - service: persistent_notification.create

            data:
              
              #TODO
              title: 'Pulizia Database'

              message: >-
              
                {{  repeat.index  }} / {{  database_entities | count  }}
                

                {{  repeat.item  }}
              
              notification_id: 'system_cleaning'
    


          - variables:
          
              item: "{{  repeat.item  }}"



          #  Start purging entity
          
          - service: recorder.purge_entities
          
            data:
            
              entity_globs: "{{  repeat.item  }}"



          #  Set query to check purging progession
          
          - service: var.set
          
            target:
          
              entity_id: var.sql
              
            data:
            
              query: "{{  'SELECT COUNT( * ) AS value FROM states WHERE entity_id = \"{entity_id}\"'.format( entity_id = repeat.item )  }}"
              
              column: 'value'



          #  Wait the purge to complete
          
          - service: var.update
          
            target:
          
              entity_id: var.sql

          - repeat:
                    
              while: "{{  states( 'var.sql' ) | int > 0  }}"
          
              sequence:

                - service: persistent_notification.create

                  data:
                    
                    #TODO
                    title: 'Pulizia Database'

                    message: >-
                    
                      {{  repeat.index  }} / {{  database_entities | count  }} --- {{  states( 'var.sql' )  }}
                      

                      {{  item  }}
                    
                    notification_id: 'system_cleaning2'
              
                - delay:
                
                #TODO
                    #seconds: "{{  1 if states( 'var.sql' ) | int >= 100 else 0  }}"
                    #milliseconds: "{{  1000 if states( 'var.sql' ) | int >= 100 else 200  }}"
                    milliseconds: 250
          
                - service: var.update
                
                  target:
                
                    entity_id: var.sql





    - service: persistent_notification.dismiss

      data:
              
        notification_id: 'system_cleaning'



    - service: persistent_notification.create

      data:
              
        #TODO
        title: 'Pulizia Database'

        message: |-
        
          La pulizia del database è terminata

          {{  states( 'sensor.system_time' )  }} &nbsp; &nbsp; {{  states( 'sensor.system_date' )  }}






    - if:
    
        - or:
    
            - condition: template
            
              value_template: "{{  keep_days | int( default = 0 ) >= 0 if keep_days is defined else false  }}"
    
            - condition: template
            
              value_template: "{{  repack | default( false ) | lower == 'true' if repack is defined else false  }}"
          
      then:



        - service: persistent_notification.create

          data:
                  
            #TODO
            title: 'Compattazione Database'

            message: |-
            
              La compattazione del database è iniziata

              {{  states( 'sensor.system_time' )  }} &nbsp; &nbsp; {{  states( 'sensor.system_date' )  }}



        #  Get datatbase size
        
        - variables:

            database_size: "{{  states( 'sensor.system_database_size' )  }}"  


        
        #  Compact the databse
        
        - service: recorder.purge

          data:

            keep_days: "{{  keep_days | int( default = 3650 ) if keep_days is defined else 3650  }}"

            repack: "{{  repack | default( false ) | lower == 'true' if repack is defined else false  }}"



        #  Wait purge to complete
        
    #TODO come fare controllo nel caso si eseguisse due volte di seguito?!? o solo con keepdays?!?  controllo repack = false
        - wait_template: "{{  states( 'sensor.system_database_size' ) | float < database_size | float  }}"
        # - wait_template: >-
        
            # {{

                # states( 'sensor.system_database_size' ) | float < database_size | float
                
                    # or

                # states( 'sensor.system_database_size' ) | float < 0.001 
            
            # }}



        - service: persistent_notification.create

          data:
                  
            #TODO
            title: 'Compattazione Database'

            message: |-
            
              La compattazione del database è terminata

              {{  states( 'sensor.system_time' )  }} &nbsp; &nbsp; {{  states( 'sensor.system_date' )  }}






    - service: recorder.enable




```

**Reply by 50494554524F** [reply]
sistemato lo script

https://pastebin.com/AmzxU1DV

ora si possono usare anche le wildcard per gli object_id da escludere dalla pulizia...

devo vedere se si può mostrare il progresso in un popup al posto delle notifiche, migliorerebbe un po' la velocità...

**Comment by AndreaTo1** [comment]
Mi aggancio a questo post visto che il tema è lo stesso.. 

Ho pulito i dati di alcune entità, nello specifico continuano a registrare le entità anche se sono nella lista delle esclusioni nel configuration.yaml

Sbaglio qualcosa nella sintassi?
(qui purge_keep_days è commentato per ora perché sto cancellando manualmente tramite automazione)

```
recorder:
#  purge_keep_days: 7
  auto_repack: false
  exclude:
    domains:
      - automation
      - update
    entity_globs:
      - sensor.sun*
      - weather.*
      - button.netatmo_*
      - climate.netatmo_*
      - sensor.netatmo_*
      - select.netatmo_*
    entities:
      - sensor.last_boot
      - sun.sun
      - sensor.date
      - calendar.calendario
      - tts.google_en_com
      - sensor.energia_residua_batteria
      - sensor.ad_battery_level_3
      - sensor.byd_battery_box_premium_hv_capacita_massima
```
