### DISCUSSION TITLE
Leggere volume speaker alexa e salvarlo in una variabile

### DISCUSSION THREAD

**Discussion by reiner348** [indomus/forum#2405] [GENERALE - Discussioni generiche]
Ciao a tutti!
Presumo che la mia domanda avrà una risposta banale, ma ci sto litigando da giorni e non riesco a uscirne... 
Vorrei prelevare da uno speaker alexa, integrato tramite alexa media, il suo volume, per poi modificarlo, fare un annuncio, e rimetterlo dov'era. Riesco a fare tutto, tranne a salvare il volume iniziale...
Il codice che ho, per leggere il valore e salvarlo, è questo:
```
input_number:
  echo_volume_bud:
    name: echo_volume_bud
    min: 0
    max: 1
    step: 0.01
script:
  bud_save_dot_volume:
    sequence:
    - service: input_number.set_value
      data:
        value_template: "{{ state_attr('media_player.bud', 'volume_level') | float }}"
      target:
        entity_id: input_number.echo_volume_bud
  mode: single
```
Il value template funziona, ho verificato nella sezione development di HA e mi restituisce il valore corretto del volume (esempio, "0.12" se il volume è al 12%). Però me lo restituisce come "string", per questo ho aggiunto | float nel value template. Nell'esempio precedente, m lo restituisce il valore con doppi apici inclusi, "0.12". Se però provo a togliere "" da value template ottengo un errore al check prima di riavviare HA. 
Forse è qualche errore di sintassi, o forse... non lo so, non riesco a capire...
Qualche suggerimento?
