### DISCUSSION TITLE
Automazione trigger "platform: numeric_state" come verificare il valore del sensore se gia superiore alla soglia.

### DISCUSSION THREAD

**Discussion by mosix76** [indomus/forum#2408] [HUB: Home Assistant]
Riporto il mio caso per capire bene come utilizzare questi strumenti. 
Ho un automazione che attivo alle 8:30 di mattina, e fra le varie cose deve intervenire se la tensione di una stringa del fotovoltaico e' superiore a un certo valore (290V). 
Mi sta capitando che, al momento dell'attivazione dell'automazione, la tensione e' gia superiore al valore di soglia impostata, per cui l'automazione non interviene.

Codice dell'automazione:
```
alias: F1 P1 Boiler ON
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.powerfromline
    for:
      hours: 0
      minutes: 0
      seconds: 20
    below: -1400
  - platform: numeric_state
    entity_id: sensor.inverter_pv_2_voltage
    for:
      hours: 0
      minutes: 3
      seconds: 0
    above: 290
    enabled: true
  - platform: numeric_state
    entity_id: sensor.snfbasic_ds18b20_temperature
    below: 33
    for:
      hours: 0
      minutes: 10
      seconds: 0
condition: []
action:
  - type: turn_on
    device_id: 5186a656632b9f025ea71bf4daa
    entity_id: switch.snfpow_boilerp1
    domain: switch
  - type: turn_on
    device_id: 3e4dfdb7e1a1a12b0db2810f866
    entity_id: switch.snf_basic
    domain: switch
mode: single
```

**DOMANDA**: Come andrebbe impostato la condizione del
trigger:
platform: numeric_state
affinche almeno la prima volta che attivo l'automazione, verifichi il valore del sensore, piuttosto che stare a guardare solo se passa dalla soglia?
