### DISCUSSION TITLE
Connessione SSH Cloudflared

### DISCUSSION THREAD

**Discussion by andreadannibale** [indomus/forum#2409] [Networking]
Buongiorno, ho seguito la vostra guida per creare un tunnel con cloudflare tramite un dominio personale.. ho configurato il tutto tramite docker compose.. mi connetto correttamente da remoto all'installazione di HA core (sempre su docker). 

Il tutto gira su un mini pc con Ubuntu. Non ho un indirizzo ip pubblico.

Ora vorrei fare la stessa procedura per collegarmi tramite ssh, ho modificato il config come da doc:
```
tunnel: UUID
credentials-file: /root/.cloudflared/UUID.json

ingress:
  # home assistant core:
  - hostname: hass.miodominio.com
    service: IPinterno:8123
  # SSH
  - hostname: ssh.miodominio.com
    service: ssh://localhost:22
```

Tramite questa config non riesco a connettermi; credo di aver capito che localhost non può essere risolto dal container docker. 

Non riesco ad andare avanti purtroppo..
