### DISCUSSION TITLE
Modbus ed Epever

### DISCUSSION THREAD

**Discussion by goldrake1981** [indomus/forum#2420] [HUB: Home Assistant]
Buongiorno, 
ho acquistato tempo fa un modulo epever wifi 01 per monitorare la produzione solare di uno dei miei regolatori di carica.
Il modulo funziona solo che ogni tanto HA non riesce a ricevere i dati dal modulo. Questo avviene in modo random nel ordine delle 3 o 4 volte al giorno. A volte tutto torna a funzionare da solo altre volte baata un riavvio di tutta la configurazione yaml per far si che il modulo torni a funzionare. MI sono accorto che negli unltimi due giorni anche un sensore ( Produzione fotovoltaica Epever ) inserito nella plancia enrergia HA mi ha prima inserito un valore molto alto nella produzione energia molto simile alla produzione totale del regolatore di carica, e poi oggi non inserisce niente. Fino all'altro ieri funzionava normalmente inserendo la produzione oraria. 
Ho provato a cambiare delay , timeout, retries e scan_interval senza successo, il comportamento non cambia.
Sono nuovo di HA e di queste cose in genere, cerco di imparare leggendo guide a destra e a manca e quindi perdonatemi se nel codice che inserisco ci sono errori .
Grazie a chi può aiutarmi

```
#EPEver eBox-Wifi-01 modbus
modbus:
  - name: Sol3
    type: rtuovertcp
    host: 192.168.11.85
    delay: 5
    port: 8088
    timeout: 600
    close_comm_on_error: false
    retry_on_empty: true
    retries: 100
    sensors:
      - name: "Sol3 Solar V"
        device_class: voltage
        slave: 7
        address: 12544
        input_type: input
        scale: 0.01
        precision: 2
        scan_interval: 60
      - name: "Sol3 Solar A"
        unit_of_measurement: A
        device_class: current
        slave: 7
        address: 12545
        input_type: input
        scale: 0.01
        precision: 2
        scan_interval: 60
      - name: "Sol3 Charging W"
        unit_of_measurement: W
        device_class: power
        slave: 7
        address: 12546
        input_type: input
        data_type: int32
        scale: 0.01
        count: 2
        precision: 2
        swap: word
        scan_interval: 60
      - name: "Sol3 Battery V"
        unit_of_measurement: V
        device_class: voltage
        slave: 7
        address: 13082
        input_type: input
        scale: 0.01
        precision: 2
        scan_interval: 60
      - name: "Sol3 WH Today energy"
        device_class: energy
        unit_of_measurement: kWh
        slave: 7
        address: 13068
        input_type: input
        data_type: int32
        scale: 0.01
        precision: 2
        count: 2
        swap: word
        scan_interval: 60
      - name: "Sol3 WH Month energy"
        device_class: energy
        unit_of_measurement: kWh
        slave: 7
        address: 13070
        input_type: input
        data_type: int32
        scale: 0.01
        precision: 2
        count: 2
        swap: word
        scan_interval: 60
      - name: "Sol3 WH Year energy"
        device_class: energy
        unit_of_measurement: kWh
        slave: 7
        address: 13072
        input_type: input
        data_type: int32
        scale: 0.01
        precision: 2
        count: 2
        swap: word
        scan_interval: 60
      - name: "Sol3 WH Total energy"
        device_class: energy
        unit_of_measurement: kWh
        slave: 7
        address: 13074
        input_type: input
        data_type: int32
        scale: 0.01
        precision: 2
        count: 2
        swap: word
        scan_interval: 60

template:
  - sensor:
      - name: Produzione fotovoltaica Epever
        unit_of_measurement: "kWh"
        state_class: total_increasing
        device_class: energy
        state: "{{ states('sensor.sol3_wh_today_energy') }}"
```
