### DISCUSSION TITLE
Lanciare script da Apple Watch

### DISCUSSION THREAD

**Discussion by Matty1184** [indomus/forum#2425] [GENERALE - Discussioni generiche]
Ciao a tutti, 
ho creato un azione dal menu dell'app denominata "Chiudi Tapparelle", visibile da watch, creato un automazione con:
attivazione: ios.action.fired
dati evento: actionName: Chiudi Tapparelle
e come azioni ho messo uno script.
per prova ho messo un commuta luce ma aimè non funziona.
è corretto creare un azione per watch in questo modo?
premetto che le scene fuznionamo correttamente...

**Comment by Scialla** [comment]
il "pulsante" (o Action) su iPhone/Apple Watch lo crei o sull'app companion, oppure sul file `configuration.yaml` come da documentazione, es.:
```
ios:
  actions:
    - name: bed_time
      background_color: "#000000"
      label:
        text: "Buonanotte"
        color: "#ff0000"
      icon:
        icon: bed
        color: "#ffffff"
```
l'automazione che intercetta l'azione la crei con, ad es.:
```
automation:
  - alias: "Spegni tutte le luci"
    initial_state: true
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: "bed_time"
    action:
      - service: light.turn_off
        entity_id: group.all_lights
```
Ovviamente puoi metterci il tuo script al posto dello spegnimento delle luci.

Tutto documentato qui:
https://companion.home-assistant.io/docs/core/actions/

**Reply by Matty1184** [reply]
grazie mille,
ho provato a modificare nomi e automazioni ma non riesco a farlo girare....
configuration:
```
ios:
  actions:
    - name: Chiudi_Tapparelle_no_bagno
      background_color: "#000000"
      label:
        text: "Chiudi Tapparelle (no Bagno)"
        color: "#ff0000"
      icon:
        icon: bed
        color: "#ffffff"
```
e confermo che su watch sinronizza correttamente la funzione
automazione:
```
alias: Watch - Chiusura Tapparelle (no Bagno)
description: ""
trigger:
  - platform: event
    event_type: ios.action.fired
    event_data:
      actionName: Chiudi_Tapparelle_no_bagno
condition: []
action:
  - type: toggle
    device_id: c7fadd4dae5c8a9c6b200c010a2d9c76
    entity_id: light.luce_lavello_garage_lightbulb
    domain: light
mode: single
```
NB: come prova ho impostato l'azione con commuta luce lavello per capire se funziona.
l'automazione non viene mai avviat
