### DISCUSSION TITLE
[RISOLTO]Problema Caddy: Errore 502 - Bad Gateway

### DISCUSSION THREAD

**Discussion by addocm** [indomus/forum#2427] [HUB: Home Assistant]
Ciao a tutti,
Ho iniziato da pochissimo a utilizzare HA Core, che ho installato su un Mini PC con OS Ubuntu su docker.
Sto avendo problemi a raggiungere HA dall'esterno della LAN, cerco di spiegarmi meglio:
ho seguito la guida [https://indomus.it/guide/collegarsi-da-remoto-a-home-assistant-via-reverse-proxy/](url), installando Caddy come container docker, facendo generare i certificati (e ottenendo i messaggi di creazione completata come mostrato nella guida linkata), utilizzando DuckDNS avendo io un indirizzo IP pubblico ma dinamico. Ho aperto correttamente le porte sul mio FritzBox (la 443 e la 9000) e ho modificato il Caddyfile come indicato, oltre anche a modificare il file Configuration.yaml di HA.

Purtroppo, quando cerco di raggiungere HA dall'esterno della LAN, tramite l'indirizzo https://nomedominio.duckdns.org:9000, ricevo l'errore 502 - BAD GATEWAY.

Il Caddyfile è il seguente:
```
(https_header) {
  header {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}

https://nomedominio.duckdns.org { 
  respond "Saluti dal Crew inDomus.it"
  file_server
}

https://nomedominio.duckdns.org:9000 { 
  import https_header
  reverse_proxy http://127.0.0.1:8123
}
```
Preciso che l'istanza di HA e di Caddy sono eseguite sulla medesima macchin (il mini PC).

Il file Configuration.yaml è il seguente:
```

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.2

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```
l'indirizzo IP segnato in `trusted_proxies` l'ho ricavato con il comando `docker network inspect bridge` dove nel blocco "Containers" l'IPv4Address riportato era appunto quello riportato nel file.

Grazie a chiunque possa darmi una mano e se servono altre informazioni, chiedetemele!
