### DISCUSSION TITLE
[Risolto] - Impossibile utilizzare scene in Routine di Google Home

### DISCUSSION THREAD

**Discussion by matteo-vannucchi** [indomus/forum#2440] [HUB: Home Assistant]
Ciao,

per provare a forzare un ricaricamento dei dispositivi collegati a Google Home tramite le vostre guide (integrazione via gcp e local fullfillment), ho fatto, dentro Google Home, unlink account del servizio che avevo creato.

Ho ricollegato l'account e riesco a controllare i singoli dispositivi, ma se provo ad utilizzare le scene all'interno delle routine, ricevo il servizio non è disponibile al momento.

Avete idea di come risolvere?

**Comment by matteo-vannucchi** [comment]
Aggiungo che questa è la configurazione yaml per l'integrazione:

``` yaml
 project_id: home-assistant-XXXXX
  service_account: !include home-assistant-XXXXXXXXXXX.json
  report_state: true
  exposed_domains:
    - switch
    - climate
    - light
    - scene
    - script
```
