### DISCUSSION TITLE
[Solved] Aiuto: google home e batteria fotovoltaico

### DISCUSSION THREAD

**Discussion by labionda67** [indomus/forum#2452] [GENERALE - Discussioni generiche]
Buongiorno a tutti,
vorrei far in modo che chiedendo al mio assistante google "Dimmi quant'è la carica della batteria del fotovoltaico" questo mi risponda la percentuale della carica della batteria dello stesso. L'inverter è della SolarEdge ed è già integrato su Home assistant che gira sul mio nas synology come macchina virtuale. Avevo letto qualcosa riguardo Dialogflow ma il prossimo mese dovrebbe essere disattivato se non ho capito male.
Esiste qualche guida o un vostro suggerimento che mi possa aiutare a fare ciò che cerco?
Vi ringrazio in anticipo.
Angelo

**Comment by indomus** [comment]
> Buongiorno a tutti, vorrei far in modo che chiedendo al mio assistante google "Dimmi quant'è la carica della batteria del fotovoltaico" questo mi risponda la percentuale della carica della batteria dello stesso. L'inverter è della SolarEdge ed è già integrato su Home assistant che gira sul mio nas synology come macchina virtuale. Avevo letto qualcosa riguardo Dialogflow ma il prossimo mese dovrebbe essere disattivato se non ho capito male. Esiste qualche guida o un vostro suggerimento che mi possa aiutare a fare ciò che cerco? Vi ringrazio in anticipo. Angelo

ti basta scriverti uno script che faccia parlare google leggendo quel che credi, ed evocare tale script via google tramite attivazione vocale della frase che più trovi appropriata.

**Comment by labionda67** [comment]
Grazie, sto provando ma qualcosa non funziona nel senso che chiedo all'assistente google, ci pensa un attimo e non mi risponde nulla.
Di seguito il codice che ho usato come script:

```
carica_batteria_fotovoltaico:
   alias: carica_batteria_fotovoltaico
   sequence:
   - service: tts.google_say
     data:
       message: "La carica della batteria del fotovoltaico è al {{ states('sensor.fotovoltaico_battery1_state_of_charge') }} per cento."
       cache: false
```
