### DISCUSSION TITLE
Calendario con garbage collector

### DISCUSSION THREAD

**Discussion by Fedeli92** [indomus/forum#2455] [HUB: Home Assistant]
Salve a tutti!
Stavo seguendo una guida su youtube (https://www.youtube.com/watch?v=RpwAhy7f52I) per integrare il calendario con i giorni di ritiro della raccolta differenziata, per poi integrarla con la funzione TTS per le notifiche.
Ho configurato così il file configuration.yaml
```yaml
template:
  - sensor:
      - name: giorni_carta
        state: >
          {{ min(((state_attr('calendar.carta','start_time')  | as_timestamp - today_at('00:00') | as_timestamp) / 86400) | int,2) }}
        attributes:
          days: >
            {{ ((state_attr('calendar.carta','start_time')  | as_timestamp - today_at('00:00') | as_timestamp) / 86400) | int }}
      - name: giorni_plastica
        state: >
          {{ min(((state_attr('calendar.plastica','start_time')  | as_timestamp - today_at('00:00') | as_timestamp) / 86400) | int,2) }}
        attributes:
          days: >
             {{ ((state_attr('calendar.plastica','start_time')  | as_timestamp - today_at('00:00') | as_timestamp) / 86400) | int }}
      - name: giorni_secco
        state: >
          {{ min(((state_attr('calendar.secco','start_time')  | as_timestamp - today_at('00:00') | as_timestamp) / 86400) | int,2) }}
        attributes:
          days: >
            {{ ((state_attr('calendar.secco','start_time')  | as_timestamp - today_at('00:00') | as_timestamp) / 86400) | int }}
```

Ho creato gli stati e tutto quello che viene detto.

Ora sto creando la scheda nella homepage, però inserendo questo codice

```yaml
type: custom:config-template-card
entities:
  - sensor.giorni_secco
variables:
  DAYS: states['sensor.giorni_secco']-attributes['days']+'d'
card:
  type: picture-entity
  entity: sensor.giorni_secco
  name: ${DAYS}
  show_name: true
  show_state: false
  state_images:
    '0': /home/pi/homeassistant/immagini/Cestino_pieno.png
    '1': /home/pi/homeassistant/immagini/Cestino_vuoto.png
    '2': /home/pi/homeassistant/immagini/Cestino_vuoto.png
```

mi ritrovo la scheda senza immagini e senza altre informazioni. Completamente vuota
![image](https://user-images.githubusercontent.com/57504557/236929113-0ae71e27-7769-4a64-9487-564d04bf3250.png)

Riuscite ad aiutarmi?
Grazie mille!
