### DISCUSSION TITLE
[Risolto] Lettura/Scrittura Registri Modbus Tipo "Flag" Ventilconvettori

### DISCUSSION THREAD

**Discussion by carl-bb** [indomus/forum#2464] [HUB: Home Assistant]
Buongiorno a tutti,

Ho dei ventilconvettori modello Riello Design Inverter Plus. I ventilconvettori sono controllabili tramite comando a bordo ma anche tramite interfaccia seriale Modbus RS485. Ho a disposizione la tabella dei registri modbus che allego e collegandomi ad un fancoil con il notbook tramite convertitore USB-RS485 riesco con programma [modpoll](https://www.modbusdriver.com/modpoll.html) a leggere e scrivere i vari registri. Fatto questo test la mia intenzione ora è di tirare i cavi bus e integrare la gestione dei ventilconvettori in Home Assistant. 

Leggendo la documentazione dell' integrazione modbus di HA ho predisposto la configurazione tipo da aggiungere al file configuration.yaml in modo da avere un'entità climate per ciascun ventilconvettore. Una cosa di questo tipo:

```yaml
modbus:
  - name: "fancoil_hub"
    port: /dev/ttyUSB0
    type: serial
    method: rtu
    baudrate: 9600
    bytesize: 8
    stopbits: 1
    parity: N

    climates:
      - name: fancoil_soggiorno
        slave: 2
        scan_interval: 15
        scale: 0.1
        address: 0 # current_temp_register
        max_temp: 28
        min_temp: 16
        target_temp_register: 231
      - name: fancoil_cucina
        slave: 3
        # ...  e via di seguito gli altri fancoil ...     

```

La questione nasce nel momento in cui devo interfacciarmi non con dei registri come quelli Temperatura o Setpoint che restituiscono un' intero ma con registri come il n. 201 PRG (vedi pdf allegato) che sono registri di tipo "Flag" ovvero che vanno letti interpretandoli bit a bit. Nello specifico, il registro PRG consente di leggere/settare diverse cose: il 7mo bit controlla lo stato ON/OFF del fancoil, il 4o bit lo stato LOCK/UNLOCK della tastiera a bordo e i primi 3 bit la modalità di funzionamento AUTO/MIN/NOTTE/MAX.

Ad esempio per lo stato ON/LOCK/AUTO io leggo il decimale 16 ma che va interpretato come in figura:

![Screenshot 2023-05-13 161718](https://github.com/indomus/forum/assets/70807772/bfa31c0d-0eb7-4e5c-a458-faaae33368ce)

La domanda è : Come posso gestire registri di questo tipo in HomeAssistant?

Di seguito il pdf con tabella registri:  [Riello-Fancoil-Parametri-RS485.pdf](https://github.com/indomus/forum/files/11469863/Riello-Fancoil-Parametri-RS485.pdf)

**Comment by carl-bb** [comment]
Buongiorno a tutti,

Aggiorno la situazione. Sono quasi arrivato ad integrare il tutto ma ho un problema.

Ho configurato i fancoil tramite l' integrazione Modbus creando le entità Climate ma queste entità vanno bene solo per impostare il setpoint ma non per impostare le modalità  di funzionamento in quanto come dicevo nel post precedente tali impostazioni richiedono di leggere/scrivere singoli bit dei corrispondenti registri modbus.

Allora ho proceduto andando a definire tutti i vari sensori 'modbus' riportati nella tabella del produttore che mi leggono i valori interi e una serie di template binary_sensor che mi vanno a leggere lo stato dei singoli bit d'interesse per i registri di tipo 'flag', in questo modo:

configuration.yaml
``` yaml
# riello fancoils (modbus RS485 network)
modbus:
  - name: "fancoil_hub"
    port: /dev/ttyUSB0
    type: serial
    method: rtu
    baudrate: 9600
    bytesize: 8
    stopbits: 1
    parity: N

    sensors:  !include_dir_merge_list fancoil_hub/modbus_sensors/
    climates: !include fancoil_hub/modbus_climate.yaml

template:
  - binary_sensor: !include_dir_merge_list fancoil_hub/template_binary_sensors
  
climate: !include_dir_merge_list fancoil_hub/template_climates

```

esempio modbus_sensor

``` yaml
# FANCOIL SOGGIORNO - MODBUS SENSORS
# ----------------------------------

# TEMPERATURA ARIA
# Temperatura Aria AIR {R}
- name: "fc_soggiorno_t1"
  unique_id: "v1_T1"
  slave: 2
  scan_interval: 15
  scale: 0.1
  precision: 1
  min_value: 0
  max_value: 100
  device_class: temperature
  state_class: measurement
  unit_of_measurement: °C
  address: 0

### ecc ecc per tutti gli altri sensori ###

```
esempio template_binary_sensor

``` yaml
# FANCOIL SOGGIORNO - BINARY SENSORS
# ----------------------------------

# FLAG CONFIGURAZIONE {R/W}
# Modalità Stand-By
- name: "fc_soggiorno_mod_stdby"
  unique_id: "v1_MOD_STDBY"
  state: "{{ states('sensor.fc_soggiorno_prg')|int|bitwise_and(128) > 0 }}"
# Blocco Tastiera
- name: "fc_soggiorno_key_lock"
  unique_id: "v1_KEY_LOCK"
  state: "{{ states('sensor.fc_soggiorno_prg')|int|bitwise_and(16) > 0 }}"
# Modo Ventilatore: AUTO
- name: "fc_soggiorno_mod_auto"
  unique_id: "v1_MOD_AUTO"
  state: "{{ states('sensor.fc_soggiorno_prg')|int|bitwise_and(7) == 0 }}"
# Modo Ventilatore: MIN
- name: "fc_soggiorno_mod_min"
  unique_id: "v1_MOD_MIN"
  state: "{{ states('sensor.fc_soggiorno_prg')|int|bitwise_and(7) == 1 }}"
# Modo Ventilatore: NOTTE
- name: "fc_soggiorno_mod_notte"
  unique_id: "v1_MNOTTE"
  state: "{{ states('sensor.fc_soggiorno_prg')|int|bitwise_and(7) == 2 }}"
# Modo Ventilatore: MAX
- name: "fc_soggiorno_mod_max"
  unique_id: "v1_MOD_MAX"
  state: "{{ states('sensor.fc_soggiorno_prg')|int|bitwise_and(7) == 3 }}"

# .....   .....  .....    .....   .....  .....     .....   .....  .....    .....   .....  .....    .....   .....  .....  #

# FLAG ALLARMI {R}
# Allarme Comunicazione
- name: "fc_soggiorno_alr_com"
  unique_id: "v1_ALR_COM"
  state: "{{ states('sensor.fc_soggiorno_alr_stat')|int|bitwise_and(1) > 0 }}"
# Allarme Sonda AIR
- name: "fc_soggiorno_alr_air"
  unique_id: "v1_ALR_AIR"
  state: "{{ states('sensor.fc_soggiorno_alr_stat')|int|bitwise_and(2) > 0 }}"
# Allarme Sonda H4
- name: "fc_soggiorno_alr_h4"
  unique_id: "v1_ALR_H4"
  state: "{{ states('sensor.fc_soggiorno_alr_stat')|int|bitwise_and(4) > 0 }}"
# Allarme Acqua Non Idonea
- name: "fc_soggiorno_alr_acq_dan"
  unique_id: "v1_ALR_ACQ_DAN"
  state: "{{ states('sensor.fc_soggiorno_alr_stat')|int|bitwise_and(8) > 0 }}"
# Allarme Sonda H2
- name: "fc_soggiorno_alr_h2"
  unique_id: "v1_ALR_H2"
  state: "{{ states('sensor.fc_soggiorno_alr_stat')|int|bitwise_and(16) > 0 }}"
# Allarme Temperatura Acqua H4 Non Idonea
- name: "fc_soggiorno_alr_h4_nid"
  unique_id: "v1_ALR_H4NID"
  state: "{{ states('sensor.fc_soggiorno_alr_stat')|int|bitwise_and(32) > 0 }}"
# Allarme Temperatura Resistenza
- name: "fc_soggiorno_alr_hi_res"
  unique_id: "v1_ALR_HIRES"
  state: "{{ states('sensor.fc_soggiorno_alr_stat')|int|bitwise_and(64) > 0 }}"
# Allarme Guasto Motore
- name: "fc_soggiorno_alr_mot"
  unique_id: "v1_ALR_MOT"
  state: "{{ states('sensor.fc_soggiorno_alr_stat')|int|bitwise_and(128) > 0 }}"
# Allarme Contatto GRID Aperto
- name: "fc_soggiorno_alr_grid"
  unique_id: "v1_ALR_GRID"
  state: "{{ states('sensor.fc_soggiorno_alr_stat')|int|bitwise_and(256) > 0 }}"
# Allarme Temperatura Acqua H2 Non Idonea
- name: "fc_soggiorno_alr_h2_nid"
  unique_id: "v1_ALR_H2NID"
  state: "{{ states('sensor.fc_soggiorno_alr_stat')|int|bitwise_and(512) > 0 }}"
# Allarme Filtro Sporco
- name: "fc_soggiorno_alr_filtro"
  unique_id: "v1_ALR_FILTRO"
  state: "{{ states('sensor.fc_soggiorno_alr_stat')|int|bitwise_and(1024) > 0 }}"
# Allarme Comunicazione Sonda Aria Remota / Presenza Sonde Aria Multiple
- name: "fc_soggiorno_alr_2airm4"
  unique_id: "v1_ALR_2AIRM4"
  state: "{{ states('sensor.fc_soggiorno_alr_stat')|int|bitwise_and(2048) > 0 }}"
```

Fin qui tutto ok, poi per avere un' entità climate utile ho utilizzato il componente custom  [Climate Template](https://github.com/jcwillox/hass-template-climate) che mi permette di usare i template facendo le operazioni bit-a-bit richieste per leggere e settare i vari stati. La configurazione che ho settato è la seguente:

```yaml
- platform: climate_template
  name: Soggiorno
  unique_id: v1_climate_template
  min_temp: 16
  max_temp: 28
  precision: 0.1
  temp_step: 0.5
  swing_modes:
    - "on"
    - "off"
  modes:
    - "heat"
    - "cool"
  fan_modes:
    - "auto"
    - "low"
    - "medium"
    - "high"

  availability_template: "{{is_state('binary_sensor.fc_soggiorno_com_err','off')}}"

  current_temperature_template: "{{states('sensor.fc_soggiorno_t1')}}"
  target_temperature_template: "{{states('sensor.fc_soggiorno_sp')}}"

  swing_mode_template: "{{iif(is_state('binary_sensor.fc_soggiorno_stdby','off'), 'on', 'off')}}"

  hvac_mode_template: "{{iif(is_state('sensor.fc_soggiorno_man','3'), 'heat', 'cool')}}"

  hvac_action_template: >
    {% if is_state('binary_sensor.fc_soggiorno_mod_raff','on') %}
    heating
    {% elif is_state('binary_sensor.fc_soggiorno_mod_risc','on') %}
    cooling
    {% else %}
    idle
    {% endif %}

  fan_mode_template: >
    {% if is_state('binary_sensor.fc_soggiorno_mod_auto','on') %}
    auto
    {% elif is_state('binary_sensor.fc_soggiorno_mod_notte','on') %}
    low
    {% elif is_state('binary_sensor.fc_soggiorno_mod_min','on') %}
    medium
    {% else %}
    max
    {% endif %}


  set_temperature:
    - service: modbus.write_register
      data:
        hub: fancoil_hub
        slave: 2
        address: 231
        value: "{{ state_attr('climate.soggiorno', 'temperature') | int * 10}}"

  set_hvac_mode:
    - service: modbus.write_register
      data:
        hub: fancoil_hub
        slave: 2
        address: 233
        value: "{{iif(is_state('climate.soggiorno','heat'), 3, 5) | int }}"

  set_fan_mode:
    - service: modbus.write_register
      data:
        hub: fancoil_hub
        slave: 2
        address: 201
        value: >
          {% if is_state_attr('climate.soggiorno','fan_mode', 'auto') %}
          {{ states('sensor.fc_soggiorno_prg') | int | bitwise_and(65528) }}
          {% elif is_state_attr('climate.soggiorno','fan_mode', 'low') %}
          {{ states('sensor.fc_soggiorno_prg') | int | bitwise_and(65530) | bitwise_or(2) }}
          {% elif is_state_attr('climate.soggiorno','fan_mode', 'medium') %}
          {{ states('sensor.fc_soggiorno_prg') | int | bitwise_and(65529) | bitwise_or(1) }}
          {% else %}
          {{ states('sensor.fc_soggiorno_prg') | int | bitwise_and(65531) | bitwise_or(3) }}
          {% endif %}

  set_swing_mode:
    - service: modbus.write_register
      data:
        hub: fancoil_hub
        slave: 2
        address: 201
        value: >
          {% if is_state_attr('climate.soggiorno','swing_mode', 'on') %}
          {{ states('sensor.fc_soggiorno_prg') | int | bitwise_or(128) }}
          {% else %}
          {{ states('sensor.fc_soggiorno_prg') | int | bitwise_and(65407) }}
          {% endif %}
```

Qui nasce il problema... l' entità funziona in lettura nel senso che temperatura, setpoint, on/off, modo ventola, modo stagionale vengono letti e aggiornati correttamente. ho anche provato a modificare le impostazioni dal comando a bordo del fancoil e vengono riflesse nell'entità climate_template. Quando però provo a modificare qualcosa dalla UI del termostato le varie azioni non funzionano.

Nei log ho: `[homeassistant.helpers.script.soggiorno] Soggiorno: Running script requires passing in a context`

Però provando dal tab 'Developer Tools' della UI di Home Assistant ad eseguire i vari servizi `modbus.write_register` impostati nella configurazione sopra tutti funzionano.

Mi sfugge qualcosa, qualcuno può aiutarmi?
