### DISCUSSION TITLE
Notifica appuntamento local calendar con una determinata denominazione

### DISCUSSION THREAD

**Discussion by evirci** [indomus/forum#2466] [GENERALE - Discussioni generiche]
Buongiorno a tutti,
sapreste consigliarmi come ricevere una notifica quando si verifica l'ora di un appuntamento con un determinato nome?

Ho scritto questo codice con l'aiuto di un altro gentile utente, ma non so dove sbaglio...
Il calendario si chiama calendar.pippo e l'appunto è denominato "Prova"

Grazie per l'aiuto

```
alias: Automazione prova
description: ""
trigger:
  - platform: calendar
    event: start
    offset: "-0:0:0"
    entity_id: calendar.pippo
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.calendar_event.summary.lower()== 'Prova' }}"
        sequence:
          - device_id: xxxxxxxxx
            domain: mobile_app
            type: notify
            message: Prova
            title: Prova
mode: single
```

**Comment by indomus** [comment]
```
alias: Automazione prova
description: ""
trigger:
  - platform: calendar
    event: start
    entity_id: calendar.pippo
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.calendar_event.summary.lower()== 'prova' }}"
        sequence:
          - device_id: xxxxxxxxx
            domain: mobile_app
            type: notify
            message: Prova
            title: Prova
mode: single
```

prova così
