### DISCUSSION TITLE
[SOLVED] MQTT e Shelly 2.5 non disponible

### DISCUSSION THREAD

**Discussion by naverre** [indomus/forum#2467] [HUB: Home Assistant]
Salve, a fini "didattici" sto provando ad integrare uno Shelly 2.5 tramite protocollo MQTT.
Ho configurato il dispositivo e tramite MQTT Explorer ho visto che lo Shelly pubblica i vari topic, ma non sto riuscendo ad integrarlo in HA, o meglio, lo trovo tra le varie entità ma è indicato come non disponibile.
Questo è il codice che ho inserito nel file configuration:
```yaml

mqtt:
  switch:
  - name: "Canale 1"
    icon: mdi:lightbulb
    state_topic: "shellies/prova/relay/0"
    command_topic: "shellies/prova/relay/0/command"
    availability_topic: "shellies/prova/online"
    optimistic: false
    payload_on: "on"
    payload_off: "off"
    payload_available: "true"
    payload_not_available: "false"
    retain: false
    qos: 1

```
Potreste aiutarmi a capire dove sbaglio?

**Comment by Scialla** [comment]
sembra corretto, hai fatto un announce?
```
- alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  action:
  - data:
      payload: announce
      topic: shellies/command
    service: mqtt.publish
 ```

**Reply by snakuzzo** [reply]
In realtà per fare una cosa precisa andrebbe fatta così...


```yaml
- alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      payload: announce
      topic: shellies/command
  - service: mqtt.publish
    data:
      topic: shellies/command
      payload: update
```

l'announce non recupera lo "STATO" (che arriverebbe solo al massimo entro 30 secondi).
Con l'update invece recuperi immediatamente lo stato delle entità
