### DISCUSSION TITLE
ESPHome - Cover component

### DISCUSSION THREAD

**Discussion by cl-7k-01** [indomus/forum#2469] [Hardware & Firmware]
Buongiorno a tutti,
mi sto cimentando in ESPHome ma ho alcune difficoltà.
Ho flashato correttamente un firmware che contiene alcuni binary_sensor, switch e cover.
Nello specifico:

```
switch:
  - platform: gpio
    name: "relay_1"
    id: relay_1
    interlock: [relay_2]
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 0
      mode: OUTPUT
      inverted: true

    
  - platform: gpio
    name: "relay_2"
    id: relay_2
    interlock: [relay_1]
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 1
      mode: OUTPUT
      inverted: true

cover:
  - platform: time_based
    name: "Cover1"
    id: cover1
    
    open_action:
      - switch.turn_on: relay_1
    open_duration: 0.52min

    close_action:
      - switch.turn_on: relay_2
    close_duration: 0.52min

    stop_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2

binary_sensor:
  - platform: gpio
    name: "input1"
    id: input1
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 0
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_click:
      then:
        - cover.open: cover1

  - platform: gpio
    name: "input2"
    id: input2
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 1
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_click:
      then:
        - cover.close: cover1
```

Con questa impostazione, i binary_sensor ricevono "lo stato" da due pulsanti fisici e fanno partire rispettivamente l'apertura e la chiusura della tapparella. All'evento "on_click" eseguono rispettivamente l'azione cover.open e cover.close.
Vorrei poter condizionare questa azione usando come "test" lo stato della tapparella: se ferma, se in apertura, se in chiusura.
Nella documentazione ufficiale ho trovato "current_operation" che restituirebbe appunto i valori:
COVER_OPERATION_IDLE, COVER_OPERATION_CLOSING e COVER_OPERATION_OPENING
```
if (id(my_cover).current_operation == CoverOperation::COVER_OPERATION_IDLE) {
  // Cover is idle
} else if (id(my_cover).current_operation == CoverOperation::COVER_OPERATION_OPENING) {
  // Cover is currently opening
} else if (id(my_cover).current_operation == CoverOperation::COVER_OPERATION_CLOSING) {
  // Cover is currently closing
}

```
ma è da usare con Lambdas (se ho capito bene...) e non riesco a inserirlo correttamente all'interno del mio sketch, credo di commettere errori di sintassi e di non aver capito affondo come usare Lambdas. Qualcuno saprebbe indicarmi se sto procedendo correttamente e, se si, come inserire questo blocco nel mio sketch?
Come sempre grazie per l'attenzione.
