### DISCUSSION TITLE
Perdita storico template

### DISCUSSION THREAD

**Discussion by ster1um** [indomus/forum#2472] [HUB: Home Assistant]
dopo aggiornamento immagine HA perdo tutto lo storico.

è una cosa normale?
```
sensor:
  - platform: integration
    source: sensor.presa_tostapane_power
    name: "presa_tostapane_energia"
    unit_prefix: k
    round: 3

customize:
  sensor.presa_tostapane_energia:
    friendly_name: "Energia Tostapane"
    icon: mdi:counter
    last_reset: '1970-01-01T00:00:00+00:00'
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: kWh

```
