### DISCUSSION TITLE
Shelly 2.5 non funziona via configurazione yaml

### DISCUSSION THREAD

**Discussion by simorox** [indomus/forum#248] [HUB: Home Assistant]
Buongiorno,
ho un installazione di HomeAssistant con HASSIO su RASPI.
Ho acquistato dei moduli Shelly e stavo cominciando a configurare il 2.5.
Configurato il broker Mosquitto apparentemente senza problemi, con utente/password dedicati.

Aggiunto automazione di autoannounce MQTT, come segue:

```
- alias: MQTT Announce
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: mqtt.publish
    data:
      payload: announce
      topic: shellies/command

```
aggiunto lo switch in un mio package yaml come segue:

```
switch:
  - platform: mqtt
    name: "Leddo"
    state_topic: "shellies/shellyswitch25-D8F15B12F87F/relay/0"
    command_topic: "shellies/shellyswitch25-D8F15B12F87F/relay/0/command"
    availability_topic: "shellies/shellyswitch25-D8F15B12F87F/online"
    qos: 0
    payload_on: "on"
    payload_off: "off"
    payload_available: "true"
    payload_not_available: "false"
    optimistic: false
    retain: false
```

Nulla, non funziona, quando aggiungo l'entità in Lovelace, la vedo disponibile, setto lo switch su ON, ma dopo poco torna ad OFF automaticamente senza aver di fatto aver eccitato il relè Shelly.
Ho fatto diverse prove, cambiando il qos, sia su Shelly che nel file YAML, cambiando il nome shelly mettendone uno custom e rimettendo poi ancora il suo, nulla.

Provo ad aggiungere il mio Shelly come integrazione (per fortuna si è auto-trovato senza che io facessi nulla), ottimo, l'entità si crea da sola, la aggiungo in Lovelace e tutto per magia funziona.
La mia paura però che l'autodiscovery poi mi possa creare problemi con tutti gli altri dispositivi shelly che dovrò aggiungere, e sinceramente non amo troppo dipendere da dei "wizard" che magicamente appaiono tra le integrazioni.
Vorrei farlo funzionare con configurazione manuale, come ho fatto per tante altre integrazioni.

Tra l'altro la cosa buffa è che quando accendo lo switch dell'entità autocreata dall'integrazione, anche lo switch inserito manualmente da me cambia di stato (quindi è come se funzionasse in modalità "read-only")...
Non demordo, decido di installare MQTT explorer.
Qui scopro una cosa altrettanto buffa, entrambe le entità inviano messaggi al broker, ma quella che funziona lo fa con un topic del tipo: "shellies/shellyswitch25-D8F15B12F87F/relay/0" con poi contenuto del messaggio "0 = off" o "0 = on".
Mentre l'entità che ho configurato io manda messaggi sul topic "shellies/shellyswitch25-D8F15B12F87F/relay/0/command" con contentuto quindi "command = on"/"command = off".
A questo punto decido di editare il mio file YAML eliminando "command" dalla descrizione del topic:
command_topic: "shellies/shellyswitch25-D8F15B12F87F/relay/0"
in modo da avere lo stesso medesimo formato del messaggio dell'altra entità.
In effetti ora su MQTT explorer vedo messaggi identici, quando attivo lo switch su lovelace ora rimane su ON senza che torni indietro automaticamente come prima, ma nulla, il relè non vuole eccitarsi....
le ho provate tutte (con le mie forze/limitazioni tecniche) e dopo ore, ore, ed ore, sono qui a chiedere il vostro gentilissimo aiuto.

Grazie mille in anticipo,
Simone

**Comment by snakuzzo** [comment]
Ciao...allora

1. Quando posti il codice devi usare il markdown (leggi il regolamento). Ti chiedo quindi di modificare il post, altrimenti dovrò cancellarlo
2. Consiglio personale, scegli UN MODO di integrare gli shelly...non cominciare a mischiare le cose.
3. Personalmente preferisco l'integrazione via MQTT. Ti posto di seguito la mia configurazione...funzionante al 100%.

Questa l'automazione di announce

```yaml
- id: shelly_announce
  alias: Shelly Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    minutes: /59
  action:
  - service: mqtt.publish
    data:
      payload: announce
      topic: shellies/command
```

Questa la cover (ho sostituito già il mio topic con il tuo)...

```yaml
- platform: mqtt
  name: "matrimoniale"
  command_topic: "shellies/shellyswitch25-D8F15B12F87F/roller/0/command"
  position_topic: "shellies/shellyswitch25-D8F15B12F87F/roller/0/pos"
  state_topic: "shellies/shellyswitch25-D8F15B12F87F/roller/0"
  set_position_topic: "shellies/shellyswitch25-D8F15B12F87F/roller/0/command/pos"
  availability_topic: "shellies/shellyswitch25-D8F15B12F87F/online"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  state_opening: "open"
  state_closing: "close"
  state_stopped: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
```
