### DISCUSSION TITLE
Integrazione Shelly Plug S in Home Assistant tramite MQTT

### DISCUSSION THREAD

**Discussion by VeronicaMichelini** [indomus/forum#2480] [GENERALE - Discussioni generiche]
Ciao, sto seguendo la guida https://indomus.it/guide/integrare-shelly-plug-s-a-home-assistant-via-mqtt/ per integrare Shelly Plug S con MQTT. 
Premessa : Uso Home Assistant Core in Docker e anche il broker MQTT è in Docker. Il tutto su Raspberry Pi 3.

Questa è la configurazione del dispositivo via web, tutto come indicato nella guida.
![image](https://github.com/indomus/forum/assets/48562858/911469c7-61da-45c6-a039-2dab83a0bfb1)
Questo è il file configuration.yaml
```
# Loads default set of integrations. Do not remove.
# default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

mqtt:
  broker: 172.17.0.1
  port: 1883
  username: ***********
  password: ***********
  discovery: true

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# SenseHat
mqtt:
  sensor:
    - name: "SenseHAT Temperature"
      state_topic: "homeassistant/sensors/sensehat"
      value_template: "{{ value_json.temperature }}"
      unit_of_measurement: "°C"
      unique_id: sensehat_temperature

    - name: "SenseHAT Humidity"
      state_topic: "homeassistant/sensors/sensehat"
      value_template: "{{ value_json.humidity }}"
      unit_of_measurement: "%"
      unique_id: sensehat_humidity

    - name: "ShellyPlugS Presa"
      state_topic: "shellies/shellyplug-s083A8DC34A83/relay/0/power"
      unit_of_measurement: "Watt"
      unique_id: shellyplugs_pot

  switch:
    - name: "shellyplugs"
      state_topic: "shellies/shellyplug-s083A8DC34A83/relay/0"
      command_topic: "shellies/shellyplug-s083A8DC34A83/relay/0/command"
      availability_topic: "shellies/shellyplug-s083A8DC34A83/online"
      qos: 1
      value_template: "{% if value == 'on' %} on {% else %} off {% endif %}"
      payload_on: "on"
      payload_off: "off"
      payload_available: "true"
      payload_not_available: "false"
      optimistic: false
      retain: false
      unique_id: shellyplugs_lavatrice
```
Il problema che riscontro è che dall'interfaccia di Home Assistant vedo il sensore però non vedo il valore della potenza (ma la scritta "Sconosciuto"). 
Se mi metto in ascolto con il seguente comando : 
`mosquitto_sub -h 172.17.0.1 -p 1883 -t shellies/shellyplug-s083A8DC34A83/relay/0/power -u <username> -P <password>`
non vedo passare niente.

Ho provato anche ad aggiungere la seguente automazione al file delle automazioni ma il problema non si è risolto.
```
- alias: MQTT Announce
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: mqtt.publish
    data:
      payload: announce
      topic: shellies/command
```

In un altra discussione ho visto questo commento
![image](https://github.com/indomus/forum/assets/48562858/79e8496f-4fee-4ce8-b9a0-5c81dda8b46d)
Quindi la stringa del topic non è di default come immaginavo, però nella pagina di configurazione dello shelly non ho trovato una sezione dove impostare il topic, quindi non mi è molto chiaro.

Inoltre anche l'entità dello switch non funziona, ovvero viene visualizzata ma è disabilitata (non disponibile).

Grazie in anticipo.

**Comment by snakuzzo** [comment]
E' sbagliato i topic.
Hai scritto...

```
shellyplug-s-083A8DC34A83
```

...ma nello screenshot leggo...

```
shellyplug-s083A8DC34A83
```

**Reply by snakuzzo** [reply]
Controlla bene sulla coda...

```
mosquitto_sub -v -t +/# -h tuohost -u tuauser -P tuapassword | grep shellies
```

**Reply by VeronicaMichelini** [reply]
Ok provo. Vorrei capire però la questione del topic. Puoi chiarirmi questo punto ?
![image](https://github.com/indomus/forum/assets/48562858/8781faff-8acf-4047-9a94-6b2e2dceb915)

**Reply by VeronicaMichelini** [reply]
> E' sbagliato i topic. Hai scritto...
> 
> ```
> shellyplug-s-083A8DC34A83
> ```
> 
> ...ma nello screenshot leggo...
> 
> ```
> shellyplug-s083A8DC34A83
> ```

Ho corretto la domanda, avevo riportato il nome sbagliato perchè per fare delle prove lo avevo modificato. Non è quello il problema.

**Reply by snakuzzo** [reply]
Premesso che dovresti capire bene come funziona il protocollo MQTT prima di utilizzarlo...

> Ok provo. Vorrei capire però la questione del topic. Puoi chiarirmi questo punto ? ![image](https://user-images.githubusercontent.com/48562858/241233934-8781faff-8acf-4047-9a94-6b2e2dceb915.png)

Qui non c'è nulla da chiarire. Si parlava (immagino) del topic utilizzato per capire se era quello giusto o meno

> > E' sbagliato i topic. Hai scritto...
> > ```
> > shellyplug-s-083A8DC34A83
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...ma nello screenshot leggo...
> > ```
> > shellyplug-s083A8DC34A83
> > ```
> 
> Ho corretto la domanda, avevo riportato il nome sbagliato perchè per fare delle prove lo avevo modificato. Non è quello il problema.

Se è giusto...deve pubblicare qualcosa sulla coda del broker...se non pubblica, il problema è altrove.
Hai provato il comando che ti ho detto ?

```
mosquitto_sub -v -t +/# -h tuohost -u tuauser -P tuapassword | grep shellies
```

In alternativa puoi usare anche MQTT Explorer

**Reply by VeronicaMichelini** [reply]
Ho provato e confermo che non passa niente.
Dal web vedo il valore correttamente
![image](https://github.com/indomus/forum/assets/48562858/38ab494d-693f-4bb1-bca1-20760fe5fd10)

**Reply by snakuzzo** [reply]
Se non passa niente, vuol dire che non è connesso al broker mqtt

**Reply by VeronicaMichelini** [reply]
Per connetterlo al broker non è sufficiente questa configurazione?
![image](https://github.com/indomus/forum/assets/48562858/76fb2457-4b76-48b4-975a-4266a6cbaf9d)

**Reply by snakuzzo** [reply]
Sì, ma io come faccio a dirti se è la configurazione corretta?
Sicura che user e password siano ok?
Ripeto...se non vedi nulla sulla coda del broker, vuol dire che non è connesso o che comunque non riesce a connettersi. In tal caso, guarda i log del broker (attenzione...i log...non la coda mqtt)

**Comment by VeronicaMichelini** [comment]
Ho resettato lo shelly.
![image](https://github.com/indomus/forum/assets/48562858/3dafc3bd-ac8b-46cc-837f-b66dbb68d9f8)
(quando salvo e riavvio, se torno nella schermata vedo Use custom MQTT prefix disalibitato, è normale ??)
Questo è il file configuration.yaml
```
# Loads default set of integrations. Do not remove.
# default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

mqtt:
  broker: 172.17.0.2
  port: 1883
  username: "pi"
  password: "**************"
  discovery: true

  sensor:
    - name: "Shellyplugassorbimento"
      state_topic: "shellies/shellyplug-s083A8DC34A83/relay/0/power"
      unit_of_measurement: "Watt"
      unique_id: shellyplugslavanderia

    - name: "Sensehatemperatura"
      state_topic: "homeassistant/sensors/sensehat"
      value_template: "{{ value_json.temperature }}"
      unit_of_measurement: "°C"
      unique_id: sensehatemperatura

    - name: "SenseHAT Humidity"
      state_topic: "homeassistant/sensors/sensehat"
      value_template: "{{ value_json.humidity }}"
      unit_of_measurement: "%"
      unique_id: sensehat_humidity

  switch:
    - name: "Interruttore ShellyPlugS"
      state_topic: "shellies/shellyplug-s083A8DC34A83/relay/0"
      command_topic: "shellies/shellyplug-s083A8DC34A83/relay/0/command"
      availability_topic: "shellies/shellyplug-s083A8DC34A83/online"
      qos: 0
      value_template: "{% if value == 'on' %} on {% else %} off {% endif %}"
      payload_on: "on"
      payload_off: "off"
      payload_available: "true"
      payload_not_available: "false"
#      optimistic: false
      retain: false
      unique_id: switch_presa

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```
Questa è la configurazione dell'integrazione MQTT su Home Assistant
![image](https://github.com/indomus/forum/assets/48562858/33feb8e5-4d40-4d37-b90b-0d0ad20a591e)

Se da qui mi metto in ascolto su shellies/# non vedo niente
![image](https://github.com/indomus/forum/assets/48562858/724f4fb2-df46-4465-bb48-174354223146)

Stessa cosa con il comando mosquitto_sub
![image](https://github.com/indomus/forum/assets/48562858/be2dfc7b-d01c-47bd-8107-1bd6a2c8b102)

Come indirizzo IP del broker ho messo l'indirizzo IP del container mosquitto
![image](https://github.com/indomus/forum/assets/48562858/0f81ee76-44b2-4eec-b8ad-f9aa5d886ab6)

Questo è quello che vedo da home assistant
![image](https://github.com/indomus/forum/assets/48562858/a2d2d38a-5d84-4091-971d-accf5cc492c3)

Nei log di mosquitto non ci sono segnalazioni di errore, solo connessioni e disconnessioni.
```
"New connection from X.X.X.X:Y on port 1883": Indica una nuova connessione al server MQTT da parte di un client. X.X.X.X rappresenta l'indirizzo IP del client e Y è il numero di porta utilizzato per la connessione.

"New client connected from X.X.X.X:Y as ClientID (p2, c1, k60, u'pi')": Indica che un nuovo client si è connesso al server MQTT. X.X.X.X rappresenta l'indirizzo IP del client, Y è il numero di porta e ClientID è l'identificatore univoco assegnato al client. "(p2, c1, k60, u'pi')" potrebbe rappresentare alcune opzioni o autorizzazioni associate al client.

"Client ClientID disconnected": Indica che il client con l'identificatore ClientID si è disconnesso dal server MQTT.

"Saving in-memory database to /mosquitto/data//mosquitto.db": Indica che il database in memoria del server MQTT viene salvato su disco nel percorso specificato.
```

Quali altri controlli posso fare ?

**Reply by snakuzzo** [reply]
Domanda...ma la tua rete LAN ha classe 172.17.x.x ?
Chiedo perché quella è la classe solitamente utilizzata da Docker.
Solitamente, salvo personalizzazioni, per le LAN domestiche si ha 192.168.x.x

**Reply by VeronicaMichelini** [reply]
No, la mia rete LAN ha classe 192.168.x.x . Infatti, l'indirizzo IP di Raspberry è 192.168.1.12, mentre 172.17.0.2 è l'indirizzo IP del container Docker. Ti spiego meglio cosa ho fatto.

Prima ho installato Docker su Raspberry seguendo questa guida : https://indomus.it/guide/come-installare-docker-su-raspberry-pi-con-raspbian/ 

Poi ho configurato il broker MQTT su Docker seguendo questa guida : https://indomus.it/guide/come-installare-e-configurare-il-broker-mqtt-mosquitto-su-docker-su-raspbian/

Infine ho configurato il client seguendo questa guida  : https://indomus.it/guide/configurare-mqtt-broker-client-su-home-assistant/ (Su Home Assistant Core), dove ho messo l'indirizzo 172.17.0.2 come indirizzo del broker (dal comando docker inspect mosquitto | grep IPAddress) , e non quello di Raspberry (192.168.1.12)
![image](https://github.com/indomus/forum/assets/48562858/ee18c3dd-3724-4711-85e3-fb0991e23194)

Nello script che ho creato per leggere temperatura ed umidità da sensehat ho inserito 172.17.0.2 come IP del broker e funziona correttamente, quindi ho dato per scontato che fosse giusto inserire quello, e non l'indirizzo IP di Raspberry.
(anche dal comando mosquitto_sub -v -h 172.17.0.2 -u pi -P ***************** -t "#" vedo che pubblica i dati correttamente)
![image](https://github.com/indomus/forum/assets/48562858/883c95c4-de9c-4356-b383-08c149458058)

**Reply by snakuzzo** [reply]
Sì ma come ti aspetti che lo shelly si colleghi al broker se gli imposti l'IP 172.17.0.2. Lì devi impostare l'IP LAN del server 192.168.1.12.

**Reply by VeronicaMichelini** [reply]
Pensavo che dovessi impostargli proprio l'indirizzo IP del broker...sensehat funziona con quello...
Va bene, allora provo a mettere l'indirizzo IP che il router assegna a Raspberry (192.168.1.12).

**Reply by snakuzzo** [reply]
Perdonami, però da quello che stai scrivendo e a prescindere dal discorso del broker, dovresti un attimino chiarirti qualche concetto di rete legato a Docker...perché secondo me l'isolation di Docker non ti è chiara

**Reply by VeronicaMichelini** [reply]
No, infatti prima non conoscevo e non avevo mai usato Docker, ho letto tutto quello riportato nella guida ma si, qualcosa non mi è ancora molto chiaro.

**Reply by VeronicaMichelini** [reply]
Quindi anche nella sezione mqtt di configuration.yaml 
```
# Loads default set of integrations. Do not remove.
# default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

mqtt:
  broker: ?
  port: 1883
  username: ***********
  password: ***********
  discovery: true
```
e nell'integrazione client mqtt su home assistant devo mettere l'IP di Raspberry ?
