### DISCUSSION TITLE
Sensori ghost

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#2482] [HUB: Home Assistant]
Con questo codice in configuration.yaml dovrei creare dei sensori che mi leggono dei dati stringa in un file:
```
sensor:  
  - platform: file   
    name: "cyan"
    file_path: "/config/custom_data/stampante.json"
    value_template: "{{ value_json.cyan | int }}"
    unit_of_measurement: "%"
  
  - platform: file
    name: "magenta"
    file_path: "/config/custom_data/stampante.json"
    value_template: "{{ value_json.magenta | int }}"
    unit_of_measurement: "%"

  - platform: file   
    name: "yellow"
    file_path: "/config/custom_data/stampante.json"
    value_template: "{{ value_json.yellow | int }}"
    unit_of_measurement: "%"
```
Ma non cavo un ragno dal buco nel senso che i sensori non compaiono. L'indirizzo della path è corretto, la voce di valore json è presente e corretta nel file stampante.json . Vedete errori?

**Comment by Scialla** [comment]
Magari posta anche il contenuto del file `stampante.json` così, chi è in grado, ti da una mano

**Reply by Dregi56** [reply]
Pronti: 
```
{ "yellow":"10", "cyan":"10", "magenta":"20", "black_bk":"10", "black_pgbk":"50" }
```
 black_bk e black_pgbk non sono presenti nel codice postato per brevità.
 Anzi, per completezza:
```
- platform: file
    name: "blackbk"
    file_path: "/config/custom_data/stampante.json"
    value_template: "{{ int(value_json.black_bk) | int }}"
    unit_of_measurement: "%"
  
- platform: file   
  name: "blackpgbk"
  file_path: "/config/custom_data/stampante.json"
  value_template: "{{ value_json.black_pgbk | int }}"
  unit_of_measurement: "%"
```

**Reply by Scialla** [reply]
Ciao, io ho provato facendo un sensore rest e funziona:
```
  - platform: rest
    name: "Giallo"
    resource: http://localhost:8123/local/stampante.json
    value_template: "{{ value_json.yellow | int }}"
    scan_interval: 3600
 ```

hai messo il file `stampante.json` nella cartella `www`?
dici che la `path` è corretta, magari verifica

**Reply by Dregi56** [reply]
Scialla, con gli indirizzi in locale vado in tilt, non ti sembri OT se ti chiedo due cose: uso duckdns con una porta esterna ad es. 7000 e interna 8123 ma in locale ho sempre avuto problemi https://10.0.0.20:8123/lovelace/default_view mi da errore e non entra, oppure entro ma cliccando [Procedi su 10.0.0.20 (non sicuro)](chrome-error://chromewebdata/#). http://localhost:8123 mi da errore. Cosa dovrei aggiungere in configuration.yaml per ovviare al problema?

**Reply by Scialla** [reply]
questo però è un altro problema; tu hai abilitato i certificati per accedere da fuori e i certificati vengono rilasciati sul dominio e non possono essere rilasciati su IP interno. Quando accedi da dentro casa devi quindi fare come fai, dirgli di proseguire anche se non è sicuro (dice che non è sicuro perché su IP interno non hai i certificati), oppure accedere anche da casa col dominio, oppure di installi un reverse proxy tipo caddy e fai gestire a lui i certificati, così facendo in locale accedi in http e da fuori in https. Puoi guardarti la guida di caddy sul sito per capire meglio.

Per quanto riguarda i percorsi la directory `local` corrisponde alla cartella `www` che si trova dentro la cartella dove hai la config di homeassistant. usa questa cartella per i documenti/immagini che vuoi vedere in HA

https://www.home-assistant.io/integrations/http/#hosting-files

**Reply by Dregi56** [reply]
Ok. Definita la storia del sito non "sicuro". Avevo iniziato il discorso per paura che questo potesse influire sulla raggiungibilità del file stampante.json. Le sottodirectory di www, sono quindi egualmente visibili?

**Reply by Dregi56** [reply]
```
- platform: rest
    name: "Giallo"
    resource: http://localhost:8123/local/stampante.json
    value_template: "{{ value_json.yellow | int }}"
    scan_interval: 3600
```
Vado in Strumenti sviluppatori -->Stati digito Giallo nel campo entità e non lo trova.... 
Alla verifica del codice, no n dà alcun errore per il link...

**Reply by snakuzzo** [reply]
Da quel poco che ho letto di questo thread, hai HA configurato in https, non ti risponderà mai in http.
Prova a cambiare la url in https, m anon è detto che funzioni.
Inoltre devi mettere a `false` la verifica SSL

```yaml
- platform: rest
  name: "Giallo"
  resource: https://localhost:8123/local/stampante.json
  value_template: "{{ value_json.yellow | int }}"
  verify_ssl: false
  scan_interval: 3600
```

**Comment by Dregi56** [comment]
Giusto per concludere anche il discorso sulla raggiungibilità da browser:
```
homeassistant:
  packages: !include_dir_named packages
  external_url: "https://mionome.duckdns.org:7000"
  internal_url: "https://10.0.0.20:8123"
```
La quarta riga non serve quindi a nulla?
