### DISCUSSION TITLE
plancia energia non trova sensore

### DISCUSSION THREAD

**Discussion by XRedShark** [indomus/forum#2491] [HUB: Home Assistant]
Salve a tutti, non capisco cosa mi manca: la plancia energia non trova il sensore. Dove sbaglio? Grazie

```
- platform: template
  sensors:
    energy_luci_servizi:
      unique_id: energy_luci_servizi
      unit_of_measurement: "kWh"
      device_class: energy
      value_template: >
        {% set difference = states('sensor.totale_carichi_energy')|float() - states('sensor.prese_carichi_energy')|float() %}
        {{ max(0, difference) }}
```
