### DISCUSSION TITLE
Aggiornamento 2023.8.0

### DISCUSSION THREAD

**Discussion by bottai1969** [indomus/forum#2497] [HUB: Home Assistant]
Ciao a tutti,
scusate la domanda magari banale, ma me ne intendo poco.
Con l'ultimo aggiornamento di HA, mi esce questo avviso:

![HA](https://github.com/indomus/forum/assets/59028577/42f75846-0875-4c73-a229-9546316fe34e)

Cosa devo modificare?

Grazie 1000 a tutti!!

**Comment by snakuzzo** [comment]
È scritto nel changelog sul sito ufficiale e anche nel nostro articolo sul sito, quello relativo all'aggiornamento

**Comment by bottai1969** [comment]
Snakuzzo, mi devi scusare, sono un somaro, non ho capito cosa devo fare e la cartella in file editor che devo modificare, scusami.
E' per caso questa?
![HA](https://github.com/indomus/forum/assets/59028577/3c500eeb-a21f-4068-9f7e-a81615b08eba)

E come devo modificare?
Grazie 1000.

**Reply by snakuzzo** [reply]
Scusa eh, ma visto che vuoi che uno ti dia una mano, almeno sforzati a fare copia incolla del codice (usando il markdown). Così come hai fatto che t'aspetti, che uno si metta a riscrivere carattere per carattere le stesse cose che hai scritto?
Un po' di impegno, per favore :)

**Comment by bottai1969** [comment]
Scusami tanto, non son pratico, non è il non voler collaborare, per carità, se ho ben capito devo postare direttamente le righe e non il cattura schermo, ci provo:

```
 -  platform: rest
    name: "Assorbimento  Istantaneo"
    scan_interval: 2
    resource: http://192.168.0.43/emeter/0
    value_template: "{{ value_json['power'] }}"
    device_class: power    
    
 -  platform: command_line
    name: "CPU"
    command: 'cat /sys/class/thermal/thermal_zone0/temp'
    unit_of_measurement: '°C'
    value_template: '{{ value | multiply(0.001) | round(1)}}'

```

Spero di aver fatto correttamente, grazie 1000.

**Reply by snakuzzo** [reply]
Immagino che quello indicato sia un package (tra le altre cose non completo)...quindi...

```yaml
sensor:

 -  platform: rest
    name: "Assorbimento  Istantaneo"
    scan_interval: 2
    resource: http://192.168.0.43/emeter/0
    value_template: "{{ value_json['power'] }}"
    device_class: power    

command_line:

  - sensor:
  
      name: CPU
      command: 'cat /sys/class/thermal/thermal_zone0/temp'
      unit_of_measurement: '°C'
      value_template: '{{ value | multiply(0.001) | round(1)}}'

```
