### DISCUSSION TITLE
Regolazione luci automatica con sensore luminosità.

### DISCUSSION THREAD

**Discussion by AlexZappy** [indomus/forum#250] [HUB: Home Assistant]
Ciao a tutti, 
Vorrei creare una luce che si inneschi ad una certa ora e che parta da 0 arrivando al 100%.
A tal proposito ho letto la guida di indomus, [https://indomus.it/progetti/regolare-automaticamente-la-luminosita-negli-ambienti-tramite-home-assistant/](url).
Qualcono di voi ha avuto modo di provarla/usarla?

ho inserito la seguente automazione per prova:

```
automation:
  - alias: "Auto regolazione punto luce"
    trigger:
      - platform: state
        entity_id: sensor.luminosita, light.cucina
    condition:
      - condition: and
        conditions:
        - condition: state
          entity_id: group.famiglia
          state: 'home'
        - condition: or
          conditions:
          - condition: template
            value_template: "{{ (trigger.entity_id == 'light.cucina') and (trigger.from_state.state == 'off') }}"
          - condition: template
            value_template: "{{ (trigger.entity_id == 'sensor.luminosita') and (states.light.cucina.state == 'on') }}"
    action:
      service: light.turn_on
      data:
        entity_id: light.cucina
        brightness_pct: "{{ (((((states.sensor.luminosita.state * (100/300)) - 100)-((states.sensor.luminosita.state * (100/300)) - 100)|abs)/2)+100)|int }}"
```
il risultato è che al trigger ho il seguente errore:

`TypeError: can't multiply sequence by non-int of type 'float'`

Credo che dipenda dalla tipologia di dato della luminosità.

Sapreste aiutarmi o consigliarmi qualche metodo alternativo?
Grazie.
