### DISCUSSION TITLE
Integrazione ESPHome con Vaillant Sensocomfort e Split IdealClima

### DISCUSSION THREAD

**Discussion by ichigo86x** [indomus/forum#2513] [GENERALE - Discussioni generiche]
Ciao a tutti,
mi hanno installato un impianto ibrido con caldaia a condensazione e pompa di calore Vaillant, con cronotermostato sensocomfort e condizionatori idealclima ikaro.

Il cronotermostato SensoComfort 720f non è integrato in rete (c'è un gateway molto costoso da aggiungere), ma volevo capire se secondo voi è possibile o avete già fatto un integrazione, magari tramite esphome. 

Per quanto riguarda gli split che fanno da riscaldamento/raffrescamento, so che hanno Modbus con RS485, quindi ho ho provato ad integrare con Nodemcu e RS485, ma da profano forse sbaglio qualcosa, e non funziona nulla.

Qualcuno ha avuto modo di integrare questi componenti con ESPHome o altro su HA?
E' vero che esistono componenti ufficiali per entrambi, ma vorrei provare a fare da solo (visto anche il costo elevato che non rientrano nel 110%).
Potete darmi supporto?

Grazie

Queste sono le istruzioni dello split:
![IMG_6537](https://github.com/indomus/forum/assets/3751343/c826ca19-15ad-4493-844b-d705e964697f)

E questo il circuito di test realizzato:
![IMG_6538](https://github.com/indomus/forum/assets/3751343/4f2d07c7-62af-4653-89aa-468acbd4685b)

Per il clima, questo è il codice che ho integrato su ESPHOME:
```yaml
esphome:
  name: clima-camera
  friendly_name: Clima Camera

esp32:
  board: nodemcu-32s

  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MYENCKEY"

ota:
  password: "OTAPASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Clima-Camera Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:


#ABILITO PROXY BLUETOOTH
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true


#ABILITO UART
uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  stop_bits: 1
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

modbus:
  id: modbus1
  flow_control_pin: 5

modbus_controller:
  - id: epever
    ## the Modbus device addr
    address: 0x0F
    modbus_id: modbus1
    setup_priority: -10


sensor:
  #TEMPERATURA RILEVATA
  - platform: modbus_controller
    modbus_controller_id: epever
    id: temperature
    name: "Temperatura"
    address: 0xB6D1
    unit_of_measurement: "C"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    skip_updates: 60
    filters:
      - multiply: 0.1

  #VELOCITA VENTOLA
  - platform: modbus_controller
    modbus_controller_id: epever
    id: fan
    name: "Ventola"
    address: 0xB6D3
    unit_of_measurement: ""
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 0
    skip_updates: 60

number:

  #STATO ON OFF
  - platform: modbus_controller
    modbus_controller_id: epever
    id: set_on_off
    name: "Stato"
    address: 0x6E8D
    value_type: S_WORD
    min_value: 0
    max_value: 1
    use_write_multiple: True

  #VELOCITA VENTOLA (SET)
  - platform: modbus_controller
    modbus_controller_id: epever
    id: set_fan
    name: "Velocità Ventola"
    min_value: 1
    max_value: 6
    step: 1
    address: 0x6E8F
    value_type: S_WORD
    use_write_multiple: True

  #MODALITA
  - platform: modbus_controller
    modbus_controller_id: epever
    id: set_mode
    name: "Modalità"
    min_value: 1
    max_value: 4
    step: 1
    address: 0x6E8E
    value_type: S_WORD
    use_write_multiple: True

  #TEMPERATURA RISCALDAMENTO
  - platform: modbus_controller
    modbus_controller_id: epever
    id: set_temp_hot
    name: "Temperatura Riscaldamento"
    min_value: 15
    max_value: 31
    step: 0.5
    address: 0x6E97
    value_type: S_WORD
    multiply: 10
    use_write_multiple: True

  #TEMPERATURA RAFFRESCAMENTO
  - platform: modbus_controller
    modbus_controller_id: epever
    id: set_temp_cold
    name: "Temperatura Raffrescamento"
    min_value: 15
    max_value: 31
    step: 0.5
    address: 0x6E97
    value_type: S_WORD
    multiply: 10
    use_write_multiple: True
```
