### DISCUSSION TITLE
Automazione con condizioni multiple

### DISCUSSION THREAD

**Discussion by array81** [indomus/forum#2521] [HUB: Home Assistant]
Ho creato un'automazione per alimentare o meno una presa smart. In sostanza voglio fare quanto segue:

1. se sto cedendo alla rete (ho un impianto fotovoltaico) più di 500W e l'umidità nella stanza dove si trova la presa e superiore al 70% la presa deve essere alimentata in modo che un deumidifcare si accenda;
2. se sto assorbendo energia dalla rete la presa si deve spegnere;
3. se l'umidità nella stanza è inferiore al 65% la presa si deve spegnere;

Il problema della mia automazione è l'accensione. Se infatti creo per ognuna delle 2 condizioni di accensione un azione distinta l'automazione funziona ma ha me serve creare un'azione per l'accensione della presa che si attivi quando entrambe le condizioni sono vere. Oggi per diverso tempo entrambe le condizioni erano vere ma la presa non si è accesa.
Posto il mio codice:

```
alias: Accensione/spegnimento presa deumidificatore Taverna
description: >-
  Accende e spegni la presa dell'umidificatore in base ai watt scambiati al
  contatore
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.contatore_channel_2_power
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
    below: -500
    id: deumidificatore_on
  - platform: numeric_state
    entity_id:
      - sensor.contatore_channel_2_power
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
    above: 0
    id: deumidificatore_off
  - platform: numeric_state
    entity_id:
      - sensor.termostato_taverna_tado_humidity
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
    below: 66
    id: umidita_off
  - platform: numeric_state
    entity_id:
      - sensor.termostato_taverna_tado_humidity
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
    above: 69
    id: umidita_on
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: deumidificatore_off
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              device_id: 7955e9a9c9fe72d0114e24eddaa23d90
      - conditions:
          - condition: trigger
            id: umidita_off
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              device_id: 7955e9a9c9fe72d0114e24eddaa23d90
      - conditions:
          - condition: trigger
            id: umidita_on
          - condition: trigger
            id: deumidificatore_on
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              device_id: 7955e9a9c9fe72d0114e24eddaa23d90
mode: single
```

**Comment by 50494554524F** [comment]
due automazioni, una per l'accensione e una per lo spegnimento... dividi i compiti il più possibile e vedrai che si semplifica tutto

(poi creati dei blueprint così se volessi riutilizzarla in un'altra stanza con altri parametri è un attimo...)

**Comment by array81** [comment]
Non voglio creare 2 automazioni, ovvero una per l'accensione e uno per lo spegnimento). A parte che non ne vedrei l'utilità. E poi lo spegnimento funziona e l'accensione con coppia condizione che ha problemi. Se separo l'accensione dello spegnimento mi ritrovo una automazione che funziona e una no. Ovviamente è il mio codice che ha un problema per l'accensione. Vorrei capire dove sta lo sbaglio.

**Reply by 50494554524F** [reply]
l'utilità è di tipo logico per avere codice separato, più facile da debuggare, più pulito e ridotto al minimo, ed è ottimizzato perché non deve eseguire quella choose enorme... come ti pare

non ti si accende perché nella conditions hai messo due condizioni di tipo trigger e, ovviamente, funziona come una condizione and, ma di trigger ne può scattare solo uno... sarà sempre false... con due automazioni anche questa cosa sarebbe stata molto più semplice da scrivere

**Comment by array81** [comment]
Preferisco avere tutto in un'automazione. Tanto più che come hai detto tu il mio problema era legato alle conditions quindi anche separando il codice avrei avuto un'automazione che funzionava e una che non funzionava.
Ho quindi modificato il codice come segue. Non l'ho ancora testato (dato che le 2 condizioni non si sono verificate) ma penso che dovrebbe funzionare:

```
alias: Controllo presa deumidificatore Taverna
description: >-
  Accende e spegni la presa dell'umidificatore in base ai watt scambiati al
  contatore
trigger:
  - platform: numeric_state
    entity_id: sensor.contatore_channel_2_power
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
    below: -500.1
    id: deumidificatore_on
  - platform: numeric_state
    entity_id:
      - sensor.contatore_channel_2_power
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
    above: 0
    id: deumidificatore_off
  - platform: numeric_state
    entity_id:
      - sensor.termostato_taverna_tado_humidity
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
    below: 66
    id: umidita_off
  - platform: numeric_state
    entity_id: sensor.termostato_taverna_tado_humidity
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
    above: 69
    id: umidita_on
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: deumidificatore_off
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              device_id: 7955e9a9c9fe72d0114e24eddaa23d90
      - conditions:
          - condition: trigger
            id: umidita_off
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              device_id: 7955e9a9c9fe72d0114e24eddaa23d90
      - conditions:
          - condition: trigger
            id: umidita_on
          - condition: and
            conditions:
              - condition: numeric_state
                entity_id: sensor.contatore_channel_2_power
                below: -500
              - condition: numeric_state
                entity_id: sensor.termostato_taverna_tado_humidity
                above: 69
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              device_id: 7955e9a9c9fe72d0114e24eddaa23d90
      - conditions:
          - condition: trigger
            id: deumidificatore_on
          - condition: and
            conditions:
              - condition: numeric_state
                entity_id: sensor.contatore_channel_2_power
                below: -500
              - condition: numeric_state
                entity_id: sensor.termostato_taverna_tado_humidity
                above: 69
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              device_id: 7955e9a9c9fe72d0114e24eddaa23d90
mode: single

```

**Reply by 50494554524F** [reply]
ps: le automazioni scattano ai trigger, funzionano sempre... ora per esercizio rifai tutto separando come ti ho detto e vedrai che il codice diventa un decimo

**Reply by snakuzzo** [reply]
Se posso dire la mia, sono completamente in disaccordo con quello che dici.
Ha senso fare tutto con un'unica automazione. Non cambia assolutamente nulla a livello di quantità di righe di codice. Non ho letto nel dettaglio, ma fa bene a voler fare tutto con un'unica automazione, andrà solo rivista con calma e scritta con altrettanta calma.

Quando si scrive codice non conta solo da quante righe di codice è composto...e comunque, seppur fosse come dici, parliamo di una "caccoletta" in mezzo al mare che non ha assolutamente alcun impatto sulle prestazioni.

P.S. finitela di creare ad ogni risposta nuovi thread. Fate reply sotto l'ultima risposta (come ho fatto io in questo momento).

Grazie

**Reply by 50494554524F** [reply]
non ha impatto sulle prestazioni perché ha controllerà sempre i trigger e l'automazione in fondo è solo una funzione da chiamare

te riscrivile le due automazioni e vedrai quanto semplice, pulito e leggibile diventa... poi ti convertirai al nuovo modello di programmazione :D

**Reply by snakuzzo** [reply]
Io non ho bisogno di fare ciò. Le automazioni le scrivevo separate le prime volte che ho messo mano ad HA. Poi con i template, choose e il resto ho semplificato tantissimo gestendo più entità in contemporanea e creando una sola automazione per ambito

E questo è esattamente il contrario di quello che hai appena detto di fare

**Reply by snakuzzo** [reply]
Scansare le funzionalità messe a disposizione per fare cose migliori non è un buon approccio

**Reply by 50494554524F** [reply]
la on separata... io dico che si è semplificata e ripulita, più leggibile e facile da mantenere... migliore non vuol dire aggiungere codice che non serve, divide et impera è la regola

```
trigger:
  - platform: numeric_state
    entity_id: sensor.contatore_channel_2_power
    for:
      minutes: 1
    below: -500.1
  - platform: numeric_state
    entity_id: sensor.termostato_taverna_tado_humidity
    for:
      minutes: 1
    above: 69
action:
    - service: switch.turn_on
      target:
         device_id: 7955e9a9c9fe72d0114e24eddaa23d90
```


edit: ps: al posto di mode single userei queue o restart... con single potresti perderti cambiamenti successivi se l'automazione è ancora in corso... non capiterà ma è sempre per questioni di logica

**Reply by snakuzzo** [reply]
Guarda che non ho detto di aggiungere codice che non serve...rileggi cosa ho scritto.
Quello che hai detto non vale sempre.

Leggibilità e pulizia del codice non vuol dire non usare funzionalità più complesse o scrivere meno righe di codice, altrimenti dovremmo prendere e buttare nel ce**o tutto quanto.

**Reply by 50494554524F** [reply]
che c'entra cose complesse... qui abbiamo un'automazione che fa due cose diverse e stai aggiungendo un sacco di codice che non serve per discriminare cosa cosa fare... ecco perché separare... cmq fate come vi pare, il suggerimento l'ho dato

**Reply by 50494554524F** [reply]
pps: per completezza nei riguardi di array81... se proprio vuoi averne una sola (visto che il caso è semplice) potesti fare così
!.....scrivo solo pseudo codice per non riscrivere tutto.....! modifica poi te...
rimane pulita ma non suddivisa per compiti, in caso di modifiche ti devi sempre ricordare di ricontrollare tutto...

```
trigger:
  - platform: numeric_state
    entity_id: sensor.contatore_channel_2_power
    for:
      minutes: 1
    below: -500.1
    id: 'on'
  - platform: numeric_state
    entity_id: sensor.termostato_taverna_tado_humidity
    for:
      minutes: 1
    above: 69
    id: 'on'
    AGGIUNGERE TRIGGER OFF
action:
    - service: >-
         {%  if triggerid=='on' %}
         switch.turn_on
         {%else %}
         switch.turn_off
         {%endif %}
      target:
         device_id: 7955e9a9c9fe72d0114e24eddaa23d90
```
