### DISCUSSION TITLE
HA COMPANION - problema background e automazione apertura cancello

### DISCUSSION THREAD

**Discussion by braudoo** [indomus/forum#2530] [HUB: Home Assistant]
Salve a tutti , ho creato un automazione per l'apertura del cancello quando entro nell' area CANCELLO sulla mappa.
All'app di HA  sono stati tolti i limiti di background, risparmio energetico e concesso tutti i permessi per tracciabilità, ma nonostante questo per avviare l'automazione devo entrare nell' app di HA, oppure devo aspettare diverso tempo davanti al cancello finché nn aggiorna.
Non so se il problema risiede nel device oppure in qualche impostazione dell' app.
Non penso nenahce che aggiornare continuamente i sensori di HA COMPANION siano soluzione migliore.

Qualcuno ha avuto stesso problema?

Grazie

**Comment by Scialla** [comment]
Non dici neanche che telefono hai né che S.O., dovremmo avere la sfera di cristallo.
Posso solo dirti di aumentare il raggio della zona, così ha più tempo per attivarsi

**Reply by braudoo** [reply]
Sorry pensavo di averlo messo Redmi note 10s con Android 13

**Comment by aventrax** [comment]
Ciao, hai attivato l'high accuracy mode sull'app?

Per dirti, questo è il tracking con High Accuracy disabilitato...

![image](https://github.com/indomus/forum/assets/6949472/806becb0-edeb-4d2f-a742-8c861f0b4868)

Mentre questo è il tracking con l'opzione abilitata...

![image](https://github.com/indomus/forum/assets/6949472/573d2ad6-3395-4db2-824b-fb7630d08d62)


Va da sé che consuma molta batteria ma si ovvia facendo una "zona" quale "Vicino Casa" nella quale si attiva l'opzione in questione e poi la si disattiva appena aperto il cancello o comunque dopo un timeout.


```
alias: "[Personal] Open the driveway gate when entering Home zone"
description: ""
trigger:
  - platform: zone
    entity_id: person.administrator
    zone: zone.near_home
    event: enter
condition: []
action:
  - service: notify.mobile_app_redmi_note_11s
    data:
      message: command_high_accuracy_mode
      data:
        command: turn_on
    alias: Enable High Accuracy Mode
  - wait_for_trigger:
      - platform: zone
        entity_id: person.administrator
        zone: zone.home
        event: enter
        id: matteo_at_home
    timeout:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
    alias: Wait for Matteo enters Home zone (5m timeout)
  - if:
      - condition: template
        value_template: "{{ wait.trigger.id == 'matteo_at_home' }}"
    then:
      - service: button.press
        data: {}
        target:
          entity_id: button.driveway_gate
      - service: notify.matrix_notify
        data:
          message: Driveway gate opened
    alias: Open the Driveway Gate when enter Home
  - service: notify.mobile_app_redmi_note_11s
    data:
      message: command_high_accuracy_mode
      data:
        command: turn_off
    alias: Disable High Accuracy Mode
mode: single
```
