### DISCUSSION TITLE
Impianto di irrigazione a 2 valvole

### DISCUSSION THREAD

**Discussion by array81** [indomus/forum#2535] [HUB: Home Assistant]
Mi sto cimentando a realizzare un piccolo dispositivo per controllare l'irrigazione del mio giardino.
In sostanza il mio impianto è composto da 2 zone, una per il prato e l'altra per una siepe (quest'ultima al momento è una predisposizione). Inoltre a breve voglio montare un flussometro sulla tubazione relativa al prato.
Detto questo sto cercando di utilizzare il componente "sprinkler" in ESPHOME ma ho qualche problema. Non mi è chiarissimo  ma il componente "sprinkler" usa una sorta di gestione della coda per le valvole. Se attivo una valvola di fatto il sistema mi disattiva la seconda e viceversa. A me attualmente non mi interessa questo sistema delle code. Io vorrei poter in autonomia accendere o spegnere ciascuna delle due valvole in modo indipendente.
C'è questa possibilità? Possibile che uno debba passare per forza per le code a accendere le zone in sequenza?
Posto il mio codice:

```
button:  
  - platform: restart
    name: "Restart device"
    
  - platform: factory_reset
    name: Reset to factory settings   

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    icon: mdi:clock-outline
    update_interval: 60s

  - platform: pulse_meter #pulse_counter
    pin:
      number: D5
      mode: INPUT_PULLUP
    id: irrigation_zone_a_flow
    name: "Zone A Flow"
    state_class: measurement
    unit_of_measurement: "l/min"    
    accuracy_decimals: 1
    icon: "mdi:water-pump"
    filters:
      - lambda: return x/6.6/60; # F=6.6*Q con F in Hz e Q in l/min (precisione 3%) -> impulsi per litro 396   
    total:
      id: irrigation_zone_a_pulse_meter_total
      name: "Zone A Water Total"
      state_class: "total_increasing"
      device_class: water
      icon: mdi:water
      unit_of_measurement: "m³"
      accuracy_decimals: 3
      filters:
        - multiply: 0.001

text_sensor:
  - platform: version
    name: "ESPHome Version"

sprinkler:
  - id: lawn_sprinkler_ctrlr
    main_switch: "Irrigation"
    auto_advance_switch: "Irrigation Auto Advance"
    reverse_switch: "Irrigation Reverse"
    multiplier_number: "Irrigation Multiplier"
    repeat_number: "Irrigation Repeat"
    valve_overlap: 5s
    valves:
      - valve_switch: "Active Lawn (zone A)"
        enable_switch: "Enable circle for Valve Lawn"
        valve_switch_id: zone_a
        run_duration_number:
          id: irrigation_zone_a_duration
          name: "Zone A Watering Duration"
          initial_value: 10
          max_value: 20
          unit_of_measurement: min
      - valve_switch: "Active Hedge (zone B)"
        enable_switch: "Enable circle for Valve Hedge"
        valve_switch_id: zone_b
        run_duration_number:
          id: irrigation_zone_b_duration
          name: "Zone B Watering Duration"
          initial_value: 10
          max_value: 20
          unit_of_measurement: min

switch:
  - platform: gpio
    id: zone_a
    pin:
      number: D1
      inverted: True
  - platform: gpio
    id: zone_b
    pin:
      number: D2
      inverted: True
```
