### DISCUSSION TITLE
Chiarimenti su Garbage_Collection

### DISCUSSION THREAD

**Discussion by Newreader** [indomus/forum#254] [HUB: Home Assistant]
Salve vorrei chiarirmi un dubbio in merito al custom component: garbage_collection.
Se creo, come da guida, in configuration.yaml la voce garbage_collection:  e poi di seguito i vari sensori; questi ultimi vengono regolarmente creati e non c’è alcun tipo di problema.
Il problema nasce quando cerco di spostare il tutto sotto sensors.yaml, dove peraltro definisco tutti i sensori che utilizzo in HA. Per fare questo inserisco (lo riporto in forma semplificata):

```
  - platform: garbage_collection
    name: "Carta"
    frequency: "weekly"
    verbose_state: true
    collection_days:
    - fri
```
Questa procedura purtroppo mi restituisce il seguente errore:
![image](https://user-images.githubusercontent.com/49215325/116869001-23805800-ac10-11eb-91bb-179f99771ccf.png)

Vi sarei grato se qualcuno mi aiutasse a capire dove sbaglio.
Grazie

**Comment by Dregi56** [comment]
Io ho fatto così:
```
# Sensori per raccolta rifiuti differenziata
 sensors:
  - name: "Secco indifferenziato"
    frequency: "weekly"
    verbose_state: true
    icon_normal: mdi:trash-can
    icon_tomorrow: mdi:delete-circle
    icon_today: mdi:delete-restore
    collection_days:
    - wed
    move_country_holidays: IT
```
ecc.
in un file che ho chiamato differenziata.yaml e in configuration.yaml:  garbage_collection: !include differenziata.yaml
