### DISCUSSION TITLE
Disabilitare Autenticazione a 2 fattori in locale

### DISCUSSION THREAD

**Discussion by federoco** [indomus/forum#2545] [HUB: Home Assistant]
Ciao a tutti, cerco aiuto con l'autenticazione a 2 fattori di HA.
Ho attivato la funzione da Profilo --> "Moduli di autenticazione a più fattori" e uso Authy come App sul telefono. 
Vorrei disattivarla quando mi collego su rete locale ed ho [googlato](https://www.home-assistant.io/docs/authentication/providers/#available-auth-providers) trovando il seguente codice da aggiungere nel configuration.yaml che, però, non interessa la 2FA ma solo la richiesta di password.

```
homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.1/24
```

A me, invece, sta bene di continuare a mettere utente e password anche da locale.
Vorrei solo disabilitare il secondo controllo con Authy.
E, ovviamente, mantenere la 2FA quando mi collego da remoto.
C'è modo di farlo?

Qualora, poi, volessi disabilitare la password tramite il suddetto codice, basta aggiungerlo alla fine del configuration.yaml oppure c'è una posizione specifica?

E perchè nella [guida ufficiale](https://www.home-assistant.io/docs/authentication/multi-factor-auth/) per il Multi-factor authentication viene indicato di modificare il file yaml? Io ho abilitato Authy direttamente da interfaccia.
