### DISCUSSION TITLE
Dati HA verso più bucket di influxdb

### DISCUSSION THREAD

**Discussion by Americo65** [indomus/forum#2556] [HUB: Home Assistant]
Salve, ho installato HA core su docker su mini pc 64bit .
Sto inviando 3 sensori di HA ad InfluxDB (anche lui su docker) e tutto funziona.
questo è lo script in configuration.yaml di HA:
```
influxdb:
  host: 192.168.0.11
  port: 8086
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==
  organization: xxxxxxxxxxxx
  bucket: Casa_HA
  api_version: 2
  ssl: false
  max_retries: 3
  include:
    entities:
      - sensor.w_ist_pannelli_casa
      - sensor.w_ist_consumi_casa
      - sensor.wh_prodotti_ultimo_giorno
```
il problema è che i tre sensori confluiscono in un unico bucket ed invece io vorrei conservare i dati dei primi due sensori per una settimana ed il terzo sensore per sempre.
Quindi avrei due domande:

 1 - C'è un modo per inviare sensori da HA in più buckets di influxdb?
 2 - C'è un modo in influxdb per creare dalle entity_id di un bucket più buckets distinti?

Grazie per le risposte
