### DISCUSSION TITLE
Termostato - non crea entità

### DISCUSSION THREAD

**Discussion by Matty1184** [indomus/forum#2558] [GENERALE - Discussioni generiche]
Ciao a tutti, temo mi stia perdendo in un bicchiere d'acqua!
ho creato un entità climate come segue:
```
climate:
  - platform: generic_thermostat
    name: Termostato_Clima_Camera
    heater: input_boolean.temp_camera_on_off
    target_sensor: sensor.temp_qualita_camera_temperature_filtrata
    min_temp: 17
    max_temp: 30
    target_temp: 19
    cold_tolerance: 0.5
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 120
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1
```
dove:
 heater: input_boolean.temp_camera_on_off  ---è un sensore binario in quanto dovrò collegare un automazione che alla variazione di stato mi lanci il comando IR allo split.

mi aspettavo di trovare un entità climate e creare una card termostato ma non si crea.
dove mi sto perdendo?
