### DISCUSSION TITLE
Shelly MQTT che vanno "non disponibili"

### DISCUSSION THREAD

**Discussion by riccionese** [indomus/forum#2565] [HUB: Home Assistant]
ciao a tutti, 
Ho diversi Shelly tra cui degli 1 (svariati usi) e degli 2.5 che uso per le tende motorizzate.
Sono configurati da circa il 2020  ed hanno sempre funzionato bene.
Solo che da qualche tempo, a configurazione invariata ma solo spostata dopo che hanno ricevuto una sezione autonoma e non più una "platform",  continuano a funzionare bene ma casualmente HA li vede "non disponibile" e tornano on line solo:
- quando gli pare
- se mi collego ai device con il browser puntato sul loro IP e li riavvio 

se mi metto in ascolto sui topic di questi device vedo passare ma sembra che HA non li senta:
![image](https://github.com/indomus/forum/assets/62329292/f311c4e1-45bb-459c-8f1b-b3632c4a4150)

questa configurazione di uno di questi:, che mi pare coerente anche con la guida sul sito 
```yaml
mqtt:
  switch:
  - unique_id: switch_luce_garage
    name: "Sh-luce-garage"
    state_topic: "shellies/sh-luce-garage/relay/0"
    command_topic: "shellies/sh-luce-garage/relay/0/command"
    availability_topic: "shellies/sh-luce-garage/online"
    qos: 1
    value_template: "{% if value == 'on' %} on {% else %} off {% endif %}"
    payload_on: "on"
    payload_off: "off"
    payload_available: "true"
    payload_not_available: "false"
    optimistic: false
    retain: false
```

ho anche l'automazione

```yaml
- alias: MQTT Announce
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: tasmota/tasmotas/cmnd/power
  - service: mqtt.publish
    data:
      payload: announce
      topic: shellies/command
```

nella configurazione di altri miei dispositivi Sonoff (e compatibili) flashati con il FW Tasmota, nel _availability_topic_ ho il riferimento a LWT che non ho sugli Shelly.

```
availability_topic: "tasmota/sala-1/tele/LWT"
```
infatti se "ascolto" i tasmota vedo passare anche i topic LWT mentre per gli Shelly ovviamente (?) no.

Diego, in Telegram, ha già iniziato a cazziarmi come al solito :-D ma accetto sia suggerimenti, sia link a documentazione, sia altri cazziatoni !

**Comment by snakuzzo** [comment]
Non ti è chiaro ancora il discorso dell'availability topic. Non è detto che debba esserci scritto "LWT" nel topic. Il topic può chiamarsi pure "paperino", l'importante è che quello che hai impostato sul device faccia scopa con quello impostato sulla configurazione dell'entità su HA.
Le configurazioni che hai impostato su HA immagino siano corrette, altrimenti non vedresti mai online il device.
Quanto allo screenshot che hai postato:

1. Analizzare la problematica da lì è praticamente impossibile...è una perdita di tempo
2. Ti consiglio di usare un tool come MQTT Explorer oppure, ancora meglio se lo fai da riga di comando in aggiunta di una grep per vedere cosa accade in real-time ([QUI](https://indomus.it/formazione/mosquitto-mqtt-broker-comandi-utili/) maggiori info)
3. Quelli dello screenshot sono i topic pubblicati con lo stato di input e relay, probabilmente passano quando ancora il topic LWT di shelly (`shellies/sh-luce-garage/online`) è offline

P.S. Cosa non strettamente legata al tuo problema, aggiorna l'automazione aggiungendo anche l'update per gli shelly (in poche parole, con l'announce recuperi l'info legata al LWT, e quindi sai se il device è online o offline, mentre con l'update recuperi tutti gli stati):

```yaml
- alias: MQTT Announce
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: mqtt.publish
    data:
      topic: tasmota/tasmotas/cmnd/power
  - service: mqtt.publish
    data:
      payload: announce
      topic: shellies/command
  - service: mqtt.publish
    data:
      payload: update
      topic: shellies/command
```

NOTA: Nella tua automazione, per i tasmot, per come l'hai impostata, allo start recuperi sì lo stato online/offline dei device, ma poi recuperi solo lo stato degli switch (ovvero tutto quello che viene pubblicato con il topic POWER). Tutto il resto (eventuali sensori o altre tipologie di entità) ti arriva solo alla prima pubblicazione da parte del device (che di base, se non erro, ha un intervallo di 30s)

**Reply by riccionese** [reply]
ti ringrazio.
e giusto per ...
1) certo che dallo screenshot non si diagnostica nulla. L'ho messo solo per confermare che il broker funzia e HA lo legge/pubblica regolarmente
2) sì. anche io uso MQTT Explorer e per sicurezza anche la line di comando :-)  in questo caso lo SS  ... vedi punto 1) 

3) ecco. questo è il punto che sicuramente non ho ancora capito/imparato.
Mettendomi in ascolto sul  topic ```shellies/sh-luce-garage/``` vedo passare MOLTI ```relay``` e ```input``` prima di avere, dopo molti minuti, un ```online``` che, come ipotizzavi tu è ```false```.
pubblicando con MQTT Explorer un ```shellies/sh-luce-garage/online true``` poi infatti i dispositivi diventano disponibili, con tutti i valori corretti (per la motorizzazione della tenda, ad esempio, la posizione e lo stato fermo/movimento)

e qui arrivo alla cosa che non ho capito: ho provato a riavviare HA e il ```shellies/sh-luce-garage/online``` torna ```false```.
Ripubblico il ```true``` e tutto si riattiva.

chi/come viene settato questo stato ?
come dovrei fare per averli ```true``` per default ?
lo devo pubblicare io nella automazione di avvio di HA ?
ho provato a cercare ma o non ho capito o non ho trovato ... sono di coccio :'-(  

p.s.: ho aggiunto l'update che suggerisci alle automazioni

**Reply by riccionese** [reply]
e comunque non riesco a capire perhé per ormai quasi 3 anni non ho mai avuto questo problema e adesso, senza modificare nulla né sul device né nella configurazione ... 
l'unica cosa che è cambiata è HA che prima prima MQTT era una "platform: mqtt"  e adesso è una sezione autonoma e quindi ho "spostato"
boh !

**Reply by snakuzzo** [reply]
Continui a non afferrare il concetto.

Per capire cosa accade, scordati la GUI di HA ed usa `mosquito_sub` da CLI

Quanto al LWT, quello stato non lo imposti tu (e mi pare giustissimo), lo imposta il device/broker:

Quando il device si collega al broker, il device pubblica lo stato online
Quando il device si scollega dal broker, se entro tot secondi non si ricollega, è giustamente il broker (che sa cosa pubblicare perché gliel'ha detto il client, ovvero il device, nel momento in cui si è collegato) a mandare l'offline.

Più chiaro di così non so spiegartelo

Leggi [QUI](https://indomus.it/formazione/mqtt-cose-e-come-funziona-il-last-will-and-testament-lwt/) per capire cos'è il LWT.

Poi...prova a vedere se hai qualcosa degli shelly in retain sul broker (con MQTT Explorer lo vedi subito) ed eventualmente cancella

**Reply by riccionese** [reply]
credo tu abbia ragione. Non afferro.
scusa. 
riproverò a rivedere la configurazione e a cercare documentazioni
grazie.

**Reply by snakuzzo** [reply]
Perché ti scusi ? Guarda che non l'ho detto per offendere eh ;) Semplicemente ti sfugge il funzionamento e quindi è inutile se prima non ti è chiaro.

Ripeto...comincia a cancellare la roba in retain, perché per gli shelly (che sono alimentati NON a batteria), non serve.
Fatto ciò, prova a riavviare Core e vedi se ricapita.
Però devi chiarirti bene come funziona il LWT e a che cosa serve...io te l'ho spiegato, più semplice di così non saprei come esporlo. Poi...se proprio non riesci a capire, possiamo metterci d'accordo e provo a collegarmi da remoto e darti una mano a capire

**Comment by riccionese** [comment]
ri-ciao
ho ricontrollato: 
- di retain non ce ne sono
![image](https://github.com/indomus/forum/assets/62329292/ca472b76-cfd4-4255-a3fc-09a0487477d1)

- la configurazione del LWT mi sembra corretta
```yaml    
    ....
    availability_topic: "shellies/sh-luce-garage/online"
    ...
    payload_available: "true"
    payload_not_available: "false"
    ...
```
e comunque è strutturalmente uguale a quella di tutti gli altri miei shelly che funzionano correttamente. tra Shelly1, Shelly 2.5 e Plug ne ho 12 ma solo 2 (sh-luce-portone e sh-luce-garage) mi danno questo problema

i parametri di riconnessione e keep alive  dei dispositivi sono tutti 12 uguali 
![image](https://github.com/indomus/forum/assets/62329292/d5a8b9c3-07b9-4bd7-802d-9f387d9c32e6)

ho riletto la pagina con la spiegazione del LWT e ... credo mi torni tutto.

"forzando" in modo fraudolento lo stato di ```online``` da MQTT pubblicando _io_ il topic ```shellies/sh-luce-garage/online``` a ```true```, vedo che lo switch sulla plancia si riattiva, giustamente, e a volte funziona anche (la luce si accende e spegne, segno che era "solo" un problema di stati) ma altre volte la luce "non risponde" allo switch in plancia.
Escluderei un problema del broker (tutti i messaggi li vedo passare) 

se punto il browser sul device e gli forzo il reboot, torna tutto a posto
![image](https://github.com/indomus/forum/assets/62329292/defd3eab-658d-4796-92f7-c8f86bca5f10)

quindi ... sono al palo.
sto pensando di provare a sostituire i due device (ne ho di scorta) per vedere se fosse un prob del device.
else ... tasmotizzo anche gli shelly
