### DISCUSSION TITLE
aiuto configurazione caddy, non scarica i certificati

### DISCUSSION THREAD

**Discussion by bortog** [indomus/forum#2570] [GENERALE - Discussioni generiche]
Ciao a tutti, ho dei problemi a configurare Caddy.
Ho installato su mini pc hassio con supervisor seguendo le guide. Sono arrivato al punto di configurare Caddy ma mi blocco al punto dei certificati "test".
Il log scrive questo:

```
INFO: Prepare Caddy...
INFO: Use built-in Caddy
v2.7.2 h1:QqThyoyUFAv1B7A2NMeaWlz7xmgKqU49PXBX08A+6xg=
INFO: Prepare Caddyfile...
INFO: Caddyfile found at /config/caddy/Caddyfile
INFO: Run Caddy...
{"level":"info","ts":1691225010.3923106,"msg":"using provided configuration","config_file":"/config/caddy/Caddyfile","config_adapter":""}
{"level":"warn","ts":1691225010.3944912,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/config/caddy/Caddyfile","line":3}
{"level":"info","ts":1691225010.3965967,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"info","ts":1691225010.397458,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
{"level":"info","ts":1691225010.3976903,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1691225010.3982124,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000379980"}
{"level":"info","ts":1691225010.3987265,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"}
{"level":"info","ts":1691225010.3990347,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/ssl/caddy"}
{"level":"info","ts":1691225010.4002242,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1691225010.4005053,"logger":"http.log","msg":"server running","name":"remaining_auto_https_redirects","protocols":["h1","h2","h3"]}
{"level":"info","ts":1691225010.4007318,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["bortoghome.duckdns.org"]}
{"level":"info","ts":1691225010.4024868,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1691225010.4037106,"msg":"autosaved config (load with --resume flag)","file":"/data/caddy/autosave.json"}
{"level":"info","ts":1691225010.4037235,"msg":"serving initial configuration"}
{"level":"info","ts":1691225010.4043727,"logger":"watcher","msg":"watching config file for changes","config_file":"/config/caddy/Caddyfile"}
```

Caddyfile copiato e incollato dalla guida con personalizzazione del duckdns.

Nella configurazione di Caddy quando copio e incollo, al salvataggio mi riordina le righe ma mi sembra che il contenuto sia corretto:

```
non_caddyfile_config:
  email: your@email.com
  domain: mydomain.com
  destination: localhost
  port: 8123
args:
  - "--watch"
env_vars: []
log_level: info
config_path: /config/caddy/Caddyfile
```

Nel router ho aperto la 443, la 80 e quella che ho assegnato a HA.

Dove sbaglio?
Manca qualcosa da mettere le configuration.yaml?

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

hacs:
  token:  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  
# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages: !include_dir_named packages
```
