### DISCUSSION TITLE
Gestione tapparelle con percentuale apertura

### DISCUSSION THREAD

**Discussion by Jason-Voorhees** [indomus/forum#2582] [HUB: Home Assistant]
Ciao a tutti,

sono alle prime armi con Home Hassistant e sto cercando di integrare la gestione delle tapparelle tramite HA che sono collegate al Raspberry di test come dal seguente diagramma:

[![iot-tapp-pics.png](https://i.postimg.cc/nLpZMB4L/iot-tapp-pics.png)](https://postimg.cc/yDQ2bJrq)

I contatti secondari dei relay (RT-SU/RT-GIU) avrebbero lo scopo di monitorare lo stato (S1/S2) della tapparella anche quando azionata manalmente dal pulsante a muro.
Al Raspberry sono collegati due relay (REL-1/REL-2) che vengono utilizzati come switch per sollecitare i relay collegti al motore della tapparella, inoltre l'intenzione è di usare solo componenti filari, quindi nessun modulo wifi o cose simili.

Sto però riscontrando alcune problematiche sulle quali vi chiedo aiuto:

* Il relay del Raspberry una volta attivato continua ad eccitare il relay della tapparella quindi devo attivarlo e disattivarlo con il toggle di HA, l'unico modo indiretto che ho trovato per farlo agire come impulso è stato quello di creare uno script che lo accende e segne dopo circa 1 sec. ma immagino che ci sia un modo più elegante per ottenere lo stesso risultato, per cui se avete seggerimento sono ben accetti.

* L'altra problematica è che vorrei poter impostare anche la percentuale di apertura della tapparella che si aggiorni anche quando l'apertura/ciusura viene cambiata manualmente dal pulsante a muro, anche in questo caso pensavo di utilizzare i contatti secondari dei relay per gestire i movimenti ma faccio fatica a inquadrare la cosa, mi potete dare un aiuto?

Tra l'altro nella card "Tapparella sala", vedo solo la freccia verso l'alto e il pulsante stop, mentre la freccia verso il basso è grigia.

Di seguito posto anche il codice che ho utilizzato:

```
#config.yaml

cover:
  - platform: template
    covers:
      tappa_std:
        device_class: shutter
        friendly_name: "Tapparella sala"
        value_template: closed
        open_cover:
          service: script.relay_pulse
        close_cover:
          service: script.relay_pulse
        stop_cover:
          service: script.relay_pulse


switch:
  - platform: rpi_gpio
    switches:
      - port: 23
        name: "Switch Tapparella Su"
        unique_id: "tapparella_up"
        invert_logic: true
      - port: 24
        name: "Switch Tapparella Giu"
        unique_id: "tapparella_dwn"
        invert_logic: true
```

```
# script

alias: relay_pulse
sequence:
  - service: switch.turn_on
    entity_id: switch.switch_tapparella_su
  - delay:
      milliseconds: 800
  - service: switch.turn_off
    entity_id: switch.switch_tapparella_su
mode: single
```

Grazie
