### DISCUSSION TITLE
Funzionamento helper per visualizzazione stato binario dispositivo

### DISCUSSION THREAD

**Discussion by tachipirina** [indomus/forum#2585] [HUB: Home Assistant]
Buongiorno a tutti,
vorrei  chiedere aiuto sul perché l'helper inserito all'interno dell'automazione non funzioni cambiando il suo stato. L'helper è di tipo boolenao quindi dovrebbe avere solo lo stato acceso o spento.
Inserisco qui il codice dell'automazione:

```
 alias: Attivazione ventola
description: ""
trigger:
  - platform: time_pattern
    hours: /2
condition:
  - condition: time
    after: "07:00:00"
    before: "22:00:00"
action:
  - service: shell_command.ventola_on
    data: {}
  - service: timer.start
    data: {}
    target:
      entity_id: timer.ventola_attiva
  - condition: state
    entity_id: input_boolean.attivazione_entola
    state: "on"
  - condition: numeric_state
    entity_id: binary_sensor.jaea
    value_template: "1"
    above: 1
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: shell_command.ventola_off
    data: {}
  - service: timer.cancel
    data: {}
    target:
      entity_id: timer.ventola_attiva
  - condition: state
    entity_id: input_boolean.attivazione_entola
    state: "off"
mode: single
```

Grazie a chi mi aiuterà.
