### DISCUSSION TITLE
Problemi Termostato

### DISCUSSION THREAD

**Discussion by Matty1184** [indomus/forum#2594] [GENERALE - Discussioni generiche]
Ciao a tutti, sto riscontrando questo problema in modo sporadico, vi spiego la mia configurazione.
uno switch input_boolean. clima_camera_on_off attiva il termostato generico in modalità HVAC, come heater ho impostato un input_boolean.temp_camera_on_off che a sua volta a ogni variazione di stato lancia un send remote control tramite bloadlink e accende/spegne lo split del clima emulando il telecomando IR.
premetto che non so se il metodo utilizzato è corretto ma al momento è l'unico che trovavo utilizzabile considerato che non ho i codici del telecomando per poter creare un termostato vero e proprio.
a metà notte, non sempre, nonostante il comando si on, il clima non si spegne più. al mattino, a clima acceso, disabilito lo swicht ma non succede nulla. 
ho cercato nella traccia dell'automazione, ma purtroppo non rileva nulla. consigli da dove iniziare a controllare?

**Comment by 50494554524F** [comment]
posta il codice...

**Reply by Matty1184** [reply]
Termostato:
```
climate:
  - platform: generic_thermostat
    name: Termostato_Clima_Camera
    heater: input_boolean.temp_camera_on_off
    target_sensor: sensor.temperatura_camera_filtrata
    min_temp: 17
    max_temp: 30
    target_temp: 24.5
    ac_mode: true
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    min_cycle_duration:
      seconds: 120
    initial_hvac_mode: "off"
    precision: 0.1
```

switch per abilitare il termostato:
automazione
```
alias: Controllo Cima Camera
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.clima_camera_on_off
condition: []
action:
  - if:
      - condition: state
        entity_id: input_boolean.clima_camera_on_off
        state: "on"
    then:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: cool
        target:
          entity_id: climate.termostato_clima_camera
    else:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: "off"
        target:
          entity_id: climate.termostato_clima_camera
mode: single
```
invio comando tramite broadlink allo split:
automazione:
```
alias: Accensione Speglimento Clima Camera da Termostato
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.temp_camera_on_off
condition: []
action:
  - if:
      - condition: state
        entity_id: input_boolean.temp_camera_on_off
        state: "on"
    then:
      - service: remote.send_command
        data:
          num_repeats: 1
          delay_secs: 0.4
          hold_secs: 0
          device: Condizionatore_Camera
          command: on-off 22C auto quite
        target:
          device_id: 15205653be30e6f819aef3ac6cf28d16
    else:
      - service: remote.send_command
        data:
          num_repeats: 1
          delay_secs: 0.4
          hold_secs: 0
          device: Condizionatore_Camera
          command: on-off 22C auto quite
        target:
          device_id: 15205653be30e6f819aef3ac6cf28d16
mode: single
```
NB: il  command: on-off 22C auto quite è uguale sia in caso di accensione che spegnimento, in quanto aimè il telecomando funzione in questo modo..

**Reply by 50494554524F** [reply]
il codice non è bello da vedere :D ma sembrerebbe fare tutto quello che serve... c'è modo di verificare che il comando vada effettivamente a buon fine?! 

mode single cambialo in mode queued sempre per evitare che rimanga qualcosa di non concluso...

**Reply by Matty1184** [reply]
il tutto funziona regolarmente, ad eccezione di alcune colte che non invia il comando allo split.
provo a cambiare il mode come da te suggerito.

**Reply by 50494554524F** [reply]
una bella ripulita, non c'è bisogno di automazioni, da mettere in un package, cambiare i nomi...

il termostato lo accendi/spegni aggiungendo la card termostato... il termostato gestisce lo switch che, a sua volta, invierà il comando al climatizzatore

ora devi solo capire se c'è modo di sapere se il comando va a buon fine o no e/o se c'è qualche parametro da cambiare

(così è molto semplice e pulito, visto che non c'è modo di sapere lo stato del climatizzatore se qualcosa cambiasse fuori da HA)

```
test:



  climate:

    - platform: generic_thermostat

      name: 'Room Name - Thermostat'

      unique_id: 'room_name_thermostat'

      heater: switch.room_name_cooler

      target_sensor: sensor.room_name_thermometer_temperature
 
      ac_mode: true

      min_temp: 17

      max_temp: 30

      target_temp: 24.5

      cold_tolerance: 0.3

      hot_tolerance: 0.3

      min_cycle_duration:

        seconds: 120

      initial_hvac_mode: "off"



  switch:



    - platform: template

      switches:



        room_name_cooler:

          friendly_name: 'Room Name - Cooler'

          unique_id: 'room_name_cooler'

          icon_template: 'mdi:snowflake'

          turn_on:
          
            - condition: state
            
              entity_id: switch.room_name_cooler
              
              state: 'off'

            - service: remote.send_command

              data:

                num_repeats: 1

                delay_secs: 0.4

                hold_secs: 0

                device: 'Condizionatore_Camera'

                command: 'on-off 22C auto quite'

              target:

                device_id: 15205653be30e6f819aef3ac6cf28d16

          turn_off:
          
            - condition: state
            
              entity_id: switch.room_name_cooler
              
              state: 'on'

            - service: remote.send_command

              data:

                num_repeats: 1

                delay_secs: 0.4

                hold_secs: 0

                device: 'Condizionatore_Camera'

                command: 'on-off 22C auto quite'

              target:

                device_id: 15205653be30e6f819aef3ac6cf28d16

```
