### DISCUSSION TITLE
Aiuto per creazione automazione

### DISCUSSION THREAD

**Discussion by 01leoter** [indomus/forum#2596] [HUB: Home Assistant]
Sto cercando di creare un automazione che mi accenda e spenda delle luci in base a degli eventi google calendar.
In poche parole mi deve accendere la luce 5 minuti prima dell'inizio di un determinato evento e spegnerla dopo 15 minuti la fine. Però così facendo, nel caso ci dovessero essere due eventi consecutivi, accade che l'orario di spegnimento del primo evento è dopo l'orario di accensione per il secondo evento. Risultato: la luce si accende e spegne regolarmente per il primo evento ma per il secondo no.
La cosa che mi era venuta in mente era controllare se nei 15 minuti successivi alla fine del primo evento ci fossero altri eventi e in caso non spegnere la luce, ma attendere la fine del secondo evento, ma non so come fare.

Intanto vi allego il codice che sto utilizzando finora che però non fa quello che dovrebbe fare.
```
alias: Fari cemento prenotazione
description: >-
  Accende i fari del cemento 5 minuti prima della prenotazione e li spegne 15
  minuti dopo la fine prenotazione.
trigger:
  - platform: calendar
    event: start
    offset: "-0:5:0"
    entity_id: calendar.campo_cemento
condition:
  - condition: template
    value_template: "{{ 'Campo cemento illuminato' in trigger.calendar_event.summary }}"
action:
  - type: turn_on
    device_id: b2baaaf31ea5057ab6181d9eb236b8e7
    entity_id: 9bb2b49f6e07506bdcda96a7794cd46f
    domain: switch
  - wait_for_trigger:
      - platform: calendar
        event: end
        offset: "0:15:0"
        entity_id: calendar.campo_cemento
  - type: turn_off
    device_id: b2baaaf31ea5057ab6181d9eb236b8e7
    entity_id: 9bb2b49f6e07506bdcda96a7794cd46f
    domain: switch
mode: restart
```
Chiedo aiuto!
Grazie in anticipo.
Leonardo

**Comment by 50494554524F** [comment]
devi riscriverla senza usare wait_for_trigger.... un trigger per accendere, un trigger per spegnere... con due automazioni separate il codice viene più semplice

mode restart cambialo in mode queued in modo da completare il codice ed evitare che qualcosa rimanga appeso...

**Reply by snakuzzo** [reply]
No... già ne avevamo discusso tempo fa per un altro utente, se non ricordo male, non sono d'accordo su questa cosa di fare le cose separate, soprattutto in questo caso

**Reply by snakuzzo** [reply]
Invece sono d'accordo sul separare i trigger... perché in questo caso già sai quando deve scattare, non ha senso usare il wait for trigger.

Quindi fai due trigger, come ti ha suggerito lui.

Per quanto riguarda il mode, cambiando la logica con due trigger, tocca un attimo ragionarci...a pelle direi che in questo caso, quindi togliendo il wait for trigger, considerando che due eventi del calendar non scattino mai in contemporanea, sia ininfluente

**Reply by snakuzzo** [reply]
Per farla semplice, potresti fare una cosa del genere...
Lasci un solo trigger basato sul calndar (quello per l'accensione) e ne crei un altro per lo spegnimento basato sul valore di un input date_time di appoggio.

Quando scatta il trigger per l'accensione vai a popolare quell'input date_time con la data/orario in cui vuoi spegnere la luce (la calcoli dalla fine dell'evento del calendar).

Nel caso in cui, prima dello spegnimento legato al primo evento, scatti il trigger di on di un secondo evento, aggiorni l'input date_time con il nuovo orario di spegnimento.

In questo modo la luce sarà sempre accesa e si spegnerà, in caso di eventi sovrapposti, solo quando finirà l'ultimo evento.

Appena posso faccio una prova e ti posto il codice, ora sono da cell e mi risulta scomodo

**Comment by 01leoter** [comment]
Nel mentre ho scritto anche nel forum di home assistant e mi hanno inviato un codice, che poi modificandolo un po, funziona come deve. Lo allego qui sotto:
```
alias: Fari cemento prenotazione
description: >-
  Accende i fari cemento 5 minuti prima della prenotazione e li spegne 15 minuti
  dopo il termine della prenotazione.
trigger:
  - platform: calendar
    event: start
    entity_id: calendar.campo_cemento
    id: "on"
    offset: "-0:5:0"
  - platform: calendar
    event: end
    entity_id: calendar.campo_cemento
    id: "off"
    offset: "0:15:0"
condition:
  - condition: template
    value_template: "{{ 'Campo cemento illuminato' in trigger.calendar_event.summary }}"
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
        sequence:
          - type: turn_on
            device_id: b2baaaf31ea5057ab6181d9eb236b8e7
            entity_id: 9bb2b49f6e07506bdcda96a7794cd46f
            domain: switch
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - service: calendar.list_events
            data:
              duration: "00:30:00"
              start_date_time: "{{now()}}"
            target:
              entity_id: calendar.campo_cemento
            response_variable: agenda
          - condition: template
            value_template: >-
              {{ agenda.events | selectattr('summary', 'search', 'Campo cemento
              illuminato') | list | count == 0 }}
          - type: turn_off
            device_id: b2baaaf31ea5057ab6181d9eb236b8e7
            entity_id: 9bb2b49f6e07506bdcda96a7794cd46f
            domain: switch
mode: single
```
Comunque ringrazio a tutti per il supporto.
