### DISCUSSION TITLE
Problemi con wizard

### DISCUSSION THREAD

**Discussion by barbatrukko** [indomus/forum#2606] [HUB: Home Assistant]
Salve,
ho provato ad usare la wizard Motion-activated light, per far si che quando una certa videocamera rileva un movimento, mi venga inviato un messaggio su telegram e si accenda una luce.
Il messaggio su telegram arriva, ma la luce non si accende.
Ho inserito da wizard diverse entità e device... ma nessuna si accende

```
alias: Test Movimento
description: Test Movimento Cucina
action:
  - service: notify.YYYYYYYYYY
    data:
      title: "*Movimento giardino*"
      message: Movimento giardino
use_blueprint:
  path: homeassistant/motion_light.yaml
  input:
    motion_entity: binary_sensor.c6n_XXXXXXXX_motion_trigger
    light_target:
      entity_id:
        - light.wled_segment_0
        - light.wledq
        - light.wled_pc_master
      device_id: ZZZZZYYYYYYY
mode: single
```
