### DISCUSSION TITLE
Influx + Grafana

### DISCUSSION THREAD

**Discussion by Matty1184** [indomus/forum#2608] [HUB: Home Assistant]
Ciao a tutti, 
ho installato influx e grafana ma temo sto sbagliando qualcosa....
HA OS
installato influx
creato DB e utente, quest'ultimo read e write sia _internal, che DB Home assitant
inserito in configuration la seguente l'abilitazione:
```
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  api_version: 1
  ssl: false
  database: HomeAssistant
  username: influx_user
  password: xxxxxxxxxxxxxxxxxxxxxx
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor
```
Premesso che nello schema dell'interìfaccia web mi aspettavo di vedere qualche tabella in realtà vedo solo questo
![image](https://github.com/indomus/forum/assets/106579001/ff78e01a-050e-4967-bcbf-03332e498c28)

ma il problema è anche nel collegamento a grafana.
 ho inserito i dati ma non si collega

![image](https://github.com/indomus/forum/assets/106579001/95ac4083-c28c-4468-a5dc-3bdde49e3909)

suggerimenti?
