### DISCUSSION TITLE
Automazione per regolare volume speaker Google

### DISCUSSION THREAD

**Discussion by dwarfish** [indomus/forum#2616] [HUB: Home Assistant]
Ciao a tutti,
ho realizzato la seguente automazione che imposta il volume di uno speaker, una volta interrotta la riproduzione, se più alto:
```
alias: Volume
trigger:
  - platform: device
    device_id: df7a40febde37ae9422ab99b8fcd47fa
    domain: media_player
    entity_id: 5e3b810b3be2fee96205d60e5739977e
    type: paused
condition:
  - condition: numeric_state
    entity_id: 5e3b810b3be2fee96205d60e5739977e
    attribute: volume_level
    above: 0.15
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.15
    target:
      device_id: df7a40febde37ae9422ab99b8fcd47fa
mode: single
```
Volendo utilizzare la stessa automazione anche per gli altri speaker della casa, come dovrei modificarla?
L'idea è: va in pausa lo speaker A, imposto il volume di A; va in pausa B, imposto B; etc etc

^SiMoNe^
