### DISCUSSION TITLE
Shelly 1 risultano indisponibili al riavvio di HomeAssistant

### DISCUSSION THREAD

**Discussion by CesareDebian** [indomus/forum#2618] [HUB: Home Assistant]
Buongiorno, dopo aver integrato in HomeAssistant Supervised su Mini Pc Intel due shelly 1 in MQTT, ho notato che ad ogni riavvio di Home Assistant diventano non disponibili costringendomi a riavviarli in manuale.
Gli shelly sono stati inseriti creando un package:

```yaml
mqtt:
  switch:
    - name: "Cancello Secondo"
      state_topic: "shellies/cancello_secondo/relay/0"
      command_topic: "shellies/cancello_secondo/relay/0/command"
      availability_topic: "shellies/cancello_secondo/online"
      qos: 1
      value_template: "{% if value == 'on' %} on {% else %} off {% endif %}"
      payload_on: "on"
      payload_off: "off"
      payload_available: "true"
      payload_not_available: "false"
      optimistic: false
      retain: false
    - name: "Cancello Primo"
      state_topic: "shellies/cancello_primo/relay/0"
      command_topic: "shellies/cancello_primo/relay/0/command"
      availability_topic: "shellies/cancello_primo/online"
      qos: 1
      value_template: "{% if value == 'on' %} on {% else %} off {% endif %}"
      payload_on: "on"
      payload_off: "off"
      payload_available: "true"
      payload_not_available: "false"
      optimistic: false
      retain: false
```

Mi è stato detto che questo problema si risolve aggiungendo un'automazione per l'announce. Pertanto ho aggiunto questa automazione all'interno del package:

```yaml
automation:
- alias: MQTT Announce
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: mqtt.publish
    data:
      payload: update
      topic: shellies/command
```

Purtroppo il problema non è stato risolto.

**Comment by snakuzzo** [comment]
Non hai usato correttamente il markdown.
Correggi il post, altrimenti verrà cancellato
Grazie.

**Reply by snakuzzo** [reply]
vabbè te l'ho corretto io...famo prima

**Comment by snakuzzo** [comment]
Ad occhio l'automazione mi sembra corretta...e anche le entità MQTT.
Detto ciò, assicurati che non ci siano problemi sintattici con l'automazione, riavvia core e controlla che sia abilitata e che scatti correttamente.
Se vedi che non funziona, l'unica cosa da fare è controllare.
Quindi dovresti metterti in ascolto sul broker e vedere cosa passa quando viene eseguita l'automazione.

Ti faccio un esempio di come metterti in ascolto con i mosquitto client se li hai installati...

```
mosquitto_sub -v -t +/# -h ipmosquitto -u tuauser -P tuapassword | grep shelly1
```

Forzi la publish eseguendo manualmente l'automazione dalla webgui di HA...e dovresti trovare un output come questo: 

```
shellies/shelly1-98F4ABF298AD/online true
shellies/shelly1-98F4ABF298AD/relay/0 off
shellies/shelly1-98F4ABF298AD/input/0 1
shellies/shelly1-98F4ABF298AD/input_event/0 {"event":"","event_cnt":24}
```

Quello che ti interessa e che fa tornare online il device su HA è 

```
shellies/shelly1-98F4ABF298AD/online true
```

Fai sapere.

Ciao.

**Reply by CesareDebian** [reply]
Ho installato tutto d'accapo sperando in una risoluzione del problema. Purtroppo adesso le cose si sono complicate. Una volta installato MQTT ho inserito la configurazione degli shelly come riportato sopra, ma, questa volta, ho solo gli shelly rilevati in integrazione mentre se mi sposto in Entità non compaiono.
Mi sono messo in ascolto su MQTT inserendo # e noto che riesce ad ascoltare gli shelly.
Quando invece provo a scrivere l'automazione in Payload mi dice che non è possibile pubblicare in particolare ottengo:
Invocazione del servizio MQTT/publish non riuscita. MQTT topic name/filter must not be empty. for dictionary value @ data [topic]

**Reply by snakuzzo** [reply]
> Ho installato tutto d'accapo sperando in una risoluzione del problema. Purtroppo adesso le cose si sono complicate. Una volta installato MQTT ho inserito la configurazione degli shelly come riportato sopra, ma, questa volta, ho solo gli shelly rilevati in integrazione mentre se mi sposto in Entità non compaiono.

non ho capito

> Mi sono messo in ascolto su MQTT inserendo # e noto che riesce ad ascoltare gli shelly.
Quando invece provo a scrivere l'automazione in Payload mi dice che non è possibile pubblicare in particolare ottengo:
Invocazione del servizio MQTT/publish non riuscita. MQTT topic name/filter must not be empty. for dictionary value @ data [topic]

Ricontrolla bene l'automazione. Ti dice che è il topic ad essere vuoto, non il payload.

**Comment by CesareDebian** [comment]
Ciao, quello che ho notato è che se attivo manualmente l'automazione gli shelly diventano disponibili. Ti posto lo screenshot:

<img width="1620" alt="Schermata 2023-09-08 alle 22 25 09" src="https://github.com/indomus/forum/assets/109909412/6ee3e67a-1845-4e6d-8317-924ba773f249">

**Reply by Scialla** [reply]
il che vuol dire che la action funziona ma non funziona il trigger. Se non scatta il trigger all'avvio di homeassistant, vuol dire che HA non si riavvia ( o che hai altri problemi).
Fatto sta che sei tu a dover indagare guardando i log e mettendoti in ascolto sul broker, noi possiamo fare ben poco per capire come mai non ti va il trigger, ma non è una cosa normale

**Comment by lcorsini** [comment]
Ciao, vado a memoria perchè non uso shelly con HA da un pò ma ricordo un problema di questo tipo, avevo risolto con una automazione che refreshava tutte le info sulla coda forzando l'announce degli shelly


```
alias: "[generale] MQTT Announce Shellies"
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: mqtt.publish
    data:
      payload: announce
      topic: shellies/command
mode: single
```
