### DISCUSSION TITLE
Statistics Graph card per sensore custom

### DISCUSSION THREAD

**Discussion by skydado** [indomus/forum#2622] [HUB: Home Assistant]
Ho creato un sensore custom per "estrarre" la temperatura da un condizionatore che ho integrato tramite HACS (e che non aveva le relative entità).

```
- platform: template
  sensors:
    condiz_notte_temp:
      friendly_name: "Temperatura rilevata da Condizionatore zona notte"
      device_class: temperature
      value_template: "{{ state_attr('climate.condiz_zona_notte', 'current_temperature') }}"
      unit_of_measurement: "°C"
```

Ho poi visualizzato questa temperatura tramite state-badge card.
![image](https://github.com/indomus/forum/assets/144361321/87c702df-1538-46d7-a489-dab3567547d6)

Se ci clicco sopra, vedo il grafico con la history delle variazioni recenti (e quindi in qualche modo vengono salvate).
![image](https://github.com/indomus/forum/assets/144361321/0ecb44e5-39ed-4a13-bf0f-fe5f5aa67915)

Fino a qui tutto ok.

Vorrei aggiungere alla dashboard una "statistics graph" card per mostrare l'andamento della temperatura direttamente sulla dashboard.
Il sensore custom però non viene riconosciuto come sensore con history e, se anche lo indico manualmente, il risultato è "no statistics found."

Qualche suggerimento?
