### DISCUSSION TITLE
entità legate a homekit - info interpretazione

### DISCUSSION THREAD

**Discussion by Matty1184** [indomus/forum#2626] [GENERALE - Discussioni generiche]
Avrei bisogno del vostro aiuto in quanto non trovo documentazione in merito al mio dubbio che ho sui componenti utilizzati tramite homekit.
nei registri errori mi compare sempre un warning dove indica il superamento di 150 entità ma onestamente mi segnala anche entità che non sono associate tramite homekit come sensori creati da file yaml o automazioni.
un esempio:
```
2023-09-10 17:00:50.257 WARNING (MainThread) [homeassistant.components.homekit] Cannot add automation.tracker_wifi_telefoni as this would exceed the 150 device limit. Consider using the filter option
```
```
2023-09-10 17:00:50.255 WARNING (MainThread) [homeassistant.components.homekit] Cannot add sensor.cert_expiry_timestamp_xxxxxxxxxx_duckdns_org as this would exceed the 150 device limit. Consider using the filter option
```
perchè mi segnala anche questi?

**Comment by Scialla** [comment]
Homekit ha il limite tecnico di 150 device per ogni bridge

Tu esponi a homekit tutti i device presenti in HA, automazioni comprese

Devi usare i filtri nell'esporre i tuoi device a homekit, escludendo interi domini e includendo quello che ti serve, ad esempio:

```
homekit:
- filter:
    exclude_domains:
      - automation
      - device_tracker
      - person
      - script
      - group
      - media_player
      - remote
      - camera
      - input_select
      - select
      - button
      - script
    include_entities:
      - script.film_on
      - script.film_off
    exclude_entities:
      - climate.camera_da_letto
      - climate.cucina
      - climate.studio
      - climate.ingresso
   ```
etc etc, la mia lista delle entità escluse è lunghetta
