### DISCUSSION TITLE
pulse counter via mqtt

### DISCUSSION THREAD

**Discussion by zanac** [indomus/forum#2630] [GENERALE - Discussioni generiche]
Ciao,

ho un device che sta pubblicando via json un contatore di impulsi.... da home assistant vedo che nel server mqtt effettivamente il topic 1778384968/JSON contiene i dati:
![image](https://github.com/indomus/forum/assets/21194919/2e535eb1-d0ef-4226-9d48-dd78f0ec6e52)

Il mio scopo è ora leggere quel valore TCH1 e inserirlo in un sensore... però se inserisco questo non mi pare funzionare. Dove sbaglio?
mqtt:
  binary_sensor:
    name: contatoreimpulsi
    state_topic: "1778384968/JSON"
    value_template: "{{ TCh1 }}"

**Comment by snakuzzo** [comment]
Innanzi tutto, per tutto quello che riguarda codice dovresti usare il markdown e non copiare brutalmente come hai appena fatto.
Poi...così come hai scritto non va bene. Il consiglio è quello di leggere la documentazione ufficiale [QUI](https://www.home-assistant.io/integrations/binary_sensor.mqtt/), dove è tutto scritto in modo molto chiaro.

Entrando nello specifico, la stringa JSON in questo caso si trova in `value_json`...ma non solo. Trattandosi di un `binary_sensor` devi fare in modo che il valore di `0` e `1` sia riconosciuto come `off` o `on`. Ti dico questo perché, per questo tipo di entità, di default per Core le stringhe che ti permettono di evidenziare l'entità con stato on e off  sono `'OFF'` e `'ON'` (come scritto [QUI](https://www.home-assistant.io/integrations/binary_sensor.mqtt/#payload_off) ... guarda il valore di default che lui considera); quindi, utilizzando i template, uno dei modi per poter visualizzare il valore potrebbe essere questo:

```yaml
binary_sensor:
  - name: "contatoreimpulsi"
    state_topic: "1778384968/JSON"
    value_template: "{{ 'ON' if value_json.TCh1 == 1 else 'OFF' }}"
```

Se invece non è un sensore binario...ti basta questo...

```yaml
sensor:
  - name: "contatoreimpulsi"
    state_topic: "1778384968/JSON"
    value_template: "{{ value_json.TCh1 }}"
```
