### DISCUSSION TITLE
idea di modello di sviluppo

### DISCUSSION THREAD

**Discussion by 50494554524F** [indomus/forum#2633] [Nuove idee, proposte, progetti e guide]
definitivo!!!

```
blueprint.heater_lock
    |
PARAMETRI                                                                                    blueprint.on_heater_lock
entities  [list]                                                                               |
condition [template, optional]                                                               PARAMETRI
delay     [duration, optional]                                                               entity [string]
    |                                                                                        action [script block, optional]
AUTOMAZIONE                                                                                     |
alias: Heater Lock                                                                           AUTOMAZIONE
id: heater_lock                                                                              alias: On Heater Lock
entities: ...                                                                                id: on_heater_lock
condition: ...                   PARAMETRI                    PARAMETRI                      entity: ...
delay: ...                       entities  [list]             entities  [list]               action: ...
    |                                |                           |                              |   
automation.heater_lock     >     script.heater_lock     >     event.on_heater_lock     >     automation.on_heater_lock     >     script.on_heater_lock 
    |                                |                           |                              |                                   |                  
trigger                          esegue                       si propaga                     trigger                             esegue                  
condition + delay                azioni comuni                                               event.on_heater_lock                azioni comuni      
    |                                |                                                          |
chiama                           genera evento                                               chiama
script.heater_lock               event.on_heater_lock                                        script.on_heater_lock                  
                                                                                                |        
                                                                                             esegue
                                                                                             script block
```

è partito come un appunto, lo metto così anche se andrebbe fatto un grafico di flusso

c'ho pensato un sacco di tempo cercando di replicare il modello ad eventi, direi che è venuto bellino e funziona bene

semplicità, leggibilità, flessibilità massima

spiego direttamente con questo esempio, lo uso per bloccare un valvola nel caso ci siano troppi apri/chiudi che possono far accendere/spegnere la caldaia in continuazione

la prima parte si occupa di controllare il verificarsi di una condizione, la seconda parte è il post accadimento

il primo blueprint si occupa solo di definire il nostro trigger grazie alla condition - eventualmente di attentedere che la condizione sia manenuta 
per un certo tempo con delay - e di chiamare lo script.heater_lock
perché?! perché se lo script serve è già lì pronto se dover ricopiare/mantere un altro blocco di codice

nello script.heater_lock possiamo inserire azioni comuni a tutte le valvole, altrimenti verrà generato il solo evento event.on_heater_lock
perché?! perrché l'evento si propagherà in tutto il sistema e potrà essere intercettato da altre automazioni/trigger sensor/etc
eventualmente potrà essere generato con altri dati, in altri posti, secondo necessità

il secondo blueprint si occupa di intercettare il precedente evento e possiamo usarlo per definire azioni da eseguire per una entità specifica (forse lo modificherò per accettare più entità)
l'automazione generata eseguirà prima le azioni comuni definite in script.on_heater_lock e poi eseguire il blocco action che gli abbiamo passato
perché?! similmente a quanto detto prima abbiamo uno script già pronto dovesse servire

tutto è bello separato in modo logico, si può impacchettare nei packages mantenendo tutto insieme come fosse un classico oggetto, 
nella maggior parte dei casi si tratterà di usare solo il primo blueprint ed il primo script

(anche qui sto pensando se usare i blueprint per gli script in modo da inserirli direttamente in un package)

sperando che sia tutto chiaro :D ... un attimo di pazienza, fatemi capire se posso allegare uno zip, sennò nei post successivi vi allegherò il codice che sto usando...

**Comment by 50494554524F** [comment]
```



#
#     blueprint:
#
#       name: heater-lock.yaml
#
#       description: lock an heater
#
#       dependencies:
#
#         scripts:
#
#           - script.heater_lock
#
#       usage:
#
#         use_blueprint:
#
#           path: heater-lock.yaml
#
#           input:
#
#             entities:
#
#               - entity_id                                  #  the entity_id of the heater to monitor
#
#             condition: template                            #  condition template to match [ optional ]
#
#             delay: duration                                #  the amount of time to wait [ optional ]
#



#  Heater - Lock

blueprint:



  name: 'Heater - Lock'

  description: 'Lock an heater'

  domain: automation



  input:



    entities:

      name: 'Heater'

      description: 'The heater to monitor'
      
      selector:
      
        entity:
        
          domain: switch

          multiple: true



    condition:

      name: 'Condition'

      description: 'The condition template to match'

      default: "{{  none  }}"
      
      selector:
      
        template:



    delay:

      name: 'Delay'

      description: 'The amount of time to wait'
      
      default: "00:00:00"
      
      selector:
      
        duration:



mode: queued



trigger:



  - platform: template

    value_template: !input condition

    for: !input delay



action:



  - service: script.heater_lock

    data:

      entities: !input entities




```

**Reply by 50494554524F** [reply]
```



#
#     script:
#
#       name: script.heater_lock
#
#       description: lock an heater
#
#       usage:
#
#         action: call-service
#
#         service: script.heater_lock
#
#         data:
#
#           entities:
#
#             - entity_id                                     #  the entity_id of the heater to manage
#



#  Heater - Lock

heater_lock:



  alias: 'Heater - Lock'
  
  description: 'Lock an heater'

  mode: queued


  
  fields:


  
    entities:

      name: 'Heater'

      description: 'The heater to manage'
      
      required: true
      
      selector:
      
        entity:
        
          domain: switch

          multiple: true



  sequence:



    - event: on_heater_lock

      event_data:

        entities: >-

          {{

              entities

          }}




```

**Reply by 50494554524F** [reply]
```



#
#     blueprint:
#
#       name: on-heater-lock.yaml
#
#       description: services to run when an on_heater_lock event is raised
#
#       dependencies:
#
#         scripts:
#
#           - script.on_heater_lock
#
#       usage:
#
#         use_blueprint:
#
#           path: on-heater-lock.yaml
#
#           input:
#
#             entity: entity_id                                     #  entity_id of the entity to monitor
#
#             action: object                                        #  the action to perform
#



#  On - Heater - Lock

blueprint:



  name: 'On - Heater - Lock'

  description: 'Services to run when an on_heater_lock event is raised'

  domain: automation



  input:



    entity:

      name: 'Heater'

      description: 'The heater to monitor'
      
      selector:
      
        entity:

          domain: switch



    action:

      name: 'Action'

      description: 'The action to perform'
      
      selector:
      
        object:



mode: queued



variables:



  entity: !input entity



trigger:



  - platform: event

    event_type: on_heater_lock



condition:



  - condition: template

    value_template: >-

      {{

          trigger.event.data.entities is defined
      
      }}

  - or:

      - condition: template

        value_template: >-

          {{

              trigger.event.data.entities is string

                  and
              
              trigger.event.data.entities == entity

          }}

      - condition: template

        value_template: >-

          {{

              trigger.event.data.entities is not string

                  and

              trigger.event.data.entities is not mapping

                  and

              trigger.event.data.entities is iterable

                  and
              
              trigger.event.data.entities | contains( entity )

          }}
    


action:



  - service: script.on_heater_lock

    data:

      entities: !input entity

      data: >-

        {{

            trigger.event.data

        }}



  - repeat:

      count: 1

      sequence: !input action




```

**Reply by 50494554524F** [reply]
```



#
#     script:
#
#       name: script.on_heater_lock
#
#       description: services to run when an on_heater_lock event is raised
#
#       usage:
#
#         action: call-service
#
#         service: script.on_heater_lock
#
#         data:
#
#           entities:
#
#             - entity_id                                         #  the entity_id of the entity that raised the event
#
#           data: object                                          #  additional data to use
#



#  On - Heater - Lock

on_heater_lock:



  alias: 'On - Heater - Lock'

  description: 'Services to run when an on_heater_lock event is raised'

  mode: queued



  fields:



    entities:

      name: 'Heater'

      description: 'The heater that raised the event'
      
      required: true
      
      selector:
      
        entity:
        
          domain: switch

          multiple: true



    data:

      name: 'Data'

      description: 'Additional data to use'
      
      selector:
      
        object:



  sequence:




```

**Reply by 50494554524F** [reply]
```



  automation:



    #  Radiator Valve - Heater - Lock

    - alias: 'Radiator Valve - Heater - Lock'

      id: 'radiator_valve_heater_lock'

      use_blueprint:

        path: heater-lock.yaml

        input:

          entities: switch.radiator_valve

          condition: >-

            {{

                is_state( 'binary_sensor.radiator_valve_tilt', 'on' )

            }}



    #  Radiator Valve - On - Heater - Lock

    - alias: 'Radiator Valve - On - Heater - Lock'

      id: 'radiator_valve_on_heater_lock'

      use_blueprint:

        path: on-heater-lock.yaml

        input:

          entity: switch.radiator_valve

          action:

            - service: input_select.select_option

              target:

                entity_id: input_select.radiator_valve_mode

              data:

                option: 'locked'

```
