### DISCUSSION TITLE
Problema con haaska

### DISCUSSION THREAD

**Discussion by 19melos87** [indomus/forum#2650] [HUB: Home Assistant]
Ciao,

ho un problema con la configurazione di haaska.
Questo è l'errore
```
{
  "errorMessage": "HTTPSConnectionPool(host='**miosito.it**', port=9000): Max retries exceeded with url: /api/alexa/smart_home (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))",
  "errorType": "SSLError",
  "requestId": "ad0de3cc-954f-4efd-8a79-1296256d7c03",
  "stackTrace": [
    "  File \"/var/task/haaska.py\", line 111, in event_handler\n    return ha.post('alexa/smart_home', event, wait=True)\n",
    "  File \"/var/task/haaska.py\", line 63, in post\n    r = self.session.post(self.build_url(endpoint),\n",
    "  File \"/var/task/requests/sessions.py\", line 581, in post\n    return self.request('POST', url, data=data, json=json, **kwargs)\n",
    "  File \"/var/task/requests/sessions.py\", line 533, in request\n    resp = self.send(prep, **send_kwargs)\n",
    "  File \"/var/task/requests/sessions.py\", line 646, in send\n    r = adapter.send(request, **kwargs)\n",
    "  File \"/var/task/requests/adapters.py\", line 514, in send\n    raise SSLError(e, request=request)\n"
  ]
}
```
Ho fatto varie prove, la prima è stata escludere la verifica ssl nel json, ed escludendola il test lambda viene eseguito senza errori.
Ho controllato vari post su github, anche passati da voi.

La mia configurazione in questo momento è:
- HA su mini pc senza ssl installati, da LAN accedo in http
- Caddy installato sullo stesso mini pc con le seguenti config:
```
(https_header) {
  header {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}

https://**miosito**.it {
  respond "Home"
  file_server
}
https://**miosito**.it:9000 {
  tls /data/melos87.cer /data/private_key.key
  import https_header
  reverse_proxy http://192.168.1.5:8123
}
```
e questo è il docker compose con cui lo installo:

```
 caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/deb/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/deb/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
```
- dominio **miosito**.it comprato su ionos che mi ha fornito un certificato SSL wildcard (sul sito ho la possibilità di scaricarlo in .cer)

Al momento l'accesso dall'esterno con https non da alcun tipo di problema, escluso per haaska.
