### DISCUSSION TITLE
esercizio 1 – Creare dei sensori template

### DISCUSSION THREAD

**Discussion by ivannotavailable** [indomus/forum#2654] [HUB: Home Assistant]
Primo messaggio, primi passi con HA.  Perdonate se non 'sbaglio stile'. 
Installazione HASSIO su RPi4. (InDomus)  Formazione- Esercizi di domotica su Home Assistant: “1 – Creare dei sensori template”

Ho seguito la giuda.  Aggiunto il blocco yaml in configuration.yaml - non trovando alcun riferimento ad eventuali sidecar. 

```yaml
template:
  - sensor:
      temperatura_living_mio:
        friendly_name: "Temperatura-Living-Mio"
        value_template: ‘{{ states.climate.mago_living.attributes.temperature|float(default=0) }}’
        unit_of_measurement: "°C"
        icon_template: mdi:thermometer
```

Mi restituisce questo errore.

_Logger: homeassistant.config
Source: config.py:864
Invalid config for [template]: [temperatura_living_mio] is an invalid option for [template]. Check: template->sensor->0->temperatura_living_mio. (See /config/configuration.yaml, line 33)._

Suggerimenti? grazie.
Aggiungo: ‘{{ states.climate.mago_living.attributes.temperature|float(default=0) }}’ mi da esito positivo con dev.tool - template.

**Comment by snakuzzo** [comment]
Così...

```yaml
template:
- sensor:
  - name: "temperatura_living_mio_1"
    state: "{{ state_attr('climate.mago_living','temperature') | float(default=0) }}"
    unit_of_measurement: "°C"
    icon: mdi:thermometer
```

oppure 

```yaml
sensor:
- platform: template
  sensors:
    temperatura_living_mio_2:
      friendly_name: "Temperatura-Living-Mio_2"
      value_template: "{{ state_attr('climate.mago_living','temperature') | float(default=0) }}"
      unit_of_measurement: "°C"
      icon_template: mdi:thermometer
```

Leggi e studia anche la doc ufficiale [QUI](https://www.home-assistant.io/integrations/template/)

E guarda come ho scritto il value template usando `states()` (che è il modo più corretto per quanto scritto [QUI](https://www.home-assistant.io/docs/configuration/templating/#states)) ... attento anche agli apici che hai usato!

Nello specifico:

![image](https://github.com/indomus/forum/assets/7205371/0ac27c99-5431-4c07-a9c6-f41d4041403d)

Questo il risultato sulla dashboard con entrambi gli esempi...

![image](https://github.com/indomus/forum/assets/7205371/6d144728-dc2e-4db9-9f67-cf7fdbfe9443)

**Comment by ivannotavailable** [comment]
Grazie! 
ancora non mi sono chiari gli errori commessi... sono in fase learning by doing, fatico - mi mancano le basi ma non desisto.

**Comment by NuccioT** [comment]
Buonasera ottengo lo stesso errore di cui sopra. La cosa strana è che ho due istanze di Home Assistant su due diverse macchine: su una non mi dà errore e funziona, sull'altra invece mi ritorna l'errore. il template è il seguente
 
```
# Configurazione sensore previsioni orarie Met.No
template:
  - trigger:
      - platform: time_pattern
        hours: /1
    action:
      service: weather.get_forecasts
      data:
        type: hourly
      target:
        entity_id: weather.casa
      response_variable: forecast_data
    sensor:
      name: "Casa Orarie Nor"
      unique_id: dal202403252000
      state: "{{ forecast_data['weather.casa'].forecast[0].condition }}"
      attributes:
        forecast: "{{ forecast_data['weather.casa'].forecast }}"
        updatedAt: "{{ now().isoformat() }}"
```
Come detto le due configurazioni sono identiche ma su un'istanza funziona e sull'altra no. Le due versioni di HA sono aggiornate alla stesso modo. Unica cosa che differisce è la macchina: uno un PI e l'alto un mini computer.
Grazie per eventuali feedback
