### DISCUSSION TITLE
Zigbee2MQTT Error "connection not initialized"

### DISCUSSION THREAD

**Discussion by centenico** [indomus/forum#2659] [ZigBee, Z-Wave, Thread, Matter]
Sto usando il Sonoff ZBDongle-E 3.0 flashato con il firmware RCP (4.3.1)
Ho verificato mille volte il tutto, provato a riflashare il dongle con una versione precedente (4.3.1) ma nulla da fare.

Ho il seguente errore

_Using '/app/data' as data directory
Zigbee2MQTT:info  2023-10-12 14:18:24: Logging to console and directory: '/var/log' filename: log.txt
Zigbee2MQTT:info  2023-10-12 14:18:24: Starting Zigbee2MQTT version 1.33.1 (commit #7e63039)
Zigbee2MQTT:info  2023-10-12 14:18:24: Starting zigbee-herdsman (0.19.0)
**Zigbee2MQTT:error 2023-10-12 14:18:44: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-10-12 14:18:44: Failed to start zigbee**
Zigbee2MQTT:error 2023-10-12 14:18:44: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
**Zigbee2MQTT:error 2023-10-12 14:18:44: Exiting...
Zigbee2MQTT:error 2023-10-12 14:18:44: Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:551:19)**
    _at Ezsp.version (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:349:35)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:141:25)
    at EZSPAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:165:16)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)__

Ho configurato il tutto nel seguente modo:

**Le mie porte USB:**

_/dev/bus/usb/001/006 - ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230830081449
/dev/ttyACM0 - ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230830081449_

**Network:**

_2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 
    inet 192.168.0.110/24 brd 192.168.0.255 scope global noprefixroute enp1s0_

Mosquitto su /srv/mosquitto, nel file /srv/mosquitto/config/mosquitto.conf

> persistence true
> persistence_location /mosquitto/data/
> log_dest file /mosquitto/log/mosquitto.log
> log_dest stdout
> listener 1883
> password_file /mosquitto/config/mosquitto.passwd
> allow_anonymous false

Zigbee2mqtt su /home/nico/zigbee2mqtt, nel file /home/nico/zigbee2mqtt/configuration.yaml

> homeassistant: true
> permit_join: false
> mqtt:
>   base_topic: zigbee2mqtt
>   server: 'mqtt://localhost'
>   user: nico
>   password: *******
>   version: 5
>   include_device_information: true
**> serial:
>   port: tcp://192.168.0.110:9999**
>   adapter: ezsp
> advanced:
>   log_directory: /var/log
> experimental: {}
> frontend:
>   port: 8080
> ota:
>   update_check_interval: 10
> disable_automatic_update_check: false

Invece nel docker-compose le 3 configurazioni sono le seguenti:

```
  multipan:
    container_name: multipan
    image: b2un0/silabs-multipan-docker
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    restart: 'no'
    privileged: true
    network_mode: host
    **devices:
      - /dev/ttyACM0**
    volumes:
      - ./data/:/data
    environment:
      # OCPD environment variables
      DEVICE: "/dev/ttyACM0"
      BAUDRATE: "460800"
      CPCD_TRACE: "false"
      FLOW_CONTROL: "false"

      NETWORK_DEVICES: 0

      # OTBR-AGENT environment variables
      OTBR_ENABLE: 1
      BACKBONE_IF: "enp1s0"
      OTBR_LOG_LEVEL: "debug"
      OTB_FIREWALL: 1
      OTBR_REST_LISTEN_PORT: "8081"

      # OTBR-WEB environment variables
      OTBR_WEB_PORT: "8086"

      # SOCAT environment variables
      NETWORK_DEVICE: ""

      # ZIGBEED environment variables
      EZSP_LISTEN_PORT: "20108"

      # UNIVERSAL FLASHER variables
      AUTOFLASH_FIRMWARE: 0
      FIRMWARE: "86"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
    - "/srv/mosquitto/config:/mosquitto/config"
    - "/srv/mosquitto/log:/mosquitto/log"
    - "/srv/mosquitto/data/:/mosquitto/data"
    restart: always
    ports:
    - "1883:1883"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
    - "/home/nico/zigbee2mqtt:/app/data"
    environment:
    - "TZ=Europe/Rome"
    network_mode: host
    restart: always
```

**Logs mosquitto:**

_1697112623: mosquitto version 2.0.18 starting
1697112623: Config loaded from /mosquitto/config/mosquitto.conf.
1697112623: Opening ipv4 listen socket on port 1883.
1697112623: Opening ipv6 listen socket on port 1883.
1697112623: mosquitto version 2.0.18 running_

**Logs multipan**

_2023-10-12 12:10:21 [INFO] Starting otbr-web...
otbr-web[296]: [INFO]-WEB-----: Running 0.3.0
otbr-web[296]: [INFO]-WEB-----: Border router web started on wpan0
otbr-agent[206]: 00:00:00.135 [I] Platform------: Session socket is ready
s6-rc: info: service legacy-services successfully started
otbr-agent[206]: [INFO]-MDNS----: Received reply for service Home Assistant Silicon Labs Multiprotocol #15D6._meshcop._udp., serviceRef = 0x564ee8282040
otbr-agent[206]: [INFO]-MDNS----: Successfully registered service Home Assistant Silicon Labs Multiprotocol #15D6._meshcop._udp.
otbr-agent[206]: [INFO]-BA------: Result of publish meshcop service Home Assistant Silicon Labs Multiprotocol #15D6._meshcop._udp.local: OK
otbr-agent[206]: [INFO]-BA------: Result of publish meshcop service Home Assistant Silicon Labs Multiprotocol #15D6._meshcop._udp.local: OK
Default: mDNSCoreReceiveResponse: Received from 192.168.0.110:5353   21 110.0.168.192.in-addr.arpa. PTR homeserver-23.local.
Default: mDNSCoreReceiveResponse: Unexpected conflict discarding   18 110.0.168.192.in-addr.arpa. PTR homeserver.local.
Default: mDNSCoreReceiveResponse: Received from 192.168.0.110:5353   21 6.3.d.a.9.b.e.f.f.f.4.3.3.8.e.7.1.0.0.0.d.7.a.3.1.8.e.7.7.0.a.2.ip6.arpa. PTR homeserver-23.local.
Default: mDNSCoreReceiveResponse: Unexpected conflict discarding   18 6.3.D.A.9.B.E.F.F.F.4.3.3.8.E.7.1.0.0.0.D.7.A.3.1.8.E.7.7.0.A.2.ip6.arpa. PTR homeserver.local.
Default: mDNSCoreReceiveResponse: Received from fe80::42:95ff:fed8:f210:5353   21 0.1.2.f.8.d.e.f.f.f.5.9.2.4.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa. PTR homeserver-23.local.
Default: mDNSCoreReceiveResponse: Unexpected conflict discarding   18 0.2.6.1.1.6.E.F.F.F.B.F.2.E.8.F.0.0.0.0.0.0.0.0.0.0.0.0.0.8.E.F.ip6.arpa. PTR homeserver.local.
Default: mDNSCoreReceiveResponse: Received from fe80::2485:fbff:fe73:b89c:5353   21 c.9.8.b.3.7.e.f.f.f.b.f.5.8.4.2.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa. PTR homeserver-23.local.
Default: mDNSCoreReceiveResponse: Unexpected conflict discarding   18 C.9.8.B.3.7.E.F.F.F.B.F.5.8.4.2.0.0.0.0.0.0.0.0.0.0.0.0.0.8.E.F.ip6.arpa. PTR homeserver.local.
Listening on port 20108 for connection...
Accepting connection.
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::6cbb:b3ff:fe1c:2dcd/veth944baf2/134947
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::6cbb:b3ff:fe1c:2dcd/veth944baf2/134947
Default: mDNSCoreReceiveResponse: Received from fe80::6cbb:b3ff:fe1c:2dcd:5353   21 d.c.d.2.c.1.e.f.f.f.3.b.b.b.c.6.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa. PTR homeserver-25.local.
Default: mDNSCoreReceiveResponse: Unexpected conflict discarding   18 D.C.D.2.C.1.E.F.F.F.3.B.B.B.C.6.0.0.0.0.0.0.0.0.0.0.0.0.0.8.E.F.ip6.arpa. PTR homeserver.local.
otbr-agent[206]: 00:01:00.061 [D] Platform------: Trying to get RCP time offset
otbr-agent[206]: 00:01:00.062 [D] Platform------: Sent spinel frame, flg:0x2, iid:2, tid:3, cmd:PROP_VALUE_GET, key:TIMESTAMP
otbr-agent[206]: 00:01:00.062 [D] Platform------: Wait response: tid=3 key=2050
otbr-agent[206]: 00:01:00.064 [D] Platform------: Received spinel frame, flg:0x2, iid:2, tid:3, cmd:PROP_VALUE_IS, key:TIMESTAMP,
otbr-agent[206]: 00:03:00.069 [D] Platform------: Trying to get RCP time offset
otbr-agent[206]: 00:03:00.069 [D] Platform------: Sent spinel frame, flg:0x2, iid:2, tid:5, cmd:PROP_VALUE_GET, key:TIMESTAMP
otbr-agent[206]: 00:03:00.069 [D] Platform------: Wait response: tid=5 key=2050
otbr-agent[206]: 00:03:00.071 [D] Platform------: Received spinel frame, flg:0x2, iid:2, tid:5, cmd:PROP_VALUE_IS, key:TIMESTAMP, timestamp:182402684_

Grazie mille in anticipo.
