### DISCUSSION TITLE
Zigbee2mqtt switch - integrazione in HA

### DISCUSSION THREAD

**Discussion by reiner348** [indomus/forum#2704] [HUB: Home Assistant]
Ciao a tutti!
Ho un problema con uno switch ZBMINIL2...

Premesse:
- ho mosquitto
- ho home assistant core installato
- ho zigbee2mqtt installato e funziona correttamente
- ho vari sensori zigbee che funzionano perfettamente (aqara e altri)

Ho configurato in zigbee2mqtt lo zbminil2, si chiama "riscaldamento". Funziona bene e rimbalza tutto il dovuto su mosquitto. Il log mqtt che vedo ogni volta che switcha è:
```
zigbee2mqtt/riscaldamento {"device":"dateCode":"20230505","friendlyName":"riscaldamento","ieeeAddr":"0x84ba20fffee23ef0","manufacturerID":4742,"manufacturerName":"SONOFF","model":"ZBMINIL2","networkAddress":18608,"powerSource":"Mains (single phase)","softwareBuildID":"1.0.14","type":"EndDevice","zclVersion":8},"linkquality":168,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":4110,"latest_version":4110,"state":"idle"}}
```
Ho configurato in HA uno switch mqtt così (ho altri sensori mqtt, ho tolto la parte di codice che non serve per facilità di lettura):
```
mqtt:
  switch:
    - name: "riscaldamento"
      state_topic: "zigbee2mqtt/riscaldamento/state"
      command_topic: "zigbee2mqtt/riscaldamento/set"
      qos: 1
      value_template: "{% if value == 'on' %} on {% else %} off {% endif %}" 
      payload_on: "on"
      payload_off: "off"
      payload_available: "true"
      payload_not_available: "false"
      optimistic: true
      retain: true
```

Ho creato una card di prova button in lovelace. Se lo controllo da quella, funziona perfettamente. Si accende e spegne e lo stato sulla card si aggiorna in accordo allo stato effettivo del ZBMINI. 
Il problema è se comando lo ZBMINI fisicamente, con un interruttore... In questo caso, lo switch giustamente cambia stato fisicamente, però su HA non si aggiorna di conseguenza. Quindi in sostanza HA non "legge" lo stato del ZBMINI, ma si aggiorna solo in funzione del comando che HA stesso lancia: Se lancia ON, diventa on; se lancia OFF, diventa off. Ma se ne frega di quello che succede all'interruttore fisico...
Credo che il problema sia nella lettura del topic generato su mqtt dal zbmini quando cambia stato. Topic che viene generato correttamente anche usando lo switch fisico, ma che non viene recepito da HA...

Non riesco a trovare la soluzione... Qualche aiuto?
