### DISCUSSION TITLE
miglioramento automazione

### DISCUSSION THREAD

**Discussion by barbatrukko** [indomus/forum#2710] [HUB: Home Assistant]
Salve,
nel mio corridoio ho 3 pulsanti (normali pulsanti vimar) con i quali tramite un relè accendo le luci. Qualche tempo fa ho aggiunto un sonoff al circuito percui posso spegnere e accendere dai pulsanti da app da HA etc.
In seguito ho aggiunto una automazione che quando accendo la luce del corridoio dopo 1 min la spegne in automatico.

```
alias: Autospegnimento Corridoio
description: Spegne la luce dopo 60 secondi dall accensione
trigger:
  - platform: state
    entity_id: switch.sonoff_XXXXXXXXXX
    from: "off"
    to: "on"
action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data:
      entity_id: switch.sonoff_XXXXXXXXXXXX
```

Vorrei migliorarla, facendo in modo che in seguito ad un doppio click del pulsante (stabilendo entro quanto tempo effettuare il secondo click) si "disabiliti la modalità di spegnimento automatico (magari per fare qualcosa nel corridoio che non sia il semplice passaggio).
Quando poi spegno le luci ripremendo il pulsante o per via domotica, il funzionamento torna ad essere quello solito (dopo 1 min si spegne la luce).
In pratica quindi il doppio click dovrebbe attivare un flag che mi inibisce lo spegnimento automatico, che poi viene resettato al primo spegnimento.
