### DISCUSSION TITLE
Sommare 2 grafici di produzione Solare

### DISCUSSION THREAD

**Discussion by ghost** [indomus/forum#2714] [HUB: Home Assistant]
Ciao a tutti e grazie per le numerose dritte che ho trovato in queste pagine.
Finalmente sono riuscito a far visualizzare la produzione di 2 impianti solari distinti in 2 grafici distinti.
Ma vorrei chiedervi supporto per sommare i 2 grafici al fine di visualizzare la produzione globale.
Questo è il codice che mi permette di visualizzare i 2 grafici dai rispettivi sensori.

```
cards:
  - type: gauge
    entity: sensor.sn_1930013711_grid_power
    name: SMA
    theme: Graphite
    max: 1580
    min: 10
    needle: false
  - type: gauge
    name: SolarEdge
    theme: Graphite
    max: 4100
    min: 10
    needle: false
    entity: sensor.solaredge_current_power
```

Se avete qualche guida per imparare a gestire queste tipologie di domande non esitate a postare il link.
Grazie in anticipo
