### DISCUSSION TITLE
il trigger non scatta...

### DISCUSSION THREAD

**Discussion by Nik71git** [indomus/forum#2718] [GENERALE - Discussioni generiche]
Buongiorno, la seguente automazione ha gli stati dei sensori corretti (verificati in "strumenti per sviluppatori" ma non esegue le action, cioè non commuta i sensori booleani; posto il codice per vedere se qualcuno mi aiuta a trovare l'inghippo.

```
alias: arieggiare
description: attiva il relativo sensore booleano
trigger:
  - platform: template
    value_template: >-
      {{ (states.sensor.umidita_assoluta_bagni.state|float) >
      (states.sensor.umidita_assoluta_esterna.state|float) }}
    id: bagni on
    for:
      hours: 0
      minutes: 30
      seconds: 0
  - platform: template
    value_template: >-
      {{ (states.sensor.umidita_assoluta_bagni.state|float) <
      (states.sensor.umidita_assoluta_esterna.state|float) }}
    id: bagni off
    for:
      hours: 0
      minutes: 30
      seconds: 0
  - platform: template
    value_template: >-
      {{ (states.sensor.umidita_assoluta_zona_giorno.state|float) >
      (states.sensor.umidita_assoluta_esterna.state|float) }}
    id: giorno on
    for:
      hours: 0
      minutes: 30
      seconds: 0
  - platform: template
    value_template: >-
      {{ (states.sensor.umidita_assoluta_zona_giorno.state|float) <
      (states.sensor.umidita_assoluta_esterna.state|float) }}
    id: giorno off
    for:
      hours: 0
      minutes: 30
      seconds: 0
  - platform: template
    value_template: >-
      {{ (states.sensor.umidita_assoluta_zona_notte.state|float) >
      (states.sensor.umidita_assoluta_esterna.state|float) }}
    id: notte on
    for:
      hours: 0
      minutes: 30
      seconds: 0
  - platform: template
    value_template: >-
      {{ (states.sensor.umidita_assoluta_zona_notte.state|float) <
      (states.sensor.umidita_assoluta_esterna.state|float) }}
    id: notte off
    for:
      hours: 0
      minutes: 30
      seconds: 0
  - platform: template
    value_template: >-
      {{ (states.sensor.umidita_assoluta_taverna.state|float) >
      (states.sensor.umidita_assoluta_esterna.state|float) }}
    id: taverna on
    for:
      hours: 0
      minutes: 30
      seconds: 0
  - platform: template
    value_template: >-
      {{ (states.sensor.umidita_assoluta_taverna.state|float) <
      (states.sensor.umidita_assoluta_esterna.state|float) }}
    id: taverna off
    for:
      hours: 0
      minutes: 30
      seconds: 0
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - taverna on
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.arieggiare_taverna
      - conditions:
          - condition: trigger
            id:
              - taverna off
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.arieggiare_taverna
      - conditions:
          - condition: trigger
            id:
              - giorno on
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.arieggiare_zona_giorno
      - conditions:
          - condition: trigger
            id:
              - giorno off
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.arieggiare_zona_giorno
      - conditions:
          - condition: trigger
            id:
              - notte on
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.arieggiare_zona_notte
      - conditions:
          - condition: trigger
            id:
              - notte off
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.arieggiare_zona_notte
      - conditions:
          - condition: trigger
            id:
              - bagni on
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.arieggiare_bagni
      - conditions:
          - condition: trigger
            id:
              - bagni off
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.arieggiare_bagni
initial_state: true
mode: single

```
