### DISCUSSION TITLE
Integrazione Termovalvole Tado con Homeassistant

### DISCUSSION THREAD

**Discussion by Topolynx** [indomus/forum#2727] [HUB: Home Assistant]
Ciao a tutti. Stamattina ho sostituito l'impianto termovalvole/relé Netatmo (rotto dopo tre anni appena di vita) con il sistema Tado, 4 teste + internet hub. Homeassistant ha trovato da sé i componenti suggerendomi due intgrazioni, Tado e Tado internet bridge come integrazione Homekit. Ho configurato la prima, fin qui tutto ok. Per quanto riguarda la seconda, io mi interfaccio con Homekit via Homekit Bridge, ed è HA ad esporre in HomeKit tutti i miei dispositivi.
Dovrei abilitare o meno l'integrazione HomeKit Device per Tado internet bridge, piuttosto che esporla ad HomeKit?
In seconda analisi, ho notato che se imposto delle temperature da app Tado, non mi vengono sincronizzate nell'entità climate relativa di HA. Qualcuno di voi ha avuto lo stesso problema ed ha trovato una soluzione?
Grazie!

**Comment by 50494554524F** [comment]
devi usare homekit controller e tado come backup... questo perché tado viene aggiornata ogni 5 minuti e puoi avere ritardi nel gestire i comandi e/o nel leggere lo stato

**Reply by Topolynx** [reply]
Grazie! Ma quindi devo abbinare Tado ad Homekit prima?

**Reply by 50494554524F** [reply]
è indifferente...

**Reply by Topolynx** [reply]
Grazie!

**Comment by KC-inDomus** [comment]
> Ciao a tutti. Stamattina ho sostituito l'impianto termovalvole/relé Netatmo (rotto dopo tre anni appena di vita) con il sistema Tado, 4 teste + internet hub. Homeassistant ha trovato da sé i componenti suggerendomi due intgrazioni, Tado e Tado internet bridge come integrazione Homekit. Ho configurato la prima, fin qui tutto ok. Per quanto riguarda la seconda, io mi interfaccio con Homekit via Homekit Bridge, ed è HA ad esporre in HomeKit tutti i miei dispositivi. Dovrei abilitare o meno l'integrazione HomeKit Device per Tado internet bridge, piuttosto che esporla ad HomeKit? In seconda analisi, ho notato che se imposto delle temperature da app Tado, non mi vengono sincronizzate nell'entità climate relativa di HA. Qualcuno di voi ha avuto lo stesso problema ed ha trovato una soluzione? Grazie!

usa l'integrazione ufficiale di Home Assistant. quella HomeKit è sì locale ma è molto limitata.

**Reply by Topolynx** [reply]
Grazie @KC-inDomus. Si, ho notato la grossa differenza tra le entità esposte da integrazione Tado VS HomeKit Device. Però c'è da dire che attraverso integrazione Tado i tempi di sincronizzazione Tado Cloud>->Homeassistant sono biblici come aveva risposto @50494554524F, fatto riportato anche [sul forum di HA](https://community.home-assistant.io/t/tado-make-the-tado-server-polling-interval-flexible-instead-of-fixed-5-minutes/286490), mentre da questo punto di vista l'integrazione HomeKit Device è egregia.
Noto invece che una differenza notabile tra le due integrazioni è che gli attributi delle entità create via HomeKit Device riportano una temperatura massima errata (max_temp: 35) mentre la massima temperatura impostabile realmente è 25 gradi, quindi l'attributo va modificato nel customize.yaml per fare match.

A proposito delle Tado, la schedulazione del riscaldamento la trovo più semplice ma anche più "magra" rispetto alle Netatmo. Le Netatmo permettono di configurare dei preset di temperatura da associare alle fasce orarie, mentre le Tado offrono solo i presets "home" e "away".
Sto finendo di mettere a punto un termostato virtuale con [awesome thermostat](https://github.com/dadge/awesome_thermostat) ed un sistema di gestione centrale delle Tado, disabilitabile, con selettore di presets con nomi personalizzati e degli switch per abilitare-disabilitare il controllo da termostato su singola valvola, e le automazioni per il controllo delle teste. Se qualcuno può essere interessato, a pacchetto completato e testato pubblico il codice :)

**Reply by KC-inDomus** [reply]
> Grazie @KC-inDomus. Si, ho notato la grossa differenza tra le entità esposte da integrazione Tado VS HomeKit Device. Però c'è da dire che attraverso integrazione Tado i tempi di sincronizzazione Tado Cloud>->Homeassistant sono biblici come aveva risposto @50494554524F, fatto riportato anche [sul forum di HA](https://community.home-assistant.io/t/tado-make-the-tado-server-polling-interval-flexible-instead-of-fixed-5-minutes/286490), mentre da questo punto di vista l'integrazione HomeKit Device è egregia.


Guarda, onestamente io ho Tado configurato con l'integrazione standard non homekit e francamente i cinque minuti di polling non hanno mai rappresentato un problema - tanto più che i servizi di azionamento sono istantanei. Inoltre le entità che offre mi servono, Homekit è troppo magra.

**Reply by snakuzzo** [reply]
Per quanto possa valere, concordo totalmente con Ale. Il discorso legato al ritardo se imposti qualsiasi cosa da app Tado inoltre, è del tutto normale. Non puoi pretendere che l'integrazione faccia polling una volta al secondo per avere un aggiornamento istantaneo dell'entità su HA. Considerate che io sfrutto le API di tado per effettuare delle mie cose custom (regolazione dinamica offset, etc) e la refresh token l'ho dovuta impostare con un intervallo di 500s. Non ricordo quali siano i limiti in tal senso per la token e/o per le varie chiamate alle API di Tado, ma di sicuro ci sono e con un intervallo troppo "ristretto" si rischia il blocco lato Tado con conseguente non funzionamento dell'integrazione

**Reply by Scialla** [reply]
io uso netatmo integrato via cloud e via homekit, ha lo stesso problema relativo all'aggiornamento. Uso la doppia integrazione proprio per sfruttare sia la maggiore configurabilità dell'integrazione, sia la maggior reattività in locale (che sfrutto in alcune automazioni)

**Reply by Topolynx** [reply]
La vera sòla a usare Homekit Device è che manca il sensore finestra aperta :/
Per il resto - almeno per l'uso che ne faccio io - va bene anche così.
Semmai potesse tornare utile a qualcuno, riporto il mio lavoro a seguire :)
Mi sono creato un termostato con [awesome thermostat](https://github.com/dadge/awesome_thermostat):
```
# configuration.yaml
climate:
  - platform: awesome_thermostat
    name: Generale Tado (HomeKit)
    heater: input_boolean.tado_thermo_switch_homekit # helper commutatore
    target_sensor: sensor.temperatura_media_casa_homekit # definito in template_sensors.yaml
    window_sensor: binary_sensor.finestre_aperte # helper gruppo
    away_temp: 15 # = Sparta
    eco_temp: 17 # = Da Solo Freddo
    home_temp: 20 # Da Solo Comfort 
    comfort_temp: 22 # Sofia
    boost_temp: 25 # = Chiara
    sleep_temp: 25 # Valvole Aperte Estate
    min_temp: 5
    max_temp: 25
    precision: 0.5
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    initial_hvac_mode: 'off'
```
Il sensore finestre aperte è - era - un gruppo di sensori dell'integrazione Tado Cloud.
Il codice del sensore di temperatura media è questo:
```
# template_sensors.yaml
- sensor:
    - name: "Temperatura Media Casa (HomeKit)"
      unit_of_measurement: "C°"
      icon: mdi:home-thermometer
      state: >
        {% set bagno = state_attr("climate.tado_bagno_homekit", "current_temperature") | float %}
        {% set letto = state_attr("climate.tado_letto_homekit", "current_temperature") | float %}
        {% set sofia = state_attr("climate.tado_sofia_homekit", "current_temperature") | float %}
        {% set salotto = state_attr("climate.tado_salotto_homekit", "current_temperature") | float %}
        {{ ((bagno + letto + sofia + salotto) / 4) | round(1, default=0) }}
    - name: "Temperatura Bagno (HomeKit)"
      unit_of_measurement: "C°"
      icon: mdi:home-thermometer
      state: >
        {{state_attr("climate.tado_bagno_homekit", "current_temperature") | float}}
    - name: "Temperatura Camera Da Letto (HomeKit)"
      unit_of_measurement: "C°"
      icon: mdi:home-thermometer
      state: >
        {{state_attr("climate.tado_letto_homekit", "current_temperature") | float}}
    - name: "Temperatura Camera Di Sofia (HomeKit)"
      unit_of_measurement: "C°"
      icon: mdi:home-thermometer
      state: >
        {{state_attr("climate.tado_sofia_homekit", "current_temperature") | float}}
    - name: "Temperatura Salotto (HomeKit)"
      unit_of_measurement: "C°"
      icon: mdi:home-thermometer
      state: >
        {{state_attr("climate.tado_salotto_homekit", "current_temperature") | float}}
```
Ho creato 4 commutatori per abilitare-disabilitare il controllo delle singole teste dal generale:
```
input_boolean.termostato_salotto
input_boolean.termostato_bagno
input_boolean.termostato_letto
input_boolean.termostato_sofia
```
Infine un helper input select con le voci "Off, Sparta, Da Solo Freddo, Da Solo Comfort, Chiara, Sofia, Estate"
```
input_select.tado_presets
```
Ho due automazioni, la prima cambia i presets di awesome thermostat in base alllo input_select qui sopra:
```
alias: "[TADO] [02] Lista Presets Pilota Thermo (HomeKit)"
description: ""
trigger:
  - platform: state
    entity_id:
      - input_select.tado_presets
    to: "Off"
    id: tado-off
  - platform: state
    entity_id:
      - input_select.tado_presets
    to: Sparta
    id: tado-sparta
  - platform: state
    entity_id:
      - input_select.tado_presets
    to: Da Solo Freddo
    id: tado-solo-freddo
  - platform: state
    entity_id:
      - input_select.tado_presets
    to: Da Solo Comfort
    id: tado-solo-comfort
  - platform: state
    entity_id:
      - input_select.tado_presets
    to: Chiara
    id: tado-chiara
  - platform: state
    entity_id:
      - input_select.tado_presets
    to: Sofia
    id: tado-sofia
  - platform: state
    entity_id:
      - input_select.tado_presets
    to: Estate
    id: tado-estate
condition:
  - condition: state
    entity_id: input_boolean.abilitazione_tado_thermo
    state: "on"
    enabled: false
action:
  - parallel:
      - alias: Tado Off
        if:
          - condition: trigger
            id:
              - tado-off
        then:
          - service: climate.turn_off
            data: {}
            target:
              entity_id: climate.generale_tado_homekit
      - alias: Tado Sparta (Away)
        if:
          - condition: trigger
            id:
              - tado-sparta
        then:
          - service: climate.turn_on
            data: {}
            target:
              entity_id: climate.generale_tado_homekit
          - service: climate.set_preset_mode
            data:
              preset_mode: away
            target:
              entity_id: climate.generale_tado_homekit
      - alias: Tado Da Solo Freddo (Eco)
        if:
          - condition: trigger
            id:
              - tado-solo-freddo
        then:
          - service: climate.turn_on
            data: {}
            target:
              entity_id: climate.generale_tado_homekit
          - service: climate.set_preset_mode
            data:
              preset_mode: eco
            target:
              entity_id: climate.generale_tado_homekit
      - alias: Tado Da Solo Comfort (Home)
        if:
          - condition: trigger
            id:
              - tado-solo-comfort
        then:
          - service: climate.turn_on
            data: {}
            target:
              entity_id: climate.generale_tado_homekit
          - service: climate.set_preset_mode
            data:
              preset_mode: home
            target:
              entity_id: climate.generale_tado_homekit
      - alias: Tado Chiara (Boost)
        if:
          - condition: trigger
            id:
              - tado-chiara
        then:
          - service: climate.turn_on
            data: {}
            target:
              entity_id: climate.generale_tado_homekit
          - service: climate.set_preset_mode
            data:
              preset_mode: boost
            target:
              entity_id: climate.generale_tado_homekit
      - alias: Tado Sofia (Comfort)
        if:
          - condition: trigger
            id:
              - tado-sofia
        then:
          - service: climate.turn_on
            data: {}
            target:
              entity_id: climate.generale_tado_homekit
          - service: climate.set_preset_mode
            data:
              preset_mode: comfort
            target:
              entity_id: climate.generale_tado_homekit
      - alias: Tado Estate (Sleep)
        if:
          - condition: trigger
            id:
              - tado-estate
        then:
          - service: climate.turn_on
            data: {}
            target:
              entity_id: climate.generale_tado_homekit
          - service: climate.set_preset_mode
            data:
              preset_mode: sleep
            target:
              entity_id: climate.generale_tado_homekit
mode: single
```
La seconda automazione si occupa di spegnere le teste abilitate al controllo da awesome thermostat, accenderle ed impostarne la temperatura (NOTA: ciascuna testa si comporta _**autonomamente**_, una volta raggiunta la temperatura desiderata va in idle), e di settare la temperatura target in caso venga abilitata al controllo remoto.
```
alias: "[TADO] [03] Thermo Switch Pilota Teste (HomeKit)"
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.generale_tado_homekit
    to: "off"
    id: thermo-off
  - platform: state
    entity_id:
      - climate.generale_tado_homekit
    id: thermo-on
    to: heat
  - platform: state
    entity_id:
      - climate.generale_tado_homekit
    id: thermo-temp-change
    attribute: temperature
  - platform: state
    entity_id:
      - climate.generale_tado_homekit
    id: thermo-preset-change
    attribute: preset_mode
  - platform: state
    entity_id:
      - input_boolean.termostato_bagno
    id: bagno-armato
    to: "on"
  - platform: state
    entity_id:
      - input_boolean.termostato_letto
    id: letto-armato
    to: "on"
  - platform: state
    entity_id:
      - input_boolean.termostato_salotto
    id: salotto-armato
    to: "on"
  - platform: state
    entity_id:
      - input_boolean.termostato_sofia
    id: sofia-armato
    to: "on"
condition:
  - condition: state
    entity_id: input_boolean.abilitazione_tado_thermo
    state: "on"
action:
  - parallel:
      - alias: Spegne Tutte le Teste ARMATE PER REMOTO
        if:
          - condition: trigger
            id:
              - thermo-off
        then:
          - parallel:
              - alias: Spegne Salotto
                if:
                  - condition: state
                    entity_id: input_boolean.termostato_salotto
                    state: "on"
                then:
                  - service: climate.turn_off
                    data: {}
                    target:
                      entity_id: climate.tado_salotto_homekit
              - alias: Spegne Bagno
                if:
                  - condition: state
                    entity_id: input_boolean.termostato_bagno
                    state: "on"
                then:
                  - service: climate.turn_off
                    data: {}
                    target:
                      entity_id: climate.tado_bagno_homekit
              - alias: Spegne Camera da Letto
                if:
                  - condition: state
                    entity_id: input_boolean.termostato_letto
                    state: "on"
                then:
                  - service: climate.turn_off
                    data: {}
                    target:
                      entity_id: climate.tado_letto_homekit
              - alias: Spegne Camera di Sofia
                if:
                  - condition: state
                    entity_id: input_boolean.termostato_sofia
                    state: "on"
                then:
                  - service: climate.turn_off
                    data: {}
                    target:
                      entity_id: climate.tado_sofia_homekit
      - alias: Accende Tutte le Teste ARMATE PER REMOTO
        if:
          - condition: or
            conditions:
              - condition: trigger
                id:
                  - thermo-on
              - condition: trigger
                id:
                  - thermo-temp-change
              - condition: trigger
                id:
                  - thermo-preset-change
        then:
          - parallel:
              - if:
                  - condition: state
                    entity_id: input_boolean.termostato_salotto
                    state: "on"
                then:
                  - alias: Accende Testa
                    service: climate.turn_on
                    data: {}
                    target:
                      entity_id: climate.tado_salotto_homekit
                  - service: climate.set_temperature
                    data:
                      temperature: >-
                        {{state_attr('climate.generale_tado_homekit',
                        'temperature') | float | round(0)}}
                      hvac_mode: heat
                    target:
                      entity_id:
                        - climate.tado_salotto_homekit
                    alias: Imposta Temperatura del Termostato su Testa
                alias: Accende e Imposta Temperatura su Salotto
              - alias: Accende e Imposta Temperatura su Bagno
                if:
                  - condition: state
                    entity_id: input_boolean.termostato_bagno
                    state: "on"
                then:
                  - alias: Accende Testa
                    service: climate.turn_on
                    data: {}
                    target:
                      entity_id: climate.tado_bagno_homekit
                  - service: climate.set_temperature
                    data:
                      temperature: >-
                        {{state_attr('climate.generale_tado_homekit',
                        'temperature') | float | round(0)}}
                      hvac_mode: heat
                    target:
                      entity_id:
                        - climate.tado_bagno_homekit
                    alias: Imposta Temperatura del Termostato su Testa
              - alias: Accende e Imposta Temperatura su Camera da Letto
                if:
                  - condition: state
                    entity_id: input_boolean.termostato_letto
                    state: "on"
                then:
                  - alias: Accende Testa
                    service: climate.turn_on
                    data: {}
                    target:
                      entity_id: climate.tado_letto_homekit
                  - service: climate.set_temperature
                    data:
                      temperature: >-
                        {{state_attr('climate.generale_tado_homekit',
                        'temperature') | float | round(0)}}
                      hvac_mode: heat
                    target:
                      entity_id:
                        - climate.tado_letto_homekit
                    alias: Imposta Temperatura del Termostato su Testa
              - alias: Accende e Imposta Temperatura su Camera di Sofia
                if:
                  - condition: state
                    entity_id: input_boolean.termostato_sofia
                    state: "on"
                then:
                  - alias: Accende Testa
                    service: climate.turn_on
                    data: {}
                    target:
                      entity_id: climate.tado_sofia_homekit
                  - service: climate.set_temperature
                    data:
                      temperature: >-
                        {{state_attr('climate.generale_tado_homekit',
                        'temperature') | float | round(0)}}
                      hvac_mode: heat
                    target:
                      entity_id:
                        - climate.tado_sofia_homekit
                    alias: Imposta Temperatura del Termostato su Testa
      - alias: LA TESTA ARMATA viene settata su termostato
        if:
          - alias: E Thermo abilitato E una testa viene armata
            condition: and
            conditions:
              - alias: Una testa è stata armata
                condition: or
                conditions:
                  - condition: trigger
                    id:
                      - bagno-armato
                  - condition: trigger
                    id:
                      - letto-armato
                  - condition: trigger
                    id:
                      - salotto-armato
                  - condition: trigger
                    id:
                      - sofia-armato
              - condition: state
                entity_id: input_boolean.abilitazione_tado_thermo
                state: "on"
        then:
          - parallel:
              - alias: Setta Salotto
                if:
                  - condition: state
                    entity_id: input_boolean.termostato_salotto
                    state: "on"
                then:
                  - alias: Accende Testa
                    service: climate.turn_on
                    data: {}
                    target:
                      entity_id: climate.tado_salotto_homekit
                    enabled: false
                  - service: climate.set_temperature
                    data:
                      temperature: >-
                        {{state_attr('climate.generale_tado_homekit',
                        'temperature') | float | round(0)}}
                      hvac_mode: heat
                    target:
                      entity_id:
                        - climate.tado_salotto_homekit
                    alias: Imposta Temperatura del Termostato su Testa
              - alias: Setta Bagno
                if:
                  - condition: state
                    entity_id: input_boolean.termostato_bagno
                    state: "on"
                then:
                  - alias: Accende Testa
                    service: climate.turn_on
                    data: {}
                    target:
                      entity_id: climate.tado_bagno_homekit
                    enabled: false
                  - service: climate.set_temperature
                    data:
                      temperature: >-
                        {{state_attr('climate.generale_tado_homekit',
                        'temperature') | float | round(0)}}
                      hvac_mode: heat
                    target:
                      entity_id:
                        - climate.tado_bagno_homekit
                    alias: Imposta Temperatura del Termostato su Testa
              - alias: Setta Camera da Letto
                if:
                  - condition: state
                    entity_id: input_boolean.termostato_letto
                    state: "on"
                then:
                  - alias: Accende Testa
                    service: climate.turn_on
                    data: {}
                    enabled: false
                    target:
                      entity_id: climate.tado_letto_homekit
                  - service: climate.set_temperature
                    data:
                      temperature: >-
                        {{state_attr('climate.generale_tado_homekit',
                        'temperature') | float | round(0)}}
                      hvac_mode: heat
                    target:
                      entity_id:
                        - climate.tado_letto_homekit
                    alias: Imposta Temperatura del Termostato su Testa
              - alias: Setta Camera di Sofia
                if:
                  - condition: state
                    entity_id: input_boolean.termostato_sofia
                    state: "on"
                then:
                  - alias: Accende Testa
                    service: climate.turn_on
                    data: {}
                    enabled: false
                    target:
                      entity_id: climate.tado_sofia_homekit
                  - service: climate.set_temperature
                    data:
                      temperature: >-
                        {{state_attr('climate.generale_tado_homekit',
                        'temperature') | float | round(0)}}
                      hvac_mode: heat
                    target:
                      entity_id:
                        - climate.tado_sofia_homekit
                    alias: Imposta Temperatura del Termostato su Testa
        enabled: true
mode: single
```
Per cronaca, ho evitato di usare nell'automazione lo switch indicato nella configurazione del termostato perché non mi conviene attaccare e staccare tutte le teste allo stesso momento, in quanto il bagno e il salotto sono camere generalmente più fredde delle altre.

**Reply by KC-inDomus** [reply]
ma tutto questo che senso ha?

**Reply by Topolynx** [reply]
Ha senso in quanto Home/Away mi sembrano un po' pochini come presets di temperatura. L'app di Netatmo aveva altri metodi di schedulazione e mi ci trovavo bene, con quelle Tado no. E poi, se voglio mettere la temperatura di casa a una certa temperatura, perché dovrei impostarla X volte di fila per ogni termosifone? C'è da dire pure che io un termostato fisicamente in casa non ce l'ho, ecco perché me ne sono fatto uno virtuale.

**Comment by Ector73** [comment]
Buongiorno a tutti,
mi aggancio a questa discussione per sottoporvi una questione sempre relativa al sistema tado:
Ho creato uno script per impostare lo stato dell'entità relativa a "HOME -AWAY", da utilizzare poi in un automazione.
Lo script funziona, ma non viene passato all'APP in cloud, con il risultato che se ad esempio imposto lo stato a HOME (su cloud è AWAY) non solo non viene cambiato nel cloud ma dopo un pò di tempo anche su HA torna lo stato AWAY.
Le altre entità (temperatura, etc.) anche se con un pò di ritardo le cambia senza problemi, questa no.
...i più sospettosi potrebbero pensare che TADO voglia spingere a fare l'abbonamento? 
O sbaglio qualcosa?
PS: su HA utilizzo l'integrazione ufficiale TADO
Vi aggiungo per completezza uno degli script che utilizzo:

```
service: python_script.set_state
data_template:
  entity_id: sensor.casa_tado_mode
  state: HOME
```
