### DISCUSSION TITLE
Impostare valore relativo di temperatura climatizzatore

### DISCUSSION THREAD

**Discussion by array81** [indomus/forum#2733] [HUB: Home Assistant]
Ho la necessità in un'automazione di impostare il valore di temperatura di un termostato TADO.
Al momento utilizzo il servizio "Climatizzatore: Imposta la temperatura" su detto termostato e vado a impostare un valore assoluto di temperatura. Ad esempio 18 gradi.
Questo però non mi soddisfa a pieno nel senso che io vorrei settare la temperatura un grado di più di quella rilevata dal termostato nel momento in cui l'automazione viene eseguita. Ad esempio se il termostato rileva 17 gradi voglio settare la temperatura a 18 gradi ma se rileva 18 gradi voglio settare la temperatura a 19 e così via.

Qualche consiglio?

**Comment by 50494554524F** [comment]
dipende da come hai scritto l'automazione, rischieresti un loop infinito... postala

**Comment by array81** [comment]
Questa è l'automazione:

```
alias: Gestione temperatura stufa
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.temp_mandata
    above: 74.9
    id: alarm_low
  - platform: numeric_state
    entity_id:
      - sensor.temp_mandata
    above: 77.5
    id: alarm_high
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: alarm_low
          - condition: time
            after: "20:00:00"
            before: "05:00:00"
        sequence:
          - service: climate.set_temperature
            data:
              temperature: 18.5
            target:
              entity_id: climate.termostato_mansarda_homekit
      - conditions:
          - condition: trigger
            id: alarm_low
          - condition: time
            after: "05:00:00"
            before: "06:30:00"
        sequence:
          - service: climate.set_temperature
            data:
              temperature: 18
            target:
              entity_id: climate.termostato_piano_terra_homekit
      - conditions:
          - condition: trigger
            id: alarm_high
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: switch.valvola_garage_relay
mode: single

```
