### DISCUSSION TITLE
Problema Sensore porta SONOFF 	SNZB-04

### DISCUSSION THREAD

**Discussion by barbatrukko** [indomus/forum#2737] [HUB: Home Assistant]
Ho connesso un sensore per porte sonoff SNZB-04 tramite Zigbee2MQTT, ed ho creato alcune automazioni che mi dicono mi mandano un messaggio su telegram quando la porta si apre, quando si chiude o quando sta aperta per più di 1 minuto...
Ricevi regolarmente dei messaggio di apertura porta seguiti da messaggi di chiusura porta..... tuttavia spesso in momento in cui la porta non viene aperta, ricevo messaggio di "porta chiusa" in momenti in cui nessuno ha aperto o chiusa la porta. Durante la notte ad esempio ho ricevuto 4-5 messaggi di "porta chiusa"
Non capisco, capirei più un falso positivo di porta aperta (magari il vento fa muovere la porta e scatta il sensore) ma di porta chiusa?
oppure la sequenza aperto/chiusa è cosi veloce che il secondo evento annulla il primo e parte 1 solo messaggio?

```
alias: Allarme Porta Aperta
description: ""
trigger:
  - type: opened
    platform: device
    device_id: XXXXXXXXXXXXXXX
    entity_id: YYYYYYYYYYYYY
    domain: binary_sensor
condition: []
action:
  - service: notify.barbatrukko
    data:
      title: "*Porta casa Aperta*"
      message: La porta di casa è Aperta
mode: single

```
