### DISCUSSION TITLE
Un aiutino per uno script...

### DISCUSSION THREAD

**Discussion by roma777roma** [indomus/forum#274] [HUB: Home Assistant]
Ciao a tutti, mi aiutereste a fare uno script?
Attualmente ho uno script per mettere una sorgente al denon avr in base a dove clicco tramite una variabile:

```
denon_on:
  sequence:
  - entity_id: media_player.denon
    service: media_player.turn_on
  - entity_id: media_player.denon
    data:
      volume_level: '0.4'
    service: media_player.volume_set
  - entity_id: media_player.denon
    service: media_player.select_source
    data_template:
      source: "{% if is_state('var.var_denon_source', 'game') %}\n  Game\n{% elif is_state('var.var_denon_source',\
        \ 'dvd') %}\n  DVD\n{% elif is_state('var.var_denon_source', 'aux') %}\n  AUX\n\
        {% elif is_state('var.var_denon_source', 'bluetooth') %}\n  Bluetooth\n{% endif %}\n"
  mode: single
```

Tutto funziona però quando cambio la sorgente col telecomando ovviamente non se ne accorge nessuno per cui volevo fare un'automazione che intercetta il cambio e richiama uno script "inverso". L'automazione ok funziona ma non ho proprio idea di come fare lo script, cioè, in base alla sorgente che rileva mi va a settare la var.var_denon_source.

come si setta una variabile lo so:
```
  - entity_id: var.var_denon
    data:
      value: 'on'
    service: var.set
```
come si setta la sorgente anche (vedi script sopra) ma come si prende la sorgente per poi settarci la variabile no....

Qualcuno può aiutarmi? :-)

**Comment by roma777roma** [comment]
trovato:

```
  - entity_id: var.var_denon_source
    data:
      value: "{% if is_state_attr('media_player.denon', 'source', 'Game') %}\n  Game\n{% elif is_state_attr('media_player.denon', 'source', 'Media Player') %}\n  Media Player\n{% elif is_state_attr('media_player.denon', 'source', 'AUX') %}\n  AUX\n\
        {% elif is_state_attr('media_player.denon', 'source', 'HEOS Music') %}\n  Bluetooth\n{% endif %}\n"
    service: var.set
```
    
    Grazie lo stesso.
