### DISCUSSION TITLE
Prese WeMo "emulate"

### DISCUSSION THREAD

**Discussion by cldparisi** [indomus/forum#2740] [HUB: Home Assistant]
Sul mio Magic Mirror sono emulate delle prese WeMo, queste vengono viste dall'App Alexa e riesco a gestirle tranquillamente, ho provato ad aggiungerle su home Assistant con l'interazione ufficiale Wemo (https://www.home-assistant.io/integrations/wemo) ma non riesco a vederle, nella documentazione c'è una sessione per parla proprio dei "Emuleted devices" e spiega come inserirli.
La sezione del configuration.yaml relativo è questa:

```
wemo:
  discovery: false
  static:
    - 192.168.111.128:11101
    - 192.168.111.128:11102
    - 192.168.111.128:11103
    - 192.168.111.128:11104
    - 192.168.111.128:11105
    - 192.168.111.128:11106
    - 192.168.111.128:11107
    - 192.168.111.128:11108
   
```

Ma HA non riesce a rilevarle.

Avete suggerimenti su come provare?

Grazie
