### DISCUSSION TITLE
Sensori temperatura aqara

### DISCUSSION THREAD

**Discussion by alenyc81** [indomus/forum#2746] [HUB: Home Assistant]
Ciao, qualcuno di voi utilizza questi sensori?

Vorrei sapere se è possibile impostare il tempo dell'interrogazione dello stato sensore da parte di zigbee... Spesso vedo come ultimo aggiornamento stato anche mezz'ora... Avendo collegato questi sensori all'automazione riscaldamento in casa, spesso e volentieri mi trovo con il riscaldamento spento perché ,le condizioni di temp minima per fer partire il riscaldamento ci sono, ma i sensori non vengono interrogati con frequenza...

**Comment by Scialla** [comment]
Ti ho risposto di là, non è che i sensori "vengano interrogati", funziona proprio al contrario, sono i sensori a decidere quando inviare il valore e, di norma, avviene quando il valore cambia, ovvero quando la temperatura (o l'umidità) variano
Io ne ho diversi e funzionano proprio così e non ho alcun problema con le automazioni basate si di essi
Non puoi impostare l'invio quando vuoi tu sui sensori a batteria, puoi farlo su quelli alimentati

**Comment by alenyc81** [comment]
Questa è l'automazione fatta... Quanto una condizione passa, devo aspettare il primo risveglio del sensore per fare partire il riscaldamento... Se si risveglia dopo un ora, non è comodissimo


```
alias: accensione stufa
description: ""
trigger:
  - type: temperature
    platform: device
    device_id: 2208211b148e4b72313f4cc7ccf16639
    entity_id: 0c27134bf5a4588f0a8be6af78a03da2
    domain: sensor
    below: 20.5
condition:
  - condition: or
    conditions:
      - condition: time
        after: "03:00:00"
        before: "05:00:00"
        weekday:
          - sun
          - sat
          - fri
          - thu
          - wed
          - tue
          - mon
      - condition: time
        after: "09:00:00"
        before: "11:00:00"
        weekday:
          - sat
          - sun
          - fri
          - thu
          - wed
          - tue
          - mon
      - condition: time
        before: "16:30:00"
        after: "14:00:00"
        weekday:
          - sat
          - sun
          - fri
          - thu
          - wed
          - tue
          - mon
      - condition: time
        after: "19:00:00"
        before: "21:00:00"
        weekday:
          - sun
          - sat
          - fri
          - wed
          - tue
          - mon
          - thu
action:
  - device_id: 25c81032ef5f936f3d024264e013d704
    domain: climate
    entity_id: 7ea2fb914f048de51546dbe51c58755f
    type: set_hvac_mode
    hvac_mode: heat
  - device_id: ecf648019d744e6d634f36649f4b942f
    domain: mobile_app
    type: notify
    message: "Stufa accesa "
  - device_id: 30c97e144cb0c02e167d09223c4ead66
    domain: mobile_app
    type: notify
    message: "Stufa accesa "
mode: single
```

**Reply by KC-inDomus** [reply]
mammamia che brutto quel trigger

**Comment by alenyc81** [comment]
Perché? 
L'ho fatto nella schermata delle automazioni...
So che ho ancora da imparare 🤣🤣

Ma brutto perché ci sono errori che ne impediscono il corretto funzionamento?

**Reply by Scialla** [reply]
Mi permetto di evidenziarti alcuni problemi in come hai postato:
- non hai usato il markdown ed è difficile riuscire a "leggere" cosa hai postato
-  non aprire nuovi thread quando rispondi ma continua in quello precedente
- cerca di non usare la GUI per fare le automazioni perché è di difficile lettura poi nel codice

così come hai scritto il trigger lo sai che l'automazione parte solo quando passa da un valore precededente uguale o superiore a 20,5 ad un valore inferiore (poi controlla le condition per proseguire)
Se il valore quindi è già inferiore non parte l'automazione, così come se il valore precedente è sconosciuto o unavailable.

Premesso ciò, per dire che non comunica, dovresti avere altro termometro che ti dice che il valore è già inferiore e che lui invece ha ancora un valore superiore.

Ribadisco che, al variare del valore, il sensore comunica il nuovo stato. Se non lo fà hai errori di comunicazione.

**Reply by alenyc81** [reply]
In effetti è come dici,si è aggiornato ora lo stato del sensore,la temperatura è inferiore a quella prefissata e il riscaldamento non è partito... 

Però non capisco... Se l'automazione parte dal comando del sensore, dove è impostata la temp inferiore a 20,5 gradi, a prescindere dalle condizioni di fascia oraria che ho messo,qualdo il sensore si aggiorna e misura la temp inferiore a quella impostata ,non dovrebbe partire l'automazione?
Cortesemente, riesci a dirmi come impostare questa automazione,di modo da coprire come fare le altre? Purtroppo sto usando home assistant solo da un paio di mesi e, non avendo nozioni di base, è tutto home made... Alla scoperta...

P.s. sto cercando di capire come usare il markdown per correggere il post sopra

**Reply by Scialla** [reply]
io ti consiglio di usare gli strumenti per sviluppatori e fare delle prove; da lì puoi forzare lo stato del sensore e vedere se l'automazione triggera e se non triggera vuol dire che hai sbagliato qualcosa
Da impostazioni, automazioni, andando sui 3 pallini e poi su tracce puoi vedere se e quando l'automazione ha triggerato e come ha proceduto
Verifica bene le condizioni, se deve funzionare tutti i giorni della settimana non è assolutamente necessario indicarli, è inutile e rende meno comprensibile la lettura
Inoltre nella tua automazione prevedi solo l'accensione e mai lo spegnimento
Per il markdown devi usare tre backtick (accento grave) prima e dopo il codice

parti da un trigger comprensibile e fai qualche prova forzando gli stati dagli strumenti sviluppatore

```
- platform: numeric_state
  entity_id: sensor.nome_del_tuo_sensore
  belowe: 20.5
```
vedi come rimane pulito e comprensibile?
stessa cosa fai per le action, rimane tutto più leggibile

**Reply by alenyc81** [reply]
Adesso ci provo...

Per lo spegnimento ho fatto un'altra automazione solo X lo spegnimento al superamento di una certa temperatura... Quello so che funziona perché ho già provato ieri..

P.s. ho provato a guardare su tracce ma non riesco a capire come leggere il tutto..
Di sicuro non ha funzionato perché il riscaldamento l'ho dovuto accendere in manuale..

Non c'è un modo più semplice e intuitivo per fare un automazione per come mi serve ,senza incasinarsi?

In pratica l'automazione di accensione funziona tutti i giorni della settimana, dalle 3 alle 5, dalle 9 alle 11 ,dalle 14 alle 16.30 e dalle 19 alle 21 se la temperatura scende sotto i 20,5 gradi.. per poi spegnere ogni volta che raggiunge i 22.5

**Reply by Scialla** [reply]
se poi vuoi integrare anche lo spegnimento sopra soglia usi due trigger nella stessa automazione, non c'è bisogno di due automazioni:
```
  trigger:
    - platform: numeric_state
      entity_id: sensor.nome del tuo sensore
      above: 22.5
    - platform: numeric_state
      entity_id: sensor.sensor.nome del tuo sensore
      below: 20.5
  action:
    - service: >
        {% if trigger.to_state.state | float > 22.5 %}
          switch.turn_off
        {% else %}
          switch.turn_on
        {% endif %}
      data:
        entity_id: switch.nome del tuo switch
```

ovviamente devi aggiungerci le tue condition...

Però non fare copia e incolla, cerca di capire, magari cercando online cosa non ti quadra, per imparare a farti da solo le tue automazioni e, soprattutto, senza la GUI visto che, quando vai a vedere cosa ha tirato fuori, diventa incomprensibile

**Reply by alenyc81** [reply]
Allora, so che mi hai detto di non fare copia e incolla, ma purtroppo parto da zero... Dovrei avere un riferimento "comprensibile per capire cosa sto guardando...

Ho provato a copiare la tua automazione,inserendo id sensore e l'editor visuale con la gui mi ha tirato fuori che

Quando il sensore è inferiore a 20,5 gradi
Quando il sensore è superiore a 22,5 gradi

Attivazione
Qua l'editor visuale non è compatibile

In pratica deve attivare e disattivare il riscaldamento

Però come fa in una sola automazione a capire che deve il riclscaldamento deve attivarsi se il sensore legge meno di 20,5 e spegnersi al superamento dei 22.5?

Lascio da parte le condizioni che al momento ho già abbastanza problemi..

**Reply by Scialla** [reply]
- Quando la temperatura passa da 20,5 gradi (o superiore) a una temperatura inferiore ai 20,5, l'automazione scatta, ma anche:
- Quando la temperatura passa da 22,5 gradi (o inferiore) a una temperatura superiore ai 22,5, l'automazione scatta
nella Action poi va a verificare quale sia il valore che l'ha fatta scattare (`trigger.to_state.state`) lo trasforma in numero nel caso fosse una stringa (float) e controlla se il valore che ha fatto scattare il trigger è superiore a 22,5. Se è superiore a 22,5 allora spegne, altrimenti accende (il trigger scatta solo in due occasioni, se superiore a 22,5 o se inferiore a 20,5 quindi, se nel controllo non è vero che è superiore a 22,5 sarà sicuramente scattato per l'altro motivo, quindi inferiore a 20,5).
l'entità da da far spegnere o accendere sarà ovviamente la stessa..
Leggiti i corsi su inDomus per imparare a fare le automazioni, sono utilissimi!!!!

**Reply by KC-inDomus** [reply]
https://indomus.it/formazione/esercizi-di-domotica-su-home-assistant-2-definire-diversi-trigger-per-innescare-automazioni/

**Reply by alenyc81** [reply]
Mi conviene si leggere qualcosa perché ho troppa confusione... 

Ad esempio avevo fatto un automazione per accendere e una distinta X spegnere perché in ognuna, con l'interfaccia grafica, potevo selezionare il cambio di stato dell' entità,da acceso a spento o viceversa....

**Reply by alenyc81** [reply]
Domanda stupida... Se il sensore si aggiorna solo quando legge una variazione di temperatura e come adesso, vedo il sensore che è da 2 ore all'ultima lettura, come fa a dare limput al riscaldamento X partire? L'automazione tiene conto dell'ultimo stato detto che corrisponde alla temp utile per l'accensione, parte lo stesso?
Non so se mi sono spiegato.

Cmq quell'automazione li la potrei anche copiare dentro con file editor giusto per vedere come e se mi fa partire la stufa?

**Reply by Scialla** [reply]
il trigger scatta quando si avvera la condizione, ovvero quando la temperatura scende (o sale) sotto (o sopra) le soglie indicate e NON quando si trova già nella condizione indicata.

**Comment by alenyc81** [comment]
scusate, vorrei postarvi l'automazione per vedere se ci sono problemi ma non ho capito come usare il markdown

in pratica copio il codice e lo incollo qui usando 3 virgolette sopra e 3 sotto?

**Reply by snakuzzo** [reply]
https://github.com/indomus/forum/discussions/1311

**Reply by snakuzzo** [reply]
... non sono "virgolette" ma backtick

**Comment by alenyc81** [comment]
ecco qua...
ho provato a premere su avvia e in effetti la stufa si è accesa....
comunque penso che il problema di far partire la stufa in automatico con l'automazione dipende dal trigger del sensore....

```
alias: prova
description: ""
trigger:
  - type: temperature
    platform: device
    device_id: 2208211b148e4b72313f4cc7ccf16639
    entity_id: 0c27134bf5a4588f0a8be6af78a03da2
    domain: sensor
    above: 22.7
    below: 20.5
condition: []
action:
  - choose:
      - conditions:
          - type: is_temperature
            condition: device
            device_id: 2208211b148e4b72313f4cc7ccf16639
            entity_id: 0c27134bf5a4588f0a8be6af78a03da2
            domain: sensor
            below: 20.5
        sequence:
          - device_id: 25c81032ef5f936f3d024264e013d704
            domain: climate
            entity_id: 7ea2fb914f048de51546dbe51c58755f
            type: set_hvac_mode
            hvac_mode: heat
      - conditions:
          - type: is_temperature
            condition: device
            device_id: 2208211b148e4b72313f4cc7ccf16639
            entity_id: 0c27134bf5a4588f0a8be6af78a03da2
            domain: sensor
            above: 22.7
        sequence:
          - device_id: 25c81032ef5f936f3d024264e013d704
            domain: climate
            entity_id: 7ea2fb914f048de51546dbe51c58755f
            type: set_hvac_mode
            hvac_mode: "off"
mode: single
```

**Reply by snakuzzo** [reply]
Non ho letto tutta la discussione precedente, ma...
innanzi tutto butta questa automazione e riscrivila con le entità, non con i device...perché così è inguardabile.
Quanto al discorso del trigger, per come l'hai scritta, questa automazione scatta in automatico quando passa  da fuori il range 20.5 - 22.7 gradi a dentro il range 20.5 -22.7 ... ora però la mia domanda è... perché stai facendo in questo modo ?

A mio avviso, creare un'automazione del genere per gestire un climate, è totalmente sbagliato e va contro ogni logica.

Il climate è già di suo la soluzione...non servono automazioni

**EDIT:** Se i sensori non rilevano una temperatura diversa, vuol dire che non c'è stata una variazione tale da comunicare il cambio di temperatura. Se la temperatura varia tanto e i sensori non espongono la corretta temperatura, il problema non si risolve facendo un'automazione assurda, ma magari capendo perché i sensori non funzionano correttamente.

Altra nota sul fatto di far scattare l'automazione a mano. Se la esegui a mano, non viene preso in considerazione né il trigger né le condition...viene eseguito solo quello che è presente nella action

**Reply by alenyc81** [reply]
Allora, a me servirebbe un automazione che, dalle 3:00 alle 5:00 , dalle 09:00 alle 11:00 ,dalle 14:00 alle 16:30 e dalle 19:00 alle 21:00( al momento non ho messo queste fasce orarie), se la temperatura scende sotto i 20,5 gradi,la stufa si accende e si spegne al superamento dei 22,7 gradi.

Se hai suggerimenti, dimmi pure che magari mi semplificano il tutto

**Reply by snakuzzo** [reply]
ora provo a scrivertela

**Reply by alenyc81** [reply]
Per il discorso dei sensori, la temperatura la rilevano correttamente... L'automazione l'ho creata ora e il sensore era sotto i 20,5 gradi... Appena creata non è partita la stufa in automatico... Quindi presumo che finché il sensore non non si aggiorna di stato, non può fare partire l'automatismo. Però, se fosse così, se il sensore non riveva più una differenza di temperatura da fare aggiornare il suo stato(magari perché la temperatura resta stabile), vuol dire che l'automazione non partirà mai... Servirebbe usare l'ultimo stato temp letto dal sensore ..

Per dire, di notte scende la temperatura e l'ultima lettura è di 18 gradi. Se alla 3 di notte il sensore non si è più aggiornato, l'automazione prende in considerazione l'ultima lettura temperatura letta dal sensore e, se sotto i 20,5 gradi, l'automazione parte.

**Reply by snakuzzo** [reply]
dammi qualche minuto

**Reply by snakuzzo** [reply]
Allora...
questo un piccolo package dove mi sono appoggiato ad un'entità di tipo [schedule](https://www.home-assistant.io/integrations/schedule/) (che permette proprio di gestire queste casistiche) e ad un'entità climate ([generic thermostat](https://www.home-assistant.io/integrations/generic_thermostat/)) ... il tutto è **testato e funzionante** (unica cosa ho inserito le chiamate a due service diversi per accendere il climate, altrimenti non si accendeva...ma non ho indagato più di tanto)..
Quello che puoi fare tu è definire bene tutte le proprietà del climate generic thermostat (se l'hai utilizzato).

```yaml
schedule:

  stufa:
    name: "stufa"
    monday:
      - from: "03:00:00"
        to: "05:00:00"
      - from: "09:00:00"
        to: "11:00:00"
      - from: "14:00:00"
        to: "16:30:00"
      - from: "19:00:00"
        to: "21:00:00"
    tuesday:
      - from: "03:00:00"
        to: "05:00:00"
      - from: "09:00:00"
        to: "11:00:00"
      - from: "14:00:00"
        to: "16:30:00"
      - from: "19:00:00"
        to: "21:00:00"
    wednesday:
      - from: "03:00:00"
        to: "05:00:00"
      - from: "09:00:00"
        to: "11:00:00"
      - from: "14:00:00"
        to: "16:30:00"
      - from: "19:00:00"
        to: "21:00:00"
    thursday:
      - from: "03:00:00"
        to: "05:00:00"
      - from: "09:00:00"
        to: "11:00:00"
      - from: "14:00:00"
        to: "16:30:00"
      - from: "19:00:00"
        to: "21:00:00"
    friday:
      - from: "03:00:00"
        to: "05:00:00"
      - from: "09:00:00"
        to: "11:00:00"
      - from: "14:00:00"
        to: "16:30:00"
      - from: "19:00:00"
        to: "21:00:00"
    saturday:
      - from: "03:00:00"
        to: "05:00:00"
      - from: "09:00:00"
        to: "11:00:00"
      - from: "14:00:00"
        to: "16:30:00"
      - from: "19:00:00"
        to: "21:00:00"
    sunday:
      - from: "03:00:00"
        to: "05:00:00"
      - from: "09:00:00"
        to: "11:00:00"
      - from: "14:00:00"
        to: "16:30:00"
      - from: "19:00:00"
        to: "21:00:00"

automation:

- id: stufa_schedule
  alias: stufa_schedule
  trigger:
    - id: schedule_on
      platform: state
      entity_id: schedule.stufa
      to: 'on'
    - id: schedule_off
      platform: state
      entity_id: schedule.stufa
      to: 'off'      
  action:
    - choose:
      - conditions:
          - condition: trigger
            id: 'schedule_on'
        sequence:
        - service: climate.set_temperature
          data:
            entity_id: climate.riscaldamento
            temperature: 22.7
            hvac_mode: heat
        - service: climate.turn_on
          data:
            entity_id: climate.riscaldamento
      - conditions:
          - condition: trigger
            id: 'schedule_off'
        sequence:
          - service: climate.turn_off
            data:
              entity_id: climate.riscaldamento
```

**Reply by alenyc81** [reply]
Intanto ti ringrazio per il tempo dedicato a fare tutto ciò... Da tutta la discussione avrai ben capito che sono nuovo di tutte queste cose e sto cercando di imparare man mano... Giusto X capire, se volessi provare questa automazione su home assistant, come procedo? Profumo non basti fare un copia e incolla...

Come mi muovo? Devo inserire qualcosa in questo codice?

**Reply by snakuzzo** [reply]
Se vuoi creare un package (così come ho fatto io), studia prima cosa sono [QUI](https://indomus.it/formazione/i-package-di-home-assistant-cosa-sono-e-come-si-installano/).
Poi...una volta configurato il tutto, crei il file del tuo package e dovrai solo adeguare i nomi delle entità (quelle scritte qui sono le mie)

**Comment by alenyc81** [comment]
cmq ho avuto conferma che la mia automazione non funziona nemmeno per spegnere la stufa al superamento della temp impostata.... che caos, alla peggio torno a usare il crono mode della stufa, anche se non viene comandato da home assistant

**Reply by snakuzzo** [reply]
ora però che c'entra la tua automazione ?

**Reply by alenyc81** [reply]
Quella postata prima, dove dicevo che non faceva partire la stufa, ho avuto conferma che nemmeno la spegne.

Quello che hai creato te non l'ho ancora messa perché non riesco a usare il PC ora... Da telefono è un caos usare editor file.

Ma domanda: visto che si possono anche creare automazioni con l'interfaccia grafica, non esiste un modo per crearla così e farla funzionare? Ho altre automazioni fatte così e funzionano tutte al primo colpo... Con i sensori temp è un casino invece... O che sbaglio a impostare io .

**Reply by Scialla** [reply]
Tu sbagli a leggere una cosa e farne un'altra.
Ti ho già ripetuto che se metti un trigger quando scende sotto una certa temperatura, il trigger scatta quando da un valore più alto passa a un valore più basso della temperatura impostata. Se decidi di fare partire l'automazione ora e la temperatura è già più bassa di quella impostata, il trigger non scatta.
Continuo a ripetertelo e tu continui a parlare di lettura del valore non capendo questo concetto.
Se non lo capisci, continuerai a fare automazioni sbagliate.
Cerca di recepire il concetto che, quando la condizione del trigger si avvera (e solo nel momento in cui si avvera ovvero quando si è avverata poi non è che continua a scattare) scatta il trigger e parte l'automazione.
Io non so più come ripetertelo...

**Comment by alenyc81** [comment]
Ho capito che sbaglio... Purtroppo non sono cose facilmente comprensibili al primo compo se si parte da zero.
Come trigger, al posto del sensore temp, non posso usare il tempo? Ovvero, come trigger, un lasso ti tempo, da tot ora a tot ora, come condizione se la temperatura è sotto tot, azione accendi stufa e spegni al raggiungimento di una certa temperatura?
Ammetto che faccio fatica a usare questi sensori. Ripeto, con altre automazioni X luci ecc,nessun problema

**Reply by Scialla** [reply]
La cosa migliore che puoi fare è usare quella che ti ha postato Diego,ovviamente cambiando le sue entità con le tue.
Dovresti però cercare di capirla...
Devi studiare un pochino..

**Reply by alenyc81** [reply]
Trovato il perché e probabilmente è quello che hai cercato di spiegarmi... 
Lo sbaglio erano le soglie temp sul trigger... 

Per accensione impostavo 20,5.... Ora ho messo un trigger temp sup a 1 e inferiore a 20,5. 
E un altro con temp minore di 30 e max di 22,7

Come azione ho messo scelta tra 2 opzioni.
Una per l'accensione a condizione che la temp attuale sia minore di 20,5( e adesso funziona perché il trigger è tra 1 grado e 22,5)

L'altro opzione è per lo spegnimento a condizione che la tem attuale sia sup a 22,7

```
alias: "Nuova automazioneproooova "
description: ""
trigger:
  - type: temperature
    platform: device
    device_id: 2208211b148e4b72313f4cc7ccf16639
    entity_id: 0c27134bf5a4588f0a8be6af78a03da2
    domain: sensor
    above: 1
    below: 21.3
  - type: temperature
    platform: device
    device_id: 2208211b148e4b72313f4cc7ccf16639
    entity_id: 0c27134bf5a4588f0a8be6af78a03da2
    domain: sensor
    above: 22.7
    below: 30
  - platform: time
    at: "05:00:00"
  - platform: time
    at: "11:00:00"
  - platform: time
    at: "16:30:00"
  - platform: time
    at: "21:00:00"
condition:
  - condition: time
    after: "03:00:00"
    before: "05:00:00"
    enabled: false
  - condition: time
    after: "09:00:00"
    before: "11:00:00"
    enabled: false
  - condition: time
    after: "14:00:00"
    before: "16:30:00"
    enabled: false
  - condition: time
    after: "19:00:00"
    before: "21:00:00"
    enabled: false
action:
  - choose:
      - conditions:
          - type: is_temperature
            condition: device
            device_id: 2208211b148e4b72313f4cc7ccf16639
            entity_id: 0c27134bf5a4588f0a8be6af78a03da2
            domain: sensor
            below: 21.6
        sequence:
          - device_id: 25c81032ef5f936f3d024264e013d704
            domain: climate
            entity_id: 7ea2fb914f048de51546dbe51c58755f
            type: set_hvac_mode
            hvac_mode: heat
      - conditions:
          - type: is_temperature
            condition: device
            device_id: 2208211b148e4b72313f4cc7ccf16639
            entity_id: 0c27134bf5a4588f0a8be6af78a03da2
            domain: sensor
            above: 22.7
        sequence:
          - device_id: 25c81032ef5f936f3d024264e013d704
            domain: climate
            entity_id: 7ea2fb914f048de51546dbe51c58755f
            type: set_hvac_mode
            hvac_mode: "off"
mode: single
```
