### DISCUSSION TITLE
Riavvii continui HA e disconnessione dispositivi

### DISCUSSION THREAD

**Discussion by faustozago** [indomus/forum#2754] [HUB: Home Assistant]
Cia a tutti,
ho HASSIO installato su RASPB3+ , con sia sia dispositivi WIFi che dispositivi zigbee (Z2M con sonoff dongle P).
Dai registri di LOG dei singoli dispositivi, da molto tempo mi accorgo che piu' volte al giorno i dispositivi vanno tutti (e tutti alla stessa ora) in modalita' "è diventato sconosciuto" oppure "è diventato non disponibile" .
Poi ,nel giro di qualche minuto, tornano disponibili e connessi.
Questa notte è successo 3 volte, ho guardato nei registro di SUPERVISOR , e in minuto prima del problema ho trovato questo:

SUPERVISOR
_23-12-07 07:45:48 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.34.0-1
23-12-07 07:45:49 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
23-12-07 07:45:50 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]_

La riga ERROR.... viene ripetuta 9 volte consecutive poi ci sono queste righe:

_23-12-07 07:47:34 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
23-12-07 07:47:53 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-12-07 07:52:37 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)_

Non so se sia collegato a questo problema m a volte quando sono connesso alla pagina di HASSIO, mi appare la scritta "CONNESSIONE PERSA" , e per circa 1 minuto devo attendere che si riconnetta.

Qualcuno puo' aiutarmi con questi problemi?
Grazie

**Comment by snakuzzo** [comment]
Non c'entra nulla la connessione persa ad HA OS con l'errore dell'addon zigbee2mqtt.

Per quanto riguarda zigbee2mqtt, hai sicuramente sbagliato la configurazione e l'addon si riavvia di continuo proprio perché trova quell'errore.
Quanto al supervisor, quell'errore probabilmente è dovuto dal fatto che è cambiato l'IP di qualche container.

Prova a riavviare proprio il server e vedi se si risolve almeno questa cosa.

**Reply by faustozago** [reply]
Questo errore ce l'ho da tempo , ho fatto vari riavvii del raspberry, ma dopo si presenta di nuovo.
Fra qualche giorno togliero' l'addon nativa Z2M dal raspberry dove ho HASSIO,  e la mettero' in una VM di un MINIPC . Disinstallero' quella del raspberry.
Pensi che il problema potrebbe risolversi da solo?

Ora ho gia' un'altra istanza Z2M su un'altra VM del minipc ,  connessa a Mosquitto broker che si trova nel rasbberry di HA ,  pensi che questa possa creare problemi?

Grazie

**Reply by snakuzzo** [reply]
Ma cosa stai combinando ?
Una VM solo per zigbee2mqtt ? Quale sarebbe il senso ?
Ma poi scusami eh, secondo te i problemi si risolvono da soli ? Hai un semplice errore in configurazione sul quale dovresti indagare, la soluzione non è mai reinstallare.

**Reply by faustozago** [reply]
Mi servono 2 istanze Z2M , una è sul rasp.PI3+. addon ufficiale di  HASSIO , una l'avevo da sola un un'altro rasp.PI2, installata su raspbian.

Ora vorrei eliminare i 2 raspberry e mettere tutto nel MINIPC.
L'istanza Z2M che avevo da sola nel raspberry PI2  l'ho gia' messa su una VM del minipc
Fra poco passero' anche HASSIO su VM del minipc , il dubbio è se lasciare Z2M su HASSIO oppure su VM a parte .

_Quello che scrivi tu' (un semplice errore in configurazione) è giustissimo, ma dipende anche dalle competenze di chi deve risolverlo...nel mio caso è non è tanto semplice...._


Provo a vedere se trovo un riscontro a  "172.30.33.3:8099" ?

**Reply by snakuzzo** [reply]
Hai riavviato l'host come ti dicevo prima ?
Sul dove/come mettere più sitanze di Z2M non metto bocca. Devi sapere tu, in base alle tue esigenze, cosa fare. Avere Z2M come addon o come container docker o come applicazione installata direttamente sull'OS, non fa alcuna differenza. L'applicazione è sempre la stessa. Inoltre, non ti serve una VM a parte per avere una seconda istanza di Z2M. Puoi utilizzare anche lo stesso host. Se usi HA OS e l'addon "SSH & Web Terminal" abilitando la modalità avanzata, hai praticamente pieno accesso all'OS e hai anche la possibilità di utilizzare docker creando tutti i container che ti pare e, di conseguenza, anche tirare su uno o più container di zigbee2mqtt.

**Reply by faustozago** [reply]
Ho visto l'addon "SSh & Web Terminal  " ,molto interessante, ma va oltre le mie competenze....
La seconda istanza Z2M mi serve per una rete zigbee (piccolo antifurto) tutta sotto UPS  ,anche i router , in modo che i dispositivi a batteria non si colleghino a quelli a 230V dell'altra rete; Questo perche' quando salta la corrente i dispositivi a batteria collegati a quelli a 230V ci mettono minuti a ricollegarsi , cosa che voglio evitare.

Tornando  al mio problema,  hai qualche consiglio su come trovare la soluzione? 
Selle impostazioni di zigbee2mqtt non ho trovato nessun riferimento all'indirizzo 172.30.33.3:8089
Ho visto che pero' , sempre nell'interfaccia di Z2M , non è configurata la porta 8099 per quanto riguarda il frontend (la casella è vuota); posso configurarla?

**Reply by snakuzzo** [reply]
stai confondendo i due errori. Rileggi cosa ho scritto prima

**Reply by faustozago** [reply]
Non capisco ma provo a indovinare :

1-errore: devo configurare la porta 8099----> Fatto, ma la situazione non cambia.
2-errore : supervisor non trova nessuno all'indirizzo 172.30.33.3:8090 .   OK , ma perche' la cerca? dove è impostata?

**Reply by faustozago** [reply]
Scusa dimenticavo...ho fatto anche il riavvio completo, ma niente...

**Reply by snakuzzo** [reply]
Ma io che ne posso sapere? Dovresti sapere tu cosa e come hai configurato determinate cose.
Comunque..pensa prima a risolvere il problema della configurazione di zigbee2mqtt. Di sicuro hai sbagliato ad indentare o a posizionare `base_topic`

**Reply by snakuzzo** [reply]
Giusto per darti un'idea di come ho configurato l'addon zigbee2mqtt su una VM di test di HA OS...

![image](https://github.com/indomus/forum/assets/7205371/799bcd6b-394b-4201-a09f-4abb460dde7b)

il cui `/config/zigbee2mqtt/configuration.yaml` è questo...

![image](https://github.com/indomus/forum/assets/7205371/10dc7347-a73f-4bd1-809a-aeadb547d161)

**Reply by faustozago** [reply]
Sulle opzioni SOCAT è uguale alla tua.
Io su MQTT io ho indicato  :
-base topic :  zigbee2mqtt
-server: mqtt//core-mosquitto
-user: xxxx
-password: xxxx

Riguardo al file configuration.yaml , io non riesco a vedere la tua immagine (mi dice che è privata) , ma non credo ci siano errori , provo ad allegarlo su un file pdf
[yaml_0.pdf](https://github.com/indomus/forum/files/13601369/yaml_0.pdf)

**Reply by snakuzzo** [reply]
a parte che il base topic di default mi pare sia già quello...ma secondo te base topic si scrive come hai scritto tu ?

**Reply by snakuzzo** [reply]
Leggi [QUI](https://www.zigbee2mqtt.io/guide/configuration/mqtt.html) ... e ricorda che tutto quello che è già di default così come hai scritto tu, puoi ometterlo

**Reply by faustozago** [reply]
"base topic:" è scritto  "base_topic:" ...questo è corretto,   anche "zigbee2mqtt" è corretto.
Era tutto di default , ho sono aggiunto i campi dopo i ":" .
Comunque ancora non capisco che errore vedi tu.

**Comment by faustozago** [comment]
[yaml_1.pdf](https://github.com/indomus/forum/files/13601815/yaml_1.pdf)

**Reply by snakuzzo** [reply]
scusa ma cosa diavolo condividi come pdf ?
Usa il markdown

**Reply by faustozago** [reply]
Scusa, ma ti avevo avvisato che non sono tanto ferrato...la prossima volta ci provo...

**Comment by faustozago** [comment]
Ecco qua...(era piu' semplice del previsto).

```
homeassistant: true
advanced:
  network_key:
    - 34
    - 52
    - 224
    - 41
    - 76
    - 0
    - 157
    - 112
    - 28
    - 242
    - 42
    - 127
    - 132
    - 191
    - 254
    - 21
  pan_id: 28505
  ext_pan_id:
    - 182
    - 212
    - 188
    - 115
    - 187
    - 202
    - 95
    - 240
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  channel: 25
  log_level: info
mqtt:
  server: mqtt://core-mosquitto
  user: xxxxx_user
  password: xxxx
  keepalive: 60
  reject_unauthorized: true
  version: 5
frontend:
  port: 8099
serial:
  port: /dev/ttyUSB0
device_options:
  legacy: false
devices:
  '0x70ac08fffe7b900c':
    friendly_name: Ripetitore su UPS _ piano interr
  '0x70b3d52b6001add7':
    friendly_name: 'PRESA TUYA ZB7__(xxxxx) '
  '0x70b3d52b6001abf5':
    friendly_name: PRESA TUYA ZB6__(LAVATRICE)
  '0x00124b00250920c7':
    friendly_name: Sens. Movimento_Z1 (P.int)
  '0xe0798dfffebb9b46':
    friendly_name: ZBMINI_camere
  '0x00124b0025134f7d':
    friendly_name: Sens. Movimento_Z2 (sogg)
  '0xa4c138620227b7ec':
    friendly_name: Temp. Frigo
  '0xf082c0fffe89fd96':
    friendly_name: Ripetitore IK piano sup_
  '0x00124b0024ca63e4':
    friendly_name: ZBMINI PROVA
  '0x70b3d52b6001acb7':
    friendly_name: PRESA TUYA ZB4 __(TV CUCINA)
  '0x70b3d52b60018e0a':
    friendly_name: PRESA TUYA ZB5__(LAVASTOVIGLIE)
  '0x00124b0029194292':
    friendly_name: Temp. Esterna
  '0x00124b002931e676':
    friendly_name: PIR_ZB_LUCE_Garage_Est.
  '0x00124b0026b7f6a3':
    friendly_name: ZBMINI_Garage_Luce est.
  '0xa4c13831e4c65606':
    friendly_name: CONTATORE ENERGIA TUYA
    voltage_precision: 1
    voltage_calibration: 0
    debounce: 2
    debounce_ignore:
      - Current b
    filtered_attributes: []
    homeassistant: {}
    legacy: false
    optimistic: true
  '0x70b3d52b6001acc0':
    friendly_name: PRESA TUYA ZB3__(TV_AMPLI)
  '0xe0798dfffe93d5a9':
    friendly_name: ZBMINI Luce Ingresso
  '0xe0798dfffebbd9a4':
    friendly_name: ZBMINI_Luce Cancello
  '0x54ef4410001ff058':
    friendly_name: Sensore luminosita'
  '0xe0798dfffeafceaf':
    friendly_name: ZBMINI_Stufa elettr bagno
  '0x00124b0025132b18':
    friendly_name: Pulsante Stufa bagno
  '0x00124b002916f18c':
    friendly_name: PIR_ZB_Ingresso
  '0x000d6f000c484a41':
    friendly_name: '0x000d6f000c484a41'
permit_join: false
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500

```
