### DISCUSSION TITLE
[RISOLTO] Aiuto automazione: alert tensione

### DISCUSSION THREAD

**Discussion by crug80** [indomus/forum#2755] [HUB: Home Assistant]
Buongiorno, sto imparando HA e, erroneamente pensavo di aver afferrato buona parte dei concetti essendo riuscito ad integrare molte componenti della mia casa (KNX, inverter etc.), ma mi sto incasinando per un'automazione per la notifica di tensione anomala. 
```

alias: Alert_email_Tensione
description: Invia un alert via email in caso di tensione maggiore di 255 o minore 210
trigger:
  - type: voltage
    platform: device
    device_id: 0bda3a6d48d87b7122b5388854386f44
    entity_id: b41158e0bf4b12393cc7415cc7796f59
    domain: sensor
    above: 230
   - type: voltage
    platform: device
    device_id: 0bda3a6d48d87b7122b5388854386f44
    entity_id: b41158e0bf4b12393cc7415cc7796f59
    domain: sensor
    below: 210
condition: []
action:
   - service: notify.NotifyByEmail
    data:
      title: Alert Tensione anomala
      message: "{{ states.sensor.lxp_ba12090474_grid_voltage.state }}"
mode: single
```
Ora in message vorrei mettere il valore di tensione attuale che riesco a visualizzare tramite l'entità sensor.lxp_ba12090474_grid_voltage che è 

```
state_class: measurement
unit_of_measurement: V
device_class: voltage
friendly_name: Tensione In Ingresso

```

L'invio della email di prova avviene correttamente.. 

P.S. ovviamente il limite di 230 è solo per fare la prova.., poi diventerà 255
