### DISCUSSION TITLE
Automazione variabile con condizione pregressa

### DISCUSSION THREAD

**Discussion by Borghese** [indomus/forum#2765] [GENERALE - Discussioni generiche]
Ciao a tutti,

tra le varie cose, in casa, ho installato anche uno shelly EM per monitorare il consumo energetico, ovviamente il tutto configurato in home assistant. 
Stavo iniziando a creare un pò di automazioni, che mi avvisino sia su smartphone che tramite alexa in casa, nel caso in cui per es. l'assorbimento di corrente sia superiore a 3kwh per almeno 60 secondi (obiettivo è allertare chi sta in casa, per evitare di arrivare ai 3,3kwh e far scattare il contatore)
Questa devo dire che funziona perfettamente (l'ho testata sul campo accendendo per un attimo di tutto di più ;)) 

```python
  alias: Consumo Energetico Abitazione - Superamento Soglia
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 432950f36df26e5cc71f6332f51c4224
    entity_id: 1e48688574646bc7edab1aa491e7f7de
    domain: sensor
    above: 3000
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_iphone_12_di_diego
    data:
      message: Il consumo energetico di casa è superiore a 3Kwh
      title: Attenzione!
  - service: notify.alexa_media_echo_dot_studio
    data:
      message: Attenzione! Il consumo energetico di casa, è superiore a 3 chilovatt.
  - service: notify.alexa_media_echo_dot_salotto
    data:
      message: Attenzione! Il consumo energetico di casa, è superiore a 3 chilovatt.
  mode: single
- id: '1702229579808'
``` 

Ne ho poi creato un altra, con l'obiettivo di essere avvisato allo stesso modo, quando l'assorbimento rientra a valori standard, diciamo sotto i 3kwh, ed è questa : 

```python
  alias: Consumo normale
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 432950f36df26e5cc71f6332f51c4224
    entity_id: 1e48688574646bc7edab1aa491e7f7de
    domain: sensor
    below: 3000
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.alexa_media_echo_dot_studio
    data:
      message: Il consumo è normale
  mode: single

``` 

il punto è che questa seconda automazione, ogni tanto parte da sola, perchè ovviamente rileva un assorbimento sotto i 3kwh e quindi mi avvisa. 
Ma in realtà io vorrei legarci in qualche modo, la condizione che dica "solo se in precedenza si è attivata quella di superamento della soglia"
solo che non so come dirglielo... voi mi sapete aiutare ? 

grazie in antiicpo
Diego

**Comment by 50494554524F** [comment]
impossibile parta due volte senza che la soglia sia riandata sopra i 3kwh... potrebbe riscattare se il sensore va unavailable/unknown, al riavvio etc... devi vedere un po' te come funziona il sensore in queste situazioni e gestirle

**Reply by Borghese** [reply]
quindi non posso dirgli : 

Avvisami se il consumo è inferiore a 3kwh, SOLO SE (per es nei 5 minuti precedenti) è andata sopra i 3kwh ? 

Diversamente (ma forse è una cafonata) potrei inserire nell'automazione che mi avvisa se il consumo supera i 3kwh, l'attivazione dello switch dello shelly EM (che non è collegato a nulla...) e legare la seconda automazione, cioè il rientro del consumo sotto i 3kwh, allo spegnimento di quello switch...

però volevo capire se a livello logico di condizioni, si potesse implementare la prima soluzione, al di la del caso specifico, proprio per saperlo, perchè le ho provate tutte ma non ho trovato un opzione di questo tipo

**Reply by Scialla** [reply]
Basta che tieni la seconda automazione disattivata e la attivi al fondo della prima automazione, quando supera i 3 kW, e la disattivi nella sua stessa action, alla fine

**Reply by 50494554524F** [reply]
pensandoci... potresti anche derivare un sensore trigger ed escludere gli stati unknown unavailable, questi sensori mantengono anche lo stato al riavvio e diventerebbe semplice da gestire

**Comment by crug80** [comment]
A livello concettuale credo tu possa avvalerti in modo molto semplice degli aiutanti.
Te ne crei uno di tipo commutatore che setti nel momento in cui ti si scatena l'alert del consumo sopra i 3Kw.  
Nell'automazione in cui controlli se sei sotto i 3Kw, metti come condizione il check del commutatore aiutante e se è settato ti invi la notifica e provvedi a resettarlo. 
Puoi anche lavorare con le tempistiche, creandoti a supporto degli aiutanti di tipo timer, ma credo che oltre a complicarti la vita non otterresti dei vantaggi significativi.

**Comment by blakdog1978** [comment]
La butto li, si crea un timer di 5 minuti e crea un sensore di soglia per i 3kw  poi con uno script fa avviare il timer quando il sensore di soglia si accende e poi mette come condizione nell'automazione della notifica che il timer sia acceso un pò macchinoso ma dovrebbe funzionare ...

**Comment by Borghese** [comment]
grazie ragazzi, sono tutte soluzioni valide, faccio un pò di test e vi dico 
Così a naso forse la più "pulita" sarebbe quella di tenerla spenta, e farla azionare solo se si innesca la prima, come suggeriva @Scialla 

Però le provo tutte e ci gioco un pò.... vi posto poi risultato finale!

**Reply by Scialla** [reply]
La uso da sempre sulla mia automazione che fa la stessa cosa, e qualcosa in più...

**Reply by Borghese** [reply]
hai per caso un esempio di codice per capire ? (voglio evitare la gui perchè sto imparando...)

**Reply by Scialla** [reply]
Nella `action` della tua automazione aggiungi:
```
    action:
    # attivo automazione per il riarmo
    - service: automation.turn_on
      entity_id: automation.riaccensione_dispositivi
```
E poi ti fai l'automazione per il riarmo che inizialmente è disattiva e, alla fine della sua `action` si disattiva da sola:

```
  - alias: Riaccensione dispositivi
    id: riaccensione_dispositivi
    trigger:
      platform: numeric_state
      entity_id: sensor.casa_potenza
      below: 1000
      for:
        minutes: 5
    action:
      - service: switch.turn_on
        entity_id: switch.lavatrice, switch.forno, switch.forno_microonde, switch.lavastoviglie, switch.scaldabagno
      - service: script.riaccensione_dispositivi
      - service: automation.turn_off
        entity_id: automation.riaccensione_dispositivi
    initial_state: false
```

Spero di non avere fatto pasticci, sono da iPhone..
