### DISCUSSION TITLE
automazione tariffe energetiche

### DISCUSSION THREAD

**Discussion by sp2003** [indomus/forum#2773] [HUB: Home Assistant]
ciao a tutti

volevo modificare l'automazione presente sul blog relativa al cambio fasce energetiche e invece di usare come trigger il _time_  ho pensato di farla lavorare in funzione dell'integrazione Prezzi PUN mese che integra il cambio fasce in real time.

allora ho modificato così l'integrazione in automations.yaml

```
- id: tariffe_energetiche
  alias: Tariffe energetiche
  trigger:
  - platform: state
    entity_id:
    - sensor.pun_fascia_corrente
  action:
  - service: select.select_option
    target:
      entity_id: select.energia_totale_giornaliera_fasce
    data:
      option: '{{ tariff }}'
  - service: select.select_option
    target:
      entity_id: select.energia_totale_mensile_fasce
    data:
      option: '{{ tariff }}'
  initial_state: true
```

ma ho la certezza che ci sia qualcosa che non funziona in quanto quando ho provato con il cmbio manulae della fascia:

<img width="632" alt="Immagine 2023-12-16 131002" src="https://github.com/indomus/forum/assets/34820831/a2025b02-de42-4270-88ff-df14b5e33c36">

in più, come faccio a fargliela eseguire all'avvio di home assistant??? 

l'utility_meter

```
utility_meter:

  energia_totale_giornaliera_fasce:
    source: sensor.energia_prelevata_kwh
    unique_id: energia_totale_giornaliera_fasce
    cycle: daily
    tariffs:
      - F1
      - F2
      - F3
  energia_totale_mensile_fasce:
    source: sensor.energia_prelevata_kwh
    unique_id: energia_totale_mensile_fasce
    cycle: monthly
    tariffs:
      - F1
      - F2
      - F3
```

il suo sensor

```
sensor:
  - platform: integration
    source: sensor.prelievi_live
    name: energia_prelevata_kwh
    unique_id: energia_prelevata_kwh
#    unit_prefix: k
    round: 0
    unit_time: h
    method: left
```

**Comment by sp2003** [comment]
a chi servisse, questa funziona sicuro e fa il cambio considerando i festivi nazionali, a patto di installare con HACS l'integrazione prezzi PUN mese di virtualdj.

```
- id: '1702829488199'
  alias: fasce
  description: cambio fasce tramite integrazione PUN
  trigger:
  - platform: state
    entity_id:
    - sensor.pun_fascia_corrente
  condition: []
  action:
  - service: select.select_option
    target:
      entity_id:
      - select.energia_totale_giornaliera_fasce
      - select.energia_totale_mensile_fasce
    data:
      option: '{{ states.sensor.pun_fascia_corrente.state }}'
  mode: single
```
