### DISCUSSION TITLE
Comandi diretti TCP e parsing risposte

### DISCUSSION THREAD

**Discussion by crug80** [indomus/forum#2775] [HUB: Home Assistant]
Sto cercando di interagire con [un webrelay ](https://www.robot-electronics.co.uk/ds378.html) che accetta l'invio di comandi su TCP. 
Ho quindi creato un command_line switch utilizzando questo codice, ma ho ancora qualche problemino.. 
```
switch:
    name: "Pompa P0b"
    unique_id: "pump_termo_p0"
    scan_interval: 20
    command_on: echo -n -e '\x31\x05\x01\x00\x00\x00\x00\' | nc 192.168.1.16 18165
    command_off: echo -n -e '\x31\x05\x00\x00\x00\x00\x00\' | nc  192.168.1.16 18165
    command_state: echo -n -e '\x33\x05\' | nc  192.168.1.16 18165
    value_template: "{{ value[0] == '1' }}"
```
Lo switch funziona, nel senso che attiva/disattiva la valvola ma in esecuzione mi appare un pop-up a scomparsa che mi segnala un errore che onestamente non capisco
<img width="462" alt="Utf_8" src="https://github.com/indomus/forum/assets/41435902/0999e7b5-8388-4422-8aa2-f07ee3b43b52">

Il secondo problema, ,invece, riguarda la valutazione dello stato del relay nel caso esso venga attivato non tramite switch. In questo caso, infatti, per lo switch il relay è sempre spento, anche se acceso. 
Ora, credo di aver capito che se valorizzato, il valore value_template dovrebbe analizzare la risposta al command state. Nel mio caso, quel comando restituisce 5 bytes ed il primo è lo stato del relay. .. Il problema è che la mia condizione sembra non restituire mai true..

qualche dritta?
