### DISCUSSION TITLE
Telegram e Topics

### DISCUSSION THREAD

**Discussion by barbatrukko** [indomus/forum#2781] [HUB: Home Assistant]
Salve,
utilizzo abitualmente telegram per inviare notifiche sul cellulare.
Poiché le notifiche sono di diverso tipo ed alcune molto numerose, spesso è complicato trovarle nella chat.
Allora ho predisposto un gruppo telegram con dei topic e volevo diversificare la destinazione del messaggio usando i topic.
Non ci sono riuscito, ho letto in giro che molti hanno avuto problemi in merito, ed ho letto che c'era un problema sul plugin che però su un forum dicono risolto ad aprile... ma io non sono riuscito a farlo funzionare.
Ho preso dalla versione WEB di telegram l'id del gruppo (solitamente al quale mi pare di aver capito va apposto un -100 e poi l'id del topic, ma non sono riuscito ad usare il parametro 

```
telegram_bot:
  - platform: polling
    api_key: XXXXXXXXXXXXXXXXXXXXXXXX
    allowed_chat_ids:
      - YYYYYYYYYY
      - -100XXXXXXXXXXX

notify:
  - platform: telegram
    name: barbatrukko
    chat_id: -100XXXXXXXXXXX
    message_thread_id: ZZ
```
Voi avete provato? Qualcuno è riuscito?
