### DISCUSSION TITLE
Alexa Media Player attivare/disattivare routine (rileva movimento con ultrasuoni)

### DISCUSSION THREAD

**Discussion by skydado** [indomus/forum#2782] [HUB: Home Assistant]
Ciao, ho già integrato Alexa Media Player in HA con successo.
Vorrei attivare/disattivare una routine Alexa da HA, ma non funziona il comando vocale che invece sembra funzionare in altri paesi ("enable xxxxx routine"). Ho provato varie versioni in inglese e italiano.
Questo il codice di base:

```
service: media_player.play_media
data:
  media_content_id: enable <ROUTINE NAME> routine
  media_content_type: custom
target:
  entity_id: media_player.echo_dot
```

Qualche idea?

Lo scopo è quello di attivare/disattivare il rilevamento movimento con ultrasuoni di Alexa, che è possibile fare solo tramite routine, non essendo esposta alcuna entità utile allo scopo su HA.

Al momento utilizzo l'alternativa di avere la routine sempre attiva che chiama uno script su HA che, sulla base dello stato di uno switch, segnala o meno il movimento. La soluzione non mi piace perchè rischia di saturare il limite gratuito di chiamate/interazioni con AWS tra Alexa e HA (lambda).
