### DISCUSSION TITLE
Problema connessione ad HA da remoto dopo migrazione a docker

### DISCUSSION THREAD

**Discussion by sagoweb** [indomus/forum#2788] [Networking]
Buongiorno a tutti,
dopo svariati tentativi infruttuosi chiedo umilmente aiuto.

Ho effettuato la migrazione a docker seguendo la guida su indomus, ha funzionato più o meno tutto tranne che non riesco ad accedere ad HA dall'esterno. Misteriosamente se accedo a:
http://[casa].duckdns.org:48123/  --> funziona (cosa che non mi aspetterei)
mentre se accedo a 
https://[casa].duckdns.org:48123/  --> ricevo un errore ssl (ERR_SSL_PROTOCOL_ERROR su chrome e SSL_ERROR_RX_RECORD_TOO_LONG su firefox).
I files di configurazione sono i seguenti:

**docker-compose.yaml**
```
  duckdns:
    container_name: duckdns
    image: ghcr.io/linuxserver/duckdns
    environment:
    - "TZ=Europe/Rome"
    - "SUBDOMAINS=[casa]"
    - "TOKEN=[miotoken]"
    restart: always

  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
    - "/home/pi/caddy/Caddyfile:/etc/caddy/Caddyfile"
    - "/home/pi/caddy/data:/data"
    environment:
    - "TZ=Europe/Rome"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    - "48123:48123"
```

Caddyfile
```
{
  debug
}
(https_header) {
  header {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}
https://[casa].duckdns.org {
  respond "Saluti dal Crew inDomus"
  file_server
}
https://[casa].duckdns.org:48123 {
  import https_header
  reverse_proxy http://192.168.1.1:8123
}
```
configuration.yaml (di home-assistant)
```
homeassistant:
  external_url: "https://[casa].duckdns.org:48123" # ho anche provato a rimuoverlo
  packages: !include_dir_named packages

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/16 
```
La sottorete indicata in trusted_proxies l'ho ottenuta con il comando docker network inspect bridge | grep Subnet
Le porte sul router sono aperte, facendo un port scan sulla porta 48123 sul mio dominio ottengo una risposta tipo:
State: open
Service name: http
Service product: aiohttp 3.9.1
Service info: Python 3.11

Questo mi fa supporre che caddy stia funzionando correttamente.

C'è evidentemente qualcosa che mi sfugge, grazie a chi vorrà aiutarmi!
