### DISCUSSION TITLE
lo script salta la condizione

### DISCUSSION THREAD

**Discussion by minocardia** [indomus/forum#2791] [HUB: Home Assistant]
Salve
premesso il fatto che sono alle prime armi
cercavo di far eseguire una determinata azione soltanto ad una determinata condizione
questo è il semplice codice YAML:

```
alias: spegni stufa
trigger:
  - platform: conversation
    command:
      - spegni stufa
condition:
  - condition: state
    entity_id: binary_sensor.stufaaccesa
    state: "on"
action:
  - type: turn_off
    device_id: 1938087b35050ed306c079dfe0a4d172
    entity_id: aa56aa99f12b78cbfefdc46e2c580450
    domain: switch
mode: single

```

il problema sta nel fatto che nonostante la condizione sia falsa (testata con il TEST integrato) viene eseguita comunque l'azione
dove sto sbagliando?
