### DISCUSSION TITLE
rendere disponibili sensori HA per altri hub domotici

### DISCUSSION THREAD

**Discussion by sp2003** [indomus/forum#2795] [HUB: Home Assistant]
così per il gusto di provare, vorrei rendere disponibili alcuni sensori che HA usa (tipo la lettura dei dati via modbus dell'inverter e dei contatori di energia/potenza) per altri hub domotici, tipo openHAB o altri.
La prima cosa che mi era venuta in mente era MQTT e avevo pensato ad una automazione che si attiva al cambio di stato di un sensore e che quindi chiama il servizio mqtt.publish, ma non so che cosa fargli pubblicare, o meglio il messaggio da pubblicare non mi è chiaro come deve essere.
O magari c'è un'altra via....

**Comment by snakuzzo** [comment]
Ciao.
In realtà per rendere disponibile il valore di quel sensore, potresti semplicemente utilizzare le [API REST di Home Assistant](https://developers.home-assistant.io/docs/api/rest/). Nel caso specifico di un sensore...

![image](https://github.com/indomus/forum/assets/7205371/01050aa8-1ab6-4677-a107-8730e882b605)

Se però vuoi pubblicare sul broker lo stato di un sensore, come hai scritto e come ti è stato detto in chat, ti basta un'automazione.
Il topic e come strutturare il payload, lo decidi tu

Esempio:

```yaml
- id: esempio_publish_mqtt
  alias: Esempio publish MQTT
  trigger:
  - platform: state
    entity_id: sensor.finestra_bagno
    to: ~
  action:
  - service: mqtt.publish
    data:
      topic: "myhomeassistant/finestra_bagno"
      payload: "{{ trigger.to_state.state }}"
```

Con questa automazione, ad ogni cambio stato del sensore su HA, verrà fatta una publish MQTT con il nuovo stato del sensore con un topic scelto da te. Poi puoi scegliere eventualmente altre opzioni legate a retain, qos, etc, ma è tutta roba scritta in documentazione e che puoi analizzare per conto tuo [QUI](https://www.home-assistant.io/integrations/mqtt/#publish--dump-services)
