### DISCUSSION TITLE
Automazione Calendar Festività Italiane

### DISCUSSION THREAD

**Discussion by djgragra** [indomus/forum#2799] [HUB: Home Assistant]
Ciao, ho seguito la [guida di InDomus sulle festività italiane](https://indomus.it/guide/integrare-il-calendario-delle-festivita-italiane-ed-altri-sulla-domotica-home-assistant/) e ho aggiunto 2 calendari. Ho fatto un piccolo package che contiene anche le automazioni ma purtroppo ho notato che non triggherano ,infatti questa mattina (28/12/23) alle 00:00:30 Buono a Sapersi risulta acceso ma l’automazione non parte. dove sbaglio? 
Di seguito il package 
[https://pastebin.com/6ACwuBcE](https://pastebin.com/6ACwuBcE)

```
ics_calendar:
  calendars:
    - name: "Festività Italiane"
      url: "https://www.webcal.guru/it-IT/scarica_calendario?calendar_instance_id=66"
      include_all_day: true
      days: 365
      parser: "ics"
    - name: "Buono a Sapersi"
      url: "https://www.webcal.guru/it-IT/scarica_calendario?calendar_instance_id=194"
      include_all_day: true
      days: 365
      parser: "ics"


automation:
  - alias: "service_festivita_italiane"
    id: "service_festivita_italiane"
    mode: single
    trigger:
      - platform: calendar
        entity_id: calendar.festivita_italiane
        event: start
        id: "START"
    condition: []
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.holiday_festivita_italiane
      - delay:
          hours: 24
      - service: input_boolean.turn_off
        entity_id: input_boolean.holiday_festivita_italiane
      - service: notify.famiglia_telegram
        data:
          title: Oggi è...
          message: "{{ states.calendar.festivita_italiane.attributes.message }} {{ '\n' }} {{ '\n' }}{{ states.calendar.festivita_italiane.attributes.description }}"   

  - alias: "service_buono_a_sapersi"
    id: "service_buono_a_sapersi"
    mode: single
    trigger:
      - platform: calendar
        entity_id: calendar.buono_a_sapersi
        event: start
        id: "START"
    condition: []
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.holiday_buono_a_sapersi
      - delay:
          hours: 24
      - service: input_boolean.turn_off
        entity_id: input_boolean.holiday_buono_a_sapersi
      - service: notify.famiglia_telegram
        data:
          title: Oggi è...
          message: "{{ states.calendar.buono_a_sapersi.attributes.message }} {{ '\n' }} {{ '\n' }}{{ states.calendar.buono_a_sapersi.attributes.description }}"

```

**Comment by KC-inDomus** [comment]
ma "buono a sapersi" contiene eventi all-day?

**Reply by djgragra** [reply]
Credo proprio di si. Nello specifico ha 31 eventi al momento e uno era oggi.

**Reply by KC-inDomus** [reply]
mah non capisco come possa non andare, allora. a mezzanotte deve eseguire l'automazione, period. non ho capito se non ti parte proprio l'esecuzione o cos'altro.

**Reply by djgragra** [reply]
Ma infatti anche perchè rispetto al codice dell'articolo ho solo aggiunto il servizio di notifica telegram, che testato mi genera un messaggio come quello nella foto allegata.
<img width="397" alt="Screenshot 2023-12-29 alle 12 44 01" src="https://github.com/indomus/forum/assets/65872226/e5765440-1c7d-4b70-b983-0b67b1604847">

Nel registro di HA ho trovato a mezzanotte del 28 Buono a Sapersi ACCESO 
<img width="420" alt="Screenshot 2023-12-29 alle 12 46 01" src="https://github.com/indomus/forum/assets/65872226/0da0eae6-3b55-4466-a3f8-c4ae8b68a2b8">
ma l'automazione non risulta eseguita, dovrei trovare anche quella nel registro no?
Adesso ho due altre "finestre" per vedere cosa succede. Una per il calendario Buono a Sapersi il 31 e l'altra il primo dell'anno per il calendario Festività nazionali.
Ho provato a forzare gli stati delle entità calendario ma ricevo un errore come se non potessero venire forzate.

**Reply by djgragra** [reply]
Ho creato un evento TUTTO IL GIORNO su calendar.local, creato l'input_boolean e l'automazione relativa. Mi aspetto che domani alle 00.00 parta.

```

alias: service_local
mode: single
trigger:
  - platform: calendar
    entity_id: calendar.local
    event: start
    id: START
condition: []
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.holiday_local
  - delay:
      hours: 24
  - service: input_boolean.turn_off
    entity_id: input_boolean.holiday_local
  - service: notify.famiglia_telegram
    data:
      title: Oggi è...
      message: |-
        {{ states.calendar.local.attributes.message }} {{{ '\n' }} {{ '\n' }}{{ states.calendar.local.attributes.description }}

```

**Comment by djgragra** [comment]
@KC-inDomus 
Dopo varie prove volevo riportare le mie considerazioni sulle automazioni legate al calendario.
Ho avuto diversi problemi con il trigger delle automazioni collegate a calendari esterni con eventi all-day.
Ho fatto delle automazioni "parallele" che hanno come unica differenza il trigger.
Anziché utilizzare 
```
platform: calendar
entity_id: calendar.festivita_italiane
event: start
id: START

```
ho provato ad utilizzare 
```

platform: state
entity_id:
  - calendar.festivita_italiane
from: "off"
to: "on"

```
In questo modo le automazioni al momento non mi stanno dando problemi.
Per quanto riguarda invece le automazioni legate al calendario locale con eventi NON all-day li nessun problema usando come attivazione START e come condition il nome dell'evento.
```

trigger:
  - platform: calendar
    event: start
    offset: "0:0:0"
    entity_id: calendar.local
  - platform: calendar
    event: end
    offset: "0:0:0"
    entity_id: calendar.local
condition:
  - condition: template
    value_template: "{{ 'Evento TEST 1' in trigger.calendar_event.summary }}"

```

**Reply by KC-inDomus** [reply]
guarda, con @snakuzzo abbiamo corretto il tiro della guida, che attualmente corretta.
il modo giusto di innescare l'automazione è il seguente (per gli all-day, intendo):



```
platform: calendar
entity_id: calendar.festivita_italiane
event: start
id: START
```

avendo cura di impostare a `mode:parallel` la modalità dell'automazione.

Un'altra modalità è questa:

```
- platform: template
value_template: "{{ state_attr('calendar.festivita_italiane', 'all_day') and states('calendar.festivita_italiane') == 'on' }}"
 id: "holiday"
```

**Reply by djgragra** [reply]
Però l'automazione aggiornata sulla guida mi sembra diversa dal codice che hai postato quì. 

```
automation:
  - alias: "service_holiday_calendar"
    id: "service_holiday_calendar"
    mode: parallel
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.festivita_italiane
    condition: []
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.holiday
      - delay:
          hours: 24
      - service: input_boolean.turn_off
        entity_id: input_boolean.holiday

```
