### DISCUSSION TITLE
Status con ultimo script eseguito

### DISCUSSION THREAD

**Discussion by tabs78** [indomus/forum#2807] [GENERALE - Discussioni generiche]
Ciao, ho una velux che comando con broadlink mediante  due scripts
Integrati in alexa.

vorrei poter verificare ( a grandi linee, so che per più precisione servirebbe un sensore apertura) quando è aperta o chiusa.
Vorrei farlo cambiando lo status di un'entità fittizia quando aziono uno dei due script.

ho provato a seguire la guida per un cover template ma non sono pratico e quando aziono i comandi fittizi di apertura o chiusura non cambia status.

qualcuno mi aiuterebbe?

**Comment by snakuzzo** [comment]
Testato e funzionante...

```yaml
# Qui viene salvato lo stato aperto/chiuso (on/off)      
input_boolean:

  velux_status:

# Questa è l'entità di tipo cover
cover:

  - platform: template
    covers:
      velux:
        device_class: window
        friendly_name: "Velux"
        # recupero stato dall'input boolean
        value_template: "{{ states('input_boolean.velux_status') == 'on' }}"
        open_cover:
          # esecuzione script per apertura cover
          service: script.velux_open
        close_cover:
          # esecuzione script per chiusura cover
          service: script.velux_close


automation:

- id: velux_update_status
  alias: Velux Update Status
  trigger:
  # automazione che scatta all'esecuzione di uno dei due script di apertura/chiusura
  - platform: state
    entity_id:
    - script.velux_open
    - script.velux_close
    to: "on"
  action:
  # se viene eseguito lo script di apertura, imposta l'input boolean a on, altrimenti lo imposta a off
  - service: >
      {% if trigger.entity_id == 'script.velux_open' %}
        input_boolean.turn_on
      {% else %}
        input_boolean.turn_off
      {% endif %}
    data:
      entity_id: input_boolean.velux_status
```

Qui quando la cover è chiusa

![image](https://github.com/indomus/forum/assets/7205371/446d8579-2d76-4c14-a435-26122e2bb178)

Qui quand ola cover è aperta

![image](https://github.com/indomus/forum/assets/7205371/9c073f5f-f3fa-4348-843a-943a672828ec)
