### DISCUSSION TITLE
SSH & Web Terminal config.

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#282] [HUB: Home Assistant]
Ci risiamo, sto per ripristinare il sistema, ma non riesco ancora una volta ad accedere via SFTP con Filezilla. Questa la configurazione di SSH:
```
ssh:
  username: root
  password: 'lapassworddaccessoadhassio'
  authorized_keys:
    - ssh-rsa AASDJKJKJFWJFAFLCNALCMLAK234234
  sftp: true
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: true
share_sessions: true
packages:
  - '-build-base'
init_commands:
  - '-ls -la'
log_level: info
```
Ma se tento di aprire il Terminale dice: _502: Bad Gateway_  . 
In filezilla protocollo SFTP,  IP di Raspberry, username e password presi dalla configurazione qui sopra, porta 22
Ma non si connette.
