### DISCUSSION TITLE
Problema da principiante su configuration.yaml

### DISCUSSION THREAD

**Discussion by paolicchi94** [indomus/forum#2829] [HUB: Home Assistant]
Buongiorno a tutti,
Da qualche giorno ho iniziato ad usare, in modo molto banale, HA.
Volendo integrare Alexa, ho applicato la guida "Botta e risposta con Alexa verso Home Assistant" e sono riuscito ad arrivare quasi alla fine. il problema che ho riscontrato, perche sono un principiante, è nel copiare gli script in configuration.yaml
Mi esce l'errore ( non bloccante) : duplicated mapping key (19:1)
Questo è il file configuration.yaml  che genera questo errore sopra 
```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

browser_mod :
binary_sensor:
    platform: meteoalarm
    country: "Italy"
    province: "Pistoia"
    
script:
  activate_alexa_actionable_notification:
    alias: activate_alexa_actionable_notification
    description: Attiva le notifiche azionabili verso uno specifico Amazon Echo
    fields:
      text:
        description: Il testo che si vuol far pronunciare ad Alexa.
        example: 'A che temperatura vuoi regolare il termostato?'
      event_id:
        description: Identificativo di risposta
        example: 'richiesta_temperatura'
      alexa_device:
        description: L'echo da utilizzare
        example: 'media_player.echo_camera'
      suppress_confirmation:
        description: Impostare a "true" se non si vuole conferma verbale da parte di Alexa
        example: 'true'
    sequence:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.alexa_actionable_notification
          value: '{"text": "{{ text }}", "event": "{{ event_id }}", "suppress_confirmation": "{{ suppress_confirmation }}"}'
      - service: media_player.play_media
        data_template:
          entity_id: "{{ alexa_device }}"
          media_content_type: skill
          media_content_id: media_player.echo_show_di_luca
    mode: single
```

Cosa sbaglio?
