### DISCUSSION TITLE
ESP32-WROOM multi servizio

### DISCUSSION THREAD

**Discussion by sp2003** [indomus/forum#2838] [Hardware & Firmware]
ciao a tutti

dovrei sostituire un sonoff basis con tasmota che ha 3 sonde dallas ds18b20.
siccome dovrei aggiungere un altro rele 4ch e rilevare lo stato di on/off di 4 termostati stavo pensando di sostituire il sonoff con questa board che ha un ESP32-WROOM.
con i fw esphome, riuscirei a fargli gestire gli 8 rele installati + le 3 sonde di temperatura + 4 ingressi digitali?
![71U8ydQPZlL _SL1500_](https://github.com/indomus/forum/assets/34820831/352643c5-c45c-4f77-8d3d-66f20fcdb1c2)

**Comment by KC-inDomus** [comment]
sì,  non dovrebbe essere complicatissimo

**Reply by sp2003** [reply]
```
esphome:
  name: 8ch
  friendly_name: 8ch

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: 'domotica up'
  password: 'password'
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AP Fallback 8ch"
    password: "q1w2e3r4"

captive_portal:

time:
  - platform: sntp
    id: my_time
    timezone: Europe/Rome

binary_sensor:
  - platform: status
    name: Status
  - platform: gpio
    pin: GPIO34
    name: "Termostato salone"
    device_class: power
  - platform: gpio
    pin: GPIO35
    name: "Termostato cucina"
    device_class: power
  - platform: gpio
    pin: GPIO36
    name: "Termostato matrimoniale"
    device_class: power
  - platform: gpio
    pin: GPIO39
    name: "Termostato singola"
    device_class: power

text_sensor:
  - platform: version
    name: Version
    hide_timestamp: true

web_server:
  port: 80
  auth:
    username: admin
    password: admin

# Enable logging
logger:

# Status LED
light:
  - platform: status_led
    name: "Led di status"
    restore_mode: ALWAYS_ON
    pin:
      number: GPIO23
      inverted: true

# 8 relay outputs, exposed as switches in Home Assistant
switch:
  - platform: gpio
    pin: GPIO32
    name: relay salone
    id: relay1
  - platform: gpio
    pin: GPIO33
    name: relay cucina
    id: relay2
  - platform: gpio
    pin: GPIO25
    name: relay singola
    id: relay3
  - platform: gpio
    pin: GPIO26
    name: relay matrimoniale
    id: relay4
  - platform: gpio
    pin: GPIO27
    name: relay zonatv
    id: relay5
  - platform: gpio
    pin: GPIO14
    name: Relay6
    id: relay6
  - platform: gpio
    pin: GPIO12
    name: Relay7
    id: relay7
  - platform: gpio
    pin: GPIO13
    name: Relay8
    id: relay8
  - platform: restart
    name: Riavvio

# sonde DS18b20
dallas:
  - pin: GPIO21

sensor:
  - platform: dallas
    address: 0x8f3ce10457af0828
    name: "Mandata impianto"
  - platform: dallas
    address: 0xaf3ce10457fd8c28
    name: "Collettori solari"
  - platform: dallas
    address: 0xc13ce10457955b28 
    name: "Temperatura puffer"  

# Enable Home Assistant API
api:
  encryption:
    key: "api"

ota:
  password: "q1w2e3r4"

```

rele e sonde temperatura vanno, ma se metto i cavetti dupon sui pin dei binary_sensor (34 , 35 ,  36 e 39) senza collegarli a massa  i binary_sensor palleggiano velocemete tra on e off. senza cavetti, segnano tranquillamente OFF....

cosa può essere??

**Reply by snakuzzo** [reply]
Prova a dare un'occhiata qui -> https://community.home-assistant.io/t/binary-sensor-constantly-changing-from-on-off/236009/6

**Comment by sp2003** [comment]
SOLVED

i pin di solo input 34, 35, 36 e 39 non hanno resistenza interna perciò c'è bisogno di una resistenza e di fare dei collegamenti come da immagine. la vcc è la 3.3v
![photo_2024-01-28_13-02-36](https://github.com/indomus/forum/assets/34820831/23e7a6ef-adc3-4d21-89d0-902b79f1a836)
aggiungo anche il codice definitivo
```
esphome:
  name: 8ch
  friendly_name: 8ch

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: 'lamiaretewif'
  password: 'lamiapassword'
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AP Fallback 8ch"
    password: "q1w2e3r4"

captive_portal:

time:
  - platform: sntp
    id: my_time
    timezone: Europe/Rome

binary_sensor:
  - platform: status
    name: Status
  - platform: gpio
    pin: GPIO34
    on_press:
     then:
      - delay: 400ms
    name: "input digitale 1"
    device_class: power
  - platform: gpio
    pin: GPIO35
    on_press:
     then:
      - delay: 400ms
    name: "input digitale 2"
    device_class: power
  - platform: gpio
    pin: GPIO36
    on_press:
     then:
      - delay: 400ms
    name: "input digitale 3"
    device_class: power
  - platform: gpio
    pin: GPIO39
    on_press:
     then:
      - delay: 400ms
    name: "input digitale 4"
    device_class: power

text_sensor:
  - platform: version
    name: Version
    hide_timestamp: true
  - platform: wifi_info
    ip_address:
      name: IP
    mac_address:
      name: Mac Address

web_server:
  port: 80

# Enable logging
logger:

# Status LED
light:
  - platform: status_led
    name: "Led di status"
    restore_mode: ALWAYS_ON
    pin:
      number: GPIO23
      inverted: false

# 8 relay outputs, exposed as switches in Home Assistant
switch:
  - platform: gpio
    pin: GPIO32
    name: Relay1
    id: relay1
  - platform: gpio
    pin: GPIO33
    name: Relay2
    id: relay2
  - platform: gpio
    pin: GPIO25
    name: Relay3
    id: relay3
  - platform: gpio
    pin: GPIO26
    name: Relay4
    id: relay4
  - platform: gpio
    pin: GPIO27
    name: Relay5
    id: relay5
  - platform: gpio
    pin: GPIO14
    name: Relay6
    id: relay6
  - platform: gpio
    pin: GPIO12
    name: Relay7
    id: relay7
  - platform: gpio
    pin: GPIO13
    name: Relay8
    id: relay8
  - platform: restart
    name: Riavvio

# sonde DS18b20
dallas:
  - pin: GPIO21
    update_interval: 30s

sensor:
  - platform: dallas
    address: 0x8f3ce10457af0828
    name: "Temperatura 1"
  - platform: dallas
    address: 0xaf3ce10457fd8c28
    name: "Temperatura 2"
  - platform: dallas
    address: 0xc13ce10457955b28 
    name: "Temperatura 3"  
     
# Enable Home Assistant API
api:
  encryption:
    key: "mettiquilatuakey"

ota:
  password: "q1w2e3r4"  
```

**Comment by sp2003** [comment]
sempre su questa board, non riesco a fare una sorta di interlock tra 2 rele
In sostanza vorrei che se lo stato di uno switch è ON, un altro switch deve passare a OFF e rimanere così fino a quando lo stato del primo switch non passa a OFF.

avevo scritto questo ma la validazione fallisce
```
  - platform: gpio
    pin: GPIO14
    name: 6 abilita/disabilita PdC
    id: relay6
    on_switch.is_on:
      if:
        condition:
          switch.turn_off: relay5
```
![photo_2024-02-06_12-32-16](https://github.com/indomus/forum/assets/34820831/8edc449c-8452-4959-bece-0a61a742f737)

ho provato anche l'opzione 

`interblock: [releay5] `

 ma ovviamente funziona solo in un senso
dove sbaglio?
