### DISCUSSION TITLE
EZSP Error durante configurazione ZigBee2MQTT

### DISCUSSION THREAD

**Discussion by giadamosi** [indomus/forum#2841] [GENERALE - Discussioni generiche]
Buonasera a tutti,
scrivo qui perché sono disperato. Possiedo un ZBDONGLE-E v2, flashato con firmware RPC v4.3.2 (la penultima versione perché tanto non funziona neanche con l'ultima).
Invece su raspberry ho HA su docker, ho già provveduto all'installazione del docker con MQTT e docker con multipan RPC e l'intoppo arriva quando provo ad installare il docker con zigbee2mqtt. Di seguito vi inserisco il file di configurazione del docker compose:

``` yaml

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
    - "/home/alessandro/data/zigbee2mqtt:/app/data"
    devices:
    - "/dev/ttyACM0"
    environment:
    - "TZ=Europe/Rome"
    network_mode: host
    restart: always
  
  multipan:
    container_name: multipan
    image: b2un0/silabs-multipan-docker
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    restart: always
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyACM0
    volumes:
      - ./data/:/data
    environment:
      # OCPD environment variables
      DEVICE: "/dev/ttyACM0"
      BAUDRATE: "460800"
      CPCD_TRACE: "false"
      FLOW_CONTROL: "false"

      NETWORK_DEVICES: 0

      # OTBR-AGENT environment variables
      OTBR_ENABLE: 1
      BACKBONE_IF: "wlan0"
      OTBR_LOG_LEVEL: "debug"
      OTB_FIREWALL: 1
      OTBR_REST_LISTEN_PORT: "8081"

      # OTBR-WEB environment variables
      OTBR_WEB_PORT: "8086"

      # SOCAT environment variables
      NETWORK_DEVICE: ""

      # ZIGBEED environment variables
      EZSP_LISTEN_PORT: "9999"

      # UNIVERSAL FLASHER variables
      AUTOFLASH_FIRMWARE: 0
      FIRMWARE: "86"

```

E infine il file di configurazione di zigbee2mqtt:

``` yaml

# Autodiscovery su Home Assistant abilitato
homeassistant: true
# Join alla rete MQTT disabilitato di default
permit_join: false
# MQTT settings
mqtt:
  # MQTT base topic per i messaggi di zigbee2mqtt
  base_topic: zigbee2mqtt
  # MQTT server - URL (indirizzo LAN)
  server: 'mqtt://localhost:1883'
  # MQTT server - Parametri di autenticazione (decommentare e popolare correttamente se si utilizzano credenziali per la connessione al broker MQTT
  user: mqtt_user
  password: 123456789
  version: 5
  include_device_information: true
serial:
  # Porta su cui è mappata l'antenna zigbee
  port: tcp://core-silabs-multiprotocol:9999
  adapter: ezsp
advanced:
  # Directory in cui verrà salvato il file di log
  log_directory: /var/log
experimental: {}
frontend:
  # porta su cui verrà esposta la webGUI
  port: 1885
ota:
  update_check_interval: 10
disable_automatic_update_check: false


``` 

L'errore che ottengo leggendo il log di zigbee2mqtt:

``` 

Using '/app/data' as data directory
Zigbee2MQTT:info  2024-01-16 22:39:11: Logging to console and directory: '/var/log' filename: log.txt
Zigbee2MQTT:info  2024-01-16 22:39:11: Starting Zigbee2MQTT version 1.35.1 (commit #9eaaa0f)
Zigbee2MQTT:info  2024-01-16 22:39:11: Starting zigbee-herdsman (0.30.0)
Zigbee2MQTT:error 2024-01-16 22:39:32: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-01-16 22:39:32: Failed to start zigbee
Zigbee2MQTT:error 2024-01-16 22:39:32: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-01-16 22:39:32: Exiting...
Zigbee2MQTT:error 2024-01-16 22:39:33: Error: Failure to connect
    at Ezsp.connect (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:277:19)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:139:9)
    at EZSPAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:172:16)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:98:27)
    at start (/app/index.js:107:5)

``` 

Notate errori? Spero di si perché io non ci vedo più.
Intanto vi ringrazio.
