### DISCUSSION TITLE
Interruttori fisici con priorità su automazione luci off sensore di presenza o di occupazione

### DISCUSSION THREAD

**Discussion by homeassistantby17** [indomus/forum#2844] [HUB: Home Assistant]
Buonasera,

in casa ho installato una discreta quantità di Shelly Plus 1, 1 PM e 2 PM che controllano, attraverso sensori di presenza PIR o di occupazione mmWave, l'attivazione e lo spegnimento di varie e differenti luci.
Quello che vorrei fare è costruire una automazione che prenda in considerazione e rendano prioritario anche l'utilizzo di pulsanti o interruttori che controllano  le stesse luci ovvero, più nello specifico:

-) Se la relativa luce è controllata da un interruttore e l'interruttore è in posizione "ON" allora l'automazione di spegnimento, controllata da un sensore di occupazione mmWave che riporto qui sotto, non deve essere eseguita.

```

- id: '1701436012597'
  alias: Luce cucina centrale off
  description: ''
  trigger:
  - type: not_occupied
    platform: device
    device_id: bda957bc63e91f7ff85f6c2cd5c50374
    entity_id: 15968fa1928c4fed1f9718d3146c228c
    domain: binary_sensor
  - type: illuminance
    platform: device
    device_id: bda957bc63e91f7ff85f6c2cd5c50374
    entity_id: 0e37260e6c2469d7860b73685d96ce51
    domain: sensor
    above: 110
    enabled: true
  condition:
  - condition: or
    conditions:
    - type: is_not_occupied
      condition: device
      device_id: bda957bc63e91f7ff85f6c2cd5c50374
      entity_id: 15968fa1928c4fed1f9718d3146c228c
      domain: binary_sensor
    - condition: and
      conditions:
      - type: is_occupied
        condition: device
        device_id: bda957bc63e91f7ff85f6c2cd5c50374
        entity_id: 15968fa1928c4fed1f9718d3146c228c
        domain: binary_sensor
      - type: is_illuminance
        condition: device
        device_id: bda957bc63e91f7ff85f6c2cd5c50374
        entity_id: 0e37260e6c2469d7860b73685d96ce51
        domain: sensor
        above: 110
  action:
  - type: turn_off
    device_id: 258425788019c57c60f297d0e1ffe525
    entity_id: 3e166263507de675a41d8033bd89bd27
    domain: light
  mode: single

```

-) Se la relativa luce è controllata da un pulsante e il pulsante è stato azionato entro un certo lasso temporale precedente allora l'automazione di spegnimento, una controllata da un sensore di occupazione mmWave e una da un sensore di presenza PIR, che riporto entrambe qui sotto, non devono essere eseguite.

```

- id: '1701644654114'
  alias: Luci ingresso off
  description: ''
  trigger:
  - type: not_occupied
    platform: device
    device_id: 6f702d384a17fe62e8394a920ce955f2
    entity_id: 0eae3004f8414672f8711dd315d6b3e9
    domain: binary_sensor
  - type: no_motion
    platform: device
    device_id: 59cd6a27786f9131984fce772db68125
    entity_id: ce6faafda7ea006dc8da1d78ec969546
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 3
    enabled: true
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - type: is_not_occupied
        condition: device
        device_id: 6f702d384a17fe62e8394a920ce955f2
        entity_id: 0eae3004f8414672f8711dd315d6b3e9
        domain: binary_sensor
      - condition: time
        after: 08:00:00
        before: 06:00:00
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      enabled: false
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.sensore_di_movimento_in_corridoio_occupancy
        state: 'off'
        enabled: true
      - condition: time
        after: 08:00:00
        before: 06:00:00
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      enabled: false
    - type: is_not_occupied
      condition: device
      device_id: 6f702d384a17fe62e8394a920ce955f2
      entity_id: 0eae3004f8414672f8711dd315d6b3e9
      domain: binary_sensor
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.sensore_di_movimento_in_corridoio_occupancy
        state: 'off'
        enabled: true
      - type: is_not_occupied
        condition: device
        device_id: 6f702d384a17fe62e8394a920ce955f2
        entity_id: 0eae3004f8414672f8711dd315d6b3e9
        domain: binary_sensor
      - condition: time
        after: 00:00:01
        before: 06:00:00
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
  action:
  - type: turn_off
    device_id: 64f716f1134888066af2fd292678f67d
    entity_id: d4986de5c1663d13bd0079ab6c1763cb
    domain: light
  mode: single

```

```

- id: '1704490628272'
  alias: Luci corridoio off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 59cd6a27786f9131984fce772db68125
    entity_id: ce6faafda7ea006dc8da1d78ec969546
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 6
  condition:
  - condition: or
    conditions:
    - type: is_illuminance
      condition: device
      device_id: 59cd6a27786f9131984fce772db68125
      entity_id: 1ca78f7992ccd924316f0c99cbcb436f
      domain: sensor
      above: 15
      enabled: true
    - condition: state
      entity_id: binary_sensor.sensore_di_movimento_in_corridoio_occupancy
      state: 'off'
      enabled: true
    - condition: not
      conditions:
      - condition: state
        entity_id: event.shellyplus1pm_fcb467ba0cf8_input_0
        attribute: event_type
        state: single_push
      - condition: state
        entity_id: event.luci_corridoio_ambra_input_0
        attribute: event_type
        state: single_push
    enabled: true
  - condition: or
    conditions:
    - condition: and
      conditions:
      - type: is_illuminance
        condition: device
        device_id: 59cd6a27786f9131984fce772db68125
        entity_id: 1ca78f7992ccd924316f0c99cbcb436f
        domain: sensor
        above: 15
      - condition: not
        conditions:
        - condition: state
          entity_id: event.shellyplus1pm_fcb467ba0cf8_input_0
          attribute: event_type
          state: single_push
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.sensore_di_movimento_in_corridoio_occupancy
        state: 'off'
      - condition: not
        conditions:
        - condition: state
          entity_id: event.shellyplus1pm_fcb467ba0cf8_input_0
          attribute: event_type
          state: single_push
    enabled: false
  action:
  - type: turn_off
    device_id: ccc89986ec8a4f142f79925990e7acd7
    entity_id: 7d79f56c20d447a94b24c88911f6c67f
    domain: light
  - type: turn_off
    device_id: cffa090e2978ae88586a857058253929
    entity_id: c2cadf33d686f31d5c172b765dc92340
    domain: light
  mode: single

```

Qualcuno di voi, per favore, può aiutarmi a capire come fare a realizzare un utilizzo come descritto?

Grazie mille.
