### DISCUSSION TITLE
Mold indicator

### DISCUSSION THREAD

**Discussion by homeassistantby17** [indomus/forum#2857] [HUB: Home Assistant]
Sulla base dell'articolo https://indomus.it/progetti/muffa-e-domotica-come-mitigare-il-problema-tramite-home-assistant/ ho provato a configurare due sensori rischio muffa con la configurazione seguente:

```

# Indicatore rischio muffa
sensor:
  - platform: mold_indicator
    friendly_name: "Rischio muffa in bagno cieco"
    indoor_temp_sensor: sensor.temperatura_e_umidita_bagno_cieco_temperature
    indoor_humidity_sensor: sensor.temperatura_e_umidita_bagno_cieco_humidity
    outdoor_temp_sensor: sensor.temperatura_e_umidita_esterna_temperature
    calibration_factor: 2.0
    
  - platform: mold_indicator
    friendly_name: "Rischio muffa nel bagno finestrato"
    indoor_temp_sensor: sensor.temperatura_e_umidita_bagno_finestrato_temperature
    indoor_humidity_sensor: sensor.temperatura_e_umidita_bagno_finestrato_humidity
    outdoor_temp_sensor: sensor.temperatura_e_umidita_esterna_temperature
    calibration_factor: 2.0

```

Quando faccio la verifica della configurazione ottengo questi errori:

Avvisi di configurazione
Invalid config for 'mold_indicator' from integration 'sensor' at configuration.yaml, line 38: 'friendly_name' is an invalid option for 'sensor.mold_indicator', check: friendly_name
Invalid config for 'mold_indicator' from integration 'sensor' at configuration.yaml, line 45: 'friendly_name' is an invalid option for 'sensor.mold_indicator', check: friendly_name

Cosa sbaglio?
