### DISCUSSION TITLE
Creazione di un sensore su Home Assistant

### DISCUSSION THREAD

**Discussion by lnrd00** [indomus/forum#2866] [HUB: Home Assistant]
Salve a tutti, sto provando a seguire una guida InDomus per esercitarmi, dove devo creare un sensore estraendo il valore della temperatura dall'entità del mio termostato Tado:
<img width="1004" alt="Schermata 2024-01-26 alle 18 49 02" src="https://github.com/indomus/forum/assets/154708323/2354f92c-c12b-4646-ad2f-a241fcfaf4f7">
Ho dunque creato il sensore nel file `configuration.yaml` di Home Assistant:

```
template:
  - sensor:
      temperatura_sala:
        friendly_name: "Temperatura della sala"
        value_template: '{{ states.climate.soggiorno.attributes.temperature }}'
        unit_of_measurement: "°C"
        icon_template: mdi:thermometer
```
Dopo aver verificato che non crei problemi utilizzando "Verifica Configurazione" e dopo aver verificato il suo effettivo funzionamento attraverso "Modelli" all'interno degli strumenti per sviluppatori di Home Assistant, provo a riavviare HA ma ottengo il seguente errore sui logs successivamente al riavvio:

```
Logger: homeassistant.config
Source: config.py:596
First occurred: 18:45:40 (1 occurrences)
Last logged: 18:45:40

Invalid config for 'template' at configuration.yaml, line 22: 'temperatura_sala' is an invalid option for 'template', check: sensor->0->temperatura_sala Invalid config for 'template' at configuration.yaml, line 22: required key 'state' not provided
```

Di cosa potrebbe trattarsi? Non capisco cosa abbia che non vada il nome "temperatura_sala" che ho assegnato al sensore, tra l'altro identico a quello proposto da voi nell'esercizio.
Grazie in anticipo!

**Comment by snakuzzo** [comment]
https://www.home-assistant.io/integrations/template/

```yaml
template:
  - sensor:
    - name: "temperatura_sala"
      value_template: "{{ state_attr('climate.soggiorno','temperature') | float }}"
      unit_of_measurement: "°C"
      icon_template: mdi:thermometer
```

**Reply by crug80** [reply]
Io sto provando ad usare "il nuovo modo" raccomandato. Ho i file di configurazione splittata, ergo:
Nel configuration:
```
template: !include_dir_merge_list templates/
```
Nel file templates/sensor_template.yaml:
```
sensor:
  - name: "m_potenza_impegnata_totale"
    unique_id: "m_potenza_impegnata_totale"
    device_class: power
    unit_of_measurement: "W"
    state: "{{ states(''sensor.lxp_ba12090474_grid_power_export_is_negative'') | float(0) + states(''sensor.lxp_ba12090474_inverter_power'') | float(0) }}"
```

Ma niente, l'entità non ne vuol sapere di apparire! (so che c'è l'helper ed infatti uso quello, ma sto facendo pratica con i template)
Idee?

**Reply by snakuzzo** [reply]
Premesso che in teoria non dovresti rispondere sotto lo stesso thread di una discussione con un problema diverso e che al massimo avresti dovuto creare un altro thread sotto la stessa discussione...

Tralasciando l'uso degli apici (quelli singoli scritti due volte non si possono vedere) e che potresti almeno condividere i log di core per capire se ti segnala qualche problema, dovresti leggere bene la documentazione...

https://www.home-assistant.io/docs/configuration/splitting_configuration/#example-include_dir_merge_list

...alla fine del paragrafo c'è scritto chiaramente...

> _It is important to note that when using !include_dir_merge_list, you must include a list in each file (each list item is denoted with a hyphen [-]). Each file may contain one or more entries._

**Reply by lnrd00** [reply]
>```
>template:
>  - sensor:
>    - name: "temperatura_sala"
>      value_template: "{{ state_attr('climate.soggiorno','temperature') | float }}"
>      unit_of_measurement: "°C"
>      icon_template: mdi:thermometer
>```

Ops...giusto! Grazie mille!

**Comment by KC-inDomus** [comment]
https://indomus.it/formazione/esercizi-di-domotica-su-home-assistant-1-creare-dei-sensori-template/

**Comment by crug80** [comment]
Premettendo che la domanda mi sembrava attinente, visto l'oggetto del thread e non ho capito la differenza fra "rispondere" o creare un thread sotto lo stesso oggetto, i log non mostravano errori da incollare. 
Applicando l'hyphen, le notifiche dicono che la piattaforma template non può essere configurata, ma nessun indicazione utile viene scritta nei log..   

P.S: gli esercizi linkati usano un modo diverso di creare i sensori template "legacy" che, come da documentazione ufficiale "This format still works but is no longer recommended."..

**Reply by snakuzzo** [reply]
Eppure non ci vuole tutta sta scienza per capire...comunque...

Ogni discussione può essere composta da uno o più thread.
Nel caso specifico tu avresti dovuto creare un nuovo thread (così come hai fatto ora) perché nelle altre risposte si stava dando supporto al problema specifico di dell'altro utente, che è si la stessa tematica, ma non c'entra una ceppa.

Tralasciando la nostra guida, che resta comunque valida anche se sulla doc ufficiale dicono che è raccomandata l'altra, hai letto il link che ho condiviso nel mio precedente messaggio?

**Reply by snakuzzo** [reply]
In sostanza il tuo file `templates/sensor_template.yaml` si scrive così

```yaml
- sensor:

    - name: "m_potenza_impegnata_totale"
      unique_id: "m_potenza_impegnata_totale"
      device_class: power
      unit_of_measurement: "W"
      state: "{{ states('sensor.lxp_ba12090474_grid_power_export_is_negative') | float(0) + states('sensor.lxp_ba12090474_inverter_power') | float(0) }}"
```

Ecco la dimostrazione (io l'ho chiamato `prova.yaml`

![image](https://github.com/indomus/forum/assets/7205371/1dfcfe16-83eb-4848-af81-6ca89e1e6061)

![image](https://github.com/indomus/forum/assets/7205371/6d146f64-abaa-4901-84d7-9f847228bc76)

Bastava leggere "bene" la documentazione ufficiale
