### DISCUSSION TITLE
Automazione click switch wireless -> input.select non funziona

### DISCUSSION THREAD

**Discussion by angelopampalone** [indomus/forum#287] [HUB: Home Assistant]
Salve a tutti, sto cercando, senza successo, di creare una automazione che cambi lo status di un'input select "input_select.luci_corridoio_override" alla pressione del pulsante di uno switch wireless "sensor.switch1_action" e che dopo un tempo definito in un input number "input_number.luci_corridoio_override_duration" reimposti la input select a "none".

Al momento HA riceve la pressione sullo switch e fa partire l'automazione: questa fa passare da "none" a "lights_on" lo stato di "input_select.luci_corridoio_override" ma non lo riporta a "none" dopo che il tempo indicato da "input_number.luci_corridoio_override_duration" è passato ne passa da "lights_on" a "lights_off" con un secondo click.

- L'input select "input_select.luci_corridoio_override" ha tre possibili stati: "none", "lights_on" e "lights_off"
- L'input number "input_number.luci_corridoio_override_duration" è impostato a 5 minuti.
- L'automazione è definita col seguente codice:
```
alias: Switch1
description: Gestisce gli stati di xxx alla pressione di Switch1
trigger:
  - platform: state
    entity_id: sensor.switch1_action
    to: single
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.luci_corridoio_override
            state: none
        sequence:
          - service: input_select.select_option
            target:
              entity_id: input_select.luci_corridoio_override
            data:
              option: lights_on
          - delay:
              hours: 0
              minutes: {{ states('input_number.luci_corridoio_override_duration')|int }}
              seconds: 0
              milliseconds: 0
          - service: input_select.select_option
            target:
              entity_id: input_select.luci_corridoio_override
            data:
              option: none
      - conditions:
          - condition: state
            entity_id: input_select.luci_corridoio_override
            state: lights_on
        sequence:
          - service: input_select.select_option
            target:
              entity_id: input_select.luci_corridoio_override
            data:
              option: lights_off
          - delay:
              hours: 0
              minutes: {{ states('input_number.luci_corridoio_override_duration')|int }}
              seconds: 0
              milliseconds: 0
      - conditions:
          - condition: state
            entity_id: input_select.luci_corridoio_override
            state: lights_off
        sequence:
          - service: input_select.select_option
            target:
              entity_id: input_select.luci_corridoio_override
            data:
              option: none
    default: []
mode: single
```

**Comment by Larry-78** [comment]
Ciao, non è molto chiara la sequenza che vorresti ottenere. Se non ho capito male se premi sw1 deve passare da 'none' a 'lights_on' e dopo il tempo stabilito da `input_number.luci_corridoio_override_duration` deve ritornare su 'none'. E se premi prima dei 5min una seconda volta? Deve passare su 'lights_off? E se si trova su 'lights_off', alla terza pressione in breve tempo, deve passare su 'none' senza alcuna eventuale attesa? Per quanto riguarda il `delay:` potresti scrivere in modo:
```yaml
- delay: "{{ states('input_number.luci_corridoio_override_duration') | multiply(60) | int }}"
```
se nel tuo `input_number.luci_corridoio_override_duration` imposti soltanto minuti.

**Reply by xyzmauro** [reply]
Effettivamente non è molto chiaro quello che vuoi ottenere alla fine, prova a dare un occhio anche a timer al posto di un input_number per il tempo che ha i suoi stati, eventi e servizi per farlo partire, metterlo in pausa, cancellarlo etc
https://www.home-assistant.io/integrations/timer/

**Reply by angelopampalone** [reply]
Ciao, grazie per l'input alla fine ho risolto tutto.

Io volevo ottenere un pulsante che ad ogni click cambiasse lo stato di un input select:
L'input select "luci_corridoio_override" ha come stato iniziale "none".
Premendo il pulsante lo stato passa a "lights_on" per x minuti e poi ritorna a "none".
Premendo il pulsante mentre lo stato di "luci_corridoio_override" è a "lights_on" lo stato passa "lights_off" per x minuti e poi ritorna a "none".

Questo mi serve perché ho una automazione che fa accendere le luci del corridoio quando il gruppo dei sensori del corridoio rileva movimento e dopo 5 minuti che non rileva più movimento le spegne.
Capita a volte che voglia mantenere le luci accese oppure spente nel corridoio indipendentemente dalle rilevazioni dei sensori e questa automazione gestirà questi casi eccezionali andando a valorizzare la select appropriatamente.

```
alias: Corridoio - Switch1
description: Gestisce gli stati di xxx alla pressione di Switch1
trigger:
  - platform: state
    entity_id: sensor.switch1_action
    to: single
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.luci_corridoio_override
            state: none
        sequence:
          - service: input_select.select_option
            target:
              entity_id: input_select.luci_corridoio_override
            data:
              option: lights_on
          - delay: >-
              00:{{
              states('input_number.luci_corridoio_override_duration')|int(0)
              }}:00
          - service: input_select.select_option
            target:
              entity_id: input_select.luci_corridoio_override
            data:
              option: none
      - conditions:
          - condition: state
            entity_id: input_select.luci_corridoio_override
            state: lights_on
        sequence:
          - service: input_select.select_option
            target:
              entity_id: input_select.luci_corridoio_override
            data:
              option: lights_off
          - delay: >-
              00:{{
              states('input_number.luci_corridoio_override_duration')|int(0)
              }}:00
          - service: input_select.select_option
            target:
              entity_id: input_select.luci_corridoio_override
            data:
              option: none
      - conditions:
          - condition: state
            entity_id: input_select.luci_corridoio_override
            state: lights_off
        sequence:
          - service: input_select.select_option
            target:
              entity_id: input_select.luci_corridoio_override
            data:
              option: none
    default: []
mode: restart
```

Ora che "input_select.luci_corridoio_override" ha lo stato che voglio; posso usarla come condiction nelle automation per accendere e spegnere le luci

_18/05/2021 Corretto il codice_

**Reply by angelopampalone** [reply]
Aggiungo l'automazione delle luci del corridoio nel caso possa essere d'inspirazione a qualcuno

```
alias: Corridoio - Luci on/off (v4)
description: >-
  Accende e spegne le luci in base alla rilevazione dei sensori di presenza (e
  gestisce gli override)
trigger:
  - platform: state
    entity_id: group.presenza_corridoio
    to: 'on'
condition: []
action:
  - condition: or
    conditions:
      - condition: state
        entity_id: input_select.luci_corridoio_override
        state: none
      - condition: state
        entity_id: input_select.luci_corridoio_override
        state: lights_on
  - service: light.turn_on
    target:
      entity_id: group.luci_corridoio
  - delay: '00:{{ states(''input_number.corridoio_timer_mins'')|int(0) }}:00'
  - condition: or
    conditions:
      - condition: state
        entity_id: input_select.luci_corridoio_override
        state: none
      - condition: state
        entity_id: input_select.luci_corridoio_override
        state: lights_off
  - service: light.turn_off
    target:
      entity_id: group.luci_corridoio
mode: restart
```
