### DISCUSSION TITLE
Errore nel " configuration.yaml " di Home Assistant

### DISCUSSION THREAD

**Discussion by lnrd00** [indomus/forum#2871] [HUB: Home Assistant]
Salve, scrivo sul forum per capire le motivazioni dietro ad un errore che ricevo quando carico Home Assistant col seguente `configuration.yaml` :

```
homeassistant:
  packages: !include_dir_named packages
sensor: !include sensors.yaml

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes


```

In particolare, l'errore è il seguente

```
ERROR (MainThread) [homeassistant.config] Invalid config for 'sensor' at configuration.yaml, line 3: required key 'platform' not provided, please check the docs at https://www.home-assistant.io/integrations/sensor
```

Per quanto dai logs mi sembri che sia un errore all'interno del `configuration.yaml`, ecco qui di seguito il contenuto del `sensors.yaml`:

```
homeassistant:
  time_zone: Europe/Rome

sensor:

  - platform: template
    sensors:
      temperatura_media:
        friendly_name: "Temperatura Media"
        value_template: >
         {{ (((state_attr('climate.soggiorno','temperature') | float) +
         (states.sensor.temperature_humidity_sensor_d59a_temperature.state | float))
         /2) | round(1, default=0) }}
        unit_of_measurement: "°C"
        icont_template: mdi:thermometer
```
Ho ovviamente verificato che ` {{ (((state_attr('climate.soggiorno','temperature') | float) +
         (states.sensor.temperature_humidity_sensor_d59a_temperature.state | float))
         /2) | round(1, default=0) }}` fornisse un valore che avesse senso e non riportasse errori, ma comunque non sembrerebbe che il problema si trovi lì, sempre a giudicare dai logs.

Scusate se magari ci sono errori gravi e banali, e grazie mille in anticipo!!

**Comment by snakuzzo** [comment]
Innanzi tutto `packages:` nel `configuration.yaml` va sotto `homeassistant:`...

```yaml
homeassistant:
  packages: !include_dir_named packages
```

Poi, quando utilizzi file sidecar, così come hai fatto per platform `sensor`, nel file sidecar non devi utilizzare di nuovo la chiave `sensor:`.
Inoltre, che c'entra nel `sensors.yaml` la definizione della timezone ?
Il file `sensors.yaml` sarà tipo...

```yaml
- platform: template
  sensors:
    temperatura_media:
    ...
```
