### DISCUSSION TITLE
Errore nelle notifiche Alexa

### DISCUSSION THREAD

**Discussion by Paoloc66** [indomus/forum#2890] [HUB: Home Assistant]
Ciao a tutti,
da un pò di giorni mi viene segnalato questo errore su un'automazione che utilizzo da oltre 1 anno (quando rientro a casa un Dot echo mi saluta e mi dice la temperatura).

L'errore è:

L'automazione "Rientro a casa" (automation.rientro_a_casa) ha un'azione che chiama un servizio sconosciuto: notify.alexa_media.

Questo errore impedisce il corretto funzionamento dell'automazione. Forse questo servizio non è più disponibile, o forse lo ha causato un errore di battitura.

Sapete aiutarmi? è cambiato qualcosa nelle notifiche?
Grazie

```
alias: Rientro a casa
description: ""
trigger:
  - platform: zone
    entity_id:
      - person.paolo
      - person.daniele
      - person.diego
    zone: zone.home
    event: enter
condition: []
action:
  - wait_template: "{{ is_state('binary_sensor.sensore_porta_contact', 'on') }}"
    timeout: "00:30:00"
    continue_on_timeout: "false"
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - type: turn_on
    device_id: 838ff182e0
    entity_id: light.luce_entrata
    domain: light
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: notify.media_player
    data:
      target:
        - media_player.echo_sala
      data:
        type: tts
      message: >
        {% if trigger.entity_id == 'person.paolo' %}
          "Bentornato Paolo"
        {% elif trigger.entity_id == 'person.daniele' %}
          "Bentornata Daniele"
        {% elif trigger.entity_id == 'person.diego' %}
          "Bentornata Diego"
        {% else %}
          {{ states('trigger.entity_id') }}
        {% endif %}

        "La temperatura media in casa è "
        {{((states("sensor.temperatura_sala_temperature")|float +
        states("sensor.temperatura_cucina_temperature")|float
        )/2)|float|round(1)}}
        gradi
mode: single
```
