### DISCUSSION TITLE
Contalitri ESP32 e Home Assistant

### DISCUSSION THREAD

**Discussion by albe92fire** [indomus/forum#2892] [HUB: Home Assistant]
Salve a tutti; mi chiamo Alberto e sono nuovo a postare, ho iniziato da qualche mese ad utilizzare Home Assistant e i vari dispositivi compatibili per domotizzare casa.

Attualmente sto lavorando al progetto di interfacciare un contalitri con lanciaimpulsi con HA attraverso un ESP32.

Il lanciaimpulsi del contalitri è normalmente chiuso con una resistenza di 47 ohm, quando "lancia" il segnale si apre appunto interrompendo la conduzione.

Attualmente ho configurato l'ESP32 con un codice trovato nella community che funziona egregiamente, ma, purtroppo non fa al caso mio, in quanto, conta quando il segnale è "HIGH" e non "LOW".

Senza dover creare una circuitazione dedicata, è possibile aggiustare il codice per far si che il conteggio funzioni al contrario? Ovvero che quanto è HIGH significa che il contatore è fermo e conti quando il circuito si apre?

Sotto il codice attuale:

```

esphome:
  name: esphome-web-cb492c
  friendly_name: water_meter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "psw"

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Cb492C"
    password: "psw"

captive_portal:

sensor:
  - platform: pulse_counter
    state_class: measurement
    name: "Acqua litri/min"
    id: waterlmin
    pin:
      number: GPIO35
      mode: input
    update_interval: 5s
    filters:
    - lambda: return (x / 1000); 
    unit_of_measurement: "l/min" 

  - platform: integration
    device_class: water
    state_class: total_increasing
    name: “Acqua m³"
    id: waterm3
    unit_of_measurement: "m³"
    accuracy_decimals: 7
    sensor: waterlmin
    time_unit: min
    icon: "mdi:water"
    filters:
      - lambda: return (x / 1);

```
Ringrazio in anticipo per il vostro aiuto.
