### DISCUSSION TITLE
Problema con time_pattern

### DISCUSSION THREAD

**Discussion by duedipicche** [indomus/forum#2930] [HUB: Home Assistant]
Vorrei sostituire una costante numerica con una variabile.
esempio:
```
trigger:
  -platform: time_pattern
    minutes: "/5"`
    id:` timer
```
con una simile:
```
trigger:
  -platform: time_pattern
    minutes: "/[variabile a mio piacimento tipo un input_number]"`
    id:` timer
```
Le soluzioni trovate propongono questo:
```
trigger: 
      - platform: template
        value_template: "{{ (now()|as_timestamp/60)|int % states('input_number.timer_ripristino')|int == 0 }}"
        id: timer_r
```
ma questo significa che se la mia variabile è uguale a 5 il trigger sarà vero solo al minuto 5 o ai suoi multipli e non ogni 5 minuti che non è la stessa cosa perché se io avvio un automazione al minuto 4 o 14 essa scatterà dopo un minuto al minuto 5  o 15.
Avete soluzioni. Grazie
