### DISCUSSION TITLE
Integrazione Sonoff ZigBee Bridge Pro (Con Zigbee2Tasmota) su Zigbee2MQTT

### DISCUSSION THREAD

**Discussion by lnrd00** [indomus/forum#2934] [ZigBee, Z-Wave, Thread, Matter]
Salve a tutti, avrei una domanda.
Ho seguito la guida inDomus per [Riprogrammare e usare ITEAD Sonoff ZigBee Bridge Pro (ZB Bridge-P) con firmware Tasmota](https://indomus.it/guide/riprogrammare-e-usare-itead-sonoff-zigbee-bridge-pro-zb-bridge-p-con-firmware-tasmota/) e in particolare il mio interesse è quello di usare Sonoff ZBBridge come antenna secondaria, ulteriore, che lavorerà da remoto rispetto all'antenna coordinator che ho installato su Raspberry.
Ipotizzando quindi di star seguendo la giusta sezione della guida, ovvero quella dove si spiega come impiegare Sonoff ZBBridge come coordinator remoto, mi ritrovo a dover inserire nel `Configuration.yaml` di zigbee2mqtt la seguente sezione di codice:

```
port:
  tcp://indirizzo_ip_tasmota:8888
```
dove ho sostituito a `indirizzo_ip_tasmota` l'indirizzo IP statico che ho assegnato al Sonoff ZBBridge.

**La mia domanda è**: avendo seguito anche la guida per [l'installazione del firmare RCP sull'antenna ZBDongle-E](https://indomus.it/guide/riprogrammare-il-firmware-di-itead-sonoff-zbdongle-e-zigbee-3-0-usb-dongle-plus-v2/#webapp), e avendo quindi nel `Configuration.yaml` di zigbee2mqtt la seguente situazione:

```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://ip-del-broker-mqtt
  user: *****
  password: *****
  version: 5
  include_device_information: true
serial:
  port: tcp://core-silabs-multiprotocol:9999
  adapter: ezsp
.
.
.
```
devo inserire `tcp://indirizzo_ip_tasmota:8888` insieme a ` tcp://core-silabs-multiprotocol:9999` oppure in un'altra sezione?

Grazie in anticipo!!
