### DISCUSSION TITLE
creazione file di testo con sorgente sensori modbus

### DISCUSSION THREAD

**Discussion by sp2003** [indomus/forum#2938] [HUB: Home Assistant]
ciao a tutti

ho 2 contatori energia eastron che leggo via modbus.
La configurazione è la seguente

```
- name: Eastron
  type: serial
  port: /dev/ttyUSB1
  baudrate: 9600
  bytesize: 8
  method: rtu
  parity: N
  stopbits: 1

  sensors:
    - name: 'consumo energia totale'
      unique_id: consumo_energia_totale
      address: 342
      slave: 2
      input_type: input
      precision: 2
      data_type: float32
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing

    - name: 'tensione'
      unique_id: tensione
      address: 0
      slave: 2
      input_type: input
      precision: 2
      data_type: float32
      unit_of_measurement: V
      device_class: voltage

    - name: 'corrente'
      unique_id: corrente
      address: 6
      slave: 2
      precision: 3
      input_type: input
      data_type: float32
      unit_of_measurement: A
      device_class: current

    - name: 'consumo live'
      unique_id: consumo_live
      address: 12
      slave: 2
      precision: 3
      input_type: input
      scale: 0.001
      data_type: float32
      unit_of_measurement: kW
      device_class: power
      
    - name: 'power factor'
      unique_id: power_factor
      address: 30
      slave: 2
      precision: 2
      input_type: input
      data_type: float32
#     unit_of_measurement: cosф
      device_class: power_factor

    - name: 'frequenza live'
      unique_id: frequenza_live
      address: 70
      slave: 2
      precision: 2
      input_type: input
      data_type: float32
      unit_of_measurement: Hz
      device_class: frequency

    - name: 'consumo energia totale pdc'
      unique_id: consumo_energia_totale_pdc
      address: 342
      slave: 6
      precision: 2
      input_type: input
      data_type: float32
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing

    - name: 'corrente pdc'
      unique_id: corrente_pdc
      address: 6
      slave: 6
      precision: 3
      input_type: input
      data_type: float32
      unit_of_measurement: A
      device_class: current

    - name: 'consumo live pdc'
      unique_id: consumo_live_pdc
      address: 12
      slave: 6
      precision: 3
      input_type: input
      scale: 0.001
      data_type: float32
      unit_of_measurement: kW
      device_class: power
```

partendo da questi, vorrei creare 2 files di testo (metern2.txt e metern6.txt) nella cartella /dev/shm di una installazione su mini PC di Core dockerizzata.
il contenuto di ogni file deve essere così

```
2(3785.80*W) <- il valore di consumo_live
2(26652232*Wh) <- il valore di consumo_energia_totale
2_1(217.70*V) <- il valore di tensione
2_2(17.87*A) <- il valore di corrente
2_3(50.00*Hz) <- il valore di frequenza_live
2_4(0.99*F) <- il valore di power_factor
```
il file metern6.txt è uguale ma ha come riferimento il contatore con ID 6 (slave 6).

come posso fare??
