### DISCUSSION TITLE
serviceIR e file docker-compose.yaml

### DISCUSSION THREAD

**Discussion by chip83** [indomus/forum#2982] [HUB: Home Assistant]
Dev'essere una cazzata ma non riesco a far andare al conifugrazione di serviceIR (per la gestione dei condizionatori tramite broadlink) nel file docker-compose.yaml:

all'interno di "service:", in coda al file, metto:

```
smartir: 

climate:
  - platform: smartir
    name: Panasonic
    device_code: 6116
    controller_data: nome_della_entità_remote_broadlink
    temperature_sensor: sensor.sensore_soggiorno_temperature
```

L'errore è: services.climate must be a mapping
Poi, a seconda di come formatto il testo, ho errori diversi (ovviamente).
Non capisco se smartir deve stare all'interno di serices o meno e se climate deve stare allo stesso livello di smartir...
