### DISCUSSION TITLE
Non so come fare per dimmerare le luci, riesco solo a accenderle e spegnerle

### DISCUSSION THREAD

**Discussion by framarfre** [indomus/forum#2983] [GENERALE - Discussioni generiche]
Come da titolo... sicuramente il problema è dato dalla mia inesperienza, ma sono ore che faccio tentativi e non so più dove sbattere la testa. In impostazioni, dispositivi, mqtt vado su **telecomando luci** (modello RODERET IKEA) col quale vorrei poter abbassare o aumentare la luminosità alle 3 lampadine (sempre ikea), vado in automazioni per aggiungere brightness_move_down poi in "Allora" scelgo commuta o spegni luce. Da adesso mentre tengo premuto per spegnere parte a spegnere le luci ma non si ferma nemmeno se tolgo il dito (come dovrebbe essere per decidere l'intensità della luce) cosa altro dovrei fare? Dove sbaglio? Ho provato a fare una ricerca ma sono finito fuori dal forum, scusatemi non sono pratico di questo sito, spero di ricevere una risposta risolutiva il più semplice possibile da capire e attuare, grazie.

**Comment by Scialla** [comment]
Non è del RODERET ma di quello precedente quindi, eventualmente, adatta i topic:
```
# La logica dell'automazione si basa sul "click" del payload del topic che pubblica il pulsante IKEA
# brightness_up -> dimmer up
# brightness_down -> dimmer down
# brightness_stop -> dimmer stop
# on -> lampada on (mantiene impostazione dimmer dello spegnimento)
# off -> lampada off

automation:     

- alias: automazione_dimmer_zigbee_ikea #piantana
  id: automazione_dimmer_zigbee_ikea
  initial_state: true
  # Imposto modalità restart perché se arriva un'altra publish dello stesso device...
  # ...devo interrompere quello che sto facendo e rieseguire l'automazione da capo
  mode: restart
  trigger:
  # L'automazione viene triggerata quando viene pubblicato il topic del pulsante IKEA...
  - platform: mqtt
    topic: 'zigbee2mqtt/IkeaSwitch/click'
  action:
  # Qui utilizzo la choose per valutare se dimmerare oppure fermarmi...
  - choose:
    ########################
    # BLOCCO PER DIMMERARE #
    ########################
    - conditions:
      - condition: or
        conditions:
        # Se brightness_down...
        - condition: template
          value_template: "{{ trigger.payload == 'brightness_down' }}"
        # ...oppure brightness_up
        - condition: template
          value_template: "{{ trigger.payload == 'brightness_up' }}"
      sequence:
      - repeat:
          # Finché...
          until:
          - condition: or
            conditions:
            # ...la luce non si spegne...
            - condition: state
              entity_id: light.koogeek_lb1_1f299c_lightbulb
              state: 'off'
            # ...oppure la luce non è alla massima luminosità (la luminosità va da 1 a 255)...
            - condition: template
              value_template: "{{ state_attr('light.koogeek_lb1_1f299c_lightbulb','brightness') | int(0) == 255 }}"
          # ...ripeto i seguenti passaggi:
          sequence:
          # Chiamo il servizio light.turn_on...
          - service: light.turn_on
            entity_id: light.koogeek_lb1_1f299c_lightbulb
            data:
              # ...aumentando o diminuendo la luminosità di 5...
              brightness: >-
                {% if trigger.payload == 'brightness_up' %}
                  {{ state_attr('light.koogeek_lb1_1f299c_lightbulb','brightness') | int(0) + 6 }}
                {% else %}
                  {{ state_attr('light.koogeek_lb1_1f299c_lightbulb','brightness') | int(0) - 3 }}
                {% endif %}
          # ...e aspetto un numero preciso di millisecondi
          # ...per rallentare e rendere più fluido il cambio di luminosità
          - delay:
              milliseconds: 70
    ######################
    # BLOCCO PER FERMARE #
    ######################
    - conditions:
      # Se brightness_stop
      - condition: template
        value_template: "{{ trigger.payload == 'brightness_stop' }}"
      # ...Aspetto 1 millisecondo. In pratica non faccio nulla. 
      # Mi serve solo per interrompere il dimmer
      sequence:
      - delay:
          milliseconds: 1
      # Questo accade perché l'automazione è impostata con mode repeat e quindi quando viene
      # ...nuovamente triggerata, interrompe quello che stava facendo e viene eseguita da capo
    #################
    # BLOCCO ON/OFF #
    #################
    - conditions:
      # Se ON
      - condition: template
        value_template: "{{ trigger.payload == 'on' }}"
      sequence:
      - service: light.turn_on
        entity_id: light.koogeek_lb1_1f299c_lightbulb
    - conditions:
      # Se OFF
      - condition: template
        value_template: "{{ trigger.payload == 'off' }}"
      sequence:
      - service: light.turn_off
        entity_id: light.koogeek_lb1_1f299c_lightbulb
 ```
        
Ringrazia @snakuzzo non me

Dimenticavo.... oltre ad aggiornare i topic e le entità, fai due prove con le tue lampadine per trovare il corretto valore da aggiungere o togliere

Ciauz
