### DISCUSSION TITLE
Aiuto Per Automazione

### DISCUSSION THREAD

**Discussion by michelesant** [indomus/forum#2989] [GENERALE - Discussioni generiche]
Ciao a tutti. Ho creato 2 automazione una per l'apertura di una valvola e una per la chiusura, collegata ad un bollitore. In pratica quando l'acqua al suo interno raggiunge i una temperatura di 42° , fa aprire una valvola e ne permette l'utilizzo, quando l'acqua scende sotto i 38° chiude la valvola e nel caso di richiesta fa partire la caldaia. L'unica cosa che non riesco a sistemare sono le notifiche, il mio obbiettivo è quello di ricevere una notifica su smartphone non appena l'acqua raggiunge i 42° e una quando scende sotto i 38°. Sia inserendole come azioni nelle Action delle automazioni già create, per aprire e chiudere le valvole boiler, le notifiche vengono ripetute ogni tot di minuti. Ho provato a creare 2 automazioni separate che controllano lo stato dello shelly se si on o si off, ma anche qui vengono ripetute. A me servirebbe un singola notifica. Sapete aiutarmi? Inoltre snakuzzo mi diceva che era possibile farlo con una sola automazione.

Di seguito le 2 Automazioni chiamare Boiler ON e Boiler OFF

```
alias: Boiler On
description: ""
trigger:
  - type: temperature
    platform: device
    device_id: f0467a9c1393b7bb79f0ac5f0a63b843
    entity_id: 0ca110382bf0b88cfa435383376a948b
    domain: sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
    above: 42
condition: []
action:
  - type: turn_on
    device_id: f0467a9c1393b7bb79f0ac5f0a63b843
    entity_id: 4913e62315bb454b516a505315caf525
    domain: switch
mode: restart
```

```
alias: Boiler Off
description: ""
trigger:
  - type: temperature
    platform: device
    device_id: f0467a9c1393b7bb79f0ac5f0a63b843
    entity_id: 0ca110382bf0b88cfa435383376a948b
    domain: sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
    below: 38
condition: []
action:
  - type: turn_off
    device_id: f0467a9c1393b7bb79f0ac5f0a63b843
    entity_id: 4913e62315bb454b516a505315caf525
    domain: switch
mode: restart
```

Per le notifiche sto utilizzando queste 2 automazioni:

```
alias: Notifica per Boiler ACS ON
description: ""
trigger:
  - platform: state
    entity_id:
      - switch.termostato_boiler
    from: "off"
    to: "on"
condition: []
action:
  - service: notify.mobile_app_xiaomi_pro
    metadata: {}
    data:
      message: Camino per ACS.
mode: single
```

```
alias: Notifica per Boiler ACS OFF
description: ""
trigger:
  - platform: state
    entity_id:
      - switch.termostato_boiler
    from: "on"
    to: "off"
condition: []
action:
  - service: notify.mobile_app_xiaomi_pro
    metadata: {}
    data:
      message: Caldaia per ACS.
mode: single
```

**Comment by snakuzzo** [comment]
Non c'è bisogno di fare 4 automazioni, te ne basta una sola e... consiglio spassionato...devi aggiungere il for nei trigger, altrimenti rischi che nel giro di pochi secondi sale e scende sopra i 42 o sotto i 38, scatta di continuo...

(ovviamente adegua con i nomi di entità tuoi...non so come si chiama il sensore che usi)

e... fare le automazioni con i device è una vera schifezza :)

```yaml
automation:

- id: gestione_boiler
  alias: Gestione boiler
  trigger:
  - id: temp_above_42
    platform: numeric_state
    entity_id: sensor.tuo_sensore
    above: 42
    for:
      minutes: 2
  - id: temp_below_38
    platform: numeric_state
    entity_id: sensor.tuo_sensore
    below: 38
    for:
      minutes: 2
  action:
  - choose:
    - conditions:
      # quando scatta il trigger che prevede il superamento della temperatura di 42°C
      - condition: trigger
        id: temp_above_42
      sequence:
      # Accende lo switch...
      - service: switch.turn_on
        data:
          entity_id: switch.termostato_boiler
      # ...e manda la notifica
      - service: notify.mobile_app_xiaomi_pro
        data:
          message: Camino per ACS
    - conditions:
      # quando invece scatta il trigger che prevede la temperatura sotto i 38°C
      - condition: trigger
        id: temp_below_38
      sequence:
      # Spegne lo switch...
      - service: switch.turn_on
        data:
          entity_id: switch.termostato_boiler
      # ...e manda la notifica
      - service: notify.mobile_app_xiaomi_pro
        data:
          message: Caldaia per ACS
```

**Comment by michelesant** [comment]
Grazie per la celere, risposta. Accetto i tuoi consigli, anche se la variazione di temperatura all'interno del boiler , riscaldato da un termocamino non è velocissima. L'importante è che se scende sotto i 38° la commutazione della valvola sia rapida e senza aspettare i 2 minuti.
Ho provato a creare la tua automazioni, ma mi dà sempre errore "Extra Key malformed:...@data[automation] e non riesco ad individuare l'errore.
Inoltre nell'ultima parte il trigger sotto i 38° il servizio non dovrebbe essere turn_off?

```
automation:
- id: gestione_boiler
  alias: Gestione boiler
  trigger:
  - id: temp_above_42
    platform: numeric_state
    entity_id: sensor.termostato_boiler_temperature
    above: 42
    for:
      minutes: 2
  - id: temp_below_38
    platform: numeric_state
    entity_id: sensor.termostato_boiler_temperature
    below: 38
    for:
      minutes: 2
  action:
  - choose:
    - conditions:
      # quando scatta il trigger che prevede il superamento della temperatura di 42°C
      - condition: trigger
        id: temp_above_42
      sequence:
      # Accende lo switch...
      - service: switch.turn_on
        data:
          entity_id: switch.termostato_boiler
      # ...e manda la notifica
      - service: notify.mobile_app_xiaomi_pro
        data:
          message: Camino per ACS
    - conditions:
      # quando invece scatta il trigger che prevede la temperatura sotto i 38°C
      - condition: trigger
        id: temp_below_38
      sequence:
      # Spegne lo switch...
      - service: switch.turn_on
        data:
          entity_id: switch.termostato_boiler
      # ...e manda la notifica
      - service: notify.mobile_app_xiaomi_pro
        data:
          message: Caldaia per ACS
```

**Reply by snakuzzo** [reply]
Dove hai messo l'automazione ?
Se lo stai facendo da GUI, non devi aggiungere `automation:` all'inizio.
Io ti ho postato il codice YAML da scrivere nei file YAML

**Reply by snakuzzo** [reply]
Allora...da GUI incollala così...
Ho tolto il trattino e l'id (che non serve se la fai da GUI). E ho adeguato anche il for per la temperatura sotto i 38°C

```yaml
alias: Gestione boiler
trigger:
  - id: temp_above_42
    platform: numeric_state
    entity_id: sensor.tuo_sensore
    above: 42
    for:
      minutes: 2
  - id: temp_below_38
    platform: numeric_state
    entity_id: sensor.tuo_sensore
    below: 38
    for:
      seconds: 15
action:
  - choose:
      - conditions:
          - condition: trigger
            id: temp_above_42
        sequence:
          - service: switch.turn_on
            data:
              entity_id: switch.termostato_boiler
          - service: notify.mobile_app_xiaomi_pro
            data:
              message: Camino per ACS
      - conditions:
          - condition: trigger
            id: temp_below_38
        sequence:
          - service: switch.turn_on
            data:
              entity_id: switch.termostato_boiler
          - service: notify.mobile_app_xiaomi_pro
            data:
              message: Caldaia per ACS
```

Guarda...

![image](https://github.com/indomus/forum/assets/7205371/393bf27a-bd5f-405e-91f8-df12bd5b6101)
