### DISCUSSION TITLE
Automazione Sensore Porta > Sirena

### DISCUSSION THREAD

**Discussion by Jones1982** [indomus/forum#30] [HUB: Home Assistant]
Buongiorno,
sto provando a creare questa automazione, ma non riesco a fissare le condizioni.
Così com'è qui sotto, suona indifferentemente dallo stato del sensore porta, o meglio.. suona quando cambia lo stato.
Poi devo spegnerla io a mano la sirena.
Avevo provato anche a inserire l'azione per spegnerla al cambio di stato della porta, ma suonava per 1 secondo e poi si staccava.

```
alias: Balcone - Sirena
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.sonoff_a48000bd70
condition: []
action:
  - type: turn_on
    device_id: 44013b9a5ea2f28b77892cca81479edf
    entity_id: switch.sirena_on_off
    domain: switch
mode: single
```

Devo aggiungere le 2 condizioni:
se rileva l'apertura del sensore porta, suona la sirena
se rileva la chiusura, spegne la sirena

Ho provato varie volte, ma da sempre errore condition ecc..

Grazie a chi mi aiuterà

**Comment by snakuzzo** [comment]
Per il codice devi usare il markdown. C'è il pulsantino apposito.
Modifica il contenuto del messaggio, altrimenti dovrò eliminarlo.

Grazie

**Reply by Jones1982** [reply]
Parli del pulsante <> ? 
mi mette solo 2 ' e basta!

**Reply by snakuzzo** [reply]
per favore...impara ad usare il markdown. Devi semplicemente racchiudere tra i backtick (non sono gli apici !!!! ). C'è il pulsante apposito.
Se scrivi un blocco di codice ce ne vogliono 3 prima e 3 alla fine.
Se scrivi tutto su una riga ne basta 1 prima e 1 alla fine.

Però non possiamo fare markdown learning...è una cosa che c'è da anni. Quindi per favore, correggi.
Grazie.

**Reply by Jones1982** [reply]
> per favore...impara ad usare il markdown. Devi semplicemente racchiudere tra i backtick (non sono gli apici !!!! ). C'è il pulsante apposito.
> Se scrivi un blocco di codice ce ne vogliono 3 prima e 3 alla fine.
> Se scrivi tutto su una riga ne basta 1 prima e 1 alla fine.
> 
> Però non possiamo fare markdown learning...è una cosa che c'è da anni. Quindi per favore, correggi.
> Grazie.

Dio santo, dove sta sto pulsante? In qualsiasi altro forum, premi il pulsante x il codice.. incolli il codice dentro, e posti! 

cmq era meglio l'altro forum... ahhaah   fatto! grazie cmq

p.s.: puoi rimuovere questi msg se vuoi, grazie

**Reply by snakuzzo** [reply]
Selezioni il codice e clicchi sul pulsantino del codice

**Comment by snakuzzo** [comment]
```yaml

  - alias: Balcone - Sirena
    trigger:
    - platform: state
      entity_id: binary_sensor.sonoff_a48000bd70
    action:
    - service: >
        {% if trigger.to_state.state == 'on' %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      data:
        entity_id: switch.sirena_on_off
```
