### DISCUSSION TITLE
Messaggio di benvenuto da google nest

### DISCUSSION THREAD

**Discussion by zolabus** [indomus/forum#301] [HUB: Home Assistant]
ciao a tutti,
sto provando a creare un'automazione che faccia dire "bentornato_nome_persona" al mio google nest quando un componente della famiglia apre la porta.
Ho un sensore sulla porta, ho configurato le person e ho creato le zone ed ogni telefono ha instalalto life360...
Il tutto sembra non funzionare...qualche suggeriemento?

```
- id: '1620554892604'
  alias: Messaggio arrivo casa Ale
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 231e46a0ea1741c1b091ace46aa59a79
    entity_id: binary_sensor.door_window_sensor_158d00033a9289
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: person.ale
    state: home
  - condition: template
    value_template: '{{ ((now() - states.person.ale.last_changed).seconds < 180 )
      }}'
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.nesthub
      message: Ciao ben arrivato Alessandro
```

**Comment by snakuzzo** [comment]
Ciao.
Correggi il codice usando il markdown, altrimenti dovrò cancellare il topic
Leggi [QUI](https://github.com/indomus/forum) il regolamento

**Reply by zolabus** [reply]
mah le ho già inserite...

**Reply by Larry-78** [reply]
Ciao, io utilizzo un approccio diverso, vedi un po' de riesci ad adattarla alle tue entità. 
Io sono in possesso di Alexa ma il concetto è lo stesso, si può utilizzare qualsiasi sistema di notifica. 
Il trigger dell'automazione è l'ingresso nella zona di casa definita poi ho inserito un `wait_for_trigger:` sul sensore della porta di ingresso con `timeout: '00:15:00'` e `continue_on_timeout: false` così se la porta verrà aperta entro 15min notificherà altrimenti l'automazione si fermerà. Ho preferito questo perché è capitato che il cell di mia moglie aveva agganciato il segnale GPS durante la giornata rimanendo in casa e dopo molte ore quando ho aperto la porta per uscire per andare a lavoro ho ricevuto il saluto di benvenuto.
Per la scelta del messaggio di benvenuto mi sono affidato ad una `choose:` che a seconda del trigger sceglierà chi salutare. Con Alexa c'è la possibilità di personalizzare le voci e ho aggiunto alcune frasi che verranno scelte random. 

```yaml
  alias: Saluto al rientro
  description: rientro a casa
  trigger:
  - platform: zone
    entity_id: person.lorenzo, person.adriana
    zone: zone.home
    event: enter
  condition: []
  action:
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.porta_ingresso
      to: 'on'
    timeout: 00:15:00
    continue_on_timeout: false
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.entity_id == ''person.lorenzo'' }}'
      sequence:
      - service: notify.alexa_media_echo_show_di_lorenzo
        data:
          message: '{{ [ "Bentornato a casa, Lorenzo!",  "Guarda chi si vede, ciao
            Lorenzo", "Casa dolce casa."] | random }}'
          data:
            type: tts
    - conditions:
      - condition: template
        value_template: '{{ trigger.entity_id == ''person.adriana'' }}'
      sequence:
      - service: notify.alexa_media_echo_show_di_lorenzo
        data:
          message: <voice name="Giorgio"> {{ ["La mamma è finalmente tornata a casa!",  "Bentornata
            a casa Adriana!",  "Guarda chi si vede, ciao Adriana!"] | random }} </voice>
          data:
            type: tts
    default: []
  mode: single
  ```
