### DISCUSSION TITLE
Script attivazione con Alexa tramite codice

### DISCUSSION THREAD

**Discussion by vincenzocoletta** [indomus/forum#3016] [GENERALE - Discussioni generiche]
Ciao, chiedo aiuto agli esperti per il seguente codice che avrebbe l'obiettivo di attivare tramite Alexa una luce solo a seguito dell'inserimento di un codice numerico predefinito (1234) e della verifica tramite sensore esterno che la luce sia effettivamente spenta (predisposizione per poi sostituire in futuro il controllo ed impostarlo su un sensore di luminosità).
Lo script non mi da errori ma non riesco a farlo funzionare come atteso e, dopo aver effettuato mille prove, chiedo cortesemente a chi ne sa più di me un aiuto ad individuare dove sbaglio. (P.S. il controllo sul codice l'ho impostato come "below: 1234" perchè non so come verificare l'uguaglianza...)

```

alias: Accensione Luce Soggiorno
sequence:
  - service: script.turn_on
    target:
      entity_id: script.activate_alexa_actionable_notification
    data:
      text: Qual è il codice per la luce soggiorno?
      event_id: aan_luce_soggiorno
      alexa_device: media_player.echo_camera
  - condition: and
    conditions:
      - condition: state_numeric
        entity_id: input_text.alexa_actionable_notification_response
        below: 1234
      - condition: state
        entity_id: binary_sensor.luce_soggiorno
        state: "off"
  - service: light.turn_on
    entity_id: light.soggiorno
  - service: notify.alexa_media
    data:
      target: media_player.echo_camera
      data:
        type: tts
      message: Attenzione, ho acceso la luce del soggiorno
  - service: notify.mobile_app_iphone
    metadata: {}
    data:
      message: Luce Soggiorno Accesa!!!
      title: "ATTENZIONE: "
mode: single

```

Segnalo che in modalità semplificata eliminando come segue il blocco "- service: script.turn_on" e riducendo la "  - condition: and" alla sola verifica sulla luce già accesa il tutto funziona regolarmente...

```

alias: Accensione Luce Soggiorno
sequence:
  - condition: state
     entity_id: binary_sensor.luce_soggiorno
     state: "off"
  - service: light.turn_on
    entity_id: light.soggiorno
  - service: notify.alexa_media
    data:
      target: media_player.echo_camera
      data:
        type: tts
      message: Attenzione, ho acceso la luce del soggiorno
  - service: notify.mobile_app_iphone
    metadata: {}
    data:
      message: Luce Soggiorno Accesa!!!
      title: "ATTENZIONE: "
mode: single

```

Grazie in anticipo!
