### DISCUSSION TITLE
Alexa: individuazione dispositivo che ha avviato la routine che attiva HA

### DISCUSSION THREAD

**Discussion by vincenzocoletta** [indomus/forum#3025] [GENERALE - Discussioni generiche]
Ciao, sarebbe utile nonché bello interagire con Alexa sullo stesso dispositivo dal quale si è attivata l’automation HA (tramite routine definita su Alexa). Qualcuno ci ha provato e/o ci è riuscito? Basterebbe “intercettare” il dispositivo che ha generato la domanda tra tutti quelli configurati e da li dovrebbe essere abbastanza semplice ma non sono ancora riuscito ad individuare un comando o una automazione che riesca a farlo. Potreste indicarmi una guida o un esempio che possa aiutarmi (qualora fosse fattibile…)?

**Comment by 2Max2Pax** [comment]
sensor.last_alexa

**Reply by vincenzocoletta** [reply]
Grazie! Sono riuscito a travare un po di indicazioni grazie alla tua segnalazione e quindi a far comunicare Alexa tramite l'ultimo device chiamato (con notify.alexa_media_last_called) ma non riesco ancora a trovare il modo per individuare il device. Una volta individuato lo passerei come "alexa_device" alla "activate_alexa_actionable_notification" rendendo quindi ogni mia interazione con Alexa automaticamente recepita e risposta dal device che ha iniziato la conversazione. Riesci a darmi ancora una mano?
A presto e grazie!

**Reply by 2Max2Pax** [reply]
Dunque, la logica di funzionamento di Alexa Actionable notifications dovrebbe essere funzionare grazie al fatto che tramite uno degli Echo presenti in caso lancio uno script che fa partire il botta e risposta. Ipotizziamo di avere echo_camera ed echo_sala. Entrambi possono far partire una determinata sequenza di botta e risposta e quindi voglio che quello partito echo_camera rimanga su echo_camera e quello partito da echo_sala rimanga su echo_sala.


L'esempio sul sito indomus e' semplice:
```

script:
  activate_alexa_actionable_notification:
    alias: activate_alexa_actionable_notification
    description: Attiva le notifiche azionabili verso uno specifico Amazon Echo
    fields:
      text:
        description: Il testo che si vuol far pronunciare ad Alexa.
        example: 'A che temperatura vuoi regolare il termostato?'
      event_id:
        description: Identificativo di risposta
        example: 'richiesta_temperatura'
      alexa_device:
        description: L'echo da utilizzare
        example: 'media_player.echo_camera'
      suppress_confirmation:
        description: Impostare a "true" se non si vuole conferma verbale da parte di Alexa
        example: 'true'
    sequence:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.alexa_actionable_notification
          value: '{"text": "{{ text }}", "event": "{{ event_id }}", "suppress_confirmation": "{{ suppress_confirmation }}"}'
      - service: media_player.play_media
        data_template:
          entity_id: "{{ alexa_device }}"
          media_content_type: skill
          media_content_id: <L'ID della skill creata in precedenza>
    mode: single
```
Io uso pyscript per i mei script, quindi potrei non usare la sintassi corretta, ma potresti sostituire **alexa_device** in questo modo:

```
alexa_device:
        description:  "{{ states('sensor.last_alexa') }}"
```

Potresti anche definire uno o piu' input_text in cui memorizzare l'Echo associato alle varie catene di botta e risposta.
