### DISCUSSION TITLE
Bad gateway - Error code 502 - Host error

### DISCUSSION THREAD

**Discussion by step9024** [indomus/forum#3027] [HUB: Home Assistant]
Ciao a tutti,

Mi presento, mi chiamo Stefano, sono uno smanettone e amante della tecnologia e ho deciso di immergermi nel mondo di Home Assistant. Ho scoperto il vostro sito e le vostre utilissime guide, per cui eccomi qui..... con un problema:

ho installato Home Assistant Core (su Docker) su un Raspberry Pi4.
Per poter accedere da remoto, ho configurato un tunnel con Cloudflare (dopo aver acquistato un dominio su Godaddy) e tutto ha funzionato alla grande fino a qualche giorno fa: non so se sia una casualità, ma nella notte tra il 2 e il 3 Aprile è saltata la corrente e il 3 è uscito un major update di HA. Dal 3 Aprile ha cominciato a comparire l'errore che ho scritto nel titolo.

Ho cercato su google (e anche qui su GitHub) ma non sono riuscito a risolvere niente, ho provato a riconfigurare i DNS con Cloudflare, nulla.

Non riesco veramente a capire cosa possa essere successo, Cloudflare dice che la configurazione DNS è "Healty", in locale tramite indirizzo ip:8123 accedo senza problemi.

Di seguito riporto la configurazione dei vari file .yaml

configuration.yaml
```
http:
    use_x_forwarded_for: true
    trusted_proxies:
    - 172.17.0.0/16
 ```

docker-compose.yaml
```
  cloudflared:
    container_name: cloudflared
    hostname: cloudflared
    image: cloudflare/cloudflared:latest
    restart: always
    volumes:
    - /home/deb/cloudflared:/home/nonroot/.cloudflared
    command: tunnel run 32c34920-75ff-4f10-9053-ad0013c162e1
```

config.yml
```
tunnel: 32c34920-75ff-4f10-9053-ad0013c162e1
credentials-file: /home/nonroot/.cloudflared/32c34920-75ff-4f10-9053-ad0013c162e1.json
url: http://ip_locale:8123
```

Nei log (impostazioni>sistema>registri) non mi sembra ci sia nulla di rilevante se non:

```
Registratore: aiohttp.server
Fonte: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
Prima occorrenza: 6 aprile 2024 alle ore 23:59:39 (184 occorrenze)
Ultima registrazione: 00:05:56

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^
```

Ma non sono sicuro che sia riferito al problema che ho io.

Premetto che non sono assolutamente un esperto, per cui sicuramente ci saranno inesattezze in quello che ho scritto.

Fatemi sapere se vi servono altre informazioni.

Spero di ricevere presto un aiuto.

Grazie!
Stefano
