### DISCUSSION TITLE
Gestione Timer a mezzo di input_number

### DISCUSSION THREAD

**Discussion by Maderik72** [indomus/forum#3029] [GENERALE - Discussioni generiche]
Ciao,
prima di scrivere ho provato a fare una ricerca sul Forum ma con poco successo.
Avrei la necessità di impostare un TIMER la cui durata è definita da un input_number.
Con l'helper non mi sembra fattibile, mi hanno detto che è possibile sia YAML ma non ho alcuna idea dove e come.

Riuscite ad indirizzarmi?
Grazie

**Comment by snakuzzo** [comment]
Ciao.
Ecco il package con quello che chiedevi

```yaml
# Qui viene definita l'entità di tipo timer con una durata di default in formato HH:mm:ss
timer:
  timer_template:
    name: "Timer template"
    duration: "00:00:00"

# Volevo utilizzare un input_datetime per definire la durata da utilizzare per il timer, ma purtroppo non è previsto l'utilizzo dei secondi.
# Quindi ho definito tre entità di tipo input_number. Una per le ore, una per i minuti e una per i secondi. Ovviamente cambia tu i dettagli in base alle tue esigenze.
input_number:

  timer_hours:
    name: Timer hours
    mode: box
    min: 0
    max: 23

  timer_minutes:
    name: Timer minutes
    mode: box
    min: 0
    max: 59

  timer_seconds:
    name: Timer seconds
    mode: box
    min: 0
    max: 59

# Questo invece è lo script che, quando lanciato, avvia il timer definito in alto con l'attributo "duration" impostato con ore, minuti e secondi definiti con le entità di tipo input_number
script:
  timer_start:
    alias: "Timer start"
    sequence:
        service: timer.start
        data:
          entity_id: timer.timer_template
          duration: "{{ states('input_number.timer_hours') | int }}:{{ states('input_number.timer_minutes') | int }}:{{ states('input_number.timer_seconds') | int }}"
```

Questa la card di tipo "Entities" che ti mostra come viene in dashboard e lo stato del timer pochi secondi dopo lo start lanciato con lo scrpit

![image](https://github.com/indomus/forum/assets/7205371/9678655f-1b62-4893-996a-ad76598a8485)
