### DISCUSSION TITLE
Problema con dispositivo ZigBee

### DISCUSSION THREAD

**Discussion by barbatrukko** [indomus/forum#3036] [HUB: Home Assistant]
Salve,
tramite Zigbee2MQTT e il dongle sonoff gestisco alcuni dispositivi.
Uno di questi è il sensore di porta SONOFF SNZB-04.
Fino a qualche tempo fa funzionava regolarmene, ma da un po' di tempo non mi notifica più quando la porta è aperta o chiusa.
Ho verificato e l'hub vede regolarmente il sensore (l'ho anche dissociato e riassociato).
Dal pannello di controllo vedo lo stato aperto chiuso della porta...
Allora sono andato a controllare l'automazione ed effettivamente pare non riesca a riconoscere l'entity_id

In pratica non vedo nell'auto completamento più questa entità **binary_sensor.porta_ingresso_contact**

_Error in describing trigger: Cannot read properties of undefined (reading 'entity_id')_

In realtà non c'è nulla di **binary_sensor.porta_ingresso**

Quindi non capisco se è cambiato qualcosa in HA su come viene gestito questo tipo di senore o se va riconfigurata qualcosa.

La mia automazione era molto semplice

```
alias: Allarme Porta Aperta
description: ""
trigger:
  - platform: state
    id: trigger_apertura_porta
    entity_id: binary_sensor.porta_ingresso_contact
    from: "off"
    to: "on"
condition: []
action:
  - service: notify.XXXXXXXXX
    data:
      title: "*Porta casa Aperta*"
      message: La porta di casa è Aperta
mode: single
```
