### DISCUSSION TITLE
DuckDNS & NGINX

### DISCUSSION THREAD

**Discussion by Nefasto78** [indomus/forum#3051] [HUB: Home Assistant]
Sono giorni che provo, ma sto impazzendo. Ho configurato duckdns per avere ssl, funziona tutto, faccio il port forward della porta 8123 su 443 e giustamente ottengo che home assistant si collega via https, naturalmente ora non è possibile collegarsi ad home assistant dall'interno della rete. Provo a risolvere questa problematica con NGINX ma non ci riesco... Configuro ed Avvio NGINX, apro la porta esterna 443 verso la 443 dell'ip di home assistant, modifico il configuration.yaml levando i collegamenti alle chiavi di let's encript. Naturalmente non va tutta la parte dei certificati e posso collegarmi solo tramite http. In realtà potrei anche evitare di battermi se non mi servisse https per collegarmi con smartthings. Qualcuno riuscirebbe ad aiutarmi? Grazie a tutti

**Comment by Nefasto78** [comment]
Per completezza inserisco parte del configuration.yaml
```
http:
    use_x_forwarded_for: true
    trusted_proxies:
        - 127.0.0.1
```
e visto che non l'avevo scritto prima, dico che il mio home assistant è ospitato da un raspberry pi.
Inserisco anche la configurazione di NGINX

```

domain: ***.duckdns.org
hsts: max-age=31536000; includeSubDomains
certfile: fullchain.pem
keyfile: privkey.pem
cloudflare: false
customize:
  active: false
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf

```
