### DISCUSSION TITLE
Home assistant e Alexa actionable notification

### DISCUSSION THREAD

**Discussion by dommyreg** [indomus/forum#3052] [HUB: Home Assistant]
Buongiorno ragazzi, ho seguito la  guida dal vostro sito internet per abilitare alexa actionable notification.

Ho inserito su home assistant tutto correttamente ma non mi viene accettata questa automazione quindi impossible salvarla copiando il vostro codice:

```
    id: "risposta_actionable_notifications"
    trigger:
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: aan_test
    variables:
      response_type: "{{ trigger.event.data.event_response_type }}"
      response: "{{ trigger.event.data.event_response }}"
    action:
    - service: input_text.set_value
      data:
        value: "{{ response_type }}"
      target:
        entity_id: input_text.alexa_actionable_notification_response_type
    - service: input_text.set_value
      data:
        value: "{{ response }}"
      target:
        entity_id: input_text.alexa_actionable_notification_response

```

Cosa dovrei correggere?
