### DISCUSSION TITLE
unire più automazioni

### DISCUSSION THREAD

**Discussion by efestopini** [indomus/forum#3054] [HUB: Home Assistant]
buongiorno, nonostante abbia letto le varie guide su come creare automazioni in yaml queste restano fuori dalla mia portata (spero di capirle prima o poi), quindi al momento le faccio con l' interfaccia grafica sapendo che sono più limitate, infatti per avere un po' di ordine vorrei unire tre automazioni diverse che nel' insieme mi permettono di accendere, spegnere e regolare l' intensità della luminosità con un pulsante con rotore, il codice delle tre automazioni e questo 
```
alias: pulsate con rotore camera genitori
description:
trigger:
  - platform: device
    domain: mqtt
    device_id: 8ac0f48cb6b05e50012551bf12e6dc67
    type: action
    subtype: single
condition: []
action:
  - service: light.toggle
    metadata: {}
    data: {}
    target:
      device_id: 5790ffe42fc652bec12d5e118abccd80
mode: single



alias: luce camera genitori su
description: ""
trigger:
  - platform: device
    domain: mqtt
    device_id: 8ac0f48cb6b05e50012551bf12e6dc67
    type: action
    subtype: rotate_right
condition: []
action:
  - device_id: 5790ffe42fc652bec12d5e118abccd80
    domain: light
    entity_id: f71d76a534356736a0afd9b3586d5aa6
    type: brightness_increase
mode: single



alias: luce camera genitori giù
description: ""
trigger:
  - platform: device
    domain: mqtt
    device_id: 8ac0f48cb6b05e50012551bf12e6dc67
    type: action
    subtype: rotate_left
condition: []
action:
  - device_id: 5790ffe42fc652bec12d5e118abccd80
    domain: light
    entity_id: f71d76a534356736a0afd9b3586d5aa6
    type: brightness_decrease
mode: single```

**Comment by Scialla** [comment]
Io ti consiglio davvero di provare a seguire le guide sul sito per imparare a fare le automazioni in yaml.
Come tu stesso puoi renderti conto, le automazioni fatte da GUI sono incomprensibili, dal nome dei device è impossibile risalire a cosa triggera e cosa viene comandato; in più, nel caso in cui tu dovessi sostituire il device con altro, devi riscriverti le automazioni, se lavori sulle entità invece basta dare lo stesso nome alla nuova che sostituisce la vecchia.

Premesso ciò, devi crearti una sola automazione che contenga tutti e tre i `trigger` e poi, usando una `choose`, fai scegliere, in base al `trigger` che è scattato (usando gli `id` dei `trigger` oppure le variabili dei trigger) la action da effettuare

https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions

https://www.home-assistant.io/docs/automation/templating/

**Reply by Scialla** [reply]
Come si chiama l'entità del tuo pulsante rotore? quella che corrisponde al `device_id: 5790ffe42fc652bec12d5e118abccd80` che hai usato come trigger
Anzi, che facciamo prima, che entità esponde su HA il tuo pulsante rotore e qual'é che contiene la `action` che sarebbe poi quello che nella tua automazione si chiama `subtype`?
Queste informazioni io non le conosco perché sei tu che le vedi sul tuo sistema
Se vai sulle impostazioni, dispositivi e servizi, sul tuo dispositivo, ti dà l'elenco delle entità esposte dal device

**Reply by Scialla** [reply]
Siccome sto per partire in ferie, il concetto comunque è qualcosa tipo questo:
```
  - alias: "Gestione Pulsante Rotore"
    id: "gestione_pulsante_rotore"
    mode: queued
    trigger:
      - platform: state
        entity_id: sensor.pulsante_rotore_action # al posto di questo sensore devi ovviamente mettere il tuo che espone il subtype
        to:
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'single' }}"
            sequence:
              - service: light.toggle
                entity_id: light.nome_entita_tua_luce
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'rotate_right' }}"
            sequence:
              - service: light.turn_on
                entity_id: light.nome_entita_tua_luce
                data:
                  brightness: {{ state_attr('light.nome_entita_tua_luce','brightness') | int(0) + 10 }}
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'rotate_left' }}"
            sequence:
              - service: light.turn_on
                entity_id: light.nome_entita_tua_luce
                data:
                  brightness: {{ state_attr('light.nome_entita_tua_luce','brightness') | int(0) - 10 }}
```
Poi si può fare anche in altri modi..
