### DISCUSSION TITLE
Alexa media player: funzionamento parziale

### DISCUSSION THREAD

**Discussion by Vinz1985** [indomus/forum#306] [HUB: Home Assistant]
Buongiorno ho provveduto ad installare Alexa media player seguendo la guida e sembra che sia arrivato a termine dell'installazione. Sono stati riconosciuti i miei 3 echo dot e sono state generate 3 entita media.player_nomeEcho.
Tuttavia ho un funzionamento parziale, nel senso che non riesco a far funzionare come chiamate di servizio ed altre cose e quindi non mi è utile cosi per le automazioni.  Ecco il problema che mi si pone quando vado a fare il payload?

Fallita chiamata a servizio notify.alexa_media . expected a dictionary for dictionary value @ data['sequence'][0]['target']. Got 'media_player.alexa'

Allego anche il service adottato:
 
Servizio
Notifiche: Send a notification with alexa_media

```
service: notify.alexa_media
data:
  type: announce
  method: spoken
target: media_player.alexa
```

Aiutatemi perchè sto impazzendo. Non è che c'è da aggiungere qualcosa nel configuration.yaml?

**Comment by KC-inDomus** [comment]
il messaggio che vuoi fargli pronunciare dov'è

**Reply by snakuzzo** [reply]
@Vinz1985 ... a parte il `message:` che manca, l'errore che ti dà è chiaro.
Gli hai passato `target: in modo sbagliato... gli hai passato una stringa al posto di un dictionary e te lo dice pure nel messaggio di log
Inoltre nella nostra guida non è scritto come hai postato tu, ma in questo modo...

```yaml
    - service: notify.alexa_media
      data:
        target:
          - media_player.alexa
        data:
          type: announce
          method: spoken
        message: "Bentornati a casa."
```

Come vedi si passa un dictionary a `target` e c'è anche il `message`

**Comment by Vinz1985** [comment]
tra service e data, posto screen:
![img](https://user-images.githubusercontent.com/83169955/118157453-dde73a80-b41a-11eb-9382-2032e95e615d.jpg)

**Comment by Vinz1985** [comment]
aggiungo l'errore direttamente dal registro, in cui si fa riferimento alle API.
![image](https://user-images.githubusercontent.com/83169955/118168048-b2b71800-b427-11eb-9c3e-50b21a73a4de.png)

**Reply by snakuzzo** [reply]
Ma perché scrivi apri sempre un thread diverso ?
Fai reply sotto uno stesso thread, no ?

**Reply by Vinz1985** [reply]
hai ragione, inizialmente non ho neanche messo tra tag il codice me ne sono accorto dopo e ho provveduto. E stato voluto in quanto, avendo allegato le immagini, potevo rendere più caotico per le dimensioni. Chiedo venia....

**Reply by snakuzzo** [reply]
Tranquillo ;)

**Reply by Larry-78** [reply]
ciao  @Vinz1985  invece di utilizzare il ` - service: notify.alexa_media` 
prova con il ` - service: notify.alexa_media_nomeEcho` di sicuro ne troverai uno personalizzato per ogni dispositivo integrato.
Per esempio nel mio caso:
```yaml
service: notify.alexa_media_echo_show_di_lorenzo
data:
  message: Questo è un messaggio di prova
  data:
    type: tts
```
cambiando il `type: tts` in `type: announce` otterrai un annuncio e sentirai un suono prima del messaggio.
