### DISCUSSION TITLE
Automazione per apertura tapparelle con calendario

### DISCUSSION THREAD

**Discussion by fregol** [indomus/forum#3063] [HUB: Home Assistant]
Ciao!
Ho impostato un calendario (calendar.scuola) in cui segno manualmente i giorni di vacanza dei bimbi. L'automazione dovrebbe rilevare se il giorno è un giorno di vacanza e far aprire le tapparelle all'ora indicata. 
Ho messo delle condizioni: che siamo a casa, che sia un giorno lavorativo e che nel calendario sia segnata Vacanza.
L'automazione non si avvia, cosa dovrei controllare?
```
alias: Apre Finestre bimbi alle 8.30 se vacanza
description: "Apri finestra sx bimbi alle 8.30 se nel calendario è vacanza "
trigger:
  - platform: time
    at: "08:30:00"
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('calendar.scuola', 'Vacanza') }}"
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: or
        conditions:
          - condition: zone
            entity_id: person.ga
            zone: zone.home
          - condition: zone
            entity_id: person.ma
            zone: zone.home
action:
  - device_id: e1942cc33cf20e428f2f3fbf9
    domain: cover
    entity_id: 821b1128796a1a27d7a80ab1
    type: set_position
    position: 15
mode: single
```

**Comment by snakuzzo** [comment]
Per cortesia, correggi il post usando il markdown per il codice ([QUI](https://github.com/indomus/forum/discussions/1311) è spiegato come), altrimenti la discussione verrà rimossa.
Grazie

**Comment by fregol** [comment]
Mi sono aiutato con chatgpt e credo di aver tirato fuori una soluzione, anche piu elegante. Ma onestamente non so come provarla senza aspettare che si verifichi!! 
Se gentilmente date un'occhiata e mi date un parere:
```
description: "Apre le finestre bimbi alle 9.30 se nel calendario è vacanza, we o festivo "
trigger:
  - platform: time
    at: "09:30:00"
condition:
  - condition: and
    conditions:
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ is_state('calendar.scuola', 'Vacanza') }}"
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: "off"
          - condition: time
            weekday:
              - sat
              - sun
      - condition: or
        conditions:
          - condition: zone
            entity_id: person.ga
            zone: zone.home
          - condition: zone
            entity_id: person.ma
            zone: zone.home
action:
  - device_id: e1942cc33cf20e428f2f3fbf9eadbc82
    domain: cover
    entity_id: 821b1128796a1a27d7a80ab1be908da2
    type: set_position
    position: 80
  - device_id: 5b86e86161fcb4e9be6466426a045ab7
    domain: cover
    entity_id: 603f5b336ba5742391d030c86f8f79c3
    type: set_position
    position: 80
mode: single
```
