### DISCUSSION TITLE
Configurazione MultiPAN RCP su LXC Proxmox con Sonoff ZBDongle-E

### DISCUSSION THREAD

**Discussion by marcogazzola** [indomus/forum#3064] [ZigBee, Z-Wave, Thread, Matter]
Ciao a tutti, 
oggi ho avuto la brillante idea di aggiornare il FW alla mia amata Sonoff ZBDongle-E per iniziare a giocare con matter.
Ho aggiornato il FW della Sonoff ZBDongle-E alla versione rcp-uart-802154-v4.3.1-zbdonglee-460800.gbl
Ho "installato" in docker il container "multipan" ghcr.io/b2un0/silabs-multipan-docker:latest 
di seguito riporto la configurazione del docker compose:
```yaml
  multipan:
    container_name: multipan
    image: ghcr.io/b2un0/silabs-multipan-docker:latest
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    restart: always
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyACM0
    volumes:
      - ./data/:/data
    environment:
      # OCPD environment variables
      DEVICE: "/dev/ttyACM0"
      BAUDRATE: "460800"
      CPCD_TRACE: "false"
      FLOW_CONTROL: "false"

      NETWORK_DEVICES: 0

      # OTBR-AGENT environment variables
      OTBR_ENABLE: 1
      BACKBONE_IF: "eth0@if6"
      OTBR_LOG_LEVEL: "debug"
      OTB_FIREWALL: 1
      OTBR_REST_LISTEN_PORT: "8081"

      # OTBR-WEB environment variables
      OTBR_WEB_PORT: "8186"


      # ZIGBEED environment variables
      EZSP_LISTEN_PORT: "20108"

      # UNIVERSAL FLASHER variables
      AUTOFLASH_FIRMWARE: 0
      FIRMWARE: "rcp-uart-802154-v4.3.1-zbdonglee-460800.gbl"
    ports:
      - "8081:8081"
      - "20108:20108"
      - "8186:8186"

```
![image](https://github.com/indomus/forum/assets/5739630/6f5e70ab-744e-4777-b10b-ccfd4568a5fb)

Questo l'errore che trovo nei log:

``
otbr-agent[12880]: 49d.18:23:04.724 [D] Platform------: Received spinel frame, flg:0x2, iid:2, tid:6, cmd:PROP_VALUE_IS, key:RADIO_CAPS, caps:255
otbr-agent[12880]: 49d.18:23:04.728 [C] Platform------: platformBackboneInit() at backbone.cpp:62: Failure
``

![image](https://github.com/indomus/forum/assets/5739630/419169df-e1c3-4fd8-a958-9b52b0750faf)

Poi, il prossimo step sarà Zigbee2mqtt.. ma ci penseremo a tempo debito!

Grazie
