### DISCUSSION TITLE
EspHome da remoto con MQTT

### DISCUSSION THREAD

**Discussion by AntonMusu** [indomus/forum#3073] [Hardware & Firmware]
Buonasera a tutti,
vorrei realizzare un sistema di irrigazione con controllo remoto. Sto usando come hardware un esp32 e un modulo con 4 relè. Riesco a far funzionare tutto in locale tramite EspHome installando il firmware nell'esp32. Il problema lo trovo integrando MQTT per farlo funzionare da remoto. In EspHome mi dice che l'esp32 è offline
Forse c'è un errore nel codice?  

```yaml
esphome:
  name: esp32-irri-asfo
  friendly_name: Esp32-Irri-Asfo
  platform: ESP32
  board: esp32dev
  build_path: build/esp32-irri-asfo

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXX"

ota:
  password: "XXX"

wifi:
  ssid: "RUT_C561_2G"
  password: ""

# Optional manual IP
  manual_ip:
    static_ip: 192.168.1.196
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Irri-Asfo Fallback Hotspot"
    password: ""

mqtt:
  topic_prefix: Irri-asfo
  discovery: false
  broker: indirizzo remoto duckdnd
  port: 1883
  username: mqtt_user
  password: ""

captive_portal:

output:
  - platform: gpio
    pin: GPIO27
    id: pump_relay
    inverted: True

  - platform: gpio
    pin: GPIO26
    id: valve_1_relay
    inverted: True

  - platform: gpio
    pin: GPIO25
    id: valve_2_relay
    inverted: True

  - platform: gpio
    pin: GPIO33
    id: valve_3_relay
    inverted: True

switch:
  - platform: output
    name: "Pompa"
    id: pump_switch
    output: pump_relay
    on_turn_on:
      then:
        - mqtt.publish:
            topic: "Irri-asfo/pump_relay"
            payload: "ON"
        - logger.log: "Pump relay turned ON"
    on_turn_off:
      then:
        - mqtt.publish:
            topic: "Irri-asfo/pump_relay"
            payload: "OFF"
        - logger.log: "Pump relay turned OFF"

  - platform: output
    name: "Valvola 1"
    id: valve_1_switch
    output: valve_1_relay
    on_turn_on:
      then:
        - mqtt.publish:
            topic: "Irri-asfo/valve_1_relay"
            payload: "ON"
        - logger.log: "Valve 1 relay turned ON"
    on_turn_off:
      then:
        - mqtt.publish:
            topic: "Irri-asfo/valve_1_relay"
            payload: "OFF"
        - logger.log: "Valve 1 relay turned OFF"

  - platform: output
    name: "Valvola 2"
    id: valve_2_switch
    output: valve_2_relay
    on_turn_on:
      then:
        - mqtt.publish:
            topic: "Irri-asfo/valve_2_relay"
            payload: "ON"
        - logger.log: "Valve 2 relay turned ON"
    on_turn_off:
      then:
        - mqtt.publish:
            topic: "Irri-asfo/valve_2_relay"
            payload: "OFF"
        - logger.log: "Valve 2 relay turned OFF"

  - platform: output
    name: "Valvola 3"
    id: valve_3_switch
    output: valve_3_relay
    on_turn_on:
      then:
        - mqtt.publish:
            topic: "Irri-asfo/valve_3_relay"
            payload: "ON"
        - logger.log: "Valve 3 relay turned ON"
    on_turn_off:
      then:
        - mqtt.publish:
            topic: "Irri-asfo/valve_3_relay"
            payload: "OFF"
        - logger.log: "Valve 3 relay turned OFF"
        - 
```
Questo invece è la fine del log

```
INFO Successfully compiled program.
INFO Connecting to 192.168.1.196
ERROR Connecting to 192.168.1.196:3232 failed: timed out

```
Qualcuno mi puo aiutare? Grazie

**Comment by KC-inDomus** [comment]
l'host sul quale è presente il broker mqtt è esposto a internet sulla 1883?

**Reply by AntonMusu** [reply]
Si la porta in uso su mqtt è la 1883

**Reply by snakuzzo** [reply]
L'errore che hai indicato alla fine credo c'entri poco con il discorso del broker MQTT.
Invece, per la parte MQTT, che riporto di seguito...

```yaml
mqtt:
  topic_prefix: Irri-asfo
  discovery: false
  broker: indirizzo remoto duckdnd
  port: 1883
  username: mqtt_user
  password: ""
```

...mi sembra strano che nei log non ci sia nulla realtivo alla connettività verso il broker MQTT.
Comunque...

1. Assicurati che sia effettivamente raggiungibile da internet. Prova una telnet da internet verso il tuo dominio su porta 1883

```
telnet tuodominio.duckdns.org 1883
```

2. Sei sicuro di aver impostato username e password correttamente ? Il broker MQTT prevede autenticazione oppure no ? Così come hai scritto gli stai passando username `mqtt_user` e password vuota. Le cose sono due...se il broker non prevede autenticazione, devi togliere proprio username e password dalla configurazione di esphome, se invece (come spero che sia, essendo esposto su internet come dici) prevede autenticazione, devi passargli username e password corretti...dubito che tu abbia impostato username e password vuota lato broker.
