### DISCUSSION TITLE
Automazioni Snelle

### DISCUSSION THREAD

**Discussion by PakyITA** [indomus/forum#3082] [HUB: Home Assistant]
Buonasera a tutti. Ho creato un’automazione di allarme che mi scatena diversi eventi.
Spiego meglio, quando uno dei sensori si attiva si scatenano i seguenti eventi:
1 arriva un messaggio di avviso sul mio iphone;
2 arriva un messaggio su telegram di avviso presenza in casa;
3 la cam scatta una foto e la salva;
4 ha invia la foto su telegram;
5 ha registra un video di 30 sec. Lo salva e poi lo invia…
E a seguire altri eventi.
Il probema principale e che contando i 30 sec ecc fino a che si scatenano i successivi eventi passano più di 30 sec. E se un latro entra in casa, ogni secondo è prezioso!
Non c è un modo x snellire o far partire le sequenze in un unico blocco? Non so se mi son spiegato. Ecco l’automazione:

```

alias: Allarme Casa ON/OFF 🏠 🚨
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.sensore_porta_ingresso_porta
    from: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.finestra_terrazzo_porta
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    enabled: false
  - platform: state
    entity_id:
      - binary_sensor.pir_sala_occupancy
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: state
    entity_id:
      - binary_sensor.cam_cucina_motion_alarm
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
condition:
  - condition: state
    entity_id: automation.allarme_on
    state: "on"
    enabled: true
action:
  - service: notify.mobile_app_iphone_di_paky
    data:
      message: Allarme Casa!
  - service: script.1709854897444
    metadata: {}
    data: {}
    enabled: true
  - service: camera.snapshot
    target:
      entity_id: camera.cam_cucina_profile000
    data:
      filename: /media/snapshots/cam_cucina_profile000/archive/last_motion.jpg
  - service: telegram_bot.send_message
    data:
      message: Allarme! Ce qualcuno in casa
      title: 🚨🚨🚨INTRUSIONE🚨🚨🚨
    enabled: true
  - service: telegram_bot.send_photo
    data:
      authentication: digest
      timeout: 10
      file: /media/snapshots/cam_cucina_profile000/archive/last_motion.jpg
      caption: Presenza Rilevata
  - service: camera.record
    metadata: {}
    data:
      duration: 30
      lookback: 0
      filename: /media/snapshots/cam_cucina_profile000/archive/last_vid.mp4
    target:
      entity_id: camera.cam_cucina_profile000
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.95
    target:
      entity_id: media_player.echo_dot_di_pasquale
    enabled: true
  - service: notify.alexa_media_echo_dot_di_pasquale
    metadata: {}
    data:
      message: >-
        Allarme!!! Chiamo Polizia!   Allarme!!! Chiamo Polizia!   Allarme!!!
        Chiamo Polizia!   Allarme!!! Chiamo Polizia!   Allarme!!! Chiamo
        Polizia!   Allarme!!! Chiamo Polizia!   Allarme!!! Chiamo Polizia!
    enabled: true
  - type: turn_on
    device_id: ab245a327ad496492bff0713b2a1959a
    entity_id: 145097c495877f3ba8b710fd14d527f0
    domain: switch
    enabled: true
  - device_id: a9a2260e55836827787d67fe45cb34f1
    domain: cover
    entity_id: 19f6ad3a7a99f1dc03e122315bf92279
    type: close
    enabled: true
  - device_id: 245493c53050794b81a3e854b18f33f5
    domain: cover
    entity_id: 4bf9b6240c8b2f8294814a4b9c1984ad
    type: close
    enabled: true
  - service: telegram_bot.send_video
    data:
      authentication: digest
      file: /media/snapshots/cam_cucina_profile000/archive/last_vid.mp4
      caption: Video Presenza Rilevata
      timeout: 10
  - service: notify.mobile_app_iphone_di_paky
    data:
      message: Presenza in Casa!!!
      data:
        push:
          sound:
            name: Presenza in Casa!!!Presenza in Casa!!!.wav
            critical: 1
            volume: 100
  - service: notify.mobile_app_sm_a137f
    data:
      message: TTS
      data:
        ttl: 0
        priority: high
        media_stream: alarm_stream_max
        tts_text: Presenza in casa!
mode: single

```
