### DISCUSSION TITLE
Come vedere il sensore template creato

### DISCUSSION THREAD

**Discussion by selo1982** [indomus/forum#3105] [GENERALE - Discussioni generiche]
ciao a tutti,
seguendo la guida di indomus ho provato a creare il mio primo sensore template.
ho inserito il codice nel configuration.yaml, senza avere errori, ma non trovo da nessuna parte il sensore creato.
Cosa sto sbagliando? sono nuovo dell'argomento e sto cercando di imparare grazie
il codice che ho inserito é il seguente:
```
template:
  - sensor:
    - name: "Consumo_totale_di_corrente"
      friendly_name: "Consumo totale di corrente"
      unit_of_measurement: "W"
      value_template: "{{ states('sensor.presa_lavatrice_taverna_consumo_di_corrente') | float(default=0) +
           states('sensor.presa_asciugatrice_consumo_di_corrente') | float(default=0) }}"
      icon_template: mdi:home-lightning-bolt-outline
```

**Comment by snakuzzo** [comment]
Riavvia Core, oppure vai sotto Opzioni sviluppatore > YAML > Ricarica entità di tipo template

**Reply by selo1982** [reply]
sì ho già riavviato ma non vedo ancora niente.
guardando i log in home-assistant.log ho i seguenti errori
```
2024-06-03 12:49:32.364 ERROR (MainThread) [homeassistant.config] Invalid config for 'template' at configuration.yaml, line 26: 'friendly_name' is an invalid option for 'template', check: sensor->0->friendly_name
Invalid config for 'template' at configuration.yaml, line 26: 'icon_template' is an invalid option for 'template', check: sensor->0->icon_template
Invalid config for 'template' at configuration.yaml, line 26: 'value_template' is an invalid option for 'template', check: sensor->0->value_template
Invalid config for 'template' at configuration.yaml, line 26: required key 'state' not provided
```

**Reply by snakuzzo** [reply]
Leggi i log e capisci... c'è scritto in maniera chiara cosa non va.

**Comment by selo1982** [comment]
per me non è stato per niente semplice :-) ...
il codice non era corretto. metto il codice corretto se può essere di aiuto per altre persone
```
sensor:
  - platform: template
    sensors:
      consumo_totale_corrente:
        friendly_name: "Consumo totale di corrente"
        unit_of_measurement: 'W'
        value_template: "{{ states('sensor.presa_lavatrice_taverna_consumo_di_corrente') | float(default=0) + states('sensor.presa_asciugatrice_consumo_di_corrente') | float(default=0) }}"
        icon_template: mdi:home-lightning-bolt-outline
```
