### DISCUSSION TITLE
HomeAssistant&Telegram: notifica doppia

### DISCUSSION THREAD

**Discussion by diegoves** [indomus/forum#3106] [HUB: Home Assistant]
ciao a tutti! ho creato su HACore (minipc) un’automazione in cui se la potenza rilevata da uno shelly passa la soglia dei 125W mi manda una notifica via telegram, tutto funziona il problema è che la notifica arriva sempre doppia 😅 la configurazione l’ho replicata dall’automazione che avevo creato su hassio all’interno di un QNAP, ma in quel caso la notifica è singola 😅qualcuno per piacere sa darmi una mano su dove poter controllare??
Per lo yaml dell'automazione ho questo:

```
alias: "Pompa di calore: attiva"
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.pompa_vmc_acs_power
    above: 125
    for:
      hours: 0
      minutes: 0
      seconds: 10
condition: []
action:
  - service: notify.hacore_diegoves
    data:
      message: "Pompa di calore: attiva"
mode: single

```
