### DISCUSSION TITLE
Automazione wallbox e solare

### DISCUSSION THREAD

**Discussion by gideonklein** [indomus/forum#3109] [HUB: Home Assistant]
Carissimi, ho bisogno del vostro ingegno perchè non so da dove iniziare per un'automazione. Ho tutti i sensori dell'inverter riguardo l'impianto solare e tutti i sensori della wallbox. Mi servirebbe un'automazione che mi ricarichi la macchina solo con il solare. Come sapete, i pannelli producono sempre in maniera diversa in base all'orario e anche alle nuvole che possono esserci. Fino ad ora, ho caricato facendo tutto manualmente (cioè aumentando la potenza erogazione al veicolo in base alla produzione solare) ma vorrei automatizzare tutto così che inserito il connettore di ricarica faccia tutto da solo.
Il principio dovrebbe essere questo: 
Automazione:
Carica veicolo con il sole:
Quando i pannelli producono minimo 3 kWh e la batteria è carica minimo al 50% eroga corrente al veicolo cominciando con 8A e aumentare a 10A, 12A, 14A, 16A, 18A, 20A, etc (cio+ di 2 step per volta) se il solare aumenta progressivamente la produzione (e aumenta fino a 8kWh). Quindi diminuire gli ampere progressivamente se il sole viene coperto da nuvole per piu di 2 minuti e quando poi finisce il solare fino a spegnere la wallbox. Ho tutti i sensori ma non so come fare l'automazione. Qualche buona persona può aiutarmi? Una cosa del genere la fanno alcune wallbox che costano intorno a 1.500 euro integrabili con home assistant ma vorrei fare la stessa cosa con un'automazione. Grazie anticipatamente

**Comment by gideonklein** [comment]
Questa è l'automazione che sono riuscito a fare, non ha errori ma non so se funzionerà, domani la provo

```
alias: Nuova automazione
description: Carica veicolo con il sole
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.axpert_plus_pv_power
    above: 3001
    below: 4000
    attribute: W
condition:
  - condition: numeric_state
    entity_id: sensor.axpert_plus_battery_state_of_charge
    above: 50
    attribute: "%"
action:
  - service: select.select_option
    metadata: {}
    data:
      option: Start charging
    target:
      entity_id: select.ev_charger_toggle_charging
  - service: number.set_value
    metadata: {}
    data:
      value: "8"
    target:
      entity_id: number.ev_charger_set_charge_current
  - if:
      - condition: numeric_state
        entity_id: sensor.axpert_plus_pv_power
        above: 4001
        attribute: W
        below: 5000
    then:
      - service: number.set_value
        metadata: {}
        data:
          value: "12"
        target:
          entity_id: number.ev_charger_set_charge_current
  - if:
      - condition: numeric_state
        entity_id: sensor.axpert_plus_pv_power
        above: 5001
        attribute: W
        below: 6000
    then:
      - service: number.set_value
        metadata: {}
        data:
          value: "16"
        target:
          entity_id: number.ev_charger_set_charge_current
  - if:
      - condition: numeric_state
        entity_id: sensor.axpert_plus_pv_power
        above: 6001
        attribute: W
        below: 7000
    then:
      - service: number.set_value
        metadata: {}
        data:
          value: "20"
        target:
          entity_id: number.ev_charger_set_charge_current
  - if:
      - condition: numeric_state
        entity_id: sensor.axpert_plus_pv_power
        above: 7001
        attribute: W
        below: 8000
    then:
      - service: number.set_value
        metadata: {}
        data:
          value: "24"
        target:
          entity_id: number.ev_charger_set_charge_current
  - if:
      - condition: numeric_state
        entity_id: sensor.axpert_plus_pv_power
        above: 2000
        attribute: W
        below: 3000
    then:
      - service: select.select_option
        metadata: {}
        data:
          option: Stop charging
        target:
          entity_id: select.ev_charger_toggle_charging
mode: single

```
