### DISCUSSION TITLE
Anomalia accensione attraverso un automazione di una lampada Meross msl120d

### DISCUSSION THREAD

**Discussion by mikycol** [indomus/forum#3112] [HUB: Home Assistant]
``Uso 3 di queste lampade da anni, ho scritto un automazione che le accende all'imbrunire e le spegne all'alba, ha funzionato tutto senza problemi fino a qualche settimana fa (non so definire quando, perché pensavo che il problema fosse la indisponibilità del wifi a causa di nuova rete del vicino). Solo ieri mi sono reso conto che la lampadina se pigio il pulsante su Home Assistant si accende e spegne senza problemi, ma se lo faccio fare ad un automazione non si accende, facendo il trace il comando viene passato correttamente, ma come se non fosse eseguito. L'integrazione con le lampade è attraverso meross_lan.
Questa l'automazione:
```yaml
alias: Esterno - Accensione Faretto e Luce Ingresso
description: ""
trigger:
  - platform: sun
    event: sunset
condition: []
action:
  - service: notify.michele
    data:
      title: Domotica - Esterno
      message: Accese luci fuori
  - service: light.turn_on
    target:
      entity_id: light.luce_ingresso
    data:
      brightness_pct: 100
      kelvin: 2000
  - service: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.luci_esterne
mode: single
```
A qualcuno è successo?
