### DISCUSSION TITLE
Consiglio personalizzazione card

### DISCUSSION THREAD

**Discussion by michele-diurno** [indomus/forum#3118] [GENERALE - Discussioni generiche]
Ciao a tutti,
sono alle prime armi con HA, vorrei modificare la card climate mushroom facendo in modo che l'icona della ventola possa girare quando clicco per accendere il climatizzatore. Come posso riuscire?
![Card climatizzatori](https://github.com/indomus/forum/assets/164509259/1b77396f-9830-4c6c-b396-9bf86f7bbb8a)

Il codice è il seguente:
```
title: Climatizzatori
type: vertical-stack
cards:
  - type: custom:mushroom-climate-card
    entity: climate.cucina
    icon: mdi:fan
    layout: vertical
    show_temperature_control: true
    collapsible_controls: true
    tap_action:
      action: toggle
    hvac_modes:
      - cool
    hold_action:
      action: none
    double_tap_action:
      action: none
```

Grazie a tutti in anticipo.
