### DISCUSSION TITLE
Problemi con climate.set_hvac = cool

### DISCUSSION THREAD

**Discussion by silvano90** [indomus/forum#3134] [HUB: Home Assistant]
Ciao a tutti,
vi illustro la problematica:
ho due condizionatori identici (condizionatore1 e condizionatore2 da qui in avanti) per i quali ho configurato smartir in combinazione a due broadlink. L'integrazione ha sempre funzionato correttamente fino all'altro giorno, momento in cui ha smesso di funzionare esclusivamente l'impostazione "freddo" sul condizionatore2. Quindi la sintomatologia e' la seguente:
Condizionatore2: 
- clicco il tasto su HA per il caldo -> il condizionatore si accende, 
- clicco il tasto di HA per il freddo -> il condizionatore non si accedende,
- triggero il servizio climate.set_hvac_mode con hvac = cool -> il condizionatore non si accende
- replico quanto sopra con hvac = heat -> il condizionatore si accende
onestamente non riesco a comprendere la differenza di comportamento soprattutto considerando che il condizionatore 1 e' impostato nella medesima maniera e funziona perfettamente.
riporto la configurazione del componente per completezza:
```
smartir:
climate:
  - platform: smartir
    name: Condizionatore_Sala
    device_code: 1137
    controller_data: remote.telecomando_sala
    temperature_sensor: sensor.multi_sensor_2
    humidity_sensor: sensor.multi_sensor_2_2
#    power_sensor: binary_sensor.Condizionatore_Sala_ONOFF
  - platform: smartir
    name: Condizionatore_Camera
    device_code: 1137
    controller_data: remote.zhi_neng_yao_kong
    temperature_sensor: sensor.multi_sensor_1
    humidity_sensor: sensor.multi_sensor_1_2
#    power_sensor: binary_sensor.Condizionatore_Camera_ONOFF
```
grazie,
Silvano

**Comment by Scialla** [comment]
però così ci va la sfera di cristallo....
prova a dare evidenza dei log sia di quando accetta il comando che di quando non lo accetta.
Se i log non chiacchierano metti a debug il componente e riprova

Dai anche un'occhiata qua se trovi qualcun altro che ha riportato il tuo stesso problema:
https://github.com/smartHomeHub/SmartIR/issues

**Reply by silvano90** [reply]
Ciao, il log non segnala niente quando lancio il servizio, e non so dove attivare il debug per smartir (di solito andrei in integrazioni, ma smartir e' installato via HACS e non mi compare nel tab integrazioni). 
Dal link che mi hai mandato ho scoperto pero' delle modifiche ai codici per quel dispositivo. Resta comunque un mistero del perche' due dispositivi identici recepiscano due set di codici diversi.
Probabilmente vale la pena lasciare aperto il thread, l'issue di per se non e' risolta e' solo stato risolto un workaround...

**Reply by Scialla** [reply]
con core lo imposti nel `configuration.yaml`
```
logger:
  default: info
  logs:
    custom_components.smartir: debug
```
poi ti guardi il log di sistema
