### DISCUSSION TITLE
z2m: Error: Failed to connect to the adapter [Home Assistant Core su docker e Ubuntu MiniPC]

### DISCUSSION THREAD

**Discussion by skantaman** [indomus/forum#3136] [ZigBee, Z-Wave, Thread, Matter]
Salve a tutti,
ho da qualche giorno formattato il mio minipc per migrare da HASSOS a Core su docker
installando Ubuntu.
Ho configurato tutto senza problemi finchè non mi sono scontrato con l'implementazione relativa a Zigbee:
ovviamente l'hardware è lo stesso che usavo con HASSOS e il coordinator è un Sonoff Zigbee 3.0 USB Dongle Plus V2 
flashato con firmware RCP Multipan (v 4.3.1 dati gli errori con le altre versioni).
Premetto che visitando il link (https://darkxst.github.io/silabs-firmware-builder/ ) da Ubuntu non riesco a vedere il coordinator, mentre eseguendo lo script ports.sh l'output è questo:
```
/dev/bus/usb/001/006 - ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231216170615
/dev/ttyACM0 - ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231216170615
/dev/bus/usb/001/001 - Linux_6.8.0-36-generic_xhci-hcd_xHCI_Host_Controller_0000:00:14.0
/dev/bus/usb/001/003 - Realtek_Bluetooth_Radio_00e04c000001
/dev/bus/usb/002/001 - Linux_6.8.0-36-generic_xhci-hcd_xHCI_Host_Controller_0000:00:14.0
```

L'errore che leggo nei log del container zigbee2mqtt  è il seguente:

```
Starting Zigbee2MQTT without watchdog.
[2024-07-02 17:46:57] info: 	z2m: Logging to console, file (filename: log.log)
[2024-07-02 17:46:57] info: 	z2m: Starting Zigbee2MQTT version 1.39.0 (commit #0326926)
[2024-07-02 17:46:57] info: 	z2m: Starting zigbee-herdsman (0.50.1)
[2024-07-02 17:46:57] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2024-07-02 17:46:57] info: 	zh:zstack:znp: Serialport opened
[2024-07-02 17:46:57] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-07-02 17:46:59] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-07-02 17:47:17] error: 	z2m: Error while starting zigbee-herdsman
[2024-07-02 17:47:17] error: 	z2m: Failed to start zigbee
[2024-07-02 17:47:17] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-07-02 17:47:17] error: 	z2m: Exiting...
[2024-07-02 17:47:17] error: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:101:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:129:29)
    at Zigbee.start (/app/lib/zigbee.ts:63:27)
    at Controller.start (/app/lib/controller.ts:139:27)
    at start (/app/index.js:154:5)
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-07-02 17:47:20] info: 	z2m: Logging to console, file (filename: log.log)
[2024-07-02 17:47:20] info: 	z2m: Starting Zigbee2MQTT version 1.39.0 (commit #0326926)
[2024-07-02 17:47:20] info: 	z2m: Starting zigbee-herdsman (0.50.1)
[2024-07-02 17:47:21] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2024-07-02 17:47:21] info: 	zh:zstack:znp: Serialport opened
[2024-07-02 17:47:21] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-07-02 17:47:23] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-07-02 17:47:41] error: 	z2m: Error while starting zigbee-herdsman
[2024-07-02 17:47:41] error: 	z2m: Failed to start zigbee
[2024-07-02 17:47:41] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-07-02 17:47:41] error: 	z2m: Exiting...
[2024-07-02 17:47:41] error: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:101:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:129:29)
    at Zigbee.start (/app/lib/zigbee.ts:63:27)
    at Controller.start (/app/lib/controller.ts:139:27)
    at start (/app/index.js:154:5)

```

Mi collego al minipc tramite anydesk e da Ubuntu lancio i comandi da terminale nelle directory di docker (non uso ssh).
Allego i vari file di configurazione e gli output dei comandi che ho usato.
Grazie a chiunque riuscirà a darmi una mano.

**docker-compose.yaml**
```
services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
    - ~/homeassistant/.homeassistant:/config
    environment:
    - TZ=Europe/Rome
    network_mode: host
    restart: always
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - TZ=Europe/Rome
      - PLEX_CLAIM=claim-********
    network_mode: host
    volumes:
      - ../plex/config:/config
      - ../plex/transcode:/transcode
      - ../plex/media/tvseries:/tv
    devices:
      - /dev/dri:/dev/dri
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
    - "../../../srv/mosquitto/config:/mosquitto/config"
    - "../../../srv/mosquitto/log:/mosquitto/log"
    - "../../../srv/mosquitto/data/:/mosquitto/data"
    restart: always
    ports:
    - "1883:1883"
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
    - "~/zigbee2mqtt:/app/data"
    devices:
    - /dev/ttyACM0
    environment:
    - "TZ=Europe/Rome"
    network_mode: host
    restart: always
  multipan:
    container_name: multipan
    image: b2un0/silabs-multipan-docker
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    restart: always
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyACM0
    volumes:
      - ./data/:/data
    environment:
      # OCPD environment variables
      DEVICE: "/dev/ttyACM0"
      BAUDRATE: "460800"
      CPCD_TRACE: "false"
      FLOW_CONTROL: "false"
      NETWORK_DEVICES: 0
      # OTBR-AGENT environment variables
      OTBR_ENABLE: 1
      BACKBONE_IF: "enp1s0"
      OTBR_LOG_LEVEL: "debug"
      OTB_FIREWALL: 1
      OTBR_REST_LISTEN_PORT: "8081"
      # OTBR-WEB environment variables
      OTBR_WEB_PORT: "8086"
      # SOCAT environment variables
      NETWORK_DEVICE: ""
      # ZIGBEED environment variables
      EZSP_LISTEN_PORT: "9999"
      # UNIVERSAL FLASHER variables
      AUTOFLASH_FIRMWARE: 0
      FIRMWARE: "86"
```
**zigbee2mqtt configuration.yaml**
```
# Autodiscovery su Home Assistant abilitato
homeassistant: false
# Join alla rete MQTT disabilitato di default
permit_join: false
# MQTT settings
mqtt:
  # MQTT base topic per i messaggi di zigbee2mqtt
  base_topic: zigbee2mqtt
  # MQTT server - URL (indirizzo LAN)
  server: 'mqtt://core-mosquitto:1883'
  # MQTT server - Parametri di autenticazione (decommentare e popolare correttamente se si utilizzano credenziali per la connessione al broker MQTT
  user: NOME UTENTE PER ACCESSO SU FRONTEND DI HOME ASSISTANT
  password: PASSWORD DI ACCESSO AL FRONTEND DI HOME ASSISTANT
  include_device_information: true
serial:
  # Porta su cui è mappata l'antenna zigbee
  port: tcp://core-silabs-multiprotocol:9999
  adapter: ezsp
advanced:
  # Directory in cui verrà salvato il file di log
  log_directory: /var/log
experimental: {}
frontend:
  # porta su cui verrà esposta la webGUI
  port: 8080
ota:
  update_check_interval: 10
disable_automatic_update_check: false
```

**mosquitto.conf**
```
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
listener 1883
password_file /mosquitto/config/mosquitto.passwd


allow_anonymous false
```

**mosquitto.passwd**
`skantaman:$******`

**Comment by KC-inDomus** [comment]
silicon labs multiprotocol sale correttamente? hai evidenza dai log?

**Comment by skantaman** [comment]
Ti allego i log di multipan:
[multipan_log.txt](https://github.com/user-attachments/files/16097389/multipan_log.txt)

Grazie

**Reply by KC-inDomus** [reply]
```
otbr-agent[2853600]: 56d.11:56:50.973 [C] Platform------: CPC endpoint open failed
otbr-agent[2853600]: 56d.11:56:50.974 [C] Platform------: mCpcBusSpeed = 115200
otbr-agent[2853600]: 56d.11:56:50.974 [C] Platform------: Init() at radio.cpp:121: Failure
close cpc endpoint: Success
2024-07-04 10:32:05 [INFO] otbr-agent ended with exit code 1 (signal 0)...
```

non sale. concentrati su questo, se silicon labs non parte, non ti funzionerà ma l'intero stack.

**Comment by skantaman** [comment]
Ciao KC,
il log attuale di multipan è il seguente 
[log_multipan1507.txt](https://github.com/user-attachments/files/16231470/log_multipan1507.txt)
dovrei aver risolto commentando dentro il docker-compose.yaml il blocco "devices"

multipan:
    container_name: multipan
    image: b2un0/silabs-multipan-docker
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    restart: always
    privileged: true
    network_mode: host
   # devices:
    #  - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231216170615-if00:/dev/ttyACM0
    volumes:
      - ./data/:/data
    environment:
      # OCPD environment variables
      DEVICE: "/dev/ttyACM0"
      BAUDRATE: "460800"
      CPCD_TRACE: "false"
      FLOW_CONTROL: "false"
      NETWORK_DEVICES: 0
      # OTBR-AGENT environment variables
      OTBR_ENABLE: 1
      BACKBONE_IF: "enp1s0"
      OTBR_LOG_LEVEL: "debug"
      OTB_FIREWALL: 1
      OTBR_REST_LISTEN_PORT: "8081"
      # OTBR-WEB environment variables
      OTBR_WEB_PORT: "8086"
      # SOCAT environment variables
      NETWORK_DEVICE: ""
      # ZIGBEED environment variables
      EZSP_LISTEN_PORT: "9999"
      # UNIVERSAL FLASHER variables
      AUTOFLASH_FIRMWARE: 0
      FIRMWARE: "86"

Purtroppo continuo a beccare l'errore su zigbee2mqtt
`Starting Zigbee2MQTT without watchdog.
[2024-07-15 09:55:37] info: 	z2m: Logging to console, file (filename: log.log)
[2024-07-15 09:55:37] info: 	z2m: Starting Zigbee2MQTT version 1.39.0 (commit #0326926)
[2024-07-15 09:55:37] info: 	z2m: Starting zigbee-herdsman (0.50.1)
[2024-07-15 09:55:38] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2024-07-15 09:55:38] info: 	zh:zstack:znp: Serialport opened
[2024-07-15 09:55:38] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-07-15 09:55:39] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-07-15 09:55:58] error: 	z2m: Error while starting zigbee-herdsman
[2024-07-15 09:55:58] error: 	z2m: Failed to start zigbee
[2024-07-15 09:55:58] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-07-15 09:55:58] error: 	z2m: Exiting...
[2024-07-15 09:55:58] error: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:101:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:129:29)
    at Zigbee.start (/app/lib/zigbee.ts:63:27)
    at Controller.start (/app/lib/controller.ts:139:27)
    at start (/app/index.js:154:5)
`

Non mi torna il valore di baudRate 115200 che leggo nell'output

**Comment by KC-inDomus** [comment]
è la configurazioen di zigbee2mqtt a essere sbagliata, non puoi mappare - /dev/ttyACM0 se usi silicon labs multiprotocol. come spiegato in dettaglio qui https://indomus.it/guide/gestire-zigbee-sui-diversi-bridge-gateway-usando-coordinator-multipan-rcp/

**Comment by skantaman** [comment]
a che punto fai riferimento? dentro il configuration.yaml di zigbee2mqtt ho mappato la porta come da guida

```

> # Autodiscovery su Home Assistant abilitato
> homeassistant: false
> # Join alla rete MQTT disabilitato di default
> permit_join: false
> # MQTT settings
> mqtt:
>   # MQTT base topic per i messaggi di zigbee2mqtt
>   base_topic: zigbee2mqtt
>   # MQTT server - URL (indirizzo LAN)
>   server: 'mqtt://core-mosquitto:1883'
>   # MQTT server - Parametri di autenticazione (decommentare e popolare correttamente se si utilizzano credenziali per la connessione al broker MQTT
>   user: NOME UTENTE PER ACCESSO SU FRONTEND DI HOME ASSISTANT
>   password: PASSWORD DI ACCESSO AL FRONTEND DI HOME ASSISTANT
>   include_device_information: true
> serial:
>   # Porta su cui è mappata l'antenna zigbee
>   port: tcp://core-silabs-multiprotocol:9999
>   adapter: ezsp
> advanced:
>   # Directory in cui verrà salvato il file di log
>   log_directory: /var/log
> experimental: {}
> frontend:
>   # porta su cui verrà esposta la webGUI
>   port: 8080
> ota:
>   update_check_interval: 10
> disable_automatic_update_check: false

```

**Comment by Pacs79** [comment]
buonasera
sono alla mia  prima istallazione di home assistant, ho seguito passo passo la guida su indomus, ed ho scelto la d montare home assistant os su un mini pc dedicato (teclast n10) integrando come coordinator, Sonoff zbdongle-E.
Le prove preliminari sono positive con il dongle che riesce d integrare i dispositivi per casa che non erano più riconosciuti del vecchio gateway.
Il problema è zigbee2mqtt , che in fase di avvio non trova il dongle, ripeto conZHA funziona correttamente.
mi vengono dei dubbi di comprensione:
 il dongle deve essere flashato per forza? 
l'ultima versioen di zigbee2mqtt non è compatibile con il ZBdongle -E?
qualcunoa tempo per darmiqualche dritta?
grazie in anticipo 

questo il log di z2m

[15:24:33] INFO: Preparing to start...
[15:24:33] INFO: Socat not enabled
[15:24:34] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-09-08 15:24:37] info: 	z2m: Logging to console, file (filename: log.log)
[2024-09-08 15:24:37] info: 	z2m: Starting Zigbee2MQTT version 1.40.1 (commit #unknown)
[2024-09-08 15:24:37] info: 	z2m: Starting zigbee-herdsman (0.57.3)
[2024-09-08 15:24:37] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_42b9394feb12ef1189506fb8bf9df066-if00-port0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2024-09-08 15:24:37] info: 	zh:zstack:znp: Serialport opened
[2024-09-08 15:24:38] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-09-08 15:24:39] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-09-08 15:24:58] error: 	z2m: Error while starting zigbee-herdsman
[2024-09-08 15:24:58] error: 	z2m: Failed to start zigbee
[2024-09-08 15:24:58] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-09-08 15:24:58] error: 	z2m: Exiting...
[2024-09-08 15:24:58] error: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:123:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:138:29)
    at Zigbee.start (/app/lib/zigbee.ts:64:27)
    at Controller.start (/app/lib/controller.ts:140:27)
    at start (/app/index.js:154:5)

**Reply by snakuzzo** [reply]
guarda che il dongle puoi usarlo solo con ZHA o solo con Zigbee2mqtt. Non puoi usare lo stesso hardware in questo modo.
Grazie al ciuffolo che zigbee2mqtt non riesce a collegarsi alla chiavetta...è occupata da ZHA.
Devi scegliere...o ZHA o zigbee2mqtt, non entrambi.

P.S. Probabilmente dovrai rifare il pairing passando a zigbee2mqtt.

**Reply by Pacs79** [reply]
grazie per la velocità di risposta, comunque io ho usato ZHA solo dopo aver provato zigbee2mqtt, per escludere che era la dongle il problema, il mio promo tentativo è stato con  zigbee2mqtt e il risultato è quello dello screen

**Reply by snakuzzo** [reply]
Vuol dire che hai sbagliato la configurazione di zigbee2mqtt.
Fai vedere che configurazione hai...e ricordati di disabilitare ZHA prima di fare partire zigbee2mqtt (sperano che la porta della chiavetta non resti lockata)

**Reply by Pacs79** [reply]
non riesco a disabilitare ZHA 

data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial:
  port: >-
    /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_42b9394feb12ef1189506fb8bf9df066-if00-port0

intendi questa configurazione ??

**Reply by snakuzzo** [reply]
Sì.
Ma non si capisce niente così. L'indentazione corretta non si vede. Devi usare il markdown quando condividi ste cose... è pure scritto a caratteri cubitali sulla home del forum.
Comunque, errore che si nota subtito...manca la tipologia di adapter "ember" per la dongle E ...e nelle nostre guide è scritto.

Questo, per intenderci...

```yaml
serial:
  port: /dev/ttyXXX
  adapter: ember #prende il posto di ezsp
```
