### DISCUSSION TITLE
Esphome - affidabilità sensore impronte R503

### DISCUSSION THREAD

**Discussion by cecc83** [indomus/forum#3197] [Hardware & Firmware]
Buongiorno a tutti,
ho seguito la guida [per il sensore impronte con esphome](https://indomus.it/progetti/integrare-un-lettore-di-impronte-digitali-a-home-assistant-via-nodemcu-ed-esphome/), questo il mio file di configurazione:

```
esphome:
  name: fingerprint
  platformio_options:
    upload_speed: 115200

esp32:
  board: esp32-poe
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "TjPQgwSXmO/0DdBnjLFqJpKWnR/Hi6dz7ZLKihy++V0="
  services:
  - service: enroll
    variables:
      finger_id: int
      num_scans: int
    then:
      - fingerprint_grow.enroll:
          finger_id: !lambda 'return finger_id;'
          num_scans: !lambda 'return num_scans;'
  - service: cancel_enroll
    then:
      - fingerprint_grow.cancel_enroll:
  - service: delete
    variables:
      finger_id: int
    then:
      - fingerprint_grow.delete:
          finger_id: !lambda 'return finger_id;'
  - service: delete_all
    then:
      - fingerprint_grow.delete_all:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  manual_ip:
    static_ip: 192.168.1.202
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1

ota:
  - platform: esphome
    password: "XXXXXXX"

# Built-in buttons. See https://esphome.io/components/button/
binary_sensor:
  - platform: fingerprint_grow
    id: fingerprint_enrolling
    name: "Acquisendo impronta"

uart:
  rx_pin: GPIO4
  tx_pin: GPIO1
  baud_rate: 57600

fingerprint_grow:
  sensing_pin: GPIO3
  on_finger_scan_start:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Impronta in scansione"
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: CYAN
        count: 2
  on_finger_scan_matched:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Impronta autorizzata"
    - fingerprint_grow.aura_led_control:
        state: BREATHING
        speed: 200
        color: GREEN
        count: 2
    - delay: 3000ms
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Attesa"
  on_finger_scan_unmatched:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Impronta non autorizzata"
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 2
    - delay: 3000ms
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Attesa"
  on_enrollment_scan:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Impronta acquisita"
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: BLUE
        count: 2
    - fingerprint_grow.aura_led_control:
        state: ALWAYS_ON
        speed: 0
        color: PURPLE
        count: 0
  on_enrollment_failed:
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Acquisizione impronta fallita"
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 4

text_sensor:
  - platform: template
    id: fingerprint_state
    name: "Stato impronta"

sensor:
  - platform: fingerprint_grow
    fingerprint_count:
      name: "Conta impronte"
    last_finger_id:
      name: "Ultimo ID impronta"
    last_confidence:
      name: "Affidabilità ultima impronta"
    status:
      name: "Stato impronta"
    capacity:
      name: "Capacità impronta"
    security_level:
      name: "Livello di sicurezza"
```

il sistema funziona e logga correttamente "No touch sensing" quando non c'è il dito sul sensore. Solo che, quando appoggio il dito, non sempre questo attiva il sensore e molto spesso sembra che il sensore sia in stato di sleep, o comunque spento (anche se nel mentre continua a loggare "No touch sensing").
Ho collegato filo rosso a 3.3v dell'esp 32, nero a GND, bianco sia prima a 3.3v che poi a 5v dell'esp32 e marrone, blu e giallo ai rispettivi GPIO dell'esp 32. I collegamenti sembrano ok infatti funziona e riconosce l'impronta ogni tanto, solo che mi aspettavo qualcosa di più "costante" e affidabile.
Grazie, buona giornata.
EDIT: un comportamento che ho notato è che spesso quando alzo il dito dopo averlo appoggiato inizia la scansione dell'impronta (con blink del led) dandomi poi il messaggio di scansione non riuscita.
