### DISCUSSION TITLE
Info File Configuration

### DISCUSSION THREAD

**Discussion by Matty1184** [indomus/forum#3202] [HUB: Home Assistant]
Ciao a tutti, 
una info penso banale, ma temo di essermi perso una modifica vecchia di HA.
il mio file è dichiarato come:
```
sensor:
  - platform: template
    sensors:
      potenza_totale_casa:
        friendly_name: "Potenza Totale Casa"
        value_template: ..........
        unit_of_measurement : "Watt"
```
ma forse dovrei variale il tutto in:
```
template:
  - sensors:
      potenza_totale_casa:
        friendly_name: "Potenza Totale Casa"
        value_template: ........
        unit_of_measurement: "Watt"
```
scusate la banalità ma non ho trovato info in merito.
