### DISCUSSION TITLE
Automazione a condizioni multiple

### DISCUSSION THREAD

**Discussion by merovese** [indomus/forum#3224] [HUB: Home Assistant]
Buonasera a tutti, ho provato a creare una automazione che, nel caso i sensori di presenza di sala e cucina non dovessero rilevare nessuno, la tv della sala, nel caso fosse accesa, dovrebbe avvisare e dopo un minuto spegnersi ed inviare una notifica.

```yaml
alias: "MEDIA: SPEGNI TV SALA SE NON C'È NESSUNO PER 20 MINTUI"
description: ""
trigger:
  - type: not_occupied
    platform: device
    device_id: 408c2f848c057fbd4be94a4a5bbcfdbd
    entity_id: 8dd2545f75c84db1cba5a50ea83c64a6
    domain: binary_sensor
    for:
      hours: 0
      minutes: 20
      seconds: 0
condition:
  - type: is_not_occupied
    condition: device
    device_id: aeafd41ed8bdcef95c1f2c68293e6d3c
    entity_id: 7487ed8d9fcd4373ab18d2973d7a607d
    domain: binary_sensor
action:
  - sequence:
      - action: notify.lg_webos_tv_qned826qb
        metadata: {}
        data:
          message: La Tv si spegnerà tra 1 minuto
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      - action: media_player.turn_off
        metadata: {}
        data: {}
        target:
          device_id: 7968962c74737b23ca3e840987d06a86
      - if:
          - condition: state
            entity_id: media_player.tv_sala_lg_qned826qb
            state: "off"
        then:
          - action: notify.mobile_app_iphone
            metadata: {}
            data:
              message: Ho spento la tv della sala
            enabled: true
mode: single
```

Purtroppo qualcosa non va, la tv si spegne, ma la notifica mi arriva anche se la tv non è mai stata accesa…

potreste darmi una mano?
Grazie mille

**Comment by snakuzzo** [comment]
correggi il post. Non si capisce una fava...devi usare correttamente il markdown (con i tre backtick...non con uno...è pure scritto a caratteri cubitali sulla home del forum)

**Reply by snakuzzo** [reply]
Ho corretto io il post con i backtick in modo corretto.

**Reply by snakuzzo** [reply]
Se posso darti un consiglio, se ho capito bene quello che vuoi fare, non farei l'automazione dalla webgui (come sono sicuro tu abbia fatto), ma farei un [package](https://indomus.it/formazione/i-package-di-home-assistant-cosa-sono-e-come-si-installano/) inserendo un gruppo di sensori da usare nel trigger e l'automazione.
Di seguito un package fatto al volo che dovrebbe essere corretto a livello sintattico (visto che non dà alcun errore sulla configurazione di Core). In line i commenti:

```yaml
binary_sensor:

  # Gruppo di sensori binari
  # Se solo uno di questi sensori è "on" il gruppo ha stato "on", altrimenti ha stato "off"
  - platform: group
    name: "gruppo_sensori"
    device_class: occupancy
    entities:
      - binary_sensor.tuo_sensore_1 # cucina 1
      - binary_sensor.tuo_sensore_2 # cucina 2
      - binary_sensor.tuo_sensore_3 # sala 1
      - binary_sensor.tuo_sensore_4 # sala 2

automation:

  # Imposta anche un ID, perché ti può servire per fare debug con il trace nella schermata della automazioni
  - id: spegni_tv_automaticamente
    alias: "Spegni TV automaticamente"
    trigger:
      # (Consiglio: Evita di usare i device, ma usa le entità)
      # in questo caso se il gruppo passa da on (rilavata presenza) a off (nessun sensore rilavea presenza)...
      platform: state
      entity_id: binary_sensor.gruppo_sensori
      from: 'on'
      to: 'off'
      # ...per 20 minuti
      for:
        minutes: 20
    action:
        # ...notifica che la TV si spegnerà tra 1 minuto
        - action: notify.tuo_notify
          data:
            message: "La Tv si spegnerà tra 1 minuto"
        # Poi aspetta 1 minuto...
        - delay:
            minutes: 1
        # ...allo scadere del minuto...
        - if:
            # ...se il gruppo dei sensori è ancora in off (presenza non rilevata)
            - condition: state
              entity_id: binary_sensor.gruppo_sensori
              state: "off"
          then:
            # ...spegne la TV...
            - action: media_player.turn_off
              target:
                entity_id: media_player.tua_tv
            # ...e manda una notifica
            - action: notify.tuo_notify
              data:
                message: "Ho spento la TV in sala"
```

Qui è dove trovi il tastino per il trace delle automazioni

![image](https://github.com/user-attachments/assets/4bf5bc83-20fd-49fc-a2b0-cc0b660cdac6)
