### DISCUSSION TITLE
Automazione striscia led su valore bitcoin

### DISCUSSION THREAD

**Discussion by Jones1982** [indomus/forum#3234] [HUB: Home Assistant]
Buongiorno,
sto cercando di creare un automazione sul valore "in tempo reale" di bitcoin.
Per la precisione, uso l'integrazione Cryptoinfo e come controller Magic Home per la striscia led.

Il problema che riscontro è sul far attivare la striscia led in base all'attributo "baseprice" del sensore "sensor.cryptoinfo_bitcoin_usd".

Il valore di riferimento che ho segnato, è 56000$: se va sopra, accende i led verdi, altrimenti rossi.

![bit](https://github.com/user-attachments/assets/76780535-9ba4-41bd-8219-100e637f2fb6)
questo è l'esempio di quello che mi interessa. ignorate che sia in euro. ho anche il valore in dollari

Ho provato sia così.. (ma non so come dirgli di "leggere" il valore -baseprice-) :

```
alias: Bitcoin Lamp (test)
description: ""
trigger:
  - platform: template
    value_template: "{{ states('sensor.cryptoinfo_bitcoin_usd') |float(0) < 56000 }}"
condition: []
action:
  - target:
      entity_id:
        - light.stripled
    data:
      effect: red_fade
    action: light.turn_on
mode: single
```

che così;

```
alias: Bitcoin Lamp (+56000$)
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.cryptoinfo_bitcoin_usd
    above: 56000
    attribute: baseprice
action:
  - target:
      entity_id:
        - light.stripled
    data:
      effect: green_fade
    action: light.turn_on
mode: single
```

Qualcuno può aiutarmi per favore?
Ringrazio in anticipo!!!

**Comment by Scialla** [comment]
per leggere il valore dell'attributo devi usare `state_attr()` altrimenti leggi il valore dello stato

https://www.home-assistant.io/docs/configuration/templating/

`state_attr('sensor.cryptoinfo_bitcoin_usd', 'Baseprice')`

**Comment by Jones1982** [comment]
Ciao Scialla, grazie x la risposta.
Ho provato così... ma non si attiva:

```
trigger:
  - platform: template
    value_template: "{{ state_attr('sensor.cryptoinfo_bitcoin_usd', 'Baseprice') |float(0) < 56000 }}"
```

**Reply by Scialla** [reply]
Aiutati con i modelli negli strumenti sviluppatori così vedi cosa ti valorizza il template

**Reply by Jones1982** [reply]
si stavo provando già lì.  sembra che il " |float(0) < 56000 }}" non vada bene, e non mi restituisce il valore.
rimosso, mi da il valore .
però a me serve la condizione che se è inferiore il valore di 56000, attiva il resto.

**Reply by Scialla** [reply]
Se è un numero intero usa `int(0)`

**Reply by Jones1982** [reply]
uhm... il valore dell'attributo è anche decimale, con la virgola.  dici che va bene?

cmq niente. non si attiva.

**Reply by Scialla** [reply]
I trigger scattano alla variazione di stato. Nel tuo caso l'automazione scatta quando, da sopra o uguale a 56000 scende al di sotto. Se è già sotto è normale che non si attivi

**Reply by Jones1982** [reply]
ieri il valore l'ho settato a 70000 x sicurezza, ma lo stesso non si attiva.
ho provato anche a fare il contrario, mettere come " > 10 "    . stesso risultato, non scatta.

se non ho tradotto male dalla pagina che hai postato ieri... mi sembra di aver capito che il "float su un valore di attributo" deve essere un numero intero, non con decimali...    forse ho capito male.

**Reply by Scialla** [reply]
o non capisco io, o non capisci tu.... i trigger scattano al verificarsi della condizione impostata e NON se, quando verifichi il valore, la condizione è già quella....

Se metti un trigger > 10, scatterà quando il valore, da inferiore o uguale a 10, diventa maggiore, ovvero 11 o di più ma, se è già 11, non scatterà mai, stessa cosa col minore

per il resto `int()` fa il casting a un valore intero mentre `float()` fa il casting a un valore con i decimali. Dipende da cosa vuoi ottenere tu

**Reply by Jones1982** [reply]
> Se metti un trigger > 10, scatterà quando il valore, da inferiore o uguale a 10, diventa maggiore, ovvero 11 o di più ma, se è già 11, non scatterà mai, stessa cosa col minore


 Si questo mi è chiaro, il 10 è stato un errore mio a scriver qui, avevo messo x `> x` con un valore di poco superiore (di 10) a quello che al momento segnava come valore in tempo reale (se non ricordo male, 2 gg fa era intorno ai 63100. ma non è scattato lo stesso.
Preferisco il `float()`, per poi poter usare l'automazione anche con altre crypto.
Non capisco se il problema potrebbe stare nel `float(0) > 64000` , cioè quel (0).  sicuramente mi spiego male io. ma se non ricordo male, quel (0) indica un valore di riferimento, giusto? se è così, a questo punto dovrei cambiare quel 0 in un valore fisso, es: se deve scattare a un valore superiore a 64000$, se ho capito bene, dovrei mettere `float(64000) > 64001`   (dove 64000 $ è il valore dal quale dovrebbe scattare). corretto? 
O mi conviene direttamente togliere il valore nel `float()` ? ricordo che dopo un aggiornamento di mesi fa, fu obbligatorio inserirlo.
grazie ancora e abbi pazienza, lo so, quello che è ovvio x te.. non lo è per tutti.

**Reply by Scialla** [reply]
No, `float(0)` è l'abbreviazione di `float(default=0)` ovvero de il valore del tuo sensore non è valorizzato, ovvero è `unknown` oppure è `unavailable`, al sensore viene assegnato il valore di default, questo per non avere errori o warning nel log.

Se non ti funziona devi provare nei modelli cosa ti restituisce come valore lo stato del tuo sensore, stai sbagliando qualcosa

**Reply by Jones1982** [reply]
```
alias: Bitcoin led 1
description: ""
trigger:
  - platform: template
    value_template: >-
      {{ state_attr('sensor.cryptoinfo_bitcoin_usd', 'baseprice') |float(0) <
      63700 }} 
action:
  - target:
      entity_id:
        - light.stripled
    data:
      effect: red_fade
    action: light.turn_on
mode: single
```

![Cattura2](https://github.com/user-attachments/assets/732506a4-b603-4f05-9b54-f7124d966283)

![Cattura3](https://github.com/user-attachments/assets/aa4743d3-09a7-4208-9584-d7cb1e26b74a)

In questo momento è vicino ai 63700, e ho impostato sia il `>` che il `<` a `63700`.   
Quindi se supera 63700 scatta (automazione con i led verdi), se scende sotto i 63700 (dopo averli superati).. scatta (altra automazione con i led rossi). giusto?

Ti ho fatto gli screenshot x mostrarti che valore mi restituisce il valore. ho dovuto "rimuovere il float etc.." altrimenti non mi visualizzava il valore e non potevo "Vederlo".

Però una cosa non mi è chiara... perdonami, ma se deve leggere il valore all'avvio di HA, ed è sotto a 63700 x giorni, non scatterà mai con i led rossi, xchè prima di poterlo fare, deve superarli e poi scendere sotto 63700. giusto?  
questo vuol dire che se x 1 mese sta sotto i 55000, non scatterà mai ne in rosso che in verde.  
a me servirebbe che scatti ogni volta che il valore dei bitcoin salga o scenda. 
Allo stato attuale.. se riavvio spesso HA, dovrei ogni volta cambiare il valore di riferimento x farli scattare.

**Reply by Jones1982** [reply]
aggiornamento:
pochi minuti fa è scattato con l'automazione del valore > 63700. ed ha attivato i led verdi.
da poco sono scattati con i led rossi (il valore è sceso a 63540).
Ora ho riavviato HA, valore attuale 63647  ... e tutto tace (come ipotizzavo prima)
Forse dovrei usare come riferimento l'attributo "1h change" al posto del "baseprice"!?! quello varia tra - e "+" .
![Cattura5](https://github.com/user-attachments/assets/80e90761-e8bd-4d1e-8a25-3c4efb0885b6)

**Reply by snakuzzo** [reply]
Premesso che non ho letto (e non ho intenzione di leggere) tutto il thread, guardando il trigger della tua ultima automazione...

```yaml
  - platform: template
    value_template: >-
      {{ state_attr('sensor.cryptoinfo_bitcoin_usd', 'baseprice') |float(0) < 63700 }} 
 ```

Correggetemi se dico cagate, ma Il tuo trigger dovrebbe scattare quando quell'attributo passa da un valore `>=  63700` ad un valore `< 63700`.
In fase di restart devi capire bene se assume altri valori (es. `unknown`) o se rimane sempre quello pre-restart.
