### DISCUSSION TITLE
Termostato con 2 setpoint per pompa di calore in modbus

### DISCUSSION THREAD

**Discussion by Balteck** [indomus/forum#3248] [HUB: Home Assistant]
Buongiorno a tutti, sto implementando la mia UTA con modbus in Home Assistant. 
Funziona tutto, tranne che ho 2 registri per impostare i setpoint (estate/inverno) e nella modalità AUTO o CALDO/FREDDO la macchina sceglie da sola il setpoint corretto. 
Purtroppo l'entità climate di home assistant mi espone solo un setpoint e cambiando le modalità mi scrive la temperatura invernale nell'estiva o viceversa. Qualcuno mi può dare una mano a correggere?

Ho visto che Home assistant ha un termostato con due setpoint, ma non riesco a farlo uscire

![image](https://github.com/user-attachments/assets/6e300654-5bf8-4615-8044-56d153597c5f)

Questo è il mio yaml di configurazione:

```
climates:
     - name: "Termostato Ethos"
       unique_id: ethos.thermostat
       address: 1
       slave: 1
       input_type: input
       data_type: int16
       max_temp: 30
       min_temp: 15
       offset: 0
       precision: 1
       scale: 0.1
       target_temp_register: 
        - 86
        - 86
        - 86
        - 86
        - 87
        - 87
        - 87
       temp_step: 0.5
       temperature_unit: C
       hvac_mode_register:
         address: 5042
         values:
           state_cool: 0
           state_heat: 1
           state_auto: 2
           state_dry: 3
           state_fan_only: 4
       fan_mode_register:
         address: 5043
         values:
           state_fan_low: 1
           state_fan_medium: 2
           state_fan_high: 3
           state_fan_auto: 4
```
