### DISCUSSION TITLE
Zigbee2MQTT - errore installazione Error while starting zigbee-herdsman

### DISCUSSION THREAD

**Discussion by Andrea83013** [indomus/forum#3264] [ZigBee, Z-Wave, Thread, Matter]
Buonasera,
ho il seguente errore, credo che sia il COORDINATOR che non viene letto,
ho seguito la guida passo passo,
prima però ho aggiornato il firmware del mio Sonoff ZigBee 3.0 USB Dongle Plus v2 (ZBDongle-E](https://indomus.it/link/itead-sonoff-zigbee-3-0-dongle-usb-plus-v2-zbdongle-e/), con questo ncp-uart-hw-v7.4.4.0-zbdonglee-115200
ho visto che il percorso dispositivo è /dev/ttyACM0

ma viene restituito sempre questo errore 

2024-10-30 17:19:14] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-30 17:19:14] error: 	z2m: Failed to start zigbee
[2024-10-30 17:19:14] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-30 17:19:14] error: 	z2m: Exiting...
[2024-10-30 17:19:14] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.

la configurazione è

serial:
  port: /dev/ttyACM0
  adapter: ember

che altro devo controllare ?

**Comment by KC-inDomus** [comment]
https://indomus.it/formazione/troubleshooting-zigbee2mqtt-perche-non-parte-e-come-risolvere/

**Comment by marcoferroha** [comment]
Ho lo stesso problema anch'io, premetto che ho installato e configurato mosquitto che viene regolarmente raggiunto e configurato da HA ma non si avvia il coordinator. Ho visto tutte le guide e gli help ma non vedo nulla di strano nella mia con figurazione. Il coordinator è lo stesso di Andrea83013. ho provato sia con /dev/ttyACM0 che con /dev/ttyUSB0. Vi viene in mente qualcos'altro ? Di seguito file di configurazione:

```
serial:
     port: /dev/ttyUSB0
     adapter: ember
   mqtt:
     base_topic: zigbee2mqtt
     server: 'mqtt:192.168.178.151'
     user: oscurato
     password: oscurata
     version: 5
     reject_unauthorized: true
     include_device_information: true
   permit_join: false
   frontend:
     port: 8080
   homeassistant:
     legacy_triggers: true
     legacy_entity_attributes: false
   ota:
     update_check_interval: 1440
     disable_automatic_update_check: false
   advanced:
     cache_state: true
     cache_state_persistent: true
     cache_state_send_on_startup: true
     channel: 19
     transmit_power: 20
     legacy_api: false
     legacy_availability_payload: false
     log_level: info
     log_namespaced_levels:
        z2m:mqtt: warning
```
