### DISCUSSION TITLE
Broadlink RM mini 3 e TV Panasonic

### DISCUSSION THREAD

**Discussion by mateferrox** [indomus/forum#3269] [GENERALE - Discussioni generiche]
Ciao a tutti,
sono nuovo nel forum, e sto facendo pratica con HA.
In pratica ho installato l'app mobile di Broadlink e sono riuscito a fare l'integrazione tra HA e Broadlink RM mini 3 tramite IP.
Soltanto che, seguendo la guida https://indomus.it/componenti/componente-home-assistant-smartir-media-player/ ho installato tramite HACS Smartir, e ho inserito nel file di configurazione questo codice yaml:
```
smartir:
media_player:
    - platform: smartir
      name: TV Camera
      unique_id: tv_camera
      device_code: 1002
      controller_data: remote.ir_camera
```
Poi, ho creato il json a mano, perchè non era presente il modello del mio televisore (file 1002.json inserito sotto /homeassistant/custom_components/smartir/codes/media_player/1002.json):
```
{
    "manufacturer": "Panasonic",
    "supportedModels": [
      "TX-43JX600E"
    ],
    "supportedController": "Broadlink",
    "commandsEncoding": "Base64",
    "commands": {
        "off": "codice.....",
        "on": "codice.....",
        "sources": {
            "EXT1": "codice.....",
            "EXT2": "codice.....",
            "VGA": "codice.....",
            "HDMI": "codice.....",
            "HDMI Side": "codice.....",
            "AV Side": "codice.....",
            "Channel 1": "codice.....",
            "Channel 11": [
                "codice 1.....",
                "codice 2....."
            ]
        }
      }
}
```
Il problema è che dalla card generata, non si accende il televisore.
Cosa ho sbagliato?
