### DISCUSSION TITLE
Sensore template e statistiche

### DISCUSSION THREAD

**Discussion by Starc73** [indomus/forum#3285] [HUB: Home Assistant]
Scusare perchè non vedo nelle statistiche questo sensore template molto semplice, ho provato ad aggiungere la state class ma mi da errore

Grazie in anticipo

```
template:
  - sensor:
      - name: "temperatura esterna"
        unit_of_measurement: '°C'
        entity_id: temperatura_esterna
        state: >
          {{ states.weather.forecast_home.attributes.temperature }}      
        state_class: 'measurement'
```
