### DISCUSSION TITLE
HA non raggiungibile localmente

### DISCUSSION THREAD

**Discussion by Masino83** [indomus/forum#3290] [HUB: Home Assistant]
Ciao a tutt*,

Stavo configurando l’Hub in modo da poterlo raggiungere remotamente, seguendo la guida InDomus che consiglia Cloudflare.
Nel momento in cui ho modificato il file configuration.yaml il tag: 

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 
    
Da questo momento bon tutto perso.
come posso sistemare? 
grazie per vostro supporto

**Comment by Starc73** [comment]
Da quel poco che so se perdi l'accesso in locale o recuperi da qualche backup o reinstalli tutto

**Reply by snakuzzo** [reply]
assolutamente no...hai sempre la CLI a disposizione per recuperare.
Ripristinare un backup non è quasi mai necessario.
@Masino83  hai commesso un errore di indentazione, se è corretto quello che hai scritto. Quindi, nella peggiore delle ipotesi, collega monitor e tastiera e sistema così...

```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.0/24 # questo sostituiscilo con la tua subnet
    - ::1
    - 172.30.33.0/24
 ```
