### DISCUSSION TITLE
Binary_Sensor in configuration.yaml

### DISCUSSION THREAD

**Discussion by alessandro68** [indomus/forum#3291] [HUB: Home Assistant]
Buongiorno a tutti.
Mi sto approcciando all'uso di Home Assistant grazie alle vostre guide.
Sto banalmente usando delle automazioni che notificano al cellulare un evento trasmetto tramite MQTT di vari sensori RF.
Fin qui tutto bene.
Vorrei pero' ora tramite questi codici creare dei "binary_sensor" (delle entita' giusto?) in modo poi da poterli "vedere"
nell'app casa tramite "HomeKit Bridge"
Per fare questo allego la parte di codice Yaml che sono certo non e' giusta e devo fare 2 precisazioni.

``` yaml

mqtt:
  binary_sensor:
  
    state_topic: "tele/RFState/RESULT"
    name: "STATOCancello2"
    unique_id: "GateStatus"
    value_template: "{{ value_json.RfReceived.Data }}"
    payload_on: "137C09"
    payload_off: "8D3C09"
    device_class: motion
    
    state_topic: "tele/RFState/RESULT"
    name: "STATOMovimento2"
    value_template: "{{ value_json.RfReceived.Data }}"
    payload_on: "137C03"
    payload_off: "8D3C03"
    device_class: motion

```

Scritto cosi come sopra HA mi vede solo STATOMovimento2 e molto probabilmente "prende" "GateStatus" come unique ID dato l'entità ha tutti i dettagli ( senza unique_id, lo vede ma non mi e' gestibile )
Ho provato anche visto da esempi mettere:

```
binary:sensor:
  - platform: mqtt
```

mi viene accettato come sintassi ma non trovo poi le entita

Spero in una vostra dritta aiuto e magari anche una conferma sia fattibile come cosa..
Grazie 
Alberto
