### DISCUSSION TITLE
Aiuto statistiche e storico sensore

### DISCUSSION THREAD

**Discussion by Balteck** [indomus/forum#3296] [HUB: Home Assistant]
Buongiorno, ho un sensore così configurato:

 
```
modbus:
  - name: xxx
    type: tcp
    host: 1.1.1.1
    port: 502
    sensors:
      - name: T_AMBIENTE1
        unique_id: T_AMBIENTE1
        device_class: temperature
        state_class: measurement
        unit_of_measurement: °C
        data_type: int16
        input_type: input
        slave: 1
        address: 1
        scan_interval: 10
        scale: 0.1
        offset: 0
        precision: 1 
``` 

Vedo lo storico degli ultimi 10 giorni e non posso tornare indietro.
Nel pannello statistiche vedo:

![Immagine 2024-11-26 135042](https://github.com/user-attachments/assets/bb7b1ec5-040c-4cd0-b621-4e3dc3dd4490)

Dove ho sbagliato? 
Come posso correggere?
