### DISCUSSION TITLE
Accesso directory HD esterno per registrare da ipcam

### DISCUSSION THREAD

**Discussion by braudoo** [indomus/forum#3307] [HUB: Home Assistant]
Ciao a tutti, ho RP4 con installato HA CORE tramite container docker.
Vorrei sfruttare l'azione **camera.record** per registrare da un'ip-cam, su un'HD esterno collegato all'RPI4, ma mi da il seguente errore:
`Impossibile eseguire l'azione: camera.record Can't write /export/nas_5tb/ipcam_movies/prova.mp4, no access to path!`

Aggiungo al file configuration.yaml la dicitura:

```
homeassistant:
  whitelist_external_dirs:
    - /export/nas_5tb/ipcam_movies

```
ma al riavvio di HA mi da il seguente errore:
`The system cannot restart because the configuration is not valid: Invalid config for 'homeassistant' at configuration.yaml, line 23: Not a directory 'whitelist_external_dirs->0', got '/export/nas_5tb/ipcam_movies'`

Nel file docker-compose.yaml aggiunto quanto segue sotto al blocco home-assistant:
```
services:
  home-assistant:
  ...
  volumes:
    ...
    - ~/homeassistant/.homeassistant/media:/media
    - /export/nas_5tb/ipcam_movies:/ipcam_movies
```

Non so come procedere.

Qualcuno riuscirebbe ad aiutarmi?

Grazie.
