### DISCUSSION TITLE
Bubble Card - Castomizzazione Sub button

### DISCUSSION THREAD

**Discussion by merovese** [indomus/forum#3325] [HUB: Home Assistant]
Ciao e buonasera a tutti, sto cercando di raffinare la mia dashboard, attualmente sto utilizzando la celeberrima bubble card, ma ho un piccolo problema con la customizzazione dei sub-button, nello specifico ho inserito nell'header 5 sub-button, ai quali chiedo, in caso di entità ON, di colorarsi di arancione, ma purtroppo, ogni volta che una delle entità cambia stato (in ON)  i 5 sub-button si colorano tutti d'arancione e non riesco a trovare una via d'uscita.

```yaml
type: custom:bubble-card
card_type: button
button_type: name
name: Cucina
icon: phu:rooms-kitchen
button_action:
  tap_action:
    action: navigate
    navigation_path: "#cucina"
tap_action:
  action: navigate
  navigation_path: "#camera"
show_name: true
card_layout: normal
entity: light.gruppo_luci_cucina
sub_button:
  - entity: light.luci_cucina
    tap_action:
      action: toggle
  - entity: light.luci_cappa
    tap_action:
      action: toggle
    icon: mdi:countertop
  - icon: mdi:washing-machine
    entity: binary_sensor.lavatrice_door_lock
    show_state: false
  - name: ""
    icon: mdi:dishwasher
    entity: sensor.403100542183000432_bsh_common_setting_powerstate
    show_state: false
    state_background: true
  - icon: mdi:fridge
    entity: sensor.frigorifero_active_power
  - entity: binary_sensor.aqara_lumi_motion_ac01_occupancy_2
    icon: mdi:motion-sensor
    tap_action:
      action: none
styles: |
  .bubble-sub-button-1 {
   background-color: ${state === 'on' ?  'darkorange' : 'white'} !important;
  }
  .bubble-sub-button-2 {
   background-color: ${state === 'on' ?  'darkorange' : 'white'} !important;
  }
  .bubble-sub-button-3 {
   background-color: ${state === 'on' ?  'darkorange' : 'white'} !important;
  }
  .bubble-sub-button-4 {
   background-color: ${state === 'on' ?  'darkorange' : 'white'} !important;
  }
  .bubble-sub-button-5 {
   background-color: ${hass.states['sensor.frigorifero_active_power'].state > 0 ? 'lightgreen' : 'red' } !important;
  } 
```

Spero di aver riportato bene il codice
