### DISCUSSION TITLE
ZigBee2MQTT 2.0.0: condivisione problemi e soluzioni

### DISCUSSION THREAD

**Discussion by indomus** [indomus/forum#3338] [ZigBee, Z-Wave, Thread, Matter]
L'uscita di ZigBee2MQTT 2.0.0, come previsto, ha portato una serie di problemi. Fermo restando che la maggior parte (la totalità?) possono essere risolti dalla lettura attenta [delle release note](https://github.com/Koenkk/zigbee2mqtt/releases/tag/2.0.0), apriamo questo thread per dar modo a tutti di condividere problemi e soluzioni.

Si prega di aprire, sotto questo intervento, discussioni autonome con risposte collegate, per non creare disordine nella lettura.

**Comment by KC-inDomus** [comment]
Per chi avesse problemi con le action dei pulsanti, la soluzione che ripristina il vecchio comportamento (temporanea, perché alla lunga verranno rimossi) è impostare questo in configurazione:

```
homeassistant:
  enabled: true
  homeassistant_legacy_triggers: true
  legacy_action_sensor: true
```

**Comment by Metus88** [comment]
Per chi avesse problemi nel riconoscere la chiavetta usb ricevendo questo errore:
`USB adapter discovery error`
basta seguire [queste istruzioni](https://github.com/Koenkk/zigbee2mqtt/discussions/24364)
(Modificare nel file **configuration.yaml**)
```
serial:
  port: /dev/ttyACM0
  adapter: zstack # <-- Add this line MODIFICANDO zstack in base al vostro adattatore
```

**Reply by KC-inDomus** [reply]
"add this line" secondo me è fuorviante.

**Reply by Metus88** [reply]
ho copiato quello proposto nella soluzione "ufficiale" dal link sopra. Consigli di toglierlo? Era giusto per far capire cosa viene aggiunto/modificato....

**Reply by KC-inDomus** [reply]
no, dico solo che `zstack` non è necessariamente giusto. varia in funzione dell'adapter

**Reply by Metus88** [reply]
giusto. Modificato!

**Reply by Nik71git** [reply]
ho notato che nella doc raccomandano di usare la porta by id:
```
serial:
    # Location of the adapter
    # USB adapters - use format "port: /dev/serial/by-id/XXX"  #<--- LEGGETE QUESTA NOTA
    # Ethernet adapters - use format "port: tcp://192.168.1.12:6638"
    port: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00 #<--- VEDI NOTA SOPRA
    # Adapter type, allowed values: `zstack`, `ember`, `deconz`, `zigate` or `zboss`
    adapter: zstack
```
quindi per la Dongle Sonoff Plus P (esempio):
```
serial:
  #port: /dev/ttyUSB0
  port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_c4139a33fd19ec11a2857fe5f01c6278-if00-port0
  adapter: zstack
advanced:
  transmit_power: 20
  disable_led: true
  baudrate: 115200
```

ma nel mio caso, pur essendo il path corretto, non funziona... ho dovuto ripristinare `port: /dev/ttyUSB0`

**Reply by snakuzzo** [reply]
@Nik71git immagino tu abbia letto [QUI](https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.html#which-port-should-i-use-for-texas-instruments-launchxl-cc26x2r1-cc1352p-2-dev-ttyacm0-or-dev-ttyacm1).

In quello che hai scritto vedo un `-port0` di troppo alla fine, almeno rispetto a quanto riportato nella documentazione

Ho fatto una verifica sull'istanza di test di HA OS che ho, a cui è collegata una ZBDongle-E...

```
~ $ ls -l /dev/serial/by-id
total 0
lrwxrwxrwx    1 root     root            13 Jan  5 19:04 usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220811102649-if00 -> ../../ttyACM0
```

Magari ricontrolla bene.

In ogni caso, è indicato di proposito perché i percorsi `/dev/tty...` potrebbero non essere sempre gli stessi. In questo modo invece, vai praticamente sul sicuro (in teoria).

**Reply by Nik71git** [reply]
> In quello che hai scritto vedo un `-port0` di troppo alla fine, almeno rispetto a quanto riportato nella documentazione

@snakuzzo ho notato questa cosa e ho provato prima senza il `port0` finale e poi l'ho aggiunto perché il `by-id` lo riporta.
Credo di non avere i diritti di scrittura col mio utente, verificherò a breve.

**Reply by Metus88** [reply]
> > In quello che hai scritto vedo un `-port0` di troppo alla fine, almeno rispetto a quanto riportato nella documentazione
> 
> @snakuzzo ho notato questa cosa e ho provato prima senza il `port0` finale e poi l'ho aggiunto perché il `by-id` lo riporta. Credo di non avere i diritti di scrittura col mio utente, verificherò a breve.

hai verificato? anche io ho questo problema

**Reply by snakuzzo** [reply]
fate un `ls`, ci vuole un attimo a verificare i permessi

**Reply by guba91** [reply]
> 
> In quello che hai scritto vedo un `-port0` di troppo alla fine, almeno rispetto a quanto riportato nella documentazione
> 

Anche io nella conf del container lxc fatto con ttek vedo così:
/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_3b8046ff44c8ed2198aaf3a32981d5d7-if00-port0

**Reply by Metus88** [reply]
> fate un `ls`, ci vuole un attimo a verificare i permessi

`lrwxrwxrwx 1 root root 13 Jan  4 09:28 usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_94e155e95b29ec118f726f7840c9ce8d-if00-port0 -> ../../ttyUSB0`

Anche io ho -port0 finale e sia mettendo che togliendolo non funziona. Ho dovuto rimettere 
port: /dev/ttyzigbee
```
serial:
  port: /dev/ttyzigbee
  adapter: zstack 
#  port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongl..... # NON mi va.
```

**Reply by snakuzzo** [reply]
ah...ho capito l'inghippo. Ma scusate eh...ragionate un attimo.
Nella configurazione del container dovete indicare il percorso del bind all'interno del container, non all'esterno sull'host!!!

LE BASI DI DOCKER, ragazzi !!!

La configurazione di zigbee2mqtt all'interno del container la potete lasciare così com'è, se volete dovete modificare la definizione dei volumi del container.

Esempio...

Ammesso che abbiate questa definizione del container:

```yaml
volumes:
  - /dev/ttyUSB0:/dev/ttyZIGBEE
```

per seguire quello che dicevate, va cambiata la definizione in questo modo:

```yaml
volumes:
  - /dev/ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_94e155e95b29ec118f726f7840c9ce8d-if00-port0:/dev/ttyZIGBEE
```

**Reply by Metus88** [reply]
Soluzione:
Avevo dimenticato di aggiungere al container docker di accedere al device nuovo (che è lo stesso ma cambiando nome giustamente non lo riconosceva).
Docker-compose.yaml
```
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
    - "/home/deb/DOCKER/zigbee2mqtt:/app/data"
    devices:
    - "/dev/ttyzigbe"  #vecchio nome
    - "/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_94e155e95b29ec118f726f7840c9ce8d-if00-port0
```
    Quindi il finale port0 è corretto perchè funziona.
    
   EDIT: @snakuzzo mi ha preceduto circa.

**Reply by snakuzzo** [reply]
eh...te l'ho scritto poco fa
Ma puoi anche evitare di fare come hai fatto tu...e fai come ti ho scritto io.
Così, in ottica futura, sulla configurazione all'interno del container non devi cambiare niente, perché lo mappi sempre a modo tuo

**Reply by Metus88** [reply]
> eh...te l'ho scritto poco fa

eh si, nel mentre scrivevo la soluzione cha hai trovato mi hai preceduto. Grazie comunque!

**Reply by Nik71git** [reply]
Bravissimi, stasera applico la "pappa pronta".
Ragionando Koenkk indica di  mappare la seriale by-id dando per scontato che nella definizione del container sia mappata alla stessa maniera... altrimenti o by-id o con la vecchia mappatura funziona ugualmente.
O sbaglio?

**Reply by snakuzzo** [reply]
No. Koenkk non dà nulla per scontato. Per quanto riguarda il discorso relativo al compose, come puoi vedere sulla documentazione ufficiale (screenshot in basso), a parte l'utilizzo della chiave `devices:` al posto di `volumes:` (che in questo caso è totalmente indifferente), lui ti indica la mappatura della porta sull'host (a sinistra) con la porta all'interno del container (a destra), che è quella che andrai ad utilizzare nella configurazione di zigbee2mqtt...

![image](https://github.com/user-attachments/assets/2f4d314c-21c6-4e81-b1f3-53a315c9689f)

Se invece specifichi solo il device (senza i due punti e la parte a destra), quando viene creato il container la porta viene mappata esattamente come è sull'host.

Per intenerci, questo...

```yaml
devices:
  - /pippo:/pippo
```

è  esattamente uguale a questo:

```yaml
devices:
  - /pippo
```

Ribadisco quanto detto prima. Questa roba va al di là di quello che dice o non dice Koenkk...qua si tratta proprio di imparare le basi di Linux (per il discorso `udev`) e di Docker (per il discorso dei bind). Non c'entra una ceppa zigbee2mqtt.
Tra le altre cose, il compose di Koenkk andrebbe anche corretto perché ci sono delle cose che non sono più previste nelle nuove versioni di `docker compose`

**Reply by Nik71git** [reply]
> Ribadisco quanto detto prima. Questa roba va al di là di quello che dice o non dice Koenkk...qua si tratta proprio di imparare le basi di Linux (per il discorso `udev`) e di Docker (per il discorso dei bind). Non c'entra una ceppa zigbee2mqtt. Tra le altre cose, il compose di Koenkk andrebbe anche corretto perché ci sono delle cose che non sono più previste nelle nuove versioni di `docker compose`

ok, discorso bind compreso (avevo completamente scordato di controllare la config del container di zigbee2mqtt, hai ragione quando affermi che bisogna sempre ...ragionare sulle cose) ma oltre alla `version` cosa c'è di deprecato nel suo compose di esempio?
Poi, riflessione personale, trovo più logico mappare sotto `devices` anche se come affermi tu è uguale mappare la porta sotto la chiave `volumes` , dovrebbe essere uguale se la mappo col nome che voglio io anche sotto `devices` o no?

**Reply by snakuzzo** [reply]
Diciamo che l'unico errore è `version:`, poi avrei gestito il path data dell'host in maniera un po' diversa...però va bene così.
Quanto a `devices:` per la parte a destra puoi indicare quello che ti pare e riportarla poi nel `configuration.yaml` di zigbee2mqtt.

Es.

```yaml
  devices:
    - /dev/ttyUSB0:/dev/PorcaPaletta
```

Nel `configuration.yaml` di zigbee2mqtt...

```yaml
serial:
  port: /dev/PorcaPaletta
  adapter: zstack
```

P.S. `devices:` e `volumes:` non sono la stessa cosa

**Comment by Danifly80** [comment]
Per chi usasse il Sonoff ZB-Bridge (Pro) deve modificare cosi:

```
serial:
  port: 'tcp://IP:Porta'
  adapter: zstack
```

aggiungendo la riga adapter

grazie a Giancarlo (G-Man) per la dritta!

**Comment by Metus88** [comment]
Sto cercando di seguire [la vostra guida](https://indomus.it/news/hot-aggiornamento-2-0-0-per-zigbee2mqtt-affrontare-al-meglio-upgrade/) per sopperire alla sparizione delle entità di tipo sensor.*_action
La soluzione sarebbe:
```
    triggers:
      - trigger: device
        domain: mqtt
        device_id: #l'ID del device
        type: action
        subtype: single
        ID: single
```
Ho recuperato il device_id del mio [Aqara](https://www.zigbee2mqtt.io/supported-devices/#v=Aqara) 
Modello
[WXKG12LM](https://www.zigbee2mqtt.io/devices/WXKG12LM.html#aqara-wxkg12lm)
(per chi non lo sapesse in HA impostazioni->integrazioni->mqtt cliccate sul vostro dispositivo e la parte finale dell'url del browser è il device id).
Tuttavia al primo colpo non sembra funzionare. Quindi sono andato a vedere in HA-> strumenti sviluppatore -> Eventi -> ascolta eventi "action" e anche premendo fisicamente il mio aqara, non compariva. Ho quindi pensato che nel mio caso non fosse un type: action.
Ho quindi cliccato su More Info in (HA->impostazioni->Integrazioni->Mqtt->il mio dispositivo aqara.
Li ho trovato 3 Attivazioni (mqtt discovery data):
```
Topic: homeassistant/device_automation/0x00158d00044c32ea/action_hold/config
Topic: homeassistant/device_automation/0x00158d00044c32ea/action_release/config
Topic: homeassistant/device_automation/0x00158d00044c32ea/action_single/config
```
Che volendo posso espandere per visionare il relativo payload che è (nel primo caso action_single):
```
automation_type: trigger
device:
  identifiers:
    - zigbee2mqtt_0x00158d00044c32ea
  manufacturer: Aqara
  model: Wireless mini switch (with gyroscope) (WXKG12LM)
  sw_version: 3000-0001
  via_device: zigbee2mqtt_bridge_0x00124b0024c1671a
  name: Campanello
origin:
  name: Zigbee2MQTT
  sw_version: 1.40.2
  support_url: https://www.zigbee2mqtt.io
payload: single
subtype: single
topic: zigbee2mqtt/Campanello/action
type: action
```
Quindi ho optato per la vostra soluzione seconda soulzione:

```
    triggers:
      - trigger: mqtt
        payload: "single"
        topic: zigbee2mqtt/NOME_MQTT_DEL_PULSANTE/action
        ID: single
```
nel mio caso 
```
    triggers:
      - trigger: mqtt
        payload: "single"
        topic: zigbee2mqtt/Campanello/action
```
Ma evidentemente sbaglio qualcosa perchè non va. Qualcun altro è già inciampato dove sto inciampando io?
