### DISCUSSION TITLE
Integrazione Ecovacs e gestione zone di pulizia

### DISCUSSION THREAD

**Discussion by alexcroce** [indomus/forum#3342] [Nuove idee, proposte, progetti e guide]
Buongiorno,
come consigliatomi nel gruppo Telegram, vi posto qui quello che ho fatto per poter gestire la pulizia delle varie zone dalla card custom:vacuum che si trova su Hacs.

Innanzitutto ci andiamo a ricavare dalle proprietà dell'aspiravolvere i numeri corrispondenti alle stanze:

![image](https://github.com/user-attachments/assets/a568baba-c3ae-4908-80de-b674320cb393)

Nel mio caso la cucina ha il valore 0 e la sala il valore 1.

A questo punto creiamo gli script per ogni stanza che vogliamo pulire, ve ne metto uno per esempio:

```
sequence:
  - action: vacuum.send_command
    metadata: {}
    data:
      command: spot_area
      params:
        rooms: 0
        cleanings: 1
    target:
      device_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
alias: Deboot Pulisci Cucina
description: ""

```
Per effettuare la pulizia ovunque basterà mettere in uno script apposito lo stesso codice e, in rooms, tutti i numeri delle stanza intervallati dalla virgola.

Una volta fatto questo andiamo a creare la card. Vi posto lo yaml della mia, ovviamente personalizzatelo con i vostri sensori, il vostro robot e i nomi dei vostri script:

```
type: custom:vacuum-card
entity: vacuum.deebot
image: default
compact_view: false
show_name: true
show_toolbar: true
show_status: true
stats:
  default:
    - entity_id: sensor.deebot_side_brush_lifespan
      unit: "%"
      subtitle: Spazzole laterali
    - entity_id: sensor.deebot_main_brush_lifespan
      unit: "%"
      subtitle: Spazzola Princiale
    - entity_id: sensor.deebot_filter_lifespan
      unit: "%"
      subtitle: Filtro
  cleaning:
    - entity_id: sensor.deebot_area_cleaned
      unit: m2
      subtitle: Area
    - entity_id: sensor.deebot_cleaning_duration
      unit: min
      subtitle: Time
shortcuts:
  - service: script.deboot_cucina
    icon: mdi:stove
    name: Pulisci Cucina
  - service: script.deboot_pulisci_sala
    icon: mdi:sofa-outline
    name: Pulisci Sala
  - service: script.deboot_pulisci_ovunque
    icon: mdi:robot-vacuum-variant
    name: Pulisci Ovunque

```

Il risultato finale sarà il seguente:

![image](https://github.com/user-attachments/assets/bee6f472-9fe3-4422-9f7a-fe553e04c305)

**Comment by gdr1993** [comment]
Grazie del tuo prezioso contributo, dov è possibile trovare una ista completa di comandi? per esempio se oltre `cleanings` vorrei soltanto aspiare o soltanto lavare qual è il comando ?

**Reply by alexcroce** [reply]
Grazie a te per il riscontro! 

Io ho fatto riferimento a queste informazioni:

https://deebot.readthedocs.io/integrations/home-assistant/

**Reply by gdr1993** [reply]
Grazie, gli do un occhiata, saresti cosi gentile da postare tutti e 3 gli script inseriti qui? ho provato a copiare quello sopra ma non mi funziona. nello specifico il nome dello script ` - service: script.deboot_cucina` dove lo inserisci in questo codice? 
`sequence:
  - action: vacuum.send_command
    metadata: {}
    data:
      command: spot_area
      params:
        rooms: 0
        cleanings: 1
    target:
      device_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
alias: Deboot Pulisci Cucina
description: ""`

grazie

**Reply by alexcroce** [reply]
Il nome gliel'ho dato direttamente dall'interfaccia script di homeassistant. Impostazioni - > Automazioni e scenari - > Script. Una volta che lo hai salvato quando nell'editor yaml inizi a scrivere "script." il completamento automatico ti fa uscire l'elenco degli script memorizzati e lo scegli.

**Reply by gdr1993** [reply]
Perfetto ci sono riuscito, unico problema è che non mi funziona l'immagine con `shortcuts:
  - service: script.deboot_cucina
    icon: mdi:stove
    name: Pulisci Cucina`

![Screenshot 2025-01-08 194234](https://github.com/user-attachments/assets/27088306-a292-433c-9d88-4f48d649d92e)
da cosa puo dipendere? mi resta bianco

**Reply by alexcroce** [reply]
Questo non saprei dirti... Se provi a mettere un'altra icona?

**Reply by gdr1993** [reply]
ci sono riuscito, c'era uno spazio in piu. ho problemi con lo script. l'action `vacuum.send_command` non esiste. oltre l'integrazione nativa di deeboot hai installato altro?
![Screenshot 2025-01-08 195343](https://github.com/user-attachments/assets/0de520a8-780b-4af6-83c6-95abe96158df)

**Reply by alexcroce** [reply]
Se vai da Strumenti per sviluppatori e poi Azioni e digiti Vacuum.send_command non te lo dà?
Io ho installato solo l'integrazione ecovacs ufficiale.

![Screenshot_2025-01-08-20-28-09-26_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/f4360b7b-36a6-4f02-8432-4610d02816ec)

**Reply by gdr1993** [reply]
si, compilo cosi ma non va
![Screenshot 2025-01-08 203531](https://github.com/user-attachments/assets/8b6fee13-dfa1-4422-9e97-44c764d412bd)
dice comando inviato ma l'aspirapolvere non parte

**Reply by alexcroce** [reply]
Togli il primo dei due "robot". La stanza 7 esiste?

**Reply by gdr1993** [reply]
non va nemmeno cosi
![Screenshot 2025-01-08 204330](https://github.com/user-attachments/assets/48aabfb9-f7df-4be8-871f-2890d80c7145)
![Screenshot 2025-01-08 204307](https://github.com/user-attachments/assets/7d5ea14f-c919-41e1-a111-56ffb29a7854)

**Reply by alexcroce** [reply]
Dovevi togliere l'altro robot. Lascia solo quello con l'icona dell'aspirapolvere

**Reply by gdr1993** [reply]
niente
![Screenshot 2025-01-08 210133](https://github.com/user-attachments/assets/6fe49cea-c400-489d-a5c6-233f6a54f2d4)

**Reply by alexcroce** [reply]
Fammi vedere lo  yaml (al posto di xxx nel device_id ci deve essere una sequenza alfanumerica) :

```
action: vacuum.send_command
target:
  device_id: xxxxx
data:
  command: spot_area
  params:
    rooms: 0
    cleanings: 1
```
