### DISCUSSION TITLE
Eliminare un sensore dal calcolo energia

### DISCUSSION THREAD

**Discussion by gdr1993** [indomus/forum#3346] [HUB: Home Assistant]
Buongiorno ho creato un sensore template come segue 

```
sensor:
  - platform: template
    sensors:
      clima_rimanente:
        unique_id: clima_rimanente
        friendly_name: "Clima rimanente"
        unit_of_measurement: 'W'
        value_template: "{{ ((states('sensor.controllo_assorbimento_clima_channel_1_power') | float) - (states('sensor.controllo_assorbimento_clima_channel_2_power') | float)) - (states('sensor.boiler_power') | float) }}"
```

E' un sensore di differenza tra tre sensori e ogni tanto mi va in negativo, vorrei sapere come si fa per escluderlo dal calcolo della scheda energia di cui allego screen.
![Screenshot 2025-01-08 113814](https://github.com/user-attachments/assets/c5935c8a-e959-47e9-a003-da31589fff59)
La parte grigia negativa è dovuta a quel sensore, è grigia in quanto rientra tra i "consumi non monitorati" vorrei fare in modo di escludere proprio quel sensore.

grazie
