### DISCUSSION TITLE
Configurazione termostato

### DISCUSSION THREAD

**Discussion by Matty1184** [indomus/forum#3357] [GENERALE - Discussioni generiche]
Ciao a tutti, 
temo mi sto perdendo in un bicchier d'acqua!
voglio configurare un termostato la quale mi attivi uno shelly (mi apre una valvola del riscaldamento)
```
  - platform: generic_thermostat
    name: Termostato_Cabina_Armadi
    heater: Valvola_Riscaldamento.Pav_Cabina_Switch_0
    target_sensor: sensor.temp_cabina_armadi
    min_temp: 16
    max_temp: 22
    target_temp: 19.5
    cold_tolerance: 0.2
    hot_tolerance: 0.3
    min_cycle_duration:
      seconds: 240
    initial_hvac_mode: "heat"
    precision: 0.1
```
in teoria da come ho letto, quando il termostato va in ON porta a ON l'heater e viceversa.
in realtà nulla....
