### DISCUSSION TITLE
Problema attivazione automazione accensione clima

### DISCUSSION THREAD

**Discussion by Vinz1985** [indomus/forum#336] [HUB: Home Assistant]
Buongiorno, nella definizione delle varie automazioni ho un problema con l'attivazione dell'automazione relativa all'accensione di un determinato dispositivo (nella fattispecie è un climatizzare, ma può valere anche per il termostato ) quando la temperatura è compresa all'interno di un range di valori. In sostanza non mi funziona il trigger dello stato numerico ma l'action, se la eseguo, funziona. 
Il codice non dovrebbe presentare problemi, tuttavia lo posto: (ovviamente i valori erano solo per testare, non è che accendo l'aria fredda con 20° in casa):

```
alias: 6. CLIMA ZONA GIORNO A 18 GRADI di prova
description: ''
trigger:
  - platform: numeric_state
    entity_id: sensor.termostato_vinz_temperature
    above: '19'
    below: '22'
condition: []
action:
  - service: climate.turn_on
    target:
      entity_id: climate.clima_zonagiorno
  - service: climate.set_temperature
    target:
      entity_id: climate.clima_zonagiorno
    data:
      hvac_mode: cool
      temperature: 18
mode: single
```

Da cosa può dipendere?

**Comment by Larry-78** [comment]
Ciao, mi sa che il problema sono gli apici. Eliminali e prova senza forzare l'esecuzione.

**Reply by Vinz1985** [reply]
No Larry purtroppo non è quello. Non va il trigger. Forse non gli piace il sensore della temperatura ma non so che fargli. Per me il codice è giusto.

**Comment by KC-inDomus** [comment]
non sono sicuro che tu possa usare above e below in quel modo. prova con un trigger template

**Comment by Larry-78** [comment]
Ci stavo appena pensando e l'ho buttato al volo, non sono sicuro se è giusto ma ho fatto una prova con un mio sensore sul Template in Developer Tools e mi restituisce true/false a seconda delle temperatura  che ho provato a modificare
```yaml
  trigger:
    - platform: template
      value_template: "{{ ((states.sensor.termostato_vinz_temperature.state) | float > 19 ) and ((states.sensor.termostato_vinz_temperature.state) | float < 22 )}}"
```

**Reply by Vinz1985** [reply]
Provato e funziona solo se attivo esattamente come nell'opzione del numeric state, se salvo ed esco nulla...non va in automatico...nemmeno validando e riavviando...Ovviamente anche a me da valore TRUE la tua stringa.

**Reply by Larry-78** [reply]
Oppure l'alternativa potrebbe essere che ti crei due input_number che saranno le tue temperature Min e Max e in base a quelli potrai creare un binary_sensor template che diventerà on quando la temperatura rilevata sarà compresa nel range due valori. In fine potrai utilizzarlo come trigger per l'automazione.

**Reply by Vinz1985** [reply]
si ma non dovrebbe funzionare cosi, secondo me sia con lo numeric state che col template dovrebbe funzionare...io davvero rimango interdetto

**Reply by Larry-78** [reply]
Si infatti la documentazione ufficiale porta alcuni esempi e comunque dovrebbe triggerare una sola volta appena entrato nel range. 
https://www.home-assistant.io/docs/automation/trigger/#numeric-state-trigger
Ma quel sensore che tipo è? Come stai effettuando i test temperatura?

**Reply by Larry-78** [reply]
...poi non è chiaro: funziona solo se attivo esattamente come nell'opzione del numeric state

**Reply by Larry-78** [reply]
Ad ogni modo ho fatto un test al volo con un mio sensore temperatura e ho attivato un semplice servizio light.turn_on e funziona, ho giusto modificato un pò il template.
```yaml
alias: prova trigger template
description: ''
trigger:
  - platform: template
    value_template: >
      {{ states('sensor.temperatura_cucina') | float > 19  and
      states('sensor.temperatura_cucina') | float < 22 }}
condition: []
action:
  - service: light.turn_on
    target:
      entity_id: light.ingresso
mode: single
```

**Reply by Vinz1985** [reply]
ciao Larry, significa che se esco dall'automazione e spingo ESEGUI AZIONE funziona (il condizionatore si accende e si imposta alla temperatura impostata nella action) sia col mio codice (trigger numeric state) sia col tuo (template). Non essendoci condizioni e visto che l'action funziona, per esclusione, rimane che il problema ovviamente è il TRIGGER. 
Quel sensore è il sensore del termostato collegato alla caldaia.  

Tuttavia a titolo di prova, ho cambiato e anziche mettere come variabile il sensore di temperatura del termostato ho messo quello di temperatura del telefono e una banale action di accensione di una luce (anziche l'accensione del climatizzatore). 
```
alias: 'PROVA'
description: ''
trigger:
  - platform: template
    value_template: >-
      {{ ((sensor.honor_vinz_temperatura_della_batteria) > 20 ) and
      ((sensor.honor_vinz_temperatura_della_batteria) < 35 )}}
condition: []
action:
  - service: switch.turn_on
    target:
      entity_id: switch.sonoff_1000b47b8a
mode: single
```
Stessa identica situazione, se faccio ESEGUI AZIONE funziona, se invece esco,salvo e riavvio non va; ciò mi porta a pensare: non è che non si instaura il trigger perchè devo eseguire qualcosa che mi sfugge (tipo una dichiarazione nel configuration.yaml o qualche impostazione che faccia partire in automatico le action) ?

**Comment by Vinz1985** [comment]
che dirti, il trigger non parte. il codice è corretto, ho provato la tua stessa configurazione. Sono uscito, ho salvato anche con un nome diverso l'automazione. Ho persino validato e riavviato, nulla. Il trigger non mi va...Forse non legge i sensori, che ti devo dire, è assurdo.

**Reply by Larry-78** [reply]
Ok adesso ho compreso. 
Per fare un pò di chiarezza, quando si crea un'automazione e quindi dopo aver salvato ed eventualmente controllato la configurazione e ricaricato da Server Controls, è attiva subito solo che rimane in attesa che si verifichi il trigger. Non c'è nessuna impostazione su confguration.yaml a parte il riferimento al file automations.yaml.
Se fai ESEGUI AZIONE che nella mia versione inglese è RUN ACTION lo dice la parola stessa, non fa altro che "forzare" l'action dell'automazione saltando trigger e condition. Quindi l'unico modo è far si che l'automazione verifichi il trigger per far si che essa possa partire.

**Reply by Larry-78** [reply]
...il mio sensore di temperatura è un semplice Xiaomi a batterie e per far il test mi è bastato metterlo nel frigo per far abbassare la temperatura, superata la soglia l'ho messo al sole ed è stato molto preciso, appena è arrivato a 19,1 si è accesa la luce.
Comunque dai uno sguardo ai logs.

**Reply by Vinz1985** [reply]
mi hai anticipato, alla fine sono andato al log e mi appare un warning 
![image](https://user-images.githubusercontent.com/83169955/118933526-96e0d400-b949-11eb-842d-9d5e4675c155.png)

**Reply by Vinz1985** [reply]
Template variable warning: 'dict object' has no attribute 'program' when rendering '{{ value_json.program }}'
Template variable warning: 'dict object' has no attribute 'remaining_time' when rendering '{{ value_json.remaining_time }}'
Template variable warning: 'dict object' has no attribute 'remaining_time_minutes' when rendering '{{ value_json.remaining_time_minutes }}'

Ecco gli errori, sicchè non capisco cosa non va sinceramente tra come l'hai scritto tu il codice e come l'ho scritto io. Mi vien da pensare che ho problemi ai sensori a sto punto. Non li legge o trova errori di non so quale tipo

**Reply by Larry-78** [reply]
non penso si riferiscano a quel template creato. Fa riferimento a degli attributi mancanti 'program', 'remaining_time', 'remaining_time_minutes'. forse su entità che hai creato, non sono un esperto su interpretazioni dei logs...
Per far scattare il trigger devi fare in modo da abbassare oppure alzare la temperatura del sensore e portarlo fuori dal range, solo quando rientrerà potrà triggerare. Come hai fatto ad abbasare la temp del sensore termostato oppure alzarla oltre la soglia? Hai provato anche con il sensore della batteria, sei sicuro di essere uscito fuori range? Soltanto in questo modo potrai assicurarti che il trigger scatti correttamente.

**Reply by Larry-78** [reply]
ho provato anche così e funziona
```yaml
alias: prova trigger template
description: ''
trigger:
  - platform: numeric_state
    entity_id: sensor.temperatura_cucina
    above: '19'
    below: '22'
condition: []
action:
  - service: light.turn_on
    target:
      entity_id: light.ingresso
mode: single
```
e l'ho provato in entrambi i sensi, cioè prima da una temp più alta verso il range e poi da una temp più bassa verso il range e ha funzionato entrambe le volte.
