### DISCUSSION TITLE
Mappare directory su container HA

### DISCUSSION THREAD

**Discussion by braudoo** [indomus/forum#3361] [HUB: Home Assistant]
Ciao a tutti, sto tentando in tutti i modi di mappare una directory sul container HA e aggiungerla poi su sotto  **allowlist_external_dirs:**
Di seguito i passaggi:
aggiunto quanto segue nel **docker-compose.yaml**
```
    volumes:
    - ~/homeassistant/.homeassistant:/config
    - /run/dbus:/run/dbus:ro
    - ~/homeassistant/.homeassistant/media:/media
    - /export/nas_5tb/ipcam_movies:/ipcam_movies
```
eseguito stack con
`docker compose up -d`

Aggiunto nel **configuration.yaml** 
```
homeassistant:
  packages: !include_dir_named packages
  customize: !include configurations/customize.yaml
  media_dirs:
    local: /media
  allowlist_external_dirs:
    - "/tmp"
    - "/export/nas_5tb/ipcam_movies"
```

Ma al riavvio mi da questo errore:

`Impossibile eseguire l'azione: homeassistant/restart The system cannot restart because the configuration is not valid: Invalid config for 'homeassistant' at configuration.yaml, line 24: Not a directory 'allowlist_external_dirs->1', got '/export/nas_5tb/ipcam_movies`

Direi di avere messo tutte le info.

Qualcuno riesce a darmi un'aiuto?

Grazie
