### DISCUSSION TITLE
integrare climatizzatore con broadlink e smartIR

### DISCUSSION THREAD

**Discussion by Samubol** [indomus/forum#3366] [HUB: Home Assistant]
Buongiorno. seguita la guida indicata in titolo ora vorrei aggiungere alla plancia la grafica di controllo che mi appare selezionando l entita "climate.mitsubishi" che si è creata in SmartIR ma cio non è possibile in quanto non ha un id univoco. come devo fare per averla in plancia (panoramica)? grazie

**Comment by Scialla** [comment]
aggiungi una card `Thermostat` usando la tua entità `climate`

**Reply by Samubol** [reply]
Ho aggiunto una card per l entità “climate.mitsubishi_clima” alla plancia però è molto strano che non mi permetta di eseguire automazioni. Praticamente posso comandarlo solo dalla plancia.

**Reply by Scialla** [reply]
Le automazioni non si fanno dalla plancia, le devi scrivere tu in yaml o appoggiandoti alla webui

**Comment by Samubol** [comment]
volevo dire che, volendo creare l automazione da "impostazioni" e "automazioni e scenari" non è possibile in quanto il dispositivo non è nell elenco. quindi ho creato questa:

```
- id: '1737702415746'
  alias: Nuova automazione
  description: ''
  triggers:
  - trigger: time_pattern
    hours: 08
    minutes: '10'
  conditions: []
  actions:
  - action: climate.turn_on
    metadata: {}
    data: {}
  mode: single
```

l automazione viene eseguita ma non succede nulla

**Reply by Scialla** [reply]
gli dici di accendere il climatizzatore senza indicargli quale climatizzatore accendere.... cosa ti aspetti che accada? Aggiungigli il nome dell'entità `climate` che hai usato nella card, guarda nella doc come impostare la cosa, impara a fare le automazioni usando le entità e non i dispositivi

**Reply by Samubol** [reply]
boh. non riesco a capire quali errori commetto. 
questo il file in script.yaml:

```
  action:
    - action: climate.set_swing_mode
      data:
        entity_id: climate.mitsubishi_clima_soggiorno
        swing_mode: auto
    - action: climate.set_fan_mode
      data:
        entity_id: climate.mitsubishi_clima_soggiorno
        fan_mode: auto
    - action: climate.set_temperature
      data:
        entity_id: climate.mitsubishi_clima_soggiorno
        temperature: 21
        hvac_mode: heat
```

mentre questa in automation.yaml

```
- id: "1737887097299"
  alias: Nuova automazione
  description: ""
  triggers:
    - trigger: time_pattern
      hours: "11"
      minutes: "49"
      seconds: "00"
  conditions: []
  actions:
    - action: climate.set_swing_mode
```

eppure non è successo nulla

**Reply by Scialla** [reply]
perché fai le cose a caso....
leggiti la doc del climate:
https://www.home-assistant.io/integrations/climate/
l'esempio riportato nella doc è il seguente:
```
automation:
  triggers:
    - trigger: time
      at: "07:15:00"
  actions:
    - action: climate.set_aux_heat
      target:
        entity_id: climate.kitchen
      data:
        aux_heat: true
```
vedi differenze col tuo?
guardati la doc degli script con i relativi esempi:
https://www.home-assistant.io/integrations/script/
```
# Example configuration.yaml entry
script:
  message_temperature:
    sequence:
      # This is Home Assistant Script Syntax
      - action: notify.notify
        data:
          message: "Current temperature is {{ states('sensor.temperature') }}"
```
le vedi le differenze???

**Reply by Samubol** [reply]
Sì. Vedo molte differenze, l automazione che vedi l ho impostata con “automazioni e scenari” ma è differente da quanto indicato nella doc. Questo mi crea confusione, non conoscendo affatto la materia. Grazie dell aiuto.

**Reply by Scialla** [reply]
la materia si "impara" leggendo la doc ufficiale, ma se questo ti crea confusione devi studiare.... altrimenti, ogni singola automazione, avrai bisogno che te la faccia qualcuno...
Devi partire dalle basi!
Tanto per cominciare non hai specificato dove stai creando questo script e questa automazione, se lo stai facendo dalla UI, se stai usando i file sidecar, se stai usando un package... se quello che ho appena scritto per te è arabo parti dalle nozioni di base, ci sono guide sul sito che spiegano tutto, anche questi termini.

Se stai scrivendo tutto nel `configuration.yaml` lo script va preceduto da `script:` e l'automazione da `automation:`

ora, lo script, come dall'esempio che ti ho postato (sempre dando per scontato che tu lo stia creando all'interno del file `script.yaml` dopo avere incluso il file sidecar all'interno del `configuration.yaml` tramite `script: !include script.yaml` perché, se non lo hai fatto devi aggiungere `script:`)  è sbagliato perché:
- manca il nome dello script
- manca `sequence:`
- l'entità da pilotare deve stare sotto `target:`

quindi, il tuo script diventerebbe:
```
nome_tuo_script:
  sequence:
    - action: climate.set_swing_mode
      target:
        entity_id: climate.mitsubishi_clima_soggiorno
      data:
        swing_mode: "auto"
    - action: climate.set_fan_mode
      data:
        entity_id: climate.mitsubishi_clima_soggiorno
        fan_mode: "auto"    
    - action: climate.set_temperature
      data:
        entity_id: climate.mitsubishi_clima_soggiorno
        temperature: 21
        hvac_mode: heat
```
la tua automazione invece non può funzionare perché il `trigger` è sbagliato, come già ti avevo scritto, non hai indicato l'entità da richiamare, non indichi quale condizionatore vuoi usare ne gli passi i parametri, cosa vuoi fare? vuoi lanciare lo script? E, se così fosse, perché hai separato lo script dall'automazione? Insomma stai facendo una confusione pazzesca, devi STUDIARE!

Poi, perché usi come `trigger` un `time_pattern`??? Sai come funziona?
https://www.home-assistant.io/docs/automation/trigger/#time-pattern-trigger
il `time_pattern` serve a far partire l'automazione di continuo, ogni intervallo temporale che devi specificare e non a un'ora che indichi, quello è il trigger `time`

Quindi, cercando di immaginare quello che stai cercando di fare (e ti assicuro non è facile), se vuoi che alle 11:49 il tuo condizionatore parta con i parametri che hai indicato devi creare una automazione completa (senza script) con tutti i parametri necessari, ad esempio:

```
- id: "1737887097299"
  alias: Nuova automazione
  description: ""
  triggers:
    - trigger: time
      hours: "11"
      minutes: "49"
  actions:
    - action: climate.set_swing_mode
      target:
        entity_id: climate.mitsubishi_clima_soggiorno
      data:
        swing_mode: "auto"
    - action: climate.set_fan_mode
      data:
        entity_id: climate.mitsubishi_clima_soggiorno
        fan_mode: "auto"    
    - action: climate.set_temperature
      data:
        entity_id: climate.mitsubishi_clima_soggiorno
        temperature: 21
        hvac_mode: heat
```

questa la sintassi poi non entro nel merito del funzionamento, da vedere come ottimizzare e come hai integrato il condizionatore.

Però capisci che ci va un sacco di tempo a spiegarti cosa per cosa se non sai cosa stai facendo?
Parti dalle basi, studia cosa sono i file yaml, i sidecar, i package, gli script, le automazioni, poi inizi a cercare di fartele seguendo la doc ufficiale, se no non ne esci..
