### DISCUSSION TITLE
configurazione fail2ban con docker

### DISCUSSION THREAD

**Discussion by daiv87** [indomus/forum#3384] [GENERALE - Discussioni generiche]
Come da titolo non ho trovato molto in rete per cui vorrei condividere con voi ciò che sono riuscito a fare ... sarà sicuramente utile a qualcuno.
il problema principale sta che caddy scrive i log in formato json.... l 'alternativa più pulita è far scrivere i log in un altro formato ( io ne ho provato vari ma l ' unico che legge è il " console " per  cui la prima cosa che si fa è modificare il caddy file così:
```
https://miodominio.ddns.net:XX25 {
  import https_header
  reverse_proxy http://192.168.1.112:8123
  log {
    output file /var/log/caddy/ha.log {
      roll_size     5MiB
      roll_keep     2
      roll_keep_for 48h
    }
    format console
  }
}
```
controlliamo che i log di caddy cambino da così
```
`http.log.access.log0	handled request	{"request": {"remote_ip": "151.74.135.6", "remote_port": "60242", "client_ip": "151.74.135.6", "proto": "HTTP/2.0", "method": "GET", "host": "miodominio.ddns.net:8125", "uri": "/frontend_latest/73113.98009bf87fe9a89c.js", "headers": {"Sec-Fetch-Site": ["same-origin"], "Accept-Encoding": ["gzip, deflate, br"], "Sec-Fetch-Mode": ["cors"], "User-Agent": ["Mozilla/5.0 
```
a così
```
151.74.135.6 - - [02/Mar/2025:22:05:53 +0000] "GET /frontend_latest/73113.98009bf87fe9a89c.js HTTP/2.0" 200 10239
```

dopo di che si procede a creare fail2ban

ho creato i file di configurazione 
```
mkdir -p /home/deb/container/fail2ban/{config,logs}
```
 creare il jail.local
 ```
nano /home/deb/container/fail2ban/config/jail.local
```
e incollare dentro 
```
[DEFAULT]
bantime = 10m
findtime = 10m
maxretry = 5
backend = auto
logtarget = STDOUT

[Caddy]
enabled = true
filter = caddy
logpath = /home/deb/container/config/caddy/log/ha.log
port = http,https
```
bantime → Blocca un IP per 10 minuti dopo troppi tentativi falliti.
findtime → Considera solo i tentativi negli ultimi 10 minuti.
maxretry → Dopo 5 tentativi errati, l'IP viene bannato.
logpath → Percorso del log di Caddy che Fail2Ban analizzerà.

Ora creiamo il filtro per rilevare i tentativi di accesso malevoli:
```
nano /home/deb/container/fail2ban/config/filter.d/caddy.conf
```
e incolliamo dentro :
```
[Definition]
failregex = .*"remote_ip":\s?"<HOST>".*"status":\s?(403|401|404)

ignoreregex =

```
Intercetta errori 403, che indicano accessi vietati.
Esclude altri codici HTTP per evitare falsi positivi.
l codice HTTP “401  il visitatore non ha fornito credenziali valide
Ho incluso lo status code 404 nel filtro di Fail2Ban, il che significa che Fail2Ban registrerà anche gli accessi che generano errori 404 Not Found e potrebbe bannare gli IP che fanno troppe richieste che restituiscono 404. Quindi ho Protezione dagli scanner automatici
e Mitigare attacchi di enumerazione infatti alcuni attaccanti cercano di scoprire risorse nascoste (come pagine di login o API private) inviando molte richieste a URL inesistenti. Se un IP causa troppi 404 in un breve periodo, potrebbe essere un tentativo di enumerazione.

Questo è il mio docker-compose
```
version: '3.8'

services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /home/deb/container/config/fail2ban:/data
      - /home/deb/container/config/caddy/log:/var/log/caddy:rw
      - /home/deb/container/config/fail2ban/config/filter.d:/etc/fail2ban/filter.d
      - /home/deb/container/config/fail2ban/config/jail.local:/etc/fail2ban/jail.local:ro
    environment:
      - F2B_LOG_TARGET=STDOUT
      - F2B_DB_PURGE_AGE=1d
      - TZ=Europe/Rome
```
network_mode: "host" → Permette a Fail2Ban di bloccare gli IP sulla rete host.
cap_add (NET_ADMIN, NET_RAW) → Permette a Fail2Ban di gestire le regole di iptables.
dopo aver controllato che non ci siano errori nel log
```
docker logs -f fail2ban
```
testiamo se compare caddy nel jail.list
```
docker exec -it fail2ban fail2ban-client status
Status
|- Number of jail:      1
`- Jail list:   Caddy
```
così abbiamo lo status delle jail di caddy 
```
docker exec -it fail2ban fail2ban-client status Caddy
Status for the jail: Caddy
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     11
|  `- File list:        /var/log/caddy/ha.log
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
  ```
  ora generiamo dei test per vedeere se il conteggio aumenta con curl
  ```
  curl -I https://miodominio.ddns.net:XX25/prova_ban
```
controlliamo lo status 
```
docker exec -it fail2ban fail2ban-client status Caddy
```
Se Total failed aumenta, significa che Fail2Ban sta riconoscendo gli errori
Per vedere gli IP attualmente bannati, puoi usare il comando usare lo stesso comando di prima
Per rimuovere manualmente un IP bannato, usare il comando 
```
docker exec -it fail2ban fail2ban-client unban <IP_ADDRESS>
```

se sospettiamo che  Fail2Ban stia bannando in modo errato, puoi controllare i log di Caddy per capire meglio cosa sta succedendo. Puoi fare una ricerca con:
```
docker exec -it fail2ban grep "151.74.135.6" /var/log/caddy/ha.log
```
Questo ti aiuterà a capire se l'IP sta generando errori legittimi che portano al ban.
quindi modifichiamo  maxretry,findtime, e la regex.
spero che vi sia utile 😄
