### DISCUSSION TITLE
Integrazione Alexa - Actionable Notifications

### DISCUSSION THREAD

**Discussion by 81daniele81** [indomus/forum#3387] [HUB: Home Assistant]
Buonasera a tutti, dopo una serie infinita di tentativi chiedo il vostro supporto.
Ho seguito la guida "Botta e risposta con Alexa su HA" ed eseguiti tutti i passaggi con successo compreso il test dello script per fare pronunciare una frase al mio Echo.
Non riesco invece a generare le automazioni, nello specifico già la prima che riporto sotto, perché ottengo l'errore "Message malformed: extra keys not allowed @ data['0']", anche nel caso che provi a formattare diversamente il testo alla ricerca di errori mi dà gli errori più svariati.
Codice formalmente corretto, come verificato online, ma non riesco a chiudere il cerchio.

Grazie dell'attenzione che vorrete darmi.

```

automation:
  - alias: Innesco actionable notifications
    id: "innesco_actionable_notifications"
    trigger:
    - platform: state
      entity_id: input_button.alexa_actionable_notification_trigger
    action:
    - action: script.activate_alexa_actionable_notification
      data:
        text: "Sì o no?"
        event_id: aan_test
        alexa_device: media_player.cucina

```

**Comment by Scialla** [comment]
la guida è da sistemare..

così funziona:
```
  - alias: Innesco actionable notifications
    id: "innesco_actionable_notifications"
    triggers:
    - trigger: state
      entity_id: input_button.alexa_actionable_notification_trigger
    actions:
    - action: script.activate_alexa_actionable_notification
      data:
        text: "Sì o no?"
        event_id: aan_test
        alexa_device: media_player.echo_studio
        
```
