### DISCUSSION TITLE
Automazioni - shelly 2pm/2.5

### DISCUSSION THREAD

**Discussion by baldus88** [indomus/forum#3410] [HUB: Home Assistant]
Ciao ragazzi, io ho degli shelly montanti nelle pulsantiere delle tapparelle elettriche, ho 3 shelly 2pm e 1 2.5 ancora in vita.
Ho configurato un'automazione su home assistant dove mi chiude tutte le tapparelle e spegne le luci quando il gps del telefono esce di casa e viceversa quando rientro e apro la porta si apre tutto e riaccende le luci (in base a gli orari del giorno).
Ha funzionato sempre tutto, ora da qualche mese ho dei problemini. 

In maniera apparentemente randomica, ma a sto punto non credo, quando esco non si chiudono le tapparelle o quando rientro non si riaprono, ma le luci per dire si accendono quindi l'automazione di per sè funziona.
Per farli risvegliare devo fare il riavvio di tutto home assistant, e per un po' funziona poi muore di nuovo.
E' un problema secondo voi dei HA o gli shelly danno i numeri?
Premetto che li vedo sempre online, non è che si sganciano dalla wifi o altro.
Se devo fare qualche controllo specifico fatemi sapere

**Comment by snakuzzo** [comment]
Controlla i log di HA per vedere se c'è qualcosa che non va.
Uno non è che può darti risposte a sensazione.

**Comment by baldus88** [comment]
Questo è quello che vedo nel trace dell'automazione rientro - tapparelle:
```
Triggered by the state of device_tracker.iphone at March xx, 2025 at xxx
Stopped because only a single execution is allowed at March 15, 2025 at 10:38:14 AM (runtime: 0.00 seconds)
```

Questa è l'automazione che parte in parallelo per le luci e che funziona:
```
Triggered by the state of device_tracker.iphone at March xx, 2025 at xxx
Test If Sun is Below horizon
Stopped because a condition failed at March 15, 2025 at 10:38:14 AM (runtime: 0.00 seconds)
```

Premesso che le automazioni non le ho toccate e home assistant è alla release 2025.1.2. Mi sono perso qualche cambiamento?

**Reply by snakuzzo** [reply]
Il primo messaggio non c'entra nulla con la seconda automazione, ma si riferisce alla stessa automazione. Per qualche motivo l'automazione parte più volte...ed essendo probabilmente in single mode, interrompe la action.

Pubblica il codice dell'automazione che non va.
Inoltre, perché non fare una sola automazione ???

**Comment by baldus88** [comment]
Questa è l'automazione per l'uscita, ed è unica:

```
alias: Esco da casa
triggers:
  - entity_id: device_tracker.xxx
    to: not_home
    trigger: state
actions:
  - entity_id: group.luci
    action: light.turn_off
  - data:
      entity_id: group.tapparelle
      position: 20
    action: cover.set_cover_position
  - data:
      entity_id: group.valvole
      temperature: 18
    action: climate.set_temperature
mode: single
```

Per il rientro probabilmente non ricordo all'epoca come mai ho fatto sta pazzia ma sicuramente si possono accorpare. Per anni hanno sempre funzionato anche separati, magari non centra nulla ma lo dico per cronaca
