### DISCUSSION TITLE
Sensore lock senza azione per Switchbot Lock Pro

### DISCUSSION THREAD

**Discussion by homeassistantby17** [indomus/forum#3418] [HUB: Home Assistant]
Buongiorno,

ho installata una serratura Switchbot Lock Pro che espone il controllo lock.serratura_porta_ingresso, aggiunto alla vista principale di HA diventa un controllo che, da cellulare, rischio di azionare senza volerlo.

![image](https://github.com/user-attachments/assets/ab6eb901-8ef1-413c-84ad-231add4bc210)

![image](https://github.com/user-attachments/assets/50dfbded-e021-423d-981e-fb257ca14901)

Vorrei poter aggiungere alla vista, al posto di questo controllo, o una sua entità identica ma che non faccia azioni, oppure un sensore aggiuntivo che riporti lo stato del lock, ovvero locked, locking o unlocked.
Ho provato, senza successo e seguendo le guide su inDomus, a fare un sensore template:

```
- platform: template
  sensors:
    serratura_porta_ingresso:
    name: "Serratura porta ingresso"
    value_template: "{ states.serratura_porta_ingresso }"
```

Il risultato è che mostra la stringa { states.serratura_porta_ingresso } ma se tolgo i doppi apici il check della configurazione del file YAML fallisce.

Potreste aiutarmi? Grazie.
