### DISCUSSION TITLE
Creazione sensore cumulativo in positivo e negativo

### DISCUSSION THREAD

**Discussion by DJTech84** [indomus/forum#3419] [GENERALE - Discussioni generiche]

**Comment by DJTech84** [comment]
Ciao a tutti, riformulo la domanda aggiungendo più dettagli.
Sto cercando di configurare la scheda energy attraverso alcuni sensori dell'inverter.

**sensor.inverter_ac_out_watt** si occupa di leggere i watt in uscita dell'inverter verso l'abitazione
**sensor.inverter_pv_charging_power** si occupa di dire quanti watt stanno producendo i pannelli
**sensor.inverter_battery_load** mostra gli ampere con valori positivi (per la carica) o negativi (se è in scarica)

tramitre mqtt interrogo l'inverter ma NON esiste un sensore che mi permetta di avere carica e scarica della batteria, 
sto provando a crearli ma non sto risolvendo nulla.

Il calcolo che sto effettuando per la batteria in fase di carica è:
potenza pannelli - potenza uscita inverter - 70 w di autoconsumo
Questa dovrebbe essere la potenza pulita che viene immagazzinata e ho creato un sensore chiamato **sensor.batteria_calc**


batteria per la scarica  
se sensor.inverter_battery_load
sensor.inverter_ac_out_watt - sensor.inverter_pv_charging_power  se **sensor.inverter_battery_load** è negativo

```
- sensor:
      - name: "Energia Carica Batteria"
        unique_id: "energia_carica_batteria"
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        state: >
          {% set batteria_calc = states('sensor.batteria_calc') | float(0) %}
          {% if batteria_calc > 0 %}
            {{ (batteria_calc / 1000 / 60 / 60) | round(4) }}
          {% else %}
            0
          {% endif %}

     - name: "Energia Scarica Batteria"
        unique_id: "energia_scarica_batteria"
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        state: >
          {% set batteria_calc = states('sensor.batteria_calc') | float(0) %}
          {% if batteria_calc < 0 %}
            {{ (batteria_calc * -1 / 1000 / 60 / 60) | round(4) }}
          {% else %}
            0
          {% endif %}

- platform: integration
    source: sensor.energia_carica_batteria
    name: "Energia Carica Batteria Totale"
    unit_prefix: k
    round: 2
    method: trapezoidal
    unique_id: "energia_carica_batteria_totale"

  - platform: integration
    source: sensor.energia_scarica_batteria
    name: "Energia Scarica Batteria Totale"
    unit_prefix: k
    round: 2
    method: trapezoidal
    unique_id: "energia_scarica_batteria_totale"

homeassistant:
  customize:
    sensor.energia_carica_batteria_totale:
      device_class: energy
      state_class: total_increasing
      unit_of_measurement: kWh

    sensor.energia_scarica_batteria_totale:
      device_class: energy
      state_class: total_increasing
      unit_of_measurement: kWh
```
il sensore scarica  non appare nella scheda energy
potete aiutarmi a farli funzionare?
grazie a chiunque mi possa dare delle dritte
