### DISCUSSION TITLE
Impossibile modificare la zona

### DISCUSSION THREAD

**Discussion by jimborm** [indomus/forum#3422] [HUB: Home Assistant]
Ciao vorrei modificare la grandezza della zona home . se vado da interfaccia grafica non mi permette alcuna modifica di quella zona indicando che è configurata nel file configuration.yaml
Ho verificato e in quel file non ci sono rifermenti alla zona home. Sapete dove altro potrei cercare?
![image](https://github.com/user-attachments/assets/42653628-ff8d-4ff9-9d27-eb3fb5001bb2)

**Comment by Scialla** [comment]
non hai cercato bene, hai sicuramente (possibile in qualsiasi punto dentro al file) qualcosa di simile:
```
zone:
  - name: Home
    latitude: xx.xxxxxx
    longitude: x.xxxxxx
    radius: 125
    icon: 'mdi:home'
 ```
dove `radius` è il raggio del cerchio
