### DISCUSSION TITLE
Problema con sensore command_line per lettura access token da file .txt

### DISCUSSION THREAD

**Discussion by zaro1969** [indomus/forum#3423] [GENERALE - Discussioni generiche]
Ciao a tutti,
sto cercando di integrare nel mio Home Assistant un impianto fotovoltaico SunPower tramite API REST, utilizzando un access token dinamico che salvo in un file di testo (access_token.txt).

Il mio obiettivo è aggiornare automaticamente questo token tramite una shell_command e poi leggerlo con un sensore command_line per iniettarlo nelle chiamate rest:.

⸻

1. Sensore command_line nel configuration.yaml:
sensor:
  - platform: command_line
    name: SunPower Access Token
    command: cat /homeassistant/access_token.txt
    scan_interval: 60

2. REST API con riferimento al sensore:
rest:
  - resource: https://api.sunpower.maxeon.com/v1/systems/SOD001024010160/power_meter
    method: GET
    headers:
      Authorization: "Bearer {{ states('sensor.sunpower_access_token') }}"
      accept: application/json
    scan_interval: 30

3. Shell command per aggiornare il token:
shell_command:
  aggiorna_token_sunpower: >-
    bash -c 'REFRESH_TOKEN=$(cat /homeassistant/refresh_token.txt);
    curl -s -X POST https://api.sunpower.maxeon.com/v1/token
    -H "Content-Type: application/x-www-form-urlencoded"
    -d "grant_type=refresh_token&refresh_token=$REFRESH_TOKEN&client_id=...&client_secret=..."
    | jq -r ".access_token" > /homeassistant/access_token.txt’

Il problema:
	•	Il file access_token.txt è presente e contiene un token valido (verificato manualmente da terminale).
	•	Tuttavia, il sensore sensor.sunpower_access_token non compare tra gli stati.
	•	Questo comporta che i sensori REST restituiscano unknown .

Domanda:
	•	C’è qualcosa che sto sbagliando nella definizione del sensore?
	•	Il sensore command_line non può essere usato per popolare header dinamici in REST?
	•	Qualche suggerimento su come ottenere questo comportamento in modo alternativo?

Grazie mille a chi potrà darmi una mano!

**Comment by snakuzzo** [comment]
Ciao.
Se posso darti qualche consiglio, visto che ho fatto una cosa simile per Tado per controllare l'offset delle teste termostatiche che non è previsto nativamente...

Alcune premess...
- Innanzi tutto è fondamentale che tu ti metta a guardare i log per vedere qual è il problema. Con l'approccio che hai seguito non capirai mai cosa accade
- Devi tener presente che l'access token potrebbe avere più caratteri di quelli ammessi per uno stato di un'entità (255). Quindi, se vuoi memorizzarlo in un'entità, devi memorizzarlo come attributo e non come stato
- Non so se utilizzi docker o altro, ma devi considerare che i path che utilizzi per richiamare gli script o i file non sono come li vedi tu sull'host, ma dipendono dall'environment dell'applicazione

Ti riassumo poi quello che ho fatto, così potresti trarne spunto...

Ho un sensore di tipo command line che esgeue uno script python per la gestione dell'autenticazione (inclusa la refresh token) che restituisce in output una JSON string. Da lì vado a recuperare il response code come stato e tutti gli altri parametri, incluso l'access token, che vado a memorizzare negli attributi.
Quando poi ti occorre utilizzarlo su Home Assistant per altre request definite con altri sensori o altre tipologie di entità, accedi all'attributo con i template.

Di seguito un esempio...

```yaml
command_line:

  - sensor:
  
      name: "tado_auth"
      command: 'python /config/myscripts/tado_auth.py'
      value_template: "{{ value_json.response_code }}"
      scan_interval: 30
      json_attributes:
        - access_token
        - refresh_token
        - expires_at
        - need_auth
        - verification_url
        - response_code
        - response_message

  - sensor:

      name: "Tado Ingresso Offset"
      command: "curl -s 'https://my.tado.com/api/v2/devices/{{ states('input_text.tado_ingresso_id') }}/temperatureOffset' -H 'Authorization: Bearer {{ state_attr('sensor.tado_auth','access_token') }}' "
      value_template: >
        {% if 'celsius' in value_json %}
          {{ value_json.celsius }}
        {% endif %}
 ```

P.S. La gestione dell'auth in uno script python è molto più semplice da gestire. Fare tutto solo con le entità di HA è un delirio e non è detto che si riesca. Poi ho dovuto fare così anche perché ora viene seguito il flusso oauth2 e quindi va applicata della logica. Inoltre, soprattutto se usi Core su docker o HA Supervised, devi stare ovviamente attento ad utilizzare solo moduli python già inclusi nell'immagine di core.
Come vedi, negli attributi sono presenti altri parametri che non solo sono necessari per il giro di ouath2, ma mi occorrono anche su HA per notifiche in caso di problemi o di necessità di riautenticazione.
