### DISCUSSION TITLE
Errore integrazione Spotify dietro reverse Proxy

### DISCUSSION THREAD

**Discussion by labattazza** [indomus/forum#3438] [HUB: Home Assistant]
Buondì a tutti,

chiedo se a qualcuno di voi capita lo stesso problema: sto cercando di configurare l'integrazione Spotify (che in passato funzionava, quando avevo installato Home Assistant Supervised in Docker) ma senza successo.
La mia installazione è Home Assistant come container docker, usando un pratico docker compose.

La mia rete è così organizzata:

FritzBox ==> Raspberry con Caddy@Docker come reverse Proxy e Server DNS con ADGuard ==> MiniPc con HomeAssistant @Docker

In Spotify Developers ho già configurato l'app con ClientID e ClientSecret.

Il problema che riscontro è che quando clicco sul pulsante dell'ingrazione, prima ancora di accedere alla schermata nella quale inserire ClientID e CLient Secret ottengo l'errore "INVALID_CLIENT: Failed to get client".

Non riesco a capire se il problema risiede in una mancata configurazione in Caddy, o se in Home assistant.
La cosa particolare che noto è che nel link che viene generato, c'è anche un riferimento a https://my.home-assistant.io, ma io non ho configurato il serivzio cloud, e nella mia configurazione è presente correttamente come url esterno quello gestito da Caddy.

In rete non trovo proprio altri casi del genere..

Ecco parte dei file di configurazione:

Caddyfile:
```
https://labahouse.it {
  respond "tutto ok"
  file_server
}

(https_header) {

  header {
    Strict-Transport-Security max-age=31536000; includeSubdomains
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}


https://ha.labahouse.it {
    import https_header

    reverse_proxy http://10.0.0.7:8123 {
        header_up Host {host}
        header_up X-Forwarded-Proto {scheme}
        header_up X-Real-IP {remote_host}

        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Host {host}
    }
      @ws: {
        header Connection "Upgrade"
        header Upgrade websocket
      }
    tls xxx.yyy@zzz.it {
        dns cloudflare XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
    }
}
```

e questo il configuration.yaml di HomeAssistant
```
homeassistant:
  external_url: "https://ha.XXXXXXXXX.XX"
  internal_url: "http://10.0.0.7:8123"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.2
  use_x_forwarded_host: true
  cors_allowed_origins:
    - https://ha.XXXXXXXXX.XX
    - https://my.home-assistant.io

```

Any idea!! Grazie!
