### DISCUSSION TITLE
TRIGGER AUTOMAZIONE CONNESSO AL WIFI

### DISCUSSION THREAD

**Discussion by jimborm** [indomus/forum#3443] [HUB: Home Assistant]
Cao ho creato questa automazione per aprire il cancello di casa quando io o i miei familiari si  avvicinano ad esso usando l'integrazione Proximity. 
```
alias: apriti_sesamo_jimbohome_new
description: Apertura autotomatica del cancello quando ci si avvicina al cancello.
triggers:
  - entity_id:
      - sensor.real_jimbo_home_nearest_distance
    below: 2
    id: Avvicinamento
    trigger: numeric_state
conditions:
  - condition: and
    conditions:
      - condition: state
        entity_id: sensor.real_jimbo_home_nearest_direction_of_travel
        state: arrived
actions:
  - data_template:
      entity_id: media_player.jimbo_home
      message: >-
        {{states.sensor.real_jimbo_home_nearest_device.state}} è a meno di 2
        metri da casa ....  Gli apro io!
    action: tts.google_say
  - data:
      title: APRITI SESAMO CASA
      message: "{{states.sensor.real_jimbo_home_nearest_device.state}}"
    action: notify.mobile_app_iphonegia
  - action: script.carraiocasa_a_piedi
    metadata: {}
    data: {}
mode: single
```
Succede a volte che il mio iphone aggiorni la sua posizione anche quando sono in casa e il trigger si aziona aprendo il cancello. 
Vorrei inserire una condizione sul trigger che controlli innanzitutto se il mio iphone è collegato al wifi di casa. 
Sapete aiutarmi a modificarla in tal senso?
