### DISCUSSION TITLE
Trigger Falliti

### DISCUSSION THREAD

**Discussion by Mizius** [indomus/forum#3450] [HUB: Home Assistant]
Buongiorno a tutti, sono nuovo  sto avendo un problema ad un’automazione molto semplice, vorrei disattivare l'allarme alle 7:30 del mattino.
Il problema che sto avendo è che non scatta all'ora che indico, dalle tracce vedo che si avvia anche dopo un'ora dal trigger
```
id: '1747435754650'
alias: Allarme Mattutino Disattiva
description: ''
triggers:
  - trigger: time
    at: '07:30:00'
conditions:
  - condition: state
    entity_id: alarm_control_panel.alarmo
    state: armed_home
actions:
  - action: alarm_control_panel.alarm_disarm
    metadata: {}
    data:
      code: '2377'
    target:
      entity_id: alarm_control_panel.alarmo
mode: single
```
lo screen della traccia di oggi:
![immagine](https://github.com/user-attachments/assets/b18e1399-809b-4740-9396-26eb1c087821)

ho provato anche con il time pattern:
![immagine](https://github.com/user-attachments/assets/77dfb550-d2b3-4467-9765-2799a6b13a42)

non capisco ne il perchè ne dove potrei vedere per capire meglio

**Comment by Scialla** [comment]
`time_pattern` non c'entra proprio nulla...
A parte che si capisce poco perché non hai usato il markdown, e che non hai postato lo screen della cronologia, dal grafico sembrerebbe che sia scattato ma che non abbia continuato perché la condizione non era soddisfatta...

la condizione che hai impostato è ch `alarm_control_panel.alarmo` deve essere impostato come `armed_home`, se non è così impostato non esegue la `action`.

Tu sei SICURO che sia correttamente valorizzato?
Verifica lo stato nel pannello strumenti sviluppatore

**Reply by Mizius** [reply]
Grazie per la risposta.
Il problema è che dovrebbe partire alle 7.30 del mattino, ma invece come oggi, parte sempre in ritardo. La condizione non la trova poiché ho già disattivato l'allarme manualmente.
la cronologia di oggi, si è avviato alle 09:01 invece era programmato per avviarsi alle 7:30:
![immagine](https://github.com/user-attachments/assets/d9d5a79a-57fb-4ec1-992c-eeb2121b6f3f)

su puoi, mi spiegheresti meglio cosa vedere in strumenti sviluppatore?

**Reply by Scialla** [reply]
Guarda lo stato di `sensor.time` che deve corrispondere all'ora attuale; se non corrisponde hai un problema con l'orologio di sistema del tuo miniPC. 
Prima mi riferivo invece allo stato dell'allarme perché, era evidente, che dall'automazione usciva perché la condizione non era soddisfatta (lo hai disattivato tu a mano)

Indaga quindi sull'ora di sistema

**Reply by Mizius** [reply]
Non sono risucito a trovare lo stato di `sensor.time`, ho controllato l'orario del mini pc ed è corretto
 ma la cosa strana è che si avvia ad orari sempre diversi:
![immagine](https://github.com/user-attachments/assets/a5739294-1a38-43f6-8a04-0d78f7810e61)

**Reply by Scialla** [reply]
questa cosa è impossibile, a meno che non sia tu ad avviare manualmente l'automazione

**Reply by Mizius** [reply]
assolutamente no, oggi è scattato alle 7:34 e stavo ancora a letto
![immagine](https://github.com/user-attachments/assets/4eb52953-f4be-445b-b0ac-2e95b30428af)
```
id: '1747435754650'
alias: Allarme Mattutino Disattiva
description: ''
triggers:
  - trigger: time
    at: '07:30:00'
conditions:
  - condition: state
    entity_id: alarm_control_panel.alarmo
    state: armed_home
actions:
  - action: alarm_control_panel.alarm_disarm
    metadata: {}
    data:
      code: '2377'
    target:
      entity_id: alarm_control_panel.alarmo
mode: single
```

**Reply by Scialla** [reply]
![Screenshot 2025-06-04 alle 17 46 30](https://github.com/user-attachments/assets/a658d87a-5b1b-4499-a95c-56f5715ef19b)
Se lo stato di sensor.time è corretto, suggerisco di mettere a debug le automazioni e guardare i log per capire come mai scatta ad un'ora sbagliata
```
    logger:
      default: debug
      logs:
        homeassistant.components.automation: debug
```
devi cercare di capire tu, da remoto rimane difficile aiutarti
