### DISCUSSION TITLE
Controllo più capillare dell'irrigazione con HASS

### DISCUSSION THREAD

**Discussion by Alfystar** [indomus/forum#3470] [HUB: Home Assistant]
Ciao a tutti!

Con riferimento a questa valvola per irrigazione:

https://indomus.it/componenti/itead-sonoff-zigbee-smart-water-valve/?ht-comment-id=26205675

Volevo chiedere/discutete/pensare una soluzione o workaround che permetta di sfruttare da homeassistant le impostazioni cyclic sia di tempo che di quantità d'acqua.

I principali vantaggi che vedo nello sfruttare questa feature onboard, rispetto a realizzare una equivalente con script e integratori, sono:
- Controllo preciso della funzionalità, evitando down della connessione 
- Garanzia di non lasciare la valvola aperta all'infinito
- sistema di trigger più semplice

Ora ho pensato, visto che quando arriva un errore nell'invio leggo un json nel messaggio, prendendo lo stesso json e mandandolo con mqtt potremmo sfruttare la feature, ed il json starebbe in uno script di homeassistant da far chiamare con i trigger o altro.

Voi avete già affrontato risolto questo problema?

**Comment by indomus** [comment]
Perché non puoi semplicemente regolare questa prevista funzionalità lato z2m e lasciare che operi?

**Reply by Alfystar** [reply]
A me andrebbe **BENISSIMO** fare così, ma su HASS ho solo lo switch di on/off, e il visualizzatore del conto attuale:
<img width="409" alt="image" src="https://github.com/user-attachments/assets/d5e75dda-c3ed-42e0-b265-4d0164a36f2b" />

E non potendolo mandare in automatico, devo andare ogni volta su z2m per attivarlo io. 😕😕
Capisci bene che facendo così crollerebbe tutto il valore aggiunto di avere uno strumento così potente.

In compenso questa mattina, con calma, mi sono messo a fare prove e ho letto con maggiore attenzione anche **la documentazione riportata su z2m**:
https://www.zigbee2mqtt.io/devices/SWV.html#sonoff-swv

E grazie al mio debugger mqtt: https://github.com/terdia/mqttui  (ho così creato un "front end" per mosquitto 😁)

Ho potuto fare qualche prova, arrivando a capire quale _topic MQTT_ e quale _messaggio_ usare per controllare la valvola nella modalità di mio interesse!

### MQTT messaggio controllo quantitativo:
Topic:
```json
zigbee2mqtt/FRIENDLY_NAME/set
```

Payload:
```json
{
  "cyclic_quantitative_irrigation":{
    "current_count":"VALUE",
    "total_number":"VALUE",
    "irrigation_capacity":"VALUE",
    "irrigation_interval":"VALUE"
  }
}
```

Mettendo il `current_count ` a 0, per ovvi motivi.


Arrivato a questo punto mi sento ringuorato e sto iniziando a capire come trasformare questa informazione in uno script su HASS.
Sarebbe bello farlo con i field o le variabili, così da averlo parametrico, qualche suggerimento?
Soprattutto, vi torna come soluzione o sto facendo overthinking?

**Reply by indomus** [reply]
perdonami, io non sto letteralmente capendo la mimica di cosa vuoi fare. ti è chiaro che se regoli un'erogazione di tot litri, se accendi l'irrigazione poi si ferma da sé dopo i tot litri impostati?

**Reply by Alfystar** [reply]
Ok, forse mi sono spiegato poco bene, scusa, riparto da 0 😁

### Ambiente
Ho 2 Giardini abbastanza grandi, ed è mia intenzione irrigare il prato al centro, e le siepi sul perimetro in maniera opportuna.
Per raggiungere questo scopo ho messo in entrambi i giardini:
- Un Ala Gocciolante lungo tutto il perimetro per annaffiare le siepi
- Degli irrigatori, opportunamente posizionati per irrigare il prato.

Per un totale di 4 Valvole, oltretutto per ottimizzare anche la pressione, punto ad aprire gli irrigatori un gruppo alla volta, così da bagnare bene e fino in fondo.

### Obiettivo
Il mio obiettivo è dare al giorno circa **5L/mq** di acqua (così ho letto su internet essere la quantità mediamente ottimale) e visto che le valvole che ho comprato supportano la feature di erogare un tot di acqua in maniera controllata, voglio sfruttarla!


### Problema
Su HASS, dopo aver fatto il paring con Z2M delle valvole ho avuto accesso ai dati su batteria, stato, flusso, etc... ma ho solo lo switch dello stato "On/Off" della valvola.
Se con i trigger usassi questo On/Off di HASS, avrei in linea di principio questi problemi:
1. in primis perderei la funzionalità di controllare la quantità di acqua che finisce in giardino
2. in oltre mi esporrei al rischio che il segnale di Off della valvola per qualche motivo si perde e la valvola resta aperta (questo perchè il protocollo ZigBee non dà garanzie stile TCP, dovrei mettermi io a fare polling per vedere se è andato Off)
3. In fine, se per qualche motivo si dovesse riavviare HASS durante l'attesa, non c'è polling che tenga, la valvola resterebbe aperta a tutta pressione.

Viceversa, usando la funzionalità di cyclic_quantitive/timing, avrei la garanzia che se parte, prima o poi si ferma!
Non irrigare una volta per un problema di HASS è molto più accettabile rispetto a lasciare la valvola aperta a tempo indefinito.


### Prima soluzione
Come dicevo sopra, sono intanto riuscito a usare la funzionalità di mio interesse non da Z2M, ma da un topic MQTT, quindi un passo nella direzione corretta.
Ora devo capire come mandare lo stesso messaggio direttamente da HASS, e anche meglio, capire come parametrizzarlo su uno scritp.


### Problema secondario, scheduling offline
Nelll'ottica di sopravvivere ad un problema al mini-pc con HASS, il brocker mqtt, etc...
Esiste per questa valvola la possibilità di programmare uno scheduling fisso direttamente in locale? Così da programmarla una volta e "campare sereno" 😁
Se servisse potrei anche metterci dentro Tasmota, l'ho già fatto su molti altri dispositivi, per ora queste sono con il firmware originale, aggiornato alla 1.0.4 per avere la chiusura automatica in caso di mancanza d'aqua per più di 30min



Spero di essere stato abbastanza chiaro e di avere il vostro supporto 😁

**Reply by indomus** [reply]
```
Obiettivo
Il mio obiettivo è dare al giorno circa 5L/mq di acqua (così ho letto su internet essere la quantità mediamente ottimale) e visto che le valvole che ho comprato supportano la feature di erogare un tot di acqua in maniera controllata, voglio sfruttarla!

Problema
Su HASS, dopo aver fatto il paring con Z2M delle valvole ho avuto accesso ai dati su batteria, stato, flusso, etc... ma ho solo lo switch dello stato "On/Off" della valvola.
Se con i trigger usassi questo On/Off di HASS, avrei in linea di principio questi problemi:

in primis perderei la funzionalità di controllare la quantità di acqua che finisce in giardino
in oltre mi esporrei al rischio che il segnale di Off della valvola per qualche motivo si perde e la valvola resta aperta (questo perchè il protocollo ZigBee non dà garanzie stile TCP, dovrei mettermi io a fare polling per vedere se è andato Off)
In fine, se per qualche motivo si dovesse riavviare HASS durante l'attesa, non c'è polling che tenga, la valvola resterebbe aperta a tutta pressione.
```

ma perché?
se tu regoli 5 litri (per dire), regoli 5 litri come quantità massimale da erogare e usi semplicemente l'attivazione ON della valvola lato home assistant. a OFF ci torna da solo, NON lo devi dare tu.
pure che cada Home Assistant, a OFF ci torna da solo, la programmazione risiede sul dispostivo.

devi solo regolare la quantità e dare ON quando ti serve.

**Reply by Alfystar** [reply]
Perdonami, ma quanto dici non corrisponde a quanto ho sperimentato, purtroppo.

Dopo aver messo i parametri su z2m, e fatto "Applica" l'irrigazione parte come ci siamo detti, procede e poi termina.
Se dopo da HASS semplicemente faccio On sullo switch dell'irrigatore, lui apre i rubinetti e inizia a irrigare senza più fermarsi.

Sto forse sbagliando io qualcosa?
Ho appena rifatto la prova che ti ho descritto sopra, e lui va senza più fermarsi.

Il mio obiettivo è proprio dare la quantità, l'On, e non fare più nulla, mentre attualmente, usando quel segnale di switch, posso dare l'on quando voglio,  e DEVO dare l'OFF dopo un certo tempo, senza avere controllo diretto sulla quantità

**Reply by KC-inDomus** [reply]
> Sto forse sbagliando io qualcosa? Ho appena rifatto la prova che ti ho descritto sopra, e lui va senza più fermarsi.

boh, prova ad aggiornare il firmware, a me funziona precisamente così: imposti il volume, dai on e si ferma quando lo raggiunge. com'è inteso a funzionarsi, per l'appunto

**Reply by Alfystar** [reply]
Ti posso chiedere @KC-inDomus di mandarmi qualche screen? per avere un confronto visivo e capire cosa sbaglio

**Reply by KC-inDomus** [reply]
appena ho un attimo, ma non c'è molto da illustrare: è impostato su z2m e poi faccio andare in on lo switch

**Reply by Alfystar** [reply]
Fai forse applica? O metti semplicemente i numeri e chiudi la pagina?

**Reply by KC-inDomus** [reply]
<img width="855" alt="Screenshot 2025-07-01 at 02 20 27" src="https://github.com/user-attachments/assets/023e4291-d293-4605-a65a-2c39431f37da" />

imposti e poi cicchi applica. tutto qui

**Reply by Alfystar** [reply]
Appena lo faccio parte, e funziona come impostato, ma se poi riprovo da HASS facendo on, si accende fisso 😫

Sicuro che non hai modificato nulla nelle altre schede?

**Reply by KC-inDomus** [reply]
nella maniera più assoluta no

**Comment by Alfystar** [comment]
Ho appena rifatto la prova, ho configurato così l'irrigatore:

<img width="857" alt="image" src="https://github.com/user-attachments/assets/d1c3a546-ae8d-4c2c-b2ed-fe5345de38f2" />


quindi ho fatto applica e ho potuto vedere in meno di 1 minuto finire il giro, con le 2 ripetizioni.

quindi, senza toccare assolutamente niente altro, sono andato su HASS e ho attivato lo stesso irrigatore dallo switch:
<img width="636" alt="image" src="https://github.com/user-attachments/assets/f301ccd5-1f1f-4f2b-b228-766d3bb5466d" />

(ci sono 2 valvole perchè uno è l'interruttore e l'altra la valvola virtuale)

Ho atteso ed è rimasto attivo senza mai interrompersi per 3 min

Tu @KC-inDomus vedi le stesse cose sul tuo dispositivo in HASS? E a questo punto hai idea a chi potrei chiedere o continuo con la mia idea di mandare il messaggio MQTT?

**Reply by KC-inDomus** [reply]
non so che dirti, anche io sono configurato così. però a me funziona

**Reply by Alfystar** [reply]
Capisco, amen, io ho creato un script che permette di attivare la modalità quantitativa con pieno controllo da HASS, e funziona, ecco qui lo script:

<img width="560" alt="image" src="https://github.com/user-attachments/assets/277f264f-b4e3-4dca-b23f-d785a9059005" />

```yaml
sequence:
  - action: mqtt.publish
    metadata: {}
    data:
      qos: "1"
      topic: zigbee2mqtt/{{mqtt_device_name}}/set
      payload: |-
        {% set h, m, s = intervallo_cicli.split(':') | map('int', 0) | list %}
        {
          "cyclic_quantitative_irrigation":{
            "current_count":"0",
            "total_number":"{{cicli_consegutivi}}",
            "irrigation_capacity":"{{litri_acqua}}",
            "irrigation_interval":"{{ timedelta(hours=h, minutes=m, seconds=s).total_seconds() }}"
          }
        }
mode: parallel
max: 10
fields:
  mqtt_device_name:
    selector:
      text: {}
    name: MQTT Device name
    description: Friendly name della valvola idraulica
    required: true
  litri_acqua:
    selector:
      number:
        min: 1
        max: 200
    name: Litri acqua
    description: Numero di litri di acqua da emettere per ciclo
    default: 25
  cicli_consegutivi:
    selector:
      number:
        min: 1
        max: 4
    name: Cicli consegutivi
    description: >-
      Numero di ripetizioni del ciclo consegutivi, con la stessa quantità ogni
      volta
    default: 2
    required: false
  intervallo_cicli:
    selector:
      time: {}
    name: Intervallo cicli
    description: Numero di Secondi di intervallo tra un ciclo e l'altro
    default: "00:05:00"
    required: true
alias: Irrigazione a Litri
description: Richiedi ciclo di irrigazione quantitativo
icon: mdi:water-pump
```

In compenso puoi controllarlo come vuoi, basta che metti il nome del dispositivo che hai dato attraverso Z2M, e puoi personalizzare "on the fly" il comportamento.
Si può eseguire in parallelo lo script così da applicarlo, potenzialmente, a ogni valvola in contemporanea, poi io suggerisco di attendere e farne una alla volta, per motivi di pressione.

Per altri che dovessero avere il mio stesso problema 😁

@KC-inDomus che tu sappia, si può prendere il nome dal dispositivo, limitando la ricerca tra quelli dell'integrazione MQTT con un menù a tendina?

**Reply by KC-inDomus** [reply]
non ho capito la domanda

**Reply by Alfystar** [reply]
Se metto nel field il tipo "device" non voglio che mi mostri tutti i possibili device, ma solo quelli che rispettano certe regole, in particolare i filtri per questa valvola, ma ci sono riuscito 😆

Ora sotto posto la soluzione completa, sperando che ad altri possa essere utile

**Comment by Alfystar** [comment]
<h2 id="irrigazionealitriautomazionepervalvolezigbeesonoff">💧 Irrigazione a Litri – Automazione per Valvole Zigbee Sonoff</h2>
<h3 id="descrizione">📋 Descrizione</h3>
<p>Questo script per Home Assistant consente di avviare un ciclo di irrigazione <strong>quantitativo/temporale e ciclico</strong> su una valvola Sonoff Zigbee integrata via MQTT. L’utente può specificare:</p>
<ul>
<li><strong>Litri d’acqua per ciclo</strong></li>
<li><strong>Numero di cicli consecutivi</strong></li>
<li><strong>Intervallo di tempo tra i cicli</strong></li>
</ul>
<p>Lo script invia i parametri via MQTT alla valvola, attende il completamento dei cicli e verifica che il flusso sia terminato e la valvola sia chiusa prima di concludere.</p>
<hr>
<h3 id="funzionalitprincipali">⚙️ Funzionalità principali</h3>
<ul>
<li>✅ <strong>Controllo preciso</strong> della quantità d’acqua per ciclo</li>
<li>🔁 <strong>Gestione automatica di cicli multipli</strong> con intervallo configurabile</li>
<li>⏳ <strong>Attesa intelligente</strong> del completamento reale dell’irrigazione</li>
<li>📡 <strong>Comunicazione MQTT</strong> con payload dinamico</li>
<li>🧠 <strong>Parsing avanzato</strong> dello stato MQTT per evitare falsi positivi</li>
<li>🧩 <strong>Compatibile con più dispositivi</strong> grazie all’uso di <code>device_attr</code></li>
<li>🔍 <strong>Filtro automatico dei dispositivi</strong>: mostra solo le valvole Sonoff Zigbee compatibili</li>
<li>🧵 <strong>Esecuzione parallela</strong>: lo script può essere eseguito contemporaneamente su più dispositivi</li>
<li>🔄 <strong>Sovrascrittura intelligente</strong>: se lo script viene richiamato più volte sullo stesso dispositivo, il comando MQTT viene aggiornato, ma le attese già in corso continuano a funzionare correttamente, poiché dipendono dallo stato reale del sistema e non da variabili interne</li>
</ul>

## Interfaccia Quantitativa
<img width="558" alt="image" src="https://github.com/user-attachments/assets/d590e40c-037b-4b34-94cb-7d113dd2f59c" />

## Interfaccia Temporale
<img width="558" alt="image" src="https://github.com/user-attachments/assets/2934ac69-7774-4706-ac20-d85e44da222a" />

<hr>
<h3 id="passaggichiave">🔑 Passaggi chiave</h3>
<ol>
<li><p><strong>Invio comando MQTT</strong><br>
Lo script pubblica un payload JSON sul topic MQTT della valvola, specificando:</p>
<ul>
<li><code>current_count</code>: 0 (inizio)</li>
<li><code>total_number</code>: numero di cicli</li>
<li><code>irrigation_capacity</code>: litri per ciclo</li>
<li><code>irrigation_interval</code>: intervallo tra i cicli in secondi</li></ul></li>
<li><p><strong>Attesa del completamento dei cicli</strong><br>
Il primo <code>wait_template</code> monitora il sensore MQTT e attende che <code>current_count == total_number</code>.</p></li>
<li><p><strong>Attesa della chiusura effettiva</strong><br>
Dopo un breve <code>delay</code>, un secondo <code>wait_template</code> verifica che:</p>
<ul>
<li>Il flusso (<code>flow</code>) sia pari a 0</li>
<li>La valvola (<code>switch</code>) sia spenta (<code>off</code>)</li></ul></li>
<li><p><strong>Timeout di sicurezza</strong><br>
Entrambe le attese hanno un timeout configurato per evitare blocchi infiniti.</p></li>
</ol>
<hr>
<h3 id="parametriconfigurabili">🧩 Parametri configurabili</h3>

Campo | Descrizione | Default
-- | -- | --
mqtt_device | Dispositivo MQTT (valvola Sonoff) | —
litri_acqua | Litri d’acqua per ciclo | 1
cicli_consegutivi | Numero di cicli consecutivi | 2
intervallo_cicli | Tempo tra un ciclo e l’altro (formato HH:MM:SS) | 00:00:10


<hr>
<h3 id="requisiti">🧠 Requisiti</h3>
<ul>
<li>Valvola Sonoff compatibile con Zigbee2MQTT</li>
<li>Sensori MQTT per:<ul>
<li>Stato ciclico (<code>_cyclic_quantitative_irrigation</code>)</li>
<li>Flusso (<code>_flow</code>)</li>
<li>Switch (<code>_switch</code>)</li></ul></li>
<li>Home Assistant con supporto a <code>device_attr</code>, <code>slugify</code>, e <code>from_json</code></li>
</ul>
<hr>

<h3 id="script_quantitativo">🧠 Script quantitativo</h3>

Ecco lo script che realizza quanto descritto, ora basterà richiamarlo da un automazione o direttamente da un pulsante 😁
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/6a1f2f2f-28e3-48f9-8f7e-d84bf2ca3204" />


```yaml

sequence:
  - action: mqtt.publish
    metadata: {}
    data:
      qos: "1"
      topic: zigbee2mqtt/{{ device_attr(mqtt_device, 'name') }}/set
      payload: |-
        {% set h, m, s = intervallo_cicli.split(':') | map('int', 0) | list %}
        {
          "cyclic_quantitative_irrigation":{
            "current_count":"0",
            "total_number":"{{cicli_consegutivi}}",
            "irrigation_capacity":"{{litri_acqua}}",
            "irrigation_interval":"{{ timedelta(hours=h, minutes=m, seconds=s).total_seconds() }}"
          }
        }
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - wait_template: >
      {# 1️⃣ Attende che il conteggio dei cicli sia completato #}


      {# Costruiscono dinamicamente i nomi delle entità Home Assistant #}

      {% set base = device_attr(mqtt_device, 'name') | slugify %}

      {% set sensor_name = 'sensor.' ~ base ~ '_cyclic_quantitative_irrigation'
      %}


      {# Parsing dello stato del sensore MQTT come JSON valido #}

      {% set raw = states(sensor_name) | replace("'", '"') %}

      {% set irrigation_dict = raw | from_json %}


      {# Estrazione dei valori #}

      {% set current = irrigation_dict.current_count | default(0, true) | int %}

      {% set total = irrigation_dict.total_number | default(1, true) | int %}


      {# Condizione finale: tutti i cicli completati #}

      {{ current == total }}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - wait_template: |
      {# 2️⃣ Attende che il flusso sia 0 e la valvola spenta #}
      {# Costruiscono dinamicamente i nomi delle entità Home Assistant #}
      {% set base = device_attr(mqtt_device, 'name') | slugify %}
      {% set flow_sensor = 'sensor.' ~ base ~ '_flow' %}
      {% set switch_sensor = 'switch.' ~ base %}

      {# Estrazione dei valori #}
      {% set flow = states(flow_sensor) | default(0, true) | float %}
      {% set switch_state = states(switch_sensor) | default('off', true) %}

      {# Condizione finale: flusso a 0 e valvola spenta #}
      {{ flow == 0 and switch_state == 'off' }}
mode: parallel
max: 10
fields:
  mqtt_device:
    name: Valvola Zigbee Sonoff
    description: Seleziona una valvola Sonoff SWV integrata via MQTT
    required: true
    selector:
      device:
        integration: mqtt
        model: Zigbee smart water valve
  litri_acqua:
    selector:
      number:
        min: 1
        max: 200
    name: Litri acqua
    description: Numero di litri di acqua da emettere per ciclo
    default: 1
  cicli_consegutivi:
    selector:
      number:
        min: 1
        max: 4
    name: Cicli consegutivi
    description: >-
      Numero di ripetizioni del ciclo consegutivi, con la stessa quantità ogni
      volta
    default: 2
    required: false
  intervallo_cicli:
    selector:
      time: {}
    name: Intervallo cicli
    description: Numero di Secondi di intervallo tra un ciclo e l'altro
    default: "00:00:10"
    required: true
alias: Irrigazione a Litri
description: Richiedi ciclo di irrigazione quantitativo
icon: mdi:water-pump

```

<hr>
<h3 id="script_temporale">🧠 Script temporale</h3>

Ed ecco lo script gemello, che realizza le stesse cose, ma su base temporale, anche questo basterà richiamarlo da un automazione o direttamente da un pulsante 😁

```yaml
sequence:
  - action: mqtt.publish
    metadata: {}
    data:
      qos: "1"
      topic: zigbee2mqtt/{{ device_attr(mqtt_device, 'name') }}/set
      payload: >-
        {% set h_ap, m_ap, s_ap = tempo_apertura.split(':') | map('int', 0) | list %}

        {% set h, m, s = intervallo_cicli.split(':') | map('int', 0) | list %}

        {
          "cyclic_timed_irrigation":{
            "current_count":"0",
            "total_number":"{{cicli_consegutivi}}",
            "irrigation_duration":"{{ timedelta(hours=h_ap, minutes=m_ap, seconds=s_ap).total_seconds() }}",
            "irrigation_interval":"{{ timedelta(hours=h, minutes=m, seconds=s).total_seconds() }}"
          }
        }
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - wait_template: |
      {# 1️⃣ Attende che il conteggio dei cicli sia completato #}

      {# Costruiscono dinamicamente i nomi delle entità Home Assistant #}
      {% set base = device_attr(mqtt_device, 'name') | slugify %}
      {% set sensor_name = 'sensor.' ~ base ~ '_cyclic_timed_irrigation' %}

      {# Parsing dello stato del sensore MQTT come JSON valido #}
      {% set raw = states(sensor_name) | replace("'", '"') %}
      {% set irrigation_dict = raw | from_json %}

      {# Estrazione dei valori #}
      {% set current = irrigation_dict.current_count | default(0, true) | int %}
      {% set total = irrigation_dict.total_number | default(1, true) | int %}

      {# Condizione finale: tutti i cicli completati #}
      {{ current == total }}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - wait_template: |
      {# 2️⃣ Attende che il flusso sia 0 e la valvola spenta #}
      {# Costruiscono dinamicamente i nomi delle entità Home Assistant #}
      {% set base = device_attr(mqtt_device, 'name') | slugify %}
      {% set flow_sensor = 'sensor.' ~ base ~ '_flow' %}
      {% set switch_sensor = 'switch.' ~ base %}

      {# Estrazione dei valori #}
      {% set flow = states(flow_sensor) | default(0, true) | float %}
      {% set switch_state = states(switch_sensor) | default('off', true) %}

      {# Condizione finale: flusso a 0 e valvola spenta #}
      {{ flow == 0 and switch_state == 'off' }}
mode: parallel
max: 10
fields:
  mqtt_device:
    name: Valvola Zigbee Sonoff
    description: Seleziona una valvola Sonoff SWV integrata via MQTT
    required: true
    selector:
      device:
        integration: mqtt
        model: Zigbee smart water valve
  tempo_apertura:
    selector:
      time: {}
    name: Tempo apertura
    description: Tempo in cui la valvola resta aperta per ciclo
    required: true
    default: "00:01:00"
  cicli_consegutivi:
    selector:
      number:
        min: 1
        max: 4
    name: Cicli consegutivi
    description: >-
      Numero di ripetizioni del ciclo consegutivi, con la stessa quantità ogni
      volta
    default: 1
    required: true
  intervallo_cicli:
    selector:
      time: {}
    name: Intervallo cicli
    description: Numero di Secondi di intervallo tra un ciclo e l'altro
    default: "00:05:00"
    required: true
alias: Irrigazione a Tempo
description: Richiedi ciclo di irrigazione temporale
icon: mdi:water-pump

```


Link utili:
- https://indomus.it/componenti/itead-sonoff-zigbee-smart-water-valve/
- https://indomus.it/formazione/mqtt-cose-e-come-funziona-il-qos-quality-of-service/
