### DISCUSSION TITLE
il PC non si spegne

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#359] [HUB: Home Assistant]
Questo il codice in configuration.yaml
```
# Wakeonlan
switch wol:
  - platform: wake_on_lan
    mac: "48:25:AS:47:9F:36"
    name: "MIOPC"
    host: "192.168.1.10"
    turn_off:
      service: shell_command.turn_off_pc

shell_command:
  turn_off_pc: net rpc shutdown -f -C 'Computer in spegnimento da Alexa' -I 192.168.1.10 -U Aldo Castellani%lamiapassword
```
Lo switch naturalmente è condiviso su Alexa: con "Alexa accendi MIOPC" riesco ad accendere il PC, ma con "Alexa, spegni MIOPC" non si spegne. 
E' corretto l'uso di **net rpc** col computer collegato alla stessa rete di hassio?
Oppure il problema può essere dovuto allo spazio tra nome e cognome dell'USER?

**Comment by snakuzzo** [comment]
Premesso che io non uso Hassio...

Di sicuro la username scritta così non va bene...perché quello è il FULL NAME, non la username. Guarda...

![image](https://user-images.githubusercontent.com/7205371/119798169-2c94da00-bedb-11eb-8317-64ca6631429a.png)

Poi, per quanto riguarda la sintassi...è questa: 

`net rpc shutdown -I ip.address -U user%password`

Quindi è corretta, ma la domanda è...sei sicuro di avere quel comando disponibile di default su hassio (a me non sembra proprio) ? Hai usato un addon ? (nel caso ho trovato [QUESTO](https://github.com/home-assistant/addons/tree/master/rpc_shutdown)).

Ad ogni modo per provare l'intero comando ti basta andare in SSH sul container di Core e lanciarlo. Voi su Hassio dovreste avere l'addon SSH Terminal (o una cosa simile)

**Reply by Dregi56** [reply]
Ok. L'addon suggerito funziona e da Alexa ora tutto OK. Grazie.
Problemino invece con automazione:
```
- id: 'veramentenessunproblema'
  alias: PC Corsair
  description: Spegne il computer se è in rete alle ore 2
  trigger:
  - platform: time
    at: '02:00:00'
  condition:
  - condition: state
    entity_id: binary_sensor.computer_corsair
    state: 'on'
  action:
  - service: hassio.addon_stdin
    data: 
      addon: core_rpc_shutdown
      input: Corsair
  mode: single
```
Dov'è il problema?

**Reply by snakuzzo** [reply]
l'automazione a livello di sintassi mi sembra ok.
Non so che servizio sia `hassio.addon_stdin` ... visto che non uso hassio.
Accendi il PC, prova ad eseguire a mano l'automazione e vedi cosa viene loggato su HA

**Reply by Dregi56** [reply]
**hassio.addon_stdin**  è l'addon che mi hai suggerito.    :)
Logviewer rimane a schermo nero, nulla.

**Reply by snakuzzo** [reply]
non saprei...metti a debug i log con [logger](https://www.home-assistant.io/integrations/logger/)

**Reply by Dregi56** [reply]
Allora, rivediamo un attimo la cosa, ora con l'addon funzionante via Alexa, in configuration.yaml ho:
```
# Wakeonlan
switch wol:
  - platform: wake_on_lan
    mac: "48:25:AS:47:9F:36"
    name: "MIOPC"
    host: "192.168.1.10"
    turn_off:
      service: hassio.addon_stdin
      data:
        addon: core_rpc_shutdown
        input: MIOPC
```
La domanda allora diventa: Come eseguo quel **turn_off** in una action di un'automazione?
