### DISCUSSION TITLE
iBBQ @ ESPhome

### DISCUSSION THREAD

**Discussion by gabrio79** [indomus/forum#365] [HUB: Home Assistant]
Ciao,
seguendo questo post 
[https://github.com/esphome/feature-requests/issues/397](url)

ho creato il mio codice per 

```
esphome:
  name: ibbq-gateway
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  ap:
    ssid: !secret esphome_ap_ssid_ibbq-gateway
    password: !secret esphome_ap_password

captive_portal:

logger:

api:
  password: !secret esphome_api_password
ota:
  password: !secret esphome_ota_password
sensor:
  - platform: template
    name: "iBBQ Temperature Probe 1"
    expire_after: 60s
    id: ble_sensor_1
    unit_of_measurement: "°C"
    accuracy_decimals: 1

```

continua come da link

in compilazione mi da un errore che non capisco come risolvere...

```
sensor.template: [source /config/esphome/iBBQ-Gateway.yaml:28]
  platform: template
  name: iBBQ Temperature Probe 1
  
  This option requires component mqtt.
  expire_after: 60s [source /config/esphome/iBBQ-Gateway.yaml:30]
  id: ble_sensor_1
  unit_of_measurement: °C
  accuracy_decimals: 1
```

sapete darmi una dritta?

> expire_after: 60s ti dice che richiede mqtt ... ma lo stai usando in template ...
