### DISCUSSION TITLE
agire su una zona

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#37] [HUB: Home Assistant]
Per non essere anch'io tacciato di aspettare la _pappa pronta_ , metto le mani avanti: dove posso trovare indicazioni sulla sintassi da tenere nei file yaml, come vengono decise le piattaforme, le chiamate  ad una servizio piuttosto che una altro, i vari tag ?
Ora invece la domanda, col codice che segue in una automazione, chiudo la tapparella studio al tramonto. Se volessi chiudere tutta la zona notte e la zona giorno, cosa dovrei scrivere?
```
 alias: Sera
  description: Chiude tapparelle al tramonto
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: cover.close_cover
    data: {}
    entity_id: cover.studio
  mode: single
```

**Comment by snakuzzo** [comment]
1. Per quanto riguarda Home Assistant nello specifico, ti basta leggere le nostre guide e/o guardare la documentazione sul sito ufficiale di home assistant. Non si apprende leggendo 5 minuti, ma applicando e facendo pratica. Per quanto riguarda la comprensione "in generale" di YAML, la risposta è ad esempio "Google"

2. Quanto alla tua automazione, puoi trovare la risposta [QUI](https://www.home-assistant.io/docs/scripts/service-calls/#targeting-areas-and-devices)

**Reply by Dregi56** [reply]
Grazie snakuzzo, beh... non voglio la pappa pronta, ma nemmeno rinuncio al minimo suggerimento in termini di righe di codice...  :)
Ho risolto così e funziona:
```
- id: '1616694978240'
  alias: Sera
  description: Chiude tapparelle al tramonto
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - delay:
      minutes: 20
  - service: cover.close_cover
    data: {}
    entity_id: group.sera
  mode: single

```
Ho notato che quando l'automazione presenta in' _id_ come in questo caso, è anche possibile editarla visuale, mentre quando manca quell' _id_  è oscurata l'icona per l'edit visuale. L' ID viene dato dal "visual editor" per cui presumo, che non è che uno se lo possa inventare e scrivere....
