### DISCUSSION TITLE
Sensori porte e finestre TUYA

### DISCUSSION THREAD

**Discussion by Vinz1985** [indomus/forum#370] [HUB: Home Assistant]
Buongiorno ragazzi, qualcuno di voi è riuscito a risolvere l'integrabilità tra i sensori porte e finestre con Tuya o Tuya Local? Di default non vengono riconosciuti, ho provato la soluzione del ping e almeno vengono riconosciute le entità però funziona male, nel senso che:
- le entità vengono riconosciute ma gli stati funzionano un po a caxxo, ovvero se apro la finestra il sensore cambia stato (e fin qui OK) ma lo mantiene per pochi secondi (indipendentemente se la richiudi o la lasci aperta la finestra o porta) e quindi non è utile in questo modo. 

Non capisco perchè  Tuya ha questa problematica rispetto ad es. ai Sonoff DW2 o agli Shelly Door che vengono automaticamente riconosciuti come sensori binari. Tuttavia ho proceduto all'acquisto di nuovi sensori porte e finestre (gli Aquara) che abbinerò ad un ConbeeII dove ho già quelli per temperatura ma per soddisfazione personale vorrei riuscire a integrare questi qui in mio possesso (e se mai dovessi riuscirci li re-impiegherei per le porte interne, attualmente li ho solo sulle finestre e porta d ingresso).
Vi allego il codice utilizzato (preso da github) e riadattato:
```
input_number:
  motion_sensor_idle_secs:
    name: Motion Sensor Idle Seconds
    initial:  600
    min: 60
    max: 3600
    step: 1
```

+ 
```
binary_sensor:  
  - platform: ping
    host: 192.168.178.173
    count: 1
    scan_interval: 1
    name: ping_tuya_motion_sensor_finestra_soggiorno
  
  - platform: template
    sensors:
      tuya_motion_sensor_finestra_soggiorno:
        friendly_name: "Finestra Soggiorno, Sensor Alarm"
        value_template: >-
          {{ as_timestamp(states.sensor.date_time.last_changed) - as_timestamp(states.binary_sensor.ping_tuya_motion_sensor_finestra_soggiorno.last_changed) < states('input_number.motion_sensor_idle_secs')|int }}

```
