### DISCUSSION TITLE
climatizzatori Hisense

### DISCUSSION THREAD

**Discussion by genus-giuseppe** [indomus/forum#377] [HUB: Home Assistant]
ho integrato i climatizzatori Hisense
vorrei sapere se è possibile tramite mqtt leggere solo il sensore temperatura in allegato il playload

```
name: Bagno rosa
unique_id: XXXXXXXXXX
device:
  identifiers:
    - hisense_ac_XXXXXXXXXX
  manufacturer: Hisense (oem-eu)
  model: Smart-1-110
  name: Bagno rosa
  sw_version: 'bc 2.5.3-beta 12/28/16 15:58:28 ID XXXXX'
availability:
  - topic: hisense_ac/LWT
  - topic: hisense_ac/XXXXXXXXXX/available/status
precision: 1
temperature_unit: F
current_temperature_topic: hisense_ac/XXXXXXXXXX/f_temp_in/status
fan_mode_command_topic: hisense_ac/XXXXXXXXXX/t_fan_speed/command
fan_mode_state_topic: hisense_ac/XXXXXXXXXX/t_fan_speed/status
fan_modes:
  - auto
  - lower
  - low
  - medium
  - high
  - higher
mode_command_topic: hisense_ac/XXXXXXXXXX/t_work_mode/command
mode_state_topic: hisense_ac/XXXXXXXXXX/t_work_mode/status
modes:
  - 'off'
  - fan_only
  - heat
  - cool
  - dry
  - auto
power_command_topic: hisense_ac/XXXXXXXXXX/t_power/command
power_state_topic: hisense_ac/XXXXXXXXXX/t_power/status
swing_mode_command_topic: hisense_ac/XXXXXXXXXX/t_fan_power/command
swing_mode_state_topic: hisense_ac/XXXXXXXXXX/t_fan_power/status
swing_modes:
  - 'on'
  - 'off'
temperature_command_topic: hisense_ac/XXXXXXXXXX/t_temp/command
temperature_state_topic: hisense_ac/XXXXXXXXXX/t_temp/status
max_temp: '86'
min_temp: '61'
platform: mqtt

```
