### DISCUSSION TITLE
(RISOLTO) errore servizio notify.alexa_media

### DISCUSSION THREAD

**Discussion by calz64** [indomus/forum#379] [HUB: Altro (Homey, iHost, SmartThings, Fibaro ecc.)]
Buongiorno, ho provato il test della guida https://indomus.it/guide/far-parlare-amazon-alexa-come-sistema-di-notifica-domotica-su-home-assistant/ per inviare notifiche a voce con speaker echo dot 4gen.
```
message: Questo è un messaggio di test
title: Titolo
data:
  type: announce
  method: spoken
target: media_player.alexa
```
Mi da un errore: 
`ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547697890736] Error handling message: required key not provided @ data['message']. Got None`

Alexa è funzionante ed è integrato in HA, qualcuno sa come correggere il problema. Grazie in anticipo

**Comment by snakuzzo** [comment]
Ma tutta quella roba l'hai messa sotto data?

**Comment by calz64** [comment]
Si il codice sotto, leggendo avevo capito che bisognasse fare così, emh forse non ho capito...
```
message: Questo è un messaggio di test
title: Titolo
data:
  type: announce
  method: spoken
target: media_player.alexa
```

**Comment by calz64** [comment]
Ho risolto con questo codice:
```
  action:
  - service: notify.alexa_media_echo_dot_di_...-
    data:
      target:
      - media_player.alexa
      data:
        type: announce
        method: all
```
Innazitutto ho identificato meglio il mio notify.alexa_media.. che è in più ... echo_dot_di_....-
poi ho riscritto la sequenza e nel method si può mettere spoken o all (quest'ultimo oltre a spoken notifica su display), così mi funziona.
