### DISCUSSION TITLE
Controllo codice

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#408] [HUB: Home Assistant]
Il codice dell'automazione più sotto ha sempre funzionato fino all'aggiunta che segue:
```
condition:
  - condition: state
    entity_id: switch.gardenlight
    state: 'off'
```
HA non rileva alcun errore nel codice, nulla sul file di log, eppure per assurdo (?) non ottengo più la chiusura delle tapparelle mentre invece si accendono le luci in giardino, ma non nel tempo stabilito ossia 10 minuti dopo la suddetta chiusura, ma invece 10 minuti dopo il tramonto, come se l'attesa di 20 minuti dopo il tramonto venisse disattesa. L' entity_id: switch.gardenlight è uno switch virtuale perchè diversamente non ho modo di sapere se le luci in giardino sono accese o spente in quanto il device_id: d80c70313310e78150af97e4485e6f71 è di uno shelly 1 che agisce su un telecomando il quale ultimo azione un relay.
Ecco quindi il codice da controllare:
```
- id: e76b044a2e864df38c7262dec386aeda
  alias: Sera
  description: Chiude tapparelle al tramonto
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - service: cover.close_cover
    target:
      entity_id:
      - cover.tapparella_cameretta
      - cover.tapparella_bagnonotte
      - cover.tapparella_matrimoniale
      - cover.tapparella_camera_girasoli
      - cover.tapparella_studio
      - cover.tapparella_soggiorno
      - cover.tapparella_bagnogiorno
      - cover.tapparella_salotto
  - service: script.turn_on
    target:
      entity_id: script.salva_fiori
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  condition:
  - condition: state
    entity_id: switch.gardenlight
    state: 'off'
  action:
  - service: switch.turn_on
    target:
      device_id: d80c70313310e78150af97e4485e6f71
      entity_id: switch.gardenlight
  mode: single
```

**Comment by snakuzzo** [comment]
L'automazione che hai postato è sbagliata.
Da come hai indentato il codice, hai inserito un altro blocco condition ed un altro blocco action alla fine..non va bene.
Forse volevi mettere la condition e la chiamata al service "sotto" la action ?
Spiega per favore

**Reply by Dregi56** [reply]
E' sufficiente cancellare questa?  **condition: []**   ?

**Reply by snakuzzo** [reply]
Se ho capito bene cosa vuoi fare...ecco l'automazione...

```yaml
- id: e76b044a2e864df38c7262dec386aeda
  alias: Sera
  description: Chiude tapparelle al tramonto
  trigger:
  - platform: sun
    event: sunset
  action:
  - delay:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - service: cover.close_cover
    target:
      entity_id:
      - cover.tapparella_cameretta
      - cover.tapparella_bagnonotte
      - cover.tapparella_matrimoniale
      - cover.tapparella_camera_girasoli
      - cover.tapparella_studio
      - cover.tapparella_soggiorno
      - cover.tapparella_bagnogiorno
      - cover.tapparella_salotto
  - service: script.turn_on
    target:
      entity_id: script.salva_fiori
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: switch.turn_on
    target:
      entity_id: switch.gardenlight
  mode: single
```

La condition che hai aggiunto di fatto non serve.
Non ha alcun senso verificare che la luce sia ad off per poi portarla ad on.
Così come ho scritto io... 
- se è off passa ad on
- se è già on rimane ad on

Se poi ho capito male lo scopo di questa tua automazione, fammi capire cosa vuoi fare di preciso.

**Reply by Dregi56** [reply]
Non è proprio così lo switch device_id: d80c70313310e78150af97e4485e6f71 è uno shelly 1 che funziona come pulsante di un telecomando che aziona un relè a distanza. E' chiaro che quando "aziono il telecomando" ottengo on oppure off a seconda dello stato precedente e HA non ha modo di sapere se lo stato è on oppure off. Ho quindi pensato di inserire uno switch.gardenlight da settare ogni volta che viene "azionato il telecomando".  L'inghippo sta nel fatto che qualcuno potrebbe accendere le luci con un telecomando prima dell'esecuzione dell'automazione, in questo caso l'automazione trova le luci accese e le spegne a meno che io non metta, come avevo fatto, uno stato da verificare, quello di switch.gardenlight.
Lo so mi stai per dire, tira un filo e agisci direttamente bypassando il telecomando.... :)  lo farò  :)  ma per il momento dovrei risolvere il problema.

**Reply by snakuzzo** [reply]
Se non puoi sapere lo stato dello switch credo sia sbagliata proprio in partenza...stai ragionando in maniera ottimistica e potresti sfasare in qualsiasi momento lo stato reale con quello presente su HA.

Ad ogni modo, se vuoi la condition prima della action che esegue il turn_on, puoi fare così...

```yaml
- id: e76b044a2e864df38c7262dec386aeda
  alias: Sera
  description: Chiude tapparelle al tramonto
  trigger:
  - platform: sun
    event: sunset
  action:
  - delay:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - service: cover.close_cover
    target:
      entity_id:
      - cover.tapparella_cameretta
      - cover.tapparella_bagnonotte
      - cover.tapparella_matrimoniale
      - cover.tapparella_camera_girasoli
      - cover.tapparella_studio
      - cover.tapparella_soggiorno
      - cover.tapparella_bagnogiorno
      - cover.tapparella_salotto
  - service: script.turn_on
    target:
      entity_id: script.salva_fiori
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - condition: state
    entity_id: switch.gardenlight
    state: 'off'
  - service: switch.turn_on
    target:
      entity_id: switch.gardenlight
  mode: single
```
