### DISCUSSION TITLE
FluxLed - Magic Home

### DISCUSSION THREAD

**Discussion by Jones1982** [indomus/forum#41] [HUB: Home Assistant]
Buondì,
ho 2 controller wifi per strisce led della Magic Home.
Il primo (Striscia), è a 5V, RGB, e il controller è ver 5 (04.v5.20.6759-A)
Il secondo (Barra), è a 12V, RGBW, e il controller è ver 1 (06.v1.11.7376-A)

Entrambi sono attivi sia sul Cloud server che Local Network.

La configurazione in configuration.yaml è la seguente:
```
light:
  - platform: flux_led
    devices:
      192.168.1.115:
        name: Striscia
        mode: "rgb"
  - platform: flux_led
    devices:
      192.168.1.130:
        name: Barra
        mode: "rgbw"
```
Striscia mi funziona bene con la scheda, un pò lento nell'aggiornare lo stato (acceso/spento, colore, ecc) ma funziona.

Barra invece, oltre alla stessa reattività di Striscia, da errore quando provo a impostare la luce fredda dalla sua scheda (in HA),
dando errore: "Fallita chiamata a servizio light/turn_on".

A volte non si accende, e se la spengo dalla scheda (e non da google home o dalla sua app magic home), si blocca il dispositivo.
Devo premere 2-3 volte il simbolo dell'accesione sull'app proprietaria per poterla riusare.

Scavando in giro, avevo letto che si doveva aggiungere nella configurazione, il `protocol: 'ledenet'`, ma non noto differenze.

Escludendo di flasharli con tasmota (che ora non farò...), qualcuno sa notizie in merito a questi dispositivi e a come risolvere?

**Ringrazio in anticipo!!!**

**Comment by Jones1982** [comment]
Un altra cosa:

nelle automations.yaml  ho inserito questo:


```
  - service: light.turn_on
    entity_id: light.striscia
    data:
      effect: red_strobe

```
non riesco a trovare il comando per la velocità dell'effetto (red_strobe).
Ho provato       `     speed_pct: 100`  ma da errore nel log.
Qual è il comando giusto?

**### _GRAZIE!_**

**Reply by snakuzzo** [reply]
Sull'effetto onestamente non so dirti...dovrei controllare. Quanto al platform utilizzato, io ho messo Tasmota (anche esphome non sarebbe male). Usavo flux_led ma era inutilizzabile...proprio per quello che dicevi pure tu

**Reply by Jones1982** [reply]
Questo è quello che ho trovato sulla pagina delle integrazioni flux_led, sezione effects

```
light:
  - platform: flux_led
    devices:
      192.168.1.10:
        custom_effect:
          speed_pct: 100
          transition: 'strobe'
          colors:
            - [255,0,0]
            - [255,255,0]
            - [0,255,0]
            - [0,255,255]
            - [0,0,255]
            - [255,0,255]
```
 è per il configuration.yaml.

A me serve per l'integrazione Alarmo, nella sezione delle azioni:

```
name: RGB Red Allarme Attivo
modes: []
triggers:
  - state: triggered
actions:
  - service: light.turn_on
    service_data:
      entity_id: light.barra
      rgb_color:
        - 255
        - 0
        - 0
      brightness: 255
  - service: light.turn_on
    service_data:
      entity_id: light.striscia
      rgb_color:
        - 255
        - 0
        - 0
      brightness: 255
area: '1616825446'
```

Ho provato a integrare parte delle stringhe (custom_effect ecc...), ma da errori vari!
