### DISCUSSION TITLE
Costruzione di una automazione per deumidificatore

### DISCUSSION THREAD

**Discussion by nervimarco** [indomus/forum#410] [HUB: Home Assistant]
Buongiorno a tutti
mi servirebbe una mano per la creazione di una automazione, mi spiego:

ho un deumidificatore con interruttore push (a unica bolla, premo si accende, premo si spegne) a cui ho applicato
un sensore di umidità DHT11 il cui valore lo leggo da HOME ASSISTANT
con un esp8266 comando due relè per accensione e spegnimento (Ho saldato due fili ai due poli della bolla e collegati a relè) 

il problema sta che quando vado a costruire l'automazione i parametri minimo e massimo del valore del sensore di umidità sono invertiti cioè: a 70% si deve accendere ed a 55% si deve spegnere

ma l'automazione non accetta valori in questo modo
non so se mi sono spiegato

ho provato a creare due automazioni, una per il valore massimo ed una per il valore minimo

ma ogni volta che il valore ripassa per quello impostato viene dato un impulso a caso senza sapere se il deumidificatore è acceso o spento

ACCENSIONE:

```yaml
- id: '1622044927837'
  alias: Accensione deumidificatore
  description: ''
  trigger:
    - platform: numeric_state
      entity_id: sensor.deumidificatore_t_h_h
      above: '65'
  condition: []
  action:
    - type: turn_on
      device_id: 846ce665920cb1e1cefa26bf57d0e459
      entity_id: switch.deumidificatore_on_rele
      domain: switch
  mode: queued
  max: 10000
```

SPEGNIMENTO:

```yaml
- id: '1622044982449'
  alias: Spegnimento Deumidificatore
  description: ''
  trigger:
    - platform: numeric_state
      entity_id: sensor.deumidificatore_t_h_h
      below: '60'
  condition: []
  action:
    - type: toggle
      device_id: 7c154ec65a6294a74290900a609db55f
      entity_id: switch.deumidificatore_off_rele
      domain: switch
  mode: single
  max: 10000
```

**Comment by snakuzzo** [comment]
Per cortesia...correggi il post utilizzando il markdown...trovi come fare nel [README.md](https://github.com/indomus/forum#readme).

Per la tua automazione, puoi fare così..

```yaml
- id: '1622044927837'
  alias: Accensione - Spegnimento deumidificatore
  trigger:
  - platform: numeric_state
    entity_id: sensor.deumidificatore_t_h_h
    above: 65
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.deumidificatore_t_h_h
    below: 65
    for:
      minutes: 5
  action:
  - service: >
      {% if trigger.to_state.state | int > 65 %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    data:
      entity_id: switch.deumidificatore_on_rele
```

Ho aggiunto il for perché se l'umidità sale e scende di continuo avresti un continuo on/off.
In questo modo il trigger scatta se l'umidità resta sopra o sotto quelle soglie per 5 minuti,

Inoltre ho modificato i valori per basarsi solo su 65, altrimenti avresti un buco tra 60 e 65 che comporterebbe un funzionamento non corretto. Manterrebbe lo stato precedente (che sia on o off) ...dipende dal trigger scattato prima di entrare in quella soglia 60-65

**Reply by nervimarco** [reply]
![Immagine 2021-06-10 112037](https://user-images.githubusercontent.com/41838591/121499858-0e9c9e80-c9de-11eb-9808-cc44ef6b35c6.jpg)

**Reply by snakuzzo** [reply]
devi modificare il file YAML direttamente con il codice che ti ho scritto io...c'è pure scritto nel messaggio di errore

**Reply by nervimarco** [reply]
```yaml
- id: '1622044927837'
  alias: Accensione - Spegnimento deumidificatore
  trigger:
  - platform: numeric_state
    entity_id: sensor.deumidificatore_t_h_h
    above: 65
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.deumidificatore_t_h_h
    below: 65
    for:
      minutes: 5
  action:
  - service: >
      {% if trigger.to_state.state | int > 65 %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    target:
      entity_id: switch.deumidificatore_on_rele
```

ciao e grazie, il codice è quello che mi hai scritto te..... però mi da comunque errore quando lo inserisco...
mi dice "MESSAGE MALFORMED: INTEGRATION " NOT FOUND

**Reply by snakuzzo** [reply]
usa il markdown...trovi la guida nel  [REGOLAMENTO](https://github.com/indomus/forum) del forum.
Non siamo pignoli per spirito, ma perché serve soprattutto per capire se hai scritto bene il codice.
Correggi il post. Grazie

**Comment by nervimarco** [comment]
**_immagine rimossa_**

**Reply by nervimarco** [reply]
perche?????

**Reply by snakuzzo** [reply]
posta il codice...non fare foto allo schermo. Grazie

Rimuovo

**Reply by nervimarco** [reply]
ma quando uso il markdown quello che avviene sono gli apici in anlto, questi ``

**Reply by snakuzzo** [reply]
leggi BENE le istruzioni

EDIT: Te l'ho modificato io così capisci come si fa

**Reply by nervimarco** [reply]
```

- id: '1622044927837'
  alias: Accensione - Spegnimento deumidificatore
  trigger:
  - platform: numeric_state
    entity_id: sensor.deumidificatore_t_h_h
    above: 65
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.deumidificatore_t_h_h
    below: 65
    for:
      minutes: 5
  action:
  - service: >
      {% if trigger.to_state.state | int > 65 %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    target:
      entity_id: switch.deumidificatore_on_rele

```

Cosi dovremmo esserci?
