### DISCUSSION TITLE
Automazione per monitorare il consumo energetico

### DISCUSSION THREAD

**Discussion by auanasgheps** [indomus/forum#412] [HUB: Home Assistant]
Ciao,

Sono nuovo su HASSIO e per questo motivo non riesco a far funzionare una automazione molto basilare. 

Devo monitorare il consumo del mio frigorifero perchè è... buggato. Se non consuma nulla per un po' tempo, voglio che accadano cose. 
Il punto è che non riesco a far "scattare" il rilevamento.

Sto usando una presa Meross, integrata con il componente Meross Cloud (su HACS). Quella parte è a posto:

![image](https://user-images.githubusercontent.com/20586878/121559378-d2396480-ca16-11eb-88e2-0991b3fbe491.png)

Ora, se faccio una automazione con questo sensore, non si attiva. Ho messo valori scemi per triggerarla subito, ma non va.

La parte delle notifiche funziona, se clicco "Run Actions" ricevo la notifica. 
```yaml
alias: Consumo Frigorifero
description: Quando il consumo del frigorifero è troppo basso, manda un avviso.
trigger:
  - platform: numeric_state
    entity_id: sensor.frigorifero_mss310_power_sensor_w_0
    for: '0:00:15'
    below: '500'
condition: []
action:
  - service: notify.me
    data:
      message: Questo è un test.
mode: single
```

**Comment by gforment** [comment]
Ciao, se non leggo male il trigger scatta quando passa da un valore superiore a 500W ad uno inferiore... per un frigo mi pare una soglia un po' alta, temo riamga sempre sotto. Fai una prova con 20W

**Reply by auanasgheps** [reply]
Io ho impostato 500 proprio perché vorrei vederlo scattare in qualunque momento (per test), il consumo di picco è 200W. L'automazione funziona al contrario... O io non sto seguendo la logica?

L'ho modificato e ti aggiorno. Ora è in "sleep" fra qualche ora si accende e ti dico.

**Reply by gforment** [reply]
il trigger numerico scatta quando attraversi la soglia, se metti una soglia troppo alta non la attraversi mai e quindi non scatta mai! 😊
devi essere sicuri che il valore sia "attraversato" quindi sicuramente deve essere sotto il picco ma direi anche sotto il valore medio...
io ad esempio salvo l'ora dell'ultimo ciclo di lavatrice quando sono below 1000,ma la lavatrice solitamente gira a 2000w

**Reply by auanasgheps** [reply]
Grazie per il chiarimento! Il trigger aggiornato con il tuo suggerimento funziona! 

Pensavo che fosse un semplicissimo "if then" e non che il valore andasse attraversato.

Per essere sicuro lo abbasserò a 10W, perché quando apro lo sportello consuma 15W e quindi voglio evitare casi limite, anche se potrei tranquillamente mettere 2W visto che consuma poco più di 1W in standby.

Questo frigorifero non ha un valore "medio", ha una 15ina di anni e il motore fa solo stati on/off. 

Grazie ancora! Trovare queste informazioni a volte è molto difficile perché alcuni concetti vengono dati per scontato.
Per i posteri, questa è la configurazione.

```yaml
description: Quando il consumo del frigorifero è troppo basso per più di 3 ore, manda un messaggio su Telegram.
trigger:
  - platform: numeric_state
    entity_id: sensor.frigorifero_mss310_power_sensor_w_0
    for: '03:00:00'
    below: '10'
condition: []
action:
  - service: notify.me
    data:
      message: Il frigo sì è staccatoh da 3 ore.
      title: Annunciazione, Annunciazione!
mode: single
```
