### DISCUSSION TITLE
AC on/off quando almeno qualcuno a casa.

### DISCUSSION THREAD

**Discussion by EmAnzi3** [indomus/forum#416] [HUB: Home Assistant]
Salve a tutti,
Sto cercando di creare un'automazione per accendere/spegnere l'aria condizionata quando almeno un membro della famiglia (2 persone in totale) è in casa.
Ho provato con questa configurazione ma sembra funzionare solo quando entrambi siamo a casa.

```
alias: Raffreddamento Salotto (Acceso)
description: ''
trigger:
  - platform: numeric_state
    entity_id: sensor.salotto_temperature
    above: '24'
condition:
  - condition: zone
    entity_id: person.alex
    zone: zone.home
  - condition: or
    conditions:
      - condition: zone
        entity_id: person.manu
        zone: zone.home
action:
  - scene: scene.raffreddamento_salotto
  - service: notify.telegram
    data:
      message: Raffreddamento salotto acceso.
mode: single
```

Mi piacerebbe inoltre che al rientro di uno dei due, se la temperatura è al di sopra dei 24°C, l'AC si attivasse automaticamente.
Grazie in anticipo per il gentile supporto!

**Comment by Scialla** [comment]
```
condition:
  condition: or
  conditions:
  - condition: zone
    entity_id: person.alex
    zone: zone.home
  - condition: zone
    entity_id: person.manu
    zone: zone.home
```

**Comment by Scialla** [comment]
```
alias: Raffreddamento Salotto (Acceso)
description: ''
trigger:
  - platform: numeric_state
    entity_id: sensor.salotto_temperature
    above: '24'
    for:
      minutes: 5
  - platform: zone
      entity_id: person.alex
      zone: zone.home
      event: enter
  - platform: zone
    entity_id: person.manu
    zone: zone.home
    event: enter
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.salotto_temperature
      above: '24'
    - condition: or
      conditions:
      - condition: zone
        entity_id: person.alex
        zone: zone.home
      - condition: zone
        entity_id: person.manu
        zone: zone.home
action:
  - scene: scene.raffreddamento_salotto
  - service: notify.telegram
    data:
      message: Raffreddamento salotto acceso.
mode: single
```
Prova, dovrebbe andare..

**Comment by Larry-78** [comment]
ciao @EmAnzi3 potresti basarti sullo stato di un semplice gruppo creato dalle uniche due persone, per esempio

```yaml
group:
  family_group:
    entities:
      - person.alex
      - person.manu
```
il gruppo risulterà 'home' se almeno uno dei due è a casa. Se invece al contrario vuoi che tutti i membri devono essere a casa per far cambiare lo stato in 'home', basta aggiungere l'opzione `all: true`

**Comment by EmAnzi3** [comment]
Grazie per le gentili risposte, il mio errore principale è stato quello di non porre la condition "Or" all'inizio.

**Comment by EmAnzi3** [comment]
Buongiorno ragazzi,
Scusate ancora il disturbo ma volevo provare ad aggiungere un'ulteriore condizione all'automazione sopra espressa, ossia quella di renderla operativa solo dalle 7:00 alla mezzanotte.

```
alias: Raffreddamento Salotto (Acceso)
description: ''
trigger:
  - platform: numeric_state
    entity_id: sensor.salotto_temperature
    above: '24'
condition:
  - condition: or
    conditions:
      - condition: zone
        entity_id: person.emanuele
        zone: zone.home
      - condition: zone
        entity_id: person.alessandra
        zone: zone.home
  - condition: time
    after: '07:00:00'
action:
  - scene: scene.raffreddamento_salotto
  - service: notify.telegram
    data:
      message: Raffreddamento salotto acceso.
mode: single
```

In questo modo l'aria condizionata non parte più dopo la mezzanotte, tuttavia, dalle 7:00 in poi, se la temperatura è già al di sopra dei 24°C l'automazione non si attiva.
Suggerimenti? Grazie.
