### DISCUSSION TITLE
Chissà dov'è Antonella

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#419] [HUB: Home Assistant]
In Lovelance la card Persona mi visualizza grazie a person.antonella se Antonella è in caso oppure dove si trova in base alla zona impostata su mappa. Con Alexa richiamo lo script seguente, che mi sembra corretto:
```
dovea:
  alias: Dove Antonella
  sequence:
  - service: notify.alexa_media_echoshow_di_egidio
    data:
      message: "{% if is_state('person.antonella', 'home') %}
            Antonella è a casa
            {% else %}
            Antonella è a {{ states('person.antonella') }}
            {% endif %}"
      data:
        type: announce
        method: spoken
        volume_level: 7
      target: media_player.alexa
  mode: single
```
Ma Alexa mi risponde: _Non trovo quel tracker_
Non funziona nemmeno se a person.antonella sostituisco device_tracker.life360_antonella
Questi i miei tracker:
```
device_tracker:
  - platform: netgear
    host: 10.0.0.1
    username: !secret router_login
    password: !secret router_psw
    interval_seconds: 10
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
  - platform: nmap_tracker
    hosts:
     - 10.0.0.126  
     - 10.0.0.108  
    home_interval: 60
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
  - platform: bluetooth_tracker
    interval_seconds: 10
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    interval_seconds: 10
    consider_home: 60
```

Avete suggerimenti?

**Comment by calz64** [comment]
Secondo me devi creare una routine sull'app alexa, e devi anche integrare il tuo script fra le entità esposte ad alexa se hai configurato il filtro simile a questo in configurazione.

```
# filtro entità-domini AWS_Alexa
alexa:
  smart_home:
    filter:
      exclude_domains:
        - lock
        - alarm_control_panel
        - automation
        - binary_sensor
        - camera
        - cover
        -.....
      include_entities:
        - .....
```

**Reply by Dregi56** [reply]
Ti ringrazio per la risposta. Quello che mi suggerisci l'ho già messo in atto. Comunque il problema è relativo alle "map-zone" create in HA, se il device in tracker è dentro una zona già definita oppure no. Avevo letto da qualche parte che sarebbe possibile utilizzare google-map per individuare qualsiasi zona (anche non definita in HA) ...ma poi non ho più dato seguito...

**Reply by calz64** [reply]
Interessante l'idea, in effetti ci pensavo anch'io, ma la rilevazione del tracker è già presente in HA, infatti sulla mappa ti indica dove si trova il device (è lo stato dell'entità che cambia solo in base alle zone definite in HA) quello che bisognerebbe fare è trasformare le coordinate (che nel data_base sono scritte negli attibuti del device) in qualcosa che sia identificabile come "nome della via" e "città".

**Reply by calz64** [reply]
Oggi guardando nella sezione "storico" dove ci sono tutte le attività delle entità varie mi cade l'occhio su un sensore del tipo "***geocoded_location".
Il gioco è fatto: questo tipo di entità ha attributi con già una geolocalizzazione referenziata per - via, civico, cap, città, nazione.!!! 
Lo script è semplice da creare inserendo una sequenza del tipo sotto è alexa pronuncia perfettamente l'attributo di cui sopra. Ovviamente devi attivare questo sensore nell'app del telefonino che vuoi localizzare. Non sono ancora riuscito a far rispondere Alexa con un comando vocale ma credo che sia un passaggio che prima o poi arriva (anzi se ci riesci passa parola). Un saluto


```
service: notify.alexa_media_****
data:
  message: >-
    {% if is_state('person.****', 'home') %} NOME è a casa {% else %}
     NOME è a {{ states('***geocoded_location') | string }} {% endif %}
  data:
    type: announce
    method: spoken
  target: media_player.alexa
```
