### DISCUSSION TITLE
Integrazione Google Home Mini e interazioni eventi

### DISCUSSION THREAD

**Discussion by Jones1982** [indomus/forum#421] [HUB: Home Assistant]
Buondì,
probabilmente ci sarà qualche vecchio post su questo argomento, ma vorrei sapere se:

1) tramite HA posso farli riprodurre suoni (mp3-wave) e/o dire frasi in base agli eventi etc.. (es: Attenzione porta aperta);
2) cambiare il comando "Hey/ok Google" con altro;
3) usare un altra voce, magari usando le vecchie librerie per i navigatori satellitari (es: tomtom)

Grazie!

**Comment by snakuzzo** [comment]
1. sì
2. no
3. sì ma ci sono voci predefinite da poter usare, non quella che ti pare

**Reply by Jones1982** [reply]
ok grazie per le delucidazioni...
ma quale procedura uso x integrarli? quella nella "Raccolta componenti aggiuntivi" (Google Assistant SDK) in Supervisor?

Grazie sempre

**Reply by snakuzzo** [reply]
Una cosa è integrare uno speaker ed utilizzarlo come media player
Altro è esporre i device di HA su Google Assistant (per poterli poi pilotare con gli speaker)

La prima ti viene gratis. Con l'autodiscovery di HA li trovi al volo
La seconda va fatta integrazione o con Nabucasa (a pagamento) oppure con l'integrazione creando un progetto su GCP. [GUIDA](https://indomus.it/guide/integrare-gratuitamente-google-home-assistant-con-home-assistant-via-gcp/)

**Reply by Jones1982** [reply]
Finalmente ho trovato un po di tempo x provare a integrare gli speaker home mini (con la prima soluzione da te indicata).

Tralasciando che (H.A.) non mi ha dato nessuna notifica (nella barra) di nuovi dispositivi dopo l'aggiunta in configuration.yaml di `discovery:` e il successivo riavvio, ho ovviato inserendo gli ip dei 3 dispositivi manualmente nell'integrazione "Google Cast".

Sto provando a fare delle automazioni, una delle quali "dovrebbe" avvisarmi con msg vocale sullo speaker, che sta piovendo, usando come attivazione il cambio di stato del servizio meteo integrato in HA (Meteorologisk institutt (Met.no).

Puoi dirmi se ho scritto bene l'entità meteo, attributo etc...?

```yaml
alias: Avvisa che piove a casa
description: ''
trigger:
  - platform: state
    entity_id: weather.casa
    attribute: forecast
    to: rainy
condition: []
action:
  - service: tts.google_say
    data:
      entity_id: media_player.stanzetta
      message: AVVISO METEO, sta piovendo!
mode: single
```

**### _Grazie sempre!!!_**


P.s.: lo so che il servizio meteo non è preciso/affidabile, ma sto aspettando l'arrivo di un sensore di allagamento da mettere all'aperto, per usarlo come rilevatore di pioggia.

**Reply by snakuzzo** [reply]
Non posso sapere se hai scritto bene se prima non utilizzi bene il markdown.
Ti invito a leggere il regolamento e come utilizzare correttamente il markdown... il singolo backtick si usa quando stai postando una sola riga di codice. Se stai postando un blocco di codice ci vogliono tre backtick prima (magari evidenziando anche il linguaggio) e tre alla fine.

![capture_2021-08-28_01-52](https://user-images.githubusercontent.com/7205371/131198938-9509c728-8c7c-4d27-a8c2-62b13fb8a321.png)

...quindi correggi il tuo post per cortesia.

Quanto all'automazione,  credo tu voglia fare qualcosa del genere...

```yaml
automation:

- id: prova
  alias: Prova
  trigger:
  - platform: state
    entity_id: weather.casa
    attribute: forecast
    to: "rainy"
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.stanzetta
      message: "Avviso meteo, sta piovendo!"
```
