### DISCUSSION TITLE
SHELLY + MQTT - problemi con integrazione

### DISCUSSION THREAD

**Discussion by braudoo** [indomus/forum#427] [HUB: Home Assistant]
Ciao a tutti, facendo l'aggiornamento alla versione 2021.6 di HA Core, non mi riconosceva più i dispositivi Shelly, di fatto il repositary di ShellyForHASS non funzionava più.
Ho colto la palla al balzo provando ad integrare i dispositivi tramite MQTT.

Ho fleggato l'opzione MQTT nel dispositivo.

Ho integrato il tutto nel configuration.yamal, ma di comunicare non ne vuol sapere.

Ho pensato che fosse troppo distante antenna dal dispositivo, mo provando a mettere un sensore di temp. collegato al broker, mi risulta un segnale poco meno della metà.

Come indirizzo del server, ho utilizzato l'IP del mio RP4, con la classica porta 1883.

Ho fatto prova sia con "Use custom MQTT", sia mantenendo il nome originale.

User e pw sono corretti.

L'entità appare, e quando lo collego alla card del pulsante, dando il comando di accendersi, questo non fa niente, non da nessun segno.

Ho provato mettermi in ascolto con il topic “shellies/command“, ma niente di niente.

Qualcuno riuscirebbe ad aiutarmi?

Grazie.

**Comment by snakuzzo** [comment]
Sì, ma devi postare cos'hai scritto in configurazione.
Ad ogni modo se sei poco pratico, puoi anche provare l'integrazione Shelly su HA. Se non li trovi con l'autodiscovery ti basta abilitare l'integrazione e aggiungere i device inserendo il loro IP.

**Comment by braudoo** [comment]
Non è un problema.
Allora queste le impostazioni dello Shelly:
![image](https://user-images.githubusercontent.com/58866563/122012506-8a6f6000-cdbd-11eb-8f18-d5a65e583d4c.png)

Queste le impostazioni del configuration.yaml in merito all'entità:
```
light:
  platform: mqtt
  schema: template
  name: Faretti cucina
  command_topic: "shellies/shellydimmer-DB3D4C/light/0/set"
  state_topic: "shellies/shellydimmer-DB3D4C/light/0/status"
  command_on_template: >
    {"turn": "on"
      {% if brightness is defined %} 
        , "brightness": {{ brightness | float | multiply(0.3922) | round(0) }}
      {% endif %}
    }
  state_template: > 
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.brightness | float | multiply(2.55) | round(0) }}"
  command_off_template: '{"turn":"off"}'
  qos: 1
```


e questo in merito alla configurazione dell'mqtt:

```
mqtt:
  discovery: true
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'
  broker: 127.0.0.1
  username: mqtt_user
  password: Alfio-1982
  port: 1883
  client_id: home-assistant
  keepalive: 60

```

L'integrazione ora ce l'ho facendo un downgrade dell'agg. di HA, e infatti adesso li vedo con quelli, ma volevo fare integrazione tramite MQTT e sganciarmi dal cloud.

Se serve tutto il file **configuration.yaml** posso postarlo. Fammi sapere.

Grazie per la risp.

**Reply by snakuzzo** [reply]
La definizione dell'entità mi sembra corretta, anche se vedo che non stai usando l'availability topic basato sul [LWT](https://indomus.it/formazione/mqtt-cose-e-come-funziona-il-last-will-and-testament-lwt/).

Io la definirei così...

```yaml
light:

- platform: mqtt
  schema: template
  name: Faretti cucina
  command_topic: "shellies/shellydimmer-DB3D4C/light/0/set"
  state_topic: "shellies/shellydimmer-DB3D4C/light/0/status"
  availability_topic: "shellies/shellydimmer-DB3D4C/online"
  payload_available: "true"
  payload_not_available: "false"
  command_on_template: >
    {"turn": "on"
      {% if brightness is defined %}
        , "brightness": {{ brightness | float | multiply(0.3922) | round(0) }}
      {% endif %}
    }
  state_template: >
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.brightness | float | multiply(2.55) | round(0) }}"
  command_off_template: '{"turn":"off"}'
  qos: 1
```
Aggiungendo l'`availability_topic` dovrai anche aggiungere un'automazione di announce degli shelly all'avvio di HA

```yaml
automation:

- id: shelly_announce
  alias: Shelly Announce
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      payload: announce
      topic: shellies/command
```

Così deve funzionare...ti ho postato esattamente quello che ho io in configurazione
