### DISCUSSION TITLE
Local/Cloud SONOFF

### DISCUSSION THREAD

**Discussion by nromagna** [indomus/forum#431] [HUB: Home Assistant]
Ciao a tutti ho impostato su SONOFF LAN in Hacs 
```
sonoff:
    username: mymail@gmail.com
    password: mypassword

```
Quindi in teoria dovrebbe funzionare NON in cloud esatto? Però mi trovo tutti i Sonoff con **Local** e **Cloud** (oppure solo Cloud).

```
manufacturer: SONOFF
model: POW
sw_version: PSC-B67-GL v3.5.0
local: online   <------------------
cloud: online   <------------------
rssi: -50
power: 0
current: 0
voltage: 232.74
friendly_name: Strada
icon: hass:outdoor-lamp

```

Cosa comporta questo? Dovrei modificare la con

```
sonoff:
   username: mymail@gmail.com
   password: mypassword
   mode: local
   reload: always

```

Oppure meglio lasciare tutto così? Grazie.

**Comment by Scialla** [comment]
Se leggi la guida del component spiega tutto:
https://github.com/AlexxIT/SonoffLAN

Puoi usarlo in cloud oppure solo in local (io ti consiglio quest'ultimo)
se lo usi solo in local devi togliere quella configurazione e usare, come da guida:
```
sonoff:
  devices:
    1000abcdefg:
      devicekey: f9765c85-463a-4623-9cbe-8d59266cb2e4
```
ovviamente questo è l'esempio della guida, devi recuperare la tua device key di ogni dispositivo sonoff, sulla guida c'è scritto come fare
