### DISCUSSION TITLE
Errore cover per tapparelle con Tasmota

### DISCUSSION THREAD

**Discussion by manny199** [indomus/forum#447] [GENERALE - Discussioni generiche]
Ciao a tutti, scrivendo in configuration.yaml la cover per la gestione della posizione delle tapparelle, in fase di validazione, ottengo il seguente errore: "Invalid config for [cover.mqtt]: 'value_template' must be set together with 'state_topic'".
Ho seguito la guida dell'articolo indomus [https://indomus.it/guide/integrare-la-gestione-tapparelle-di-tasmota-a-home-assistant-via-mqtt/](url)
Chiaramente ho già il dispositivo con Tasmota che funziona perfettamente ma, ovviamente, senza il rilevamento della posizione. Dove sbaglio?

**Comment by snakuzzo** [comment]
Leggi il changelog quando aggiorni HA...

![image](https://user-images.githubusercontent.com/7205371/122828026-6ba12a00-d2e5-11eb-8f12-73c5d77c447e.png)

**Reply by snakuzzo** [reply]
Di seguito un mio esempio di configurazione di tapparella con firmware Tasmota...

```yaml
- platform: mqtt
  name: "test"
  availability_topic: "tele/tasmota-tappatest/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  command_topic: "cmnd/tasmota-tappatest/Backlog"
  payload_open: "ShutterOpen1"
  payload_close: "ShutterClose1"
  payload_stop: "ShutterStop1"
  set_position_topic: 'cmnd/tasmota-tappatest/ShutterPosition1'
  position_topic: "stat/tasmota-tappatest/RESULT"
  position_open: 100
  position_closed: 0
  position_template: >
    {% if ('Shutter1' in value_json) and ('Position' in value_json.Shutter1) %}
      {{ value_json.Shutter1.Position }}
    {% else %}
      {% if is_state('cover.test', 'unknown') %}
        50
      {% else %}
        {{ state_attr('cover.test','current_position') }}
      {% endif %}
    {% endif %}
  retain: false
  optimistic: false
  qos: 1
```

**Reply by snakuzzo** [reply]
Per quanto riguarda la guida...aggiorneremo il codice.
Grazie per la segnalazione :)

**Reply by manny199** [reply]
@snakuzzo Grazie per le dritte, 
volevo anche chiederti, avendo un sonoff 4CHPRO che gestisce 2 tapparelle, con i seguenti comandi:
sonoff4pro2/POWER1 e sonoff4pro2/POWER2 per una tapparella 
e 
sonoff4pro2/POWER3 e sonoff4pro2/POWER4 per la seconda tapparella, 
cosa dovrei aggiungere alla cover che mi hai rappresentato?

Grazie

**Comment by manny199** [comment]
Ciao a tutti, ho risolto il problema di integrazione con 4CHPRO con 2 tapparelle ma adesso mi ritrovo continuamente il seguente errore in Log:

Logger: homeassistant.components.mqtt.cover
Source: components/mqtt/cover.py:385
First occurred: 12:46:27 (214 occurrences)
Last logged: 12:52:49
**_Payload 'None' is not numeric_**
Ho cercato in rete ma non trovo risposta.

Questa è la cover:

```
- platform: mqtt
  name: "Tapp studio"
  availability_topic: "tele/sonoff4pro2/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  command_topic: "cmnd/sonoff4pro2/Backlog"
  payload_open: "ShutterOpen1"
  payload_close: "ShutterClose1"
  payload_stop: "ShutterStop1"
  set_position_topic: 'cmnd/sonoff4pro2/ShutterPosition1'
  position_topic: "stat/sonoff4pro2/RESULT"
  position_open: 100
  position_closed: 0
  position_template: >
    {% if ('Shutter1' in value_json) and ('Position' in value_json.Shutter1) %}
      {{ value_json.Shutter1.Position }}
    {% else %}
      {% if is_state('cover.test', 'unknown') %}
        50
      {% else %}
        {{ state_attr('cover.test','current_position') }}
      {% endif %}
    {% endif %}
  retain: false
  optimistic: false
  qos: 1
```
Qualcuno mi può aiutare?

**Reply by snakuzzo** [reply]
devi vedere cosa manda Tasmota...perché probabilmente invierà un topic conun payload vuoto che però non è previsto lato home assistant

**Comment by manny199** [comment]
@snakuzzo Quello che leggo per Tasmota è:

IN TASMOTA discovery config:
```
{"ip":"192.168.1.159","dn":"Tasmota","fn":["Tasmota","Tasmota2","Tasmota3","Tasmota4",null,null,null,null],"hn":"sonoff4pro2-1125","mac":"AE5T11GH9T9H","md":"Sonoff 4CH Pro","ty":0,"if":0,"ofln":"Offline","onln":"Online","state":["OFF","ON","TOGGLE","HOLD"],"sw":"9.5.0","t":"sonoff4pro2","ft":"%prefix%/%topic%/","tp":["cmnd","stat","tele"],"rl":[3,3,3,3,0,0,0,0],"swc":[-1,-1,-1,-1,-1,-1,-1,-1],"swn":[null,null,null,null,null,null,null,null],"btn":[0,0,0,0,0,0,0,0],"so":{"4":0,"11":0,"13":0,"17":0,"20":0,"30":0,"68":0,"73":0,"82":0,"114":0,"117":0},"lk":1,"lt_st":0,"sho":[1,1,0,0],"ver":1}
```
IN TASMOTA discovery sensors:
```
{"sn":{"Time":"2021-07-08T12:34:10","Shutter1":{"Position":100,"Direction":0,"Target":100},"Shutter2":{"Position":100,"Direction":0,"Target":100}},"ver":1}
```

IN TELE negli STATE:
```
{"Time":"2021-07-08T13:55:07","Uptime":"0T20:30:10","UptimeSec":73810,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":13,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"lamiawifi","BSSId":"66:77:54:56:9F:64","Channel":3,"Mode":"11n","RSSI":86,"Signal":-57,"LinkCount":3,"Downtime":"0T00:00:18"}}
```
IN TELE in SENSOR:
```
{"Time":"2021-07-08T13:55:07","Shutter1":{"Position":100,"Direction":0,"Target":100},"Shutter2":{"Position":100,"Direction":0,"Target":100}}
```
Onestamente non ci capisco nulla ...

**Reply by snakuzzo** [reply]
i topic di discovery non servono...visto che hai configurato manualmente l'entità.
Credo tu debba metterti davanti due finestre...una in tail sul log di HA, l'altra in ascolto sul broker con mosquitto_sub e vedere cosa accade. Secondo me il problema è sulla pubblicazione del topic `stat/sonoff4pro2/RESULT`

**Reply by manny199** [reply]
@snakuzzo ma nel caso come faccio a cambiare il topic che Tasmota invia a mosquitto?

**Reply by manny199** [reply]
@snakuzzo questi sono i risultati della telemetria con mosquitto_sub:

```
Client (null) received PUBLISH (d0, q0, r0, m0, 'cmnd/sonoff4pro2/ShutterPosition1', ... (2 bytes))
90
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (15 bytes))
{"POWER1":"ON"}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/POWER1', ... (2 bytes))
ON
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (23 bytes))
{"ShutterPosition1":90}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (55 bytes))
{"Shutter1":{"Position":100,"Direction":1,"Target":90}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (109 bytes))
{"Shutter1":{"Position":97,"Direction":1,"Target":90},"Shutter2":{"Position":100,"Direction":0,"Target":100}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (109 bytes))
{"Shutter1":{"Position":93,"Direction":1,"Target":90},"Shutter2":{"Position":100,"Direction":0,"Target":100}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (16 bytes))
{"POWER1":"OFF"}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/POWER1', ... (3 bytes))
OFF
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/SHUTTER1', ... (2 bytes))
90
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (54 bytes))
{"Shutter1":{"Position":90,"Direction":0,"Target":90}}


Client (null) received PUBLISH (d0, q0, r0, m0, 'cmnd/sonoff4pro2/ShutterPosition2', ... (2 bytes))
90
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (15 bytes))
{"POWER3":"ON"}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/POWER3', ... (2 bytes))
ON
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (23 bytes))
{"ShutterPosition2":90}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (55 bytes))
{"Shutter2":{"Position":100,"Direction":1,"Target":90}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (107 bytes))
{"Shutter1":{"Position":90,"Direction":0,"Target":90},"Shutter2":{"Position":98,"Direction":1,"Target":90}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'tele/pzem016/STATE', ... (230 bytes))
{"Time":"2021-07-08T14:57:39","Uptime":"0T21:40:10","Heap":18,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"Wifi":{"AP":2,"SSId":"PASSERA","BSSId":"F0:2F:74:12:58:D0","Channel":13,"RSSI":24,"LinkCount":3,"Downtime":"0T00:00:44"}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (107 bytes))
{"Shutter1":{"Position":90,"Direction":0,"Target":90},"Shutter2":{"Position":94,"Direction":1,"Target":90}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (16 bytes))
{"POWER3":"OFF"}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/POWER3', ... (3 bytes))
OFF
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/SHUTTER2', ... (2 bytes))
90
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2/RESULT', ... (54 bytes))
{"Shutter2":{"Position":90,"Direction":0,"Target":90}}


Client (null) received PUBLISH (d0, q0, r0, m0, 'cmnd/sonoff4pro2_group2/ShutterPosition2', ... (3 bytes))
100
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group2/RESULT', ... (15 bytes))
{"POWER3":"ON"}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group2/POWER3', ... (2 bytes))
ON
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group2/RESULT', ... (24 bytes))
{"ShutterPosition2":100}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group2/RESULT', ... (55 bytes))
{"Shutter2":{"Position":90,"Direction":1,"Target":100}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group2/RESULT', ... (110 bytes))
{"Shutter1":{"Position":100,"Direction":0,"Target":100},"Shutter2":{"Position":91,"Direction":1,"Target":100}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group2/RESULT', ... (110 bytes))
{"Shutter1":{"Position":100,"Direction":0,"Target":100},"Shutter2":{"Position":94,"Direction":1,"Target":100}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group2/RESULT', ... (110 bytes))
{"Shutter1":{"Position":100,"Direction":0,"Target":100},"Shutter2":{"Position":98,"Direction":1,"Target":100}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group2/RESULT', ... (16 bytes))
{"POWER3":"OFF"}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group2/POWER3', ... (3 bytes))
OFF
Client (null) received PUBLISH (d0, q0, r0, m0, 'tele/pzem016/STATE', ... (230 bytes))
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group2/SHUTTER2', ... (3 bytes))
100
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group2/RESULT', ... (56 bytes))
{"Shutter2":{"Position":100,"Direction":0,"Target":100}}


Client (null) received PUBLISH (d0, q0, r0, m0, 'cmnd/sonoff4pro2_group3/ShutterPosition2', ... (2 bytes))
10
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group3/RESULT', ... (15 bytes))
{"POWER3":"ON"}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group3/POWER3', ... (2 bytes))
ON
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group3/RESULT', ... (23 bytes))
{"ShutterPosition2":10}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group3/RESULT', ... (53 bytes))
{"Shutter2":{"Position":0,"Direction":1,"Target":10}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group3/RESULT', ... (108 bytes))
{"Shutter1":{"Position":100,"Direction":0,"Target":100},"Shutter2":{"Position":3,"Direction":1,"Target":10}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group3/RESULT', ... (108 bytes))
{"Shutter1":{"Position":100,"Direction":0,"Target":100},"Shutter2":{"Position":8,"Direction":1,"Target":10}}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group3/RESULT', ... (16 bytes))
{"POWER3":"OFF"}
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group3/POWER3', ... (3 bytes))
OFF
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group3/SHUTTER2', ... (2 bytes))
10
Client (null) received PUBLISH (d0, q0, r0, m0, 'stat/sonoff4pro2_group3/RESULT', ... (54 bytes))
{"Shutter2":{"Position":10,"Direction":0,"Target":10}}

```
ma continuo a non venirne a capo

e poi:

cmnd/tasmotas/POWER (null)
stat/sonoff4pro2_group3/RESULT {"POWER1":"OFF"}
stat/sonoff4pro2_group3/POWER1 OFF
stat/sonoff4pro2/RESULT {"POWER1":"OFF"}
stat/sonoff4pro2/POWER1 OFF
stat/sonoff4pro2_group2/RESULT {"POWER1":"OFF"}
stat/sonoff4pro2_group2/POWER1 OFF

**Reply by snakuzzo** [reply]
Innanzi tutto cambiando topic non è che risolvi qualcosa...non ti serve. Se vuoi vedere come si fa studia i [Comandi Tasmota](https://tasmota.github.io/docs/Commands/). Li puoi impartire via MQTT o direttamente sulla console Tasmota. Puoi anche configurandolo dalla webgui Tasmota del device.

Ad ogni modo la tua cover è sbagliata...hai lasciato `cover.test` nei template...hai fatto semplicemente copia incolla di quello che ho scritto io senza guardare.

Prova così...

```yaml
- platform: mqtt
  name: "Tapp studio"
  availability_topic: "tele/sonoff4pro2/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  command_topic: "cmnd/sonoff4pro2/Backlog"
  payload_open: "ShutterOpen1"
  payload_close: "ShutterClose1"
  payload_stop: "ShutterStop1"
  set_position_topic: 'cmnd/sonoff4pro2/ShutterPosition1'
  position_topic: "stat/sonoff4pro2/RESULT"
  position_open: 100
  position_closed: 0
  position_template: >
    {% if ('Shutter1' in value_json) and ('Position' in value_json.Shutter1) %}
      {{ value_json.Shutter1.Position }}
    {% else %}
      {% if is_state('cover.tapp_studio', 'unknown') %}
        50
      {% else %}
        {{ state_attr('cover.tapp_studio','current_position') }}
      {% endif %}
    {% endif %}
  retain: false
  optimistic: false
  qos: 1
```
