### DISCUSSION TITLE
Automazione per Accensione e Spegnimento automatico AC - Una volta disabilitato non si riabilita.

### DISCUSSION THREAD

**Discussion by Zagor4** [indomus/forum#452] [HUB: Home Assistant]
Ciao a tuti,
Ho da poco creato 2 automazioni per l'accensione e lo spegnimento automatico di un condizionatore, per mezzo della comparazione tra i valori di temperatura e umidità ambientali rilevati da un sensore esterno e soglie definite tramite input numbers.

Tutto sembra funzionare correttamente finchè non disabilito le automazioni.
Un volta riabilitate le automazioni anche se  i trigger e le condizioni vengono rispettate l'automazione non parte... 
Per far si che tutto si riabiliti è necessario riavviare HA.

Di seguito il codice delle 2 automazioni:
``````
########### Automazione per accensione deumidificatore Sala ###########
- id: "1624279610046"
  alias: AC_Sala_Accensione
  trigger:
    - platform: template
      value_template: "{{ states('sensor.temperatura_sala')|float > states('input_number.temp_high_sala') | float  }}"
    - platform: template
      value_template: "{{ states('sensor.umidita_sala')|float > states('input_number.hum_high_sala') | float  }}"
  condition:
    condition: state
    entity_id: climate.condizionatore_sala
    state: "off"
  action:
    - service: notify.mobile_app_sm_a505fn
      data:
        message: |
          ❄️
          Temperatura Sala {{ states('sensor.temperatura_sala') | round(1) }}°,
          Umidità Sala {{ states('sensor.umidita_sala') | round(1) }}%,
          Accendo il deumidificatore!
        title: Condizionatore Sala
    - service: scene.turn_on
      target:
        entity_id: scene.deumidificatore_sala_auto
  mode: single

########### Automazione per spegnimento deumidificatore Sala ###########
- id: "1624279610047"
  alias: AC_Sala_Spegnimento
  trigger:
    - platform: template
      value_template: "{{ states('sensor.temperatura_sala')|float < states('input_number.temp_low_sala') | float  }}"
    - platform: template
      value_template: "{{ states('sensor.umidita_sala')|float < states('input_number.hum_low_sala') | float  }}"
  condition:
    condition: state
    entity_id: climate.condizionatore_sala
    state: "dry"
  action:
    - service: notify.mobile_app_sm_a505fn
      data:
        message: |
          ❄️
          Temperatura Sala {{ states('sensor.temperatura_sala') | round(1) }}°,
          Umidità Sala {{ states('sensor.umidita_sala') | round(1) }}%,
          Spengo il deumidificatore!
        title: Condizionatore Sala
    - service: climate.turn_off
      data:
        entity_id:
          - climate.condizionatore_sala
  mode: single
``````

Grazie mille a chiunque volesse darmi una mano !
Buona serata

**Comment by snakuzzo** [comment]
Devi usare il markdown, leggi il [REGOLAMENTO](https://github.com/indomus/forum/blob/main/README.md)...altrimenti dovrò rimuovere il topic.
Grazie

**Comment by Zagor4** [comment]
Modificata l'automazione così:

``````
########### Automazione per accensione deumidificatore Sala ###########
- id: "1624279610046"
  alias: AC_Sala_Accensione
  trigger:
    - platform: time_pattern
      minutes: "/3"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: climate.condizionatore_sala
        state: "off"
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ states('sensor.temperatura_sala')|float > states('input_number.temp_high_sala')|float  }}"
          - condition: template
            value_template: "{{ states('sensor.umidita_sala')|float > states('input_number.hum_high_sala')|float  }}"
  action:
    - service: notify.mobile_app_sm_a505fn
      data:
        message: |
          ❄️
          Temperatura Sala {{ states('sensor.temperatura_sala') | round(1) }}°,
          Umidità Sala {{ states('sensor.umidita_sala') | round(1) }}%,
          Accendo il deumidificatore!
        title: Condizionatore Sala
    - service: scene.turn_on
      target:
        entity_id: scene.deumidificatore_sala_auto
  mode: single

########### Automazione per spegnimento deumidificatore Sala ###########
- id: "1624279610047"
  alias: AC_Sala_Spegnimento
  trigger:
    - platform: time_pattern
      minutes: "/3"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: climate.condizionatore_sala
        state: "dry"
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ states('sensor.temperatura_sala')|float < states('input_number.temp_low_sala')|float  }}"
          - condition: template
            value_template: "{{ states('sensor.umidita_sala')|float < states('input_number.hum_low_sala')|float  }}"
  action:
    - service: notify.mobile_app_sm_a505fn
      data:
        message: |
          ❄️
          Temperatura Sala {{ states('sensor.temperatura_sala') | round(1) }}°,
          Umidità Sala {{ states('sensor.umidita_sala') | round(1) }}%,
          Spengo il deumidificatore!
        title: Condizionatore Sala
    - service: climate.turn_off
      data:
        entity_id:
          - climate.condizionatore_sala
  mode: single
``````
E ora funziona.
Buona serata
