### DISCUSSION TITLE
Gestione Automazioni Climatizzazione

### DISCUSSION THREAD

**Discussion by NdR91** [indomus/forum#456] [HUB: Home Assistant]
Ciao a tutti, 

Avrei bisogno di qualche spunto / idea su come gestire i miei climatizzatori.
Nello specifico, uno è situato al piano superiore in studio, dove tengo PC, Server ecc...

Negli ultimi giorni ho testate due semplicissime automazioni:

```yaml
### Accensione Auto
  - id: b74d0aba-cd1c-11eb-b8bc-0242ac130003
    alias: Clima - Daikin Studio - Auto_ON
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.daikin_studio_inside_temperature
        above: '27.9'
        for: 
          minutes: 15
    action:
      - service: notify.casa
        data:
          message: |
            ❄️
            In studio ci sono {{ states('sensor.daikin_studio_inside_temperature') | round(1) }}°, accendo il clima
          data:
            inline_keyboard:
              - 'ℹ️ Info Studio:/info_studio, ✖️ Spegni Clima:/spegni_clima_studio'
      - service: script.turn_on
        entity_id: script.daikin_cool_studio

### Spegnimento Auto
  - id: d4567d14-2f65-4cdb-986a-dc1f219fec6b
    alias: Clima - Daikin Studio - Auto_OFF
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.daikin_studio_inside_temperature
        below: '27.1'
        for: 
          minutes: 10
    action:
      - service:  climate.turn_off
        data:
          entity_id:
            - climate.daikin_studio
      - service: notify.casa
        data:
          message: |
            ❄️
             Spengo il clima in studio, temperatura attuale: {{ states('sensor.daikin_studio_inside_temperature') | round(1) }}°
```

> Le notifiche Telegram sono temporanee ed utilizzate allo scopo di tenere d'occhio l'andamento del clima in questi giorni di test.

Arrivo al dunque, ovvero le mie due principali domande:

1. La stanza in questione è sostanzialmente un sottotetto, di conseguenza in questo periodo di test ho notato che raggiunge la temperatura target ogni circa due ore. Ho già alzato la temperatura di mezzo grado, senza risultati evidenti. Considerando che comunque è una stanza poco frequentata di giorno, far attivare il clima ogni due ore per circa 20 minuti (tempo generalmente necessario per tornare ai 27°) mi pare eccessivo. Esiste un modo per mantenere inalterata la logica dell'automazione "forzando" un tempo minimo durante il quale non si può triggerare nuovamente?
2. Come si può gestire la situazione in cui il clima viene acceso manualmente? Intendo nel caso in cui qualcuno sia fisicamente nella stanza e decida di accenderlo. Il problema si presenta nel momento in cui la stanza raggiunge la temperatura target della seconda automazione, spegnendo il climatizzatore. Come potrei far si che le automazioni vengano disabilitate solo in questa situzione? 

Grazie a tutti in anticipo!

**Comment by maxcanna** [comment]
Sono di corsa e dal cellulare ma le entità `automation ` hanno tra gli attributi l'ultima volta che sono scattate. Puoi usarla come `condition`  o combinarla nel `trigger`

**Reply by NdR91** [reply]
Grazie Max, non sapevo di questo attributo. Guardo subito!

**Reply by NdR91** [reply]
Ok, forse ho trovato una soluzione al mio Punto "1":

```yaml
  - id: b74d0aba-cd1c-11eb-b8bc-0242ac130003
    alias: Clima - Daikin Studio - Auto_ON
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.daikin_studio_inside_temperature
        above: '27.9'
        for: 
          minutes: 15
    condition:
      - condition: template
        value_template: >
          {% set last_triggered = states.automation.clima_daikin_studio_gestione_auto.attributes.last_triggered %}
          {{ last_triggered is none or
            (as_timestamp(now()) - as_timestamp(last_triggered )) | int > 14400 }}
    action:
      - service: notify.casa
        data:
          message: |
            ❄️
            In studio ci sono {{ states('sensor.daikin_studio_inside_temperature') | round(1) }}°, accendo il clima
          data:
            inline_keyboard:
              - 'ℹ️ Info Studio:/info_studio, ✖️ Spegni Clima:/spegni_clima_studio'
      - service: script.turn_on
        entity_id: script.daikin_cool_studio
    # --------------------------------------------------------
```

In teoria, con questa condizione, l'automazione triggera solo se l'automazione ha come attributo "last_triggered" "none" o "maggiore di 4 ore".

Cosa ne pensi?

**Reply by maxcanna** [reply]
Metti un `default` al filtro `int` per evitare il check di valore mancante 😉. 

A parte questo vedi tu se usare l'attributo come condition o in and nel trigger

**Reply by NdR91** [reply]
Scusami Max, come dovrei impostarlo ```default```?

**Reply by maxcanna** [reply]
Una cosa tipo
```
as_timestamp(last_triggered )) | int(default=14400) >= 14400
```

così in assenza di valore restituisce `14400` che, grazie al `>=` farà scattare l'automazione

**Reply by NdR91** [reply]
Top grazie 1000!

**Comment by RobyBS** [comment]


**Reply by maxcanna** [reply]
- non rispondere ad un post già esistente
- usa il markdown

**Reply by RobyBS** [reply]
ok .. grazie per il suggerimento ...

**Comment by 2Max2Pax** [comment]
Ciao,
Ho scopiazzato la tua per realizzare la mia prima automazione ma non riesco a farla funzionare , ovviamente ho sbagliato qualcosa

```
alias: TestTemperauraStudio
description: hass:fire
trigger:
  - platform: numeric_state
    entity_id: sensor.rm4mini01_temperature
    above: '25'
condition:
  - condition: time
    after: '17:00:00'
    before: '23:59:59'
  - condition: or
    conditions:
      - condition: time
        after: '00:00:01'
        before: '04:30:00'
action:
  - service: notify.mobile_app_iphone_di_massimiliano
    data:
      message: >-
        ❄️ In studio ci sono {{ states('sensor.rm4mini01_temperature') |
        round(1) }}°
  - wait_template: ''
    continue_on_timeout: true
    timeout: '5'
mode: single

```

Se testo con `RUN ACTIONS` ricevo il messaggio. Gli script per la gestione del climatizzatore, che non ho ancora inserito nell'automazione, funzionano.

**Reply by snakuzzo** [reply]
Vuol dire che hai sbagliato o il trigger o la condition. E guardando il codice che hai postato quasi sicuramente hai sbagliato la condition. Per come l'hai scritta quelle condition sono in AND e non in OR, per cui non verrà mai eseguita la action. La composizione delle due condition in OR è diversa da come l'hai scritta. Inoltre non ho capito perché usi quel `wait_template`.
Ad ogni modo...

```yaml
alias: TestTemperauraStudio
description: hass:fire
trigger:
  - platform: numeric_state
    entity_id: sensor.rm4mini01_temperature
    above: '25'
condition:
  - condition: or
    - condition: time
      after: '17:00:00'
      before: '23:59:59'
    - condition: time
      after: '00:00:01'
      before: '04:30:00'
action:
  - service: notify.mobile_app_iphone_di_massimiliano
    data:
      message: >-
        ❄️ In studio ci sono {{ states('sensor.rm4mini01_temperature') | round(1) }}°
  - wait_template: ''
    continue_on_timeout: true
    timeout: '5'
mode: single
```

**Comment by 2Max2Pax** [comment]
Ho semplificato ulteriormente,
Anche così non funziona

```
id: '1628337807265'
alias: temperaturaStudio
description: ''
trigger:
  - platform: numeric_state
    entity_id: sensor.rm4mini01_temperature
    above: 20
condition: []
action:
  - service: notify.notify
    data:
      message: studio caldo
mode: single

```
Ho provato anche con l'entità `sensor.glances_battery_charge ` con trigger below: 95. Anche questa non funziona.

Mi è forse sfuggita qualche opzione che disabilita le automazioni?
