### DISCUSSION TITLE
Alimentazione Raspberry

### DISCUSSION THREAD

**Discussion by gideonklein** [indomus/forum#458] [HUB: Home Assistant]
Vorrei fare una automazione che mi avverta se il raspberry ha una cattiva alimentazione. Mi dava problemi con il l'UPS che è di 2A, con il suo alimentatore da 3A è tutto apposto ma vorrei appunto creare ugualmente un'automazione che mi avvertisse se ci fossero problemi.
Ecco l'automazione che ho fatto ma che non funziona:

```
  alias: RPi Power status Notifica cattiva alimentazione
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.rpi_power_status
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      message: ATTENZIONE! CATTIVA ALIMENTAZIONE DEL RASPBERRY
  mode: single
```

**Comment by snakuzzo** [comment]
Correggi il post ed usa il markdown, altrimenti dovrò cancellare.
Leggi il [REGOLAMENTO](https://github.com/indomus/forum/blob/main/README.md)

Grazie

**Reply by snakuzzo** [reply]
No...devi usare il markdown.
Correggi per favore

**Reply by gideonklein** [reply]
Ho provato nel modo descritto usando il tastino <> e non funziona

**Comment by gideonklein** [comment]
Ecco il risultato

`  alias: RPi Power status Notifica cattiva alimentazione
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.rpi_power_status
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      message: ATTENZIONE! CATTIVA ALIMENTAZIONE DEL RASPBERRY
  mode: single`

**Reply by snakuzzo** [reply]
Edita...seleziona tutto il blocco di codice e poi clicchi sul tastino...
i backtick ad inizio e fine devono essere 3 e non 1

**Reply by gideonklein** [reply]
```
  alias: RPi Power status Notifica cattiva alimentazione
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.rpi_power_status
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      message: ATTENZIONE! CATTIVA ALIMENTAZIONE DEL RASPBERRY
  mode: single
```

**Reply by gideonklein** [reply]
così va bene?

**Reply by snakuzzo** [reply]
ora è ok

**Reply by snakuzzo** [reply]
Tornando alla domanda iniziale... che vuol dire "NON FUNZIONA" ?
Il sensore `binary_sensor.rpi_power_status` quando diventa on ?

**Reply by gideonklein** [reply]
Si è proprio questo il dubbio credo che non sia corretto on e off. Cambia stato da OK a PROBLEMI quando non ha sufficiente ampere, ma non so come settarlo

**Reply by gideonklein** [reply]
![Cattura3](https://user-images.githubusercontent.com/79428290/123066606-7f957a80-d410-11eb-9f06-6e3529355cff.PNG)

**Reply by gideonklein** [reply]
Voglio dire che non so che trigger dare nell'automazione e come cambia di stato

**Reply by snakuzzo** [reply]
hai sbagliato proprio l'entità...è un `sensor` e non un `binary_sensor`

```yaml
- id: rpi_power_status
  alias: RPi Power status Notifica cattiva alimentazione
  trigger:
  - platform: state
    entity_id: sensor.rpi_power_status
    to: "PROBLEMI"
  action:
  - service: notify.persistent_notification
    data:
      message: "ATTENZIONE! CATTIVA ALIMENTAZIONE DEL RASPBERRY"
```

**Reply by gideonklein** [reply]
Ho provato ma io non ho proprio il sensore, ho il sensore binario solo. Se cerco sensor.rpi_power_status nopn lo trova ma trova solo il sensore binario binary_sensor.rpi_power_status

**Reply by snakuzzo** [reply]
Il sensore binario ha due stati ... ON e OFF ... non può avere stato PROBLEMI.
Devi capire quel sensore in che condizioni è ON e in che condizioni è OFF...ma questo devi saperlo tu ed in base a quello modifichi l'automazione

**Reply by snakuzzo** [reply]
Ho dato un'occhiata al [CODICE](https://github.com/home-assistant/core/blob/6c4816567ca735c9e85f42760e98f7cef43393c9/homeassistant/components/rpi_power/binary_sensor.py#L61) dell'integrazione [Raspberry Pi Power Supply Checker](https://www.home-assistant.io/integrations/rpi_power/). Se non ho visto male, quando passa ad `"on"` dovrebbe indicarti che c'è un problema.
Quindi...

```yaml
- id: rpi_power_status
  alias: RPi Power status Notifica cattiva alimentazione
  trigger:
  - platform: state
    entity_id: binary_sensor.rpi_power_status
    to: "on"
  action:
  - service: notify.persistent_notification
    data:
      message: "ATTENZIONE! CATTIVA ALIMENTAZIONE DEL RASPBERRY"
```

**Reply by gideonklein** [reply]
Ah bene grazie, più tardi lo provo e ti faccio sapere

**Reply by gideonklein** [reply]
Ho provato e non funziona, non manda la notifica. Ho provato anche cambiando anche "on" con "Problema" ma non funziona lo stesso
![CatturaAAA](https://user-images.githubusercontent.com/79428290/123074834-f41fe780-d417-11eb-9a97-adf16b875e93.PNG)

**Reply by gideonklein** [reply]
Nell'automazione su mostra traccia non c'è traccia che l'automazione è partita. Si trova la traccia solo se la eseguo manualmente

**Reply by snakuzzo** [reply]
l'automazione è corretta...non so che dirti.
Controlla i log

**Reply by snakuzzo** [reply]
Ricorda che l'automazione scatta solo se il binary_sensor passa da un qualsiasi stato ad on.
Se è già on, non scatta

**Reply by gideonklein** [reply]
ah ecco allora sarà questo, perchè appena metto l'alimentazione a 2A e faccio partire il raspberry, home assistant si avvia già in condizione di on. Quindi funziona ma non può mai partire in questo modo. Allora se è corretta lascio così. Grazie davvero

**Reply by snakuzzo** [reply]
Volendo potresti fare in modo che scatti anche allo start di HA

```yaml
- id: rpi_power_status
  alias: RPi Power status Notifica cattiva alimentazione
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: binary_sensor.rpi_power_status
    to: "on"
  condition:
    condition: state
    entity_id: binary_sensor.rpi_power_status
    state: "on"
  action:
  - service: notify.persistent_notification
    data:
      message: "ATTENZIONE! CATTIVA ALIMENTAZIONE DEL RASPBERRY"
```

**Reply by gideonklein** [reply]
Grazie. Ma così forse si attiva solo quando si restarta home assistant? Ho capito bene? Oppure l'automazione parte sia quando si restart il sistema che quando ha problemi di amperaggio? Perchè a me servirebbe ricevere una notifica solo se il trasformatore o la batteria ups ha problemi e non eroghi abbastanza ampere (ad esempio la power bank sta per scaricarsi e comincia a diminuire l'amperaggio). Quindi dovrebbe scattare al momento di problemi di alimentazione e non quando faccio restart

**Reply by gforment** [reply]
Ciao, questo il mio con alert su Telegram quando cambia stato (quando ha problemi e quando torna a funzionare correttamente).

```
  ##############################################################
  ## Power status problem
  ##############################################################
  - id: rpi_power_status
    alias: Infra - Raspberry PI power status
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.rpi_power_status
    condition: []
    action:
    - service: notify.telegram
      data:
        message: ⚠️RPI Power status {{states('binary_sensor.rpi_power_status')}}
    mode: single
```
