### DISCUSSION TITLE
URL interno down

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#465] [HUB: Home Assistant]
Il link con DuckDNS funziona perfettamente su una porta diversa da 8123, ma il mio URL interno no.  L'URL interno impostato in Impostazioni Generali con https è invece sulla porta 8123. Questa la configurazione per duckdns che ho attualmente:
```
duckdns:
  domain: !secret access_domain 
  access_token: !secret access_token

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
```
Devo impostare qualcos'altro ?
