### DISCUSSION TITLE
Automazione con messaggio personalizzato

### DISCUSSION THREAD

**Discussion by gideonklein** [indomus/forum#467] [HUB: Home Assistant]
Buongiorno a tutti,
ho creato questa automazione che funziona. Vorrei ora personalizzare il messaggio. Anzichè il testo prescelto e statico vorrei che in automatico mi desse il messaggio con il nome del sensore che ha scatenato l'evento. Il sensore sensor.ultimo_evento_7 è quello che ho ricavato dallo script dell'allarme casa sicura, di cui mi funziona armo e disarmo e appunto gli eventi
Potete aiutarmi?

```
- id: '1621671452684'
  alias: TEST Eventi Casasicura
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ultimo_evento_7
    attribute: messaggio
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      message: Test
  - service: notify.telegram
    data:
      message: Test
```

**Comment by gideonklein** [comment]
I sensori eventi hanno degli attributi (sensore data e messaggio), volevo appunto poter avere come messaggio personalizzato il sensore. Allego screen
![Cattura4](https://user-images.githubusercontent.com/79428290/123242872-bdfb6a00-d4e2-11eb-9364-59620cd6b6c0.PNG)

**Reply by 50494554524F** [reply]
message: "{{ state_attr(trigger.entity_id,'Sensore') }}"

**Reply by gideonklein** [reply]
Grazie, mi dà questo errore:

Error rendering data template: UndefinedError: 'dict object' has no attribute 'entity_id'

**Reply by gideonklein** [reply]
```
- id: '1621671452684'
  alias: TEST Eventi Casasicura
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ultimo_evento_7
    attribute: messaggio
  condition: []
  action:
  - service: persistent_notification.create
    data:
      message: "{{ state_attr(trigger.entity_id,'Sensore') }}"
  - service: notify.telegram
    data:
      message: "{{ state_attr(trigger.entity_id,'Sensore') }}"
```

**Reply by 50494554524F** [reply]
prova un po'... (questo non è generico ricordati di cambiare lo script sei fai modifiche a entity_id)

message: "{{ state_attr( 'sensor.ultimo_evento_7','Sensore') }}"

**Reply by gideonklein** [reply]
ancora errore:
template value is None for dictionary value @ data['message']

Cosa intendi dire con cambiare lo script se faccio modifichea entity_id? Che modifiche dovrei fare?

**Reply by gideonklein** [reply]
Allora ho tolto la notifica a Telegram e ora non mi da errore ma come notifica su HA mi dà:
message: "None"

**Reply by gideonklein** [reply]
Triggered manually at 24 giugno 2021, 20:09:56
Call service persistent_notification.create
Finished at 24 giugno 2021, 20:09:56 (runtime: 0.02 seconds)

**Reply by gideonklein** [reply]
Dopo mille prove ora non fa errori nemmeno con telegram e arriva il messaggio ma funziona perchè ho aggiunto delle virgolette in più 3 anzichè 2 all'inizio e alla fine:
  message: '''{{ state_attr(''sensor.ultimo_evento_7'',''Sensore'') }}'''

Il problema è sempre che come messaggio è sempre 'None'

**Reply by snakuzzo** [reply]
Non serve a niente mettere apici e doppi apici...non pasticciare in questo modo!
Ho creato un'automazione di prova al volo sulla mia istanza...e funziona perfettamente...

```yaml
automation:

- id: 'prova'
  alias: Prova
  trigger:
  - platform: state
    entity_id: binary_sensor.finestra_soggiorno_01
    to: 'on'
  action:
  - service: persistent_notification.create
    data:
      title: "Prova"
      message: "{{ state_attr(trigger.entity_id,'device_class') }}"
```

![image](https://user-images.githubusercontent.com/7205371/123323656-1a3ba980-d536-11eb-88ea-8f88f46b2381.png)

**Reply by snakuzzo** [reply]
vedi bene con i dev tools > template come si chiama l'attributo che stai estraendo.

![image](https://user-images.githubusercontent.com/7205371/123323546-ed879200-d535-11eb-96b0-099fec74e794.png)

**Reply by gideonklein** [reply]
Grazie, ma forse non funziona con me perchè i miei sensori finestre e pir non sono rilevati. Mi funzionano solo invece gli eventi (ultimo, penultimo e terzultimo) mi dico quali pir e sensori finestre si sono attivati ma i sensori non funzionano. Quindi devo usare per forza il mio sensore degli eventi: sensor.ultimo_evento_7

**Reply by gideonklein** [reply]
Io ho questo:
![Cattura5](https://user-images.githubusercontent.com/79428290/123327018-380b0d80-d53a-11eb-960c-a881ff248cce.PNG)

**Reply by snakuzzo** [reply]
Quindi giusto che ti restituisca None visto che "Sensore" non è un attributo di quella entità

**Reply by gideonklein** [reply]
E quale sarebbe l'attributo? Io ho messo anche "data" e "messaggio", ma anche "message" e anche "Messaggio" con la m maiuscola ma mi restituisce sempre None. Ovviamente faccio sempre il riavvio sempre delle automazioni

**Reply by snakuzzo** [reply]
usa i dev tools come ti ho fatto vedere io

`{{ states.sensor.ultimo_evento_7.attributes }}`

e vedi quali sono gli attributi...che corrisponderanno all'ultima immagine che hai postato

**Reply by gideonklein** [reply]
mi esce questo:

```
{
  "data": "2021-06-24 22:22:04",
  "messaggio": "Allarme Cancellato",
  "friendly_name": "Ultimo evento",
  "icon": "mdi:security"
}
```

**Reply by gideonklein** [reply]
Da non crederci ora mi funziona, ho riavviato più volte, ho messo e tolto : dopo messaggio e ora funziona e manda entrambi i messaggio in HA e telegram
![Cattura7](https://user-images.githubusercontent.com/79428290/123333497-1e6dc400-d542-11eb-882b-fcb5794adb16.PNG)

**Reply by snakuzzo** [reply]
avrai scritto qualcosa di sbagliato e non te ne sarai accorto ;)

**Reply by gideonklein** [reply]
ecco il codice:

```
- id: '1621671452684'
  alias: TEST Eventi Casasicura
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ultimo_evento_7
    attribute: messaggio
  condition: []
  action:
  - service: persistent_notification.create
    data:
      message: '''{{ state_attr(''sensor.ultimo_evento_7'',''messaggio'') }}'''
  - service: notify.telegram
    data:
      message: '''{{ state_attr(''sensor.ultimo_evento_7'',''messaggio'') }}'''
  mode: single
```
