### DISCUSSION TITLE
Monitorare aggiornamento dati sensore

### DISCUSSION THREAD

**Discussion by akela-it** [indomus/forum#47] [HUB: Home Assistant]
Salve a tutti! Oggi ho trovato lo Shelly EM per il controllo dei consumi elettrici bloccato, in pratica non inviava dati da giorni. Mi è bastato spegnerlo e riaccenderlo per riattivare il controllo dei consumi. Esiste un modo (uno script, un modello...) per controllare che un sensore invii un aggiornamento dei dati entro e non oltre un certo tempo?

**Comment by KC-inDomus** [comment]
beh potresti usare l'attributo last update delle entità che ricevono i dati e dal lì farti notificare la cosa. strano però che si blocchi,
più che altro

**Reply by akela-it** [reply]
Ottimo suggerimento!

Scrivo per i posteri l'automazione che ho scritto:

```
alias: Notifica misure energia non inviate
description: Notifica se Shelly EM non invia dati da più di 30 minuti
trigger:
  - platform: template
    value_template: >
      {% set duration_minutes = 30 %}  
      {% set last_changed_seconds = as_timestamp(states.sensor.shelly_em.last_updated) %}  
      {% set current_time_seconds =  as_timestamp(strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M')) %} 
      {{ last_changed_seconds + duration_minutes * 60 < current_time_seconds }}
condition: []
action:
  - service: notify.me
    data:
      title: Notifica Consumi
      message: La sonda Shelly EM non invia dati da più di 30 minuti
mode: single
```
Per modificare i minuti entro i quali essere informati modificare questa riga {% set duration_minutes = 30 %}
Sostituire il nome del sensore "sensor.shelly_em" con il proprio nella riga {% set last_changed_seconds = as_timestamp(states.sensor.shelly_em.last_updated) %}
