### DISCUSSION TITLE
Garbage collection: limitazione di due giorni per tipo di sensore???

### DISCUSSION THREAD

**Discussion by Vinz1985** [indomus/forum#471] [HUB: Home Assistant]
Buongiorno volevo porre alla vostra cortese attenzione un problema che mi si sta verificando nell'implementazione della gestione dei rifiuti tramite il componente garbage collection.  In teoria mi funziona tutto ma mi sono accorto di una cosa, non riesco a inserire  più di due giorni per tipo di raccolta. Nella fattispecie , nel mio comune, la raccolta dell'umido avviene 3 giorni a settimana (Lunedi, Mercoledi,Sabato) ma me ne conteggia solo 2, in qualunque ordine metta l'elenco. 
Mi manca qualche opzione oppure l'addon è fatto con una limitazione per massimo 2 ritiri per raccolta?

Allego il codice del garbage_collection.yaml 

```
sensors:
  - name: raccolta_indifferenziata
    frequency: "odd-weeks"
    collection_days:
    - mon

  - name: raccolta_umido
    frequency: "weekly"
    collection_days:
    - fri
    - sun
    - tue
    
  - name: raccolta_carta
    frequency: "odd-weeks"
    collection_days:
    - thu
  - name: raccolta_plastica
    frequency: "weekly"
    collection_days:
    - wed

  - name: raccolta_vetro
    frequency: "even-weeks"
    collection_days:
    - mon
```

e come si può vedere di seguito le entità fungono a dovere ma nel calendario non appare il terzo giorno dell'umido

![Nuova immagine bitmap](https://user-images.githubusercontent.com/83169955/123451851-2bd88c00-d5de-11eb-8795-3ec6c2aee353.jpg)

Come posso risolvere senza effettuare brutture (tipo fare un sensore aggiuntivo tipo sensore_umido2)? Grazie 1000
