### DISCUSSION TITLE
Shelly roller

### DISCUSSION THREAD

**Discussion by manustars** [indomus/forum#481] [HUB: Home Assistant]
Salve a tutti, ho un piccolo problema, ho configurato 2 shelly 2.5 per le tapparelle via mqtt, e fino a qui tutto ok, solo che ho impostato position open al 95 e il close a 10/12, ma quando do il comando via googlehome, queste configurazioni non vengono prese in considerazione.

```yaml
  - platform: mqtt
    name: Tapparella Salone
    command_topic: "shellies/shellyswitch25-TAPPSALONE/roller/0/command"
    position_topic: "shellies/shellyswitch25-TAPPSALONE/roller/0/pos"
    set_position_topic: "shellies/shellyswitch25-TAPPSALONE/roller/0/command/pos"
    availability_topic: "shellies/shellyswitch25-TAPPSALONE/online"
    payload_available: "true"
    payload_not_available: "false"
    qos: 1
    retain: false
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
    position_open: 95
    position_closed: 12
```
