### DISCUSSION TITLE
Cancellare backup in cartella remota tramite HA

### DISCUSSION THREAD

**Discussion by gideonklein** [indomus/forum#483] [HUB: Home Assistant]
Buongiorno a tutti. Nuova richiesta di aiuto.
Ho una webcamera reolink integrata su home assistant e faccio i backup delle registrazioni via ftp in una cartella di sito di mia proprietà tramite pannello reolink (www.miosito.com/backup). Il problema è che devo svuotarla ogni settimana o mese manualmente altrimenti diventa enorme e lo spazio che ho a disposizione finisce. Ecco la domanda: Si potrebbe creare uno script tramite Home Assistant che cancelli periodicamente i video di backup più vecchi?
Grazie

**Comment by snakuzzo** [comment]
Sì...fatti uno script shell e lo richiami da HA con uno `shell_command `

**Reply by gideonklein** [reply]
Grazie. Sono arrivato a configurare .yaml e fare un'automazione ma di esempio ma non so cosa mettere nel comando. Faccio copia e incolla

```
# Exposes service shell_command.delete_backup
shell_command:
  delete_backup: #CHE COMANDO METTERE?


# Esempio automazione
- id: '1625065693296'
  alias: Delete backup ftp
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: shell_command.delete_backup
  mode: single
```
