### DISCUSSION TITLE
battery level netatmo

### DISCUSSION THREAD

**Discussion by essegi65** [indomus/forum#508] [GENERALE - Discussioni generiche]
ciao a tutti.
avevo usato questo sensore nel file di configurazione 
 ``` 
- platform: template
    sensors:
      batteria_netatmo_soggiorno:
        friendly_name: 'Batteria Netatmo'
        value_template: "{{ state_attr('climate.netatmo_soggiorno', 'battery_level') }}"
        device_class: battery
```
per avere il livello della batteria del termostato netatmo, ma dall'ultimo aggiornamento mi rende valore "sconosciuto", ho provato a vedere su internet ma le soluzioni che ho trovato, poche a dire la verità, non funzionano.
Qualcuno riesce a aiutarmi?
Grazie

**Comment by Marcellino78** [comment]
Non credevo di avere lo stato della batteria del netatmo...... ho fatto una prova copiando il tuo codice, ma non va perche ha un errore di formattazione, altrimenti funziona.

- platform: template
   sensors:
     batteria_netatmo_soggiorno:
       friendly_name: 'Batteria Netatmo'
       value_template: "{{ state_attr('climate.netatmo_soggiorno', 'battery_level') }}"
       device_class: battery

**Reply by essegi65** [reply]
Se usi i "markdown" riesco a vedere dov'è l'errore di formattazione, così non riesco e non mi sembra di vedere un errore di formattazione.
Grazie

**Reply by Marcellino78** [reply]
```
- platform: template
  sensors:
     batteria_netatmo_soggiorno:
       friendly_name: 'Batteria Netatmo'
       value_template: "{{ state_attr('climate.termostato_netatmo', 'battery_level') }}"
       device_class: battery

```
