### DISCUSSION TITLE
SOLVED: GARBAGE COLLECTION NOTIFICA TTS

### DISCUSSION THREAD

**Discussion by jimborm** [indomus/forum#51] [HUB: Home Assistant]
Ciao a tutti sto provando ad adattare la notifica su google home dell'esposizione del mastello di indifferenziata adottando il componente indicato qui https://indomus.it/progetti/gestire-la-raccolta-differenziata-tramite-la-domotica-home-assistant/
Non sono espertissimo comunque ho seguito le indicazioni dell'articolo ma il mio assistente non ne vuole sapere di parlare. Posto qui di seguito la mia conf di automazione.yaml:
```
- alias: "Notifica tts ritiro mastello"
  trigger:
    - platform: numeric_state
      entity_id: sensor.organico
      value_template: "{{ state.attributes.days }}"
      below: 1
    - platform: numeric_state
      entity_id: sensor.carta
      value_template: "{{ state.attributes.days }}"
      below: 1
    - platform: numeric_state
      entity_id: sensor.vetro_metallo
      value_template: "{{ state.attributes.days }}"
      below: 1
    - platform: numeric_state
      entity_id: sensor.indifferenziata
      value_template: "{{ state.attributes.days }}"
      below: 1
    - platform: numeric_state
      entity_id: sensor.plastica
      value_template: "{{ state.attributes.days }}"
      below: 1
  condition: [ ]
  action:
    service: tts.google_say
    data_template:
      entity_id: media_player.seminterrato
      message: "Attenzione: domani è giorno di ritiro frazione {{ trigger.from_state.attributes.friendly_name }}."
```
sensor.yaml
```
- platform: garbage_collection
  name: "Indifferenziata"
  frequency: "weekly"
  verbose_state: true
  collection_days:
  - tue
- platform: garbage_collection
  name: "Organico"
  frequency: "weekly"
  verbose_state: true
  collection_days:
  - mon
  - wed
  - sat
- platform: garbage_collection
  name: "Vetro_Metallo"
  frequency: "weekly"
  verbose_state: true
  collection_days:
  - sat
- platform: garbage_collection
  name: "Carta"
  frequency: "weekly"
  verbose_state: true
  collection_days:
  - fri
- platform: garbage_collection
  name: "Plastica"
  frequency: "weekly"
  verbose_state: true
  collection_days: 
  - thu
```
Sapreste dirmi cosa sbaglio?

**Comment by snakuzzo** [comment]
L'automazione è sintatticamente ok.
Se ti limiti a dire "non funziona" è difficile aiutarti.

1. L'entità media player funziona (a prescindere da questa automazione) ? Riesci a "farla parlare" in qualche modo ? Nel caso prova a fargli dire qualcosa utilizzando i dev tools sotto `Configuration > Developer Tools > Services` e fai sapere se parla o se comunque hai dei messaggi di errore in basso

2. Devi postare i dettagli...ad esempio il log di HA quando viene eseguita l'automazione

**Reply by jimborm** [reply]
Ciao Diego hai ragione sorry non imparerò mai. Allora lo speaker funziona; riesco a farlo parlare sia con la modalità che mi hai indicato che con altri script o dall'interfaccia web. il log di Home Assistant invece è questo
<img width="1760" alt="errore" src="https://user-images.githubusercontent.com/52866001/112755778-8c0d6100-8fe2-11eb-8633-43c491542798.png">

**Reply by snakuzzo** [reply]
Hai per caso scatenato l'automazione a mano ?
Se la esegui a mano non funzionerà mai e come vedi dal log l'oggetto trigger non è definito...non esiste.
Se usi l'oggetto trigger devi fare in modo che scatti con un trigger (quelli che hai indicato nell'automazione)

**Reply by jimborm** [reply]
Ciao Diego ho provato a creare questo script e eseguirlo manualmente e funziona ovvero google home mi dice esattamente quanti giorni mancano al ritiro del mastello
```
prova_tts:
  alias: prova tts
  sequence:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.seminterrato
      volume_level: 0.5
  - service: tts.google_say
    data_template:
      entity_id: media_player.seminterrato
      message: "Attenzione: il vetro e metallo passa tra {{ state_attr('sensor.vetro_metallo','days') }}.giorni"
      language: 'it'
```

Fatto ciò visto che il mio obiettivo finale è di avere una o più automazioni che ad un orario specifico del giorno mi dichino quale mastello esporre per il ritiro della mattina successiva, ho voluto provare a creare un automazione (la condizione l'ho presa da questo post [https://spectrum.chat/indomus/home-assistant/automation-condition~a5406cf5-821a-4573-9cf8-989fea439abb](url). Per provarla ho commentato il trigger cosi da farla funzionare ad ogni esecuzione.

```
- alias: "Notifica tts ritiro mastello2"
  trigger: [ ]
    #platform: time
    #at: '17:28:00'
  condition:
    condition: template
    value_template: "{{ state_attr('sensor.vetro_metallo','days') > 0 and state_attr('sensor.vetro_metallo','days') < 2 }}"
  action:
    service: tts.google_say
    data_template:
      entity_id: media_player.seminterrato
      message: "Attenzione: domani è giorno di ritiro frazione {{ state_attributes.friendly_name }}."
      #message: "Buonasera ricordiamoci i rifiuti"
      language: 'it'
```
Il risultato è che il messaggio "Buonasera ricordiamoci i rifiuti" viene detto mentre quello sopra (se inverto il # ai messaggi) non viene detto dallo speaker e nei log vedo questo errore:

```
2021-05-01 18:24:27 INFO (MainThread) [homeassistant.components.automation.notifica_tts_ritiro_mastello2] Notifica tts ritiro mastello2: Running automation actions
2021-05-01 18:24:27 INFO (MainThread) [homeassistant.components.automation.notifica_tts_ritiro_mastello2] Notifica tts ritiro mastello2: Executing step call service
2021-05-01 18:24:27 ERROR (MainThread) [homeassistant.components.automation.notifica_tts_ritiro_mastello2] Notifica tts ritiro mastello2: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'state_attributes' is undefined
2021-05-01 18:24:27 ERROR (MainThread) [homeassistant.components.automation.notifica_tts_ritiro_mastello2] Error while executing automation automation.notifica_tts_ritiro_mastello2: Error rendering data template: UndefinedError: 'state_attributes' is undefined
```

Cosa sbaglio?

**Reply by snakuzzo** [reply]
Hai sbagliato il template nel `message`. Cos'è `state_attributes` ? E' un oggetto che non esiste,
Credo tu debba usare...

```
message: "Attenzione: domani è giorno di ritiro frazione {{ state_attr('sensor.vetro_metallo','friendly_name') }}"
```

Ad ogni modo secondo me è sbagliato implementare più automazioni per una cosa del genere. Dovresti fare in modo di implementare un'UNICA automazione

**Reply by Scialla** [reply]
manca anche il trattino al service nella action...

**Reply by jimborm** [reply]
Grande !!! la correzione funziona (non avevo dubbi). 
Effettivamente lo step successivo sarebbe quello di provare a fare una automazione unica quindi in sostanza dovrei fare una cosa di questo tipo:
(trigger)    alle otto di sera
(condition)  la stessa condizione che ho già creato solo ripetuta per ogni sensore della raccolta differenziata in CONDIZIONE OR tra loro
(action)   fai dire a google il messaggio del mastello da esporre

Che ne dici ? Dovrebbe andare ragionata cosi?

**Comment by 88Marius88** [comment]
Seguo anche io questo topic per caso e stato risolto?

**Reply by jimborm** [reply]
no non ho avuto più feedback purtroppo.

**Reply by jimborm** [reply]
Ciao ho fatto altre prove sull'automazione scatta correttamente all'orario indicato ma da errore nel rendering :
```
- alias: "Notifica tts ritiro mastello"
  initial_state: true
  trigger:
    - platform: time
      at: '17:41:00'
    - platform: numeric_state
      entity_id: sensor.organico
      value_template: "{{ state.attributes.days }}"
      below: 1
    - platform: numeric_state
      entity_id: sensor.carta
      value_template: "{{ state.attributes.days }}"
      below: 1
    - platform: numeric_state
      entity_id: sensor.vetro_metallo
      value_template: "{{ state.attributes.days }}"
      below: 1
    - platform: numeric_state
      entity_id: sensor.indifferenziata
      value_template: "{{ state.attributes.days }}"
      below: 1
    - platform: numeric_state
      entity_id: sensor.plastica
      value_template: "{{ state.attributes.days }}"
      below: 1
  condition: [ ]
  action:
    service: tts.google_say
    data_template:
      entity_id: media_player.seminterrato
      message: "Attenzione: domani è giorno di ritiro frazione {{ trigger.state.attributes.friendly_name }}."
 ```
l'errore che vedo nel log è:
 ```
2021-09-05 17:52:00 INFO (MainThread) [homeassistant.components.automation.notifica_tts_ritiro_mastello] Notifica tts ritiro mastello: Running automation actions
2021-09-05 17:52:00 INFO (MainThread) [homeassistant.components.automation.notifica_tts_ritiro_mastello] Notifica tts ritiro mastello: Executing step call service
2021-09-05 17:52:00 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'state' when rendering 'Attenzione: domani è giorno di ritiro frazione {{ trigger.state.attributes.friendly_name }}.'
2021-09-05 17:52:00 ERROR (MainThread) [homeassistant.components.automation.notifica_tts_ritiro_mastello] Notifica tts ritiro mastello: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'dict object' has no attribute 'state'
2021-09-05 17:52:00 ERROR (MainThread) [homeassistant.components.automation.notifica_tts_ritiro_mastello] Error while executing automation automation.notifica_tts_ritiro_mastello: Error rendering data template: UndefinedError: 'dict object' has no attribute 'state'
 ```

Qualcuno Sto arrivando! indicarmi come posso estrarre il nome del sensore per farlo dire allo speaker?

**Reply by 88Marius88** [reply]
Ciao , io ho risolto diversamente . Ed ora funziona tutto .

**Reply by jimborm** [reply]
Posso sapere come?

**Reply by 88Marius88** [reply]
Ho aggiunto automazioni con l'ora in cui voglio che faccia il controllo. Domani posso metterti il codice da me inserito. Se vuoi .

**Reply by xyzmauro** [reply]
Trigger non ha attributo state come ti suggerisce l’errore, devi usare trigger.to_state o trigger.from_state,ad esempio 
"{{ trigger.to_state.attributes.friendly_name }}"

**Reply by xyzmauro** [reply]
Cmq messi così i trigger l’automazione scatterà si all’ora che hai impostato tu ma ANCHE se l’attributo days del sensor va a 0, se questo succede a mezzanotte come immagino la notifica avverrà a quell’ora 🤔

**Reply by jimborm** [reply]
purtroppo ho lo stesso errore anche se metto `"{{trigger.to_state.attributes.friendly_name }}"` o `"{{ trigger.from_state.attributes.friendly_name }}"`.

**Reply by xyzmauro** [reply]
Ma come la stai testando questa automazione? Perché se la esegui a mano è normale che non abbia il trigger perché esegue solo le action…

**Reply by jimborm** [reply]
modifico l'orario
```
  trigger:
    - platform: time
      at: '15:41:00'
```
salvo il file ricarico le automazioni e aspetto che venga l'orario.

**Reply by xyzmauro** [reply]
effettivamente time non avrà to_state e ti da errore, non va bene l'automazione fatta così, se invece togli dai trigger l'orario scatterà a mezzanotte...per farla ad un orario specifico dovresti usare choose, se i giorni del ritiro possono coincidere puoi usare l'ultimo esempio qui
https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions

**Reply by xyzmauro** [reply]
una roba simile, ma non avendo ne la raccolta differenziata impostata, ne GH dovresti testarla

```
# Example with "if" and "if"
  - alias: garbage
    trigger:
      - platform: time
        at: '17:48:00'
    action:
      # IF a entity is 0
      - choose:
          - conditions:  >
              {{ state_attr('sensor.organico','days') |int < 1 }}
            sequence:
              - service: tts.google_say
                data_template:
                  entity_id: media_player.seminterrato
                  message: "Attenzione: è giorno di ritiro frazione organica"
       # IF another entity not related to the previous, is 0
      - choose:
          - conditions:  >
              {{ state_attr('sensor.carta','days') |int < 1 }}
            sequence:
              - service: tts.google_say
                data_template:
                  entity_id: media_player.seminterrato
                  message: "Attenzione: è giorno di ritiro carta"
```

**Reply by 88Marius88** [reply]
Io ho risolto cosi creando un automazione che alle ore 22:00 fa la verifica di ogni singolo sensore. Ho creato per ogni tipologia di spazzatura l'automazione.

**`- id: 'Id'
  alias: Notifica raccolta umido
  description: Raccolta della spazzatura differenziata
  trigger:
  - platform: time
    at: '22:00'
  condition:
  - condition: numeric_state
    entity_id: sensor.umido
    below: '1'
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.salotto
      message: Uscire il bidone dell' umido che puzza Grazie
  - device_id: Id devices
    domain: mobile_app
    type: notify
    title: Raccolta rifiuti
    message: Uscire il bidone dell' umido `**

**Comment by jimborm** [comment]
Ciao a tutti grazie all'imbeccata di @xyzmauro ho finalmente risolto così:
```
################################### NOTIFICHE GARBAGE ##################################
# Example with "if" and "if"
- alias: garbage
  initial_state: true
  trigger:
    - platform: time
      at: '21:00:00'
  action:
      # IF a entity is 0
      - choose:
          - conditions:  >
              {{ state_attr('sensor.organico','days') |int == 1 }}
            sequence:
              - service: media_player.volume_set
                data_template:
                  entity_id: media_player
                  volume_level: 0.4
              - service: tts.google_say
                data_template:
                  entity_id: media_player
                  message: "Bella raga, com'è la situa? domani è giorno di ritiro frazione organica ... mastello marrone"
       # IF another entity not related to the previous, is 0
      - choose:
          - conditions:  >
              {{ state_attr('sensor.carta','days') |int == 1 }}
            sequence:
              - service: media_player.volume_set
                data_template:
                  entity_id: media_player
                  volume_level: 0.4
              - service: tts.google_say
                data_template:
                  entity_id: media_player
                  message: "Bella raga, com'è la situa? domani è giorno di ritiro frazione carta ... mastello bianco"
       # IF another entity not related to the previous, is 0
      - choose:
          - conditions:  >
              {{ state_attr('sensor.vetro_metallo','days') |int == 1 }}
            sequence:
              - service: media_player.volume_set
                data_template:
                  entity_id: media_player
                  volume_level: 0.4
              - service: tts.google_say
                data_template:
                  entity_id: media_player
                  message: "Bella raga, com'è la situa? domani è giorno di ritiro frazione vetro metallo ... mastello verde"
       # IF another entity not related to the previous, is 0
      - choose:
          - conditions:  >
              {{ state_attr('sensor.indifferenziata','days') |int == 1 }}
            sequence:
              - service: media_player.volume_set
                data_template:
                  entity_id: media_player
                  volume_level: 0.4
              - service: tts.google_say
                data_template:
                  entity_id: media_player
                  message: "Bella raga, com'è la situa? domani è giorno di ritiro frazione indifferenziata ... mastello grigio"
       # IF another entity not related to the previous, is 0
      - choose:
          - conditions:  >
              {{ state_attr('sensor.plastica','days') |int == 1 }}
            sequence:
              - service: media_player.volume_set
                data_template:
                  entity_id: media_player
                  volume_level: 0.4
              - service: tts.google_say
                data_template:
                  entity_id: media_player
                  message: "Bella raga, com'è la situa? domani è giorno di ritiro frazione plastica ... mastello giallo"
```
