### DISCUSSION TITLE
Uptime command_line for websites

### DISCUSSION THREAD

**Discussion by mariomare22** [indomus/forum#513] [HUB: Home Assistant]
Ciao!
Sto provando a monitorare tramite HA dei portali e siti che mantengo sia interni alla rete che su cloud utilizzando il seguente sensore.

```
sensor:
  - platform: command_line
    name: mStream HTTP Response Code
    command: curl -I https://dominio1/ 2>/dev/null | head -n 1 | cut -d$' ' -f2
    scan_interval: 60
```

per gli 8 domini che vorrei monitorare che sono tutti funzionanti ottengo codici HTTP diversi:
```
302
200
405
200
302
302
301
301
```
1) Come posso impostare il sensore in modo tale che mi dica quando il sito e' raggiungibile e quando non lo e'?

2) Come posso impostare un'automazione che mi notifichi quando un sito e' down e mi dica quale?

Grazie,
M.

**Comment by maxcanna** [comment]
1. IMHO la cosa migliore che puoi fare è usare un [rest sensor](https://www.home-assistant.io/integrations/sensor.rest/)
2. - Puoi creare un'automazione mettendo trigger multipli. Nella action potrei recuperare il nome del sensore che ha fatto scattare il trigger.
    - In alternativa puoi impostare un `id` su ogni trigger ed usarlo poi per cambiare il messaggio della notifica. Questo secondo approccio però è peggiore IMHO perché ti costringe ad essere più verboso ed a specificare messaggi multipli

**Reply by mariomare22** [reply]
Grazie per la risposta!
ho tentato l'esempio
```
# Example configuration.yaml entry
sensor:
  - platform: rest
    resource: https://miosito
```
ma ottengo l'errore dei 255 caratteri come limite e quindi il sensore non viene creato, immagino che io debba impostare il `value_template` ma non essendo siti che mi restituiscono json non so come comportarmi.

Non mi e' chiaro come posso filtrare solo l'HTTP Code o qualcos'altro che mi dica che il sito sia up o meno.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/12135860/125484531-c8066705-e1c7-4525-aac9-fe9d739314c1.png">
