### DISCUSSION TITLE
Automazione con Trigger ID - Dove Sbaglio

### DISCUSSION THREAD

**Discussion by Zagor4** [indomus/forum#517] [HUB: Home Assistant]
Innanzi tutto, grazie a chi vorrà rispondermi:

Le mie domande sono le seguenti:
1_Sto utilizzando correttamente la logica del Trigger ID ?
2_ Le condizioni che inserisco all'interno della sezione "Condizioni" dell'automazione, in presenza di trigger multipli valgono sempre per tutti i trigger, giusto ?

Di seguito il codice:
``````
- id: '1626198308501'
  alias: Spegnimento_AC_Sala_2.0
  description: ''
  trigger:
  - platform: template
    value_template: '{{states(''sensor.temperatura_sala'')|float < states(''input_number.temp_low_sala'')|float}}'
    id: Temp_Inferiore
  - platform: template
    value_template: '{{states(''sensor.umidita_sala'')|float < states(''input_number.hum_low_sala'')|float}}'
    id: Umid_Inferiore
  - type: opened
    platform: device
    device_id: acd4b780e9ba7e94b3daab08c687d675
    entity_id: binary_sensor.window_soggiorno_contact
    domain: binary_sensor
    id: WsOpen
  - type: opened
    platform: device
    device_id: 34c4860d7514c808baa14525cc9bf725
    entity_id: binary_sensor.window_cucina_contact
    domain: binary_sensor
    id: WcOpen
  condition:
  - condition: state
    entity_id: climate.condizionatore_sala
    state: dry
  action:
  - condition: trigger
    id: Temp_Inferiore
  - service: notify.mobile_app_mauryredmi10
    data:
      message: '❄️

        Temperatura Sala {{states(''sensor.temperatura_sala'') | round(1)}}°,

        Umidità Sala {{states(''sensor.umidita_sala'') | round(1)}}%,

        Raggiunta Temperatura di Soglia - Spengo il deumidificatore!

        '
      title: Condizionatore Sala
  - service: climate.turn_off
    target:
      entity_id: climate.condizionatore_sala
  - condition: trigger
    id: Umid_Inferiore
  - service: notify.mobile_app_mauryredmi10
    data:
      message: '❄️

        Temperatura Sala {{states(''sensor.temperatura_sala'') | round(1)}}°,

        Umidità Sala {{states(''sensor.umidita_sala'') | round(1)}}%,

        Raggiunta Umidità di Soglia - Spengo il deumidificatore!

        '
      title: Condizionatore Sala
  - service: climate.turn_off
    target:
      entity_id: climate.condizionatore_sala
  - condition: trigger
    id: WsOpen
  - service: notify.mobile_app_mauryredmi10
    data:
      message: '❄️

        Finestra sala aperta - Spengo il deumidificatore!

        '
      title: Condizionatore Sala
  - service: climate.turn_off
    target:
      entity_id: climate.condizionatore_sala
  - condition: trigger
    id: WcOpen
  - service: notify.mobile_app_mauryredmi10
    data:
      message: '❄️

         Finestra cucina aperta - Spengo il deumidificatore!

         '
      title: Condizionatore Sala
  - service: climate.turn_off
    target:
      entity_id: climate.condizionatore_sala
  mode: single

``````

**Comment by Scialla** [comment]
Premetto che non ho guardato ancora come funzione il trigger ID ma, in ogni caso:
La action non funziona così, se la prima condizione non è verificata l'automazione si interrompe e non prosegue e quindi le altre condizioni non vengono verificate. Se tu vuoi che venga scelta una tra diverse condizioni (o trigger ID) per eseguire la relativa automazione, guardati la choose della action

**Reply by Zagor4** [reply]
Ciao,
Come ti dicevo, ho risolto un problema come tu mi hai consigliato, ovvero utilizzando una choose sulle actions.
Penso però di dover affinare i trigger dell'automazione: 
Ora l'automazione rimane sempre attiva, ma tra le condizioni ho inserito un input.boolean che viene attivato dallo scheduler.
Ma anche in questo caso se l'input boolean viene attivato (o dallo scheduler oppure a mano) quando il trigger è già nel campo di verità, l'automazione ovviamente non parte. 
Prima di queste modifiche, proprio per questo motivo, avevo inserito un unico trigger di tipo Time che scattava ogni 3 minuti.
Ma secondo me si può trovare un qualcosa di più fine... 

Ti allego il codice dell'automazione di accensione:

``````
- id: '1624279610046'
  alias: AC_Sala_Accensione
  description: ''
  trigger:
  - platform: template
    value_template: '{{states(''sensor.temperatura_sala'')|float > states(''input_number.temp_high_sala'')|float}}'
    id: Temp_Superiore ##Temperatura ambiente > input number temperatura di soglia
  - platform: template
    value_template: '{{states(''sensor.umidita_sala'')|float > states(''input_number.hum_high_sala'')|float}}'
    id: Umid_Superiore ## Umidità ambiente > input number umidità di soglia
  condition:
  - condition: state
    entity_id: climate.condizionatore_sala
    state: 'off' ## Il condizionatore deve essere spento per evitare invii di codici IR se lo split è già attivo
  - type: is_not_open
    condition: device
    device_id: acd4b780e9ba7e94b3daab08c687d675
    entity_id: binary_sensor.window_soggiorno_contact
    domain: binary_sensor  ## La finestra della sala deve essere chiusa
  - type: is_not_open
    condition: device
    device_id: 34c4860d7514c808baa14525cc9bf725
    entity_id: binary_sensor.window_cucina_contact
    domain: binary_sensor  ## La finestra della cucina deve essere chiusa
  - condition: state
    entity_id: input_boolean.flag_scheduler_sala
    state: 'on' ## il flag che viene impostato dallo scheduler (o da lovelace) deve essere ON.
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: Temp_Superiore
      sequence:
      - service: notify.mobile_app_mauryredmi10
        data:
          message: '❄️ Temperatura Sala {{states(''sensor.temperatura_sala'') | round(1)}}°,
            Umidità Sala {{states(''sensor.umidita_sala'') | round(1)}}%, Temperatura
            elevata - Accendo il deumidificatore! '
          title: Condizionatore Sala
      - service: scene.turn_on
        target:
          entity_id: scene.deumidificatore_sala_auto  ##accendo il condizionatore e dico che l'umidità è elevata
    - conditions:
      - condition: trigger
        id: Umid_Superiore
      sequence:
      - service: notify.mobile_app_mauryredmi10
        data:
          message: '❄️ Temperatura Sala {{states(''sensor.temperatura_sala'') | round(1)}}°,
            Umidità Sala {{states(''sensor.umidita_sala'') | round(1)}}%, Umidità
            elevata - Accendo il deumidificatore! '
          title: Condizionatore Sala
      - service: scene.turn_on
        target:
          entity_id: scene.deumidificatore_sala_auto  ##accendo il condizionatore e dico che la temperatura è elevata
  mode: single
``````

Grazie mille per qualsiasi eventuale spunto

**Reply by Scialla** [reply]
Con queste automazioni create da UI non si capisce una fava :D 
Premesso ciò, è normale il comportamento che dici perché il trigger è il superamento della temperatura e non l'attivazione dello scheduler, che invece è solo una condizione perché si attivi la action...
Tu vuoi invece che anche quando attivi lo scheduler verifichi se la temperatura o l'umidità sono già nello stato in cui si sarebbe dovuto accendere ma non si è acceso perché era disabilitato...
Boh, magari ci sono soluzioni più pulite ma, al momento, mi viene in mente solo questa:
- aggiungi un trigger sul passaggio di stato a on dell'input boolean
- aggiungi due condizioni in or con i requisiti di temperatura e umidità
- rimodula la choose affinche agisca non sul trigger id ma su un template relativo a temperatura o umidità

così dovrebbe andare; rimane solo da capire, nel caso in cui l'automazione triggeri sul passaggio di stato dell'input boolean a on ed entrambe le condizioni di temperatura e umidità siano a true, cosa succede :D :D 
in realtà, non avendo usato un while, succede che segue l'ordine che gli hai dato, ovvero se nella choose c'è prima la temperatura e dopo l'umidità, dara precedenza alla prima...

Prova, sperimenta!

**Reply by Zagor4** [reply]
Ok per il trigger, in realtà ho pensato di spostare anche quelle che adesso sono condizioni sulla chiusura delle finestre,, tra i trigger.... altrimenti se apro le finestre (e quindi tramite automazione di spegnimento, mi si spegne il condizionatore) quando chiudo le finestre questa automazione scritta in questo post deve attendere il trigger sulla temp / umid per far ripartire il condizionatore.

OK per ripetere le condizioni, che adesso sono trigger, su umidità e temperatura anche nella sezione condizioni, in modo che i trigger "meccanici" chiusura finestre e input boolean abbiano comunque sempre un controllo sulle temperature e non parta quindi il condizione svincolato da queste condizioni essenziali.

Non ho capito invece il terzo punto: cosa intendi per template relativo a temperatura e umidità nella Choose ? In che senso (come direbbe verdone) :D 

Grazie mille

**Reply by Scialla** [reply]
nella choose tu usi il trigger id come condition  per eseguire la sequence. Se il tigger id fosse il passaggio a on del binary, nessuna delle due azioni verrebbe eseguita.
Dovresti quindi usare una condition template che ripete il controllo sullo stato della temperatura e dell'umidità invece che la condition sul trigger id

**Reply by danros3** [reply]
Ciao
Posso inserirmi?

Mi ritrovo nella problematica segnalata con il trigger sulla produzione di un fotovoltaico: vorrei che il clima si accendesse quando la produzione supera i 1000w per almeno 10 minuti consecutivi (se dopo 9minuti scende a 990w NON deve triggerare ) e si disattivi quando scende sotto i 400w per 5 minuti.

Se imposto trigger /1min mi trovo con l'impossibilità di associare un tempo.... A meno di far partire timer....
Se trigger è il sensore W potrebbe succedere che riavvio HA o altro, il valore di W sia sopra la soglia = non si attiva mai.

Nella choose dovrei inserire un wait for trigger ma anche qui mi pare abbastanza un obbrobrio. 

Diversamente potresti farmi vedere un esempio di automazione creatabdirattamente via codice? 

Grazie per l'aiuto.

**Reply by Zagor4** [reply]
Premetto che io non sono molto esperto, ho iniziato da poco a "giocare" con HA.
Leggendo quello che scrivi mi viene in mente che potresti replicare la condizione del sensore W che triggera l'automazione nelle condizioni ed eventualmente utilizzare il Trigger Home Assistant: 

https://www.home-assistant.io/docs/automation/trigger/#home-assistant-trigger

In questo modo in caso di riavvio di home assistant l'automazione verrebbe triggerata e le condizioni sul sensore W farebbe partire il clima solo nella situazione desiderata.
Penso che così potresti anche inserire i Wait ! 

Ma ripeto, non sono assolutamente esperto, quindi qualcun altro saprà sicuramente consigliarti meglio di me.
Ciao

**Reply by Scialla** [reply]
esatto, devi usare come trigger anche l'avvio di HA e come condizione la produzione dei W

**Reply by danros3** [reply]
> esatto, devi usare come trigger anche l'avvio di HA e come condizione la produzione dei W

Perdonami, ma se inserisco il trigger "avvio HA" e ho il FTv in produzione, l'automazione procede senza attendere il tempo impostato. Stessa cosa che farebbe col pattern temporale.

Potessi impostare un action con il "for" usando un template (al fine di impostare i tempi di attesa da frontend) come per i trigger sarebbe il top.

Il codice sotto è simile, al momento funziona salvo talvolta nel pomeriggio in cui, magari, riavvio HA e quindi mi perde il valore del FTV e non mi riaccende la presa con cui carico la macchina.....
ma di solito me lo aspetto e lo faccio manualmente.

```
alias: Opel carica FTV
description: ''
trigger:
  - platform: numeric_state
    entity_id: sensor.ftv_power
    above: input_number.opel_soglia_ftv_on
    for: 0:{{ states('input_number.opel_ritardo_potenza_on') | int }}:5
  - platform: numeric_state
    entity_id: sensor.mains_power
    above: input_number.opel_max_prelievo_rete
    for: 0:{{ states('input_number.opel_ritardo_potenza_off') | int }}:5
  - platform: numeric_state
    entity_id: sensor.battery_energy_percent
    below: Input_number.opel_limite_batteria
    for: '0:{{ states(''input_number.opel_ritardo_potenza_off'') | int }}:5 '
condition:
  - condition: state
    entity_id: input_boolean.opel_consenso_carica
    state: 'on'
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.ftv_power
            above: input_number.opel_soglia_ftv_on
          - condition: device
            type: is_off
            device_id: 7c5c280a2f2b5aa8c728989f3914722b
            entity_id: switch.opel_corsa
            domain: switch
            for:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
        sequence:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: sensor.battery_energy_percent
                    below: input_number.opel_limite_batteria_accensione_carica
                sequence:
                  - wait_for_trigger:
                      - platform: numeric_state
                        entity_id: sensor.battery_energy_percent
                        above: input_number.opel_limite_batteria
            default: []
          - service: notify.dka
            data:
              message: Attivazione carica da ftv
              title: Auto elettrica ON
          - type: turn_on
            device_id: 7c5c280a2f2b5aa8c728989f3914722b
            entity_id: switch.opel_corsa
            domain: switch
          - delay:
              hours: 0
              minutes: 0
              seconds: 15
              milliseconds: 0
          - choose:
              - conditions:
                  - condition: state
                    entity_id: switch.opel_corsa
                    state: 'off'
                sequence:
                  - service: notify.dka
                    data:
                      message: ATTENZIONE <Attivazione carica da FTV FALLITA>
                      title: ATTENZIONE Auto elettrica off
            default: []
      - conditions:
          - condition: numeric_state
            entity_id: sensor.mains_power
            above: input_number.opel_max_prelievo_rete
          - condition: device
            type: is_on
            device_id: 7c5c280a2f2b5aa8c728989f3914722b
            entity_id: switch.opel_corsa
            domain: switch
            for:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
        sequence:
          - type: turn_off
            device_id: 7c5c280a2f2b5aa8c728989f3914722b
            entity_id: switch.opel_corsa
            domain: switch
          - service: notify.dka
            data:
              title: 'Auto elettrica off '
              message: DisAttivazione carica auto per prelievo da rete
          - delay:
              hours: 0
              minutes: 0
              seconds: 15
              milliseconds: 0
          - choose:
              - conditions:
                  - condition: state
                    entity_id: switch.opel_corsa
                    state: 'on'
                sequence:
                  - service: notify.dka
                    data:
                      message: >-
                        ATTENZIONE <DisAttivazione carica per prelievo da rete
                        FALLITA>
                      title: ATTENZIONE Auto elettrica off
      - conditions:
          - condition: numeric_state
            entity_id: sensor.battery_energy_percent
            below: Input_number.opel_limite_batteria
          - condition: device
            type: is_on
            device_id: 7c5c280a2f2b5aa8c728989f3914722b
            entity_id: switch.opel_corsa
            domain: switch
            for:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
        sequence:
          - type: turn_off
            device_id: 7c5c280a2f2b5aa8c728989f3914722b
            entity_id: switch.opel_corsa
            domain: switch
          - service: notify.dka
            data:
              message: DisAttivazione carica per basso livello batteria
              title: 'Auto elettrica off '
          - delay:
              hours: 0
              minutes: 0
              seconds: 15
              milliseconds: 0
          - choose:
              - conditions:
                  - condition: state
                    entity_id: switch.opel_corsa
                    state: 'on'
                sequence:
                  - service: notify.dka
                    data:
                      message: >-
                        ATTENZIONE <DisAttivazione carica per basso livello
                        batteria FALLITA>
                      title: ATTENZIONE Auto elettrica off
            default: []
    default: []
mode: restart
max: 50

```
Grazie
