### DISCUSSION TITLE
esecuzione di mp3

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#521] [HUB: Home Assistant]
Il codice che segue funziona
```
prova:
  alias: Prova
  sequence:
  - service: notify.alexa_media
    data:
      message: "<audio src='https://www.jovo.tech/audio/6Ekcahf5-buongate.mp3' />"
      target: media_player.echoshow
      data:
        type: tts
  mode: single
```
ma se cambio il link con:
https://miolinkduckdns:numeroporta/local/mp3/6Ekcahf5-buongate.mp3
o
https://miolinkduckdns:numeroporta/config/www/mp3/6Ekcahf5-buongate.mp3
non è più raggiungibile. Dove sbaglio?

**Comment by Larry-78** [comment]
Ciao @Dregi56  il primo link è quello corretto e dovresti prima assicurarti che sia raggiungibile dall'esterno, per farlo potresti copiare ed incollare il link all'interno della barra degli indirizzi del tuo browser. Dovresti visualizzare un piccolo player su una pagina a sfondo nero. Se continua a non essere raggiungibile assicurati di posizionare correttamente il file o verificare se utilizzi URL esterno corretto.

```yaml
service: notify.alexa_media
data:
  message: "<audio src='https://miolinkduckdns:numeroporta/local/mp3/6Ekcahf5-buongate.mp3'/>"
  target: media_player.echoshow
  data:
    type: tts
```

**Reply by Dregi56** [reply]
Ciao Larry-78. Grazie per aver risposto. Ti confermo che hai ragione sulla correttezza del link, facendo come dici esce il player e tutto funziona....ma solo sul browser, mentre lanciando lo script Alexa continua a dire che non riesce a raggiungere il file.... MISTERO

**Reply by Larry-78** [reply]
... molto strano, se è raggiungibile deve funzionare. Ci sarà un errore da qualche parte. Parli di script ma hai provato prima da Dev tool? Assicurati di scrivere in maniera corretta

**Reply by Dregi56** [reply]
Dev tool presenta tag diverso:
```
<video controls="" autoplay="" name="media"><source src="miolinkduckdns:numeroporta/local/6Ekcahf5-buongate.mp3" type="audio/mpeg"></video>
```
che è diverso da quello usato nello script (audio src=....) Ho anche provato a buttarci dentro il tag video, ma la risposta è sempre la stessa: _in questo momento non riesco ad accedere alla skill..._
tieni presente che, come ti dicevo più sopra, col link **https://www.jovo.tech/audio/6Ekcahf5-buongate.mp3** tutto funziona perfettamente!! E non "cerca" alcuna skill!!
Potresti per favore fare una prova anche tu? Per testare se dipende dal sistema. Prendi un file mp3 della durata inferiore a 240 secondi e lo converti online su https://www.jovo.tech/audio, lo metti in www di HA e provi con uno script uguale al mio.
nell'ipotesi che la conversione su jovo non fosse "pulita" ho anche provato una conversione da Ubuntu: ffmpeg -i nomefileA.mp3 -ac 2 -codec:a libmp3lame -b:a 48k -ar 24000 nomefileB.mp3
Niente, il risultato è lo stesso, non dipende dal file. Son bloccato!!

**Reply by Larry-78** [reply]
il discorso del tag non mi è chiaro che sia diverso, ad ogni modo conosco bene Jovo Audio Converter e i requisiti degli mp3. Visto che mi hai fatto venire il dubbio ho fatto dei test e funziona perfettamente. Questo è il mio esempio funzionante con un mp3 preso a caso già convertito con Jovo ( il file è posizionato nella cartella www )

```yaml
service: notify.alexa_media_echo_show_di_lorenzo
data:
  message: <audio src="https://ilmioindirizzo.org/local/Sr02Gbv8-ambulanza.mp3"/>
  data:
    type: tts
```
Prova ad andare in Dev Tool/Service e incollalo in yaml mode modificandolo con il tuo indirizzo e service notify relativo al tuo dispositivo, ripeto se il file è raggiungibile deve funzionare.
