### DISCUSSION TITLE
Entità cancellata continua ad appare in lovelace dopo riavvio

### DISCUSSION THREAD

**Discussion by camuxx86** [indomus/forum#532] [HUB: Home Assistant]
Ciao a tutti.
Ho un problema strano.
Dopo ogni riavvio di Home Assistant, continua ad apparire in lovelace un'entità switch.
La cancello da lovelace (solo la parte grafica intendo, non l'entità stessa ovviamente perchè mi serve), e dopo un riavvio, continua ad apparire.
Ho provato a cancellarla sia in modalità grafica che in modalità testo ma il problema permane... 
Consigli ?
Tutte le tab di lovelace funzionano senza problemi ovviamente... 
Verificato anche i log ma non ho trovato niente id strano.
Questa entità si posiziona SEMPRE al primo posto nella prima tab di lovelace, e non sembra essere un problema di cache del browser ( provato con diversi browser e anche in modalità incognito )

qui sotto la parte di codice 

```
views:
  - title: TEMPERATURA
    path: temperatura
    panel: false
    icon: hass:thermometer
    badges: []
    cards:
      - type: entities
        title: Switch
        state_color: true
        show_header_toggle: false
        entities:
          - switch.100082fec0
```
