### DISCUSSION TITLE
Meter: contabilizzazione giornaliera non parte da zero

### DISCUSSION THREAD

**Discussion by danros3** [indomus/forum#534] [HUB: Home Assistant]
Ciao
Ho un problema con i meter.
In sostanza ho dei meter giornalieri che contano, non partendo da zero ma incrementano subito di un X di kwh 
Shelly 1pm integrato in HA con integrazione nativa (non mqtt). I meter forniti da shelly funzionano.
Poi io devo distinguere l'energia che misuro se è prodotta da FTV oppure acquistata da rete. Ho creato un template

```

  - platform: template
    sensors:
      opel_corsa_potenza_da_rete_f:
        friendly_name: "opel_corsa_potenza_da_rete_f"
        value_template: "{% if states('sensor.opel_corsa_power_f')|float <= 5 %} 0.0 {% else %}
        {% if states('sensor.mains_power') |float <= 85 %} 0.0 {% else %}
        {% if states('sensor.mains_power') |float < states('sensor.opel_corsa_power_f')|float %}
        {{ states('sensor.mains_power')|float }} {% else %}
        {{ states('sensor.opel_corsa_power_f')|float }}
        {% endif %}
        {% endif %}
        {% endif %}"

## Calcolo potenza ed energia da rete opel corsa ##
  - platform: integration
    source: sensor.opel_corsa_potenza_da_rete_f
    name: opel_corsa_energia_da_rete_f_kws
    unit_time: s
    unit_prefix: k
    round: 3
  - platform: template
    sensors:
      opel_corsa_energia_da_rete_f_kwh:
        friendly_name: "opel_corsa_energia_da_rete_f_kwh"
        value_template: "{{ (states('sensor.opel_corsa_energia_da_rete_f_kws')|float /3600)|round(3) }}"
        unit_of_measurement: 'kWh'

utility_meter:
  opel_energy_meter_da_rete_hourly:
    source: sensor.opel_corsa_energia_da_rete_f_kwh
    cycle: hourly
  opel_energy_meter_da_rete_daily:
    source: sensor.opel_corsa_energia_da_rete_f_kwh
    cycle: daily
  opel_energy_meter_da_rete_monthly:
    source: sensor.opel_corsa_energia_da_rete_f_kwh
    cycle: monthly
```

In effetti mi fa lo stesso problema segnalato: in sostanza, molte volte non parte da zero ma parte da valori variabili, Ad esempio oggi mi ha fatto un +0.20kwh senza colpo ferire, poi è aumentato correttamente. Altri giorni in passato che incrementato anche di 15kwh.

![Screenshot_20210629-115753_Home Assistant](https://user-images.githubusercontent.com/69107406/126194675-f45948eb-31e3-484b-93d0-898963d16d61.jpg)

![Print Screen - 20210719 175750 - 001](https://user-images.githubusercontent.com/69107406/126194706-e78e6785-4ebc-4ce2-90d4-aed1d4910457.jpg)

![Print Screen - 20210719 183429 - 001](https://user-images.githubusercontent.com/69107406/126195560-9f956e02-079b-4464-8399-c3457d3aed6e.jpg)

Grazie a chi mi potrà aiutare.

Daniele

**Comment by Alexanderdavice** [comment]
Ciao, sto riscontrando anche io un problema simile, mi aggancio a questo thread prima di aprirne un altro.

Sto utilizzando per misurare i consumi delle prese connesse Bticino K4531C (integrate con Deconz) e prese smart Gosund (integrate mediante Local tuya in cui pesco il consumo dagli attributi), ma ho notato che per alcune di queste prese c'è un problema nella misurazione energia. In particolare ho una presa Bticino (chiamata presa Bagno) che misura sempre dei valori di energia anomali,simili a quanto descritto sopra da Daniele. Ho notato un comportamento simile anche per una presa smart Gosund (chiamata presa Bollitore).
I consumi istantanei sembrano invece corretti. Riporto due esempi sotto per consumo ed energia:

![energy_bagno](https://user-images.githubusercontent.com/62716606/157233524-1c73556b-8074-4642-9910-1180b026fd66.png)
![power_bagno](https://user-images.githubusercontent.com/62716606/157233532-5bd21cd3-7ba3-4037-a629-a7b6e465fd56.png)
![energy bollitore](https://user-images.githubusercontent.com/62716606/157233533-ccd4f978-f64a-4df5-b56a-42fddb011d80.png)
![power_bollitore](https://user-images.githubusercontent.com/62716606/157233535-2028e0ca-6a0e-4046-bace-160ee3e46bbb.png)

Sicuramente si tratta di valori errati, in quanto troppo elevati per avere senso.

Riporto un estratto dal file yaml dell'integrazione:

```
        consumo_presa_bollitore:
        friendly_name: "Consumo presa bollitore"
        unit_of_measurement: 'W'
        value_template: "{{ states.switch.bollitore.attributes.current_consumption }}"
        device_class: power
```

```
  - platform: integration
    source: sensor.consumo_presa_bollitore
    name: energy_presa_bollitore
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.bagno
    name: energy_bagno
    unit_prefix: k
    round: 2
```

Grazie per l'aiuto
