### DISCUSSION TITLE
Attivare automazione solo la prima volta

### DISCUSSION THREAD

**Discussion by PAC161985** [indomus/forum#536] [HUB: Home Assistant]
Ciao a tutti, sono nuovo nel forum e mi presento....sono Claudio :)

ho un problema con un automazione e sto impazzendo da piu di un mese e spero possiate aiutarmi.

vi spiego cosa vorrei fare, ho un sensore di movimento che tra le 5 e le 11 del mattino mi deve far eseguire un'azione e fin qui tutto ok.
il problema sta nel fatto, che vorrei che questa azione funzionasse solo alla prima attivazione del sensore.

secondo voi è una cosa possibile?

**Comment by Larry-78** [comment]
Ciao Claudio, la prima cosa che mi viene in mente e di aggiungere in action come ultimo il servizio automation.turn_off in maniera tale che l'automazione al primo trigger in fine disattivi se stessa. Poi di conseguenza dovresti creare un'altra automazione che riattivi l'automazione in questione per esempio all'orario da te scelto

**Comment by PAC161985** [comment]
Ah potrebbe essere una soluzione, anche se però preferirei riuscire a farlo in un’unica automazione.

con Alexa è così semplice farlo, ma con home assistant non riesco proprio…

**Reply by snakuzzo** [reply]
infatti lui ti ha suggerito di farlo con un'unica automazione...e guarda che è semplicissimo farlo anche con HA

**Reply by PAC161985** [reply]
D’accordo però poi dovrei crearne una seconda per riattivarla, è questo che vorrei evitare se possibile.

Anche te mi suggerisci di farlo così?

**Reply by snakuzzo** [reply]
Hai ragione... non ci avevo pensato :D

**Reply by snakuzzo** [reply]
Allora...puoi farlo, ma devi verificare l'attributo `last_triggered` della stessa automazione.
Come trigger imposti il cambio stato del sensore da `off` a `on`.
Poi fai un controllo e se ti trovi nella fascia oraria 5-11 e l'automazione non è mai stata triggerata in quella fascia oraria dello stesso giorno in cui è appena scattata, fai eseguire la action

**Reply by PAC161985** [reply]
Cosa intendi? Last trigger come lo imposto?

**Reply by snakuzzo** [reply]
E' un attributo delle automazioni. Ti dice quando è scattata l'ultima volta

**Reply by snakuzzo** [reply]
Potresti provare così...

```yaml
automation:

- id: prova
  alias: prova
  trigger:
  # Il trigger scatta quando c'è il passaggio da off a on del sensore di movimento
  - id: trigger_sensor
    platform: state
    entity_id: binary_sensor.sensore_movimento
    from: "off"
    to: "on"
  condition:
    # Se ci troviamo tra le 5 e le 11...
    - condition: time
      after: '05:00:00'
      before: '11:00:00'
    # e se la data dell'ultima volta che è scattata l'automazione è diversa dalla data attuale
    - condition: template
      value_template: "{{ state_attr('automation.prova','last_triggered').strftime('%m-%d-%Y') != now().strftime('%m-%d-%Y') }}"
  # Eseguo la action
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.mio_switch
```

solo che se per caso vai a triggerare a mano l'automazione nella stessa data ma fuori da quell'orario impostato nella condition, non scatterebbe in quel giorno. Quindi potresti fare così...

```yaml
automation:

- id: prova
  alias: prova
  trigger:
  # Il trigger scatta quando c'è il passaggio da off a on del sensore di movimento
  - id: trigger_sensor
    platform: state
    entity_id: binary_sensor.sensore_movimento
    from: "off"
    to: "on"
  condition:
    # Se ci troviamo tra le 5 e le 11...
    - condition: time
      after: '05:00:00'
      before: '11:00:00'
    # e se...
    - condition: or
      conditions:
      # la data dell'ultima volta che è scattata l'automazione è diversa dalla data attuale
      - condition: template
        value_template: "{{ state_attr('automation.prova','last_triggered').strftime('%m-%d-%Y') != now().strftime('%m-%d-%Y') }}"
      # oppure se...
      - condition: and
        conditions:
        # la data dell'ultima volta che è scattata l'automazione è uguale alla data attuale
        - condition: template
          value_template: "{{ state_attr('automation.prova','last_triggered').strftime('%m-%d-%Y') == now().strftime('%m-%d-%Y') }}"
        # ...e l'orario dell'ultima volta che è scattata è inferiore alle 5 e superiore alle 11 (nel caso in cui tu l'abbia triggerata a mano)
        - condition: template
          value_template: "{{ state_attr('automation.prova','last_triggered').strftime('%H') | int < 5 and state_attr('automation.prova','last_triggered').strftime('%H') | int < 11 }}"
  # Eseguo la action
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.mio_switch
``` 

P.S. Ho scritto tutto di getto senza provare

**Reply by Larry-78** [reply]
Complimenti @snakuzzo ottimo lavoro, non c'erano dubbi che saresti riuscito a risolvere il problema. Ma se la necessità è di farla eseguire soltanto una volta tra le 05:00 e le 11:00 (almeno così ho capito e non considerando la necessità di farla eseguire a mano dopo il range temporale perché non ha spiegato il reale utilizzo), ho continuato a pensare alla mia proposta e creare un'automazione singola che triggera al primo movimento poi si arresta riattivandosi alle 11 così sarà pronta per un nuovo trigger il giorno dopo. Che ne pensi @snakuzzo, potrebbe funzionare? Ovviamente la mia è una versione più 'ignorante' rispetto a quella tua ma a ci ho provato e vorrei un parere. Ti ringrazio in anticipo!!

```yaml
alias:  prova_solo_una_volta
trigger:
  - platform: state
    entity_id: binary_sensor.movimento
    from: 'off'
    to: 'on'
condition:
  - condition: time
    after: '05:00'
    before: '11:00'
action:
  - service: switch.turn_on
    target:
      entity_id: switch.mio_switch
  - service: automation.turn_off
    target:
      entity_id: automation.prova_solo_una_volta
    data:
      stop_actions: false
  - wait_for_trigger:
      - platform: time
        at: '11:00'
  - service: automation.turn_on
    target:
      entity_id: automation.prova_solo_una_volta
mode: single
 ```

**Reply by snakuzzo** [reply]
Potrebbe andare...sicuramente è più semplice...solo che si dà per scontato che fili tutto liscio.
Mi spiego...se succede qualcosa durante il wait (non succede...ma se succede), non funzionerà nulla.
Però ragionando in maniera "ottimistica" dovrebbe andar bene

**Reply by ciutty** [reply]
Fai uno script con le due automazioni e lo metti nella cartella package. Ci sono tanti tutorial in rete.

**Reply by snakuzzo** [reply]
@ciutty se leggi gli è stato già detto all'inizio da @Larry-78 :)
Lui voleva farlo con una sola automazione

**Reply by Larry-78** [reply]
@snakuzzo giusta osservazione...potrebbe bloccarsi tutto durante il `wait` per un problema X e l'automazione rimarrebbe `off`...più sicura la tua versione.

**Reply by snakuzzo** [reply]
Sì era quello che intendevo, ma da qua a dire "più sicura" ce ne vuole :D
Non l'ho testata...l'ho scritta al volo solo pensandoci.

**Reply by xyzmauro** [reply]
Ciao,provo a darti un altro spunto sfruttando anche il trigger_id da poco introdotto...oltre al pir aggiungi un trigger con platform time alle 11:00 e gli dai id: ripristino,poi fai una choose con prima condition l’orario compreso tra le 5:00 e le 10:59 AND last_triggered dell’automazion != da oggi e come action metti le tue e per ultima automation turn_off...la seconda condition sarà con trigger_id ripristino e gli metti automation_turn on
A occhio dovresti coprire tutti i casi sia che scatti per il pir che se la fai partire a mano
Da cell mi vien difficile scriverla ma son sicuro che @snakuzzo se ha voglia te la butta giù al volo 😜

**Reply by Larry-78** [reply]
Bella @xyzmauro , di sicuro @snakuzzo sarebbe in grado e lo sappiamo...quando hai tempo provaci tu e condividi la tua idea, potrebbe essere di aiuto a tutti....anche se per ora il diretto interessato non ha ancora espresso un parere in merito ai nostri contributi. Questo non vuole essere una critica e sia chiaro

**Reply by snakuzzo** [reply]
Ottimo @xyzmauro ... come al solito.
Mi piace!

**Reply by snakuzzo** [reply]
Però siamo sempre allo stesso punto. Se la metti ad off poi non si riattiva più da sola

**Reply by xyzmauro** [reply]
> Però siamo sempre allo stesso punto. Se la metti ad off poi non si riattiva più da sola

Hai ragione, una volta messa ad OFF l'automazione poi non scatta più alle 11...senza perdersi nell'ipotesi di far scattare a mano l'automazione si potrebbe usare un boolean
```
input_boolean:
  automazione_triggerata:
    name: automazione_triggerata

automation:
  - alias: prova
    trigger:
    - id: pir
      platform: state
      entity_id: binary_sensor.sensore_movimento
      from: "off"
      to: "on"    
    - id: ripristina
      platform: time
      at: '11:00:00'
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                 {{ now().strftime('%H')|int >=5 and now().strftime('%H')|int <= 11
                 and
                 states('input_boolean.automazione_triggerata') == 'off' }} 
            sequence:
              - service: input_boolean.turn_on
                entity_id: 
                  - input_boolean.automazione_triggerata
              - service: light.turn_on
                entity_id: 
                  - light.luce_cucina  
          - conditions:
              - condition: trigger
                id: "ripristina"
            sequence:
              - service: input_boolean.turn_off
                entity_id: 
                  - input_boolean.automazione_triggerata
```
