### DISCUSSION TITLE
Consumo asciugatrice - ho fatto un casino

### DISCUSSION THREAD

**Discussion by rowiz** [indomus/forum#544] [HUB: Home Assistant]
Sperando di non prendermi subito le offese da @snakuzzo al primo post sul forum, vi condivido il mio "progetto" fatto male per la rilevazione dei cicli di un' asciugatrice.
Obiettivo del progetto: rappresentare su lovelace queste informazioni:

- consumo giornaliero
- consumo mensile
- consumo annuale
- tempo di durata dell'ultimo ciclo
- consumo dell'ultimo ciclo

il consumo è monitorato da una blitzwolf collegata in zigbee tramite la chiavetta di giobin. Le prime tre le ho realizzate abbastanza semplicemente, usando utility_meter. Per quanto riguarda la quarta, ho fatto un casino, il timer non si ferma più! L'ultima invece non vuole saperne di funzionare.

Vi posto qua un po' di roba

qui il sensore binario, che non si azzera a ciclo finito

```
binary_sensor:
  - platform: template
    sensors:
      ciclo_asciugatrice:
        friendly_name: "Asciugatrice accesa"
        value_template: "{{ states('sensor.asciugatrice_power')|int > 0 }}"
        device_class: power
        delay_on:
          seconds: 30
        delay_off:
          minutes: 2

```

qui il sensore di tempo, appena ho messo a mano il sensore di cui sopra a 0 s'è azzerato

```
  - platform: history_stats
    name: Ultimo Ciclo Asciugatrice
    entity_id: binary_sensor.ciclo_asciugatrice
    state: "on"
    type: time
    start: '{{ as_timestamp(states.binary_sensor.ciclo_asciugatrice.last_changed) }}'
    end: "{{ now() }}"

```
qui infine l'automazione

```
- alias: "consumo fine asciugatrice"
  trigger:
    platform: state
    entity_id: binary_sensor.ciclo_asciugatrice
    to: 'off'
  action:
    service: input_number.set_value
    target:
      entity_id: input_number.ultimo_ciclo_asciugatrice
    data:
      value: "{{states('sensor.asciugatrice_power')}}"

```

accetto offese & consigli, solo in coppia però :D

**Comment by snakuzzo** [comment]
Mi fa piacere sapere di essere etichettato come quello che insulta :D

**Comment by rowiz** [comment]
Allora, piccolo aggiornamento, ho modificato il binary sensor ed ora sembra fare il suo dovere

```
template:
  - binary_sensor:
      - name: "Asciugatrice"
        delay_on:
          minutes: 2
        delay_off:
          minutes: 2
        state: >
          {{ states('sensor.asciugatrice_power')|float > 0.2 }}

```

sul resto ancora alto mare!
