### DISCUSSION TITLE
Calcolo consumo in kW e in Euro con Sonoff pow2

### DISCUSSION THREAD

**Discussion by gideonklein** [indomus/forum#55] [HUB: Home Assistant]
Buongiorno a tutti. Con home assistant ho dispositivi Sonoff non tasmotizzati (https://github.com/AlexxIT/SonoffLAN). Per motivi che non vi sto a spiegare i dispositivi sono in locale e non nel cloud. Quindi mi servirebbe una automazione che calcoli i Kwh e il costo in locale. In rete ho trovato alcune stringhe di codice che però non fanno il loro dovere, copio e incollo:
```
sensor:
  - platform: template
    sensors:
      today_consumption:
        friendly_name: Today consumpion
        unit_of_measurement: kW
        value_template: "{{ state_attr('switch.sonoff_1000dd2821', 'consumption').0 }}"
```
```
  - platform: statistics
    name: power_per_minute1
    entity_id: sensor.sonoff_1000dd2821_power
    sampling_size: 60 # This is assuming you are getting 1 sample a second.  Adjust otherwise.    

  - platform: template
    sensors:
      realtime_power1:
        friendly_name: Kilowatts
        unit_of_measurement: kW
        value_template: "{{ state_attr('sensor.power_per_minute1', 'total') / (1000 * 60) }}"
```

**Comment by akela-it** [comment]
Ciao! 
Anche io ho iniziato con AlexxIT/SonoffLAN e il calcolo lo facevo in questo modo per la lavastoviglie:

```
sensor:
  - platform: template
    sensors:
      lavastoviglie_consumo_giornaliero:
        friendly_name: Lavastoviglie consumo giornaliero
        unit_of_measurement: kWh
        value_template: "{{ state_attr('switch.sonoff_xxxx', 'consumption').0 }}"
      lavastoviglie_consumo_mensile:
        friendly_name: Lavastoviglie consumo mensile
        unit_of_measurement: kWh
        value_template: "{% set p=state_attr('switch.sonoff_xxxx', 'consumption') %}{{ p[:30]|sum if p }}"
  - platform: template
    sensors:
      lavastoviglie_costo_giornaliero:
        friendly_name: "Lavastoviglie costo giornaliero"
        unit_of_measurement: '€'
        value_template: "{{ (states('sensor.lavastoviglie_consumo_giornaliero')|float * 0.18)| round(2) }}"
      lavastoviglie_costo_mensile:
        friendly_name: "Lavastoviglie costo mensile"
        unit_of_measurement: '€'
        value_template: "{{ (states('sensor.lavastoviglie_consumo_mensile')|float * 0.18)| round(2) }}"
```
Avevo messo un prezzo medio di 0.18, poi ho complicato il tutto mettendo i costi specifici per ogni fascia oraria (F1,F2,F3) e impostando la fascia elettrica corretta ma questa è la base. A me funziona dovrebbe funzionare anche a te (naturalmente il mio switch.sonoff_xxxx corrisponde al tuo switch.sonoff_1000dd2821)
