### DISCUSSION TITLE
calibrazione anemometro con ESPHome

### DISCUSSION THREAD

**Discussion by Nik71git** [indomus/forum#551] [Hardware & Firmware]
Sorry guys, chi usa anemometro con esphome? La calibrazione come la fate? al momento ho commentato quanto mi riesce difficile, ma vorrei fare una calibrazione come si deve.  Sotto ecco il mio sensore  

 ```
- platform: pulse_counter
    pin: 
      number: GPIO14 #D5
      mode: INPUT_PULLUP
    unit_of_measurement: 'Km/h'
    name: 'vento Km/h'
    icon: 'mdi:weather-windy'
    accuracy_decimals: 1
    id: my_wind_kmh
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    internal_filter: 13us
    update_interval: 30s
    #rotations_per_sec = pulses/2/60
    #circ_m=0.09*2*3.14 = 0.5652
    #mps = 1.18*circ_m*rotations_per_sec  
    #mps = 1.18*0.5652/2/60 =0,0055578
    filters:
      - multiply: 0.02000808
      #- sliding_window_moving_average:
      #    window_size: 2
      #    send_every: 1
```
