### DISCUSSION TITLE
Integrazione switch da muro bticino n4003c

### DISCUSSION THREAD

**Discussion by filpao** [indomus/forum#557] [HUB: Home Assistant]
Buongiorno a tutti,
mi sto avvicinando da poco alla domotica personale, e quindi vi premetto che sono piuttosto un principiante.
Chiedo il vostro aiuto per questo problema.
Ho comprato l'interruttore in oggetto, e sto cercando di integrarlo in HA direttamente via zigbee (senza gateway della bticino); Il mio gateway zigbee è un autocostruito composto da NodeMCU con Tasmota, e l'antenna cc2530+cc2591 (come da guide su inDomus).
In configuration.yaml ho inserito le seguenti righe:

```
# integrazione switch da muro bticino n4003c luce ingresso
switch:
  platform: mqtt
  name: "Interruttore luce ingresso"
  state_topic: "tele/zigbee_gate/7003/SENSOR"
  value_template: "{{ value_json['0x7003'].Power }}"
  command_topic: "cmnd/zigbee_gate/7003/set"
  payload_on: "1"
  payload_off: "0"
  qos: 1
  retain: false
```

HA rileva lo switch, e ne riporta correttamente lo stato attuale, e i relativi cambiamenti di stato quando premo fisicamente il pulsante; purtroppo non riesco a capire come comandarlo da HA; ho provato anche diverse varianti sia del comand_topic sia dei payload_on e *_off, ma senza successo. Cliccando sul pulsantino dello switch in HA, il pulsante cambia stato ma non succede nulla, e poco dopo torna allo stato precedente.
La telemetria sulla consolle Tasmota del nodeMCU mi dà o errore, o command unknown.
Qualcuno riesce ad aiutarmi?
Grazie per la pazienza.
Filippo
