### DISCUSSION TITLE
Cambiare logica device_tracker

### DISCUSSION THREAD

**Discussion by maxcanna** [indomus/forum#56] [HUB: Home Assistant]
Ciao guys,
eccomi col mio primo post.

Vi spiego il problema. Ho configurato due `device_tracker` come in config:

```yaml
device_tracker:
  - platform: bluetooth_tracker
    track_new_devices: false
  - platform: ping
    hosts:
      phone_ip: 192.168.0.123
    consider_home: 60
```

```yaml
phone_bt:
  hide_if_away: false
  icon: "mdi:bluetooth"
  mac: "BT_DE:AD:BE:EF:DE:AD"
  name: "Phone BT"
  picture:
  track: true

phone_ip:
  hide_if_away: false
  icon: "mdi:wifi"
  mac:
  name: "Phone IP"
  picture:
  track: true
```

li ho aggiunti alla entity `person` assieme al terzo `device_tracker` `phone` che proviene dalla companion app:

```json
{
    "version": 2,
    "key": "person",
    "data": {
        "items": [
            {
                "device_trackers": [
                    "device_tracker.phone_bt",
                    "device_tracker.phone_ip",
                    "device_tracker.phone",
                ],
                "id": "massimiliano",
                "name": "Massimiliano",
                "user_id": "8ab92981655adc3b28c2d4ae111fa393",
                "picture": null
            }
        ]
    }
}
```

Fin qui tutto ok, però vorrei affinare il comportamento in alcuni casi limite.

Esempio, esco di casa e mi allontano. Poi torno _geograficamente_ a casa ma non sono all'interno. Vorrei che `person.massimiliano` risultasse `home` solo quando tutti e tre i sensori sottostanti riportano questo stato.

Ho provato a leggere la doc di [`person`](https://www.home-assistant.io/integrations/person/) e di [`device_tracker`](https://www.home-assistant.io/integrations/device_tracker/#configuring-a-device_tracker-platform) ma non ho trovato la possibilità, se c'è, di impostare quel che voglio.

Avete idee o workaround? Grazie 🙂
