### DISCUSSION TITLE
Automazioni basate sull'ora

### DISCUSSION THREAD

**Discussion by riccionese** [indomus/forum#567] [GENERALE - Discussioni generiche]
Ciao a tutti, sto smattendo per fare partire una automazione all'ora che indico in un ```input_datetime```
ne ho configurato uno come
```
input_datetime:
  ora_inizio:
    name: Prova ora_inizio
    has_date: false
    has_time: true
```
ed ho "rubato" l'automazione dell'articolo sul sito

```
automation:
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.ora_inizio.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  action:
    ..... ecc ecc ecc 
```

ho provato in tutti i modi di cui ho trovato documentazione.
a parte che ho pure cose "strane" dato che se da strumenti per "sviluppatori --> modelli" provo a "stampare" il valore di 
```
ora input {{ states.input_datetime.ora_inizio.attributes.timestamp | int | timestamp_custom('%H:%M') }}
```
ma la visualizza con una ora in più rispetto il dato in input ... 
... non ce ne esco proprio.

e niente.
non c'è verso
cosa sbaglio ?
help

**Comment by 50494554524F** [comment]
- platform: template
    value_template: "{{ is_state( 'sensor.time', states( input_datetime.ora_inizio )[ :5 ] ) }}"

**Reply by riccionese** [reply]
Non mi funziona.
evidentemente mi manca qualche condizione base sul datetime che no ho ancora imparato
avevo anche provato una versione con "is_state" ma ... non ho trovato il significato di "[:5]"
potresti "tradurmi" la tua istruzione? 

Ormai di automazioni ne ho diverse e tutte funzionanti.
anche quelle che partono "ad una ora specifica" ma questa è la prima che vorrei fare con l'ora "da input" e non 
```
  trigger:
  - at: '21:00:00'
    platform: time
```

o basati su eventi tipo sun.sun

credo dovrò studiare ancora molto per questo "datetime"....

**Reply by snakuzzo** [reply]
Ti posto parte di un mio package che uso per lo spegnimento automatico della luce del comodino, basato su un input_datetime.
Assicurati prima di avere la timezone impostata correttamente sotto `Configuration > General`

```yaml
input_datetime:

  light_comodino_diego_spegnimento:
    name: Orario Spegnimento Comodino
    has_date: false
    has_time: true

- id: spegnimento_comodino
  alias: Spegnimento Comodino
  trigger:
  - platform: template
    value_template: "{{ states('sensor.time') == state_attr('input_datetime.light_comodino_diego_spegnimento','timestamp') | int | timestamp_custom('%H:%M', False) }}"
  condition:
  - condition: state
    entity_id: input_boolean.away_switch
    state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: light.comodino_diego
```
