### DISCUSSION TITLE
Input_number senza decimali

### DISCUSSION THREAD

**Discussion by riccionese** [indomus/forum#573] [GENERALE - Discussioni generiche]
Ho configurato degli ```input_number``` tipo questo 
```
  num1:
    name: Num 1
    initial: 10
    min: 0
    max: 20
    step: 1
```
che però vengono visualizzati con un decimale

![image](https://user-images.githubusercontent.com/62329292/127352584-31c9153a-a09d-4b71-9f68-6bbfda308033.png)

in che modo posso far visualizzare solo le cifre intere ?
