### DISCUSSION TITLE
device_tracker non funziona .. :( ( NMAP )

### DISCUSSION THREAD

**Discussion by RobyBS** [indomus/forum#577] [HUB: Home Assistant]
a seguito inserimento del seguente code in configuration.yaml mi aspettavo di essere tracciato al rientro in casa tramite il mio router wi-fi invece nulla : 

```
# Definizione NMAP tracker
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.30/32
    home_interval: 300
    consider_home: 300
    new_device_defaults:
      track_new_devices: true

# Definizione Persone
person:
  - name: Roby
    id: xxx
    device_trackers:
      - device_tracker.Roby
  - name: Vicky
    id: xxxxx
    device_trackers:
      - device_tracker.Vicky   
```

gli host dal 30 al 32 sono gli IP statici dati dal router agli smartphone delle persone ...
forse platform ? 

oppure sono tracciato , ma non vedendo il file device_tracker ( che non dovrebbe più essere gestito , bah ) ? ... 

ho provato anche aggiungendo : 
   ```
 host: IP_ADDRESS
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
```
ma anche qui mi "sfugge" la comprensione del comando platform ( che nell'esempio della guida è netgear , ma io ho un router TIM HUB+ ) ...

**Comment by RobyBS** [comment]
risolto ! ... 
come segue .. per altri che potrebbero incontrare lo stesso problema ... ;) 

configuration.yaml
```
# Definizione NMAP tracker
device_tracker:
  - platform: nmap_tracker
    hosts: 
    - 192.168.1.xx # Roby xxx
    - 192.168.1.xx # Vittoria xxx
    home_interval: 10
    consider_home: 300
```

e in known_devices.yaml 
```
s10x:
  name: Roby xxx
  mac: xx
  icon:
  picture:
  track: true

A40x:
  name: Vittoria xxx
  mac: xx
  icon:
  picture:
  track: true
```

adesso HA riconosce quando sono, anzi siamo , in casa o fuori casa ...

adesso posso andare avanti con i miei progettini ... :)  

se avete suggerimenti o migliorie .. fatevi avanti ! ... ;)
