### DISCUSSION TITLE
Integrazione centrale antifurto iAlarm o antifurto 365

### DISCUSSION THREAD

**Discussion by wifi75** [indomus/forum#58] [HUB: Home Assistant]
Ciao sto utilizzando con node red lo script creato a da nicola per utilizzare via mqtt la centrale di allarme ialarm i antifurto 365.
mi spiegate come poter recuoperare lo sttao tiggered quando la centralle allarma?
ho provato a farla allarmare ma non leggo nessuno stato triggered.
Mi servirebbe sfruttare questa funzione per far acccendere tutte le luci esterne quando allarma.

mi date una mano?

Grazie

**Comment by Nik71git** [comment]
Quando armi tramite payload mqtt ('arm_away') puoi agganciare qualsiasi automazione. 
esempio, questa è la mia automazione che mi da semplicemente una notifica, ma tu puoi fare quello che vuoi.

```
alias: notifica allarme armato
description: notifica 32 allarme armato e disabilita la notifica 33
trigger:
  - platform: state
    entity_id: alarm_control_panel.allarme
    from: disarmed
    to: armed_away
  - platform: state
    entity_id: alarm_control_panel.allarme
    from: disarmed
    to: armed_home
condition: []
action:
  - service: persistent_notification.create
    data:
      title: allarme
      message: armato
      notification_id: 32
  - service: notify.notify
    data:
      title: allarme
      message: armato
      data:
        tag: 32
  - service: persistent_notification.dismiss
    data:
      notification_id: 33
  - service: notify.notify
    data:
      message: clear_notification
      data:
        tag: 33
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.allarme
mode: restart
```
