### DISCUSSION TITLE
Google Nest Hub --> non parla ..

### DISCUSSION THREAD

**Discussion by RobyBS** [indomus/forum#591] [HUB: Home Assistant]
Ciao ... 
eccomi qua ... 

dopo aver installato il device_tracker  che tramite wifi del router di casa , rileva quando sono in casa e quando non lo sono ... volevo implementare una automazione che quando rientro a casa, il mio google nest hub mi desse il messaggio vocale di benvenuto ... 

quando rientro a casa .. il nest hub si collega all'HA appare una videata con scritto "Riproduzione in corso nell'app default media receiver" ma non si sente alcun messaggio ... il volume è impostato a 5 ...

questa la mia configurazione :

- configuration.yaml
```
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: https://xxxx.duckdns.org:8123
    service_name: google_say

```

- automation.yaml
```
# messaggio quando Roby rientra a casa 
- alias: "Ritorno a casa"
  trigger:
    platform: state
    entity_id: device_tracker.s10e_di_roberto
    to: 'home'
  condition: []
  action:
    - delay:
        seconds: 10
    - service: tts.google_say
      data:
        entity_id: media_player.soggiorno
        message: Bentornato a casa Roberto ! prova uno uno uno ! 
        language: it
```

dove sbaglio ? 

al chè per fare una prova sono andato sotto "strumenti per sviluppatori" e sotto servizi ho richiamato quanto sotto : 

```
service: tts.google_say
data:
  entity_id: media_player.soggiorno
  message: 'Ciao sono roberto ! ... sto facendo una prova ...'
  language: it
```

con e senza ' il risultato è sempre lo stesso ... si collega ma non parla ... :( 

potete aiutarmi per cortesia ... 

Grazie
