### DISCUSSION TITLE
Alexa e HA (RISOLTO)

### DISCUSSION THREAD

**Discussion by calz64** [indomus/forum#598] [HUB: Home Assistant]
Ho integrato alexa su HA seguendo la classica guida indomus attivando la risorsa Lambda e la Skill presso AWS.
All'inizio però non ho definito domini creando il filtro nel file di configurazione. In effetti sulla app di Alexa mi trovo tutte le entità rilevate e sono un sacco.
Ho la possibilità di creare il filtro adesso o devo rifare tutto da capo; e in ogni caso come devo fare: - es. eliminare l'account alexa e crearne uno nuovo? ovviamente preferirei risparmiarmi tutta la fatica.

**Comment by angelopampalone** [comment]
Ciao io ho fatto svariate modifiche al filtro, di solito il lato amazon/Alexa le legge e rende disponibili dopo un giorno.

**Reply by calz64** [reply]
Significa che se adesso creo filtro  nel file di configurazione (tipo le righe sotto prese dalla guida) 
Alexa mi esclude/cancella tutte le entità/domini che sono state rilevate:

```
alexa:
   smart_home:
     filter:
       include_entities:
        - ......
       include_domains:
         - switch
        -
       exclude_entities:
        - .....
       exclude_domains:
         - lock
    
```

**Reply by snakuzzo** [reply]
Ciao
1. utilizza il markdown quando posti codice o configurazione ... leggi il regolamento.
2. Non viene rimosso niente. Tutto ciò che hai già incluso lo devi rimuovere a mano tramite app o tramite il sito dedicato https://alexa.amazon.it/spa/index.html?#smart-home

**Comment by calz64** [comment]
Grazie. Ma come funziona fra dominio ed entità:  per esempio, se si inserisce nel filtro:
```
 exlude_domains 
 - binary_sensor
```
 
e poi si scrive
```
include_entities:
    - binary_sensor.shellyswitch...
```

viene rilevata da alexa l'entità binary_sensor.shellyswitch? oppure il filtro impostato di ' exlude_domains  - binary_sensor' non permette l'inclusione dell'entità?

**Reply by snakuzzo** [reply]
Esclude tutti i binary sensor ed include l'entità sotto include

**Reply by calz64** [reply]
Scusami ma vorrei capire se ho inteso bene ciò che dici: 
- escludendo il dominio (es. binary-sensor) escludo tutte le entità di quella tipologia;
- ma se poi decido di includere una entità specifica indicandola (es: binary_sensor.shellyswitch..) questo non entra in conflitto con l'esclusione del dominio e quindi alexa la rileva. Spero di essere stato chiaro.

**Reply by snakuzzo** [reply]
Esatto

**Reply by calz64** [reply]
Ok grazie. 
Allora ti chiedo se è una buona pensata, la strada più breve ed efficace che mi viene in mente per limitare alexa è:
- escludere tutti i domini di default, così nessuna entità viene rilevata a priori;
- poi includere le singole entità che mi interessano sotto il filtro "include_entities"

Inoltre ti chiedo se non è troppo:  -qual'è l'effettivo pericolo di esporre sensori sul server di alexa?

**Reply by snakuzzo** [reply]
Per quanto possa valere il mio contributo, anche io farei così.
Perché parli di pericolo nell'esporre i sensori?

**Reply by calz64** [reply]
Ma perché nelle guide si suggerisce sempre di usare il meno possibile i server delle app e di gestire tutto in locale, in particolare per alexa si suggerisce di cancellare il token dell'integrazione etc... In effetti il tema sicurezza è assai complesso.

**Reply by calz64** [reply]
Scasate ma io continuo a litigare con questo filtro alexa, **aggiungo entità ma non ritrovo nulla sul lato alexa**  ne sull'app ne sul sito (che ovviamente dovrebbero essere la stessa cosa).
Il filtro è questo, vedete qualche errore?
```
alexa:
  smart_home:
     filter:
      exclude_domains:
        - lock
        - alarm_control_panel
        - automation
        - binary_sensor
        - camera
        - cover
        - device_tracker
        - group
        #- media_player
        - person
        - scene
        - sensor
        - sun
        - switch
        - weather
        - zone
      include_entities:
        - binary_sensor.shellyswitch25_e8db84a9ec4e_overheating
        - binary_sensor.shellyswitch25_e8db84aa80ac_overheating
        - binary_sensor.shellyswitch25_e8db84ac53dc_overheating
        - binary_sensor.shellyswitch25_e8db84acb6e2_overheating
        - switch.echo_dot_di_daniele_do_not_disturb_switch
        - switch.echo_dot_di_daniele_repeat_switch
        - switch.echo_dot_di_daniele_shuffle_switch
        - automation.alexa_annuncio_daniele
        - automation.alexa_promeoria_giuditta
        - automation.tapparelle_50_tutte_buttom_long
        - scene.tapparella_50
        - scene.tapparelle_tutte_aperte
        - scene.tapparelle_tutte_chiuse
        - script.tapparelle_50
        - switch.c3wn_e84890119_tracking
        #- light.cucina
        #- light.camera
```
