### DISCUSSION TITLE
Utilizzare la fire stick tv come un sensore di stato

### DISCUSSION THREAD

**Discussion by luxbarba** [indomus/forum#600] [HUB: Home Assistant]
Buongiorno a tutti. Su Home assistant vorrei utilizzare la fire stick tv come sensore di stato per una vecchia televisione a cui essa è collegata. La vecchia tv la comando mediante la piattaforma smartir tramite un telecomando broadlink rmmini3. Se accendo o spengo la tv tramite il telecomando virtuale della broadlink lo stato della tv su home assistant viene rilevato correttamente. Ma se utilizzo il telecomando fisico lo stato ovviamente non cambia. Pertanto essendo la firestick alimentata tramite l'usb della tv, vorrei utilizzare la chiavetta di amazon per determinare lo stato della tv. Qualcuno sa aiutarmi? La mia configurazione è la seguente:

```yaml
media_player:

- platform: smartir
  name: TV Letto
  unique_id: tv_letto
  device_code: 1000
  controller_data: remote.telecomando_broadlink_remote
  power_sensor: media_player.fire_sick_tv

# Use the Python ADB implementation

- platform: androidtv
  name: Fire stick TV
  host: 192.168.1.10
```

**Comment by snakuzzo** [comment]
Ciao.
La prima cosa da fare quando posti la configurazione o codice, devi usare il markdown. Leggi il regolamento.

**Reply by luxbarba** [reply]
Grazie. Ho provveduto. Spero di averlo fatto correttamente.

**Reply by snakuzzo** [reply]
È sbagliato...ritenta

**Reply by luxbarba** [reply]
Non riesco.  In basso ho premuto il tasto <> e inserito il testo all'interno.Potresti spiegarmi cortesemente come si fa?

**Reply by snakuzzo** [reply]
L'abbiamo spiegato nel regolamento come fare. Scrivi il codice, lo selezioni e poi clicchi quel tastino.

Il singolo backtick è per una riga di codice
Se è un blocco di codice devi usarne 3 all'inizio e alla fine.

**Reply by luxbarba** [reply]
Grazie. Dovrebbe essere giusto ora.

**Reply by snakuzzo** [reply]
no...è sbagliato

**Reply by snakuzzo** [reply]
Te l'ho corretto io...vai in EDIT sul tuo post e vedi com'è scritto, così la prossima volta lo scrivi bene

**Reply by snakuzzo** [reply]
```yaml
binary_sensor:
  - platform: template
    sensors:
      stato_tv:
        friendly_name: "Stato TV"
        value_template: "{{ states('media_player.fire_stick_tv') }}"  # usa questo se gli stati poossono essere solo on e off
        #value_template: "{{ off if states('media_player.fire_stick_tv') == 'off' else 'on' }}" # usa questo se gli stati possono essere anche diversi da on e off
```

**Comment by snakuzzo** [comment]
Tramite broadlink tu non rilevi alcuno stato. Ragioni in maniera ottimistica perché mandi un comando di "OFF" e per quello credi che sia OFF. Se per caso copri il trasmettitore e mandi il comando di "OFF" vedrai lo stato cambiare ma "ovviamente" la TV non si spegnerà. Quindi dimenticati il fatto di rilevare lo stato di qualcosa tramite Broadlink.

Prima di procedere con quella cosa che vuoi fare, dovresti prima vedere come si comporta la Firestick in base alla gestione delle porte USB del TV.
Se la TV è in stand-by la Firestick va in "OFF" o rimane su "ON"? Se già rimane su "ON" con il TV in stand-by è inutile continuare

**Reply by luxbarba** [reply]
Grazie per aver corretto il post. Quando la TV é in stand-by la firestick va in off. Per questo motivo penso che si possa far determinare lo stato della TV tramite la firestick ma non so farlo....

**Reply by snakuzzo** [reply]
Allora...ricordo di aver fatto una cosa "simile" qualche tempo fa...ovvero usare uno switch da me creato da visualizzare come interruttore on/off per un media player.
Prova a dare un'occhiata a questa custom card [multiple-entity-row](https://github.com/benct/lovelace-multiple-entity-row).
Se ti interessa solo avere un sensore puoi usare un [template sensor](https://www.home-assistant.io/integrations/template/) o se vuoi avere un'entità di tipo switch un [template switch](https://www.home-assistant.io/integrations/switch.template/)

**Reply by luxbarba** [reply]
Mi interessa solo avere solo un sensore. Avevo dato già un occhiata ai sensor template ma non sono capace di crearlo.....Se fossi cosi gentile da scrivermi il codice te ne sarei grato....

**Reply by luxbarba** [reply]
> Allora...ricordo di aver fatto una cosa "simile" qualche tempo fa...ovvero usare uno switch da me creato da visualizzare come interruttore on/off per un media player.
> Prova a dare un'occhiata a questa custom card [multiple-entity-row](https://github.com/benct/lovelace-multiple-entity-row).
> Se ti interessa solo avere un sensore puoi usare un [template sensor](https://www.home-assistant.io/integrations/template/) o se vuoi avere un'entità di tipo switch un [template switch](https://www.home-assistant.io/integrations/switch.template/)

Innanzitutto ti ringrazio tantissimo per la risposta. Non so per quale motivo mi è arrivata solo nella mail e non sul forum (forse mi hai mandato un messagio privato?) In ogni caso delle due soluzioni mi funziona parzialmente solo la seconda. Ovvero quando la televisione è accesa (mediante telecomando fisico)lo stato su home assistant risulta corretto. Invece quando la spengo lo stato mi rimane su on. Questo, credo che derivi dal fatto che quando spengo la tv, è come se togliessi la corrente alla fire stick tv il cui stato diventa "non disponibile". Ecco cosa ho scritto:
``` yaml
media_player:
  - platform: smartir
    name: TV Letto
    unique_id: tv_letto
    device_code: 1000
    controller_data: remote.telecomando_broadlink_remote
    power_sensor: binary_sensor.stato_tv
    
    # Use the Python ADB implementation
  - platform: androidtv
    name: Fire stick TV
    host: 192.168.1.10
    apps:
      com.amazon.tv.launcher: 'Home'
      com.amazon.tv.settings.v2: 'Impostazioni'
      APP_AMAZON_VIDEO: 'Prime Video'
      APP_KODI: 'Kodi'
      APP_NETFLIX: 'Netflix'
      APP_PLEX: 'Plex'
      APP_SPOTIFY: 'Spotify'
      APP_VLC: 'VLC'
      it.dplay: 'DPLAY'
      it.rainet.androidtv: 'RaiPlay'
      it.telecomitalia.timvision.firetv: 'TIM Vision'
      com.disney.disneyplus: 'Disney+'
      com.apple.atve.amazon.appletv: 'Apple TV'
      com.amazon.firetv.youtube: 'YouTube'
      com.nowtv.it: 'NowTv'
      com.dazn: 'Dazn'
      org.courville.nova: 'Nova Video Player'
      
binary_sensor:
  - platform: template
    sensors:
      stato_tv:
        friendly_name: "Stato TV"
        value_template: "{{ off if states('media_player.fire_sick_tv') == 'off' else 'on' }}"
```

**Reply by snakuzzo** [reply]
allora adegua il template del sensore

```yaml
binary_sensor:
  - platform: template
    sensors:
      stato_tv:
        friendly_name: "Stato TV"
        value_template: "{{ off if states('media_player.fire_sick_tv') in ['off','unavailable','unknown'] else 'on' }}"
```
