### DISCUSSION TITLE
Far riconoscere i climatizzatori ad home assistant come dispositivi

### DISCUSSION THREAD

**Discussion by luxbarba** [indomus/forum#602] [HUB: Home Assistant]
Buongiorno a tutti. Ho inserito su home assistant 4 climatizzatori tramite l'integrazione Gree A/C. Funzionano tutti e 4 perfettamente. Il problema è che HA me li riconosce come entità e non come dispositivi, per cui non riesco ad inserirli nelle automazioni e nelle scene. C'è un modo di poterlo fare? Allego la mia configurazione(con mac address nascosti):
```yaml
climate:
   - platform: gree
     name: Climatizzatore Cucina
     host: 192.168.1.5
     port: 7000
     mac: xx:xx:xx:xx:xx:xx
     target_temp_step: 1
   
   - platform: gree
     name: Climatizzatore Studio
     host: 192.168.1.38
     port: 7000
     mac: xx:xx:xx:xx:xx:xx
     target_temp_step: 1
   
   - platform: gree
     name: Climatizzatore Letto
     host: 192.168.1.122
     port: 7000
     mac: xx:xx:xx:xx:xx:xx
     target_temp_step: 1
     
   - platform: gree
     name: Climatizzatore Soggiorno
     host: 192.168.1.244
     port: 7000
     mac: xx:xx:xx:xx:xx:xx
     target_temp_step: 1
```

**Comment by snakuzzo** [comment]
Questo non è un problema.
Le scene puoi farle anche basandoti sulle entità

https://indomus.it/formazione/le-scene-di-home-assistant-cosa-sono-e-come-funzionano/

**Reply by luxbarba** [reply]
Grazie. L'articolo l'avevo già letto. Ma se seleziono l'entità all'interno della scena  me lo fa solo accendere. Come faccio a settare tutti gli altri parametri (temperatura, modalità ecc...) e a spegnerlo? Ecco il codice che mi crea all'interno di scenes.yaml:
```yaml
- id: '1628680612461'
  name: Accendi condizionatore soggiorno
  entities:
    climate.climatizzatore_soggiorno:
      hvac_modes:
      - auto
      - cool
      - dry
      - fan_only
      - heat
      - 'off'
      min_temp: 16
      max_temp: 30
      target_temp_step: 1
      fan_modes:
      - Auto
      - low
      - Medium-Low
      - medium
      - Medium-High
      - high
      - Turbo
      - Quiet
      swing_modes:
      - Default
      - Swing in full range
      - Fixed in the upmost position
      - Fixed in the middle-up position
      - Fixed in the middle position
      - Fixed in the middle-low position
      - Fixed in the lowest position
      - Swing in the downmost region
      - Swing in the middle-low region
      - Swing in the middle region
      - Swing in the middle-up region
      - Swing in the upmost region
      current_temperature:
      temperature: 27
      fan_mode: Quiet
      swing_mode: Default
      friendly_name: Climatizzatore Soggiorno
      supported_features: 41
      state: cool
```
