### DISCUSSION TITLE
[RISOLTO] Nuova funzionalità "Energia"

### DISCUSSION THREAD

**Discussion by ganaweb** [indomus/forum#612] [HUB: Home Assistant]
Ciao a tutti,

sto provando a configurare il nuovo pannello "Energia".

Io attualmente possiedo il DIN Misuratore carichi (F20T60A) della Legrand/BTicino collegato ad Home Assistant tramite Zigbee2Mqtt. Naturalmente questo DIN misura la corrente istantanea e non l'energia prodotta (kWh).

Nel pannello "Energia", alla voce "Energia consumata kWh", il sistema mi scrive "Nessuna statistica corrispondente trovata".
Ho provato a seguire le guide del sito ufficiale di Home Assistant (questa https://www.home-assistant.io/blog/2021/08/04/home-energy-management/, e questa https://www.home-assistant.io/integrations/home_plus_control/), ma non sono sicuro mi porti nella strada giusta perché mi chiede di registrarmi come sviluppatore nel sito https://developer.legrand.com. Avrebbe senso se io avessi implementato il DIN tramite APP originale Legrand "Home + control" ma poiché passa per Zigbee2mqtt non penso sia la cosa giusta da fare.

Sapete dirmi come posso creare questa statistica da inserire nel pannello "Energia"?

Grazie in anticipo.

**Comment by snakuzzo** [comment]
Tu in realtà dovresti passargli un sensore che esponga il valore in KWh e per poter utilizzare "correttamente" un'entità nel pannello energia, quell'entità deve possedere alcuni requisiti specifici...

deve esporre un valore "ovviamente" crescente nel tempo
deve essere nel recorder
deve avere questi attributi...
- last_reset
- device_class: energy
- state_class: measurement

se hai sensori di tipo [utility meter](https://indomus.it/componenti/componente-home-assistant-utility-meter/) o creati con platform [integration](https://www.home-assistant.io/integrations/integration/) hai già tutto

Una volta configurato, prima di vedere i grafici, dovresti aspettare un po' di tempo

**Reply by ganaweb** [reply]
Grazie mille per la risposta tempestiva.
Mi hai aperto un mondo con i sensori "Utility meter".
Mi studierò quelle pagine ma penso di aver capito.

Grazie ancora

**Reply by ganaweb** [reply]
Inizialmente ho impostato i sensori _utility meter_ che mi servivano in questo modo:
```
utility_meter:
  energia_giornaliera:
    source: sensor.din_controllo_carichi_power
    name: Energia giornaliera
    cycle: daily
  energia_mensile:
    source: sensor.din_controllo_carichi_power
    name: Energia mensile
    cycle: monthly
  energia_annuale:
    source: sensor.din_controllo_carichi_power
    name: Energia annuale
    cycle: yearly

recorder:
  include:
    entities:
      - sensor.energia_giornaliera
      - sensor.energia_mensile
      - sensor.energia_annuale
```

sensor.din_controllo_carichi sarebbe il mio dispositivo Legrand/Bticino F20T60A.
I sensori energia (_giornaliera, _mensile e _annuale) hanno funzionato restituendomi un valore crescente nel tempo ma in Watt. Avendo bisogno dei Wattora ho reimpostato il tutto come segue:
```
sensor:
  - platform: mqtt
    name: "DIN Consumo"
    state_topic: "zigbee2mqtt/DIN controllo carichi"
    unit_of_measurement: "kWh"
    value_template: "{{ (value|float / 1000 ) | round (3) }}"

utility_meter:
  energia_giornaliera:
    source: sensor.din_consumo
    name: Energia giornaliera
    cycle: daily
  energia_mensile:
    source: sensor.din_consumo
    name: Energia mensile
    cycle: monthly
  energia_annuale:
    source: sensor.din_consumo
    name: Energia annuale
    cycle: yearly

recorder:
  include:
    entities:
      - sensor.energia_giornaliera
      - sensor.energia_mensile
      - sensor.energia_annuale
```

Il sensore DIN Consumo l'ho scopiazzato da una guida analoga per lo Shelly EM cercando di adattarla al mio dispositivo (https://indomus.it/guide/integrare-shelly-em-a-home-assistant-via-mqtt/).

Attualmente i grafici non vengono aggiornati su nessun sensore (mi avevi detto di aspettare un po' di tempo e l'ho lasciato tutta la notte).
Ho provato in entrambe le fasi a vedere se dal pannello _Energia_ mi accettasse uno dei sensori, ma nessuno viene riconosciuto. 

Cosa sto sbagliando?

Grazie dell'aiuto.

**Reply by snakuzzo** [reply]
Controlla sotto dev tools che gli utility meter abbiano quei 3 attributi. Inoltre, il primo sensore non crearlo in quel modo, ma usa platform integration

**Reply by ganaweb** [reply]
Grande!
Funziona tutto con platform Integration.

Un ultima cosa: avendo mischiato letture in W e KWh ho i dati degli _utility meter_ sballati (es. _Energia giornaliera_ è 152.731,65 kWh).
Volevo resettarli con il servizio utility_meter.reset ma non è presente su Dev Tools.
Come posso fare?

**Reply by snakuzzo** [reply]
Su questo non saprei dirti

**Reply by ganaweb** [reply]
Ok grazie comunque.
Ho forzato la cosa cambiando il nome ai sensori _utility meter_ e si sono resettati in automatico.

Riporto il codice della configurazione per i posteri:
```
sensor:
  - platform: integration
    source: sensor.din_controllo_carichi_power
    name: energia_consumata
    unit_prefix: k
    round: 2

utility_meter:
  consumo_energia_giornaliero:
    source: sensor.energia_consumata
    name: Consumo energia giornaliero
    cycle: daily
  consumo_energia_mensile:
    source: sensor.energia_consumata
    name: Consumo energia mensile
    cycle: monthly
  consumo_energia_annuale:
    source: sensor.energia_consumata
    name: Consumo energia annuale
    cycle: yearly

recorder:
  include:
    entities:
      - sensor.consumo_energia_giornaliero
      - sensor.consumo_energia_giornaliero_cost  #entità creata da home assistant da inserire nel recorder
      - sensor.consumo_energia_mensile
      - sensor.consumo_energia_annuale
 ```

Grazie ancora.

**Comment by essegi65** [comment]
Prendo spunto da sopra per esporre il mio problema:
ho dei sonoff pow che funzionano perfettamente (come letture di assorbimento e potenza) ho configurato dei utility_meter come indicato sotto:
```
utility_meter:
  energia_lavatrice_kwh:
    source: sensor.energia_oggi_lavatrice
    cycle: daily
  energia_autoclave_kwh:
    source: sensor.energia_oggi_autoclave
    cycle: daily
  energia_forno_kwh:
    source: sensor.energia_oggi_forno
    cycle: daily
```
sia il sensore della lavatrice che quello dell'autoclave hanno i 3 attributi di cui parla @snakuzzo, mentre il sensore del forno gli manca il device_class come indicato nell'immagine 
![Immagine 2021-08-17 145109](https://user-images.githubusercontent.com/60359328/129728869-4ca73e70-4d64-440b-8f31-60ae2b63346a.jpg)

Mi aiutate a capire dove sta l'errore, grazie
