### DISCUSSION TITLE
Entita: non ha ID univoco

### DISCUSSION THREAD

**Discussion by DigoGibin** [indomus/forum#614] [HUB: Home Assistant]
Ciao a tutti, ho da poco iniziato a pasticciare con homeassistant dopo aver fatto un po' di studio sul vostro sito e fin qui tutto contento è anadato tutto bene. ora però veniamo al punto crtico ho cercato anche nel forum ma non ho trovato una soluzione.

Quando vado ad aggiungere un ulteriore shelly 2.5 mi da l'errore "Questa entità (".....") non ha un ID univoco" e non so come risolvere.
Provo ad aggiungere qualche fato in più:
come home hassistant ho installato la versione HASSIO
ho già attulamente 1 shelly uno e 1 shelly 2.5 che funzionano e comunicano con MQTT
qui di seguito aggiungo la parte di codice di quello non funzionante, vorrei capire bene dove sbaglio dovendone aggiungere molti altri

SEZIONE LUCI:
```
    #BAGNO
  - platform: mqtt
    name: "Stato comando esterno LUCE BAGNO"
    payload_on: "on"
    payload_off: "off"
    device_class: power
    state_topic: "shellies/LuceBagnoSpecchioBagno/input/0"
    value_template: "{% if value == '1' %} on {% else %} off {% endif %}" 
    payload_available: "true"
    payload_not_available: "false"

    #SPECCHIO BAGNO 
  - platform: mqtt
    name: "Stato comando esterno LUCE SPECCHIO BAGNO"
    payload_on: "on"
    payload_off: "off"
    device_class: power
    state_topic: "shellies/LuceBagnoSpecchioBagno/input/1"
    value_template: "{% if value == '1' %} on {% else %} off {% endif %}" 
    payload_available: "true"
    payload_not_available: "false"`
```
SEZIONE BINARY SENSOR:
``` 
  #BAGNO
  - platform: mqtt
    name: "Stato comando esterno LUCE BAGNO"
    payload_on: "on"
    payload_off: "off"
    device_class: power
    state_topic: "shellies/LuceBagnoSpecchioBagno/input/0"
    value_template: "{% if value == '1' %} on {% else %} off {% endif %}" 
    payload_available: "true"
    payload_not_available: "false"

    #SPECCHIO BAGNO 
  - platform: mqtt
    name: "Stato comando esterno LUCE SPECCHIO BAGNO"
    payload_on: "on"
    payload_off: "off"
    device_class: power
    state_topic: "shellies/LuceBagnoSpecchioBagno/input/1"
    value_template: "{% if value == '1' %} on {% else %} off {% endif %}" 
    payload_available: "true"
    payload_not_available: "false"
```
SEZIONE AUTOMAZIONE:
```
- alias: MQTT Announce
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: mqtt.publish
    data:
      payload: announce
      topic: shellies/command'''
```
mi scuso subito per la lunghezza del post ma sono da giorni arenato qui e non trovo soluzione
Grazie anticipato a chi vorrà aiutarmi

**Comment by snakuzzo** [comment]
Il codice deve essere inserito correttamente con il markdown. Correggi altrimenti devo cancellare il topic.
Grazie

**Reply by DigoGibin** [reply]
Ciao , spero di aver corretto nel modo giusto

**Comment by snakuzzo** [comment]
A prescindere dall'oggetto del topic...

Ti consiglierei innanzi tutto di utilizzare dei topic "più corti" (e anche più sensati a mio parere) perché potresti anche avere problemi con la connessione al broker MQTT

Per quanto riguarda le entità relative alle luci, ci sono diverse cose che non vanno. Non so quali guide tu abbia seguito, ma di sicuro per configurare questo shelly 2.5 non hai seguito la [nostra](https://indomus.it/guide/integrare-shelly-2-5-a-home-assistant-via-mqtt/)

1. Manca l' `availability_topic`. Hai impostato solo i payload
2. Manca il `command_topic`
3. la `device_class` non puoi impostarla lì
4. Non so perché utilizzi `value_template`...ma resta il fatto che è deprecato in funzione di `state_value_template`. Resta comunque il fatto che, visto che lo `state_topic` ti restituisce già `on` o `off`, non ha senso impostare un template.

Se l'obiettivo è quello di usare platform light, ti consiglio di ridare un'occhiata alla [documentazione ufficiale](https://www.home-assistant.io/integrations/light.mqtt/)

Di seguito il codice per le luci...

```yaml
light:

  - platform: mqtt
    name: "luce_bagno"
    state_topic: "shellies/LuceBagnoSpecchioBagno/relay/0"
    command_topic: "shellies/LuceBagnoSpecchioBagno/relay/0/command"
    availability_topic: "shellies/LuceBagnoSpecchioBagno/online"
    optimistic: false
    payload_on: "on"
    payload_off: "off"
    payload_available: "true"
    payload_not_available: "false"
    retain: false
    qos: 1

  - platform: mqtt
    name: "luce_specchio_bagno"
    state_topic: "shellies/LuceBagnoSpecchioBagno/relay/1"
    command_topic: "shellies/LuceBagnoSpecchioBagno/relay/1/command"
    availability_topic: "shellies/LuceBagnoSpecchioBagno/online"
    optimistic: false
    payload_on: "on"
    payload_off: "off"
    payload_available: "true"
    payload_not_available: "false"
    retain: false
    qos: 1
 ```
 
 I sensori binari invece sembrano quasi ok, al netto del `value_template` che, come detto anche sopra, non dovrebbe servire e della mancanza dell' `availability_topic`
 
 ```yaml
 binary_sensor:

  - platform: mqtt
    name: "stato_luce_bagno"
    payload_on: "on"
    payload_off: "off"
    device_class: power
    state_topic: "shellies/LuceBagnoSpecchioBagno/input/0"
    availability_topic: "shellies/LuceBagnoSpecchioBagno/online" 
    payload_available: "true"
    payload_not_available: "false"

  - platform: mqtt
    name: "stato_luce_specchio_bagno"
    payload_on: "on"
    payload_off: "off"
    device_class: power
    state_topic: "shellies/LuceBagnoSpecchioBagno/input/1"
    availability_topic: "shellies/LuceBagnoSpecchioBagno/online" 
    payload_available: "true"
    payload_not_available: "false"
 ```
 
 Nessun errore nel log...e questo è il risultato...
 
![capture_2021-08-07_17-05](https://user-images.githubusercontent.com/7205371/129456666-0bd3a48a-0844-440b-a1df-4cd17bfd5c3c.png)
