### DISCUSSION TITLE
platform template

### DISCUSSION THREAD

**Discussion by toniobr1976** [indomus/forum#616] [HUB: Home Assistant]
Salve, ho provato a seguire il tutorial e sono riuscito ad integrare in HA i valori di potenza del module Shelly EM.
Sto invece riscontrando difficoltà nel visualizzare il valore somma attraverso il comando platform:template.
Qualcuno riesce a capire dove sbaglio?
Allego il codice :
```

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


sensor:
  - platform: mqtt
    name: "Produzione pannelli"
    state_topic: "shellies/shellyem-contatore/emeter/0/power"
    value_template: "{{ value }}"
    unit_of_measurement : "Watt"
    icon: mdi:speedometer
  - platform: mqtt
    name: "Carichi"
    state_topic: "shellies/shellyem-contatore/emeter/1/power"
    value_template: "{{ value }}"
    unit_of_measurement : "Watt"
    icon: mdi:speedometer
  - platform: template 
    sensors:
      shelly_em_assorbimento:
        friendly_name: "Consumo attuale"
        value_template: '{{ (states("sensor.produzione_pannelli")|float + states("sensor.carichi")|float)|float|round(1) }}'
        unit_of_measurement : "Watt"
        icon: mdi:speedometer
```

**Comment by snakuzzo** [comment]
```yaml
  - platform: template 
    sensors:
      shelly_em_assorbimento:
        friendly_name: "Consumo attuale"
        value_template: "{{ ( states('sensor.produzione_pannelli') | float + states('sensor.carichi') | float ) | round(1) }}"
        unit_of_measurement : "W"
        icon: mdi:speedometer
```
