### DISCUSSION TITLE
webhook come trigger di automazioni

### DISCUSSION THREAD

**Discussion by Nik71git** [indomus/forum#618] [HUB: Home Assistant]
Ciao a tutti, ho questa semplice automazione che ...non parte,

```
alias: notifica motioneye davanti
description: notifica 39
trigger:
  - platform: webhook
    webhook_id: >-
      http://192.168.1.7:8123/api/webhook/<il mio webhook_id identico a quello della cam di motioneyeOS, se serve lo posto>
condition: []
action:
  - service: persistent_notification.create
    data:
      message: davanti
      title: rilevato movimento
      notification_id: '39'
  - service: notify.mobile_app_nicola
    data:
      message: davanti
      title: rilevato movimento
      data:
        tag: 39
mode: single
```
non essendo molto pratico con GET e POST, c'è qualcosa che notate come errato? il POST è di tipo JSON, posso metterlo anche come QUERY e come FORM, ma credo che non cambi nulla.

**Comment by snakuzzo** [comment]
Hai toppato alla grandissima :)
Nel trigger non è che metti la chiamata che faresti con una cURL ad esempio...devi semplicemente specificare un `webhook_id` come indicato anche [QUI](https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger)

Guarda questa automazione di esempio che ho fatto ora per farti vedere come funziona...

```yaml
automation:
- id: prova_webkook
  alias: "Prova Webhook"
  trigger:
    - platform: webhook
      webhook_id: "miowebhook"
  action:
    - service: persistent_notification.create
      data:
        message: "Ciao!"
        title: "Prova Webhook"
        notification_id: '1'
```

Il webook id avrà valore `miowebhook` ... basta impostarlo nel trigger

e poi farai una chiamata in POST dal client che ti pare (ad esempio con cURL, ma poi bisogna vedere da dove vorrai farla) passando il webhook id che hai inserito nel trigger dell'automazione

`curl -X POST http://192.168.1.10:8124/api/webhook/miowebhook`

![capture_2021-08-07_17-05](https://user-images.githubusercontent.com/7205371/129578696-126091fa-fee8-48ab-b74a-b6bb28c6974b.png)
