### DISCUSSION TITLE
Problemi con Shelly EM e calcolo consumi

### DISCUSSION THREAD

**Discussion by fizzi** [indomus/forum#62] [HUB: Home Assistant]
Ciao a tutti,

volevo sottoporvi questo problema che ho riscontrato integrando shelly em con home assistant.

La mia configurazione:

**Versione HA | core-2021.3.4
Tipo di installazione | Home Assistant Container
Shelly EM configurato per inviare su Mosquitto MQTT** 

>Il firmware sullo shelly em:
>Current version: 20210323-110329/v1.10.1-gf276b51
>You have latest version on your device!

Nel configuration.yaml

```yaml
sensor:
 - platform: mqtt
   name: "Shelly EM Consumo ch1"
   state_topic: "shellies/shellyem-E45FEB/emeter/0/total"
   unit_of_measurement: 'kWh'
   value_template: "{{ (value|float / 1000 ) | round (3) }}"
 - platform: mqtt
   name: "Shelly EM Consumo ch2"
   state_topic: "shellies/shellyem-E45FEB/emeter/1/total"
   unit_of_measurement: 'kWh'
   value_template: "{{ (value|float / 1000 ) | round (3) }}"
 - platform: template
   sensors:
     shelly_em_consumo:
       friendly_name: "Shelly EM Consumo"
       value_template: '{{ (states("sensor.shelly_em_consumo_ch1")|float + states("sensor.shelly_em_consumo_ch2")|float)|float|round(1) }}'
       unit_of_measurement : "kWh"
       icon_template: mdi:speedometer
```

inoltre ho configurato l'utility meter come segue:

```yaml
utility_meter:
  daily_energy:
    source: sensor.shelly_em_consumo
    cycle: daily 
    tariffs:
      - F1
      - F23
  monthly_energy:
    source: sensor.shelly_em_consumo
    cycle: monthly
    tariffs:
      - F1
      - F23
```

Per calcolare i consumi nelle fasce F1 F23 come prima cosa ho configurato:

```yaml
binary_sensor:
 - platform: workday
   name: Giorni Lavorativi
   country: IT
```

E creato queste due automazioni:

```yaml
- id: '28'
  alias: ENERGIA - Semplice Luce Feriali
  description: Cambia tipo di contatore a seconda della fascia oraria nei giorni feriali
  trigger:
  - platform: time
    at: 08:00:00
  - platform: time
    at: '19:00:00'
  condition:
  - condition: state
    entity_id: binary_sensor.giorni_lavorativi
    state: 'on'
  action:
  - service: utility_meter.next_tariff
    data:
      entity_id: utility_meter.daily_energy
  - service: utility_meter.next_tariff
    data:
      entity_id: utility_meter.monthly_energy
  mode: single
- id: '29'
  alias: ENERGIA - Semplice Luce Festivi
  description: Cambia tipo di contatore a seconda della fascia oraria nei giorni festivi
  trigger:
  - platform: state
    entity_id: binary_sensor.giorni_lavorativi
    to: 'off'
  condition: []
  action:
  - service: utility_meter.select_tariff
    data:
      entity_id: utility_meter.daily_energy
      tariff: F23
  - service: utility_meter.select_tariff
    data:
      entity_id: utility_meter.monthly_energy
      tariff: F23
  mode: single
```
Il risultato ottenuto è esattamente quello che volevo come potete osservare nell'immagine seguente:

<img width="1016" alt="Schermata 2021-03-30 alle 08 40 23" src="https://user-images.githubusercontent.com/444291/112944795-9ee37b00-9133-11eb-8b14-43fad9e62643.png">

**Veniamo al PROBLEMA**
Fino a quando HA non viene riavviato il tutto funziona perfettamente ... i consumi vengono calcolati in maniera corretta e precisa.

Ok ... ecco quello che accade dopo un riavvio "senza aver modificato nulla sulla configurazione" :

<img width="644" alt="Schermata 2021-03-30 alle 08 49 14" src="https://user-images.githubusercontent.com/444291/112945736-ee767680-9134-11eb-881e-b13d028263c4.png">

come è possibile vedere dall'immagine sono passato da 0.3 Kwh a 44.1 ... questo nel tempo che si è riavviato HA (circa 10 secondi) 

Effettuando un altro riavvio:

<img width="719" alt="Schermata 2021-03-30 alle 08 57 15" src="https://user-images.githubusercontent.com/444291/112946556-f4208c00-9135-11eb-884e-dcf6b7cf054a.png">

Avete idee o workaround? 

Grazie mille a tutti,

**Comment by gabrio79** [comment]
non so aiutarti ma posso fare test per vedere se capita anche a me io ho hass.io su rp4 dedicato (non core, no docker)

PS: mi dai il codice che hai usato per il mini-chart?

**Reply by fizzi** [reply]
```yaml
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.monthly_energy_f1
    name: Consumo Mensile F1
    show_state: true
    show_indicator: true
    state_adaptive_color: true
  - entity: sensor.monthly_energy_f23
    name: Consumo Mensile F23
    show_state: true
    show_indicator: true
    state_adaptive_color: true
name: Consumo Mensile Energia
animate: true
hour24: true
hours_to_show: 168
group_by: date
show:
  graph: bar
```

**Comment by gabrio79** [comment]
io non ho notato il tuo errore
dopo il riavvio (HA solo non RPI)
![Screen Shot 2021-03-30 at 09 42 32](https://user-images.githubusercontent.com/65911264/112952078-63997a00-913c-11eb-9ae5-7154ae884da3.png)
prima del riavvio
![Screen Shot 2021-03-30 at 09 35 54](https://user-images.githubusercontent.com/65911264/112952080-64caa700-913c-11eb-9607-4b6223a28c57.png)

**Reply by gabrio79** [reply]
sono un pirla, io sto calcolando emeter su potenza istantanea e non sul consumo

**Reply by fizzi** [reply]
Sei passato da 783,167.55 W a 809,781.03 W .... perchè Watt ?

**Reply by gabrio79** [reply]
perchè ho preso qualche minuto dopo direi...

**Reply by gabrio79** [reply]
ora sono a 850

**Reply by baurbr** [reply]
@fizzi  scusa la domanda da newbie... ma come fai ad avere quel grafico istogramma? 
Grazie

**Reply by fizzi** [reply]
https://github.com/indomus/forum/discussions/62?sort=new#discussioncomment-546784

**Comment by davidedipa** [comment]
Buongiorno, scusate se "sfrutto" la discussione ma avrei bisogno di aiuto con lo Shelly EM.
L'ho installato qualche giorno fa per monitorare i consumi e per la gestione dei carichi (elettrodomestici). L'installazione è stata semplice ma ora ho qualche problema con l'integrazione MQTT su HA. Premetto che ho circa una ventina di Shelly sparsi per casa (1, 1PM e 2.5) tutti perfettamente integrati e funzionanti con HA.

Questo il sensor inserito nel file di config per l'EM

  - platform: mqtt
    name: "Shelly EM Assorbimento ch1"
    state_topic: "shellies/Controllo_Carichi/emeter/0/power"
    value_template: "{{ value }}"
    unit_of_measurement : "Watt"
    icon: mdi:speedometer
  - platform: mqtt
    name: "Shelly EM Voltampere reattivo ch1"
    state_topic: "shellies/Controllo_Carichi/emeter/0/reactive_power"
    unit_of_measurement: "VAR"
    icon: mdi:speedometer
  - platform: mqtt
    name: "Shelly EM Tensione"
    state_topic: "shellies/Controllo_Carichi/emeter/0/voltage"
    unit_of_measurement: "Volt"
    icon: mdi:flash-circle

Sostanzialmente quando vado ad aggiungere a Lovelace l'entità non mi restituisce nulla poiché dice che l'entità (Ad esempio Assorbimento) non è un numero.
Sicuramente ho sbagliato qualcosa ma non riesco a capire cosa. Da app Shelly funziona tutto perfettamente.
Potete aiutarmi?

Grazie mille,
Davide

**Reply by snakuzzo** [reply]
Ciao...

1. Correggi il post ed usa il markdown per il codice (leggi [QUI](https://github.com/indomus/forum#readme))
2. Hai sbagliato a scrivere le entità (leggi [QUI](https://indomus.it/guide/integrare-shelly-em-a-home-assistant-via-mqtt/))

**Reply by davidedipa** [reply]
Grazie mille per la risposta intanto e scusate per la mancanza del markdown. Rimedio subito.
Per quanto riguarda l'errore nella scrittura ti chiedo davvero di scusarmi ma non riesco ad individuare l'errore. Al di là del ch2 (che non ho inserito perché ho solo 1 pinza amperometri) e del NOME_SHELLY (incui ho inserito il mio) non vedo differenze con la guida inDomus che ho seguito.
Posso chiederti di indicarmi l'errore?
Grazie ancora e scusate se sono un pò "di coccio" :)

```
  - platform: mqtt
    name: "Shelly EM Assorbimento ch1"
    state_topic: "shellies/Controllo_Carichi/emeter/0/power"
    value_template: "{{ value }}"
    unit_of_measurement : "Watt"
    icon: mdi:speedometer
    
  - platform: mqtt
    name: "Shelly EM Voltampere reattivo ch1"
    state_topic: "shellies/Controllo_Carichi/emeter/0/reactive_power"
    unit_of_measurement: "VAR"
    icon: mdi:speedometer
    
  - platform: mqtt
    name: "Shelly EM Tensione"
    state_topic: "shellies/Controllo_Carichi/emeter/0/voltage"
    unit_of_measurement: "Volt"
    icon: mdi:flash-circle
```

**Reply by gabrio79** [reply]
Per prima cosa ti suggerisco di verificare di avere configurato sullo shelly che il messaggio Prefix MQTT sia Controllo_Carichi e non quello standard ShellyEM-XYZ

**Reply by snakuzzo** [reply]
Non credo sia un problema di topic MQTT.
@davidedipa devi postare l'errore che ti dà HA (magari anche quello che scrive nel log).
A pelle, in base a quello che hai scritto, ti direi che c'è un problema con il template del primo sensore...ma dovresti postare l'errore preciso

**Comment by davidedipa** [comment]
Ciao! Perdonate l’assenza ma è stato un periodo complicato…
Ad ogni modo volevo ringraziarvi molto per l’aiuto. In realtà ho ricontrollato per benino il codice ed era scritto tutto correttamente…con mia grande sorpresa, senza aver fatto nulla ha iniziare a funzionare correttamente dopo qualche giorno. Ora va benissimo, tutto alla grande sia il sensore che le automazioni associate.
Grazie mille per l’aiuto!
D.

**Comment by danros3** [comment]
@fizzi : Ciao
Io mi trovo esattamente con lo stesso problema.
Shelly 1pm integrato in HA con integrazione nativa (non mqtt). I meter forniti da shelly funzionano.
Poi io devo distinguere l'energia che misuro se è prodotta da FTV oppure acquistata da rete. Ho creato un template

```
  - platform: template
    sensors:
      opel_corsa_potenza_da_rete_f:
        friendly_name: "opel_corsa_potenza_da_rete_f"
        value_template: "{% if states('sensor.opel_corsa_power_f')|float <= 5 %} 0.0 {% else %}
        {% if states('sensor.mains_power') |float <= 85 %} 0.0 {% else %}
        {% if states('sensor.mains_power') |float < states('sensor.opel_corsa_power_f')|float %}
        {{ states('sensor.mains_power')|float }} {% else %}
        {{ states('sensor.opel_corsa_power_f')|float }}
        {% endif %}
        {% endif %}
        {% endif %}"

## Calcolo potenza ed energia da rete opel corsa ##
  - platform: integration
    source: sensor.opel_corsa_potenza_da_rete_f
    name: opel_corsa_energia_da_rete_f_kws
    unit_time: s
    unit_prefix: k
    round: 3
  - platform: template
    sensors:
      opel_corsa_energia_da_rete_f_kwh:
        friendly_name: "opel_corsa_energia_da_rete_f_kwh"
        value_template: "{{ (states('sensor.opel_corsa_energia_da_rete_f_kws')|float /3600)|round(3) }}"
        unit_of_measurement: 'kWh'

  opel_energy_meter_da_rete_daily:
    source: sensor.opel_corsa_energia_da_rete_f_kwh
    cycle: daily
```

In effetti mi fa lo stesso problema segnalato: in sostanza, molte volte non parte da zero ma parte da valori variabili, Ad esempio oggi mi ha fatto un +0.20kwh senza colpo ferire, poi è aumentato correttamente. Altri giorni in passato che incrementato anche di 15kwh.

![Print Screen - 20210719 175750 - 001](https://user-images.githubusercontent.com/69107406/126190684-7a8791b1-84bc-4adc-83f8-c1cafc22b2e3.jpg)

Grazie a chi mi potrà aiutare.

Daniele
