### DISCUSSION TITLE
Valvole termostatiche collegate a termometro esterno

### DISCUSSION THREAD

**Discussion by maurominella** [indomus/forum#624] [HUB: Home Assistant]
Buongiorno a tutti. Forse non ho cercato abbastanza, ma mi pare che non sia mai stato risolto in modo completo il problema di trasmettere la "vera" temperatura della stanza alla valvola termostatica (aka termostato).
Non è un problema risolvibile a livello di valvola perché inevitabilmente la temperatura intorno al calorifero è più alta, quindi per quanto preciso il suo sensore di temperatura legge la temperatura che c'è in quel punto.
Con la conseguenza che chiude la valvola prima che la temperatura della stanza sia arrivata alla soglia impostata. Idem quando deve spegnerla: appena riapre la valvola, la temperatura lì vicino sale subito e lui la spegne di nuovo, lasciando la stanza più fredda di quanto desiderato.
Ho provato, ma la soluzione non è nemmeno impostare la tolleranza nelle valvole/app che la prevedono, o banalmente impostare la temperatura di un paio di gradi sopra quella desiderata: a seconda dal fatto che si stia riscaldando o si stia raffreddando la differenza arriva anche a 5 gradi.
Una soluzione perfetta l'ha trovata IQ-3 con i prodotti della linea Max! che prevedono la possibilità di abbinare a ciascuna valvola un termometro esterno, che di fatto sostituisce il suo sensore interno di temperatura. Però è una soluzione costosa, proprietaria e ora perfino abbandonata in quanto hanno sostituito tutta la loro gamma di prodotti con una nuova linea non compatibile.

Però noi abbiamo HA, quindi vorrei capire se qualcuno ha risolto il problema in modo semplice.
Questo è ciò che ho fatto io, magari si può usare come punto di partenza:
- Acquistato prodotti separati e indipendenti: Tuya Zigbee Radiator (la valvola - 5X26 euro), Tuya Zigbee Sensore di temperatura/umidità (6X15 euro) e Sonoff Zigbee Bridge (1X18 euro)
- Patchato il firmware Tasmota sullo Zigbee Bridge
- Installato HA su una macchina virtuale (in ambiente Docker) esposta nel cloud Microsoft Azure in modo che possa controllare tutto via internet
- Rilevati tutti i dispositivi (5 valvole + 6 termometri incluso uno sul balcone)
- Configurato HA con uno script python legato ad un trigger che scatta quando la temperatura sulla valvola o sul termometro "attraversa" la soglia impostata, che determinerebbe l'apertura/chiusura della valvola
- lo script prende in ingresso l'entity ID della valvola e del "suo" termometro dedicato, e "forza" la temperatura rilevata dalla valvola usando il valore rilevato dal termometro che si trova nella stessa stanza.

Il problema, al di là del tempo notevole che ho impiegato per fare tutto questo partendo da zero, è che dopo pochi secondi (da 0 a 70 secondi), la valvola "resetta" la sua temperatura usando quella rilevata dal suo sensore interno. Quindi è un continuo trasmettere nuova temperatura fra tutti i dispositivi.

Insomma, mi sembra di aver sparato alle mosche con un cannone. Qualcuno ha risolto il problema in maniera più intelligente?

Grazie a tutti

**Comment by snakuzzo** [comment]
Secondo me puoi semplicemente fare in questo modo:

- Crei uno [Switch Template](https://www.home-assistant.io/integrations/switch.template/) per ogni testa termostatica in modo che con `on` apra completamente la valvola e con `off` la chiuda (Questo è da verificare..perché dovresti fare in modo di non permettere mai alla valvola di chiudersi in autonomia. Magari se è possibile impostare un offset sulla stessa valvola si risolve facile)

Crei un entità di tipo [Generic Thermostat](https://www.home-assistant.io/integrations/generic_thermostat) passando come `heater` lo switch creato e come `sensor` un qualsiasi sensore di temperatura configurato su HA

Esempio: (non testato, scritto al volo)

```yaml
switch:
  - platform: template
    switches:
      testa01_switch:
        value_template: "{{ states('climate.testa01') in ['heat','auto'] }}"
        turn_on:
          service: climate.turn_on
          target:
            entity_id: climate.testa01
        turn_off:
          service: climate.turn_off
          target:
            entity_id: climate.testa01

climate:
  - platform: generic_thermostat
    name: testa01_custom
    heater: switch.testa01_switch
    target_sensor: sensor.soggiorno_temperature
    min_temp: 15
    max_temp: 30
    ac_mode: false
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    precision: 0.1
```
