### DISCUSSION TITLE
Comando rapido per riavviare Home Assistant

### DISCUSSION THREAD

**Discussion by luxbarba** [indomus/forum#626] [HUB: Home Assistant]
Buongiorno a tutti. Vorrei creare un comando rapido per riavviare home assistant. Documentandomi ho scritto una cosa del genere ma non va:
```
script:
  hass_restart:
    alias: Restart Home Assistant
    sequence:
    - service: homeassistant.restart
    
type: entities
entities:
  - type: buttons
    name: Riavvia Home Assistant
    show_state: false
    tap_action:
  action: call-service
  service: script.hass_restart
```

**Comment by snakuzzo** [comment]
1. Controlla il log quando chiami il servizio
2. Perché chiami uno script (in maniera sbagliata inoltre) al posto di chiamare direttamente il service?

Lo script si chiama con il service `script.turn_on`, non come hai fatto tu

Es.

```yaml
service: script.turn_on 
target:
  entity_id: script.tuoscript
```

Invece nel tuo bottone puoi provare a mettere direttamente...

```yaml
service: homeassistant.restart
```

**Reply by Larry-78** [reply]
...scusate se mi intrometto ma qualche tempo fa mi ero informato sulle differenze di esecuzione degli script e mi è sembrato di capire che si possono eseguire direttamente (es. `service: script.nome_script` ) oppure con `service: script.turn_on`
Il riferimento alla documentazione ufficiale per comprendere le differenze [si trova qui](https://www.home-assistant.io/integrations/script/#waiting-for-script-to-complete)
In caso contrario sarei lieto di approfondire.

**Reply by snakuzzo** [reply]
Ah ottimo!
Grazie per aver fatto notare questa cosa. Sinceramente la ignoravo completamente. Molto utile saperlo.

Per quanto riguarda invece l'utilizzo di @luxbarba, premesso che non ho mai provato ad utilizzarlo in questo modo, la cosa rende ancora più errata la soluzione che aveva adottato. Dico questo perché, alla luce di quanto ha appena linkato @Larry-78, se esegui uno script da HA (con il button ad esempio), il "chiamante" resta in attesa del completamento dello script ma, visto che si sta chiamando uno script che riavvia Core, non so se lo stesso HA prima di riavviarsi riuscirà a comunicare l'esito della chiamata. Ti torna @Larry-78 ?
Quindi, secondo questo ragionamento, confermerei il mio suggerimento nel mio precedente post...ovvero di utilizzare nel button direttamente il servizio di restart

```yaml
type: entities
entities:
  - type: buttons
    name: Riavvia Home Assistant
    show_state: false
    tap_action:
  action: call-service
  service: homeassistant.restart
```

**Reply by KC-inDomus** [reply]
Figata, grazie Larry per la dritta. Si tratta di un dettaglio molto fine e molto interessante.

**Reply by luxbarba** [reply]
> Ah ottimo!
> Grazie per aver fatto notare questa cosa. Sinceramente la ignoravo completamente. Molto utile saperlo.
> 
> Per quanto riguarda invece l'utilizzo di @luxbarba, premesso che non ho mai provato ad utilizzarlo in questo modo, la cosa rende ancora più errata la soluzione che aveva adottato. Dico questo perché, alla luce di quanto ha appena linkato @Larry-78, se esegui uno script da HA (con il button ad esempio), il "chiamante" resta in attesa del completamento dello script ma, visto che si sta chiamando uno script che riavvia Core, non so se lo stesso HA prima di riavviarsi riuscirà a comunicare l'esito della chiamata. Ti torna @Larry-78 ?
> Quindi, secondo questo ragionamento, confermerei il mio suggerimento nel mio precedente post...ovvero di utilizzare nel button direttamente il servizio di restart
> 
> ```yaml
> type: entities
> entities:
>   - type: buttons
>     name: Riavvia Home Assistant
>     show_state: false
>     tap_action:
>   action: call-service
>   service: homeassistant.restart
> ```
Ho provato ad inserire questo codice nel configuration.yaml ma di da questo errore:
```
Error loading /config/configuration.yaml: while parsing a block collection
in "/config/configuration.yaml", line 170, column 3
expected <block end>, but found '?'
in "/config/configuration.yaml", line 174, column 3
```
dove line 170 corrisponde a show state mentre line 174 corrisponde alla riga vuota sotto il codice

**Reply by snakuzzo** [reply]
Quel codice non va nel `configuration.yaml`, ma immagino che sia la card di tipo button su lovelace.
Io ho dato per scontato che avessi creato una card di quel tipo...non è così ?
Ad ogni modo...

Rimuovi quel blocco di codice dal `configuration.yaml`. Vai sulla webGUI di HA (lovelace) e crei una nuova card di tipo "Pulsante" (button)

![capture_2021-08-07_17-05](https://user-images.githubusercontent.com/7205371/130044641-17f7b6c2-2f46-467a-9e06-670807857d47.png)


![capture_2021-08-07_17-05](https://user-images.githubusercontent.com/7205371/130044241-dcfe0321-13bf-46cc-8227-3f5478fcedaa.png)

Per completezza il codice YAML che visualizzerai cliccando su "Mostra editor di codice":

```yaml
type: button
tap_action:
  action: call-service
  service: homeassistant.restart
hold_action:
  action: none
show_name: true
name: Restart Core
icon: mdi:restart
show_icon: true
```

**TESTATO ORA E FUNZIONANTE**
