### DISCUSSION TITLE
Problema automazione

### DISCUSSION THREAD

**Discussion by Akkor70** [indomus/forum#63] [HUB: Home Assistant]
Ho un problema con le condizioni di questa automazione
Vorrei che l'automazione on funzionasse solo all'interno di un determinato orario (7.30-00.30) e solo quando almeno uno dei due telefoni si trova in zona casa

```
- alias: "Trigger corridoio on"
  trigger:
    platform: state
    entity_id: binary_sensor.sensore_corridoio_ias_zone, binary_sensor.sensore_corridoio_2_ias_zone
    to: "on"
  condition:
  - condition: time
    after: 07:30:00
    before: 00:30:00
  - condition: and
    conditions:
    - condition: zone
      entity_id: device_tracker.mi_9t_pro
      zone: zone.home
    - condition: or
      conditions:
      - condition: zone
        entity_id: device_tracker.redmi_note_9_pro
        zone: zone.home
  action:
    service: switch.turn_on
    target:
      entity_id: switch.sonoff_10005fdbdb

- alias: "Trigger corridoio off"
  trigger:
    platform: state
    entity_id: binary_sensor.sensore_corridoio_ias_zone, binary_sensor.sensore_corridoio_2_ias_zone
    to: "off"
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  action:
    service: switch.turn_off
    target:
      entity_id: switch.sonoff_10005fdbdb`
```

**Comment by snakuzzo** [comment]
Prova così...

```yaml
- alias: "Trigger corridoio on"
  trigger:
    platform: state
    entity_id: binary_sensor.sensore_corridoio_ias_zone, binary_sensor.sensore_corridoio_2_ias_zone
    to: "on"
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '07:30:00'
      before: '00:30:00'
    - condition: or
      conditions:
      - condition: zone
        entity_id: device_tracker.mi_9t_pro
        zone: zone.home
      - condition: zone
        entity_id: device_tracker.redmi_note_9_pro
        zone: zone.home
  action:
    service: switch.turn_on
    target:
      entity_id: switch.sonoff_10005fdbdb

- alias: "Trigger corridoio off"
  trigger:
    platform: state
    entity_id: binary_sensor.sensore_corridoio_ias_zone, binary_sensor.sensore_corridoio_2_ias_zone
    to: 'off'
    for:
      minutes: 1
  action:
    service: switch.turn_off
    target:
      entity_id: switch.sonoff_10005fdbdb`
```

che poi è sostanzialmente quello che trovi [QUI](https://www.home-assistant.io/docs/scripts/conditions/#mixed-and-and-or-conditions)

P.S. Volendo potresti anche accorpare tutto in una sola automazione, però prova prima a vedere se ora funziona
