### DISCUSSION TITLE
Antifurto365 iAlarm

### DISCUSSION THREAD

**Discussion by Franco2255** [indomus/forum#630] [GENERALE - Discussioni generiche]
ciao a tutti, volevo sapere se era possibile creare un'automazione. che quando attivo l'antifurto si accende una luce e viceversa.
Grazie

**Comment by snakuzzo** [comment]
Sì

**Reply by Franco2255** [reply]
Grazie dove trovo una guida ?

**Reply by essegi65** [reply]
Devi seguire la guida su come costruire un automazione la trovi su indomus.it
Come trigger metti il cambiamento di stato del pannello di allarme, se vuoi inserisci la o le condizioni, e come azione chiami il servizio di accensione luci e gli dici quali luci vuoi che si accenda.

**Reply by Franco2255** [reply]
ho creato questa automazione (premetto che da 1 a 100 sono a -10 )

```yaml
- alias: Antifurto inserito
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ialarm, switch.casetta2
  action:
  - service_template: >-
      {% if trigger.to_state.state == 'attiva_fuori_casa' %} 
        switch.turn_on
      {% else %} 
        switch.turn_off
      {% endif %}
    data:
      entity_id: alarm_control_panel.ialarm, switch.casetta2 
```

non mi da errori lo switch non cambia stato l'unico risultato lo switch non sta inserito.
Qualcuno mi cazziera perchè non so come postare correttamente l'automazione.

**Reply by snakuzzo** [reply]
te l'ho formattata correttamente io. Vai in edit sul tuo messaggio e vedi come si fa.

**Reply by snakuzzo** [reply]
non esiste alcun trigger `"attiva_fuori_casa"` ... quella è la traduzione in italiano. Lo stato "reale" è diverso e lo puoi trovare sotto dev tools > states

**Reply by snakuzzo** [reply]
Inoltre non ha senso scritto così...il trigger l'hai definito per più entità e poi nella action verifichi solo il trigger dell'allarme.
E' da rivedere

**Reply by Franco2255** [reply]
ho provato anche con arm_awey , 
perchè questa automazione se la uso su due switch funziona?

**Reply by snakuzzo** [reply]
awey ? Sul serio? :D
Controlla bene... :)

**Reply by Franco2255** [reply]
scusa away

**Comment by Franco2255** [comment]
![antifurto1](https://user-images.githubusercontent.com/59472878/130122117-e8ebfb7f-11da-47de-8cc4-fb8221855dd5.PNG)

**Reply by snakuzzo** [reply]
1. Per favore rispondi sotto l'ultimo messaggio, non creare un nuovo thread come hai fatto ora
2. Ti avevo detto di controllare gli stati, non i servizi disponibili. Quando è armato in quel modo lo stato dovrebbe essere `armed_away` (li puoi trovare anche brevemente descritti [QUI](https://www.home-assistant.io/integrations/manual#armed_custom_bypassarmed_homearmed_awayarmed_nightdisarmedtriggered))
3. Non si usa più `service_template:` ma solo `service:` 
4. Ti ripeto per la 3a volta che non ha senso così come hai scritto. Nel trigger devi usare solo l'entità dell'allarme. Nella action solo quella dello switch

es.

```yaml
- id: antifurto_luce
  alias: Antifurto Luce
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ialarm
  action:
  - service: >-
      {% if trigger.to_state.state == 'armed_away' %} 
        switch.turn_on
      {% else %} 
        switch.turn_off
      {% endif %}
    data:
      entity_id: switch.casetta2 
```

**Reply by Franco2255** [reply]
ok grazie il tuo funziona, come sempre 
 io lo avevo preparato cosi ma non ancora testato e sicuramente non avrebbe funzionato: 

```yaml
- alias: "antifurto attivato"      
    trigger:
      platform: state
      entity_id: alarm_control_panel.ialarm
      to: 'arm_away'
    action:
      service: switch.turn_on
      data:
        entity_id: switch.casetta2
```

purtroppo alla mia età faccio fatica a memorizzare e comprendere determinate cose
grazie ancora
