### DISCUSSION TITLE
Bticino F20T60A e Zigbee2Mqtt

### DISCUSSION THREAD

**Discussion by sainz** [indomus/forum#635] [ZigBee, Z-Wave, Thread, Matter]
Ciao a tutti,
ho un problema con il misuratore dei consumi della Bticino. Terminata l'installazione Hardware, ho effettuato il pairing tramite UI di Zigbee2Mqtt premendo sul classico pulsante permit_join (All). 
E' stato riconosciuto, ed è anche collegato, ma il valore "power" non viene aggiornato costantemente o in automatico. 
Non capisco quindi se mi sto perdendo io qualche pezzo e dove sto sbagliando.
Uso HomeAssistant OS, e come dongle Zigbee la classica chiavetta Conbee II.
Grazie mille
![image](https://user-images.githubusercontent.com/5576977/130064513-8d4b805c-9939-4a02-88de-bfb6edbd46cd.png)
![image](https://user-images.githubusercontent.com/5576977/130064597-d75b9235-2264-4b26-8d87-aa3a868d0053.png)

**Comment by snakuzzo** [comment]
Nella doc di zigbee2mqtt [QUI](https://www.zigbee2mqtt.io/devices/F20T60A.html#power-numeric) infatti non parla di invio automatico del valore, ma ti dice che devi fare una publish MQTT per recuperarlo

Non so se sia previsto nativamente un parametro lato Zigbee2mqtt per leggere costantemente i valori (tipo [QUESTO](https://www.zigbee2mqtt.io/devices/TS0121_plug.html#device-type-specific-configuration) che si usa per la SHP13). Se così non fosse potresti fare richiesta sul progetto su github [QUI](https://github.com/Koenkk/zigbee2mqtt/issues/new/choose) per farlo aggiungere e provvisoriamente (o per sempre) puoi risolvere con un'automazione di questo tipo usando trigger di tipo [Time Pattern](https://www.home-assistant.io/docs/automation/trigger/#time-pattern-trigger)

```yaml
  - id: zigbee2mqtt_get
    alias: "Zigbee2mqtt Get"
    trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      seconds: 10
    action:
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/btcino_f20t60a/get'
        payload: '{"power":""}'
```

in questo caso dovrebbe pubblicare il valore allo start di HA e poi ogni 10s (ovviamente puoi customizzare la parte dei trigger come ti pare)
