### DISCUSSION TITLE
Shelly EM ed Utility Meter

### DISCUSSION THREAD

**Discussion by directy01** [indomus/forum#645] [HUB: Home Assistant]
Ciao, avrei bisogno di aiuto con l'Utility Meter
Ho appena acquistato uno Shelly EM e tutto funziona bene. L'ho integrato in HA ed il pannello Energia mi mostra tutti i dati corretti e coincidenti con l'app Shelly.

Vorrei però inserire, nella mia dashboard, i valori di consumo orari e giornalieri letti dalle zone (pinze) ma non riesco a ricavare il valore corretto.  
Ad esempio, se imposto semplicemente il 'sensor.xxx.energy' di una delle pinze con Utility Meter con ciclo 'daily' ottengo un valore in kw che si azzera ogni giorno ma è errato in quanto molto inferiore a quanto poi visualizzo nel pannello energia di HA e nell'app Shelly. Dove sbaglio?

**Comment by essegi65** [comment]
Potresti postare come hai configurato il meter, non vorrei stessi confrontando valori nettamente diversi (kwh del meter e magari potenza istantanea dello shelly)

**Reply by directy01** [reply]
ecco il codice usato:

```yaml
utility_meter: 
  shelly_em_consumo_giornaliero_zona1:  
    source: sensor.shellyem_98cdac1e46a9_channel_1_energy
    cycle: daily
```
