### DISCUSSION TITLE
Chiusura tapparelle in sequenza

### DISCUSSION THREAD

**Discussion by LucaGT78** [indomus/forum#647] [HUB: Home Assistant]
Ciao, avrei bisogno di un vostro aiuto per creare una automazione e/o uno script.
Vi descrivo cosa vorrei fare:
Gestire la chiusura delle tapparelle in base al loro consumo.
Ho 6 tapparelle collegate con shelly 2.5.
Ho creato un sensore che somma i consumi istantanei delle 6 tapparelle.
Quando decido di chiudere le tapparelle, con un pulsante virtuale,
iniziano a chiudersi le tapparelle 1, 2 e 3,
se il consumo del sensore1 è minore di 550W chiude tapparella 4,
se il consumo ritorna sotto i 550w chiudi la 5,
se il consumo ritorna sotto i 550w chiudi l’ultima, la 6.

Come posso gestire questa automazione?
Potresti aiutarmi?

Grazie in anticipo.

**Comment by snakuzzo** [comment]
Ho capito cosa vuoi fare, ma perché vuoi complicare le cose in questo modo ?
Forse non ci arrivo io, ma non ti conviene chiderne una o due per volta e far partire la chiusura delle altre quando quelle di prima si sono chiuse ?

es.

```
chiudi tapparella 1 .... tapparella1 chiusa ... passa alla prossima tapparella
chiudi tapparella 2 .... tapparella2 chiusa ... passa alla prossima tapparella
etc.
```

...oppure vai di fretta per chiuderle tutte e 6 ?

**Reply by LucaGT78** [reply]
Esatto, avevo pensato di farlo in base ai tempi di chiusura, ma volevo semplicemente chiuderle nel minor tempo, esempio inizia a piovere forte improvvisamente e voglio chiudere prima possibile.

**Reply by snakuzzo** [reply]
il tempo per chiuderne due per volta è troppo?
Chiedo, perché per pochi secondi non mi pare giustificata tutta questa cosa per 6 tapparelle

**Reply by maxcanna** [reply]
> Esatto, avevo pensato di farlo in base ai tempi di chiusura, ma volevo semplicemente chiuderle nel minor tempo, esempio inizia a piovere forte improvvisamente e voglio chiudere prima possibile.

Perché usare il tempo? Usa lo stato e chiudi le tapparelle in cascata

**Reply by LucaGT78** [reply]
Ok, effettivamente le posso gestire in sequenza chiudendo la successiva quando la precedente risulta closed.
chiudi 1,2,3 
quando 1 è chiusa, chiudi 4
quando 2 è chiusa, chiudi 5
quando 3 è chiusa, chiudi 6

Come faccio? Automazione che richiama uno script?

**Reply by snakuzzo** [reply]
Io farei una per volta con uno script
Scritto di getto, non provato...

```yaml
script:
  close_covers:
    sequence:
    - service: cover.close_cover
      data:
        entity_id: cover.tapparella1
    - wait_template: "{{ is_state('cover.tapparella1', 'closed') }}"
    - service: cover.close_cover
      data:
        entity_id: cover.tapparella2
    - wait_template: "{{ is_state('cover.tapparella2', 'closed') }}"
    - service: cover.close_cover
      data:
        entity_id: cover.tapparella3
    - wait_template: "{{ is_state('cover.tapparella3', 'closed') }}"
    - service: cover.close_cover
      data:
        entity_id: cover.tapparella4
    - wait_template: "{{ is_state('cover.tapparella4', 'closed') }}"
    - service: cover.close_cover
      data:
        entity_id: cover.tapparella5
    - wait_template: "{{ is_state('cover.tapparella5', 'closed') }}"
    - service: cover.close_cover
      data:
        entity_id: cover.tapparella6
```

**Reply by snakuzzo** [reply]
Oppure se proprio vuoi fare come dici tu, ti sconsiglio l'automazione e farei uno script che richiama 3 script

```yaml

script:
  close_all_covers:
    sequence:
    - service: script.turn_on
      data:
        entity_id: script.close_covers1
    - service: script.turn_on
      data:
        entity_id: script.close_covers2
    - service: script.turn_on
      data:
        entity_id: script.close_covers3

  close_covers1:
    sequence:
    - service: cover.close_cover
      data:
        entity_id: cover.tapparella1
    - wait_template: "{{ is_state('cover.tapparella1', 'closed') }}"
    - service: cover.close_cover
      data:
        entity_id: cover.tapparella4

  close_covers2:
    sequence:
    - service: cover.close_cover
      data:
        entity_id: cover.tapparella2
    - wait_template: "{{ is_state('cover.tapparella2', 'closed') }}"
    - service: cover.close_cover
      data:
        entity_id: cover.tapparella5

  close_covers3:
    sequence:
    - service: cover.close_cover
      data:
        entity_id: cover.tapparella3
    - wait_template: "{{ is_state('cover.tapparella3', 'closed') }}"
    - service: cover.close_cover
      data:
        entity_id: cover.tapparella6
```

**Reply by maxcanna** [reply]
Io farei con una sola automazione, come @snakuzzo insegna

**Reply by snakuzzo** [reply]
Solo che con l'automazione devi stare attento al trigger che utilizzi

**Reply by maxcanna** [reply]
Io pensavo alla chiusura di una tapparella. In base a quale si è chiusa ne chiudi un'altra. A cascata. Però anche il tuo script con wait non mi dispiace

**Reply by LucaGT78** [reply]
Ok, vi ringrazio per la collaborazione,
nei prossimi giorni farò delle prove e vi faccio sapere.
Grazie ancora.

**Reply by LucaGT78** [reply]
Perfetto,
ho fatto un package con dentro input bolean, automazione e script (come scritto sopra)
funziona tutto alla perfezione.
Se volete posto il codice.

Grazie a tutti.

**Reply by snakuzzo** [reply]
Come vuoi...

**Reply by tigers75** [reply]
Io ho uno script phyton che le abbassa tutte facendole partire a distanza di 2 secondi l'una dall'altra per evitare che ci siano tutti gli spunti dei motori insieme. Ho aggiunto anche delle "complicazioni" per chiuderle a diversi livelli a seconda se la finestra che ci sta dietro è aperta o chiusa, ma ho anche la versione per chiuderle tutte una dopo l'altra. Se interessa la posso postare.

**Comment by LucaGT78** [comment]
```
#############################################################
#############   GESTIONE CHIUSURA TAPPARELLE   ##############
#############################################################

###################   INPUT BOLEAN   ########################
input_boolean:
  chiusura_seq_covers:
    name: Chiusura All Covers
    initial: off
    icon: mdi:archive-arrow-down-outline

###################   COVER GROUP   ########################
cover:
  - platform: group
    entities:
      - cover.shelly_roller_01tv
      - cover.shelly_roller_02di
      - cover.shelly_roller_03cu
      - cover.shelly_roller_05cm
      - cover.shelly_roller_06ba
      - cover.shelly_roller_08st

################   AUTOMATION CHIUSURA   ####################
automation:
  - alias: sequenza-chiusura-covers
    trigger:
    - platform: state
      entity_id: input_boolean.chiusura_seq_covers
      to: 'on'
    action:
    - service: script.turn_on
      entity_id: script.close_all_covers

############   AUTOMATION OFF INPUT BOLEAN   ################
  - id: aggionamento_boolean_off_seq_covers
    alias: Agg-boolean-chiusura-seq-covers
    trigger:
    - platform: state
      entity_id: cover.cover_group
      to: 'closed'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.chiusura_seq_covers

######################   SCRIPT   ##########################
script:
  close_all_covers:
    sequence:
    - service: script.turn_on
      data:
        entity_id: script.close_covers_tv_ba
    - service: script.turn_on
      data:
        entity_id: script.close_covers_cu_di
    - service: script.turn_on
      data:
        entity_id: script.close_covers_cm_st

  close_covers_tv_ba:
    sequence:
    - service: cover.close_cover
      data:
        entity_id: cover.shelly_roller_01tv
    - wait_template: "{{ is_state('cover.shelly_roller_01tv', 'closed') }}"
    - service: cover.close_cover
      data:
        entity_id: cover.shelly_roller_06ba

  close_covers_cu_di:
    sequence:
    - service: cover.close_cover
      data:
        entity_id: cover.shelly_roller_03cu
    - wait_template: "{{ is_state('cover.shelly_roller_03cu', 'closed') }}"
    - service: cover.close_cover
      data:
        entity_id: cover.shelly_roller_02di

  close_covers_cm_st:
    sequence:
    - service: cover.close_cover
      data:
        entity_id: cover.shelly_roller_05cm
    - wait_template: "{{ is_state('cover.shelly_roller_05cm', 'closed') }}"
    - service: cover.close_cover
      data:
        entity_id: cover.shelly_roller_08st
```
