### DISCUSSION TITLE
Adattare un sensore MQTT (o qualsiasi altro tipo) per usarlo con la nuova dashboard GAS

### DISCUSSION THREAD

**Discussion by sineverba** [indomus/forum#671] [HUB: Home Assistant]
Ciao a tutti,
ogni settimana a mano prendo la lettura del gas e la salvo in un sensore MQTT finto, da cui traggo un po' di statistiche.
Qui di seguito il relativo package (molto semplice)

```yaml
sensor:
  - platform: mqtt
    name: "Gas reading"
    icon: mdi:stove
    state_topic: "utilities/gas/reading"
    value_template: "{{ value_json.value }}"
    unit_of_measurement: "m3"
    payload_available: "true"
    payload_not_available: "false"

input_number:
  gas_reading:
    name: Lettura
    min: 0
    max: 9999
    mode: box

script:
  gas_reading_save:
    alias: "Salva lettura"
    sequence:
      service: mqtt.publish
      data_template:
        topic: utilities/gas/reading
        payload_template: >-
          {
            "value": "{{ states('input_number.gas_reading') | int }}"
          }
        retain: true

utility_meter:
  gas_meter_monthly:
    name: Consumo gas mensile
    source: sensor.gas_reading
    cycle: monthly
  gas_meter_yearly:
    name: Consumo gas annuale
    source: sensor.gas_reading
    cycle: yearly
```

Il primo tentativo è stato quello di modificare il sensore MQTT come segue, aggiungendo `state_class: total_increasing value`

```yaml
sensor:
  - platform: mqtt
    name: "Gas reading"
    icon: mdi:stove
    state_topic: "utilities/gas/reading"
    value_template: "{{ value_json.value }}"
    unit_of_measurement: "m3"
    payload_available: "true"
    payload_not_available: "false"
    state_class: total_increasing
    device_class: gas
```

La cosa "bella" è che ho uno Shelly EM che invece (ovviamente) viene riconosciuto perfettamente per la parte energia. Confrontandoli dagli strumenti per gli sviluppatori, sono totalmente uguali:

![](https://i.imgur.com/mCOsHki.png)

e

![](https://i.imgur.com/H6OIuyg.png)

Ho voluto vedere quali fossero le differenze nel file `config/.storage/core.entity_registry` ed in effetti in quest'ultimo ho solo l'`input_number` e non anche il sensor verso e proprio:

```yaml
{
                "entity_id": "sensor.shellyem_c45bbe5fed52_channel_1_energy",
                "config_entry_id": "64c222f83fbcdcbfd522c1ad08f9eb64",
                "device_id": "d28117bcc92e721638e80e10f3eb8855",
                "area_id": null,
                "unique_id": "C45BBE5FED52-emeter_0-energy",
                "platform": "shelly",
                "name": null,
                "icon": null,
                "disabled_by": null,
                "capabilities": {
                    "state_class": "total_increasing"
                },
                "supported_features": 0,
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "original_name": "shellyem-C45BBE5FED52 channel 1 Energy",
                "original_icon": null
            },
{
                "entity_id": "input_number.gas_reading",
                "config_entry_id": null,
                "device_id": null,
                "area_id": null,
                "unique_id": "gas_reading",
                "platform": "input_number",
                "name": null,
                "icon": null,
                "disabled_by": null,
                "capabilities": {},
                "supported_features": 0,
                "device_class": null,
                "unit_of_measurement": null,
                "original_name": "Lettura",
                "original_icon": null
            },
```

A questo punto ho fatto un ulteriore tentativo. Provato a costruire un template sensor figlio del sensor mqtt:

```yaml
template:
  - sensor:
      - name: "Gas Reading Statistics"
        unique_id: sensorgasreadingstatistics20210902
        unit_of_measurement: "m3"
        device_class: gas
        state_class: measurement
        state: >-
          {{ states.sensor.gas_reading.state }}
```

Ma neanche questo viene visto dalla dashboard.

Come si può creare un sensore che vada bene per quella dashboard e che prenda i valori da un input, quindi manuali?

Posso tranquillamente cambiare anche da MQTT...

Grazie!

**Comment by sineverba** [comment]
RIguardando nel file `config/.storage/core.entity_registry` ora ho pure quelle statistiche:

```yaml
{
                "entity_id": "sensor.gas_reading_statistics",
                "config_entry_id": null,
                "device_id": null,
                "area_id": null,
                "unique_id": "sensorgasreadingstatistics20210902",
                "platform": "template",
                "name": null,
                "icon": null,
                "disabled_by": null,
                "capabilities": {
                    "state_class": "measurement"
                },
                "supported_features": 0,
                "device_class": "gas",
                "unit_of_measurement": "m3",
                "original_name": "Gas Reading Statistics",
                "original_icon": null
            }
```

L'unica differenza dallo shelly è lo state_class ora measurement (ovviamente), la platform e il device_class.

Eppure... La dashboard non lo vede...

**Comment by sineverba** [comment]
Alla fine dovrei aver risolto!

Dovrebbe essere stato sufficiente sostituire quel "m3" con "m³", con il 3 come apice dunque...

Ho ottenuto quel valore dalla lista costanti di HASS: https://github.com/home-assistant/core/blob/d7ac4bd65379e11461c7ce0893d3533d8d8b8cbf/homeassistant/const.py#L384

La configurazione finale dunque è


```yaml
sensor:
  - platform: mqtt
    name: "Gas reading"
    icon: mdi:stove
    state_topic: "utilities/gas/reading"
    value_template: "{{ value_json.value }}"
    unit_of_measurement: "m³"
    payload_available: "true"
    payload_not_available: "false"
    state_class: total_increasing
    device_class: gas
```
