### DISCUSSION TITLE
TTS e volume

### DISCUSSION THREAD

**Discussion by nromagna** [indomus/forum#679] [HUB: Home Assistant]
Ciao a tutti ho creato qualche automazioni che comunica ai dispoisitivi audio (nel mio caso Sonos o Google) degli avvisi, spesso però i dispositivi hanno volume mooolto basso, quindi, anche se l'utomazione funziona, non si sente.
C'è modo di impostare il volume? Si insomma un po' come si imposta la lingua... Grazie.

**Comment by snakuzzo** [comment]
C'è il `service.volume_set` ad hoc.
TI faccio un esempio di una action che ho in una mia automazione....considera che il volume va da `0` a `1`

```yaml
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.minisoggiorno
      volume_level: 0.6
  - service: tts.google_say
    data:
      message: "lavatrice terminata"
      entity_id: media_player.minisoggiorno
```

Per queste cose comunque ti basta andare su `CONFIGURATION > DEVELOPER TOOLS > SERVICES` e/o leggere la documentazione [QUI](https://www.home-assistant.io/integrations/media_player/)

**Reply by nromagna** [reply]
Fatte un paio di modifiche alle auomazioni, questa sera provo... grazie infinite.

**Reply by nromagna** [reply]
Provato, tutto perfetto. Grazie infinite.

**Comment by nromagna** [comment]
Ciao, possibile che dopo l'aggiornamenrto alla 2021.9.4 non funzioni più il servizio?

Andava benissimo l'altro gg, ieri sera nulla di nulla.

```
alias: TTS Spazzatura
description: ''
trigger:
  - platform: time
    at: '19:30'
  - platform: time
    at: '20:00'
  - platform: time
    at: '20:30'
condition:
  - condition: time
    weekday:
      - tue
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.4
    target:
      entity_id:
        - media_player.sala
  - service: tts.google_say
    data:
      entity_id: media_player.sala
      language: it
      message: Porta fuori l'immondizia
  - service: media_player.volume_set
    data:
      volume_level: 0.4
    target:
      entity_id:
        - media_player.cucina
  - service: tts.google_say
    data:
      language: it
      message: Porta fuori l'immondizia
      entity_id: media_player.cucina
mode: single

```

**Reply by snakuzzo** [reply]
No.
Però non limitarti a dire non funziona.
Leggi i log, fai le prove da dev tools

**Reply by nromagna** [reply]
Potrebbe essere qursto? 

```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.hacs
Source: custom_components/hacs/operational/factory.py:58
Integration: HACS (documentation, issues)
First occurred: 7 settembre 2021, 19:50:50 (4 occurrences)
Last logged: 7 settembre 2021, 19:50:50

custom-components/custom_components - Repository is archived.
custom-components/sensor.tautulli - Repository is archived.
Michsior14/ha-laser-egg - Repository is archived.
custom-components/sensor.custom_components - Repository is archived.
```

**Reply by snakuzzo** [reply]
Scusami...ma questo ora che c'entra? Hai letto questo log ?
Non è che il primo errore è riconducibile subito al tuo problema.
Lì c'è un errore legato ad HACS e a dei custom component...che c'entra il media player ?

P.S. Tra l'altro vedo che hai fatto pure casino con le directory

**Reply by nromagna** [reply]
É l'iunico che trovo all'ora (1950ca) in cui provavo manualmente a lanciare l'automazione.
PS che casino ci sarebbe? Chiedo venia il progetto mi piace, il forum pure e sinceramente non saprei dove altro chiedere informaizoni.

**Reply by snakuzzo** [reply]
Se leggi sopra ti ho consigliato di utilizzare i dev tools per provare i servizi. Se non sai come fare, dovresti prima leggere le guide e la documentazione. Il forum viene dopo.

Ad ogni modo li trovi su lovelace andando su DEVELOPER TOOLS in spalla sx e poi su SERVICES

**Reply by nromagna** [reply]
Ma il servisio andava bene 2gg fa, tanto che ho creato più di un'automazione con TTS come mi hai suggerito, con vari volumi e vari dispositivi per la riproduzione, e lanciandoli manualmente funzionavano tutti.
Ieri sera 1. all'ora prestabilita 1930 non è partita e 2. anche lanciandola manulamnete 1950 ca non ha dato segni di vita.

**Reply by snakuzzo** [reply]
Ripeto...hai verificato con i dev tools ?

**Reply by nromagna** [reply]
Questa sera provo. Ci sentiamo domani :)

**Comment by nromagna** [comment]
Niente da fare. Anche da dev tools non parte il servizio...

![2021 09 09_000162](https://user-images.githubusercontent.com/79841098/132647828-a5931e26-73d9-49b8-a152-4dc7d5c96288.jpg)

Sui log trovo, un errore ma lo so di un components.yeelight e questo:
2021-09-09 07:54:09 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook fbb894d2ee5d403ec38a21797bbeb5c3a4eabc450b0f6ed24890ec28dc778bf7 from 10.0.0.1 (<- router)

**Reply by snakuzzo** [reply]
quello non c'entra niente.
Se clicchi su "CHIAMA IL SERVIZIO" e non ti dà errori (nemmeno a video), vuol dire che il servizio è stato invocato correttamente

**Reply by nromagna** [reply]
Ed allora perchè non sento nulla dalle casse?

**Reply by nromagna** [reply]
Dai sfrega la sfera magica :p

**Reply by nromagna** [reply]
Ho trovato questo:

![image](https://user-images.githubusercontent.com/79841098/132674700-afdfb48f-c1b6-4a2c-8189-8651bf13de45.png)

può centrare qualcosa?

Inoltre dentro il configurtion.yaml è corretto questa stringa?

```
# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: https://xxx.duckdns.org:8123
    service_name: google_say
```

Grazie,

**Reply by nromagna** [reply]
Ieri sera ho modificato il configuration.yaml mettendo solo 
```
# Text to speech
tts:
  - platform: google_translate

```
Quindi riscritto l'automatismo in:

```
alias: TTS Spazzatura
description: ''
trigger:
  - platform: time
    at: '19:30'
  - platform: time
    at: '20:00'
  - platform: time
    at: '20:30'
condition:
  - condition: time
    weekday:
      - tue
action:
  - service: tts.clear_cache
  - service: media_player.volume_set
    data:
      volume_level: 0.4
    target:
      entity_id:
        - media_player.sala
        - media_player.cucina
  - service: tts.google_translate_say
    data:
      entity_id: media_player.sala
      message: Porta fuori l'immondizia
      language: it
  - service: tts.google_translate_say
    data:
      entity_id: media_player.cucina
      language: it
      message: Porta fuori l'immondizia
  - service: tts.clear_cache
mode: single
```

Ma ancora nulla.
