### DISCUSSION TITLE
Automazione tende da sole

### DISCUSSION THREAD

**Discussion by Chiara1989** [indomus/forum#70] [HUB: Home Assistant]
Ciao a tutti, 
Premetto che sono una novizia e che vi chiederò una banalità.  
Sto automatizzando una tenda da sole.
Che si apra (e faccia ombra) quando il sole è alto e c'è una bella giornata. Ma che si chiuda al calar del sole o se il tempo cambia in peggio.
Penso di aver fatto bene e più sotto posto le due automazioni.  
Il problema è che basta che ci sia una nuvola che l'entità weather cambia da sunny a partially cloudy triggerando e facendo chiudere la tenda oppure che non si apra.
Come faccio ad impostare che si apra (o si chiuda) quando lo stato di weather sia sunny e partiallycloudy?
Spero di essere stata chiara. 
Ps
Non riesco ad inserire il codice in modo corretto sorry!

Grazie 
Chiara

```  
alias: tendeautomaticheapre
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
    above: 35
  condition:
  - condition: state
    entity_id: weather.casa
    state: sunny
  action:
  - service: script.apritenda
  mode: single
- id: '1617035672612'
  alias: tendeautomazchiude
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: "-00:20:00"
  - platform: state
    entity_id: weather.casa
    from: sunny
  condition: []
  action:
  - service: script.chiuditenda
  mode: single
 ```

**Comment by snakuzzo** [comment]
Ciao.
Potresti fare così...

```yaml
- alias: tendeautomaticheapre
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: 35
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: weather.casa
      state: 'sunny'
    - condition: state
      entity_id: weather.casa
      state: 'partiallycloudy'
  action:
  - service: script.apritenda

- id: '1617035672612'
  alias: tendeautomazchiude
  trigger:
  - platform: sun
    event: sunset
    offset: "-00:20:00"
  - platform: state
    entity_id: weather.casa
    from: 'sunny'
  action:
  - service: script.chiuditenda
```

Oppure, se vuoi usare i template nella condition, così...

```yaml
- alias: tendeautomaticheapre
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: 35
  condition:
  - condition: template
    value_template: "{{ states('weather.casa') == 'sunny' or states('weather.casa') == 'partiallycloudy' }}"
  action:
  - service: script.apritenda

- id: '1617035672612'
  alias: tendeautomazchiude
  trigger:
  - platform: sun
    event: sunset
    offset: "-00:20:00"
  - platform: state
    entity_id: weather.casa
    from: 'sunny'
  action:
  - service: script.chiuditenda
```

Poi volendo si potrebbe anche accorpare tutto in un'unica automazione sfruttando il [TRIGGER OBJECT](https://www.home-assistant.io/docs/automation/templating/)
