### DISCUSSION TITLE
Aiuto: sintassi corretta per recupero valore

### DISCUSSION THREAD

**Discussion by serbat** [indomus/forum#711] [GENERALE - Discussioni generiche]
Ciao a tutti.

Sono partito da un vecchio post su questo forum  "" Pulsante con slider per luci dimmerabili "" che ha come autore Luxor7.

In pratica sto cercando di adattare i suoi pulsanti (fantastici) utilizzando come input di valore una Input_nember ... slider compreso, quello che non riesco ad ottenere è il valore numerico della input_number in basso a dx

![immagine](https://user-images.githubusercontent.com/83161647/132950079-afe4cba3-3b6b-4841-8649-aba1d41a0025.png)

Sono 2 giorni che ci sto provando, ma non conosco la sintassi e alla fine mi da sempre errore, gentilmente qualcuno è in grado di aiutarmi... allego la parte del codice finale dove deve passare il valore numerico alla variabile bg_value, in fondo al codice...
grazie a tutti

```
custom_fields:
    left_fr:
      card:
        type: 'custom:button-card'
        entity: '[[[ return entity.entity_id ]]]'
        template: light_left_frame
        variables:
          mode: '[[[ return variables.mode ]]]'
          light_icon: '[[[ return variables.light_icon ]]]'
    center_fr:
      card:
        type: 'custom:button-card'
        entity: '[[[ return entity.entity_id ]]]'
        template: light_center_frame
        variables:
          mode: '[[[ return variables.mode ]]]'
          room_icon: '[[[ return variables.room_icon ]]]'
          light_name: '[[[ return variables.light_name ]]]'
        show_icon: >
          [[[ return (variables.mode == "room") ]]]
    empty_fr:
      card:
        type: 'custom:button-card'
        entity: '[[[ return entity.entity_id ]]]'
        template: empty_frame
        variables:
          mode: room
    right_fr:
      card:
        type: 'custom:button-card'
        entity: '[[[ return entity.entity_id ]]]'
        template: light_right_frame
        variables:
          mode: '[[[ return variables.mode ]]]'
    bg_slider:
      card:
        type: 'custom:button-card'
        entity: '[[[ return entity.entity_id ]]]'
        template: light_slider_frame

    bg_value:  '9'
```

Nota: ho visto che il testo non risulta formattato correttamente, però ho usato il markdown... 
![immagine](https://user-images.githubusercontent.com/83161647/132950436-9cfc022b-1681-4ddf-b7d4-5d213667ae4a.png)

forse sbaglio qualcosa
