### DISCUSSION TITLE
Errore Payload

### DISCUSSION THREAD

**Discussion by MarioBomb** [indomus/forum#73] [HUB: Home Assistant]
Buongiorno a tutti, da qualche tempo nel log di HA ho questo errore che non riesco a capire da cosa sia dovuto:

```Logger: homeassistant.components.mqtt.cover

Source: components/mqtt/cover.py:333
Integration: MQTT (documentation, issues)
First occurred: 0:22:37 (1154 occurrences)
Last logged: 9:58:42

Payload is not supported (e.g. open, closed, opening, closing, stopped): 0.00
Payload is not supported (e.g. open, closed, opening, closing, stopped): 281.35
```
Penso si riferisca alle tapparelle, azionate con [Shelly2.5](https://indomus.it/componenti/shelly-2-5/), ma funzionano benissimo e la configurazione delle stesse è:

```
cover:
- platform: mqtt
  name: "SHELLYN"
  command_topic: "shellies/SHELLYN/roller/0/command"
  position_topic: "shellies/SHELLYN/roller/0/pos"
  set_position_topic: "shellies/SHELLYN/roller/0/command/pos"
  availability_topic: "shellies/SHELLYN/online"
  #position_template: "{{ value.y }}"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
```

Sapete aiutarmi?

grazie
