### DISCUSSION TITLE
Notifica termine lavaggio

### DISCUSSION THREAD

**Discussion by cosimociola** [indomus/forum#762] [HUB: Home Assistant]
Voglio fare un’ automazione che mi notifica sullo smartphone il termine del lavaggio. 
Seguendo alcune indicazioni degli utenti del gruppo Telegram ho ottenuto il sottonotato codice:
```

- id: '1632508311332'
  alias: termine lavaggio lavastoviglie
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.lavastoviglie_program_progress
    to: 100
  condition: []
  action:
  - service: notify.mobile_app_iphone_di_xxxxxxx_xxxxx
    data:
      message: "Lavastoviglie terminato"
  mode: single

```

Seppure viene convalidato, al riavvio del server, restituisce i seguenti errori:

Logger: homeassistant.config
Source: config.py:464 
First occurred: 20:43:23 (1 occurrences) 
Last logged: 20:43:23

Invalid config for [automation]: expected str for dictionary value @ data['to']. Got None. (See /config/configuration.yaml, line 9).

Logger: homeassistant.setup
Source: /usr/local/lib/python3.9/asyncio/events.py:80 
First occurred: 20:43:19 (1 occurrences) 
Last logged: 20:43:19

Setup of hassio is taking over 10 seconds.

Sarei grato di un vostro aiuto nella risoluzione.

**Comment by snakuzzo** [comment]
Correggi il codice utilizzando il markdown per cortesia.

L'errore parla chiaramente...

`2021-09-24 21:54:07 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['to']. Got None. (See ?, line ?). `

Prova così...

```yaml
automation:

- id: 'lavastoviglie_fine_lavaggio'
  alias: 'Lavastoviglie - Fine lavaggio'
  description: 'Invia una notifica al termine del lavagglio della lavastoviglie'
  trigger:
  - platform: state
    entity_id: sensor.lavastoviglie_program_progress
    to: '100'
  action:
  - service: notify.mobile_app_iphone_di_xxxxxxx_xxxxx
    data:
      message: "Lavastoviglie terminato"
  mode: single
```

P.S. Consiglio di leggere accuratamente gli errori per cercare di comprenderli...sono alla base di tutto
