### DISCUSSION TITLE
mini-graph-card e valore di riferimento

### DISCUSSION THREAD

**Discussion by barbatrukko** [indomus/forum#8] [HUB: Home Assistant]
E' possibile in un mini-graph-card visualizzare oltre ai 2-3 valori da monitorare anche un valore di riferimento?
Ad esempio sto visualizzando 2 temperature, vorrei una linea costante che ad esempio sia 21° in modo da vedere quanto le oscillazioni siano al di sopra o al di sotto del riferimento.
Stessa cosa per la potenza...
Si può visualizzare una "costante" nel mini-graph-card?

**Comment by snakuzzo** [comment]
Forse puoi provare con [Alternate-Y-Axis](https://github.com/kalkih/mini-graph-card#alternate-y-axis)
O magari usando un altro sensore con valore costante

**Comment by NdR91** [comment]
Temo di no, non mi pare di aver mai visto una funzione simile.
Potresti verificare [Apex Chart Card](https://github.com/RomRider/apexcharts-card). Il dev si propone di fare qualcosa di alternativo a Mini Graph, quindi potresti anche aprire una Feature Request.

**Reply by barbatrukko** [reply]
provo con la request, di sicuro è una cosa utile.  Oppure dovrei provare a visualizzare un "aiutante"

**Comment by xyzmauro** [comment]
Come dice Diego, ti basta un sensor template che abbia valore costante e poi lo includi in mini-graf
```
- platform: template
  sensors:
    minigraf:      
      value_template: 22
      unit_of_measurement: '°C'
```

**Reply by barbatrukko** [reply]
avevo provato col template ma non ha funzionato: forse però avevo sbagliato la sintassi
riprovo

**Reply by gabrio79** [reply]
> avevo provato col template ma non ha funzionato: forse però avevo sbagliato la sintassi
> riprovo

ho notato una cosa, io sto usando un input number fisso a zero per avere l'asse... se non cambia valore per un certo periodo scompare, penso sia necessario un automazione che resetta il valore

**Reply by homepd** [reply]
strano io la gestisco cosi, input number, e la costante rimane sempre visibile

**Comment by andbad** [comment]
Controlla anche questa opzione, dovrebbe esserti utile:
fixed_value

Io comunque ho messo questo nella card:
``` 
  - entity: sensor.potenza_massima_ritardato
    name: Massima
    show_state: false
    show_indicator: false
    show_points: false
    show_fill: false
    show_labels: false
```
su questo sensore:
```
  - platform: template
    sensors:
      potenza_massima_ritardato:
        unit_of_measurement: 'W'
        value_template: "{{ states('input_number.potenza_massima_ritardato')|int }}"
```

By(t)e
