### DISCUSSION TITLE
Limitare apertura e chiusura Shelly 2.5 via MQTT

### DISCUSSION THREAD

**Discussion by f4b1ux** [indomus/forum#802] [GENERALE - Discussioni generiche]
Ciao,
sto provando ad integrare uno shelly 2.5 via mqtt.

Questa è l'automazione iniziale per prendere lo stato all'avvio:
```
alias: MQTT Announce
trigger:
- event: start
  platform: homeassistant
condition: []
action:
- service: mqtt.publish
  data:
    payload: announce
    topic: shellies/command
```

Mentre l'integrazione è questa:
```
cover:
- platform: mqtt
  name: "Avv bagno camere"
  command_topic: "shellies/shelly25_bagno/roller/0/command"
  position_topic: "shellies/shelly25_bagno/roller/0/pos"
  state_topic: "shellies/shelly25_bagno/roller/0"
  set_position_topic: "shellies/shelly25_bagno/roller/0/command/pos"
  availability_topic: "shellies/shelly25_bagno/online"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  state_opening: "open"
  state_closing: "close"
  state_stopped: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
```

Funziona tutto, ma vorrei provare a limitare l'apertura e la chiusura della tapparella in modo che, ad esempio, quando la chiudo non sia completamente oscurata ma filtri un po' di luce. Stessa cosa per l'apertura, non voglio che il motore arrivi a fine corsa.

Ho provato a cambiare i valori di `position_open` e `position_close` con scarso successo.

Qualcuno è riuscito a ottenere questo comportamento?

Grazie
