### DISCUSSION TITLE
Setting Volume Announce Alexa Player

### DISCUSSION THREAD

**Discussion by smalmathias** [indomus/forum#804] [HUB: Home Assistant]
Ciao a tutti,
Avrei bisogno di sapere se c'è possibilità di abbassare il volume del player Alexa dopo aver fatto l'annuncio.
Ho provato con il codice di seguito, ha funzionato per un po di tempo ma ora dopo alcuni aggiornamenti alza e abbassa il volume durante la lettura del messaggio. C'è il modo di poter abbassare il volume subito dopo la lettura?
Grazie a tutti

```
#Notifica Alexa
  - service: media_player.volume_set
    target:
     entity_id: media_player.echo_show_di_mathias 
    data:
     volume_level: 0.6
  - service: notify.alexa_media
    data:
      target:
        - media_player.echo_show_di_mathias 
      data:
        type: announce
        method: spoken
      message: 'Attenzione {{ states("sensor.assorbimento_totale_appartamento") }} Watt di assorbimento elettrico! Ti consiglio di spegnere qualche elettrodomestico per non rischiare di rimanere senza corrente. Grazie' 
  - service: media_player.volume_set
    target:
     entity_id: media_player.echo_show_di_mathias 
    data:
     volume_level: 0.3

```
