### DISCUSSION TITLE
MQTT: pulsanti switch Enel/Sole

### DISCUSSION THREAD

**Discussion by fabior66** [indomus/forum#81] [HUB: Home Assistant]
Buongiorno a tuttti.
Vi chiedo l'aiuto per una cosa banalissima.
Ho un impianto solare offgrid monitorato dal SolPipLog:
[https://github.com/njfaria/SolPipLog/blob/master/docs/mqttvalues.md](url)
Vedo che c'è la possibilità di passare dal sole all'Enel usando comandi MQTT.
Vorrei avere sul mio HA un pulsante o due pulsanti (Enel/Sole) per fare lo switch velocemente
e magari vedere anche lo stato attuale.
Ci ho provato, ma va oltre le mie conoscenze.
Grazie.

**Comment by snakuzzo** [comment]
Qual è il topic per cambiare l'impostazione? E quali sono i valori che puoi passare ?
Inoltre, qual è il topic che viene pubblicato che restituisce lo stato ?

**Reply by fabior66** [reply]
Dovrebbe essere "solpiplog/pip/status/set" per cambiare l'impostazione con il payload "uti" per l'Enel e "sbu" per il sole.
Per lo stato "solpiplog/pip/status". Qui ho creato il sensore "status" e mi restituisce il velore corretto ("batt" oppure "uti").

**Reply by snakuzzo** [reply]
domanda...puoi anche scegliere se spegnere ? Oppure avrà categoricamente 2 stati e basta ?

**Reply by fabior66** [reply]
Niente spegnimento. Sono tre gli stati in tutto, a dire il vero, c’è anche “sol” che sta per solo solare, ma mi interessa poco. Bastano i due che dicevo prima. Grazie Diego per l’interessamento.

**Reply by snakuzzo** [reply]
Mi sa che non esiste un'entità switch di questo tipo.
Le soluzioni che vedo io sono:

1. Classico switch dove quando lo porti su ON attiva solare e su OFF attiva Enel (o viceversa)

2. Input_select (menu a tendina) dove selezioni semplicemente la modalità "Solare" o "ENEL"

3. Un button che faccia semplicemente il toggle tra i due

Nei casi 2 e 3 credo sia sempre opportuno appoggiarsi ad un sensore per avere evidenza "reale" dello stato attuale

Quale delle 3 ???
Personalmente andrei di input_select, anche perché nel caso in cui avessi bisogno di altri stati da aggiungere non avresti problemi. Tipo così...

```yaml
input_select:

  impianto_elettrico:
    name: Impianto elettrico
    options:
      - Solare
      - ENEL

automation:

  - id: gestione_impianto_elettrico
    alias: "Gestione impianto elettrico"
    trigger:
      platform: state
      entity_id: input_select.impianto_elettrico
    action:
      service: mqtt.publish
      data:
        topic: "solpiplog/pip/status/set"
        payload: >
          {% if trigger.to_state.state == 'Solare' %}
            sol
          {% else %}
            uti
          {% endif %}
```

A questo aggiungeresti poi il tuo sensore (quello che hai già creato)

Fammi sapere

**Reply by fabior66** [reply]
È andato tutto al primo colpo (non poteva essere diversamente). Grazie Diego, sei un mago. 
Ti posso chiedere anche la configurazione di uno switch on/off classico? Sul tablet, che ho sul muro, sarebbe più semplice fare solo un click su di un pulsante grande. Grazie davvero.

![Screenshot_20210402-174352](https://user-images.githubusercontent.com/59265612/113441556-c6b23780-93ee-11eb-814a-b2355fe6e7f4.jpg)

**Reply by snakuzzo** [reply]
Figurati.
Appena ho un attimo ti posto anche le altre due soluzioni

**Reply by snakuzzo** [reply]
Questo dovrebbe essere lo switch... quando è ON è su Solare, quando è OFF è su ENEL

```yaml
switch:

- platform: mqtt
  name: "Impianto elettrico"
  state_topic: "solpiplog/pip/status"
  command_topic: "solpiplog/pip/status/set"
  payload_on: "sol"
  payload_off: "uti"
  state_on: "batt"
  state_off: "uti"
  optimistic: false
  qos: 1
```

**Reply by snakuzzo** [reply]
Per quanto riguarda l'eventuale button hai diverse soluzioni...fare semplicemente uno script che ogni volta fa il toggle, o magari giocare con le card.
Ad esempio potresti sfruttare due [BUTTON CARD](https://www.home-assistant.io/lovelace/button/) e creando di fatto due pulsanti del genere...

```
type: button
name: Solare
tap_action:
  action: call-service
  service: mqtt.publish
  service_data:
    topic: "solpiplog/pip/status/set"
    payload: "sol"
```

e

```
type: button
name: ENEL
tap_action:
  action: call-service
  service: mqtt.publish
  service_data:
    topic: "solpiplog/pip/status/set"
    payload: "uti"
```
