### DISCUSSION TITLE
Automazione con messaggio telegram con valore

### DISCUSSION THREAD

**Discussion by prinaldi54** [indomus/forum#818] [HUB: Home Assistant]
Ciao a tutti ho costruito una automazione che "dovrebbe" mandarmi un messaggio su telegram con il valore di un contatore. Il messaggio parte ma la parte contatore non mi funziona.
questo è la definizione del contatore:

```yaml
counter:

  acquario_mangime_pesci:
    initial: 0
    step: 1
```

mentre questa è l'automazione:

```yaml
automation:

- id: Acquario mangime inc
  alias: acquario_mangime_inc
  description: Incrementa il contatore mangime
  trigger:
  - platform: state
    entity_id: counter.acquario_mangime_pesci
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: counter.increment
    target:
      entity_id: 
  - service: notify.pierluigi
    data:
      title: Warning
      message: Acquario mangine ok n.. {{ states(acquario_mangime_pesci) }}
  mode: single
```

Cosa sto sbagliando?
Grazie per l'aiuto
Pierluigi

**Comment by snakuzzo** [comment]
Innanzi tutto ti conviene postare direttamente il codice usando il markdown e non allegare i file... a tal proposito mi permetto di modificare il tuo post aggiungendo il tuo codice

**Reply by snakuzzo** [reply]
Detto ciò...quell'automazione non scatterà mai e non funzionerà mai per i seguenti errori:

- Lo stato del contatore non è `'on'` o `'off'` ... ma sarà `0,1,2,3,4...etc`
- manca il nome dell'entità sotto la prima action
- mancano gli apici quando usi la funzione `states()`
- mancano i doppi apici per la parte template
- Nel nome dell'entità sotto `states()` manca il dominio `counter.` 

Suggerimento 1: Inverti id e alias come ho fatto di seguito
Suggerimento 2: Tutto quello che ti sto scrivendo puoi verificarlo direttamente tu su lovelace andando sotto `Developer Tools`

Quindi per farlo funzionare dovresti eliminare `from:` e `to:`...farei così...

```yaml

counter:

  acquario_mangime_pesci:
    initial: 0
    step: 1
    
automation:

- id: 'acquario_mangime_inc'
  alias: 'Acquario mangime'
  description: 'Incrementa il contatore mangime'
  trigger:
  - platform: state
    entity_id: counter.acquario_mangime_pesci
  action:
  - service: counter.increment
    data:
      entity_id: counter.acquario_mangime_pesci 
  - service: notify.pierluigi
    data:
      title: Warning
      message: "Acquario mangine ok n.. {{ states('counter.acquario_mangime_pesci') }}"
```
