### DISCUSSION TITLE
Automazione irrigazione

### DISCUSSION THREAD

**Discussion by cosimociola** [indomus/forum#823] [HUB: Home Assistant]
Ho la necessità di automatizzare l’accensione di una pompa a immersione in funzione delle attivazioni di 4 elettrovalvole che servono il mio prato. 
Il sistema è composto da 4 elettrovalvole comandate da un Sonoff 4ch pro e uno Sonoff mini che comanda la pompa ad immersione.
La condizione è: allo stato on di una o più di una elettrovalvole deve seguire l’accensione della pompa. Vice versa, con le elettrovalvole a riposo anche anche la pompa deve passare a stato off.
Ho fatto diversi tentativi e l’unico che mi funziona è con i trigger ma devo fare 8 automazioni, 4 on e 4 off, e 2 scene.
Sarei grato ad un vostro aiuto.

**Comment by snakuzzo** [comment]
```yaml
group:
  valvole_irrigazione:
    name: "Valvole Irrigazione"
    entities:
      - switch.valvola1
      - switch.valvola2
      - switch.valvola3
      - switch.valvola4

automation:

- id: pompa_irrigazione
  alias: 'Pompa irrigazione'
  trigger:
  - platform: state
    entity_id: group.valvole_irrigazione
  action:
  - service: >
      {% if trigger.to_state.state == 'on' %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    data:
      entity_id: switch.pompa
```
