### DISCUSSION TITLE
Mancata connessione da remoto: 400 Bad request

### DISCUSSION THREAD

**Discussion by calcioscacchi** [indomus/forum#837] [HUB: Home Assistant]
Ciao di nuovo. 
Stasera mi sono dedicato alla configuraizone per la connessione in remoto.
Torno a segnalarvi la configurazione:

-HA istanziato su docker con docker compose
-raspberry pi 3b+

Ho seguito la guida  per il controllo remoto che sfrutta caddy come reverse proxy. Durante i passaggi di installazione, tutto è filato liscio. Ma purtroppo HA ora si avvia in modalità provvisoria e se provo a collegarmi da remoto sulla porta 9000, mi da errore `400: Bad request`

Passo a passarvi gli errori e le mie configurazioni.

Errori in HA: 

> Logger: homeassistant.components.http.forwarded
> Source: components/http/forwarded.py:112
> Integration: HTTP (documentation, issues)
> First occurred: 02:10:26 (2 occurrences)
> Last logged: 02:10:27
> 
> A request from a reverse proxy was received from 172.17.0.2, but your HTTP integration is not set-up for reverse proxies

> Logger: homeassistant.components.rest.data
> Source: components/rest/data.py:69
> Integration: rest (documentation, issues)
> First occurred: 02:11:47 (1 occurrences)
> Last logged: 02:11:47
> 
> Error fetching data: https://ipinfo.io/ip failed with [Errno -3] Try again

File di configurazione configuration.yaml:

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages: !include_dir_named packages

http:
  use_x_forwarded_for: true
  trusted_proxies:
    -127.17.0.2/16  -->ip dedotto dall'errore di HA, quello segnalato sulla guida non ah dato esiti diversi
```

File Caddyfile:

```
#  When your config is ok comment block below to disable use of AMCE staging server
#{
#    acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
#}
#
  (https_header) {
  header {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
  }
}
https://nomedominio.duckdns.org {
  respond "Saluti dal Crew inDomus"
  file_server
}
https://nomedominio.duckdns.org:9000 {
  import https_header
  reverse_proxy http://192.168.1.30:8123
```

Regole di port forwarding su TIMHUB H338x:

![image](https://user-images.githubusercontent.com/60674280/136479252-d5e03551-8b2b-4d66-ae42-7ca513f1f2bd.png)

inutile dirvi che nomedominio è il domio che ho scelto per duckDNS.

A mio avviso, l'errore sta nel configuration.yaml, ma non saprei come correggerlo, non solo mi sembra di aver eseguito i passaggi della guida, ma non vedo alcuna illogicità in quello che ho scritto (pian piano sto familiarizzando con struttura e linguaggio ;)).

Suggerimenti? 
Grazie!

**Comment by snakuzzo** [comment]
Questo che hai scritto...

`    -127.17.0.2/16  -->ip dedotto dall'errore di HA, quello segnalato sulla guida non ah dato esiti diversi`

...è sbagliato.
Hai sbagliato a copiare l'IP.
Ricontrolla il log di HA :)

**Reply by calcioscacchi** [reply]
ma porc.... riletto ogni riga, e alla fine ho "solo" sbagliato a scrivere.
Sapendo poi che il problema era al 99%quello, l'ho anche ricontrollato.
Fare ste cose alle 2 di notte non fa bene...

**Comment by calcioscacchi** [comment]
ho provato a correggere l'ip nel configuration.yaml, ma senza successo.
Ho sostituito 127 con 172, e ho anche provato a togliere il /16.

In entrambi i casi, una volta fasso il restart di HA, l'hub parte sempre in modalità provvisoria.

**Reply by snakuzzo** [reply]
la modalità provvisoria non c'entra niente con il tema dell'IP del reverse proxy.
Devi controllare i log di HA per capire cos'è che è andato storto...vedrai che te lo dice

**Reply by snakuzzo** [reply]
E non creare N thread...fai reply sotto l'ultimo messaggio, così come ho fatto ora io

**Reply by calcioscacchi** [reply]
> la modalità provvisoria non c'entra niente con il tema dell'IP del reverse proxy. Devi controllare i log di HA per capire cos'è che è andato storto...vedrai che te lo dice

ORa il problema dell'ip è spartio ,rimane questo:

`Error fetching data: https://ipinfo.io/ip failed with [Errno -3] Try again`

per il quale mi sto documentando, ma non sto trovando assolutamente nulla.



> E non creare N thread...fai reply sotto l'ultimo messaggio, così come ho fatto ora io

Ok. Paese che vai, regole che trovi... in molti altri forum vogliono che crei un tread per problema, in modo da eprmettere ad altri utenti una ricerca più efficace.

**Reply by snakuzzo** [reply]
io ti parlavo di thread nella stessa discussione.
Questo è Discussions di github non è una issue o un topic di un forum. Se stai parlando dello stesso argomento fai reply sotto l'ultima risposta e non in un thread a parte.

Tornando al tuo problema...prendi quella URL e piazzala su un browser e vedi che ti dà.
Altra prova...prova a farla in http e non in https

**Reply by calcioscacchi** [reply]
ahhh ok, prima volta su forum github, perdonami...

ho cercato il problema in rete, ma non ho trovato nulla, se digito la url mi rimanda a una pagina contenente l'ip pubblico di duckdns

**Reply by snakuzzo** [reply]
non saprei allora...io ho un sensore che chiama quella URL e non ho problemi di sorta

**Reply by calcioscacchi** [reply]
quello è l'ip pubblico di duckdns, se può esserti di aiuto. può essere che ho configurato male duckdns?

**Reply by snakuzzo** [reply]
A me non serve aiuto :D

Quello è l'ip pubblico con cui esci su internet che poi fa scopa con quello che è registrato sul servizio duckdns.

P.S. ti ho cancella l'IP dal messaggio precedente...evita di pubblicarlo

**Reply by calcioscacchi** [reply]
mmm... sospetto, visti gli errori, che il problema sia nell'automatismo che aggiorna l'ip di duckdns...https://indomus.it/guide/aggiornare-il-proprio-record-su-duckdns-tramite-automazione-home-assistant/


questo è il contenuto del mio package creato su packages/duckdns.yaml
```

sensor:
  - platform: rest
    name: public_ip
    resource: https://ipinfo.io/ip

input_text:
  duckdns_domain:
    initial: !secret duckdns_domain
  duckdns_token:
    initial: !secret duckdns_token

rest_command:
  update_duckdns_ip:
    url: "https://www.duckdns.org/update?domains={{ states('input_text.duckdns_domain') }}&token={{ states('input_text.duckdns_token') }}&ip={{ states('sensor.public_ip') }}"
    verify_ssl: true

automation:
- id: update_duckdns_ip
  initial_state: 'on'
  alias: "Update DuckDNS IP"
  trigger:
  - platform: state
    entity_id: sensor.public_ip
  - platform: homeassistant
    event: start
  condition:
  - condition: template
    value_template: "{{ states('sensor.public_ip') not in ['unknown','unavailable','none'] }}"
  action:
  - service: rest_command.update_duckdns_ip
```

**Reply by snakuzzo** [reply]
L'errore ti viene restituito dal primo sensore di tipo rest.
Non c'è alcun problema con il package...uso lo stesso package su due installazioni diverse (Core e HassOS).
Si vede che sulla tua installazione c'è qualche altro problema

Prova a mettere il log a debug con logger

**Reply by calcioscacchi** [reply]
volentieri, ma non so come si fa... intendi su chrome nella pagina di HA?

**Reply by snakuzzo** [reply]
https://www.home-assistant.io/integrations/logger/

**Reply by calcioscacchi** [reply]
Grazie del consiglio!! 

il log mi ha dato questa riga:

`2021-10-10 12:49:23 ERROR (MainThread) [homeassistant.config] Invalid config for [http]: not a valid value @ data['http']['trusted_proxies'][0]. Got '-'. (See /config/configuration.yaml, line 17). Please check the docs at https://www.home-assistant.io/integrations/http`


e ho provato a togliere il carattere "-" da configuration.yaml
Da questo:

```
http:
  use_x_forwarded_for: true
  trusted_proxies: 
    -172.17.0.0
```

a questo: 

```
http:
  use_x_forwarded_for: true
  trusted_proxies: 
    172.17.0.0
```

e home assistant si è avviato.
Ci sono delle cose da provare per verificare che tutto sia andato per il verso giusto, o il fatto che home assistant sia partito è sufficiente?

Grazie.

**Reply by snakuzzo** [reply]
Non ci avevo fatto caso, ma sei riuscito nell'ardua impresa di sbagliare la sintassi in tutte le prove che hai fatto. Ci vuole un trattino e anche lo spazio. Tu invece hai scritto o senza trattino o con trattino senza spazio (a tal proposito ti consiglierei di studiare un minimo la sintassi YAML).

Prova così...

```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/16
```
