### DISCUSSION TITLE
Automazione per temporizzazione

### DISCUSSION THREAD

**Discussion by baurbr** [indomus/forum#849] [HUB: Home Assistant]
Ciao ragazzi, mi potete dare una mano per impostare un'automazione?
Dovrei attivare un interuttore (collegato a shelly1) per 20 minuti ogni ora, per tutte le 24 ore.
Si può impostare qualcosa in modo furbo? 
Grazie

**Comment by snakuzzo** [comment]
Se sai già a che minuto avviare l'automazione, puoi fare in questo modo...

```yaml
automation:

- id: prova
  alias: "Prova"
  description: ""
  trigger:
  - platform: time_pattern
    minutes: 10
  - platform: time_pattern
    minutes: 30
  action:
  - service: persistent_notification.create
    data:
      message: "{{ now().minute }}"
  - service: >
      {% if now().minute | int == 10 %}
        switch.turn_on
      {% alse %}
        switch.turn_off
      {% endif %}
    data:
      entity_id: switch.mio_switch
```

l'automazione scatta al minuto 10 e al minuto 30.
Al minuto 10 chiama `switch.turn_on` e al 30 chiama `switch.turn_off` sulla stessa entità.

Se invece non sai a prescindere quali sono i minuti bisogna cambiare la logica...ma la logica ovviamente la devi esporre tu
