### DISCUSSION TITLE
[valvole tado] non c'è funzione sempre aperto / sempre chiuso ?!

### DISCUSSION THREAD

**Discussion by 50494554524F** [indomus/forum#85] [HUB: Home Assistant]
sto cercando di integrare le valvole in home assistant... primi esperimenti, ho un problema.

ho girato la manopola per mettere la valvola in modalità manuale ed impostato che le modifiche vengano mantenute 
a tempo indeterminato. fin qui ok. mi dico che ci penserà home assistant ad aprire e chiudere...

ho settato a 22° la valvola, ho acceso la caldaia, la valvola comincia a scaldarsi ed arriva a 23°, a questo punto si chiude. 
quando si raffredda comincia a riaprirsi.
il problema è qui: la temperatura della stanza magari è salita di solo un decimo ed home assistant non è intervenuto.

sto cercando, ma non trovo soluzione... mi è sfuggito qualcosa?! devo mettere al massimo sia la valvola che l'offset?!

grazie

**Comment by snakuzzo** [comment]
Per quanto riguarda il titolo del topic..
Sempre chiuso = le imposti su OFF
Sempre aperto = per ora non esiste...dovresti sempre fare in modo di avere la temperatura impostata più alta di quella rilevata. Io in estate per ottenere questo imposto un offset di -9° su tutte le teste termostatiche e imposto la temperatura a 25°.

Quanto alla domanda nel tuo post invece, non c'è alcun problema. Devi considerare sempre un margine quando si ragiona per decimi di grado, questo perché altrimenti ti ritroveresti con la testa termostatica che apre e chiude in continuazione...è del tutto normale.
Tra le altre cose considera che il comportamento non dipende tanto da HA, ma dalle impostazioni delle teste termostatiche...ricorda che hai sempre integrato le teste via cloud di Tado° e non localmente.

**Reply by 50494554524F** [reply]
avevo già pensato ad offset su -9 (poi perché max -9?! bhò) e temp a 25, grazie per la conferma... stasera con le temperature più basse provo, vediamo un po'... (perché in estate?!) 

il decimo era riferito al fatto che la valvola si scalda rapidamente stando vicino al termosifone mentre la stanza ha bisogno di tempo...

riformulo... a che serve aggiungerle ad home assistant se non posso escludere completamente tado dalla gestione?! per leggere le temperature?! tanto vale prendere il termostato di tado per ogni stanza... mi sfugge ancora qualcosa...

**Reply by snakuzzo** [reply]
Rispondo prima alla tua ultima domanda...
l'integrazione TADO di HA si basa sul cloud di TADO°...quindi è del tutto normale. Peòr io non ho capito se tu vuoi escludere completamente il cloud o se vuoi poterle pilotare sia da app TADO° che da HA. Perché nella seconda ipotesi è già così...dipende poi se hai impostato l'entità climate su AUTO o su HEAT...ed il tutto poi eventualmente auto-gestito con automazioni.
Ad ogni modo, se vuoi puoi anche impostarle solo localmente (escludendo tutte le programmazioni lato cloud) utilizzando [Homekit Controller](https://www.home-assistant.io/integrations/homekit_controller/) (da non confondere con Homekit). Ricorda però che, a prescindere da tutto, non è che puoi tenere la valvola aperta "a cannone" sempre. Resta sempre valido il discorso che una volta raggiunta la temperatura target la testa chiude la valvola...fa parte "GIUSTAMENTE" proprio del firmware della valvola

Parlando invece alle differenze di temperatura, l'offset è stato creato proprio per questi casi... per la "calibrazione". Usa un sensore esterno, mettilo al centro della stanza e fai le tue prove...ed in base alle prove imposti l'offset

**Reply by 50494554524F** [reply]
ti ringrazio davvero per il chiarimento. avevo cominciato con l'integrazione tado, più semplice per impratichirsi, e dando per scontate funzioni ovvie (per me :D).
visto che dell'app non mi interessa, gioco un altro po' con questa di tado e poi salto direttamente a studiare homekit controller.

**Comment by 50494554524F** [comment]
ho fatto delle prove: offset -9°, target 25°, mandata 55° ... 
la temperatura registrata dalla valvola tende a stabilizzarsi già dopo un'ora e mezza di termosifone acceso e la curva tende
ad appiattirsi dopo due ore. dopo due ore cresce di +0,05° ogni 5 minuti, siamo a +5-5,25° rispetto alla stanza. 
anche dovesse andare così tutto il giorno non arriverei (speriamo) mai ai 25° del target e dovrei vedere simulato bene il sempre aperto.
poi la chiuderà l'automazione ovviamente...
ad averci pensato prima non vi avrei scocciato :D ora vado a studiarmi homekit controller...

**Reply by snakuzzo** [reply]
Ma figurati ;) nessun problema

**Comment by 50494554524F** [comment]
nel frattempo, volendo usare l'integrazione tado son riuscito a risolvere...

per avere il sempre chiuso, ovviamente, basta mettere su off chiamando il servizio climate.turn_off

per avere il sempre aperto ho risolto creando uno switch che faccia da wrapper alla valvola. due motivi: il termostato generico (ho usato questo per avere libertà) provvisto in HA la chiude ma non la riapre e, soprattutto, quando la si riapre con climate.turn_on viene persa la temperatura impostata prima.

questo da caricare come file package...

```
room_test_valve:

  switch:

    - platform: template
    
      switches:



        #  Valve
      
        room_test_valve:
        
          friendly_name: 'Room Test - Valve'
        
          value_template: "{{ is_state( 'climate.room_test_valve', 'heat' ) }}"
        
          turn_on:
          
            - service: climate.turn_on
          
              target:
            
                entity_id: climate.room_test_valve
          
            - service: climate.set_temperature
          
              target:
            
                entity_id: climate.room_test_valve
                
              data:
              
                temperature: 25
        
          turn_off:
          
            - service: climate.turn_off
          
              target:
            
                entity_id: climate.room_test_valve

```

e sul sito o app tado, piccolo trucco...

![abc](https://user-images.githubusercontent.com/78425660/113617995-58bc7900-9657-11eb-8023-3a5e9211fcee.png)
