### DISCUSSION TITLE
Conteggio kWh all'accensione di un sensore

### DISCUSSION THREAD

**Discussion by tempod** [indomus/forum#858] [HUB: Home Assistant]
...mi spiego...
Ho una pompa di calore per l'acqua calda ed il riscaldamento con un sensore per il consumo.
Ho anche dei sensori che indicano se questa pompa di calore sta lavorando per fare acqua calda sanitaria o se sta lavorando per riscaldare la casa.
Vorrei creare altri sensori che mi indichino quando ho consumato per ognuna delle due funzioni.
In pratica:
  - quanto ha consumato la pompa di calore quando era attivo il sensore per il riscaldamento
  - quanto ha consumato la pompa di calore quando era attivo il sensore per l'acqua calda

Ho provato con node red ma non ci sono riuscito.
Potete aiutarmi?
Grazie.

**Comment by Scialla** [comment]
Potresti utilizzare un utility_meter, guarda la guida di inDomus:
https://indomus.it/componenti/componente-home-assistant-utility-meter/
adattando l'automazione invece che agli orari allo stato dei sensori riscaldamento/acqua calda

**Comment by tempod** [comment]
Grazie.
Ho provato a configurare dei sensori come mi hai indicato e con node red ho creato un flow per attivare una diversa "tariffa" a seconda di cosa sta facendo la pompa di calore.

```
consumo_giorno_pdc:
  source: sensor.consumo_pdc
  cycle: daily
  tariffs:
    - acquacalda
    - riscaldamento
    - standby
consumo_mese_pdc:
  source: sensor.consumo_pdc
  cycle: monthly
  tariffs:
    - acquacalda
    - riscaldamento
    - standby
```
![Immagine 2021-10-11 233509](https://user-images.githubusercontent.com/71033514/136858378-755444d9-b68d-4aa8-b5a1-daa2df43df8b.jpg)

Adesso lo provo.
Grazie.
