### DISCUSSION TITLE
Contatore luci accese.

### DISCUSSION THREAD

**Discussion by edifabio-72** [indomus/forum#862] [GENERALE - Discussioni generiche]
Tempo fa avevo l'esigenza di contare il numero delle luci accese escludendo però una legata ad un SonOff che comanda una stampante 3D per cui non è una reale luce.
Il buon @snakuzzo  mi ha suggerito un'ottima soluzione

```yaml
  ## Conta il numero delle luci accese escludendo il SonOff della Prusa
  - platform: template
    sensors:
      luci_accese:
        friendly_name: 'Luci Accese'
        icon_template: 'mdi:lightbulb-group-outline'
        value_template: >
          {% set ns = namespace(below=[]) %}
            {% for s in states.light 
                    if 'light.sonoff_1000ab24b4' not in s.entity_id and s.state == 'on' %} 
                {% set ns.below = ns.below + [ s ] %}
            {% endfor %}
          {{ ns.below | count }}`
```

Ieri però ho avuto l'esigenza di dover installare il custom component  Browser Mod.
 Da quel momento in poi mi aggiunge alle luci alcune entità che non so neanche io a cosa servono ma che mi sfalzano il calcolo delle luci  accese.
Come lo risolvo?
