### DISCUSSION TITLE
Automazione con condizione/azione multipla

### DISCUSSION THREAD

**Discussion by barbatrukko** [indomus/forum#866] [HUB: Home Assistant]
Salve,
utilizzo dei pulsanti Shelly Button1 per pilotare alcune configurazioni di luci. Ad esempio
1 click -> accendo/spengo
2 cllick -> accendo Blu
3 click -> xxx
click lungo -> yyy
etc

per farlo uso delle automazioni tipo questa

```yaml
- alias: ShellyButton SS Toggle StripLed 
  description: ''
  trigger:
  - platform: mqtt
    topic: shellies/ShellyButtonXX/input_event/0
  - platform: mqtt
    topic: shellies/ShellyButtonYY/input_event/0
  condition:
  - condition: template
    value_template: '{{ (trigger.payload_json[''event''] ==''SS'' ) }}'
  action:
  - scene: scene.strip_ocean_50
  mode: single
```
Quindi al momento però devo creare 4 automazioni per ogni button e mi secca un po'
E' possible mettere nella stessa automazione, diverse coppie di condizione/azione in modo da avere un unico file per pulsante?

**Comment by snakuzzo** [comment]
Certo che puoi, ma non devi fare come hai fatto.
Puoi seguire sostanzialmente due strade...

1) Se il servizio che andrai a chiamare nella action è sempre lo stesso, ma cambiano solo le entità puoi fare così...

```yaml
- alias: ShellyButton SS Toggle StripLed 
  trigger:
  - platform: mqtt
    topic: shellies/ShellyButtonXX/input_event/0
  action:
  - service: schene.turn_on
    data:
      # ammettiamo che per quel topic ci siano payload 'SS', 'SSS', 'AA'
      entity_id: >
        {% if trigger.payload_json['event'] == 'SS' %}
          scene.pippo
        {% elsif trigger.payload_json['event'] == 'SSS' %}
          scene.pluto
        {% else %}
          scene.paperino
        {% endif %}
  - scene: scene.strip_ocean_50
  mode: single
```

2) Se invece il servizio cambia allora potresti sfruttare la choose così...

```yaml
- alias: ShellyButton SS Toggle StripLed 
  trigger:
  - platform: mqtt
    topic: shellies/ShellyButtonXX/input_event/0
  action:
  - choose:
    # Se il payload è SS
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json['event'] == 'SS' }}"      
      sequence:
        - service: scene.turn_on
          data:
            entity_id: scene.pippo
    # Altrimenti se il payload è SSS
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json['event'] == 'SSS' }}"
      sequence:
      - service: script.turn_on
        data:
          entity_id: script.pluto
    # Infine (ultimo caso possibile che va nel default...sarebbe l'equivalente dell'ELSE) se il payload è AA
    default:
      - service: light.turn_on
        data:
          entity_id: light.paperino
```

**Reply by barbatrukko** [reply]
> Certo che puoi, ma non devi fare come hai fatto. Puoi seguire sostanzialmente due strade...
> 
Interessante, credo che forse basti il primo metodo,anche se in un caso forse cambia il servizi...
Stasera faccio un po' di prove.
Grazie

**Reply by barbatrukko** [reply]
> Certo che puoi, ma non devi fare come hai fatto. Puoi seguire sostanzialmente due strade...
> 
> 1. Se il servizio che andrai a chiamare nella action è sempre lo stesso, ma cambiano solo le entità puoi fare così...
> 
> ```yaml
> - alias: ShellyButton SS Toggle StripLed 
>   trigger:
>   - platform: mqtt
>     topic: shellies/ShellyButtonXX/input_event/0
>   action:
>   - service: schene.turn_on
>     data:
>       # ammettiamo che per quel topic ci siano payload 'SS', 'SSS', 'AA'
>       entity_id: >
>         {% if trigger.payload_json['event'] == 'SS' %}
>           scene.pippo
>         {% elsif trigger.payload_json['event'] == 'SSS' %}
>           scene.pluto
>         {% else %}
>           scene.paperino
>         {% endif %}
>   - scene: scene.strip_ocean_50
>   mode: single
> ```
> 
> 1. Se invece il servizio cambia allora potresti sfruttare la choose così...
> 
> ```yaml
> - alias: ShellyButton SS Toggle StripLed 
>   trigger:
>   - platform: mqtt
>     topic: shellies/ShellyButtonXX/input_event/0
>   action:
>   - choose:
>     # Se il payload è SS
>     - conditions:
>       - condition: template
>         value_template: "{{ trigger.payload_json['event'] == 'SS' }}"      
>       sequence:
>         - service: scene.turn_on
>           data:
>             entity_id: scene.pippo
>     # Altrimenti se il payload è SSS
>     - conditions:
>       - condition: template
>         value_template: "{{ trigger.payload_json['event'] == 'SSS' }}"
>       sequence:
>       - service: script.turn_on
>         data:
>           entity_id: script.pluto
>     # Infine (ultimo caso possibile che va nel default...sarebbe l'equivalente dell'ELSE) se il payload è AA
>     default:
>       - service: light.turn_on
>         data:
>           entity_id: light.paperino
> ```
Salve,
ho fatto  le prove ed utilizzato il tuo script e funziona....ma è subentrato un effetto collaterale.
In pratica da quando sono passato dalle azioni singole (una automazione per ogni caso) a queste complesse, che mi permettono in un unico file di racchiudere tutta la logica di un singolo pulsante, è sorto un effetto collaterale.
Ogni tanto (di notte, di giorno, senza un motivo specifico) si accendono le luci collegate al pulsante.
Inizialmente credevo dipendesse da un pulsante difettoso, ma poi in particolare per una luce, comandata in maniera gemella  da due pulsanti, ho visto che entrambi i pulsanti in maniera casuale ogni tanto la accendono....
Ho indagato meglio ed ho scoperto un cosa: l'evento che scatta è quello "default" ovvero quello che scatta se nessuno dei canonici combacia....
Quindi non è 'S", 'SS",'"SSS","L". Ora, basta che elimino la sezione default ed il problema si risolve... ma vorrei sapere cosa è questo evento che scatta in maniera casuale. E' possibile in qualche modo mettere nell'azione default, qualcosa che "loggi" il comando ricevuto su MQTT?

**Reply by snakuzzo** [reply]
Ciao.
Per com'è scritta l'automazione, scatta ad ogni pubblicazione del topic `shellies/ShellyButtonXX/input_event/0` indipendentemente dal payload.
Ovviamente se un payload specifico non è gestito, va nel ramo `default`.
A questo punto devi sapere tu cosa vuoi e gestire il default in base alle tue esigenze.
Cosa vuoi fare ? Indica quali sono i payload che vuoi gestire e come li vuoi gestire

**Reply by barbatrukko** [reply]
I payload sono quelli indicati "S","SS","SSS","L".
Essendo un pulsante dovrebbe mandare solo quelli, perciò vorrei "loggare" nel caso "default" cosa il pulsante sti amandando

tipo qualcosa:
```
`default:
      - service: light.turn_on
        data:
          entity_id: light.paperino`
      - Logga da qualche parte il payload ricevuto
```

Ho provato con questo, ma non funziona, di sicuro il problema è nel come indicare il payload da scrivere

```
service: system_log.write
data:
  message: message ' {{ trigger.payload_json['event'] }} '
```

**Reply by snakuzzo** [reply]
Così ti crea una notifica su lovelace sulla barra laterale

```yaml
    default:
      #- service: light.turn_on
      #  data:
      #   entity_id: light.paperino
      - service: persistent_notification.create
        data:
          message: "{{ trigger.payload_json }}"
```
