### DISCUSSION TITLE
Info per Smarther Thermostat

### DISCUSSION THREAD

**Discussion by CarloCalv** [indomus/forum#868] [HUB: Home Assistant]
Vorrei poter estrarre lo stato HVAC ACTION per poter fare il conteggio delle accensioni giornaliere da Smarther Thermostat, quali comandi devo dare per assegnare lo stato ad un sensore temporaneo?
Grazie

![hvac](https://user-images.githubusercontent.com/82334492/137302718-6c96831f-567c-48f9-b6a5-fe202a45e27e.jpg)

**Comment by snakuzzo** [comment]
Devi creare un [template sensor](https://www.home-assistant.io/integrations/template/)
Tipo questo...

```yaml
sensor:
  template:
    - sensor:
        - name: "Smarther Action"
          state: "{{ state_attr('climate.smarther_thermostat','hvac_action') }}"
```

ma se vuoi solo contare le accensioni, puoi anche fare a meno di creare un template sensor. Crei un [counter](https://www.home-assistant.io/integrations/counter/)che si incrementa tramite automazione ogni volta che il `climate `passa da `'off'`a qualsiasi altro stato oppure ogni volta che `hvac_action `passa da `idle `a qualsiasi altro stato
