### DISCUSSION TITLE
Utilizzo Picture-elements

### DISCUSSION THREAD

**Discussion by Galmik** [indomus/forum#87] [HUB: Home Assistant]
Buongiorno

sto iniaziando ora ad utlizzare Home Assistant per domotizzare la casa, volevo inserire una foto utilizzando la card Picture-elements ma pur scrivendo il codce correttamente , almeno spero, non riesco a visualizzare l'immagine

```
type: picture-elements
image: media/Floorplan.png
elements:
  - type: state-badge
    entity: sensor.ipad_di_michele_battery_level
    style:
      top: 32%
      left: 40%
```
Ovviamente il file e preso da internet per fare delle prove, il percorso originale del'immagine sarebbe /local/ ma non riesco a capire cosa si intenda per "/local" , " media " e la cartella che sto utilizzando per immagazzianre le foto.

Sbaglio qualcosa oppure devo aggiungere delle righe in qualche altro file

Grazie
