### DISCUSSION TITLE
Automazione con azione a una determinata ora

### DISCUSSION THREAD

**Discussion by tabs78** [indomus/forum#875] [GENERALE - Discussioni generiche]
Ciao, vorrei un'automazione che al mattino quando passo davanti al sensore prossimità tra le 5.20 e 5.40 mi accende la luce ma poi la spegne alle 5.59.
Sul gruppo telegram mi hanno suggerito una choose ma mi sono inceppato

``` 
alias: Buongiorno 
description: ''
trigger:
  - type: motion
    platform: device
    device_id: b18e00d7e107f058049ef9e42c4719ec
    entity_id: binary_sensor.0x00158d0005bd25b4_occupancy
    domain: binary_sensor
  - platform: time
    at: '05:59'
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.0x00158d0005bd25b4_occupancy
            state: 'true'
            attribute: occupancy
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
            after: '05:20'
            before: '05:41'
        sequence:
          - type: turn_on
            device_id: 7e4bd92992184ab14282c769c559b091
            entity_id: switch.bagno
            domain: switch
      - conditions:
          - condition: time
            after: '05:59'
            before: '05:59'
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          - type: turn_off
            device_id: 7e4bd92992184ab14282c769c559b091
            entity_id: switch.bagno
            domain: switch
    default: []
mode: single
```

**Comment by Scialla** [comment]
Correggi il post usando il markdown per cortesia (tre apici inversi prima e dopo il codice)

non ti serve la choose in questo caso, né tutte quelle condizioni (non per spegnere almeno ma solo per accendere), ti bastano i due trigger che hai impostato poi fai una action utilizzando una if e utilizzando gli attributi del trigger che puoi vedere qui:
https://www.home-assistant.io/docs/automation/templating/

Ad esempio potresti utilizzare il trigger.platform (visto che sono diversi) all'interno di una if per decidere se accendere o spegnere.
prova, se non riesci la si fa assieme..

**Reply by tabs78** [reply]
Mi hanno suggerito il wait template

Così potrebbe andare?

``` alias: Buongiorno 
description: ''
trigger:
  - type: motion
    platform: device
    device_id: b18e00d7e107f058049ef9e42c4719ec
    entity_id: binary_sensor.0x00158d0005bd25b4_occupancy
    domain: binary_sensor
condition:
  - condition: time
    after: '05:20'
    before: '05:41'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - type: turn_on
    device_id: 7e4bd92992184ab14282c769c559b091
    entity_id: switch.bagno
    domain: switch
  - wait_template: '{{ is_state(''sensor.time'', ''05:59:00'') }}'
  - type: turn_off
    device_id: 7e4bd92992184ab14282c769c559b091
    entity_id: switch.bagno
    domain: switch
mode: single ```

**Reply by Scialla** [reply]
Certo che funziona ma, nel caso riavviassi HA tra accensione e spegnimento, non si spegnerebbe più. Se utilizzi il trigger time per spegnerla invece andrebbe. Una tua scelta ;)

**Reply by tabs78** [reply]
Ho dato un'occhiata al link ma non ho capito bene anche guardando gli esempi

Riesci a farmi un esempio in codice che poi adatto al mio?

**Reply by snakuzzo** [reply]
Io la farei così (scritta di getto senza provare) ...

```yaml
automation:

- id: autospegnimento_luce_bagno
  alias: "Autospegnimento Luce  Bagno"
  description: "Spegne in automatico la luce del bagno di notte"
  trigger:
  - platform: state
    entity_id: binary_sensor.0x00158d0005bd25b4_occupancy
    from: 'off'
    to: 'on'
  - platform: time
    at: '05:59:00'
  condition:
  - condition: time
    after: '05:20'
    before: '05:41'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: >
      {% if trigger.entity_id == 'binary_sensor.0x00158d0005bd25b4_occupancy' %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    data:
      entity_id: switch.bagno
```

**Reply by tabs78** [reply]
C'è qualcosa che non va nella formattazione della azione perché mi dà errore

**Reply by snakuzzo** [reply]
fai vedere l'errore

**Reply by tabs78** [reply]
Message malformed: expected dictionary @ data['action'][0]

**Reply by snakuzzo** [reply]
a me sembra formattato correttamente, probabilmente hai sbagliato a fare copia-incolla e ti sei perso qualche spazio. Ricontrolla

**Reply by tabs78** [reply]
Ok ora me lo salva. Adesso devo fare una prova, c'è un metodo empirico visto che sono fuori casa?

**Reply by snakuzzo** [reply]
per testare il funzionamento quando il sensore di presenza passa ad `'on'` puoi semplicemente forzare lo stato da Developer Tools > States ... cerchi il tuo sensore e gli forzi lo stato ad on (che per qualche secondo rimarrà ad on) e vedi se si accende la luce.

Per testare il funzionamento dello spegnimento su base orarria, ti conviene cambiare al volo l'automazione inserendo nel trigger un orario vicino all'ora in cui provi (es. se sono le 17:00, metti `'17:05:00'`), la ricarichi, ti assicuri che la luce sia accesa e aspetti che scatti l'automazione alle 17:05

**Reply by tabs78** [reply]
Non funziona, non parte proprio l'automazione

**Reply by snakuzzo** [reply]
ma hai modificato anche l'orario che hai messo nella condizione?

**Reply by snakuzzo** [reply]
Adegua la condition... 
Ah...ho provato l'automazione che ti ho scritto sulla mia istanza...e funziona perfettamente.

Quindi se a te non va vuol dire che hai sbagliato qualcosa

**Reply by xyzmauro** [reply]
> ma hai modificato anche l'orario che hai messo nella condizione?

Ma come fa a funzionare se il before della condition è minore del platform time del trigger?! 🤔
Secondo me ci va una choose qui…

**Reply by tabs78** [reply]
> Adegua la condition... Ah...ho provato l'automazione che ti ho scritto sulla mia istanza...e funziona perfettamente.
> 
> Quindi se a te non va vuol dire che hai sbagliato qualcosa

Allora la luce si accende nel range desiderato ma non si spegne all'orario impostato

**Reply by xyzmauro** [reply]
E non si spegnerà mai…🤷‍♂️
Segui la logica, scatta alle 5:59 come fa ad essere vera la condition after 5:20 e before 5:41? Li l’automazione si ferma

**Reply by tabs78** [reply]
> E non si spegnerà mai…🤷‍♂️ Segui la logica, scatta alle 5:59 come fa ad essere vera la condition after 5:20 e before 5:41? Li l’automazione si ferma

eh si però lui dice che ha provato e va, quindi tu cosa dici di fare?

**Reply by xyzmauro** [reply]
Io farei una choose tipo la 1ª che hai postato tu, però fatta bene 😅
Ora da telefono faccio fatica a scriverla ma la strada giusta è quella

**Reply by tabs78** [reply]
> Io farei una choose tipo la 1ª che hai postato tu, però fatta bene 😅 Ora da telefono faccio fatica a scriverla ma la strada giusta è quella

forse con la choose funziona!

**Reply by snakuzzo** [reply]
raga...se volete vi faccio un video di come funziona l'automazione che ho scritto io... :D

**Reply by snakuzzo** [reply]
la choose non serve...la choose è utile quando magari chiami n servizi diversi che accettano un `data` completamente diverso...l'ho spiegato nella mia prima risposta. L'automazione che ho scritto [QUI](https://github.com/indomus/forum/discussions/875#discussioncomment-1482593) fa quello che deve fare

**Reply by xyzmauro** [reply]
> raga...se volete vi faccio un video di come funziona l'automazione che ho scritto io... :D

Io non capito come funziona sinceramente 😅

**Reply by xyzmauro** [reply]
> la choose non serve...la choose è utile quando magari chiami n servizi diversi che accettano un `data` completamente diverso...l'ho spiegato nella mia prima risposta. L'automazione che ho scritto [QUI](https://github.com/indomus/forum/discussions/875#discussioncomment-1482593) fa quello che deve fare

Scusa,ma scatta alle 5:59 come fa a passare la condition?

**Reply by snakuzzo** [reply]
cosa non hai capito ?

**Reply by snakuzzo** [reply]
la condition che ha impostato è sbagliata...deve mettere un range temporale

**Reply by snakuzzo** [reply]
e deve essere incluso ovviamente il time impostato nel trigger

**Reply by snakuzzo** [reply]
ad ogni modo va corretta...aspetta che la riposto :)

**Reply by snakuzzo** [reply]
come non detto...serve la choose per via della condition ... scusate

**Reply by xyzmauro** [reply]
In quella scritta da te intendo
Trigger: 5:59
Condition:
After: 5:20
Before:5:41

**Reply by xyzmauro** [reply]
> come non detto...serve la choose per via della condition ... scusate

🙏

**Reply by xyzmauro** [reply]
Mi sentivo pirla io 😅

**Reply by snakuzzo** [reply]
è che mi era sfuggito perché poi quando ho fatto le prove ho messo un range temporale ampio :)
Ora la riposto con la choose

**Reply by tabs78** [reply]
per completezza allego quella che sembra funzionare

``` 
- alias: Bagno notte
description: ''
trigger:
  - type: motion
    platform: device
    device_id: b18e00d7e107f058049ef9e42c4719ec
    entity_id: binary_sensor.0x00158d0005bd25b4_occupancy
    domain: binary_sensor
  - platform: time
    at: '05:59'
condition: []
action:
  - choose:
      - conditions:
          - type: is_motion
            condition: device
            device_id: b18e00d7e107f058049ef9e42c4719ec
            entity_id: binary_sensor.0x00158d0005bd25b4_occupancy
            domain: binary_sensor
          - condition: time
            after: '05:20'
            before: '05:41'
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          - type: turn_on
            device_id: 7e4bd92992184ab14282c769c559b091
            entity_id: switch.bagno
            domain: switch
      - conditions: []
        sequence:
          - type: turn_off
            device_id: 7e4bd92992184ab14282c769c559b091
            entity_id: switch.bagno
            domain: switch
    default: []
mode: single
```

**Reply by snakuzzo** [reply]
```yaml
automation:

- id: autospegnimento_luce_bagno
  alias: "Autospegnimento Luce  Bagno"
  description: "Spegne in automatico la luce del bagno di notte"
  trigger:
  - platform: state
    entity_id: binary_sensor.0x00158d0005bd25b4_occupancy
    from: 'off'
    to: 'on'
  - platform: time
    at: '05:59:00'
  action:
  - choose:
      - conditions: "{{ trigger.entity_id == 'binary_sensor.0x00158d0005bd25b4_occupancy' }}"
        sequence:
        - condition: time
          after: '05:20'
          before: '05:41'
          weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
        - service: switch.turn_on
          data:
            entity_id: switch.bagno
    default:
      - service: switch.turn_off
        target:
          entity_id: switch.bagno
```
