### DISCUSSION TITLE
duckdns domain e token visualizzati in chiaro su UI

### DISCUSSION THREAD

**Discussion by Matiu-f** [indomus/forum#878] [HUB: Home Assistant]
Ciao a tutti,
ho seguito la guida per l'utilizzo di duckdns, in particolare la parte: 
https://indomus.it/guide/aggiornare-il-proprio-record-su-duckdns-tramite-automazione-home-assistant/

Tutto ok, funziona bene!

L'unica perplessità che ho è che ora mi compare sulla lovelace un box nominato "Input di testo" dove sono visualizzati i miei duckdns domain e token.

Si può fare in modo che non avvenga?
Grazie!

**Comment by snakuzzo** [comment]
Puoi anche togliere dalla visualizzazione quel token...tanto non ti serve a niente vederlo su lovelace

**Reply by Matiu-f** [reply]
Posso farlo direttamente da duckdns.yaml?

devo aggiungere qualcosa qui?
```
input_text:
  duckdns_domain:
    initial: !secret duckdns_domain
  duckdns_token:
    initial: !secret duckdns_token
```
