### DISCUSSION TITLE
generic_thermostat non mi funziona

### DISCUSSION THREAD

**Discussion by ghost** [indomus/forum#884] [GENERALE - Discussioni generiche]
Un saluto a tutti.
Sono alle prime armi con HA, ho installato HA core su un Raspberriy PI3 seguendo le guide e come prima prova automatizzare la ventola di raffreddamento del RPI, ma il termostato non funziona, dall'interfaccia grafica risulta sempre inattivo.
Ho seguito questa guida https://indomus.it/progetti/gestire-dinamicamente-una-ventola-tradizionale-su-raspberry-pi-via-home-assistant/ e altre trovate in rete ma senza successo. Dopo una settimana di prove e ricerche non so più cosa fare.
Non penso al GPIO guasto, credo non funziona l'automazione.

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#homeassistant:
#  packages: !include_dir_named packages

sensor:
  - platform: command_line
    name: Temperatura CPU
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
    scan_interval: 10
switch:
  - platform: rpi_gpio
    ports:
      18: Fan SHIM
climate:
  - platform: generic_thermostat
    name: Fan SHIM
    heater: switch.fan_shim
    target_sensor: sensor.temperatura_cpu
    min_temp: 20
    max_temp: 80
    ac_mode: true
    target_temp: 50
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 5
    keep_alive:
      seconds: 5
    initial_hvac_mode: "cool"

```
