### DISCUSSION TITLE
aiuto esphome

### DISCUSSION THREAD

**Discussion by RtoRoc** [indomus/forum#888] [HUB: Home Assistant]
sto tentando di tracciare un tag bluetoot. conosco il mac address ma una volta fleshato l'esp32 mi trova un altro mac, in oltre su home assistant lo rilevo soltanto come 1 dispositivo e nessuna entità... e sinceramente essendo la prima volta che mi ci metto non capisco cosa sto sbagliado
io l'ho configurato cosi come segue, qualcuno che ci capisce puo spiegarmi? grazie mille

```
captive_portal:
esp32_ble_tracker:

ble_client:
  - mac_address: DC:23:4D:25:EE:63
    id: TAG_AUTO
```
