### DISCUSSION TITLE
Automazioni: usare alexa come trigger è possibile?

### DISCUSSION THREAD

**Discussion by calcioscacchi** [indomus/forum#889] [HUB: Home Assistant]
Ciao a tutti, 

ho finalmente (e orgogliosamente, quasi autonomamente) configurato alexa su home assistant, domotizzato il climatizzatore tramire smartIR e broadlink, e aggiunto le mie echo a home asisstant tramite il media player di alexa.

Ora vorrei creare le automazioni che mi permettono di accendere il clima in determinate modalità.
Tuttavia, non so se sbaglio approccio, o se non ho cercato bene, non riesco a trovare nulla che utilizzi come trigger per l'automazione una frase di alexa. 

Quello che vorrei ottenere è che se io dico "Alexa, accendi pompa di calore" il condizionatore si accende in quella modalità, con una data temperatura e una determinata potenza dell'aria in uscita.

Quello che ho trovato tuttavia utilizza come trigger un altro sensore, e al massimo, posso dire ad alexa di attivare quella determinata scena come controllo (es. "alexa controlla se la luce è accesa).

Non è possibile utilizzare una frase di alexa come trigger?
Spero di essermi spiegato a dovere, chiedo scusa se esiste una guida in proposito ma io non l'ho trovata.

**Comment by snakuzzo** [comment]
non puoi... almeno che io sappia.
Questa cosa puoi farla creando ad esempio degli script (uno per ogni modalità che vorrai) che poi esporrai verso alexa...e poi su alexa crei delle routine ad hoc con delle frasi scelte da te che poi attiveranno gli script (che su Alexa vedrai come scene o routine)

**Reply by calcioscacchi** [reply]
Ok, grazie della risposta. Spero che un bel giorno qualcuno ci dia questa possibilità. 
La strada che tu indichi era il piano B. Sicuramente il mio limite è la fantasia, ma essendo che nella mia visione il trigger è la frase di alexa... cosa useresti come trigger per questa automazione (che poi richiamerò da alexa?) 
Grazie

**Reply by snakuzzo** [reply]
Te l'ho scritto prima. Ti faccio un ese mpio...così magari è più chiaro

Es.

Esponi verso alexa
script1 -> accendi_clima_freddo
scrip2 -> accendi_clima_caldo

Su Alexa crei delle routine digitando la frase con cui vuoi azionare script1 e la frase con cui vuoi azionare script2

**Reply by calcioscacchi** [reply]
ok non avevo capito, allora ci provo!

Alernativamente avevo pensato (ma non so se esiste la possibilità) di creare su alexa/HA dei device fittizzi da attivare con alexa. Lo stato di questi device fittizzi triggera l'automazione della pompa di calore.

**Reply by calcioscacchi** [reply]
Provato, e ci sono riuscito al 50%.
Non capisco come mai.... ho creato due script tramite interfaccia HA, uno che accende la pompa di calore, uno che spegne. 

Lo script che spegne è banale.

```
alias: Spegni_condizionatore_reparto_notte
sequence:
  - service: climate.turn_off
    target:
      entity_id: climate.daikin
mode: single
```

e funziona, sono anche riuscito a richiamarlo da alexa.

Ma quello che accende, anche se ho usato lo stesso metodo, non parte. LA cosa che mi fà più girare le... è che non parte nemmeno la prima sequenza, quella di accensione.

```
alias: Accendi_pompa_di_calore
sequence:
  - service: climate.turn_on
    target:
      entity_id: climate.daikin
  - service: climate.set_temperature
    target:
      entity_id: climate.daikin
    data:
      temperature: 30
  - service: climate.set_aux_heat
    target:
      entity_id: climate.daikin
    data:
      aux_heat: false
  - service: climate.set_fan_mode
    target:
      entity_id: climate.daikin
    data:
      fan_mode: High
mode: single
```


potrei capire il resto della configurazione, è la prima volta che provo, ci sta, avrei sperimentato... ma il fatto che il turn_off funzioni e il turn_on no... bho. Ho testato anche togliendo tutto il codice di configurazione, mantenendo solo l'istruzione di on.

**Reply by Larry-78** [reply]
Ciao @calcioscacchi
io in alcune mie automazioni utilizzo gli `input_boolean`
( i device fittizi a cui ti riferivi ) 
creati ad hoc ed esposti verso Alexa. Grazie alle routine e delle frasi specifiche, li attivo così triggerano le automazioni relative.

**Reply by calcioscacchi** [reply]
ciao @Larry-78 , avresti qualche esempio da cui trarre spunto?

**Reply by Larry-78** [reply]
Per esempio nel mio caso ho domotizzato tutte le tapparelle con Sonoff Dual tasmotizzati e anche creando un gruppo di tutte le tapparelle non sono mai riuscito ad impostare con alexa una percentuale contemporanea a tutto il gruppo ma solo singolarmente, quindi ho creato un'automazione utilizzando le Alexa actions ( se non sai cosa sono leggi [qui](https://github.com/keatontaylor/alexa-actions/wiki) )
in pratica se dico ad Alexa:" imposta tutte le tapparelle" 
lei mi risponde: "a quale percentuale vorresti impostarle?" 
poi basta dare un num da 0 a 100
Come prima cosa ho creato ed esposto verso Alexa `input_boolean.alexa_tapparelle`
poi ho creato le due automazioni

```yaml
alias: Impostazione Alexa tapparelle
trigger:
  - platform: state
    entity_id: input_boolean.alexa_tapparelle
    to: 'on'
action:
  - data_template:
      alexa_device: media_player.echo_show_di_lorenzo
      event_id: alexa_tapparelle
      text: A quale percentuale vorresti impostarle?
    service: script.activate_alexa_actionable_notification
mode: single


alias: Impostazione Alexa tapparelle 2
trigger:
  - platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: alexa_tapparelle
      event_response_type: ResponseNumeric
action:
  - service: cover.set_cover_position
    target:
      entity_id: all
    data:
      position: '{{ trigger.event.data.event_response }}'
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.alexa_tapparelle
mode: single
```
dopo si può creare la routine con Alexa per attivare `input_boolean` nel mio caso ho utilizzato la frase "Alexa, imposta tutte le tapparelle"
Come secondo servizio della seconda automazione conviene sempre utilizzare il `input_boolean.turn_off` perchè altrimenti rimarrebbe attivo.
Questo è il primo che mi è venuto in mente, poi ho fatto alcuni test sempre basati Alexa actions per gestire il cambio canali al mio TV o attivare il sistema di allarme con un codice personalizzato, posso capire se all'inizio potresti avere alcune difficoltà nella configurazione ma se hai superato quella di Alexa/HA ( suppongo gratuita con Haaska ) questa è nulla in confronto.
