### DISCUSSION TITLE
Ciclare "service" in automation su diverse entità

### DISCUSSION THREAD

**Discussion by andbad** [indomus/forum#892] [HUB: Home Assistant]
Ciao,
nel mio pacchetto per il controllo carichi, ho la necessità di fare diverse operazioni su molteplici entità che cambiano solo per una cifra.
Mi spiego meglio: questa è una serie di action di un'automazione
```
      - service: input_text.set_value
        data:
          entity_id: input_text.carico_1_potenza
          value: "{{ states('input_select.carico_1_potenza') }}"
      - service: input_text.set_value
        data:
          entity_id: input_text.carico_2_potenza
          value: "{{ states('input_select.carico_2_potenza') }}"
      - service: input_text.set_value
        data:
          entity_id: input_text.carico_3_potenza
          value: "{{ states('input_select.carico_3_potenza') }}"
  ....
```

E così via (fino a 20).
E' possibile usare un costrutto che richiami le varie entità variando solo il numero?
In sostanza qualcosa del tipo (**scritto male**...):
```
{% for counter = 1 to counter == 21 %}
      - service: input_text.set_value
        data:
          entity_id: input_text.carico_{{counter}}_potenza
          value: "{{ states('input_select.carico_{{counter}}_potenza') }}"
{% counter +=1 %}
{% endfor %}
```

By(t)e

**Comment by snakuzzo** [comment]
Cercando e leggendo la documentazione [QUI](https://www.home-assistant.io/docs/scripts/#while-loop) (cosa che bisognerebbe fare sempre come primo step), ho creato e testato questo package al volo...prendi spunto da qui...

```yaml
input_text:

  input1:
  input2:
  input3:
  input4:

script:

  prova_iterazione:
    sequence:
        repeat:
          while:
          - condition: template
            value_template: "{{ repeat.index < 5 }}"
          sequence:
          - service: input_text.set_value
            data:
              entity_id: input_text.input{{ repeat.index }}
              value: "{{ repeat.index }}000"
```

Ecco il risultato quando esegui lo script

![capture_2021-08-28_01-52](https://user-images.githubusercontent.com/7205371/137718917-a77ceb31-dfee-4ba5-91ff-7fa98066b4d9.png)

Ovviamente quello che fai in una sequence di uno script puoi farlo tranquillamente in un'automazione
