### DISCUSSION TITLE
Shelly Plug S switch unavailable

### DISCUSSION THREAD

**Discussion by tetionet** [indomus/forum#9] [HUB: Home Assistant]
Salve,
Sistema: home assistant (OS)
ho appena installato due plug-s; entrambi mi forniscono in maniera corretta tutte le misure, ma il primo (lavatrice) funziona correttamente anche come switch, il secondo mi dice "unavailable". Tramite terminale/broker riesco a ricevere tutte le informazioni necessarie; non riesco a fare una pub (purtroppo) perchè mi dice che "-m" è un unknown option

Cosa posso provare? Questa la configurazione.

```
switch:
  - platform: mqtt
    name: "1p_bagno_lavatrice_switch"
    state_topic: "shellies/shellyplug-s-1p-bagno-lavatrice/relay/0"
    command_topic: "shellies/shellyplug-s-1p-bagno-lavatrice/relay/0/command"
    availability_topic: "shellies/shellyplug-s-1p-bagno-lavatrice/online"
    qos: 1
    value_template: "{% if value == 'on' %} on {% else %} off {% endif %}" 
    payload_on: "on"
    payload_off: "off"
    payload_available: "true"
    payload_not_available: "false"
    optimistic: false
    retain: false
    
  - platform: mqtt
    name: "1p_bagno_asciugatrice_switch"
    state_topic: "shellies/shellyplug-s-1p-bagno-asciugatrice/relay/0"
    command_topic: "shellies/shellyplug-s-1p-bagno-asciugatrice/relay/0/command"
    availability_topic: "shellies/shellyplug-s-1p-bagno-asciugatrice/online"
    qos: 1
    value_template: "{% if value == 'on' %} on {% else %} off {% endif %}" 
    payload_on: "on"
    payload_off: "off"
    payload_available: "true"
    payload_not_available: "false"
    optimistic: false
    retain: false

sensor:
  - platform: mqtt
    name: "1p_Bagno_Lavatrice_watt"
    state_topic: "shellies/shellyplug-s-1p-bagno-lavatrice/relay/0/power"
    unit_of_measurement: "Watt"

  - platform: mqtt
    name: "1p_Bagno_Asciugatrice_watt"
    state_topic: "shellies/shellyplug-s-1p-bagno-asciugatrice/relay/0/power"
    unit_of_measurement: "Watt"
    

```
