### DISCUSSION TITLE
Sonoff rf bridge 433

### DISCUSSION THREAD

**Discussion by gntdvd** [indomus/forum#942] [HUB: Home Assistant]
Buongiorno, ho comprato questo dispositivo per ricevere i dati trasmessi dai sensori di un vecchio antifurto wireless e poterli gestire su HA. Dopo averlo aggiornato con tasmota ho iniziato a ricevere i codici in formato raw e adesso dovrei associarli ai vari dispositivi binari nel file configuration. yaml.
Essendo stringhe raw i dati sono del tipo : AA B1 03 01EA 03C0 0500 A0808180 55
Considerando che mi serve solo la parte  A0808180  come dato utile e che in fatto di programmazione sono veramente a zero, qualcuno saprebbe dirmi come fare a filtrarla dal resto?

Grazie

**Comment by snakuzzo** [comment]
Ciao.
se il sensore binario l'hai creato manualmente con platform mqtt e se quel valore che ti interessa è posizionato sempre com "sesta" stringa, puoi fare in modo che il sensore venga abbia come valore solo quella stringa estraendo dal payload MQTT solo quello che ti interessa

Se vai su "Strumenti sviluppatore" puoi testare direttamente l'estrazione della stringa in questo modo...

 ```python
{% set value = 'AA B1 03 01EA 03C0 0500 A0808180 55' %}

{{ value.split(' ')[6] }}
```

![2021-10-24_11-13](https://user-images.githubusercontent.com/7205371/138587798-cb75c95e-1514-4234-b802-c13c205d4359.png)


Comunque...fai vedere come hai creato le entità su HA e fai vedere un esempio "completo" di payload che viene pubblicato sul broker MQTT.

**Reply by gntdvd** [reply]
Eccoti il codice che ho "brutalmente " copiato inserendo nel payload solamente il codice rfraw che cambiando tutte le volte poi non mi attiva il dispositivo.

```yaml
binary_sensor:

- platform: mqtt
  name: "telecomando"
  off_delay: 1
  payload_on: "AA B1 03 01EA 03C0 0500 A0808180 55"
  payload_off: ""
  device_class: opening
  state_topic: "tele/smart/home/RESULT"
  value_template: "{{ value_json.RfReceived.Data }} %}}"
```

Esempio di MQTT :

```
09:49:19.447 MQT: tele/smart/home/RESULT = {"Time":"2021-10-24T09:49:19","RfRaw":{"Data":"AA B1 03 01EA 03C0 0500 A0808180 55"}}
```

Grazie per la velocissima e dettagliata risposta !!

**Reply by snakuzzo** [reply]
Innanzi tutto quando posti il codice dovresti usare il markdown (questa volta te l'ho corretto io, ma la prossima utilizzalo correttamente, altrimenti dovrò cancellare il post).

Poi...il payload che hai postato non è quello utilizzato per la valorizzazione del sensore binario. Nel template estrai il valore di `RfReceived.Data` che però non è presente nel payload che vedo nell'esempio (e questo mi porta a pensare che nel log di HA avrai sempre warning).

Altra cosa, non hai gestito il passaggio ad off del sensore binario ?

Spiegami a cosa ti serve solo quella stringa che dicevi prima, perché non ho capito lo scopo. Vuoi che alla pubblicazione di quel topic nell'esempio il sensore binario sia on ?

**Reply by gntdvd** [reply]
Scusami, non sapevo... diciamo che lo scopo è di creare un interruttore virtuale in HA legato ad ogni sensore dell'antifurto.
La disattivazione potrebbe essere automatica dopo un paio di secondi.
Vorrei poi fare un'automazione per gestire l'antifurto e la sirena direttamente da HA.

**Reply by snakuzzo** [reply]
La parte degli switch potresti gestirla tipo così..

```yaml
automation:

- id: sonoff_bridge_gestione_switch
  alias: Sonoff Bridge Gestione Switch
  trigger:
  - platform: state
    entity_id: switch.porta_carraia
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: switch.sbarra_garage
    from: 'off'
    to: 'on'
  action:
  - delay:
      seconds: 2
  - service: switch.turn_off
    data:
      entity_id: {{ trigger.entity_id }}
  mode: parallel


switch:

- platform: mqtt
  name: "Sbarra Garage"
  command_topic: "cmnd/sonoff-bridge/Backlog"
  payload_on: "RfRaw AA B1 03 01EA 03C0 0500 AAAAAAA  55"}}"
  availability_topic: "tele/sonoff-bridge/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  qos: 1
  retain: false

- platform: mqtt
  name: "Porta Carraia"
  command_topic: "cmnd/sonoff-bridge/Backlog"
  payload_on: "RfRaw AA B1 03 01EA 03C0 0500 BBBBBBB  55"}}"
  availability_topic: "tele/sonoff-bridge/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  qos: 1
  retain: false

```
