### DISCUSSION TITLE
Check condition

### DISCUSSION THREAD

**Discussion by domoticluca** [indomus/forum#944] [HUB: Home Assistant]
Ciao,
volevo creare uno script che mi riaccendeva i device che un'altro script aveva precedentemente spento.
Lo script dovrebbe funzionare come segue, se la somma di due sensori è minore di 3800, allora accende il device forno. 
Ma non capisco perchè quando verifica la condizione anche se vera va nel default.
Il propblema è probabilmente in questa parte di codice
```
          - condition: template
            value_template: >
              {{((states('sensor.din_power')|int +
              states('input_number.forno_memory_power_consumption')|int)<3800)}}"
```
il codice completo dovrebbe verificare 
se il device forno risulta spento , 
in quel caso se la somma dei valori  dei sensori "sensor.din_power" e "input_number.forno_memory_power_consumption" è minore di 3800 allora deve riattivare il device 
Il codice completo è il seguente:
```
alias: Turn on electrical devices
sequence:
  - choose:
      - conditions:
          - condition: device
            type: is_off
            device_id: 6590f71da2c692c18ec70648c140119c
            entity_id: switch.forno
            domain: switch
          - condition: template
            value_template: >
              {{((states('sensor.din_power')|int +
              states('input_number.forno_memory_power_consumption')|int)<3800)}}"
        sequence:
          - type: turn_on
            device_id: 6590f71da2c692c18ec70648c140119c
            entity_id: switch.forno
            domain: switch
    default: []
mode: single
icon: mdi:current-ac
```

**Comment by snakuzzo** [comment]
Per favore usa il markdown per il codice...così non si capisce nulla.
Grazie

**Reply by domoticluca** [reply]
Aggiornato :)

**Reply by snakuzzo** [reply]
Posso consigliarti di rivedere tutta la logica ?
Io gestirei tutto (spegnimento e accensione) con una singola automazione (e non con uno script a se stante).
Altro suggerimento, non usare i device, ma direttamente le entità con le chiamate ai servizi.

Esponi l'esigenza completa e vediamo se si può organizzare meglio

**Reply by domoticluca** [reply]
Allora provo a dirti che impostazione ho dato e a quale scopo:
ho un'automazione che fa da monitor, in pratica funziona così:
Se: la potenza letta dal modulo DIN supera una certa soglia
      1. Avvia i servizi di notifica
      2. Entra in un ciclo while che lancia uno script per staccare i carichi 
          2.1 Lo script stacca un carico alla volta secondo delle priorità definite e ne memorizza l'ultimo valore di assorbimento
          2.2 Se l'assorbimento totale è sotto una certa soglia termina il ciclo while altrimenti viene rilanciato lo script per staccare un altro carico
         2.3 Una volta uscito dal while aspetta 30 min e poi lancia uno script per riattivare i carichi
         2.4 Lo script per riattivare i carichi valuta la somma dell'attuale consumo più l'ultimo consumo registrato del carico staccato, e se al di sotto della soglia riattiva il carico, se al di sopra aspetta un certo tempo per riprovarci.

Ecco, io sono bloccato alla parte 2.4

perchè questa parte di codice quando verifica la condizione anche se vera va nel default.
```
          - condition: template
            value_template: >
              {{((states('sensor.din_power')|int +
              states('input_number.forno_memory_power_consumption')|int)<3800)}}"
```

**Reply by snakuzzo** [reply]
Considera che le condition nella choose devono essere entrambe verificate.
Nella condition del template hai messo dei doppi apici alla fine ma non all'inizio, magari gli danno fastidio
Inoltre...hai provato a non usare il device ma l'entità ?

```yaml
- condition: state
  entity_id: switch.forno
  state: 'off'
- condition: template
  value_template: "{{ ( (states('sensor.din_power') | int + states('input_number.forno_memory_power_consumption') | int ) < 3800 ) }}"
```
