### DISCUSSION TITLE
Duck dns

### DISCUSSION THREAD

**Discussion by antonio7319** [indomus/forum#950] [GENERALE - Discussioni generiche]
Ciao a tutti dopo vari sbattimenti non riuscendo ad installare home Assistant su un raspberry (mi dava errore until kernel) ho provato ad installarlo su di un Intel nuc, ha funzionato tutto rilevato i dispositivi,
Installato mosquito il terminale hacs e duck dns e qui il problema ,
Sul sito ho creato un dominio poi nel fle config di duck dns ho incollato il token ed il dominio 
Ma mi da errore e non capisco dove sbaglio,
Incollo il log di duck

**Comment by snakuzzo** [comment]
Sistema i log utilizzando il markdown altrimenti dovremo cancellare il post. Grazie

**Reply by antonio7319** [reply]
Non capisco cosa devo sistemare

**Reply by snakuzzo** [reply]
Quello che hai scritto... blocchi di codice o log vanno scritti utilizzando il markdown. Leggi il regolamento

**Reply by antonio7319** [reply]
Ho cancellato il log stassera provo a postarlo con il markdown (se riesco non so nemmeno cosa sia)

**Reply by snakuzzo** [reply]
leggi [QUI](https://github.com/indomus/forum/blob/main/README.md)

**Comment by antonio7319** [comment]
spero di avere postato il log in modo corretto,
ho aggiunto le prime 3 righe al Configuration yaml come da guida 
ma non riesco più a collegarmi in locale solo https,


```yaml
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Text to speech
tts:
  - platform: google_translate
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```

vi posto 2 righe del log di DuckDNS che mi da errore
WARNING: KO

questo ogni 5 minuti
poi questa riga 

```
INFO: Renew certificate for domains: Xxxxxxxxxx.duckdns.org and aliases:
```
