### DISCUSSION TITLE
Zigbee2mqtt, installazione non riuscita

### DISCUSSION THREAD

**Discussion by calcioscacchi** [indomus/forum#965] [HUB: Home Assistant]
Salve, ho seguito le varie guide per utilizzare il zigbee2mqtt su HA core via docker, ma la procedura non è andata a buon fine. 
Durante l'installazione, non sono stati rilevati intoppi, ma se provo ad accedere all'interfaccia, il browser mi da errore di connection_refused.

Inoltre, su Home Asisstant non compare l'add-on di Z2M.

Qui il file di configurazione, dove ho appurato che la porta indicata è la 8080 (a logica, mi viene da dire che l'errore sta qui da qualche parte...)

```
  # Autodiscovery su Home Assistant abilitato
homeassistant: true
# Join alla rete MQTT disabilitato di default
permit_join: false
# MQTT settings
mqtt:
  # MQTT base topic per i messaggi di zigbee2mqtt
  base_topic: zigbee2mqtt
  # MQTT server - URL (indirizzo LAN)
  server: 'mqtt://localhost'
  # MQTT server - Parametri di autenticazione (decommentare e popolare correttamente se si utilizzano credenziali per la connessione al broker MQTT
   user: USERNAME
   password: PWD
serial:
  # Porta su cui è mappata l'antennza zigbee
  port: /dev/ttyACM0
advanced:
  # Directory in cui verrà salvato il file di log
  log_directory: /var/log
experimental:
  # abilita le nuove API e l'esposizione della webGUI
  new_api: true
frontend:
  # porta su cui verrà esposta la webGUI
  port: 8080
```

ho provato a togliere gli apici da mqtt://localhost (uso mosquitto come broker), ma stesso esito.
