### DISCUSSION TITLE
502: Bad Gateway

### DISCUSSION THREAD

**Discussion by Dregi56** [indomus/forum#97] [HUB: Home Assistant]
In Hassio ho installato Node-red e SSH & Web Terminal, entrambi mi danno _502: Bad Gateway_ se tento di aprirli.
La configurazione di Node-red:
```
credential_secret: ''
dark_mode: false
http_node:
  username: ''
  password: ''
http_static:
  username: ''
  password: ''
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: true
system_packages: []
npm_packages: []
init_commands: []
```

quella di SSH:
```
ssh:
  username: root
  password: xxxxxxx
  authorized_keys: []
  sftp: true
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: true
zsh: true
share_sessions: true
packages:
  - '-build-base'
init_commands:
  - '-ls -la'
  ```
Ho letto in giro per la rete di questo errore e sembra abbia a che fare col firewal, è così? Nel caso, non ho trovato soluzione, come posso rimediare?
