### DISCUSSION TITLE
Attivazioni a due orari nella stessa giornata

### DISCUSSION THREAD

**Discussion by nromagna** [indomus/forum#992] [HUB: Home Assistant]
Ciao a tutti, presumo che creare due automazioni uguali non ha senso, gentilmente vi chiedo come posso impostare in un'unica automazione due orari nella giornata, cioè che si attivi solo dalle 08.00 alle 10.00 e dalle 14.00 alle 16.00.
Se non mi son capito son qua :)

**Comment by snakuzzo** [comment]
Specifica meglio la richiesta...ti riferisci alla condizione o al trigger ?
Da come hai scritto...credo tu ti riferisca ad una condizione. Quindi dovresti metterne due in OR, seguendo la documentazione [QUI](https://www.home-assistant.io/docs/scripts/conditions/#or-condition)

**Comment by nromagna** [comment]
Certo, scusami.
Che il sensore di movimento "binary_sensor.sonoff_xxx" funzioni in sole due fasce di orari:

```
alias: Mov Cucina
description: ''
trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.sonoff_xxx

condition:
  - condition: time
    after: '05:00'
    before: '08:30'
  - condition: or
    conditions:
      - condition: time
        after: '18:00'
        before: '20:30'

action:
  - service: light.turn_on
    target:
      entity_id:
        - light.tavola
        - light.gialla
    data:
      brightness_pct: 85
mode: restart
```

**Reply by snakuzzo** [reply]
La OR è sbagliata... non si scrive come hai fatto tu, ma così...

```yaml
- id: mov_cucina
  alias: "Mov Cucina"
  trigger:
  - platform: state
    entity_id: binary_sensor.sonoff_xxx
    from: 'off'
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: time
      after: '18:00'
      before: '20:30'
    - condition: time
      after: '05:00'
      before: '08:30'
action:
- service: light.turn_on
  target:
    entity_id:
    - light.tavola
    - light.gialla
  data:
    brightness_pct: 85
mode: restart
```
